function evidence = helperAnalyzeSyntheticTargetEvidence(mapLinear, ...
    delayAxis_s, dopplerAxis_Hz, scenarioTruth, context)
%HELPERANALYZESYNTHETICTARGETEVIDENCE Measure truth-aligned map evidence.
%
%   This helper is post-hoc by design. The map and axes must already exist;
%   scenario truth is used only to define uncertainty-aware evaluation
%   regions after truth-blind map formation.

arguments
    mapLinear (:,:) {mustBeNumeric, mustBeReal, mustBeNonnegative}
    delayAxis_s {mustBeNumeric, mustBeReal}
    dopplerAxis_Hz {mustBeNumeric, mustBeReal}
    scenarioTruth (1,1) struct
    context (1,1) struct
end

delayAxis_s = double(delayAxis_s(:).');
dopplerAxis_Hz = double(dopplerAxis_Hz(:));
mapLinear = max(single(mapLinear), eps("single"));
localValidateMapContract(mapLinear, delayAxis_s, dopplerAxis_Hz);
resolvedContext = localResolveContext(context);
truthBundle = localResolveTruthBundle(scenarioTruth);
[targetRows, regionViews] = localMeasureTargets(mapLinear, delayAxis_s, ...
    dopplerAxis_Hz, truthBundle, resolvedContext);

if isempty(targetRows)
    targetTable = localEmptyTargetTable();
    evidenceLabel = "no_truth_targets_in_map_window";
    minimumProminence_dB = NaN;
    maximumCoordinateError_bins = NaN;
else
    targetTable = struct2table(targetRows);
    evidenceLabel = "target_evidence_characterized_no_cutoff";
    minimumProminence_dB = min(targetTable.LocalProminence_dB);
    maximumCoordinateError_bins = max(targetTable.CoordinateError_bins);
end

evidence = struct();
evidence.Status = evidenceLabel;
evidence.TargetCount = height(targetTable);
evidence.MinimumLocalProminence_dB = minimumProminence_dB;
evidence.MaximumCoordinateError_bins = maximumCoordinateError_bins;
evidence.TargetTable = targetTable;
evidence.TargetRegionViews = regionViews;
evidence.MapOrientation = "rows_doppler_columns_delay";
evidence.ClaimBoundary = ...
    "post_hoc_target_region_evidence_not_detection";

end

function localValidateMapContract(mapLinear, delayAxis_s, dopplerAxis_Hz)

if size(mapLinear, 2) ~= numel(delayAxis_s) || ...
        size(mapLinear, 1) ~= numel(dopplerAxis_Hz)
    error("helperAnalyzeSyntheticTargetEvidence:MapAxisMismatch", ...
        "Map columns must match delay and map rows must match Doppler.");
end

if any(~isfinite(mapLinear), "all") || any(~isfinite(delayAxis_s)) || ...
        any(~isfinite(dopplerAxis_Hz))
    error("helperAnalyzeSyntheticTargetEvidence:NonfiniteMap", ...
        "Map values and axes must be finite.");
end

if any(diff(delayAxis_s) <= 0) || any(diff(dopplerAxis_Hz) <= 0)
    error("helperAnalyzeSyntheticTargetEvidence:NonmonotonicAxes", ...
        "Delay and Doppler axes must be strictly increasing.");
end

end

function context = localResolveContext(inputContext)

requiredFields = [ ...
    "NativeSampleRateHz"; ...
    "MapSampleRateHz"; ...
    "PartStartOffset_s"; ...
    "CpiStart_s"; ...
    "CpiDuration_s"; ...
    "DirectPathDelay_s"; ...
    "DirectPathDoppler_Hz"; ...
    "LagUncertainty_samples"; ...
    "ResidualFrequencyUncertainty_Hz" ...
    ];

for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);

    if ~isfield(inputContext, fieldName)
        error("helperAnalyzeSyntheticTargetEvidence:MissingContextField", ...
            "Context is missing %s.", fieldName);
    end
end

context = inputContext;
context.CandidateName = localStringField(inputContext, ...
    "CandidateName", "baseline");
context.Repetition = localDoubleField(inputContext, "Repetition", NaN);
context.CpiLabel = localStringField(inputContext, "CpiLabel", "");
context.WindowLabel = localStringField(inputContext, "WindowLabel", "");
context.DelaySignForMap = localDoubleField(inputContext, ...
    "DelaySignForMap", -1.0);
context.DopplerSignForMap = localDoubleField(inputContext, ...
    "DopplerSignForMap", -1.0);

end

function truthBundle = localResolveTruthBundle(scenarioTruth)

if isfield(scenarioTruth, "truth_bundle")
    truthBundle = scenarioTruth.truth_bundle;
else
    truthBundle = scenarioTruth;
end

requiredFields = ["radar_epoch_utc"; "bistatic_tracks"];

for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);

    if ~isfield(truthBundle, fieldName)
        error("helperAnalyzeSyntheticTargetEvidence:InvalidTruthBundle", ...
            "Scenario truth is missing %s.", fieldName);
    end
end

end

function [targetRows, regionViews] = localMeasureTargets(mapLinear, ...
    delayAxis_s, dopplerAxis_Hz, truthBundle, context)

tracks = truthBundle.bistatic_tracks(:);
targetRows = repmat(localTargetRowTemplate(), numel(tracks), 1);
regionViews = repmat(localRegionViewTemplate(), numel(tracks), 1);
measuredTargetCount = 0;
windowStart_s = double(context.PartStartOffset_s) + ...
    double(context.CpiStart_s);
windowStop_s = windowStart_s + double(context.CpiDuration_s);
delaySpacing_s = median(abs(diff(delayAxis_s)));
dopplerSpacing_Hz = median(abs(diff(dopplerAxis_Hz)));
delayResolution_s = 1.0 ./ double(context.MapSampleRateHz);
dopplerResolution_Hz = 1.0 ./ double(context.CpiDuration_s);
backgroundAnnulusResolutionWidths = 4.0;
speedOfLight_mps = physconst("LightSpeed");

for targetIndex = 1:numel(tracks)
    track = tracks(targetIndex);
    relativeTimes_s = double(track.t_utc(:)) - ...
        double(truthBundle.radar_epoch_utc);
    rangeExcess_m = double(track.R_excess_m(:));
    bistaticDoppler_Hz = double(track.f_D_hz(:));
    validMask = relativeTimes_s >= windowStart_s & ...
        relativeTimes_s < windowStop_s & ...
        isfinite(rangeExcess_m) & isfinite(bistaticDoppler_Hz);

    if ~any(validMask)
        continue
    end

    truthTimes_s = relativeTimes_s(validMask);
    truthDelay_s = rangeExcess_m(validMask) ./ speedOfLight_mps;
    truthDoppler_Hz = bistaticDoppler_Hz(validMask);
    expectedDisplayDelayVector_s = ...
        context.DelaySignForMap .* truthDelay_s;
    expectedDisplayDopplerVector_Hz = ...
        context.DopplerSignForMap .* truthDoppler_Hz;
    expectedDelayVector_s = expectedDisplayDelayVector_s + ...
        double(context.DirectPathDelay_s);
    expectedDopplerVector_Hz = context.DopplerSignForMap .* ...
        truthDoppler_Hz + double(context.DirectPathDoppler_Hz);
    expectedDelay_s = median(expectedDelayVector_s, "omitnan");
    expectedDoppler_Hz = median(expectedDopplerVector_Hz, "omitnan");
    delayMotionSpan_s = max(expectedDelayVector_s) - ...
        min(expectedDelayVector_s);
    delayMotionHalfExtent_s = delayMotionSpan_s ./ 2.0;
    dopplerMotionSpan_Hz = max(expectedDopplerVector_Hz) - ...
        min(expectedDopplerVector_Hz);
    dopplerMotionHalfExtent_Hz = dopplerMotionSpan_Hz ./ 2.0;
    lagUncertainty_s = abs(double(context.LagUncertainty_samples)) ./ ...
        double(context.NativeSampleRateHz);
    frequencyUncertainty_Hz = abs( ...
        double(context.ResidualFrequencyUncertainty_Hz));
    searchDelayHalfExtent_s = delaySpacing_s ./ 2.0 + ...
        delayMotionHalfExtent_s + lagUncertainty_s;
    searchDopplerHalfExtent_Hz = dopplerSpacing_Hz ./ 2.0 + ...
        dopplerMotionHalfExtent_Hz + frequencyUncertainty_Hz;
    searchMask = abs(delayAxis_s - expectedDelay_s) <= ...
        searchDelayHalfExtent_s & ...
        abs(dopplerAxis_Hz - expectedDoppler_Hz) <= ...
        searchDopplerHalfExtent_Hz;
    searchIndices = find(searchMask);

    if isempty(searchIndices)
        continue
    end

    [targetPeakPower, localPeakIndex] = max(mapLinear(searchMask));
    associatedLinearIndex = searchIndices(localPeakIndex);
    [associatedRow, associatedColumn] = ind2sub(size(mapLinear), ...
        associatedLinearIndex);
    associatedDelay_s = delayAxis_s(associatedColumn);
    associatedDoppler_Hz = dopplerAxis_Hz(associatedRow);
    backgroundGuardDelayHalfExtent_s = searchDelayHalfExtent_s + ...
        delayResolution_s;
    backgroundGuardDopplerHalfExtent_Hz = ...
        searchDopplerHalfExtent_Hz + dopplerResolution_Hz;
    backgroundOuterDelayHalfExtent_s = ...
        backgroundGuardDelayHalfExtent_s + ...
        backgroundAnnulusResolutionWidths .* delayResolution_s;
    backgroundOuterDopplerHalfExtent_Hz = ...
        backgroundGuardDopplerHalfExtent_Hz + ...
        backgroundAnnulusResolutionWidths .* dopplerResolution_Hz;
    backgroundGuardMask = ...
        abs(delayAxis_s - expectedDelay_s) <= ...
        backgroundGuardDelayHalfExtent_s & ...
        abs(dopplerAxis_Hz - expectedDoppler_Hz) <= ...
        backgroundGuardDopplerHalfExtent_Hz;
    outerMask = abs(delayAxis_s - expectedDelay_s) <= ...
        backgroundOuterDelayHalfExtent_s & ...
        abs(dopplerAxis_Hz - expectedDoppler_Hz) <= ...
        backgroundOuterDopplerHalfExtent_Hz;
    backgroundValues = double(mapLinear( ...
        outerMask & ~backgroundGuardMask));

    if isempty(backgroundValues)
        backgroundValues = double(mapLinear(~backgroundGuardMask));
    end

    localMedianPower = max(median(backgroundValues, "omitnan"), eps);
    localProminence_dB = 10.0 .* log10( ...
        double(targetPeakPower) ./ localMedianPower);
    delayError_bins = abs(associatedDelay_s - expectedDelay_s) ./ ...
        delaySpacing_s;
    dopplerError_bins = ...
        abs(associatedDoppler_Hz - expectedDoppler_Hz) ./ ...
        dopplerSpacing_Hz;
    targetId = localTrackString(track, "hex", ...
        "target_" + string(targetIndex));
    callsign = localTrackString(track, "callsign", "");
    sourceCaseId = localTrackString(track, "source_case_id", "");
    injectionGain_dB = localTrackDouble(track, ...
        "injection_gain_db", NaN);
    targetPowerRelativeToBackground_dB = localTrackDouble(track, ...
        "target_power_relative_to_background_db", NaN);
    measuredTargetCount = measuredTargetCount + 1;
    targetRows(measuredTargetCount, 1) = struct( ...
        "CandidateName", context.CandidateName, ...
        "Repetition", double(context.Repetition), ...
        "CpiLabel", context.CpiLabel, ...
        "WindowLabel", context.WindowLabel, ...
        "SourceCaseId", sourceCaseId, ...
        "TargetId", targetId, ...
        "Callsign", callsign, ...
        "InjectionGain_dB", injectionGain_dB, ...
        "TargetPowerRelativeToBackground_dB", ...
        targetPowerRelativeToBackground_dB, ...
        "TruthTime_s", median(truthTimes_s, "omitnan"), ...
        "TruthPointCount", double(nnz(validMask)), ...
        "ExpectedDisplayDelay_s", median( ...
        expectedDisplayDelayVector_s, "omitnan"), ...
        "ExpectedDisplayDoppler_Hz", median( ...
        expectedDisplayDopplerVector_Hz, "omitnan"), ...
        "ExpectedDelay_s", expectedDelay_s, ...
        "ExpectedDoppler_Hz", expectedDoppler_Hz, ...
        "AssociatedDelay_s", associatedDelay_s, ...
        "AssociatedDoppler_Hz", associatedDoppler_Hz, ...
        "DelayError_bins", delayError_bins, ...
        "DopplerError_bins", dopplerError_bins, ...
        "CoordinateError_bins", hypot(delayError_bins, ...
        dopplerError_bins), ...
        "TargetLevel_dB", 10.0 .* log10(double(targetPeakPower)), ...
        "LocalMedian_dB", 10.0 .* log10(localMedianPower), ...
        "LocalProminence_dB", localProminence_dB, ...
        "DelayMotionSpan_s", delayMotionSpan_s, ...
        "DopplerMotionSpan_Hz", dopplerMotionSpan_Hz, ...
        "SearchDelayHalfExtent_s", searchDelayHalfExtent_s, ...
        "SearchDopplerHalfExtent_Hz", searchDopplerHalfExtent_Hz, ...
        "BackgroundGuardDelayHalfExtent_s", ...
        backgroundGuardDelayHalfExtent_s, ...
        "BackgroundGuardDopplerHalfExtent_Hz", ...
        backgroundGuardDopplerHalfExtent_Hz, ...
        "BackgroundOuterDelayHalfExtent_s", ...
        backgroundOuterDelayHalfExtent_s, ...
        "BackgroundOuterDopplerHalfExtent_Hz", ...
        backgroundOuterDopplerHalfExtent_Hz, ...
        "MapDelaySpacing_s", delaySpacing_s, ...
        "MapDopplerSpacing_Hz", dopplerSpacing_Hz, ...
        "AssociatedDelayBin", double(associatedColumn), ...
        "AssociatedDopplerBin", double(associatedRow), ...
        "TargetLevelChangeFromNone_dB", NaN, ...
        "LocalProminenceChangeFromNone_dB", NaN, ...
        "DelayCoordinateChangeFromNone_samples", NaN, ...
        "DopplerCoordinateChangeFromNone_Hz", NaN, ...
        "CoordinateChangeFromNone_bins", NaN, ...
        "WithinPhysicsSearchRegion", true, ...
        "TruthUsedPostHoc", true, ...
        "DetectionClaimed", false, ...
        "EvidenceLabel", "descriptive_no_cutoff");
    regionViews(measuredTargetCount, 1) = localBuildRegionView(mapLinear, ...
        delayAxis_s, dopplerAxis_Hz, outerMask, associatedRow, ...
        associatedColumn, expectedDelay_s, expectedDoppler_Hz, targetId, ...
        callsign, sourceCaseId, injectionGain_dB, context);
end

targetRows = targetRows(1:measuredTargetCount);
regionViews = regionViews(1:measuredTargetCount);

end

function regionView = localBuildRegionView(mapLinear, delayAxis_s, ...
    dopplerAxis_Hz, outerMask, associatedRow, associatedColumn, ...
    expectedDelay_s, expectedDoppler_Hz, targetId, callsign, ...
    sourceCaseId, injectionGain_dB, context)

[regionRows, regionColumns] = find(outerMask);
rowIndices = min(regionRows):max(regionRows);
columnIndices = min(regionColumns):max(regionColumns);
regionLinear = mapLinear(rowIndices, columnIndices);
regionView = localRegionViewTemplate();
regionView.TargetId = targetId;
regionView.Callsign = callsign;
regionView.CandidateName = context.CandidateName;
regionView.SourceCaseId = sourceCaseId;
regionView.InjectionGain_dB = injectionGain_dB;
regionView.Repetition = double(context.Repetition);
regionView.CpiLabel = context.CpiLabel;
regionView.WindowLabel = context.WindowLabel;
regionView.Map_dB = 10.0 .* log10( ...
    double(max(regionLinear, eps("single"))));
regionView.DelayAxis_s = delayAxis_s(columnIndices);
regionView.DopplerAxis_Hz = dopplerAxis_Hz(rowIndices);
regionView.ExpectedDelay_s = expectedDelay_s;
regionView.ExpectedDoppler_Hz = expectedDoppler_Hz;
regionView.AssociatedDelay_s = delayAxis_s(associatedColumn);
regionView.AssociatedDoppler_Hz = dopplerAxis_Hz(associatedRow);

end

function row = localTargetRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "Repetition", NaN, ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "SourceCaseId", "", ...
    "TargetId", "", ...
    "Callsign", "", ...
    "InjectionGain_dB", NaN, ...
    "TargetPowerRelativeToBackground_dB", NaN, ...
    "TruthTime_s", NaN, ...
    "TruthPointCount", NaN, ...
    "ExpectedDisplayDelay_s", NaN, ...
    "ExpectedDisplayDoppler_Hz", NaN, ...
    "ExpectedDelay_s", NaN, ...
    "ExpectedDoppler_Hz", NaN, ...
    "AssociatedDelay_s", NaN, ...
    "AssociatedDoppler_Hz", NaN, ...
    "DelayError_bins", NaN, ...
    "DopplerError_bins", NaN, ...
    "CoordinateError_bins", NaN, ...
    "TargetLevel_dB", NaN, ...
    "LocalMedian_dB", NaN, ...
    "LocalProminence_dB", NaN, ...
    "DelayMotionSpan_s", NaN, ...
    "DopplerMotionSpan_Hz", NaN, ...
    "SearchDelayHalfExtent_s", NaN, ...
    "SearchDopplerHalfExtent_Hz", NaN, ...
    "BackgroundGuardDelayHalfExtent_s", NaN, ...
    "BackgroundGuardDopplerHalfExtent_Hz", NaN, ...
    "BackgroundOuterDelayHalfExtent_s", NaN, ...
    "BackgroundOuterDopplerHalfExtent_Hz", NaN, ...
    "MapDelaySpacing_s", NaN, ...
    "MapDopplerSpacing_Hz", NaN, ...
    "AssociatedDelayBin", NaN, ...
    "AssociatedDopplerBin", NaN, ...
    "TargetLevelChangeFromNone_dB", NaN, ...
    "LocalProminenceChangeFromNone_dB", NaN, ...
    "DelayCoordinateChangeFromNone_samples", NaN, ...
    "DopplerCoordinateChangeFromNone_Hz", NaN, ...
    "CoordinateChangeFromNone_bins", NaN, ...
    "WithinPhysicsSearchRegion", false, ...
    "TruthUsedPostHoc", false, ...
    "DetectionClaimed", false, ...
    "EvidenceLabel", "" ...
    );

end

function tableOut = localEmptyTargetTable()

tableOut = struct2table(repmat(localTargetRowTemplate(), 0, 1));

end

function view = localRegionViewTemplate()

view = struct( ...
    "TargetId", "", ...
    "Callsign", "", ...
    "CandidateName", "", ...
    "SourceCaseId", "", ...
    "InjectionGain_dB", NaN, ...
    "Repetition", NaN, ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "Map_dB", single([]), ...
    "DelayAxis_s", [], ...
    "DopplerAxis_Hz", [], ...
    "ExpectedDelay_s", NaN, ...
    "ExpectedDoppler_Hz", NaN, ...
    "AssociatedDelay_s", NaN, ...
    "AssociatedDoppler_Hz", NaN ...
    );

end

function value = localStringField(inputStruct, fieldName, defaultValue)

value = defaultValue;

if isfield(inputStruct, fieldName)
    value = string(inputStruct.(fieldName));
end

end

function value = localDoubleField(inputStruct, fieldName, defaultValue)

value = defaultValue;

if isfield(inputStruct, fieldName)
    value = double(inputStruct.(fieldName));
end

end

function value = localTrackString(track, fieldName, defaultValue)

value = defaultValue;

if isfield(track, fieldName)
    value = string(track.(fieldName));
end

end

function value = localTrackDouble(track, fieldName, defaultValue)

value = double(defaultValue);

if isfield(track, fieldName) && ~isempty(track.(fieldName))
    value = double(track.(fieldName));
end

end
