function metadataInfo = helperReadCollectionMetadata(metadataPath, datasetId)
%HELPERREADCOLLECTIONMETADATA Read dataset-local manual collection metadata.

arguments
    metadataPath (1,1) string
    datasetId (1,1) string
end

metadataInfo = localBuildEmptyMetadataInfo(metadataPath, datasetId);

if ~isfile(metadataPath)
    return
end

try
    rawMetadata = jsondecode(fileread(metadataPath));
catch readException
    error("helperReadCollectionMetadata:ReadFailed", ...
        "Failed to read collection metadata %s: %s", metadataPath, ...
        readException.message);
end

metadataInfo.MetadataPresent = true;
metadataInfo.SessionId = localGetFieldText(rawMetadata, "session_id");
metadataInfo.SessionIdMatches = strlength(metadataInfo.SessionId) > 0 && ...
    metadataInfo.SessionId == string(datasetId);
metadataInfo.MetadataSource = localGetFieldText(rawMetadata, ...
    "metadata_source");
metadataInfo.ReferenceChannel = localNormalizeChannelMetadata(rawMetadata, ...
    "reference_channel");
metadataInfo.SurveillanceChannel = localNormalizeChannelMetadata( ...
    rawMetadata, "surveillance_channel");
metadataInfo.SiteContext = localNormalizeSiteContext(rawMetadata);
metadataInfo.AcquisitionControls = localNormalizeAcquisitionControls( ...
    rawMetadata);

end

function metadataInfo = localBuildEmptyMetadataInfo(metadataPath, datasetId)

metadataInfo = struct();
metadataInfo.MetadataPath = string(metadataPath);
metadataInfo.MetadataPresent = false;
metadataInfo.DatasetId = string(datasetId);
metadataInfo.SessionId = "";
metadataInfo.SessionIdMatches = false;
metadataInfo.MetadataSource = "";
metadataInfo.ReferenceChannel = localBuildEmptyChannelMetadata();
metadataInfo.SurveillanceChannel = localBuildEmptyChannelMetadata();
metadataInfo.SiteContext = struct( ...
    "SiteRegion", "", ...
    "SurveillanceBoresightDescription", "", ...
    "ExpectedAirTrafficNote", "", ...
    "IlluminatorNote", "", ...
    "ReceiverLocationNote", "", ...
    "ObstructionsOrClutterNote", "");
metadataInfo.AcquisitionControls = struct( ...
    "GainMappingNote", "", ...
    "GainModeNote", "", ...
    "LockStatusNote", "", ...
    "OverrunNote", "", ...
    "ChannelMappingVerificationNote", "", ...
    "OperatorNotes", "");

end

function channelMetadata = localBuildEmptyChannelMetadata()

channelMetadata = struct( ...
    "ChannelLabel", "", ...
    "N320Section", "", ...
    "Port", "", ...
    "Role", "", ...
    "AntennaName", "", ...
    "AntennaType", "", ...
    "AntennaTunedFrequencyHz", "", ...
    "Manufacturer", "", ...
    "Model", "", ...
    "NominalFrequencyRange", "", ...
    "GainDbi", "", ...
    "PublishedProductGainNote", "", ...
    "PublishedNoiseFigureNote", "", ...
    "PublishedImpedanceOhm", "", ...
    "PublishedMaxOutputLevelNote", "", ...
    "PublishedPowerRequirement", "", ...
    "PublishedOperatingTemperatureNote", "", ...
    "Polarization", "", ...
    "BeamwidthDeg", "", ...
    "MountHeightM", "", ...
    "BoresightAzimuthDeg", "", ...
    "ElevationTiltDeg", "", ...
    "CableType", "", ...
    "CableLengthM", "", ...
    "CableLengthFt", "", ...
    "PreampOrAttenuator", "", ...
    "Notes", "");

end

function channelMetadata = localNormalizeChannelMetadata(rawMetadata, ...
    channelFieldName)

channelMetadata = localBuildEmptyChannelMetadata();
channelAssignments = localGetStructField(rawMetadata, "channel_assignments");
channelStruct = localGetStructField(channelAssignments, channelFieldName);
channelMetadata.ChannelLabel = localGetFieldText(channelStruct, ...
    "channel_label");
channelMetadata.N320Section = localGetFieldText(channelStruct, ...
    "n320_section");
channelMetadata.Port = localGetFieldText(channelStruct, "port");
channelMetadata.Role = localGetFieldText(channelStruct, "role");
channelMetadata.AntennaName = localGetFieldText(channelStruct, ...
    "antenna_name");
channelMetadata.AntennaType = localGetFieldText(channelStruct, ...
    "antenna_type");
channelMetadata.AntennaTunedFrequencyHz = localGetFieldText(channelStruct, ...
    "antenna_tuned_frequency_hz");
channelMetadata.Manufacturer = localGetFieldText(channelStruct, ...
    "manufacturer");
channelMetadata.Model = localGetFieldText(channelStruct, "model");
channelMetadata.NominalFrequencyRange = localGetFieldText(channelStruct, ...
    "nominal_frequency_range");
channelMetadata.GainDbi = localGetFieldText(channelStruct, "gain_dbi");
channelMetadata.PublishedProductGainNote = localGetFieldText(channelStruct, ...
    "published_product_gain_note");
channelMetadata.PublishedNoiseFigureNote = localGetFieldText(channelStruct, ...
    "published_noise_figure_note");
channelMetadata.PublishedImpedanceOhm = localGetFieldText(channelStruct, ...
    "published_impedance_ohm");
channelMetadata.PublishedMaxOutputLevelNote = localGetFieldText( ...
    channelStruct, "published_max_output_level_note");
channelMetadata.PublishedPowerRequirement = localGetFieldText(channelStruct, ...
    "published_power_requirement");
channelMetadata.PublishedOperatingTemperatureNote = localGetFieldText( ...
    channelStruct, "published_operating_temperature_note");
channelMetadata.Polarization = localGetFieldText(channelStruct, ...
    "polarization");
channelMetadata.BeamwidthDeg = localGetFieldText(channelStruct, ...
    "beamwidth_deg");
channelMetadata.MountHeightM = localGetFieldText(channelStruct, ...
    "mount_height_m");
channelMetadata.BoresightAzimuthDeg = localGetFieldText(channelStruct, ...
    "boresight_azimuth_deg");
channelMetadata.ElevationTiltDeg = localGetFieldText(channelStruct, ...
    "elevation_tilt_deg");
channelMetadata.CableType = localGetFieldText(channelStruct, "cable_type");
channelMetadata.CableLengthM = localGetFieldText(channelStruct, ...
    "cable_length_m");
channelMetadata.CableLengthFt = localGetFieldText(channelStruct, ...
    "cable_length_ft");
channelMetadata.PreampOrAttenuator = localGetFieldText(channelStruct, ...
    "preamp_or_attenuator");
channelMetadata.Notes = localGetFieldText(channelStruct, "notes");

end

function siteContext = localNormalizeSiteContext(rawMetadata)

siteContextStruct = localGetStructField(rawMetadata, "site_context");
siteContext = struct();
siteContext.SiteRegion = localGetFieldText(siteContextStruct, ...
    "site_region");
siteContext.SurveillanceBoresightDescription = localGetFieldText( ...
    siteContextStruct, "surveillance_boresight_description");
siteContext.ExpectedAirTrafficNote = localGetFieldText(siteContextStruct, ...
    "expected_air_traffic_note");
siteContext.IlluminatorNote = localGetFieldText(siteContextStruct, ...
    "illuminator_note");
siteContext.ReceiverLocationNote = localGetFieldText(siteContextStruct, ...
    "receiver_location_note");
siteContext.ObstructionsOrClutterNote = localGetFieldText( ...
    siteContextStruct, "obstructions_or_clutter_note");

end

function acquisitionControls = localNormalizeAcquisitionControls(rawMetadata)

controlsStruct = localGetStructField(rawMetadata, "acquisition_controls");
acquisitionControls = struct();
acquisitionControls.GainMappingNote = localGetFieldText(controlsStruct, ...
    "gain_mapping_note");
acquisitionControls.GainModeNote = localGetFieldText(controlsStruct, ...
    "gain_mode_note");
acquisitionControls.LockStatusNote = localGetFieldText(controlsStruct, ...
    "lock_status_note");
acquisitionControls.OverrunNote = localGetFieldText(controlsStruct, ...
    "overrun_note");
acquisitionControls.ChannelMappingVerificationNote = ...
    localGetFieldText(controlsStruct, ...
    "channel_mapping_verification_note");
acquisitionControls.OperatorNotes = localGetFieldText(controlsStruct, ...
    "operator_notes");

end

function fieldText = localGetFieldText(inputStruct, fieldName)

fieldText = "";

if ~isstruct(inputStruct)
    return
end

if ~isfield(inputStruct, fieldName)
    return
end

fieldValue = inputStruct.(fieldName);

if isnumeric(fieldValue) || islogical(fieldValue)
    fieldText = string(fieldValue);
elseif isstring(fieldValue) || ischar(fieldValue)
    fieldText = string(fieldValue);
else
    fieldText = "";
end

fieldText = strtrim(fieldText);

end

function outputStruct = localGetStructField(inputStruct, fieldName)

outputStruct = struct();

if ~isstruct(inputStruct)
    return
end

if ~isfield(inputStruct, fieldName)
    return
end

fieldValue = inputStruct.(fieldName);

if isstruct(fieldValue)
    outputStruct = fieldValue;
end

end
