function analysis = helperAnalyzeG3SyncCore(sessionData, ...
    collectionMetadataInfo, options)
%HELPERANALYZEG3SYNCCORE Analyze Stage 3 sync questions for the baseline.
%
%   ANALYSIS = HELPERANALYZEG3SYNCCORE(SESSIONDATA, ...
%   COLLECTIONMETADATAINFO, OPTIONS) evaluates the Stage 3 lag, residual
%   frequency, CPI coherence, and correction-strategy questions for the
%   baseline dataset only. The helper is question-driven on purpose: each
%   returned table row carries the Stage 3 question it exists to answer.

arguments
    sessionData (1,1) struct
    collectionMetadataInfo (1,1) struct
    options (1,1) struct = struct()
end

syncPrep = helperPrepareG3SyncInputs(sessionData, ...
    collectionMetadataInfo, options);
resolvedOptions = syncPrep.ResolvedOptions;
roleInfo = syncPrep.RoleInfo;
windowObservations = syncPrep.WindowObservations;
lagTable = localBuildLagTable(sessionData, windowObservations, ...
    resolvedOptions);
residualFrequencyTable = localBuildResidualFrequencyTable(sessionData, ...
    windowObservations, resolvedOptions);
cpiCoherenceTable = localBuildCpiCoherenceTable(sessionData, ...
    windowObservations, resolvedOptions);
[strategyComparisonTable, recommendedStrategyCandidate] = ...
    localBuildStrategyComparisonTable(windowObservations, ...
    resolvedOptions);
[questionSummaries, blockingFindings] = localBuildQuestionSummaries( ...
    lagTable, residualFrequencyTable, cpiCoherenceTable, ...
    strategyComparisonTable, recommendedStrategyCandidate, roleInfo, ...
    resolvedOptions);
interpretation = localBuildInterpretation(questionSummaries, ...
    blockingFindings, recommendedStrategyCandidate, roleInfo, ...
    resolvedOptions);

analysis = struct();
analysis.DatasetId = string(sessionData.DatasetId);
analysis.StageId = "G3_Sync_Core";
analysis.Options = localBuildOptionsOutput(resolvedOptions);
analysis.QuestionSummaries = questionSummaries;
analysis.LagTable = lagTable;
analysis.ResidualFrequencyTable = residualFrequencyTable;
analysis.CpiCoherenceTable = cpiCoherenceTable;
analysis.StrategyComparisonTable = strategyComparisonTable;
analysis.Metrics = localBuildMetrics(roleInfo, lagTable, ...
    residualFrequencyTable, cpiCoherenceTable, ...
    strategyComparisonTable, questionSummaries, interpretation, ...
    blockingFindings, recommendedStrategyCandidate, resolvedOptions);
analysis.Interpretation = interpretation;
analysis.RecommendedStrategyCandidate = recommendedStrategyCandidate;
analysis.BlockingFindings = blockingFindings;

end

function resolvedOptions = localResolveOptions(sessionData, options) %#ok<DEFNU>

sampleRateVector = unique(sessionData.RadarTable.SampleRate_Hz);
sampleCountVector = unique(sessionData.RadarTable.NumSamples);

if numel(sampleRateVector) ~= 1
    error("helperAnalyzeG3SyncCore:SampleRateMismatch", ...
        "Stage 3 requires one frozen sample rate across the session.");
end

if numel(sampleCountVector) ~= 1
    error("helperAnalyzeG3SyncCore:SampleCountMismatch", ...
        "Stage 3 requires one frozen sample count across the session.");
end

resolvedOptions = struct();
resolvedOptions.ExpectedDatasetId = "20260622T102123";
resolvedOptions.ExpectedReferenceLabel = "RF1:RX2";
resolvedOptions.ExpectedSurveillanceLabel = "RF0:RX2";
resolvedOptions.ExpectedRepetitionCount = 15;
resolvedOptions.SampleRateHz = double(sampleRateVector(1));
resolvedOptions.SamplesPerRepetition = double(sampleCountVector(1));
resolvedOptions.CpiLabels = ["short"; "medium"; "long"];
resolvedOptions.CpiDurations_s = [0.025; 0.050; 0.100];
resolvedOptions.WindowHopFractions = [1.0; 1.0; 1.0];
resolvedOptions.CorrelationSampleCount = 131072;
resolvedOptions.CorrelationMaxLagSamples = 4096;
resolvedOptions.XcorrMainlobeExclusionSamples = 8;
resolvedOptions.CoherenceWindowLength = 4096;
resolvedOptions.CoherenceOverlap = 2048;
resolvedOptions.CoherenceNfft = 4096;
resolvedOptions.CoherenceBandEdgeFraction = 0.45;
resolvedOptions.CoherencePassThreshold = 0.80;
resolvedOptions.CoherenceCaveatedThreshold = 0.65;
resolvedOptions.CoherenceReadyPassFractionThreshold = 0.80;
resolvedOptions.CoherenceBlockedPassFractionThreshold = 0.50;
resolvedOptions.SpectrogramWindowLength = 4096;
resolvedOptions.SpectrogramOverlap = 3072;
resolvedOptions.SpectrogramNfft = 4096;
resolvedOptions.SpectrogramBandThreshold_dB = 20.0;
resolvedOptions.SpectrogramMinimumBandBins = 32;
resolvedOptions.LagReadySpreadThresholdSamples = 0.5;
resolvedOptions.LagBlockedSpreadThresholdSamples = 2.0;
resolvedOptions.LagReadySharpnessThreshold_dB = 6.0;
resolvedOptions.LagBlockedSharpnessThreshold_dB = 3.0;
resolvedOptions.DelayAgreementReadyThreshold = 0.90;
resolvedOptions.DelayAgreementBlockedThreshold = 0.50;
resolvedOptions.PhaseExcursionReadyThreshold_deg = 15.0;
resolvedOptions.PhaseExcursionBlockedThreshold_deg = 45.0;
resolvedOptions.PhaseFitRmseReadyThreshold_deg = 5.0;
resolvedOptions.PhaseFitRmseBlockedThreshold_deg = 15.0;
resolvedOptions.StrategyComparisonCpiLabel = "short";
resolvedOptions.StrategyLagPassThresholdSamples = 1.0;
resolvedOptions.StrategyPhasePassThreshold_deg = 15.0;
resolvedOptions.StrategyPassFractionMargin = 0.05;
resolvedOptions.StrategyLagEquivalenceMarginSamples = 0.5;
resolvedOptions.StrategyPhaseEquivalenceMargin_deg = 5.0;

optionFields = fieldnames(options);

for idx = 1:numel(optionFields)
    fieldName = optionFields{idx};
    resolvedOptions.(fieldName) = options.(fieldName);
end

resolvedOptions.CpiLabels = string(resolvedOptions.CpiLabels(:));
resolvedOptions.CpiDurations_s = double(resolvedOptions.CpiDurations_s(:));
resolvedOptions.WindowHopFractions = ...
    double(resolvedOptions.WindowHopFractions(:));

if numel(resolvedOptions.CpiLabels) ~= numel(resolvedOptions.CpiDurations_s)
    error("helperAnalyzeG3SyncCore:InvalidCpiDefinition", ...
        "CPI labels and CPI durations must have the same length.");
end

if numel(resolvedOptions.WindowHopFractions) ~= ...
        numel(resolvedOptions.CpiDurations_s)
    error("helperAnalyzeG3SyncCore:InvalidWindowHopDefinition", ...
        "Each CPI length requires one hop fraction.");
end

resolvedOptions.CpiSampleCounts = round( ...
    resolvedOptions.CpiDurations_s .* resolvedOptions.SampleRateHz);
resolvedOptions.WindowHopSamples = max(1, round( ...
    resolvedOptions.WindowHopFractions .* ...
    resolvedOptions.CpiSampleCounts));
resolvedOptions.CpiDefinitions = localBuildCpiDefinitions( ...
    resolvedOptions.CpiLabels, resolvedOptions.CpiDurations_s, ...
    resolvedOptions.CpiSampleCounts, resolvedOptions.WindowHopSamples);

end

function cpiDefinitions = localBuildCpiDefinitions(cpiLabels, ...
    cpiDurationsSeconds, cpiSampleCounts, windowHopSamples)

definitionCount = numel(cpiLabels);
cpiDefinitions = repmat(struct( ...
    "Label", "", ...
    "Duration_s", NaN, ...
    "Samples", NaN, ...
    "WindowHopSamples", NaN ...
    ), definitionCount, 1);

for idx = 1:definitionCount
    cpiDefinitions(idx).Label = string(cpiLabels(idx));
    cpiDefinitions(idx).Duration_s = double(cpiDurationsSeconds(idx));
    cpiDefinitions(idx).Samples = double(cpiSampleCounts(idx));
    cpiDefinitions(idx).WindowHopSamples = double(windowHopSamples(idx));
end

end

function roleInfo = localResolveRoleInfo(sessionData, collectionMetadataInfo, ...
    resolvedOptions) %#ok<DEFNU>

channel1Label = string(sessionData.RadarTable.Antenna1(1));
channel2Label = string(sessionData.RadarTable.Antenna2(1));
referenceLabel = strtrim( ...
    string(collectionMetadataInfo.ReferenceChannel.ChannelLabel));
surveillanceLabel = strtrim( ...
    string(collectionMetadataInfo.SurveillanceChannel.ChannelLabel));

roleInfo = struct();
roleInfo.ReferenceLabel = referenceLabel;
roleInfo.SurveillanceLabel = surveillanceLabel;
roleInfo.ReferenceColumnIndex = NaN;
roleInfo.SurveillanceColumnIndex = NaN;
roleInfo.RoleSource = "collection_metadata_manual_mapping";
roleInfo.RoleNote = "Stage 3 keeps the accepted Stage 2 role mapping " + ...
    "fixed and does not reopen G1 or G2 role assumptions.";

manualMappingValid = collectionMetadataInfo.MetadataPresent && ...
    collectionMetadataInfo.SessionIdMatches && ...
    any(referenceLabel == [channel1Label; channel2Label]) && ...
    any(surveillanceLabel == [channel1Label; channel2Label]) && ...
    referenceLabel ~= surveillanceLabel;

if ~manualMappingValid
    error("helperAnalyzeG3SyncCore:MissingRoleMapping", ...
        "Stage 3 requires the accepted Stage 2 manual role mapping.");
end

if referenceLabel == channel1Label
    roleInfo.ReferenceColumnIndex = 1;
else
    roleInfo.ReferenceColumnIndex = 2;
end

if surveillanceLabel == channel1Label
    roleInfo.SurveillanceColumnIndex = 1;
else
    roleInfo.SurveillanceColumnIndex = 2;
end

if roleInfo.ReferenceLabel ~= resolvedOptions.ExpectedReferenceLabel || ...
        roleInfo.SurveillanceLabel ~= ...
        resolvedOptions.ExpectedSurveillanceLabel
    error("helperAnalyzeG3SyncCore:UnexpectedRoleMapping", ...
        [ ...
        "Stage 3 is scoped only to reference %s and surveillance %s ", ...
        "for the baseline session." ...
        ], resolvedOptions.ExpectedReferenceLabel, ...
        resolvedOptions.ExpectedSurveillanceLabel);
end

end

function localValidateContracts(sessionData, roleInfo, resolvedOptions) %#ok<DEFNU>

datasetId = string(sessionData.DatasetId);
repetitionCount = height(sessionData.RadarTable);

if datasetId ~= resolvedOptions.ExpectedDatasetId
    error("helperAnalyzeG3SyncCore:UnexpectedDataset", ...
        "Stage 3 is scoped only to dataset %s.", ...
        resolvedOptions.ExpectedDatasetId);
end

if repetitionCount ~= resolvedOptions.ExpectedRepetitionCount
    error("helperAnalyzeG3SyncCore:UnexpectedRepetitionCount", ...
        "Expected %d repetitions for Stage 3 but found %d.", ...
        resolvedOptions.ExpectedRepetitionCount, repetitionCount);
end

if ~isfield(sessionData, "CpiContract") || ...
        ~isfield(sessionData.CpiContract, "CrossFileAllowed") || ...
        logical(sessionData.CpiContract.CrossFileAllowed)
    error("helperAnalyzeG3SyncCore:UnexpectedCpiContract", ...
        "Stage 3 requires the frozen G1 intra-file-only CPI contract.");
end

if any(resolvedOptions.CpiSampleCounts > ...
        resolvedOptions.SamplesPerRepetition)
    error("helperAnalyzeG3SyncCore:OversizedCpi", ...
        "Each Stage 3 CPI length must fit within one repetition.");
end

if isnan(roleInfo.ReferenceColumnIndex) || ...
        isnan(roleInfo.SurveillanceColumnIndex)
    error("helperAnalyzeG3SyncCore:InvalidRoleColumns", ...
        "Stage 3 could not resolve the fixed reference/surveillance columns.");
end

end

function windowObservations = localBuildWindowObservations(sessionData, ...
    roleInfo, resolvedOptions) %#ok<DEFNU>

radarTable = sessionData.RadarTable;
repetitionCount = height(radarTable);
windowCountPerRepetition = zeros(numel(resolvedOptions.CpiDefinitions), 1);

for idx = 1:numel(resolvedOptions.CpiDefinitions)
    cpiSamples = resolvedOptions.CpiDefinitions(idx).Samples;
    hopSamples = resolvedOptions.CpiDefinitions(idx).WindowHopSamples;
    maxStart = resolvedOptions.SamplesPerRepetition - cpiSamples + 1;
    windowStarts = 1:hopSamples:maxStart;
    windowCountPerRepetition(idx) = numel(windowStarts);
end

totalObservationCount = repetitionCount * sum(windowCountPerRepetition);
rowTemplate = localBuildWindowObservationTemplate();
rows = repmat(rowTemplate, totalObservationCount, 1);
rowIndex = 0;

for repetitionIndex = 1:repetitionCount
    scan = localResolveScanWithSamples(sessionData, repetitionIndex);
    referenceSamples = double(scan.Samples(:, roleInfo.ReferenceColumnIndex));
    surveillanceSamples = double(scan.Samples(:, ...
        roleInfo.SurveillanceColumnIndex));

    for cpiIndex = 1:numel(resolvedOptions.CpiDefinitions)
        cpiDefinition = resolvedOptions.CpiDefinitions(cpiIndex);
        maxStart = numel(referenceSamples) - cpiDefinition.Samples + 1;
        windowStarts = 1:cpiDefinition.WindowHopSamples:maxStart;

        for windowIndex = 1:numel(windowStarts)
            startSample = windowStarts(windowIndex);
            stopSample = startSample + cpiDefinition.Samples - 1;
            referenceWindow = referenceSamples(startSample:stopSample);
            surveillanceWindow = surveillanceSamples(startSample:stopSample);
            lagMetrics = localEstimateLag(referenceWindow, ...
                surveillanceWindow, resolvedOptions);
            alignedSurveillance = localApplyIntegerDelay( ...
                surveillanceWindow, lagMetrics.CanonicalLagSamples);
            residualMetrics = localEstimateResidualFrequency( ...
                referenceWindow, alignedSurveillance, cpiDefinition, ...
                resolvedOptions);
            coherenceMetrics = localEstimateCoherence(referenceWindow, ...
                alignedSurveillance, resolvedOptions);

            rowIndex = rowIndex + 1;
            rows(rowIndex) = struct( ...
                "Repetition", double(radarTable.Repetition(repetitionIndex)), ...
                "RelativePath", string(radarTable.RelativePath(repetitionIndex)), ...
                "CpiLabel", cpiDefinition.Label, ...
                "CpiDuration_s", cpiDefinition.Duration_s, ...
                "CpiSamples", cpiDefinition.Samples, ...
                "WindowIndex", double(windowIndex), ...
                "WindowStartSample", double(startSample), ...
                "WindowStopSample", double(stopSample), ...
                "FindDelayLagSamples", lagMetrics.FindDelayLagSamples, ...
                "XcorrLagSamples", lagMetrics.XcorrLagSamples, ...
                "CanonicalLagSamples", lagMetrics.CanonicalLagSamples, ...
                "DelayEstimateAgreement", lagMetrics.DelayEstimateAgreement, ...
                "PeakCorrelationMagnitude", ...
                lagMetrics.PeakCorrelationMagnitude, ...
                "ZeroLagCorrelationMagnitude", ...
                lagMetrics.ZeroLagCorrelationMagnitude, ...
                "PeakToSidelobe_dB", lagMetrics.PeakToSidelobe_dB, ...
                "PeakToZero_dB", lagMetrics.PeakToZero_dB, ...
                "ResidualFrequencyHz", residualMetrics.ResidualFrequencyHz, ...
                "PhaseExcursion_deg", residualMetrics.PhaseExcursion_deg, ...
                "PhaseFitRmse_deg", residualMetrics.PhaseFitRmse_deg, ...
                "SpectrogramBandBinCount", ...
                residualMetrics.SpectrogramBandBinCount, ...
                "CoherenceMean", coherenceMetrics.CoherenceMean, ...
                "CoherenceP10", coherenceMetrics.CoherenceP10, ...
                "CoherenceMinimum", coherenceMetrics.CoherenceMinimum ...
                );
        end
    end
end

windowObservations = struct2table(rows(1:rowIndex));
windowObservations = sortrows(windowObservations, ...
    ["Repetition", "CpiLabel", "WindowIndex"]);

end

function rowTemplate = localBuildWindowObservationTemplate()

rowTemplate = struct( ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "CpiLabel", "", ...
    "CpiDuration_s", NaN, ...
    "CpiSamples", NaN, ...
    "WindowIndex", NaN, ...
    "WindowStartSample", NaN, ...
    "WindowStopSample", NaN, ...
    "FindDelayLagSamples", NaN, ...
    "XcorrLagSamples", NaN, ...
    "CanonicalLagSamples", NaN, ...
    "DelayEstimateAgreement", false, ...
    "PeakCorrelationMagnitude", NaN, ...
    "ZeroLagCorrelationMagnitude", NaN, ...
    "PeakToSidelobe_dB", NaN, ...
    "PeakToZero_dB", NaN, ...
    "ResidualFrequencyHz", NaN, ...
    "PhaseExcursion_deg", NaN, ...
    "PhaseFitRmse_deg", NaN, ...
    "SpectrogramBandBinCount", NaN, ...
    "CoherenceMean", NaN, ...
    "CoherenceP10", NaN, ...
    "CoherenceMinimum", NaN ...
    );

end

function scan = localResolveScanWithSamples(sessionData, repetitionIndex)

scan = sessionData.RadarScans(repetitionIndex);

if ~isempty(scan.Samples)
    return
end

absoluteFilePath = fullfile(string(sessionData.DatasetRoot), ...
    strrep(sessionData.RadarTable.RelativePath(repetitionIndex), ...
    "/", filesep));

try
    scan = helperScanBasebandCaptureFile(absoluteFilePath, true);
catch readException
    error("helperAnalyzeG3SyncCore:ReadSamplesFailed", ...
        "Failed to load samples for %s: %s", absoluteFilePath, ...
        readException.message);
end

end

function lagMetrics = localEstimateLag(referenceWindow, surveillanceWindow, ...
    resolvedOptions)

correlationSampleCount = min(numel(referenceWindow), ...
    resolvedOptions.CorrelationSampleCount);
referenceSegment = referenceWindow(1:correlationSampleCount);
surveillanceSegment = surveillanceWindow(1:correlationSampleCount);
findDelayLag = finddelay(referenceSegment, surveillanceSegment, ...
    resolvedOptions.CorrelationMaxLagSamples);
[correlationValues, correlationLags] = xcorr(referenceSegment, ...
    surveillanceSegment, resolvedOptions.CorrelationMaxLagSamples, ...
    "normalized");
[peakCorrelationMagnitude, peakIndex] = max(abs(correlationValues));
xcorrLag = correlationLags(peakIndex);
zeroLagIndex = find(correlationLags == 0, 1, "first");
zeroLagCorrelationMagnitude = abs(correlationValues(zeroLagIndex));
mainlobeMask = abs(correlationLags - xcorrLag) <= ...
    resolvedOptions.XcorrMainlobeExclusionSamples;
sidelobeValues = abs(correlationValues(~mainlobeMask));

lagMetrics = struct();
lagMetrics.FindDelayLagSamples = double(findDelayLag);
lagMetrics.XcorrLagSamples = double(xcorrLag);
lagMetrics.CanonicalLagSamples = double(xcorrLag);
lagMetrics.DelayEstimateAgreement = ...
    double(xcorrLag) == -double(findDelayLag);
lagMetrics.PeakCorrelationMagnitude = double(peakCorrelationMagnitude);
lagMetrics.ZeroLagCorrelationMagnitude = ...
    double(zeroLagCorrelationMagnitude);
lagMetrics.PeakToSidelobe_dB = 20.0 * log10( ...
    double(peakCorrelationMagnitude) / max(max(sidelobeValues), eps));
lagMetrics.PeakToZero_dB = 20.0 * log10( ...
    double(peakCorrelationMagnitude) / ...
    max(double(zeroLagCorrelationMagnitude), eps));

end

function delayedSignal = localApplyIntegerDelay(inputSignal, sampleDelay)

sampleDelay = double(sampleDelay);
signalLength = numel(inputSignal);

if signalLength == 0
    delayedSignal = inputSignal;
    return
end

if sampleDelay > 0
    if sampleDelay >= signalLength
        delayedSignal = zeros(size(inputSignal), "like", inputSignal);
        return
    end

    delayedSignal = [ ...
        zeros(sampleDelay, 1, "like", inputSignal); ...
        inputSignal(1:end - sampleDelay) ...
        ];
    return
end

if sampleDelay < 0
    advanceCount = abs(sampleDelay);

    if advanceCount >= signalLength
        delayedSignal = zeros(size(inputSignal), "like", inputSignal);
        return
    end

    delayedSignal = [ ...
        inputSignal(advanceCount + 1:end); ...
        zeros(advanceCount, 1, "like", inputSignal) ...
        ];
    return
end

delayedSignal = inputSignal;

end

function residualMetrics = localEstimateResidualFrequency(referenceWindow, ...
    alignedSurveillance, cpiDefinition, resolvedOptions)

stftWindow = hamming(resolvedOptions.SpectrogramWindowLength, ...
    "periodic");
[referenceSpectrogram, frequencyHz, timeSeconds] = spectrogram( ...
    referenceWindow, stftWindow, resolvedOptions.SpectrogramOverlap, ...
    resolvedOptions.SpectrogramNfft, resolvedOptions.SampleRateHz, ...
    "centered");
[surveillanceSpectrogram, ~, ~] = spectrogram(alignedSurveillance, ...
    stftWindow, resolvedOptions.SpectrogramOverlap, ...
    resolvedOptions.SpectrogramNfft, resolvedOptions.SampleRateHz, ...
    "centered");
referencePowerByBin = mean(abs(referenceSpectrogram) .^ 2, 2);
analysisBandMask = abs(frequencyHz) <= ...
    resolvedOptions.CoherenceBandEdgeFraction * ...
    resolvedOptions.SampleRateHz;
bandMask = referencePowerByBin >= max(referencePowerByBin) * ...
    10.0 ^ (-resolvedOptions.SpectrogramBandThreshold_dB / 10.0) & ...
    analysisBandMask;

if nnz(bandMask) < resolvedOptions.SpectrogramMinimumBandBins
    candidateIndices = find(analysisBandMask);
    [~, sortOrder] = sort(referencePowerByBin(candidateIndices), ...
        "descend");
    bandMask = false(size(referencePowerByBin));
    keepCount = min(resolvedOptions.SpectrogramMinimumBandBins, ...
        numel(sortOrder));
    bandMask(candidateIndices(sortOrder(1:keepCount))) = true;
end

crossSpectrum = surveillanceSpectrogram(bandMask, :) .* conj( ...
    referenceSpectrogram(bandMask, :));
bandCrossSeries = sum(crossSpectrum, 1).';
phaseVector = unwrap(angle(bandCrossSeries));
fitCoefficients = polyfit(timeSeconds(:), phaseVector, 1);
fitPhaseVector = polyval(fitCoefficients, timeSeconds(:));
residualFrequencyHz = fitCoefficients(1) / (2.0 * pi);

residualMetrics = struct();
residualMetrics.ResidualFrequencyHz = double(residualFrequencyHz);
residualMetrics.PhaseExcursion_deg = abs(residualFrequencyHz) * ...
    cpiDefinition.Duration_s * 360.0;
residualMetrics.PhaseFitRmse_deg = rad2deg(sqrt(mean((phaseVector - ...
    fitPhaseVector) .^ 2)));
residualMetrics.SpectrogramBandBinCount = double(nnz(bandMask));

end

function coherenceMetrics = localEstimateCoherence(referenceWindow, ...
    alignedSurveillance, resolvedOptions)

coherenceWindow = hamming(resolvedOptions.CoherenceWindowLength, ...
    "periodic");
[coherenceVector, coherenceFrequencyHz] = mscohere(referenceWindow, ...
    alignedSurveillance, coherenceWindow, resolvedOptions.CoherenceOverlap, ...
    resolvedOptions.CoherenceNfft, resolvedOptions.SampleRateHz);
[coherenceFrequencyHz, coherenceVector] = localCenterSingleSpectrum( ...
    coherenceFrequencyHz, coherenceVector, ...
    resolvedOptions.SampleRateHz);
analysisBandMask = abs(coherenceFrequencyHz) <= ...
    resolvedOptions.CoherenceBandEdgeFraction * ...
    resolvedOptions.SampleRateHz;
bandCoherence = coherenceVector(analysisBandMask);

coherenceMetrics = struct();
coherenceMetrics.CoherenceMean = mean(bandCoherence, "omitnan");
coherenceMetrics.CoherenceP10 = prctile(bandCoherence, 10);
coherenceMetrics.CoherenceMinimum = min(bandCoherence);

end

function [frequencyHz, spectrum] = localCenterSingleSpectrum( ...
    frequencyHz, spectrum, sampleRateHz)

if max(frequencyHz) <= sampleRateHz / 2
    return
end

frequencyHz = frequencyHz - sampleRateHz / 2;
spectrum = fftshift(spectrum);

end

function lagTable = localBuildLagTable(sessionData, windowObservations, ...
    resolvedOptions)

lagRows = repmat(localBuildLagRowTemplate(), ...
    height(sessionData.RadarTable) * numel(resolvedOptions.CpiDefinitions), ...
    1);
rowIndex = 0;

for repetitionIndex = 1:height(sessionData.RadarTable)
    for cpiIndex = 1:numel(resolvedOptions.CpiDefinitions)
        cpiLabel = resolvedOptions.CpiDefinitions(cpiIndex).Label;
        subset = windowObservations( ...
            windowObservations.Repetition == ...
            sessionData.RadarTable.Repetition(repetitionIndex) & ...
            windowObservations.CpiLabel == cpiLabel, :);
        [interpretationLabel, rationale] = localClassifyLagSubset( ...
            subset, resolvedOptions);
        rowIndex = rowIndex + 1;
        lagRows(rowIndex) = struct( ...
            "QuestionId", "Q1", ...
            "QuestionText", ...
            "Can we estimate a repeatable lag between reference and surveillance for each repetition?", ...
            "Repetition", double(sessionData.RadarTable.Repetition(repetitionIndex)), ...
            "RelativePath", string(sessionData.RadarTable.RelativePath(repetitionIndex)), ...
            "CpiLabel", cpiLabel, ...
            "CpiDuration_s", double(subset.CpiDuration_s(1)), ...
            "CpiSamples", double(subset.CpiSamples(1)), ...
            "WindowCount", double(height(subset)), ...
            "FindDelayLagMedian_samples", median(subset.FindDelayLagSamples), ...
            "XcorrLagMedian_samples", median(subset.XcorrLagSamples), ...
            "LagWindowSpread_samples", max(subset.CanonicalLagSamples) - ...
            min(subset.CanonicalLagSamples), ...
            "DelayEstimateAgreementFraction", ...
            mean(subset.DelayEstimateAgreement), ...
            "PeakCorrelationMagnitudeMedian", ...
            median(subset.PeakCorrelationMagnitude), ...
            "PeakToSidelobeMedian_dB", ...
            median(subset.PeakToSidelobe_dB), ...
            "PeakToSidelobeMin_dB", min(subset.PeakToSidelobe_dB), ...
            "InterpretationLabel", interpretationLabel, ...
            "Rationale", rationale ...
            );
    end
end

lagTable = struct2table(lagRows(1:rowIndex));

end

function rowTemplate = localBuildLagRowTemplate()

rowTemplate = struct( ...
    "QuestionId", "", ...
    "QuestionText", "", ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "CpiLabel", "", ...
    "CpiDuration_s", NaN, ...
    "CpiSamples", NaN, ...
    "WindowCount", NaN, ...
    "FindDelayLagMedian_samples", NaN, ...
    "XcorrLagMedian_samples", NaN, ...
    "LagWindowSpread_samples", NaN, ...
    "DelayEstimateAgreementFraction", NaN, ...
    "PeakCorrelationMagnitudeMedian", NaN, ...
    "PeakToSidelobeMedian_dB", NaN, ...
    "PeakToSidelobeMin_dB", NaN, ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function [interpretationLabel, rationale] = localClassifyLagSubset( ...
    subset, resolvedOptions)

lagSpread = max(subset.CanonicalLagSamples) - min(subset.CanonicalLagSamples);
sharpnessMedian = median(subset.PeakToSidelobe_dB);
agreementFraction = mean(subset.DelayEstimateAgreement);
canonicalLag = median(subset.CanonicalLagSamples);

if ~localTableHasFiniteNumericValues(subset)
    interpretationLabel = "blocked";
    rationale = "Lag metrics were not finite across all windows.";
    return
end

if lagSpread <= resolvedOptions.LagReadySpreadThresholdSamples && ...
        sharpnessMedian >= resolvedOptions.LagReadySharpnessThreshold_dB && ...
        agreementFraction >= resolvedOptions.DelayAgreementReadyThreshold
    interpretationLabel = "ready";
elseif lagSpread <= resolvedOptions.LagBlockedSpreadThresholdSamples && ...
        sharpnessMedian >= resolvedOptions.LagBlockedSharpnessThreshold_dB && ...
        agreementFraction >= resolvedOptions.DelayAgreementBlockedThreshold
    interpretationLabel = "caveated";
else
    interpretationLabel = "blocked";
end

rationale = sprintf("Lag stayed near %.1f sample with %.1f-sample " + ...
    "spread across %d windows and median peak-to-sidelobe %.2f dB.", ...
    canonicalLag, lagSpread, height(subset), sharpnessMedian);

end

function residualFrequencyTable = localBuildResidualFrequencyTable( ...
    sessionData, windowObservations, resolvedOptions)

residualRows = repmat(localBuildResidualRowTemplate(), ...
    height(sessionData.RadarTable) * numel(resolvedOptions.CpiDefinitions), ...
    1);
rowIndex = 0;

for repetitionIndex = 1:height(sessionData.RadarTable)
    for cpiIndex = 1:numel(resolvedOptions.CpiDefinitions)
        cpiLabel = resolvedOptions.CpiDefinitions(cpiIndex).Label;
        subset = windowObservations( ...
            windowObservations.Repetition == ...
            sessionData.RadarTable.Repetition(repetitionIndex) & ...
            windowObservations.CpiLabel == cpiLabel, :);
        [interpretationLabel, rationale] = ...
            localClassifyResidualFrequencySubset(subset, resolvedOptions);
        rowIndex = rowIndex + 1;
        residualRows(rowIndex) = struct( ...
            "QuestionId", "Q2", ...
            "QuestionText", ...
            "Is residual frequency or phase drift small enough to support a consistent correction model?", ...
            "Repetition", double(sessionData.RadarTable.Repetition(repetitionIndex)), ...
            "RelativePath", string(sessionData.RadarTable.RelativePath(repetitionIndex)), ...
            "CpiLabel", cpiLabel, ...
            "CpiDuration_s", double(subset.CpiDuration_s(1)), ...
            "CpiSamples", double(subset.CpiSamples(1)), ...
            "WindowCount", double(height(subset)), ...
            "ResidualFrequencyMedian_Hz", ...
            median(subset.ResidualFrequencyHz), ...
            "ResidualFrequencyAbsMedian_Hz", ...
            median(abs(subset.ResidualFrequencyHz)), ...
            "ResidualFrequencyAbsMax_Hz", ...
            max(abs(subset.ResidualFrequencyHz)), ...
            "PhaseExcursionMedian_deg", ...
            median(subset.PhaseExcursion_deg), ...
            "PhaseExcursionMax_deg", max(subset.PhaseExcursion_deg), ...
            "PhaseFitRmseMedian_deg", ...
            median(subset.PhaseFitRmse_deg), ...
            "PhaseFitRmseMax_deg", max(subset.PhaseFitRmse_deg), ...
            "InterpretationLabel", interpretationLabel, ...
            "Rationale", rationale ...
            );
    end
end

residualFrequencyTable = struct2table(residualRows(1:rowIndex));

end

function rowTemplate = localBuildResidualRowTemplate()

rowTemplate = struct( ...
    "QuestionId", "", ...
    "QuestionText", "", ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "CpiLabel", "", ...
    "CpiDuration_s", NaN, ...
    "CpiSamples", NaN, ...
    "WindowCount", NaN, ...
    "ResidualFrequencyMedian_Hz", NaN, ...
    "ResidualFrequencyAbsMedian_Hz", NaN, ...
    "ResidualFrequencyAbsMax_Hz", NaN, ...
    "PhaseExcursionMedian_deg", NaN, ...
    "PhaseExcursionMax_deg", NaN, ...
    "PhaseFitRmseMedian_deg", NaN, ...
    "PhaseFitRmseMax_deg", NaN, ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function [interpretationLabel, rationale] = ...
    localClassifyResidualFrequencySubset(subset, resolvedOptions)

phaseExcursionMax = max(subset.PhaseExcursion_deg);
phaseFitRmseMedian = median(subset.PhaseFitRmse_deg);
residualAbsMedian = median(abs(subset.ResidualFrequencyHz));

if ~localTableHasFiniteNumericValues(subset)
    interpretationLabel = "blocked";
    rationale = "Residual-frequency metrics were not finite across all windows.";
    return
end

if phaseExcursionMax <= resolvedOptions.PhaseExcursionReadyThreshold_deg && ...
        phaseFitRmseMedian <= ...
        resolvedOptions.PhaseFitRmseReadyThreshold_deg
    interpretationLabel = "ready";
elseif phaseExcursionMax <= ...
        resolvedOptions.PhaseExcursionBlockedThreshold_deg && ...
        phaseFitRmseMedian <= ...
        resolvedOptions.PhaseFitRmseBlockedThreshold_deg
    interpretationLabel = "caveated";
else
    interpretationLabel = "blocked";
end

rationale = sprintf("Median absolute residual frequency was %.3f Hz " + ...
    "with maximum phase excursion %.2f deg and median phase-fit RMSE " + ...
    "%.2f deg.", residualAbsMedian, phaseExcursionMax, ...
    phaseFitRmseMedian);

end

function cpiCoherenceTable = localBuildCpiCoherenceTable(sessionData, ...
    windowObservations, resolvedOptions)

coherenceRows = repmat(localBuildCoherenceRowTemplate(), ...
    height(sessionData.RadarTable) * numel(resolvedOptions.CpiDefinitions), ...
    1);
rowIndex = 0;

for repetitionIndex = 1:height(sessionData.RadarTable)
    for cpiIndex = 1:numel(resolvedOptions.CpiDefinitions)
        cpiLabel = resolvedOptions.CpiDefinitions(cpiIndex).Label;
        subset = windowObservations( ...
            windowObservations.Repetition == ...
            sessionData.RadarTable.Repetition(repetitionIndex) & ...
            windowObservations.CpiLabel == cpiLabel, :);
        [interpretationLabel, rationale] = ...
            localClassifyCoherenceSubset(subset, resolvedOptions);
        rowIndex = rowIndex + 1;
        coherenceRows(rowIndex) = struct( ...
            "QuestionId", "Q3", ...
            "QuestionText", ...
            "Are candidate CPI windows coherently usable, or does coherence collapse at the window sizes we care about?", ...
            "Repetition", double(sessionData.RadarTable.Repetition(repetitionIndex)), ...
            "RelativePath", string(sessionData.RadarTable.RelativePath(repetitionIndex)), ...
            "CpiLabel", cpiLabel, ...
            "CpiDuration_s", double(subset.CpiDuration_s(1)), ...
            "CpiSamples", double(subset.CpiSamples(1)), ...
            "WindowCount", double(height(subset)), ...
            "CoherenceMedian", median(subset.CoherenceMean), ...
            "CoherenceP10", prctile(subset.CoherenceMean, 10), ...
            "CoherenceMinimum", min(subset.CoherenceMean), ...
            "CoherencePassFraction", ...
            mean(subset.CoherenceMean >= ...
            resolvedOptions.CoherencePassThreshold), ...
            "CoherencePassThreshold", ...
            resolvedOptions.CoherencePassThreshold, ...
            "InterpretationLabel", interpretationLabel, ...
            "Rationale", rationale ...
            );
    end
end

cpiCoherenceTable = struct2table(coherenceRows(1:rowIndex));

end

function rowTemplate = localBuildCoherenceRowTemplate()

rowTemplate = struct( ...
    "QuestionId", "", ...
    "QuestionText", "", ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "CpiLabel", "", ...
    "CpiDuration_s", NaN, ...
    "CpiSamples", NaN, ...
    "WindowCount", NaN, ...
    "CoherenceMedian", NaN, ...
    "CoherenceP10", NaN, ...
    "CoherenceMinimum", NaN, ...
    "CoherencePassFraction", NaN, ...
    "CoherencePassThreshold", NaN, ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function [interpretationLabel, rationale] = localClassifyCoherenceSubset( ...
    subset, resolvedOptions)

coherenceMedian = median(subset.CoherenceMean);
coherencePassFraction = mean(subset.CoherenceMean >= ...
    resolvedOptions.CoherencePassThreshold);

if ~localTableHasFiniteNumericValues(subset)
    interpretationLabel = "blocked";
    rationale = "Coherence metrics were not finite across all windows.";
    return
end

if coherenceMedian >= resolvedOptions.CoherencePassThreshold && ...
        coherencePassFraction >= ...
        resolvedOptions.CoherenceReadyPassFractionThreshold
    interpretationLabel = "ready";
elseif coherenceMedian >= resolvedOptions.CoherenceCaveatedThreshold && ...
        coherencePassFraction >= ...
        resolvedOptions.CoherenceBlockedPassFractionThreshold
    interpretationLabel = "caveated";
else
    interpretationLabel = "blocked";
end

rationale = sprintf("Median band coherence was %.3f with %.1f%% of " + ...
    "windows above the %.2f pass threshold.", coherenceMedian, ...
    100.0 * coherencePassFraction, ...
    resolvedOptions.CoherencePassThreshold);

end

function [strategyComparisonTable, recommendedStrategyCandidate] = ...
    localBuildStrategyComparisonTable(windowObservations, resolvedOptions)

baseObservations = windowObservations( ...
    windowObservations.CpiLabel == ...
    resolvedOptions.StrategyComparisonCpiLabel, :);
strategyNames = [ ...
    "global_session_correction"; ...
    "per_capture_correction"; ...
    "subwindow_correction" ...
    ];
strategyScopes = ["session"; "per_repetition"; "per_window"];
complexityRank = [1; 2; 3];
strategyRows = repmat(localBuildStrategyRowTemplate(), ...
    numel(strategyNames), 1);

globalLag = round(median(baseObservations.CanonicalLagSamples));
globalFrequencyHz = median(baseObservations.ResidualFrequencyHz);
repetitionVector = unique(baseObservations.Repetition);
perCaptureLag = containers.Map("KeyType", "double", "ValueType", "double");
perCaptureFrequencyHz = containers.Map("KeyType", "double", ...
    "ValueType", "double");

for repetitionIndex = 1:numel(repetitionVector)
    repetitionValue = repetitionVector(repetitionIndex);
    repetitionMask = baseObservations.Repetition == repetitionValue;
    perCaptureLag(repetitionValue) = round(median( ...
        baseObservations.CanonicalLagSamples(repetitionMask)));
    perCaptureFrequencyHz(repetitionValue) = median( ...
        baseObservations.ResidualFrequencyHz(repetitionMask));
end

for strategyIndex = 1:numel(strategyNames)
    lagResidual = zeros(height(baseObservations), 1);
    phaseResidual = zeros(height(baseObservations), 1);

    for observationIndex = 1:height(baseObservations)
        repetitionValue = baseObservations.Repetition(observationIndex);

        switch strategyNames(strategyIndex)
            case "global_session_correction"
                candidateLag = globalLag;
                candidateFrequencyHz = globalFrequencyHz;
            case "per_capture_correction"
                candidateLag = perCaptureLag(repetitionValue);
                candidateFrequencyHz = perCaptureFrequencyHz( ...
                    repetitionValue);
            case "subwindow_correction"
                candidateLag = ...
                    baseObservations.CanonicalLagSamples(observationIndex);
                candidateFrequencyHz = ...
                    baseObservations.ResidualFrequencyHz(observationIndex);
        end

        lagResidual(observationIndex) = abs( ...
            baseObservations.CanonicalLagSamples(observationIndex) - ...
            candidateLag);
        phaseResidual(observationIndex) = abs( ...
            baseObservations.ResidualFrequencyHz(observationIndex) - ...
            candidateFrequencyHz) * ...
            baseObservations.CpiDuration_s(observationIndex) * 360.0;
    end

    passMask = lagResidual <= resolvedOptions.StrategyLagPassThresholdSamples & ...
        phaseResidual <= resolvedOptions.StrategyPhasePassThreshold_deg & ...
        baseObservations.CoherenceMean >= ...
        resolvedOptions.CoherencePassThreshold;
    passFraction = mean(passMask);
    interpretationLabel = localClassifyStrategyRow(passFraction);
    rationale = sprintf("%s explains %.1f%% of short-CPI windows " + ...
        "within %.1f sample and %.1f deg residual limits.", ...
        strrep(strategyNames(strategyIndex), "_", " "), ...
        100.0 * passFraction, ...
        resolvedOptions.StrategyLagPassThresholdSamples, ...
        resolvedOptions.StrategyPhasePassThreshold_deg);

    strategyRows(strategyIndex) = struct( ...
        "QuestionId", "Q4", ...
        "QuestionText", ...
        "Which correction strategy is most defensible for downstream use?", ...
        "StrategyCandidate", strategyNames(strategyIndex), ...
        "StrategyScope", strategyScopes(strategyIndex), ...
        "EvaluationCpiLabel", ...
        resolvedOptions.StrategyComparisonCpiLabel, ...
        "EvaluationWindowCount", double(height(baseObservations)), ...
        "LagResidualMedian_samples", median(lagResidual), ...
        "LagResidualMax_samples", max(lagResidual), ...
        "PhaseResidualMedian_deg", median(phaseResidual), ...
        "PhaseResidualMax_deg", max(phaseResidual), ...
        "ObservablePassFraction", passFraction, ...
        "ComplexityRank", complexityRank(strategyIndex), ...
        "WithinBestMargin", false, ...
        "Recommended", false, ...
        "InterpretationLabel", interpretationLabel, ...
        "Rationale", rationale ...
        );
end

strategyComparisonTable = struct2table(strategyRows);
bestStrategyIndex = localSelectBestStrategy(strategyComparisonTable);
bestPassFraction = strategyComparisonTable.ObservablePassFraction( ...
    bestStrategyIndex);
bestLagResidual = strategyComparisonTable.LagResidualMedian_samples( ...
    bestStrategyIndex);
bestPhaseResidual = strategyComparisonTable.PhaseResidualMedian_deg( ...
    bestStrategyIndex);
withinBestMargin = ...
    strategyComparisonTable.ObservablePassFraction >= ...
    bestPassFraction - resolvedOptions.StrategyPassFractionMargin & ...
    strategyComparisonTable.LagResidualMedian_samples <= ...
    bestLagResidual + ...
    resolvedOptions.StrategyLagEquivalenceMarginSamples & ...
    strategyComparisonTable.PhaseResidualMedian_deg <= ...
    bestPhaseResidual + ...
    resolvedOptions.StrategyPhaseEquivalenceMargin_deg;
strategyComparisonTable.WithinBestMargin = withinBestMargin;
recommendedIndex = find(strategyComparisonTable.WithinBestMargin, ...
    1, "first");

if isempty(recommendedIndex)
    recommendedIndex = bestStrategyIndex;
end

strategyComparisonTable.Recommended(recommendedIndex) = true;
recommendedStrategyCandidate = ...
    strategyComparisonTable.StrategyCandidate(recommendedIndex);

end

function rowTemplate = localBuildStrategyRowTemplate()

rowTemplate = struct( ...
    "QuestionId", "", ...
    "QuestionText", "", ...
    "StrategyCandidate", "", ...
    "StrategyScope", "", ...
    "EvaluationCpiLabel", "", ...
    "EvaluationWindowCount", NaN, ...
    "LagResidualMedian_samples", NaN, ...
    "LagResidualMax_samples", NaN, ...
    "PhaseResidualMedian_deg", NaN, ...
    "PhaseResidualMax_deg", NaN, ...
    "ObservablePassFraction", NaN, ...
    "ComplexityRank", NaN, ...
    "WithinBestMargin", false, ...
    "Recommended", false, ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function interpretationLabel = localClassifyStrategyRow(passFraction)

if passFraction >= 0.90
    interpretationLabel = "ready";
elseif passFraction >= 0.50
    interpretationLabel = "caveated";
else
    interpretationLabel = "blocked";
end

end

function bestStrategyIndex = localSelectBestStrategy(strategyComparisonTable)

bestStrategyIndex = 1;

for idx = 2:height(strategyComparisonTable)
    currentRow = strategyComparisonTable(idx, :);
    bestRow = strategyComparisonTable(bestStrategyIndex, :);

    if currentRow.ObservablePassFraction > bestRow.ObservablePassFraction
        bestStrategyIndex = idx;
        continue
    end

    if currentRow.ObservablePassFraction == bestRow.ObservablePassFraction && ...
            currentRow.PhaseResidualMedian_deg < ...
            bestRow.PhaseResidualMedian_deg
        bestStrategyIndex = idx;
        continue
    end

    if currentRow.ObservablePassFraction == bestRow.ObservablePassFraction && ...
            currentRow.PhaseResidualMedian_deg == ...
            bestRow.PhaseResidualMedian_deg && ...
            currentRow.LagResidualMedian_samples < ...
            bestRow.LagResidualMedian_samples
        bestStrategyIndex = idx;
    end
end

end

function [questionSummaries, blockingFindings] = ...
    localBuildQuestionSummaries(lagTable, residualFrequencyTable, ...
    cpiCoherenceTable, strategyComparisonTable, ...
    recommendedStrategyCandidate, roleInfo, resolvedOptions)

lagLabel = localCollapseInterpretationLabels( ...
    lagTable.InterpretationLabel);
residualLabel = localCollapseInterpretationLabels( ...
    residualFrequencyTable.InterpretationLabel);
coherenceLabel = localCollapseInterpretationLabels( ...
    cpiCoherenceTable.InterpretationLabel);
recommendedRow = strategyComparisonTable( ...
    strategyComparisonTable.Recommended, :);
strategyLabel = string(recommendedRow.InterpretationLabel);
coherenceDecayMedian = localComputeCoherenceDecayMedian( ...
    cpiCoherenceTable, resolvedOptions);
questionRows = repmat(localBuildQuestionSummaryTemplate(), 4, 1);

questionRows(1) = struct( ...
    "QuestionId", "Q1", ...
    "QuestionText", ...
    "Can we estimate a repeatable lag between reference and surveillance for each repetition?", ...
    "ChosenObservables", ...
    "finddelay lag, xcorr peak lag, xcorr peak-to-sidelobe sharpness", ...
    "SummaryMetrics", sprintf("max_lag_spread=%.1f samples | " + ...
        "min_peak_to_sidelobe=%.2f dB | min_delay_agreement=%.2f", ...
        max(lagTable.LagWindowSpread_samples), ...
        min(lagTable.PeakToSidelobeMin_dB), ...
        min(lagTable.DelayEstimateAgreementFraction)), ...
    "InterpretationLabel", lagLabel, ...
    "Rationale", ...
    "Lag summary stays tied to SYN-001 and reports repeatability by repetition and CPI length rather than inferring downstream map quality." ...
    );
questionRows(2) = struct( ...
    "QuestionId", "Q2", ...
    "QuestionText", ...
    "Is residual frequency or phase drift small enough to support a consistent correction model?", ...
    "ChosenObservables", ...
    "spectrogram cross-phase slope, phase excursion, phase-fit RMSE, short-to-long coherence decay", ...
    "SummaryMetrics", sprintf("median_abs_freq=%.3f Hz | " + ...
        "max_phase_excursion=%.2f deg | median_coherence_decay=%.4f", ...
        median(residualFrequencyTable.ResidualFrequencyAbsMedian_Hz), ...
        max(residualFrequencyTable.PhaseExcursionMax_deg), ...
        coherenceDecayMedian), ...
    "InterpretationLabel", residualLabel, ...
    "Rationale", ...
    "Residual-frequency summary stays tied to SYN-002 and asks whether one drift model can explain the lag-corrected direct path across repeated windows." ...
    );
questionRows(3) = struct( ...
    "QuestionId", "Q3", ...
    "QuestionText", ...
    "Are candidate CPI windows coherently usable, or does coherence collapse at the window sizes we care about?", ...
    "ChosenObservables", ...
    "mscohere band-mean coherence, coherence percentile spread, coherence pass fraction by CPI length", ...
    "SummaryMetrics", localBuildCoherenceSummaryMetrics( ...
        cpiCoherenceTable, resolvedOptions), ...
    "InterpretationLabel", coherenceLabel, ...
    "Rationale", ...
    "CPI coherence stays separate from the lag and drift summaries so a reviewer can see whether good averages hide bad window-level stability." ...
    );
questionRows(4) = struct( ...
    "QuestionId", "Q4", ...
    "QuestionText", ...
    "Which correction strategy is most defensible for downstream use?", ...
    "ChosenObservables", ...
    "short-CPI lag residuals, short-CPI phase residuals, strategy pass fraction, simplicity-first margin rule", ...
    "SummaryMetrics", localBuildStrategySummaryMetrics( ...
        strategyComparisonTable, recommendedStrategyCandidate), ...
    "InterpretationLabel", strategyLabel, ...
    "Rationale", ...
    "Strategy selection stays tied to SYN-003 and recommends the simplest candidate that remains within the best short-window fit margin." ...
    );

questionSummaries = struct2table(questionRows);
blockingFindings = localCollectBlockingFindings(questionSummaries, ...
    lagTable, residualFrequencyTable, cpiCoherenceTable, ...
    strategyComparisonTable, roleInfo, resolvedOptions);

end

function rowTemplate = localBuildQuestionSummaryTemplate()

rowTemplate = struct( ...
    "QuestionId", "", ...
    "QuestionText", "", ...
    "ChosenObservables", "", ...
    "SummaryMetrics", "", ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function label = localCollapseInterpretationLabels(labelVector)

labelVector = string(labelVector);

if any(labelVector == "blocked")
    label = "blocked";
elseif any(labelVector == "caveated")
    label = "caveated";
else
    label = "ready";
end

end

function coherenceDecayMedian = localComputeCoherenceDecayMedian( ...
    cpiCoherenceTable, resolvedOptions)

shortRows = cpiCoherenceTable( ...
    cpiCoherenceTable.CpiLabel == resolvedOptions.CpiLabels(1), :);
longRows = cpiCoherenceTable( ...
    cpiCoherenceTable.CpiLabel == ...
    resolvedOptions.CpiLabels(end), :);
coherenceDecayMedian = median(longRows.CoherenceMedian - ...
    shortRows.CoherenceMedian);

end

function summaryMetrics = localBuildCoherenceSummaryMetrics( ...
    cpiCoherenceTable, resolvedOptions)

metricParts = strings(numel(resolvedOptions.CpiLabels), 1);

for idx = 1:numel(resolvedOptions.CpiLabels)
    cpiLabel = resolvedOptions.CpiLabels(idx);
    subset = cpiCoherenceTable(cpiCoherenceTable.CpiLabel == cpiLabel, :);
    metricParts(idx) = sprintf("%s=%.2f", cpiLabel, ...
        median(subset.CoherencePassFraction));
end

summaryMetrics = strjoin(metricParts, " | ");

end

function summaryMetrics = localBuildStrategySummaryMetrics( ...
    strategyComparisonTable, recommendedStrategyCandidate)

globalRow = strategyComparisonTable( ...
    strategyComparisonTable.StrategyCandidate == ...
    "global_session_correction", :);
perCaptureRow = strategyComparisonTable( ...
    strategyComparisonTable.StrategyCandidate == ...
    "per_capture_correction", :);
subwindowRow = strategyComparisonTable( ...
    strategyComparisonTable.StrategyCandidate == ...
    "subwindow_correction", :);
summaryMetrics = sprintf("recommended=%s | global=%.2f | " + ...
    "per_capture=%.2f | subwindow=%.2f", recommendedStrategyCandidate, ...
    globalRow.ObservablePassFraction, ...
    perCaptureRow.ObservablePassFraction, ...
    subwindowRow.ObservablePassFraction);

end

function blockingFindings = localCollectBlockingFindings( ...
    questionSummaries, lagTable, residualFrequencyTable, ...
    cpiCoherenceTable, strategyComparisonTable, roleInfo, ...
    resolvedOptions)

blockingFindings = strings(0, 1);

if roleInfo.ReferenceLabel ~= resolvedOptions.ExpectedReferenceLabel || ...
        roleInfo.SurveillanceLabel ~= ...
        resolvedOptions.ExpectedSurveillanceLabel
    blockingFindings(end + 1, 1) = "unexpected_role_mapping";
end

if any(questionSummaries.QuestionId == "Q1" & ...
        questionSummaries.InterpretationLabel == "blocked")
    blockingFindings(end + 1, 1) = ...
        "lag_estimation_not_repeatable";
end

if any(questionSummaries.QuestionId == "Q2" & ...
        questionSummaries.InterpretationLabel == "blocked")
    blockingFindings(end + 1, 1) = ...
        "residual_frequency_model_unstable";
end

if any(questionSummaries.QuestionId == "Q3" & ...
        questionSummaries.InterpretationLabel == "blocked")
    blockingFindings(end + 1, 1) = ...
        "cpi_coherence_collapse_detected";
end

if any(questionSummaries.QuestionId == "Q4" & ...
        questionSummaries.InterpretationLabel == "blocked")
    blockingFindings(end + 1, 1) = ...
        "no_defensible_correction_strategy";
end

if ~localTableHasFiniteNumericValues(lagTable)
    blockingFindings(end + 1, 1) = "nonfinite_lag_output";
end

if ~localTableHasFiniteNumericValues(residualFrequencyTable)
    blockingFindings(end + 1, 1) = ...
        "nonfinite_residual_frequency_output";
end

if ~localTableHasFiniteNumericValues(cpiCoherenceTable)
    blockingFindings(end + 1, 1) = ...
        "nonfinite_cpi_coherence_output";
end

if ~localTableHasFiniteNumericValues(strategyComparisonTable)
    blockingFindings(end + 1, 1) = ...
        "nonfinite_strategy_output";
end

blockingFindings = unique(blockingFindings);
blockingFindings = blockingFindings(strlength(blockingFindings) > 0);

end

function interpretation = localBuildInterpretation(questionSummaries, ...
    blockingFindings, recommendedStrategyCandidate, roleInfo, ...
    resolvedOptions)

overallLabel = localCollapseInterpretationLabels( ...
    questionSummaries.InterpretationLabel);

if overallLabel == "ready"
    overallRationale = "All four Stage 3 questions remain analytically " + ...
        "supported on the frozen baseline session.";
elseif overallLabel == "caveated"
    overallRationale = "At least one Stage 3 question remains caveated, " + ...
        "but none are blocked on the frozen baseline session.";
else
    overallRationale = "At least one Stage 3 question is blocked, so the " + ...
        "current sync model should not be treated as downstream-ready.";
end

interpretation = struct();
interpretation.OverallLabel = overallLabel;
interpretation.OverallRationale = overallRationale;
interpretation.ReferenceLabel = roleInfo.ReferenceLabel;
interpretation.SurveillanceLabel = roleInfo.SurveillanceLabel;
interpretation.RoleNote = roleInfo.RoleNote;
interpretation.RecommendedStrategyCandidate = ...
    recommendedStrategyCandidate;
interpretation.BlockingFindingCount = numel(blockingFindings);
interpretation.BlockingFindings = blockingFindings;
interpretation.CpiCount = numel(resolvedOptions.CpiLabels);
interpretation.QuestionLabels = table2struct(questionSummaries(:, ...
    ["QuestionId", "InterpretationLabel", "Rationale"]));

end

function metrics = localBuildMetrics(roleInfo, lagTable, ...
    residualFrequencyTable, cpiCoherenceTable, strategyComparisonTable, ...
    questionSummaries, interpretation, blockingFindings, ...
    recommendedStrategyCandidate, resolvedOptions)

metrics = struct();
metrics.stage_id = "G3_Sync_Core";
metrics.reference_label = roleInfo.ReferenceLabel;
metrics.surveillance_label = roleInfo.SurveillanceLabel;
metrics.role_source = roleInfo.RoleSource;
metrics.cpi_definitions = localBuildOptionsOutput(resolvedOptions). ...
    CpiDefinitions;
metrics.lag_table = table2struct(lagTable);
metrics.residual_frequency_table = table2struct( ...
    residualFrequencyTable);
metrics.cpi_coherence_table = table2struct(cpiCoherenceTable);
metrics.strategy_comparison_table = table2struct( ...
    strategyComparisonTable);
metrics.question_summaries = table2struct(questionSummaries);
metrics.recommended_strategy_candidate = recommendedStrategyCandidate;
metrics.blocking_findings = blockingFindings;
metrics.interpretation = interpretation;

end

function optionsOutput = localBuildOptionsOutput(resolvedOptions)

optionsOutput = resolvedOptions;
optionsOutput.CpiLabels = string(resolvedOptions.CpiLabels(:));
optionsOutput.CpiDurations_s = double(resolvedOptions.CpiDurations_s(:));
optionsOutput.WindowHopFractions = ...
    double(resolvedOptions.WindowHopFractions(:));
optionsOutput.CpiSampleCounts = double(resolvedOptions.CpiSampleCounts(:));
optionsOutput.WindowHopSamples = double(resolvedOptions.WindowHopSamples(:));
optionsOutput.CpiDefinitions = localBuildCpiDefinitionOutput( ...
    resolvedOptions.CpiDefinitions);

end

function cpiDefinitionsOutput = localBuildCpiDefinitionOutput( ...
    cpiDefinitions)

cpiDefinitionsOutput = repmat(struct( ...
    "Label", "", ...
    "Duration_s", NaN, ...
    "Samples", NaN, ...
    "WindowHopSamples", NaN ...
    ), numel(cpiDefinitions), 1);

for idx = 1:numel(cpiDefinitions)
    cpiDefinitionsOutput(idx).Label = cpiDefinitions(idx).Label;
    cpiDefinitionsOutput(idx).Duration_s = ...
        cpiDefinitions(idx).Duration_s;
    cpiDefinitionsOutput(idx).Samples = cpiDefinitions(idx).Samples;
    cpiDefinitionsOutput(idx).WindowHopSamples = ...
        cpiDefinitions(idx).WindowHopSamples;
end

end

function value = localTableHasFiniteNumericValues(inputTable)

if isempty(inputTable) || height(inputTable) == 0
    value = false;
    return
end

numericTable = inputTable(:, vartype("numeric"));

if width(numericTable) == 0
    value = true;
    return
end

value = all(isfinite(numericTable{:,:}), "all");

end
