function visuals = helperBuildG3SyncVisuals(sessionData, controlG3)
%HELPERBUILDG3SYNCVISUALS Build compact, control-derived G3 display traces.
%
%   VISUALS = HELPERBUILDG3SYNCVISUALS(SESSIONDATA, CONTROLG3) recomputes
%   one representative short-window correlation, cross-phase, and
%   coherence view using the same G3 methods. It retains display traces
%   only; it does not change the already-derived correction.

arguments
    sessionData (1,1) struct
    controlG3 (1,1) struct
end

localValidateInputs(sessionData, controlG3);
options = controlG3.Options;
windowObservations = controlG3.WindowObservations;
sourceCpiLabel = string(controlG3.GlobalCorrection.SourceCpiLabel);
candidateRows = windowObservations( ...
    windowObservations.CpiLabel == sourceCpiLabel, :);

if isempty(candidateRows)
    error("helperBuildG3SyncVisuals:MissingWindow", ...
        "No %s observation is available for the G3 display.", sourceCpiLabel);
end

representativeRow = candidateRows(1, :);
roleInfo = controlG3.RoleInfo;
scan = sessionData.RadarScans(1);
referenceSignal = double(scan.Samples(:, roleInfo.ReferenceColumnIndex));
surveillanceSignal = double(scan.Samples(:, ...
    roleInfo.SurveillanceColumnIndex));
sampleIndices = representativeRow.WindowStartSample: ...
    representativeRow.WindowStopSample;
referenceWindow = referenceSignal(sampleIndices);
surveillanceWindow = surveillanceSignal(sampleIndices);
sampleRateHz = double(options.SampleRateHz);

[correlationLag, correlationMagnitude] = localBuildCorrelation( ...
    referenceWindow, surveillanceWindow, options);
appliedLag = double(controlG3.GlobalCorrection.AppliedLag_samples);
alignedSurveillance = localApplyIntegerDelay( ...
    surveillanceWindow, appliedLag);
[phaseTime_s, phase_rad, fittedPhase_rad, representativeFrequencyHz] = ...
    localBuildCrossPhase(referenceWindow, alignedSurveillance, ...
    sampleRateHz, options);
[coherenceFrequency_Hz, coherenceMagnitude, coherenceBandMask] = ...
    localBuildCoherence(referenceWindow, alignedSurveillance, ...
    sampleRateHz, options);

visuals = struct( ...
    DerivedCaseId=string(controlG3.DatasetId), ...
    ReusedCaseId="field_plus_geo_target", ...
    ControlDerived=true, ...
    ReusedByInjected=true, ...
    SourceCpiLabel=sourceCpiLabel, ...
    RepresentativeRepetition=double(representativeRow.Repetition), ...
    WindowStart_s=(double(representativeRow.WindowStartSample) - 1.0) ./ ...
    sampleRateHz, ...
    WindowDuration_s=double(representativeRow.CpiDuration_s), ...
    SampleRateHz=sampleRateHz, ...
    CorrelationLag=double(correlationLag(:)), ...
    CorrelationMagnitude=double(correlationMagnitude(:)), ...
    AppliedLag=appliedLag, ...
    PhaseTime_s=double(phaseTime_s(:)), ...
    CrossPhase_rad=double(phase_rad(:)), ...
    FittedPhase_rad=double(fittedPhase_rad(:)), ...
    RepresentativeResidualFrequency_Hz=representativeFrequencyHz, ...
    AppliedResidualFrequency_Hz=double( ...
    controlG3.GlobalCorrection.AppliedResidualFrequency_Hz), ...
    CoherenceFrequency_Hz=double(coherenceFrequency_Hz(:)), ...
    CoherenceMagnitude=double(coherenceMagnitude(:)), ...
    CoherenceBandMask=logical(coherenceBandMask(:)));

numericValues = [ ...
    visuals.CorrelationLag; visuals.CorrelationMagnitude; ...
    visuals.PhaseTime_s; visuals.CrossPhase_rad; visuals.FittedPhase_rad; ...
    visuals.CoherenceFrequency_Hz; visuals.CoherenceMagnitude];
if any(~isfinite(numericValues))
    error("helperBuildG3SyncVisuals:NonfiniteDisplayTrace", ...
        "The representative G3 display traces must be finite.");
end

end

function localValidateInputs(sessionData, controlG3)

requiredSessionFields = ["RadarScans"; "RadarTable"];
requiredG3Fields = [ ...
    "DatasetId"; "Options"; "WindowObservations"; "GlobalCorrection"; ...
    "RoleInfo"];

if ~all(isfield(sessionData, requiredSessionFields)) || ...
        ~all(isfield(controlG3, requiredG3Fields))
    error("helperBuildG3SyncVisuals:InvalidInput", ...
        "Session and control G3 inputs must contain the display contract.");
end

if isempty(sessionData.RadarScans) || ...
        isempty(sessionData.RadarScans(1).Samples)
    error("helperBuildG3SyncVisuals:MissingSamples", ...
        "The control session must retain samples while display traces form.");
end

end

function [lags, magnitude] = localBuildCorrelation( ...
    referenceWindow, surveillanceWindow, options)

sampleCount = min(numel(referenceWindow), ...
    double(options.CorrelationSampleCount));
maximumLag = min(double(options.CorrelationMaxLagSamples), ...
    sampleCount - 1);
[correlation, lags] = xcorr( ...
    referenceWindow(1:sampleCount), surveillanceWindow(1:sampleCount), ...
    maximumLag, "normalized");
magnitude = abs(correlation);

end

function alignedSignal = localApplyIntegerDelay(inputSignal, sampleDelay)

signalLength = numel(inputSignal);
sampleDelay = round(double(sampleDelay));

if sampleDelay > 0
    alignedSignal = [zeros(sampleDelay, 1); ...
        inputSignal(1:end - sampleDelay)];
elseif sampleDelay < 0
    advanceCount = abs(sampleDelay);
    alignedSignal = [inputSignal(advanceCount + 1:end); ...
        zeros(advanceCount, 1)];
else
    alignedSignal = inputSignal;
end

if numel(alignedSignal) ~= signalLength
    error("helperBuildG3SyncVisuals:DelayLength", ...
        "The representative alignment must preserve signal length.");
end

end

function [time_s, phase_rad, fittedPhase_rad, residualFrequencyHz] = ...
    localBuildCrossPhase(referenceWindow, surveillanceWindow, ...
    sampleRateHz, options)

stftWindow = hamming(double(options.SpectrogramWindowLength), "periodic");
[referenceSpectrogram, frequencyHz, time_s] = spectrogram( ...
    referenceWindow, stftWindow, double(options.SpectrogramOverlap), ...
    double(options.SpectrogramNfft), sampleRateHz, "centered");
[surveillanceSpectrogram, ~, ~] = spectrogram( ...
    surveillanceWindow, stftWindow, double(options.SpectrogramOverlap), ...
    double(options.SpectrogramNfft), sampleRateHz, "centered");
referencePower = mean(abs(referenceSpectrogram) .^ 2, 2);
analysisBandMask = abs(frequencyHz) <= ...
    double(options.CoherenceBandEdgeFraction) * sampleRateHz;
bandMask = referencePower >= max(referencePower) * ...
    10.0 ^ (-double(options.SpectrogramBandThreshold_dB) / 10.0) & ...
    analysisBandMask;

if nnz(bandMask) < double(options.SpectrogramMinimumBandBins)
    candidateIndices = find(analysisBandMask);
    [~, order] = sort(referencePower(candidateIndices), "descend");
    keepCount = min(double(options.SpectrogramMinimumBandBins), ...
        numel(order));
    bandMask = false(size(referencePower));
    bandMask(candidateIndices(order(1:keepCount))) = true;
end

crossSpectrum = surveillanceSpectrogram(bandMask, :) .* conj( ...
    referenceSpectrogram(bandMask, :));
phase_rad = unwrap(angle(sum(crossSpectrum, 1))).';
fitCoefficients = polyfit(time_s(:), phase_rad, 1);
fittedPhase_rad = polyval(fitCoefficients, time_s(:));
residualFrequencyHz = double(fitCoefficients(1) ./ (2.0 * pi));

end

function [frequencyHz, magnitude, analysisBandMask] = localBuildCoherence( ...
    referenceWindow, surveillanceWindow, sampleRateHz, options)

coherenceWindow = hamming(double(options.CoherenceWindowLength), ...
    "periodic");
[magnitude, frequencyHz] = mscohere( ...
    referenceWindow, surveillanceWindow, coherenceWindow, ...
    double(options.CoherenceOverlap), double(options.CoherenceNfft), ...
    sampleRateHz);

if max(frequencyHz) > sampleRateHz / 2.0
    frequencyHz = frequencyHz - sampleRateHz / 2.0;
    magnitude = fftshift(magnitude);
end

analysisBandMask = abs(frequencyHz) <= ...
    double(options.CoherenceBandEdgeFraction) * sampleRateHz;

end
