function result = helperAnalyzeG6ProductDiscrimination( ...
    mapProducts, truthTable, context, priorResult)
%HELPERANALYZEG6PRODUCTDISCRIMINATION Run the fixed G6-D detector study.
%
%   RESULT = HELPERANALYZEG6PRODUCTDISCRIMINATION(MAPPRODUCTS, TRUTHTABLE,
%   CONTEXT) applies the preregistered CA-CFAR and nonmaximum-suppression
%   configuration to full G5 map products. Detection generation is
%   completed before TRUTHTABLE is consulted for post-hoc association.
%
%   RESULT = HELPERANALYZEG6PRODUCTDISCRIMINATION(..., PRIORRESULT)
%   appends compact rows to a prior result. Set CONTEXT.Finalize to false
%   for case-by-case accumulation and make a final call with empty maps,
%   CONTEXT.Finalize=true, and the accumulated result to produce campaign
%   summaries, integrity status, and the diagnostic recommendation.

arguments
    mapProducts = struct([])
    truthTable table = table()
    context (1,1) struct = struct()
    priorResult (1,1) struct = struct()
end

resolvedContext = localResolveContext(context, priorResult);
configuration = localResolveDetectorConfiguration(resolvedContext);
result = localInitializeResult(priorResult, configuration, ...
    resolvedContext);

try
    if strlength(resolvedContext.StructuralIssue) > 0
        error( ...
            "helperAnalyzeG6ProductDiscrimination:StructuralIssue", ...
            "%s", resolvedContext.StructuralIssue);
    end

    if ~isempty(mapProducts)
        if ~isstruct(mapProducts)
            error( ...
                "helperAnalyzeG6ProductDiscrimination:InvalidMapProducts", ...
                "Map products must be a struct array.");
        end

        batch = localAnalyzeMapBatch(mapProducts(:), truthTable, ...
            resolvedContext, configuration);
        result = localAppendBatch(result, batch);
    end
catch analysisException
    result = localRecordIssue(result, analysisException);
end

result = localFinalizeResult(result, resolvedContext, configuration);

end

function configuration = localBuildConfiguration()

configuration = helperBuildG6DDetectorConfiguration();

end

function configuration = localResolveDetectorConfiguration(context)

configuration = localBuildConfiguration();

if isfield(context, "DetectorConfiguration") && ...
        ~isempty(context.DetectorConfiguration)
    configuration = context.DetectorConfiguration;
end

localValidateDetectorConfiguration(configuration);

end

function localValidateDetectorConfiguration(configuration)

baseline = localBuildConfiguration();
requiredFields = [ ...
    "SchemaVersion"; "CandidateNames"; "CutDelayLimits_s"; ...
    "CutDopplerLimits_Hz"; "ExpectedCutCount"; "GuardBandSize"; ...
    "TrainingBandSize"; "TrainingCellCount"; "Pfa"; "Alpha"; ...
    "NmsNeighborhood"; "AxisOrientation"; "CfarMethod"; ...
    "AssociationMethod"; "DetectionGenerationTruthBlind"; ...
    "TruthUse"; "ConfigurationMode"; "IsBaseline"; ...
    "SupportStatus"; "ActualCutCount"; "BaselineConfiguration"];

for fieldIndex = 1:numel(requiredFields)
    if ~isfield(configuration, requiredFields(fieldIndex))
        error( ...
            "helperAnalyzeG6ProductDiscrimination:DetectorConfiguration", ...
            "Detector configuration is missing %s.", ...
            requiredFields(fieldIndex));
    end
end

baselineFields = [ ...
    "SchemaVersion"; "CandidateNames"; "GuardBandSize"; ...
    "TrainingBandSize"; "TrainingCellCount"; "Pfa"; "Alpha"; ...
    "NmsNeighborhood"; "AxisOrientation"; "CfarMethod"; ...
    "AssociationMethod"; "DetectionGenerationTruthBlind"; "TruthUse"];

for fieldIndex = 1:numel(baselineFields)
    fieldName = baselineFields(fieldIndex);
    if ~isequal(configuration.(fieldName), baseline.(fieldName))
        error( ...
            "helperAnalyzeG6ProductDiscrimination:DetectorConfiguration", ...
            "Only detector support rectangles may differ from G6-D baseline.");
    end
end

if configuration.IsBaseline
    if configuration.ConfigurationMode ~= "baseline" || ...
            ~isequal(configuration.CutDelayLimits_s, ...
            baseline.CutDelayLimits_s) || ...
            ~isequal(configuration.CutDopplerLimits_Hz, ...
            baseline.CutDopplerLimits_Hz) || ...
            configuration.ExpectedCutCount ~= baseline.ExpectedCutCount
        error( ...
            "helperAnalyzeG6ProductDiscrimination:DetectorConfiguration", ...
            "Baseline detector configuration must exactly match G6-D.");
    end
else
    if configuration.ConfigurationMode ~= ...
            "exploratory_support_override" || ...
            ~isnan(configuration.ExpectedCutCount)
        error( ...
            "helperAnalyzeG6ProductDiscrimination:DetectorConfiguration", ...
            "Non-baseline support requires the explicit exploratory contract.");
    end
end

if numel(configuration.CutDelayLimits_s) ~= 2 || ...
        configuration.CutDelayLimits_s(1) >= ...
        configuration.CutDelayLimits_s(2) || ...
        numel(configuration.CutDopplerLimits_Hz) ~= 2 || ...
        configuration.CutDopplerLimits_Hz(1) >= ...
        configuration.CutDopplerLimits_Hz(2)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:DetectorConfiguration", ...
        "Detector support limits must be strictly increasing pairs.");
end

end

function context = localResolveContext(inputContext, priorResult)

context = struct();
context.CampaignId = "";
context.BackgroundId = "";
context.CaseId = "";
context.Finalize = true;
context.EnforceCampaignCounts = false;
context.ExpectedMapCount = NaN;
context.ExpectedOperatingPointCount = NaN;
context.ExpectedTruthOpportunityCount = NaN;
context.StructuralIssue = "";

if ~isempty(fieldnames(priorResult)) && ...
        isfield(priorResult, "CampaignId")
    context.CampaignId = string(priorResult.CampaignId);
end

fieldNames = fieldnames(inputContext);

for fieldIndex = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIndex};
    context.(fieldName) = inputContext.(fieldName);
end

context.CampaignId = string(context.CampaignId);
context.BackgroundId = string(context.BackgroundId);
context.CaseId = string(context.CaseId);
context.Finalize = logical(context.Finalize);
context.EnforceCampaignCounts = logical( ...
    context.EnforceCampaignCounts);
context.ExpectedMapCount = double(context.ExpectedMapCount);
context.ExpectedOperatingPointCount = double( ...
    context.ExpectedOperatingPointCount);
context.ExpectedTruthOpportunityCount = double( ...
    context.ExpectedTruthOpportunityCount);
context.StructuralIssue = string(context.StructuralIssue);

end

function result = localInitializeResult( ...
    priorResult, configuration, context)

if isempty(fieldnames(priorResult))
    result = struct();
    result.SchemaVersion = ...
        "g6_product_discrimination_compact_v1";
    result.StageId = "G6_Product_Discrimination";
    result.CampaignId = context.CampaignId;
    result.Configuration = configuration;
    result.MapTable = localEmptyMapTable();
    result.OperatingPointTable = localEmptyOperatingPointTable();
    result.TruthOpportunityTable = localEmptyTruthOpportunityTable();
    result.TruthCutDiagnosticTable = ...
        localEmptyTruthCutDiagnosticTable();
    result.DetectionTable = localEmptyDetectionTable();
    result.ProductBackgroundSummaryTable = ...
        localEmptyProductBackgroundSummaryTable();
    result.PairedProductDeltaTable = ...
        localEmptyPairedProductDeltaTable();
    result.IntegrityIssues = strings(0, 1);
else
    result = priorResult;
    localValidatePriorResult(result, configuration);
end

if strlength(result.CampaignId) == 0
    result.CampaignId = context.CampaignId;
end

result.Finalized = false;
result.Recommendation = "pending";
result.RecommendationRationale = ...
    "Case-level compact rows are awaiting final aggregation.";
result.FormalG6FreezeEnabled = false;
result.FormalG8DetectionEnabled = false;
result.ObjectDetectionsEmitted = false;
result.TrackingStarted = false;

end

function localValidatePriorResult(result, configuration)

requiredFields = [ ...
    "Configuration"; "MapTable"; "OperatingPointTable"; ...
    "TruthOpportunityTable"; "TruthCutDiagnosticTable"; ...
    "DetectionTable"; ...
    "IntegrityIssues"];

for fieldIndex = 1:numel(requiredFields)
    if ~isfield(result, requiredFields(fieldIndex))
        error( ...
            "helperAnalyzeG6ProductDiscrimination:InvalidPriorResult", ...
            "Prior result is missing %s.", requiredFields(fieldIndex));
    end
end

semanticFields = [ ...
    "Pfa"; "GuardBandSize"; "TrainingBandSize"; ...
    "CutDelayLimits_s"; "CutDopplerLimits_Hz"; ...
    "NmsNeighborhood"; "ConfigurationMode"; "IsBaseline"];

for fieldIndex = 1:numel(semanticFields)
    fieldName = semanticFields(fieldIndex);
    if ~isequaln(result.Configuration.(fieldName), ...
            configuration.(fieldName))
        error( ...
            "helperAnalyzeG6ProductDiscrimination:ConfigurationMismatch", ...
            "Prior compact rows use a different detector configuration.");
    end
end

if ~isequal(result.Configuration.CandidateNames, ...
        configuration.CandidateNames) || ...
        ~isequal(result.Configuration.Alpha, configuration.Alpha)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:ConfigurationMismatch", ...
        "Prior compact rows use a different detector configuration.");
end

end

function truthTable = localNormalizeTruthTable(truthTable)

if isempty(truthTable)
    truthTable = localEmptyInputTruthTable();
    return
end

requiredVariables = [ ...
    "BackgroundId"; "CaseId"; "CandidateName"; "WindowLabel"; ...
    "EvidenceRole"; "TargetId"; "ExpectedDelay_s"; ...
    "ExpectedDoppler_Hz"; "SearchDelayHalfExtent_s"; ...
    "SearchDopplerHalfExtent_Hz"];
availableVariables = string(truthTable.Properties.VariableNames);
missingVariables = setdiff(requiredVariables, availableVariables);

if ~isempty(missingVariables)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:MissingTruthVariables", ...
        "Truth table is missing variables: %s.", ...
        strjoin(missingVariables, ", "));
end

stringVariables = [ ...
    "BackgroundId"; "CaseId"; "CandidateName"; "WindowLabel"; ...
    "EvidenceRole"; "TargetId"];

for variableIndex = 1:numel(stringVariables)
    variableName = stringVariables(variableIndex);
    truthTable.(variableName) = string(truthTable.(variableName));
end

truthTable = localAddOptionalStringVariable( ...
    truthTable, "SourceCaseId");
truthTable = localAddOptionalStringVariable(truthTable, "Callsign");
truthTable = localAddOptionalStringVariable( ...
    truthTable, "GeometryClass");
validRoles = ismember(truthTable.EvidenceRole, ...
    ["injected"; "matched_control"]);
numericValues = [ ...
    double(truthTable.ExpectedDelay_s), ...
    double(truthTable.ExpectedDoppler_Hz), ...
    double(truthTable.SearchDelayHalfExtent_s), ...
    double(truthTable.SearchDopplerHalfExtent_Hz)];

if any(~validRoles) || any(~isfinite(numericValues), "all") || ...
        any(truthTable.SearchDelayHalfExtent_s <= 0.0) || ...
        any(truthTable.SearchDopplerHalfExtent_Hz <= 0.0)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidTruthTable", ...
        "Truth rows require recognized roles, finite coordinates, and positive search half-extents.");
end

end

function truthTable = localEmptyInputTruthTable()

truthTable = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames={ ...
    'BackgroundId', 'CaseId', 'CandidateName', 'WindowLabel', ...
    'EvidenceRole', 'TargetId', 'ExpectedDelay_s', ...
    'ExpectedDoppler_Hz', 'SearchDelayHalfExtent_s', ...
    'SearchDopplerHalfExtent_Hz', 'SourceCaseId', 'Callsign', ...
    'GeometryClass'});

end

function tableOut = localAddOptionalStringVariable( ...
    tableIn, variableName)

tableOut = tableIn;

if ismember(variableName, string(tableOut.Properties.VariableNames))
    tableOut.(variableName) = string(tableOut.(variableName));
else
    tableOut = addvars(tableOut, strings(height(tableOut), 1), ...
        NewVariableNames=variableName);
end

end

function batch = localAnalyzeMapBatch( ...
    mapProducts, truthTable, context, configuration)

mapRows = repmat(localMapRowTemplate(), numel(mapProducts), 1);
operatingRows = repmat(localOperatingPointRowTemplate(), 0, 1);
detectionRows = repmat(localDetectionRowTemplate(), 0, 1);
truthOpportunityRows = repmat( ...
    localTruthOpportunityRowTemplate(), 0, 1);
truthCutDiagnosticRows = repmat( ...
    localTruthCutDiagnosticRowTemplate(), 0, 1);

for mapIndex = 1:numel(mapProducts)
    [mapRow, mapOperatingRows, mapDetectionRows, ...
        mapTruthOpportunityRows, mapTruthCutDiagnosticRows] = ...
        localAnalyzeOneMap( ...
        mapProducts(mapIndex), truthTable, context, configuration);
    mapRows(mapIndex) = mapRow;
    operatingRows = [operatingRows; ...
        mapOperatingRows(:)]; %#ok<AGROW>
    detectionRows = [detectionRows; ...
        mapDetectionRows(:)]; %#ok<AGROW>
    truthOpportunityRows = [truthOpportunityRows; ...
        mapTruthOpportunityRows(:)]; %#ok<AGROW>
    truthCutDiagnosticRows = [truthCutDiagnosticRows; ...
        mapTruthCutDiagnosticRows(:)]; %#ok<AGROW>
end

batch = struct();
batch.MapTable = struct2table(mapRows);
batch.OperatingPointTable = localStructRowsToTable( ...
    operatingRows, @localEmptyOperatingPointTable);
batch.DetectionTable = localStructRowsToTable( ...
    detectionRows, @localEmptyDetectionTable);
batch.TruthOpportunityTable = localStructRowsToTable( ...
    truthOpportunityRows, @localEmptyTruthOpportunityTable);
batch.TruthCutDiagnosticTable = localStructRowsToTable( ...
    truthCutDiagnosticRows, @localEmptyTruthCutDiagnosticTable);

end

function [mapRow, operatingRows, detectionRows, ...
    truthOpportunityRows, truthCutDiagnosticRows] = localAnalyzeOneMap( ...
    mapProduct, truthTable, context, configuration)

[mapLinear, delayAxis_s, dopplerAxis_Hz, mapMetadata] = ...
    localValidateAndNormalizeMap(mapProduct, context, configuration);
[cutRows, cutColumns, cutIndices] = localBuildCutIndices( ...
    delayAxis_s, dopplerAxis_Hz, configuration);
noiseEstimate = localEstimateCfarNoise( ...
    mapLinear, cutIndices, configuration);
cutPower = double(mapLinear(cutIndices(1, :) + ...
    (cutIndices(2, :) - 1) .* size(mapLinear, 1))).';
noiseEstimate = double(noiseEstimate(:));
thresholdMatrix = noiseEstimate .* configuration.Alpha.';
peakCutIndices = localFindNmsPeaks( ...
    mapLinear, cutRows, cutColumns, configuration);
[operatingRows, detectionRows] = ...
    localGenerateTruthBlindDetections( ...
    mapMetadata, cutIndices, cutPower, noiseEstimate, ...
    thresholdMatrix, peakCutIndices, delayAxis_s, dopplerAxis_Hz, ...
    configuration);
normalizedTruth = localNormalizeTruthTable(truthTable);
mapTruth = localSelectMapTruth(normalizedTruth, mapMetadata);
[operatingRows, detectionRows, truthOpportunityRows, ...
    associationValid] = localAssociatePostHoc( ...
    operatingRows, detectionRows, mapTruth, mapMetadata, ...
    configuration);
truthCutDiagnosticRows = localBuildTruthCutDiagnostics( ...
    mapTruth, mapMetadata, cutRows, cutColumns, ...
    cutPower, noiseEstimate, thresholdMatrix, peakCutIndices, ...
    delayAxis_s, dopplerAxis_Hz, configuration);
detectionCounts = double([operatingRows.DetectionCount]).';
thresholdMonotonic = all(diff(thresholdMatrix, 1, 2) >= 0.0, "all");
detectionCountMonotonic = all(diff(detectionCounts) <= 0.0);
mapRow = localMapRowTemplate();
mapRow.MapId = mapMetadata.MapId;
mapRow.CampaignId = mapMetadata.CampaignId;
mapRow.BackgroundId = mapMetadata.BackgroundId;
mapRow.CaseId = mapMetadata.CaseId;
mapRow.CandidateName = mapMetadata.CandidateName;
mapRow.WindowLabel = mapMetadata.WindowLabel;
mapRow.MapRows = double(size(mapLinear, 1));
mapRow.MapColumns = double(size(mapLinear, 2));
mapRow.CutRowCount = double(numel(cutRows));
mapRow.CutColumnCount = double(numel(cutColumns));
mapRow.CutCount = double(size(cutIndices, 2));
mapRow.CutDelayMinimum_s = delayAxis_s(cutColumns(1));
mapRow.CutDelayMaximum_s = delayAxis_s(cutColumns(end));
mapRow.CutDopplerMinimum_Hz = dopplerAxis_Hz(cutRows(1));
mapRow.CutDopplerMaximum_Hz = dopplerAxis_Hz(cutRows(end));
mapRow.DelayAxisStart_s = delayAxis_s(1);
mapRow.DelayAxisEnd_s = delayAxis_s(end);
mapRow.DelayAxisSpacing_s = median(diff(delayAxis_s));
mapRow.DopplerAxisStart_Hz = dopplerAxis_Hz(1);
mapRow.DopplerAxisEnd_Hz = dopplerAxis_Hz(end);
mapRow.DopplerAxisSpacing_Hz = median(diff(dopplerAxis_Hz));
mapRow.CfarCallCount = 1.0;
mapRow.NoiseEstimateFinite = all(isfinite(noiseEstimate));
mapRow.NoiseEstimateNonnegative = all(noiseEstimate >= 0.0);
mapRow.ThresholdMonotonic = thresholdMonotonic;
mapRow.DetectionCountMonotonic = detectionCountMonotonic;
mapRow.InjectedTruthCount = double(nnz( ...
    mapTruth.EvidenceRole == "injected"));
mapRow.ControlTruthCount = double(nnz( ...
    mapTruth.EvidenceRole == "matched_control"));
mapRow.AssociationValid = associationValid;
mapRow.MapFinite = true;
mapRow.MapNonnegative = true;
mapRow.AxesIncreasing = true;
mapRow.AxisOrientation = configuration.AxisOrientation;

end

function [mapLinear, delayAxis_s, dopplerAxis_Hz, metadata] = ...
    localValidateAndNormalizeMap(mapProduct, context, configuration)

requiredFields = [ ...
    "CandidateName"; "WindowLabel"; "MapLinear"; ...
    "DelayAxis_s"; "DopplerAxis_Hz"];

for fieldIndex = 1:numel(requiredFields)
    if ~isfield(mapProduct, requiredFields(fieldIndex))
        error( ...
            "helperAnalyzeG6ProductDiscrimination:MissingMapField", ...
            "Map product is missing %s.", requiredFields(fieldIndex));
    end
end

mapLinear = mapProduct.MapLinear;
delayAxis_s = double(mapProduct.DelayAxis_s(:).');
dopplerAxis_Hz = double(mapProduct.DopplerAxis_Hz(:));

if ~isnumeric(mapLinear) || ~isreal(mapLinear) || ...
        isempty(mapLinear) || ~ismatrix(mapLinear)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidMap", ...
        "MapLinear must be a nonempty real numeric matrix.");
end

if any(~isfinite(mapLinear), "all") || ...
        any(mapLinear < 0.0, "all")
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidMap", ...
        "MapLinear must contain finite nonnegative power.");
end

if numel(delayAxis_s) ~= size(mapLinear, 2) || ...
        numel(dopplerAxis_Hz) ~= size(mapLinear, 1)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:MapAxisMismatch", ...
        "Map rows must match Doppler and columns must match delay.");
end

if any(~isfinite(delayAxis_s)) || ...
        any(~isfinite(dopplerAxis_Hz)) || ...
        any(diff(delayAxis_s) <= 0.0) || ...
        any(diff(dopplerAxis_Hz) <= 0.0)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidAxes", ...
        "Map axes must be finite and strictly increasing.");
end

candidateName = string(mapProduct.CandidateName);

if ~isscalar(candidateName) || ...
        ~ismember(candidateName, configuration.CandidateNames)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidCandidate", ...
        "Map candidate must be one of the fixed G5 products.");
end

axisOrientation = localMapString(mapProduct, ...
    "AxisOrientation", configuration.AxisOrientation);

if axisOrientation ~= configuration.AxisOrientation
    error( ...
        "helperAnalyzeG6ProductDiscrimination:AxisOrientation", ...
        "Map orientation must be rows Doppler and columns delay.");
end

metadata = struct();
metadata.CampaignId = localMapString( ...
    mapProduct, "CampaignId", context.CampaignId);
metadata.BackgroundId = localMapString( ...
    mapProduct, "BackgroundId", context.BackgroundId);
metadata.CaseId = localMapString( ...
    mapProduct, "CaseId", context.CaseId);
metadata.CandidateName = candidateName;
metadata.WindowLabel = string(mapProduct.WindowLabel);

if strlength(metadata.BackgroundId) == 0 || ...
        strlength(metadata.CaseId) == 0 || ...
        strlength(metadata.WindowLabel) == 0
    error( ...
        "helperAnalyzeG6ProductDiscrimination:MissingMapIdentity", ...
        "Each map requires background, case, candidate, and window identity.");
end

metadata.MapId = metadata.BackgroundId + "|" + ...
    metadata.CaseId + "|" + metadata.CandidateName + "|" + ...
    metadata.WindowLabel;

end

function value = localMapString(inputStruct, fieldName, defaultValue)

value = string(defaultValue);

if isfield(inputStruct, fieldName)
    candidate = string(inputStruct.(fieldName));

    if isscalar(candidate)
        value = candidate;
    end
end

end

function [cutRows, cutColumns, cutIndices] = localBuildCutIndices( ...
    delayAxis_s, dopplerAxis_Hz, configuration)

cutRows = find(dopplerAxis_Hz >= ...
    configuration.CutDopplerLimits_Hz(1) & ...
    dopplerAxis_Hz <= configuration.CutDopplerLimits_Hz(2));
cutColumns = find(delayAxis_s >= ...
    configuration.CutDelayLimits_s(1) & ...
    delayAxis_s <= configuration.CutDelayLimits_s(2));
cutCount = numel(cutRows) .* numel(cutColumns);

if isempty(cutRows) || isempty(cutColumns)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:CutCount", ...
        "The detector support rectangle contains no CUTs.");
end

if configuration.IsBaseline && ...
        ~isequal(cutCount, double(configuration.ExpectedCutCount(1)))
    error( ...
        "helperAnalyzeG6ProductDiscrimination:CutCount", ...
        "The baseline CUT region must contain exactly %d cells; found %d.", ...
        configuration.ExpectedCutCount, cutCount);
end

rowMargin = sum(configuration.GuardBandSize(1) + ...
    configuration.TrainingBandSize(1));
columnMargin = sum(configuration.GuardBandSize(2) + ...
    configuration.TrainingBandSize(2));

if cutRows(1) <= rowMargin || ...
        cutRows(end) > numel(dopplerAxis_Hz) - rowMargin || ...
        cutColumns(1) <= columnMargin || ...
        cutColumns(end) > numel(delayAxis_s) - columnMargin
    error( ...
        "helperAnalyzeG6ProductDiscrimination:CfarGeometry", ...
        "The map does not provide the fixed CFAR training margin around every CUT.");
end

[cutRowGrid, cutColumnGrid] = ndgrid(cutRows, cutColumns);
cutIndices = double([cutRowGrid(:).'; cutColumnGrid(:).']);

end

function noiseEstimate = localEstimateCfarNoise( ...
    mapLinear, cutIndices, configuration)

if exist("phased.CFARDetector2D", "class") ~= 8
    error( ...
        "helperAnalyzeG6ProductDiscrimination:MissingCfarDetector", ...
        "G6-D requires phased.CFARDetector2D.");
end

cfarDetector = phased.CFARDetector2D( ...
    Method=configuration.CfarMethod, ...
    GuardBandSize=configuration.GuardBandSize, ...
    TrainingBandSize=configuration.TrainingBandSize, ...
    ThresholdFactor="Custom", ...
    CustomThresholdFactor=1.0, ...
    NoisePowerOutputPort=true);
[~, noiseEstimate] = cfarDetector(mapLinear, cutIndices);

if numel(noiseEstimate) ~= size(cutIndices, 2) || ...
        any(~isfinite(noiseEstimate)) || ...
        any(noiseEstimate < 0.0)
    error( ...
        "helperAnalyzeG6ProductDiscrimination:InvalidNoiseEstimate", ...
        "CA-CFAR returned an invalid noise estimate.");
end

end

function peakCutIndices = localFindNmsPeaks( ...
    mapLinear, cutRows, cutColumns, configuration)

if exist("imdilate", "file") ~= 2
    error( ...
        "helperAnalyzeG6ProductDiscrimination:MissingImdilate", ...
        "G6-D requires imdilate.");
end

rowRadius = floor(configuration.NmsNeighborhood(1) ./ 2.0);
columnRadius = floor(configuration.NmsNeighborhood(2) ./ 2.0);
cropRows = (cutRows(1) - rowRadius):(cutRows(end) + rowRadius);
cropColumns = (cutColumns(1) - columnRadius): ...
    (cutColumns(end) + columnRadius);
mapCrop = mapLinear(cropRows, cropColumns);
dilatedCrop = imdilate(mapCrop, true( ...
    configuration.NmsNeighborhood));
cutMap = mapLinear(cutRows, cutColumns);
dilatedCut = dilatedCrop( ...
    rowRadius + (1:numel(cutRows)), ...
    columnRadius + (1:numel(cutColumns)));
localMaximumMask = cutMap == dilatedCut;
components = bwconncomp(localMaximumMask, 8);
peakCutIndices = zeros(components.NumObjects, 1);

for componentIndex = 1:components.NumObjects
    [componentRows, componentColumns] = ind2sub( ...
        size(localMaximumMask), ...
        components.PixelIdxList{componentIndex});
    orderedCoordinates = sortrows( ...
        [componentRows(:), componentColumns(:)], [1, 2]);
    peakCutIndices(componentIndex) = sub2ind( ...
        size(localMaximumMask), ...
        orderedCoordinates(1, 1), orderedCoordinates(1, 2));
end

peakCutIndices = sort(peakCutIndices);

end

function [operatingRows, detectionRows] = ...
    localGenerateTruthBlindDetections( ...
    metadata, cutIndices, cutPower, noiseEstimate, thresholdMatrix, ...
    peakCutIndices, delayAxis_s, dopplerAxis_Hz, configuration)

pfaCount = numel(configuration.Pfa);
operatingRows = repmat(localOperatingPointRowTemplate(), ...
    pfaCount, 1);
detectionRows = repmat(localDetectionRowTemplate(), 0, 1);

for pfaIndex = 1:pfaCount
    threshold = thresholdMatrix(:, pfaIndex);
    selectedPeakIndices = peakCutIndices( ...
        cutPower(peakCutIndices) > threshold(peakCutIndices));
    operatingRow = localOperatingPointRowTemplate();
    operatingRow.MapId = metadata.MapId;
    operatingRow.CampaignId = metadata.CampaignId;
    operatingRow.BackgroundId = metadata.BackgroundId;
    operatingRow.CaseId = metadata.CaseId;
    operatingRow.CandidateName = metadata.CandidateName;
    operatingRow.WindowLabel = metadata.WindowLabel;
    operatingRow.PfaIndex = double(pfaIndex);
    operatingRow.Pfa = configuration.Pfa(pfaIndex);
    operatingRow.Alpha = configuration.Alpha(pfaIndex);
    operatingRow.CutCount = double(numel(cutPower));
    operatingRow.ThresholdMinimum = min(threshold);
    operatingRow.ThresholdMedian = median(threshold);
    operatingRow.ThresholdMaximum = max(threshold);
    operatingRow.DetectionCount = double(numel(selectedPeakIndices));
    operatingRow.DetectionGeneratedTruthBlind = true;
    operatingRows(pfaIndex) = operatingRow;

    for detectionOrdinal = 1:numel(selectedPeakIndices)
        cutIndex = selectedPeakIndices(detectionOrdinal);
        rowIndex = cutIndices(1, cutIndex);
        columnIndex = cutIndices(2, cutIndex);
        detectionRow = localDetectionRowTemplate();
        detectionRow.DetectionId = metadata.MapId + "|pfa_" + ...
            compose("%02d", pfaIndex) + "|detection_" + ...
            compose("%05d", detectionOrdinal);
        detectionRow.MapId = metadata.MapId;
        detectionRow.CampaignId = metadata.CampaignId;
        detectionRow.BackgroundId = metadata.BackgroundId;
        detectionRow.CaseId = metadata.CaseId;
        detectionRow.CandidateName = metadata.CandidateName;
        detectionRow.WindowLabel = metadata.WindowLabel;
        detectionRow.PfaIndex = double(pfaIndex);
        detectionRow.Pfa = configuration.Pfa(pfaIndex);
        detectionRow.RowIndex = double(rowIndex);
        detectionRow.ColumnIndex = double(columnIndex);
        detectionRow.Delay_s = delayAxis_s(columnIndex);
        detectionRow.Doppler_Hz = dopplerAxis_Hz(rowIndex);
        detectionRow.PowerLinear = cutPower(cutIndex);
        detectionRow.NoiseEstimate = noiseEstimate(cutIndex);
        detectionRow.Threshold = threshold(cutIndex);
        detectionRow.DetectionGeneratedTruthBlind = true;
        detectionRows(end + 1, 1) = detectionRow; %#ok<AGROW>
    end
end

end

function mapTruth = localSelectMapTruth(truthTable, metadata)

if isempty(truthTable)
    mapTruth = truthTable;
    return
end

mask = truthTable.BackgroundId == metadata.BackgroundId & ...
    truthTable.CaseId == metadata.CaseId & ...
    truthTable.CandidateName == metadata.CandidateName & ...
    truthTable.WindowLabel == metadata.WindowLabel;
mapTruth = truthTable(mask, :);

end

function [operatingRows, detectionRows, truthOpportunityRows, ...
    associationValid] = localAssociatePostHoc( ...
    operatingRows, detectionRows, mapTruth, metadata, configuration)

truthOpportunityRows = repmat( ...
    localTruthOpportunityRowTemplate(), 0, 1);
associationValid = true;

for pfaIndex = 1:numel(configuration.Pfa)
    detectionIndices = find( ...
        [detectionRows.PfaIndex].' == pfaIndex);
    [pairs, normalizedDelayError, normalizedDopplerError] = ...
        localMatchTruthToDetections( ...
        mapTruth, detectionRows, detectionIndices);

    for pairIndex = 1:size(pairs, 1)
        truthIndex = pairs(pairIndex, 1);
        localDetectionIndex = pairs(pairIndex, 2);
        detectionIndex = detectionIndices(localDetectionIndex);
        evidenceRole = mapTruth.EvidenceRole(truthIndex);

        if evidenceRole == "injected"
            associationRole = "target_hit";
        else
            associationRole = "nuisance_control_alarm";
        end

        detectionRows(detectionIndex).AssociationRole = ...
            associationRole;
        detectionRows(detectionIndex).TargetId = ...
            mapTruth.TargetId(truthIndex);
        detectionRows(detectionIndex).SourceCaseId = ...
            mapTruth.SourceCaseId(truthIndex);
        detectionRows(detectionIndex).NormalizedDelayError = ...
            normalizedDelayError(truthIndex, localDetectionIndex);
        detectionRows(detectionIndex).NormalizedDopplerError = ...
            normalizedDopplerError(truthIndex, localDetectionIndex);
        detectionRows(detectionIndex).AssociationCost = hypot( ...
            normalizedDelayError(truthIndex, localDetectionIndex), ...
            normalizedDopplerError(truthIndex, localDetectionIndex));
        detectionRows(detectionIndex).TruthUsedPostHoc = true;
    end

    injectedTruthIndices = find( ...
        mapTruth.EvidenceRole == "injected");

    for injectedIndex = 1:numel(injectedTruthIndices)
        truthIndex = injectedTruthIndices(injectedIndex);
        pairRow = find(pairs(:, 1) == truthIndex, 1, "first");
        opportunity = localTruthOpportunityRowTemplate();
        opportunity.MapId = metadata.MapId;
        opportunity.CampaignId = metadata.CampaignId;
        opportunity.BackgroundId = metadata.BackgroundId;
        opportunity.CaseId = metadata.CaseId;
        opportunity.SourceCaseId = ...
            mapTruth.SourceCaseId(truthIndex);
        opportunity.CandidateName = metadata.CandidateName;
        opportunity.WindowLabel = metadata.WindowLabel;
        opportunity.PfaIndex = double(pfaIndex);
        opportunity.Pfa = configuration.Pfa(pfaIndex);
        opportunity.TargetId = mapTruth.TargetId(truthIndex);
        opportunity.Callsign = mapTruth.Callsign(truthIndex);
        opportunity.GeometryClass = ...
            mapTruth.GeometryClass(truthIndex);
        opportunity.ExpectedDelay_s = double( ...
            mapTruth.ExpectedDelay_s(truthIndex));
        opportunity.ExpectedDoppler_Hz = double( ...
            mapTruth.ExpectedDoppler_Hz(truthIndex));
        opportunity.SearchDelayHalfExtent_s = double( ...
            mapTruth.SearchDelayHalfExtent_s(truthIndex));
        opportunity.SearchDopplerHalfExtent_Hz = double( ...
            mapTruth.SearchDopplerHalfExtent_Hz(truthIndex));
        opportunity.TruthUsedPostHoc = true;

        if ~isempty(pairRow)
            localDetectionIndex = pairs(pairRow, 2);
            detectionIndex = detectionIndices(localDetectionIndex);
            opportunity.Matched = true;
            opportunity.DetectionId = ...
                detectionRows(detectionIndex).DetectionId;
            opportunity.NormalizedDelayError = ...
                normalizedDelayError(truthIndex, localDetectionIndex);
            opportunity.NormalizedDopplerError = ...
                normalizedDopplerError( ...
                truthIndex, localDetectionIndex);
            opportunity.AssociationCost = hypot( ...
                opportunity.NormalizedDelayError, ...
                opportunity.NormalizedDopplerError);
        end

        truthOpportunityRows(end + 1, 1) = ...
            opportunity; %#ok<AGROW>
    end

    associationRoles = string( ...
        {detectionRows(detectionIndices).AssociationRole}).';
    operatingRows(pfaIndex).TargetOpportunityCount = ...
        double(numel(injectedTruthIndices));
    operatingRows(pfaIndex).TargetHitCount = ...
        double(nnz(associationRoles == "target_hit"));
    operatingRows(pfaIndex).ControlAlarmCount = ...
        double(nnz(associationRoles == ...
        "nuisance_control_alarm"));
    operatingRows(pfaIndex).UnmatchedDetectionCount = ...
        double(nnz(associationRoles == "unmatched"));
    operatingRows(pfaIndex).AssociationValid = true;

    if ~isempty(pairs)
        associationValid = associationValid && ...
            numel(unique(pairs(:, 1))) == size(pairs, 1) && ...
            numel(unique(pairs(:, 2))) == size(pairs, 1);
    end
end

end

function [pairs, normalizedDelayError, normalizedDopplerError] = ...
    localMatchTruthToDetections( ...
    mapTruth, detectionRows, detectionIndices)

truthCount = height(mapTruth);
detectionCount = numel(detectionIndices);
normalizedDelayError = inf(truthCount, detectionCount);
normalizedDopplerError = inf(truthCount, detectionCount);
pairs = zeros(0, 2);

if truthCount == 0 || detectionCount == 0
    return
end

detectionDelay_s = double( ...
    [detectionRows(detectionIndices).Delay_s]);
detectionDoppler_Hz = double( ...
    [detectionRows(detectionIndices).Doppler_Hz]);
normalizedDelayError = abs( ...
    double(mapTruth.ExpectedDelay_s) - detectionDelay_s) ./ ...
    double(mapTruth.SearchDelayHalfExtent_s);
normalizedDopplerError = abs( ...
    double(mapTruth.ExpectedDoppler_Hz) - detectionDoppler_Hz) ./ ...
    double(mapTruth.SearchDopplerHalfExtent_Hz);
valid = normalizedDelayError <= 1.0 & ...
    normalizedDopplerError <= 1.0;
cost = hypot(normalizedDelayError, normalizedDopplerError);
cost(~valid) = Inf;
pairs = matchpairs(cost, 2.0, "min");

if ~isempty(pairs)
    pairLinearIndices = sub2ind(size(cost), ...
        pairs(:, 1), pairs(:, 2));
    pairs = pairs(isfinite(cost(pairLinearIndices)), :);
end

end

function diagnosticRows = localBuildTruthCutDiagnostics( ...
    mapTruth, metadata, cutRows, cutColumns, cutPower, ...
    noiseEstimate, thresholdMatrix, peakCutIndices, delayAxis_s, ...
    dopplerAxis_Hz, configuration)

diagnosticRows = repmat(localTruthCutDiagnosticRowTemplate(), 0, 1);

for truthIndex = 1:height(mapTruth)
    [selectedRow, selectedColumn] = ...
        localSelectRepresentativeTruthCut( ...
        double(mapTruth.ExpectedDelay_s(truthIndex)), ...
        double(mapTruth.ExpectedDoppler_Hz(truthIndex)), ...
        double(mapTruth.SearchDelayHalfExtent_s(truthIndex)), ...
        double(mapTruth.SearchDopplerHalfExtent_Hz(truthIndex)), ...
        delayAxis_s, dopplerAxis_Hz);
    rowPosition = find(cutRows == selectedRow, 1);
    columnPosition = find(cutColumns == selectedColumn, 1);
    cutWithinDetectorSupport = ~isempty(rowPosition) && ...
        ~isempty(columnPosition);

    if cutWithinDetectorSupport
        cutIndex = sub2ind( ...
            [numel(cutRows), numel(cutColumns)], ...
            rowPosition, columnPosition);
    else
        cutIndex = NaN;
    end

    for pfaIndex = 1:numel(configuration.Pfa)
        diagnostic = localTruthCutDiagnosticRowTemplate();
        diagnostic.MapId = metadata.MapId;
        diagnostic.CampaignId = metadata.CampaignId;
        diagnostic.BackgroundId = metadata.BackgroundId;
        diagnostic.CaseId = metadata.CaseId;
        diagnostic.CandidateName = metadata.CandidateName;
        diagnostic.WindowLabel = metadata.WindowLabel;
        diagnostic.EvidenceRole = mapTruth.EvidenceRole(truthIndex);
        diagnostic.TargetId = mapTruth.TargetId(truthIndex);
        diagnostic.PfaIndex = double(pfaIndex);
        diagnostic.Pfa = configuration.Pfa(pfaIndex);
        diagnostic.ExpectedDelay_s = ...
            double(mapTruth.ExpectedDelay_s(truthIndex));
        diagnostic.ExpectedDoppler_Hz = ...
            double(mapTruth.ExpectedDoppler_Hz(truthIndex));
        diagnostic.SelectedRowIndex = double(selectedRow);
        diagnostic.SelectedColumnIndex = double(selectedColumn);
        diagnostic.SelectedCutDelay_s = delayAxis_s(selectedColumn);
        diagnostic.SelectedCutDoppler_Hz = dopplerAxis_Hz(selectedRow);
        diagnostic.TruthCenterWithinDetectorSupport = ...
            diagnostic.ExpectedDelay_s >= ...
            configuration.CutDelayLimits_s(1) && ...
            diagnostic.ExpectedDelay_s <= ...
            configuration.CutDelayLimits_s(2) && ...
            diagnostic.ExpectedDoppler_Hz >= ...
            configuration.CutDopplerLimits_Hz(1) && ...
            diagnostic.ExpectedDoppler_Hz <= ...
            configuration.CutDopplerLimits_Hz(2);
        diagnostic.CutWithinDetectorSupport = ...
            cutWithinDetectorSupport;
        diagnostic.TruthUsedPostHoc = true;

        if cutWithinDetectorSupport
            diagnostic.CutPowerLinear = cutPower(cutIndex);
            diagnostic.LocalNoiseEstimate = noiseEstimate(cutIndex);
            diagnostic.CfarThreshold = ...
                thresholdMatrix(cutIndex, pfaIndex);
            diagnostic.NmsRetained = any( ...
                peakCutIndices == cutIndex);
            diagnostic.DetectionPassesThreshold = ...
                diagnostic.CutPowerLinear > diagnostic.CfarThreshold;
        end

        diagnosticRows(end + 1, 1) = diagnostic; %#ok<AGROW>
    end
end

end

function [rowIndex, columnIndex] = localSelectRepresentativeTruthCut( ...
    expectedDelay_s, expectedDoppler_Hz, delayHalfExtent_s, ...
    dopplerHalfExtent_Hz, delayAxis_s, dopplerAxis_Hz)

delayCandidates = find(abs(delayAxis_s - expectedDelay_s) <= ...
    delayHalfExtent_s);

if isempty(delayCandidates)
    [~, columnIndex] = min(abs(delayAxis_s - expectedDelay_s));
else
    columnIndex = delayCandidates(end);
end

dopplerCandidates = find(abs(dopplerAxis_Hz - expectedDoppler_Hz) <= ...
    dopplerHalfExtent_Hz);

if isempty(dopplerCandidates)
    [~, rowIndex] = min(abs(dopplerAxis_Hz - expectedDoppler_Hz));
else
    [~, localIndex] = min(abs( ...
        dopplerAxis_Hz(dopplerCandidates) - expectedDoppler_Hz));
    rowIndex = dopplerCandidates(localIndex);
end

end

function result = localAppendBatch(result, batch)

result.MapTable = [result.MapTable; batch.MapTable];
result.OperatingPointTable = [ ...
    result.OperatingPointTable; batch.OperatingPointTable];
result.TruthOpportunityTable = [ ...
    result.TruthOpportunityTable; batch.TruthOpportunityTable];
result.TruthCutDiagnosticTable = [ ...
    result.TruthCutDiagnosticTable; batch.TruthCutDiagnosticTable];
result.DetectionTable = [ ...
    result.DetectionTable; batch.DetectionTable];

end

function result = localRecordIssue(result, exception)

issue = string(exception.identifier) + ": " + ...
    string(exception.message);
result.IntegrityIssues(end + 1, 1) = issue;

end

function result = localFinalizeResult(result, context, configuration)

result.AnalysisTimestampZ = string(datetime("now", ...
    TimeZone="UTC", Format="yyyyMMdd'T'HHmmssSSS'Z'"));
result.Configuration = localRecordActualCutCount( ...
    configuration, result.MapTable);
result.ProductBackgroundSummaryTable = ...
    localBuildProductBackgroundSummary( ...
    result.OperatingPointTable, configuration);
result.PairedProductDeltaTable = localBuildPairedProductDeltas( ...
    result.ProductBackgroundSummaryTable, configuration);
result.Integrity = localBuildIntegrity(result, context, configuration);

if context.Finalize
    [result.Recommendation, result.RecommendationRationale] = ...
        localBuildRecommendation( ...
        result.ProductBackgroundSummaryTable, ...
        result.PairedProductDeltaTable, result.Integrity, ...
        configuration);
else
    result.Recommendation = "pending";
    result.RecommendationRationale = ...
        "Case-level compact rows are awaiting final aggregation.";
end

result.Finalized = context.Finalize;
result.CompactResultAudit = localAuditCompactResult(result);
result.Integrity.CompactResultValid = ...
    result.CompactResultAudit.Compact;
result.Integrity.AllPassed = result.Integrity.AllPassed && ...
    result.Integrity.CompactResultValid;

if context.Finalize && ~result.Integrity.AllPassed
    result.Recommendation = "blocked";
    result.RecommendationRationale = ...
        "At least one structural, count, map, axis, CFAR, association, or compact-retention integrity check failed.";
end

end

function integrity = localBuildIntegrity( ...
    result, context, configuration)

mapTable = result.MapTable;
operatingTable = result.OperatingPointTable;
truthTable = result.TruthOpportunityTable;
expectedMapCount = height(mapTable);
expectedOperatingPointCount = expectedMapCount .* ...
    numel(configuration.Pfa);
expectedTruthOpportunityCount = sum( ...
    mapTable.InjectedTruthCount) .* numel(configuration.Pfa);

if context.EnforceCampaignCounts
    expectedMapCount = context.ExpectedMapCount;
    expectedOperatingPointCount = ...
        context.ExpectedOperatingPointCount;
    expectedTruthOpportunityCount = ...
        context.ExpectedTruthOpportunityCount;
end

mapIdentityValid = numel(unique(mapTable.MapId)) == ...
    height(mapTable);
productGroupsComplete = localProductGroupsComplete( ...
    mapTable, configuration);
axesCompatible = localProductAxesCompatible(mapTable);
structuralValid = isempty(result.IntegrityIssues) && ...
    mapIdentityValid && productGroupsComplete;
countValid = height(mapTable) == expectedMapCount && ...
    height(operatingTable) == expectedOperatingPointCount && ...
    height(truthTable) == expectedTruthOpportunityCount;
mapValid = all(mapTable.MapFinite) && ...
    all(mapTable.MapNonnegative);
cutCountAccountingValid = localCutCountAccountingValid( ...
    mapTable, configuration);
axisValid = all(mapTable.AxesIncreasing) && ...
    cutCountAccountingValid && ...
    axesCompatible;
cfarValid = all(mapTable.CfarCallCount == 1.0) && ...
    all(mapTable.NoiseEstimateFinite) && ...
    all(mapTable.NoiseEstimateNonnegative) && ...
    all(mapTable.ThresholdMonotonic) && ...
    all(mapTable.DetectionCountMonotonic);
matchedMask = logical(truthTable{:, "Matched"});
normalizedDelayErrors = ...
    double(truthTable{:, "NormalizedDelayError"});
normalizedDopplerErrors = ...
    double(truthTable{:, "NormalizedDopplerError"});
associationValid = all(mapTable.AssociationValid) && ...
    all(operatingTable.AssociationValid) && ...
    all(normalizedDelayErrors(matchedMask) <= 1.0) && ...
    all(normalizedDopplerErrors(matchedMask) <= 1.0);
integrity = struct();
integrity.StructuralValid = structuralValid;
integrity.CountValid = countValid;
integrity.MapValid = mapValid;
integrity.AxisValid = axisValid;
integrity.CfarValid = cfarValid;
integrity.AssociationValid = associationValid;
integrity.CompactResultValid = true;
integrity.MapIdentityValid = mapIdentityValid;
integrity.ProductGroupsComplete = productGroupsComplete;
integrity.ProductAxesCompatible = axesCompatible;
integrity.CutCountAccountingValid = cutCountAccountingValid;
integrity.ExpectedMapCount = double(expectedMapCount);
integrity.ObservedMapCount = double(height(mapTable));
integrity.ExpectedOperatingPointCount = ...
    double(expectedOperatingPointCount);
integrity.ObservedOperatingPointCount = ...
    double(height(operatingTable));
integrity.ExpectedTruthOpportunityCount = ...
    double(expectedTruthOpportunityCount);
integrity.ObservedTruthOpportunityCount = ...
    double(height(truthTable));
integrity.TruthUsedOnlyPostHoc = true;
integrity.DetectionGenerationTruthBlind = true;
integrity.RawIqRetained = false;
integrity.FullMapCollectionRetained = false;
integrity.ObjectDetectionsEmitted = false;
integrity.AllPassed = structuralValid && countValid && ...
    mapValid && axisValid && cfarValid && associationValid;

end

function configuration = localRecordActualCutCount(configuration, mapTable)

if isempty(mapTable)
    configuration.ActualCutCount = NaN;
    return
end

configuration.ActualCutCount = unique(double(mapTable.CutCount), "stable");

end

function valid = localCutCountAccountingValid(mapTable, configuration)

if isempty(mapTable)
    valid = false;
    return
end

cutCounts = double(mapTable.CutCount);

if configuration.IsBaseline
    valid = all(cutCounts == configuration.ExpectedCutCount);
else
    valid = all(isfinite(cutCounts)) && all(cutCounts > 0.0) && ...
        isscalar(unique(cutCounts));
end

end

function complete = localProductGroupsComplete(mapTable, configuration)

complete = ~isempty(mapTable);

if isempty(mapTable)
    return
end

groupKeys = mapTable.BackgroundId + "|" + ...
    mapTable.CaseId + "|" + mapTable.WindowLabel;
uniqueKeys = unique(groupKeys);

for keyIndex = 1:numel(uniqueKeys)
    products = mapTable.CandidateName( ...
        groupKeys == uniqueKeys(keyIndex));
    groupComplete = numel(products) == ...
        numel(configuration.CandidateNames) && ...
        isequal(sort(products), ...
        sort(configuration.CandidateNames));
    complete = complete && groupComplete;
end

end

function compatible = localProductAxesCompatible(mapTable)

compatible = ~isempty(mapTable);

if isempty(mapTable)
    return
end

groupKeys = mapTable.BackgroundId + "|" + ...
    mapTable.CaseId + "|" + mapTable.WindowLabel;
uniqueKeys = unique(groupKeys);
numericVariables = [ ...
    "MapRows"; "MapColumns"; "DelayAxisStart_s"; ...
    "DelayAxisEnd_s"; "DelayAxisSpacing_s"; ...
    "DopplerAxisStart_Hz"; "DopplerAxisEnd_Hz"; ...
    "DopplerAxisSpacing_Hz"];

for keyIndex = 1:numel(uniqueKeys)
    rows = mapTable(groupKeys == uniqueKeys(keyIndex), :);

    for variableIndex = 1:numel(numericVariables)
        values = double(rows.(numericVariables(variableIndex)));
        scale = max(1.0, max(abs(values)));
        compatible = compatible && ...
            max(values) - min(values) <= 100.0 .* eps(scale);
    end
end

end

function summaryTable = localBuildProductBackgroundSummary( ...
    operatingTable, configuration)

if isempty(operatingTable)
    summaryTable = localEmptyProductBackgroundSummaryTable();
    return
end

backgroundIds = unique(operatingTable.BackgroundId, "stable");
rowCount = numel(backgroundIds) .* ...
    numel(configuration.CandidateNames) .* ...
    numel(configuration.Pfa);
rows = repmat(localProductBackgroundSummaryRowTemplate(), ...
    rowCount, 1);
rowIndex = 0;

for backgroundIndex = 1:numel(backgroundIds)
    backgroundId = backgroundIds(backgroundIndex);

    for candidateIndex = 1:numel(configuration.CandidateNames)
        candidateName = configuration.CandidateNames(candidateIndex);

        for pfaIndex = 1:numel(configuration.Pfa)
            pfa = configuration.Pfa(pfaIndex);
            subset = operatingTable( ...
                operatingTable.BackgroundId == backgroundId & ...
                operatingTable.CandidateName == candidateName & ...
                operatingTable.PfaIndex == pfaIndex, :);
            opportunityCount = sum(subset.TargetOpportunityCount);
            hitCount = sum(subset.TargetHitCount);
            rowIndex = rowIndex + 1;
            rows(rowIndex) = struct( ...
                "BackgroundId", backgroundId, ...
                "CandidateName", candidateName, ...
                "PfaIndex", double(pfaIndex), ...
                "Pfa", pfa, ...
                "MapCount", double(height(subset)), ...
                "TargetOpportunityCount", ...
                double(opportunityCount), ...
                "TargetHitCount", double(hitCount), ...
                "TargetHitRate", localSafeRatio( ...
                hitCount, opportunityCount), ...
                "ControlAlarmCount", double(sum( ...
                subset.ControlAlarmCount)), ...
                "DetectionCount", double(sum( ...
                subset.DetectionCount)), ...
                "UnmatchedDetectionCount", double(sum( ...
                subset.UnmatchedDetectionCount)));
        end
    end
end

summaryTable = struct2table(rows);

end

function deltaTable = localBuildPairedProductDeltas( ...
    summaryTable, configuration)

if isempty(summaryTable)
    deltaTable = localEmptyPairedProductDeltaTable();
    return
end

backgroundIds = unique(summaryTable.BackgroundId, "stable");
pairCountPerCell = numel(configuration.CandidateNames) .* ...
    (numel(configuration.CandidateNames) - 1);
rowCount = numel(backgroundIds) .* ...
    numel(configuration.Pfa) .* pairCountPerCell;
rows = repmat(localPairedProductDeltaRowTemplate(), rowCount, 1);
rowIndex = 0;

for backgroundIndex = 1:numel(backgroundIds)
    backgroundId = backgroundIds(backgroundIndex);

    for pfaIndex = 1:numel(configuration.Pfa)
        for candidateIndex = 1:numel(configuration.CandidateNames)
            candidateName = ...
                configuration.CandidateNames(candidateIndex);

            for comparatorIndex = 1:numel(configuration.CandidateNames)
                comparatorName = ...
                    configuration.CandidateNames(comparatorIndex);

                if candidateName == comparatorName
                    continue
                end

                candidate = summaryTable( ...
                    summaryTable.BackgroundId == backgroundId & ...
                    summaryTable.CandidateName == candidateName & ...
                    summaryTable.PfaIndex == pfaIndex, :);
                comparator = summaryTable( ...
                    summaryTable.BackgroundId == backgroundId & ...
                    summaryTable.CandidateName == comparatorName & ...
                    summaryTable.PfaIndex == pfaIndex, :);
                targetHitDelta = candidate.TargetHitCount - ...
                    comparator.TargetHitCount;
                controlAlarmDelta = candidate.ControlAlarmCount - ...
                    comparator.ControlAlarmCount;
                noWorse = targetHitDelta >= 0.0 && ...
                    controlAlarmDelta <= 0.0;
                strictlyBetter = targetHitDelta > 0.0 || ...
                    controlAlarmDelta < 0.0;
                rowIndex = rowIndex + 1;
                rows(rowIndex) = struct( ...
                    "BackgroundId", backgroundId, ...
                    "PfaIndex", double(pfaIndex), ...
                    "Pfa", configuration.Pfa(pfaIndex), ...
                    "CandidateName", candidateName, ...
                    "ComparatorName", comparatorName, ...
                    "TargetHitDelta", double(targetHitDelta), ...
                    "ControlAlarmDelta", ...
                    double(controlAlarmDelta), ...
                    "NoWorseAtCell", noWorse, ...
                    "StrictlyBetterAtCell", ...
                    noWorse && strictlyBetter);
            end
        end
    end
end

deltaTable = struct2table(rows);

end

function [recommendation, rationale] = localBuildRecommendation( ...
    summaryTable, deltaTable, integrity, configuration)

if ~integrity.AllPassed
    recommendation = "blocked";
    rationale = ...
        "At least one structural, count, map, axis, CFAR, or association integrity check failed.";
    return
end

if sum(summaryTable.TargetHitCount) == 0.0
    recommendation = "insufficient";
    rationale = ...
        "The complete valid sweep produced no matched truth detections.";
    return
end

robustDominance = false(numel(configuration.CandidateNames), 1);

for candidateIndex = 1:numel(configuration.CandidateNames)
    candidateName = configuration.CandidateNames(candidateIndex);
    candidateRows = deltaTable( ...
        deltaTable.CandidateName == candidateName, :);
    robustDominance(candidateIndex) = ...
        all(candidateRows.NoWorseAtCell) && ...
        any(candidateRows.StrictlyBetterAtCell);
end

exactTie = localAllProductsExactlyTied(summaryTable, configuration);
dominantProducts = configuration.CandidateNames(robustDominance);

if isscalar(dominantProducts) && ...
        dominantProducts == "conservative_lms"
    recommendation = "conservative";
    rationale = ...
        "Conservative LMS is no worse in target hits and control alarms in every background/Pfa cell and is strictly better in at least one cell.";
elseif isscalar(dominantProducts) && ...
        dominantProducts == "aggressive_lms"
    recommendation = "aggressive";
    rationale = ...
        "Aggressive LMS is no worse in target hits and control alarms in every background/Pfa cell and is strictly better in at least one cell.";
elseif isscalar(dominantProducts) && dominantProducts == "none"
    recommendation = "none";
    rationale = ...
        "No mitigation robustly dominates both LMS alternatives.";
elseif exactTie
    recommendation = "none";
    rationale = ...
        "All products are exactly tied and the sweep contains usable target detections.";
else
    recommendation = "retune";
    rationale = ...
        "Valid informative evidence contains product/background or operating-point crossovers without one robust winner.";
end

end

function tied = localAllProductsExactlyTied( ...
    summaryTable, configuration)

tied = true;
backgroundIds = unique(summaryTable.BackgroundId);

for backgroundIndex = 1:numel(backgroundIds)
    for pfaIndex = 1:numel(configuration.Pfa)
        rows = summaryTable( ...
            summaryTable.BackgroundId == ...
            backgroundIds(backgroundIndex) & ...
            summaryTable.PfaIndex == pfaIndex, :);
        tied = tied && isscalar(unique(rows.TargetHitCount)) && ...
            isscalar(unique(rows.ControlAlarmCount));
    end
end

end

function value = localSafeRatio(numerator, denominator)

if denominator == 0.0
    value = NaN;
else
    value = double(numerator) ./ double(denominator);
end

end

function audit = localAuditCompactResult(result)

prohibitedNames = [ ...
    "rawiq"; "samples"; "maplinear"; "fullmapcollection"; ...
    "objectdetection"; "objectdetections"];
paths = localFindProhibitedFields(result, "", prohibitedNames);
audit = struct();
audit.Compact = isempty(paths);
audit.RawIqPresent = any(contains(paths, ...
    "rawiq", IgnoreCase=true)) || ...
    any(contains(paths, ".samples", IgnoreCase=true));
audit.FullMapCollectionPresent = any(contains(paths, ...
    "maplinear", IgnoreCase=true)) || ...
    any(contains(paths, "fullmapcollection", IgnoreCase=true));
audit.ObjectDetectionPresent = any(contains(paths, ...
    "objectdetection", IgnoreCase=true));
audit.ProhibitedFieldPaths = paths;

end

function paths = localFindProhibitedFields( ...
    value, currentPath, prohibitedNames)

paths = strings(0, 1);

if isstruct(value)
    fieldNames = string(fieldnames(value));

    for elementIndex = 1:numel(value)
        for fieldIndex = 1:numel(fieldNames)
            fieldName = fieldNames(fieldIndex);
            fieldPath = currentPath + "." + fieldName;

            if any(lower(fieldName) == prohibitedNames)
                paths(end + 1, 1) = fieldPath; %#ok<AGROW>
            end

            nestedPaths = localFindProhibitedFields( ...
                value(elementIndex).(fieldName), ...
                fieldPath, prohibitedNames);
            paths = [paths; nestedPaths]; %#ok<AGROW>
        end
    end
elseif istable(value)
    variableNames = string(value.Properties.VariableNames);

    for variableIndex = 1:numel(variableNames)
        if any(lower(variableNames(variableIndex)) == prohibitedNames)
            paths(end + 1, 1) = currentPath + "." + ...
                variableNames(variableIndex); %#ok<AGROW>
        end
    end
elseif iscell(value)
    for elementIndex = 1:numel(value)
        nestedPaths = localFindProhibitedFields( ...
            value{elementIndex}, currentPath + "{" + ...
            elementIndex + "}", prohibitedNames);
        paths = [paths; nestedPaths]; %#ok<AGROW>
    end
end

end

function tableOut = localStructRowsToTable(rows, emptyTableFunction)

if isempty(rows)
    tableOut = emptyTableFunction();
else
    tableOut = struct2table(rows);
end

end

function tableOut = localEmptyMapTable()

tableOut = struct2table(repmat(localMapRowTemplate(), 0, 1));

end

function tableOut = localEmptyOperatingPointTable()

tableOut = struct2table(repmat( ...
    localOperatingPointRowTemplate(), 0, 1));

end

function tableOut = localEmptyDetectionTable()

tableOut = struct2table(repmat( ...
    localDetectionRowTemplate(), 0, 1));

end

function tableOut = localEmptyTruthOpportunityTable()

tableOut = struct2table(repmat( ...
    localTruthOpportunityRowTemplate(), 0, 1));

end

function tableOut = localEmptyTruthCutDiagnosticTable()

tableOut = struct2table(repmat( ...
    localTruthCutDiagnosticRowTemplate(), 0, 1));

end

function tableOut = localEmptyProductBackgroundSummaryTable()

tableOut = struct2table(repmat( ...
    localProductBackgroundSummaryRowTemplate(), 0, 1));

end

function tableOut = localEmptyPairedProductDeltaTable()

tableOut = struct2table(repmat( ...
    localPairedProductDeltaRowTemplate(), 0, 1));

end

function row = localMapRowTemplate()

row = struct( ...
    "MapId", "", ...
    "CampaignId", "", ...
    "BackgroundId", "", ...
    "CaseId", "", ...
    "CandidateName", "", ...
    "WindowLabel", "", ...
    "MapRows", NaN, ...
    "MapColumns", NaN, ...
    "CutRowCount", NaN, ...
    "CutColumnCount", NaN, ...
    "CutCount", NaN, ...
    "CutDelayMinimum_s", NaN, ...
    "CutDelayMaximum_s", NaN, ...
    "CutDopplerMinimum_Hz", NaN, ...
    "CutDopplerMaximum_Hz", NaN, ...
    "DelayAxisStart_s", NaN, ...
    "DelayAxisEnd_s", NaN, ...
    "DelayAxisSpacing_s", NaN, ...
    "DopplerAxisStart_Hz", NaN, ...
    "DopplerAxisEnd_Hz", NaN, ...
    "DopplerAxisSpacing_Hz", NaN, ...
    "CfarCallCount", NaN, ...
    "NoiseEstimateFinite", false, ...
    "NoiseEstimateNonnegative", false, ...
    "ThresholdMonotonic", false, ...
    "DetectionCountMonotonic", false, ...
    "InjectedTruthCount", NaN, ...
    "ControlTruthCount", NaN, ...
    "AssociationValid", false, ...
    "MapFinite", false, ...
    "MapNonnegative", false, ...
    "AxesIncreasing", false, ...
    "AxisOrientation", "");

end

function row = localOperatingPointRowTemplate()

row = struct( ...
    "MapId", "", ...
    "CampaignId", "", ...
    "BackgroundId", "", ...
    "CaseId", "", ...
    "CandidateName", "", ...
    "WindowLabel", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "Alpha", NaN, ...
    "CutCount", NaN, ...
    "ThresholdMinimum", NaN, ...
    "ThresholdMedian", NaN, ...
    "ThresholdMaximum", NaN, ...
    "DetectionCount", NaN, ...
    "TargetOpportunityCount", 0.0, ...
    "TargetHitCount", 0.0, ...
    "ControlAlarmCount", 0.0, ...
    "UnmatchedDetectionCount", 0.0, ...
    "DetectionGeneratedTruthBlind", false, ...
    "AssociationValid", false);

end

function row = localDetectionRowTemplate()

row = struct( ...
    "DetectionId", "", ...
    "MapId", "", ...
    "CampaignId", "", ...
    "BackgroundId", "", ...
    "CaseId", "", ...
    "CandidateName", "", ...
    "WindowLabel", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "RowIndex", NaN, ...
    "ColumnIndex", NaN, ...
    "Delay_s", NaN, ...
    "Doppler_Hz", NaN, ...
    "PowerLinear", NaN, ...
    "NoiseEstimate", NaN, ...
    "Threshold", NaN, ...
    "AssociationRole", "unmatched", ...
    "TargetId", "", ...
    "SourceCaseId", "", ...
    "NormalizedDelayError", NaN, ...
    "NormalizedDopplerError", NaN, ...
    "AssociationCost", NaN, ...
    "DetectionGeneratedTruthBlind", false, ...
    "TruthUsedPostHoc", false, ...
    "FalseAlarmClaimed", false);

end

function row = localTruthOpportunityRowTemplate()

row = struct( ...
    "MapId", "", ...
    "CampaignId", "", ...
    "BackgroundId", "", ...
    "CaseId", "", ...
    "SourceCaseId", "", ...
    "CandidateName", "", ...
    "WindowLabel", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "TargetId", "", ...
    "Callsign", "", ...
    "GeometryClass", "", ...
    "ExpectedDelay_s", NaN, ...
    "ExpectedDoppler_Hz", NaN, ...
    "SearchDelayHalfExtent_s", NaN, ...
    "SearchDopplerHalfExtent_Hz", NaN, ...
    "Matched", false, ...
    "DetectionId", "", ...
    "NormalizedDelayError", NaN, ...
    "NormalizedDopplerError", NaN, ...
    "AssociationCost", NaN, ...
    "TruthUsedPostHoc", false);

end

function row = localTruthCutDiagnosticRowTemplate()

row = struct( ...
    "MapId", "", ...
    "CampaignId", "", ...
    "BackgroundId", "", ...
    "CaseId", "", ...
    "CandidateName", "", ...
    "WindowLabel", "", ...
    "EvidenceRole", "", ...
    "TargetId", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "ExpectedDelay_s", NaN, ...
    "ExpectedDoppler_Hz", NaN, ...
    "SelectedRowIndex", NaN, ...
    "SelectedColumnIndex", NaN, ...
    "SelectedCutDelay_s", NaN, ...
    "SelectedCutDoppler_Hz", NaN, ...
    "TruthCenterWithinDetectorSupport", false, ...
    "CutWithinDetectorSupport", false, ...
    "CutPowerLinear", NaN, ...
    "LocalNoiseEstimate", NaN, ...
    "CfarThreshold", NaN, ...
    "NmsRetained", false, ...
    "DetectionPassesThreshold", false, ...
    "TruthUsedPostHoc", false);

end

function row = localProductBackgroundSummaryRowTemplate()

row = struct( ...
    "BackgroundId", "", ...
    "CandidateName", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "MapCount", NaN, ...
    "TargetOpportunityCount", NaN, ...
    "TargetHitCount", NaN, ...
    "TargetHitRate", NaN, ...
    "ControlAlarmCount", NaN, ...
    "DetectionCount", NaN, ...
    "UnmatchedDetectionCount", NaN);

end

function row = localPairedProductDeltaRowTemplate()

row = struct( ...
    "BackgroundId", "", ...
    "PfaIndex", NaN, ...
    "Pfa", NaN, ...
    "CandidateName", "", ...
    "ComparatorName", "", ...
    "TargetHitDelta", NaN, ...
    "ControlAlarmDelta", NaN, ...
    "NoWorseAtCell", false, ...
    "StrictlyBetterAtCell", false);

end
