function lineShape = helperAddPptLine(slide, lineSpec)
%HELPERADDPPTLINE Add a PowerPoint line and optional label.

arguments
    slide
    lineSpec (1, 1) struct
end

lineShape = invoke( ...
    slide.Shapes, ...
    "AddLine", ...
    lineSpec.X1, ...
    lineSpec.Y1, ...
    lineSpec.X2, ...
    lineSpec.Y2 ...
);

lineShape.Line.ForeColor.RGB = helperHexToPptColor(lineSpec.Color);
lineShape.Line.Weight = lineSpec.Weight;

if lineSpec.Arrow
    lineShape.Line.EndArrowheadStyle = 3;
end

if strlength(string(lineSpec.Label)) == 0
    return;
end

labelSpec = struct( ...
    "Text", lineSpec.Label, ...
    "X", lineSpec.LabelX, ...
    "Y", lineSpec.LabelY, ...
    "Width", lineSpec.LabelWidth, ...
    "Height", lineSpec.LabelHeight, ...
    "FontSize", lineSpec.LabelFontSize, ...
    "Bold", false, ...
    "Italic", true, ...
    "Align", lineSpec.LabelAlign, ...
    "FontColor", "#111827", ...
    "FillColor", "", ...
    "LineColor", "" ...
);

helperAddPptText(slide, labelSpec);
end
