function analysis = helperAnalyzeG2PilotAwareSignalQuality(sessionData, ...
    collectionMetadataInfo, options)
%HELPERANALYZEG2PILOTAWARESIGNALQUALITY Analyze ATSC pilot-aware RF health.
%
%   ANALYSIS = HELPERANALYZEG2PILOTAWARESIGNALQUALITY(SESSIONDATA,
%   COLLECTIONMETADATAINFO, OPTIONS) computes per-repetition pilot and
%   pilot-excluded spectral metrics for the accepted G2 reference and
%   surveillance roles. This helper does not demodulate ATSC and does not
%   compute MER or EVM.

arguments
    sessionData (1,1) struct
    collectionMetadataInfo (1,1) struct
    options (1,1) struct = struct()
end

resolvedOptions = localResolveOptions(sessionData, options);
roleInfo = localResolveRoleInfo(sessionData, collectionMetadataInfo);
[roleMetricTable, comparisonMetricTable, roleEvidence] = ...
    localBuildPilotAwareTables(sessionData, roleInfo, resolvedOptions);
roleSummaryTable = localBuildRoleSummaryTable(roleMetricTable, ...
    resolvedOptions);
dashboardTable = localBuildDashboardTable(roleSummaryTable, ...
    comparisonMetricTable, resolvedOptions);

analysis = struct();
analysis.StageId = "G2_PilotAwareSignalQuality_Development";
analysis.DatasetId = string(sessionData.DatasetId);
analysis.RoleInfo = roleInfo;
analysis.Options = localStripRuntimeOptions(resolvedOptions);
analysis.RoleMetricTable = roleMetricTable;
analysis.RoleSummaryTable = roleSummaryTable;
analysis.ComparisonMetricTable = comparisonMetricTable;
analysis.DashboardTable = dashboardTable;
analysis.RoleEvidence = roleEvidence;
analysis.CollectionMetadataInfo = collectionMetadataInfo;
analysis.Metrics = localBuildMetrics(analysis);

end

function resolvedOptions = localResolveOptions(sessionData, options)

sampleRateVector = unique(double(sessionData.RadarTable.SampleRate_Hz));
centerFrequencyVector = unique(double(sessionData.RadarTable.CenterFrequency_Hz));
sampleCountVector = double(sessionData.RadarTable.NumSamples);

resolvedOptions = struct();
resolvedOptions.SampleRateHz = sampleRateVector(1);
resolvedOptions.CenterFrequencyHz = centerFrequencyVector(1);
resolvedOptions.AtscChannelBandwidthHz = 6.0e6;
resolvedOptions.ExpectedPilotOffsetHz = -2.690559441e6;
resolvedOptions.ExpectedPilotFrequencyHz = ...
    resolvedOptions.CenterFrequencyHz + ...
    resolvedOptions.ExpectedPilotOffsetHz;
resolvedOptions.PilotSearchHalfWidthHz = 150.0e3;
resolvedOptions.PilotExclusionHalfWidthHz = 50.0e3;
resolvedOptions.DataBandHalfWidthHz = min( ...
    resolvedOptions.AtscChannelBandwidthHz / 2.0, ...
    resolvedOptions.SampleRateHz / 2.0);
resolvedOptions.WelchLength = 8192;
resolvedOptions.WelchOverlap = 4096;
resolvedOptions.WelchNfft = 8192;
resolvedOptions.MaxRepetitions = Inf;
resolvedOptions.PilotProminenceReadyThreshold_dB = 8.0;
resolvedOptions.PilotProminenceCautionThreshold_dB = 5.0;
resolvedOptions.PilotFrequencyReadyTolerance_Hz = 20.0e3;
resolvedOptions.PilotFrequencyCautionTolerance_Hz = 75.0e3;
resolvedOptions.PilotFrequencyStableThreshold_Hz = 5.0e3;
resolvedOptions.PilotFrequencyCautionStableThreshold_Hz = 25.0e3;
resolvedOptions.DataBandProminenceReadyThreshold_dB = 12.0;
resolvedOptions.DataBandProminenceCautionThreshold_dB = 20.0;
resolvedOptions.ReferencePilotDeltaReadyThreshold_dB = 0.0;
resolvedOptions.ReferencePilotDeltaCautionThreshold_dB = -6.0;

if isfield(options, "ExpectedPilotFrequencyOffsetHz") && ...
        ~isfield(options, "ExpectedPilotOffsetHz")
    options.ExpectedPilotOffsetHz = ...
        options.ExpectedPilotFrequencyOffsetHz;
    options = rmfield(options, "ExpectedPilotFrequencyOffsetHz");
end

optionFields = fieldnames(options);

for fieldIndex = 1:numel(optionFields)
    fieldName = optionFields{fieldIndex};
    resolvedOptions.(fieldName) = options.(fieldName);
end

if isfield(options, "ExpectedPilotFrequencyHz") && ...
        ~isfield(options, "ExpectedPilotOffsetHz")
    resolvedOptions.ExpectedPilotOffsetHz = ...
        resolvedOptions.ExpectedPilotFrequencyHz - ...
        resolvedOptions.CenterFrequencyHz;
end

resolvedOptions.ExpectedPilotFrequencyHz = ...
    resolvedOptions.CenterFrequencyHz + ...
    resolvedOptions.ExpectedPilotOffsetHz;
resolvedOptions.DataBandHalfWidthHz = min( ...
    resolvedOptions.DataBandHalfWidthHz, ...
    resolvedOptions.SampleRateHz / 2.0);
resolvedOptions.PilotSearchHalfWidthHz = max( ...
    resolvedOptions.PilotSearchHalfWidthHz, 0.0);
resolvedOptions.PilotExclusionHalfWidthHz = max( ...
    resolvedOptions.PilotExclusionHalfWidthHz, 0.0);
minimumSampleCount = max(32.0, min(sampleCountVector));
resolvedOptions.WelchLength = min(resolvedOptions.WelchLength, ...
    minimumSampleCount);
resolvedOptions.WelchLength = max(32.0, floor(resolvedOptions.WelchLength));
resolvedOptions.WelchOverlap = min(resolvedOptions.WelchOverlap, ...
    resolvedOptions.WelchLength - 1.0);
resolvedOptions.WelchOverlap = max(0.0, floor(resolvedOptions.WelchOverlap));
resolvedOptions.WelchNfft = max(resolvedOptions.WelchNfft, ...
    resolvedOptions.WelchLength);
resolvedOptions.WelchNfft = floor(resolvedOptions.WelchNfft);
resolvedOptions.WelchWindow = hann(resolvedOptions.WelchLength, ...
    "periodic");

end

function roleInfo = localResolveRoleInfo(sessionData, collectionMetadataInfo)

channel1Label = string(sessionData.RadarTable.Antenna1(1));
channel2Label = string(sessionData.RadarTable.Antenna2(1));
referenceLabel = strtrim( ...
    string(collectionMetadataInfo.ReferenceChannel.ChannelLabel));
surveillanceLabel = strtrim( ...
    string(collectionMetadataInfo.SurveillanceChannel.ChannelLabel));

roleInfo = struct();
roleInfo.Channel1Label = channel1Label;
roleInfo.Channel2Label = channel2Label;
roleInfo.ReferenceLabel = "";
roleInfo.SurveillanceLabel = "";
roleInfo.ReferenceColumnIndex = NaN;
roleInfo.SurveillanceColumnIndex = NaN;
roleInfo.RoleSource = "channel_order_fallback_unverified";
roleInfo.RoleNote = "Manual role mapping was unavailable or incomplete. " + ...
    "Pilot-aware review uses channel order fallback only.";

manualMappingValid = collectionMetadataInfo.MetadataPresent && ...
    collectionMetadataInfo.SessionIdMatches && ...
    strlength(referenceLabel) > 0 && ...
    strlength(surveillanceLabel) > 0 && ...
    any(referenceLabel == [channel1Label; channel2Label]) && ...
    any(surveillanceLabel == [channel1Label; channel2Label]) && ...
    referenceLabel ~= surveillanceLabel;

if manualMappingValid
    roleInfo.ReferenceLabel = referenceLabel;
    roleInfo.SurveillanceLabel = surveillanceLabel;
    roleInfo.RoleSource = "collection_metadata_manual_mapping";
    roleInfo.RoleNote = "Pilot-aware review uses the accepted G2 " + ...
        "collection_metadata.json channel-role mapping.";
else
    roleInfo.ReferenceLabel = channel1Label;
    roleInfo.SurveillanceLabel = channel2Label;
end

if roleInfo.ReferenceLabel == channel1Label
    roleInfo.ReferenceColumnIndex = 1;
else
    roleInfo.ReferenceColumnIndex = 2;
end

if roleInfo.SurveillanceLabel == channel1Label
    roleInfo.SurveillanceColumnIndex = 1;
else
    roleInfo.SurveillanceColumnIndex = 2;
end

end

function [roleMetricTable, comparisonMetricTable, roleEvidence] = ...
    localBuildPilotAwareTables(sessionData, roleInfo, resolvedOptions)

radarTable = sessionData.RadarTable;

if isfinite(resolvedOptions.MaxRepetitions)
    requestedRepetitionCount = min(height(radarTable), ...
        resolvedOptions.MaxRepetitions);
    requestedRepetitionCount = max(1.0, floor(requestedRepetitionCount));
    radarTable = radarTable(1:requestedRepetitionCount, :);
end

repetitionCount = height(radarTable);
roleRowTemplate = localBuildRoleRowTemplate();
comparisonRowTemplate = localBuildComparisonRowTemplate();
roleRows = repmat(roleRowTemplate, repetitionCount * 2, 1);
comparisonRows = repmat(comparisonRowTemplate, repetitionCount, 1);
referencePsdByRepetition = [];
surveillancePsdByRepetition = [];
psdFrequencyOffsetHz = [];

for repetitionIndex = 1:repetitionCount
    [referenceSamples, surveillanceSamples] = localReadRoleSamples( ...
        sessionData, radarTable, roleInfo, repetitionIndex);
    [referenceMetrics, referencePsd, psdFrequencyOffsetHz] = ...
        localComputeChannelPilotMetrics(referenceSamples, ...
        resolvedOptions);
    [surveillanceMetrics, surveillancePsd, ~] = ...
        localComputeChannelPilotMetrics(surveillanceSamples, ...
        resolvedOptions);

    if isempty(referencePsdByRepetition)
        referencePsdByRepetition = zeros(numel(referencePsd), ...
            repetitionCount);
        surveillancePsdByRepetition = zeros(numel(surveillancePsd), ...
            repetitionCount);
    end

    referencePsdByRepetition(:, repetitionIndex) = referencePsd;
    surveillancePsdByRepetition(:, repetitionIndex) = surveillancePsd;
    referenceRowIndex = (repetitionIndex - 1) * 2 + 1;
    surveillanceRowIndex = referenceRowIndex + 1;
    roleRows(referenceRowIndex) = localBuildRoleMetricRow(radarTable, ...
        repetitionIndex, "reference", roleInfo.ReferenceLabel, ...
        referenceMetrics);
    roleRows(surveillanceRowIndex) = localBuildRoleMetricRow(radarTable, ...
        repetitionIndex, "surveillance", roleInfo.SurveillanceLabel, ...
        surveillanceMetrics);
    comparisonRows(repetitionIndex) = localBuildComparisonMetricRow( ...
        radarTable, repetitionIndex, referenceMetrics, ...
        surveillanceMetrics);
end

roleMetricTable = struct2table(roleRows);
comparisonMetricTable = struct2table(comparisonRows);
roleEvidence = struct();
roleEvidence.PsdFrequencyOffset_Hz = psdFrequencyOffsetHz;
roleEvidence.PsdAbsoluteFrequency_Hz = ...
    resolvedOptions.CenterFrequencyHz + psdFrequencyOffsetHz;
roleEvidence.ReferencePsdByRepetition = referencePsdByRepetition;
roleEvidence.SurveillancePsdByRepetition = surveillancePsdByRepetition;
roleEvidence.ReferenceMeanPsd = mean(referencePsdByRepetition, 2);
roleEvidence.SurveillanceMeanPsd = mean(surveillancePsdByRepetition, 2);
roleEvidence.ReferenceMinusSurveillanceMeanPsd_dB = ...
    pow2db(roleEvidence.ReferenceMeanPsd + eps) - ...
    pow2db(roleEvidence.SurveillanceMeanPsd + eps);

end

function rowTemplate = localBuildRoleRowTemplate()

rowTemplate = struct( ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "Role", "", ...
    "ChannelLabel", "", ...
    "PilotFrequencyOffset_Hz", NaN, ...
    "PilotFrequencyAbsolute_Hz", NaN, ...
    "ExpectedPilotFrequencyOffset_Hz", NaN, ...
    "ExpectedPilotFrequencyAbsolute_Hz", NaN, ...
    "PilotOffsetError_Hz", NaN, ...
    "PilotPsd_dBHz", NaN, ...
    "PilotProminence_dB", NaN, ...
    "PilotSearchProminence_dB", NaN, ...
    "DataBandMedianPsd_dBHz", NaN, ...
    "DataBandPeakFrequencyOffset_Hz", NaN, ...
    "DataBandPeakFrequencyAbsolute_Hz", NaN, ...
    "DataBandPeakPsd_dBHz", NaN, ...
    "DataBandProminence_dB", NaN, ...
    "PilotExcludedDataBandPower_dB", NaN, ...
    "OccupiedBandwidth_Hz", NaN, ...
    "MeanPower_dBFS", NaN, ...
    "DataBandBinCount", NaN);

end

function rowTemplate = localBuildComparisonRowTemplate()

rowTemplate = struct( ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "ReferenceMinusSurveillancePilotPsd_dB", NaN, ...
    "ReferenceMinusSurveillancePilotProminence_dB", NaN, ...
    "ReferenceMinusSurveillanceDataBandMedianPsd_dB", NaN, ...
    "ReferenceMinusSurveillanceDataBandPower_dB", NaN, ...
    "ReferenceMinusSurveillanceDataBandPeakPsd_dB", NaN, ...
    "ReferenceMinusSurveillanceMeanPower_dB", NaN, ...
    "ReferencePilotOffsetError_Hz", NaN, ...
    "SurveillancePilotOffsetError_Hz", NaN, ...
    "ReferenceMinusSurveillancePilotOffset_Hz", NaN);

end

function [referenceSamples, surveillanceSamples] = localReadRoleSamples( ...
    sessionData, radarTable, roleInfo, repetitionIndex)

loadedSamples = complex(int16.empty(0, 0));

if isfield(sessionData, "RadarScans") && ...
        repetitionIndex <= numel(sessionData.RadarScans) && ...
        isfield(sessionData.RadarScans(repetitionIndex), "Samples")
    loadedSamples = sessionData.RadarScans(repetitionIndex).Samples;
end

if isempty(loadedSamples)
    if ~isfield(sessionData, "DatasetRoot")
        error("helperAnalyzeG2PilotAwareSignalQuality:MissingDatasetRoot", ...
            "DatasetRoot is required when samples are not preloaded.");
    end

    absoluteFilePath = fullfile(string(sessionData.DatasetRoot), ...
        strrep(radarTable.RelativePath(repetitionIndex), "/", filesep));

    try
        scan = helperScanBasebandCaptureFile(absoluteFilePath, true);
    catch scanException
        error("helperAnalyzeG2PilotAwareSignalQuality:ReadSamplesFailed", ...
            "Failed to read IQ samples from %s: %s", absoluteFilePath, ...
            scanException.message);
    end

    loadedSamples = scan.Samples;
end

if size(loadedSamples, 2) < 2
    error("helperAnalyzeG2PilotAwareSignalQuality:InsufficientChannels", ...
        "Pilot-aware G2 review requires at least two IQ channels.");
end

referenceSamples = double(loadedSamples(:, roleInfo.ReferenceColumnIndex));
surveillanceSamples = double(loadedSamples(:, ...
    roleInfo.SurveillanceColumnIndex));

end

function [channelMetrics, pxx, frequencyOffsetHz] = ...
    localComputeChannelPilotMetrics(samples, resolvedOptions)

samples = double(samples(:));

[pxx, frequencyOffsetHz] = pwelch(samples, ...
    resolvedOptions.WelchWindow, resolvedOptions.WelchOverlap, ...
    resolvedOptions.WelchNfft, resolvedOptions.SampleRateHz, ...
    "centered");
frequencyOffsetHz = double(frequencyOffsetHz(:));
pxx = max(real(double(pxx(:))), eps);
validMask = isfinite(frequencyOffsetHz) & isfinite(pxx);
pilotSearchMask = validMask & ...
    abs(frequencyOffsetHz - resolvedOptions.ExpectedPilotOffsetHz) <= ...
    resolvedOptions.PilotSearchHalfWidthHz;

if ~any(pilotSearchMask)
    pilotSearchMask = validMask;
end

pilotSearchMetrics = helperComputePilotAwarePsdMetrics( ...
    frequencyOffsetHz(pilotSearchMask), pxx(pilotSearchMask), ...
    resolvedOptions.PilotExclusionHalfWidthHz);
pilotFrequencyOffsetHz = pilotSearchMetrics.PilotFrequency_Hz;
pilotAbsoluteFrequencyHz = resolvedOptions.CenterFrequencyHz + ...
    pilotFrequencyOffsetHz;
pilotPsd = db2pow(pilotSearchMetrics.PilotPsd_dB);
[dataBandMetrics, dataBandMask] = localComputeDataBandMetrics( ...
    frequencyOffsetHz, pxx, pilotFrequencyOffsetHz, resolvedOptions);

try
    occupiedBandwidthHz = obw(samples, resolvedOptions.SampleRateHz);
catch obwException
    warning("helperAnalyzeG2PilotAwareSignalQuality:ObwFailed", ...
        "Occupied bandwidth calculation failed: %s", obwException.message);
    occupiedBandwidthHz = NaN;
end

fullScale = double(intmax("int16"));
meanPower = mean(abs(samples) .^ 2);

channelMetrics = struct();
channelMetrics.PilotFrequencyOffset_Hz = pilotFrequencyOffsetHz;
channelMetrics.PilotFrequencyAbsolute_Hz = pilotAbsoluteFrequencyHz;
channelMetrics.ExpectedPilotFrequencyOffset_Hz = ...
    resolvedOptions.ExpectedPilotOffsetHz;
channelMetrics.ExpectedPilotFrequencyAbsolute_Hz = ...
    resolvedOptions.ExpectedPilotFrequencyHz;
channelMetrics.PilotOffsetError_Hz = pilotFrequencyOffsetHz - ...
    resolvedOptions.ExpectedPilotOffsetHz;
channelMetrics.PilotPsd_dBHz = pilotSearchMetrics.PilotPsd_dB;
channelMetrics.PilotProminence_dB = pow2db( ...
    pilotPsd / max(dataBandMetrics.DataBandMedianPsd, eps));
channelMetrics.PilotSearchProminence_dB = ...
    pilotSearchMetrics.PilotProminence_dB;
channelMetrics.DataBandMedianPsd_dBHz = pow2db( ...
    dataBandMetrics.DataBandMedianPsd);
channelMetrics.DataBandPeakFrequencyOffset_Hz = ...
    dataBandMetrics.DataBandPeakFrequencyOffset_Hz;
channelMetrics.DataBandPeakFrequencyAbsolute_Hz = ...
    resolvedOptions.CenterFrequencyHz + ...
    dataBandMetrics.DataBandPeakFrequencyOffset_Hz;
channelMetrics.DataBandPeakPsd_dBHz = pow2db( ...
    dataBandMetrics.DataBandPeakPsd);
channelMetrics.DataBandProminence_dB = pow2db( ...
    dataBandMetrics.DataBandPeakPsd / ...
    max(dataBandMetrics.DataBandMedianPsd, eps));
channelMetrics.PilotExcludedDataBandPower_dB = pow2db( ...
    dataBandMetrics.PilotExcludedDataBandPower);
channelMetrics.OccupiedBandwidth_Hz = occupiedBandwidthHz;
channelMetrics.MeanPower_dBFS = pow2db( ...
    meanPower / (fullScale ^ 2) + eps);
channelMetrics.DataBandBinCount = sum(dataBandMask);

end

function [dataBandMetrics, dataBandMask] = localComputeDataBandMetrics( ...
    frequencyOffsetHz, pxx, pilotFrequencyOffsetHz, resolvedOptions)

dataBandRange = [-resolvedOptions.DataBandHalfWidthHz, ...
    resolvedOptions.DataBandHalfWidthHz];
dataBandLowerHz = max(dataBandRange(1), min(frequencyOffsetHz));
dataBandUpperHz = min(dataBandRange(2), max(frequencyOffsetHz));
dataBandMask = frequencyOffsetHz >= dataBandLowerHz & ...
    frequencyOffsetHz <= dataBandUpperHz & ...
    abs(frequencyOffsetHz - pilotFrequencyOffsetHz) > ...
    resolvedOptions.PilotExclusionHalfWidthHz & ...
    isfinite(pxx);

if ~any(dataBandMask)
    dataBandMask = isfinite(pxx);
end

dataBandFrequencyHz = frequencyOffsetHz(dataBandMask);
dataBandPsd = pxx(dataBandMask);
dataBandMedianPsd = max(median(dataBandPsd, "omitnan"), eps);
[dataBandPeakPsd, dataBandPeakIndex] = max(dataBandPsd, [], "omitnan");
pilotExcludedDataBandPower = localComputePilotExcludedBandPower( ...
    frequencyOffsetHz, pxx, dataBandLowerHz, dataBandUpperHz, ...
    pilotFrequencyOffsetHz, resolvedOptions);

dataBandMetrics = struct();
dataBandMetrics.DataBandMedianPsd = dataBandMedianPsd;
dataBandMetrics.DataBandPeakPsd = max(dataBandPeakPsd, eps);
dataBandMetrics.DataBandPeakFrequencyOffset_Hz = ...
    dataBandFrequencyHz(dataBandPeakIndex);
dataBandMetrics.PilotExcludedDataBandPower = ...
    pilotExcludedDataBandPower;

end

function pilotExcludedDataBandPower = localComputePilotExcludedBandPower( ...
    frequencyOffsetHz, pxx, dataBandLowerHz, dataBandUpperHz, ...
    pilotFrequencyOffsetHz, resolvedOptions)

if dataBandLowerHz >= dataBandUpperHz
    pilotExcludedDataBandPower = NaN;
    return
end

try
    fullDataBandPower = bandpower(pxx, frequencyOffsetHz, ...
        [dataBandLowerHz, dataBandUpperHz], "psd");
    pilotBandLowerHz = max(dataBandLowerHz, ...
        pilotFrequencyOffsetHz - ...
        resolvedOptions.PilotExclusionHalfWidthHz);
    pilotBandUpperHz = min(dataBandUpperHz, ...
        pilotFrequencyOffsetHz + ...
        resolvedOptions.PilotExclusionHalfWidthHz);

    if pilotBandLowerHz < pilotBandUpperHz
        pilotBandPower = bandpower(pxx, frequencyOffsetHz, ...
            [pilotBandLowerHz, pilotBandUpperHz], "psd");
    else
        pilotBandPower = 0.0;
    end
catch bandpowerException
    error("helperAnalyzeG2PilotAwareSignalQuality:BandpowerFailed", ...
        "Failed to compute pilot-excluded data-band power: %s", ...
        bandpowerException.message);
end

pilotExcludedDataBandPower = max(fullDataBandPower - pilotBandPower, eps);

end

function row = localBuildRoleMetricRow(radarTable, repetitionIndex, ...
    roleName, channelLabel, channelMetrics)

row = localBuildRoleRowTemplate();
row.Repetition = double(radarTable.Repetition(repetitionIndex));
row.RelativePath = string(radarTable.RelativePath(repetitionIndex));
row.Role = string(roleName);
row.ChannelLabel = string(channelLabel);
row.PilotFrequencyOffset_Hz = channelMetrics.PilotFrequencyOffset_Hz;
row.PilotFrequencyAbsolute_Hz = channelMetrics.PilotFrequencyAbsolute_Hz;
row.ExpectedPilotFrequencyOffset_Hz = ...
    channelMetrics.ExpectedPilotFrequencyOffset_Hz;
row.ExpectedPilotFrequencyAbsolute_Hz = ...
    channelMetrics.ExpectedPilotFrequencyAbsolute_Hz;
row.PilotOffsetError_Hz = channelMetrics.PilotOffsetError_Hz;
row.PilotPsd_dBHz = channelMetrics.PilotPsd_dBHz;
row.PilotProminence_dB = channelMetrics.PilotProminence_dB;
row.PilotSearchProminence_dB = channelMetrics.PilotSearchProminence_dB;
row.DataBandMedianPsd_dBHz = channelMetrics.DataBandMedianPsd_dBHz;
row.DataBandPeakFrequencyOffset_Hz = ...
    channelMetrics.DataBandPeakFrequencyOffset_Hz;
row.DataBandPeakFrequencyAbsolute_Hz = ...
    channelMetrics.DataBandPeakFrequencyAbsolute_Hz;
row.DataBandPeakPsd_dBHz = channelMetrics.DataBandPeakPsd_dBHz;
row.DataBandProminence_dB = channelMetrics.DataBandProminence_dB;
row.PilotExcludedDataBandPower_dB = ...
    channelMetrics.PilotExcludedDataBandPower_dB;
row.OccupiedBandwidth_Hz = channelMetrics.OccupiedBandwidth_Hz;
row.MeanPower_dBFS = channelMetrics.MeanPower_dBFS;
row.DataBandBinCount = double(channelMetrics.DataBandBinCount);

end

function row = localBuildComparisonMetricRow(radarTable, repetitionIndex, ...
    referenceMetrics, surveillanceMetrics)

row = localBuildComparisonRowTemplate();
row.Repetition = double(radarTable.Repetition(repetitionIndex));
row.RelativePath = string(radarTable.RelativePath(repetitionIndex));
row.ReferenceMinusSurveillancePilotPsd_dB = ...
    referenceMetrics.PilotPsd_dBHz - ...
    surveillanceMetrics.PilotPsd_dBHz;
row.ReferenceMinusSurveillancePilotProminence_dB = ...
    referenceMetrics.PilotProminence_dB - ...
    surveillanceMetrics.PilotProminence_dB;
row.ReferenceMinusSurveillanceDataBandMedianPsd_dB = ...
    referenceMetrics.DataBandMedianPsd_dBHz - ...
    surveillanceMetrics.DataBandMedianPsd_dBHz;
row.ReferenceMinusSurveillanceDataBandPower_dB = ...
    referenceMetrics.PilotExcludedDataBandPower_dB - ...
    surveillanceMetrics.PilotExcludedDataBandPower_dB;
row.ReferenceMinusSurveillanceDataBandPeakPsd_dB = ...
    referenceMetrics.DataBandPeakPsd_dBHz - ...
    surveillanceMetrics.DataBandPeakPsd_dBHz;
row.ReferenceMinusSurveillanceMeanPower_dB = ...
    referenceMetrics.MeanPower_dBFS - ...
    surveillanceMetrics.MeanPower_dBFS;
row.ReferencePilotOffsetError_Hz = ...
    referenceMetrics.PilotOffsetError_Hz;
row.SurveillancePilotOffsetError_Hz = ...
    surveillanceMetrics.PilotOffsetError_Hz;
row.ReferenceMinusSurveillancePilotOffset_Hz = ...
    referenceMetrics.PilotFrequencyOffset_Hz - ...
    surveillanceMetrics.PilotFrequencyOffset_Hz;

end

function roleSummaryTable = localBuildRoleSummaryTable(roleMetricTable, ...
    resolvedOptions)

roleNames = ["reference"; "surveillance"];
rowTemplate = struct( ...
    "Role", "", ...
    "ChannelLabel", "", ...
    "RepetitionCount", NaN, ...
    "MedianPilotFrequencyOffset_Hz", NaN, ...
    "MedianPilotFrequencyAbsolute_Hz", NaN, ...
    "PilotFrequencyStd_Hz", NaN, ...
    "MedianPilotOffsetError_Hz", NaN, ...
    "WorstPilotOffsetError_Hz", NaN, ...
    "MedianPilotPsd_dBHz", NaN, ...
    "MedianPilotProminence_dB", NaN, ...
    "WorstPilotProminence_dB", NaN, ...
    "MedianDataBandMedianPsd_dBHz", NaN, ...
    "MedianDataBandProminence_dB", NaN, ...
    "MedianPilotExcludedDataBandPower_dB", NaN, ...
    "MedianOccupiedBandwidth_Hz", NaN, ...
    "PilotConfidenceLabel", "", ...
    "PilotConfidenceRationale", "");
rows = repmat(rowTemplate, numel(roleNames), 1);

for roleIndex = 1:numel(roleNames)
    roleName = roleNames(roleIndex);
    roleRows = roleMetricTable(roleMetricTable.Role == roleName, :);
    medianPilotProminenceDb = median( ...
        roleRows.PilotProminence_dB, "omitnan");
    worstPilotProminenceDb = min( ...
        roleRows.PilotProminence_dB, [], "omitnan");
    pilotFrequencyStdHz = std( ...
        roleRows.PilotFrequencyOffset_Hz, 0, 1, "omitnan");
    medianPilotOffsetErrorHz = median( ...
        roleRows.PilotOffsetError_Hz, "omitnan");
    worstPilotOffsetErrorHz = max( ...
        abs(roleRows.PilotOffsetError_Hz), [], "omitnan");
    [confidenceLabel, confidenceRationale] = localClassifyRolePilot( ...
        medianPilotProminenceDb, pilotFrequencyStdHz, ...
        medianPilotOffsetErrorHz, resolvedOptions);

    rows(roleIndex) = struct( ...
        "Role", roleName, ...
        "ChannelLabel", string(roleRows.ChannelLabel(1)), ...
        "RepetitionCount", height(roleRows), ...
        "MedianPilotFrequencyOffset_Hz", median( ...
        roleRows.PilotFrequencyOffset_Hz, "omitnan"), ...
        "MedianPilotFrequencyAbsolute_Hz", median( ...
        roleRows.PilotFrequencyAbsolute_Hz, "omitnan"), ...
        "PilotFrequencyStd_Hz", pilotFrequencyStdHz, ...
        "MedianPilotOffsetError_Hz", medianPilotOffsetErrorHz, ...
        "WorstPilotOffsetError_Hz", worstPilotOffsetErrorHz, ...
        "MedianPilotPsd_dBHz", median( ...
        roleRows.PilotPsd_dBHz, "omitnan"), ...
        "MedianPilotProminence_dB", medianPilotProminenceDb, ...
        "WorstPilotProminence_dB", worstPilotProminenceDb, ...
        "MedianDataBandMedianPsd_dBHz", median( ...
        roleRows.DataBandMedianPsd_dBHz, "omitnan"), ...
        "MedianDataBandProminence_dB", median( ...
        roleRows.DataBandProminence_dB, "omitnan"), ...
        "MedianPilotExcludedDataBandPower_dB", median( ...
        roleRows.PilotExcludedDataBandPower_dB, "omitnan"), ...
        "MedianOccupiedBandwidth_Hz", median( ...
        roleRows.OccupiedBandwidth_Hz, "omitnan"), ...
        "PilotConfidenceLabel", confidenceLabel, ...
        "PilotConfidenceRationale", confidenceRationale);
end

roleSummaryTable = struct2table(rows);

end

function [confidenceLabel, confidenceRationale] = localClassifyRolePilot( ...
    medianPilotProminenceDb, pilotFrequencyStdHz, ...
    medianPilotOffsetErrorHz, resolvedOptions)

if ~isfinite(medianPilotProminenceDb)
    confidenceLabel = "no-confidence";
    confidenceRationale = "Pilot metrics are not finite.";
    return
end

stableReady = pilotFrequencyStdHz <= ...
    resolvedOptions.PilotFrequencyStableThreshold_Hz;
stableCaution = pilotFrequencyStdHz <= ...
    resolvedOptions.PilotFrequencyCautionStableThreshold_Hz;
offsetReady = abs(medianPilotOffsetErrorHz) <= ...
    resolvedOptions.PilotFrequencyReadyTolerance_Hz;
offsetCaution = abs(medianPilotOffsetErrorHz) <= ...
    resolvedOptions.PilotFrequencyCautionTolerance_Hz;

if medianPilotProminenceDb >= ...
        resolvedOptions.PilotProminenceReadyThreshold_dB && ...
        stableReady && offsetReady
    confidenceLabel = "ready";
    confidenceRationale = "Pilot line is prominent, stable, and near " + ...
        "the expected ATSC pilot offset.";
elseif medianPilotProminenceDb >= ...
        resolvedOptions.PilotProminenceCautionThreshold_dB && ...
        stableCaution && offsetCaution
    confidenceLabel = "caution";
    confidenceRationale = "Pilot-like evidence is present but does not " + ...
        "meet all ready thresholds.";
else
    confidenceLabel = "no-confidence";
    confidenceRationale = "Pilot-like evidence is weak, unstable, or far " + ...
        "from the expected ATSC pilot offset.";
end

end

function dashboardTable = localBuildDashboardTable(roleSummaryTable, ...
    comparisonMetricTable, resolvedOptions)

referenceSummary = roleSummaryTable(roleSummaryTable.Role == ...
    "reference", :);
surveillanceSummary = roleSummaryTable(roleSummaryTable.Role == ...
    "surveillance", :);
pilotDeltaMedianDb = median( ...
    comparisonMetricTable.ReferenceMinusSurveillancePilotPsd_dB, ...
    "omitnan");
dataBandMedianDeltaDb = median( ...
    comparisonMetricTable.ReferenceMinusSurveillanceDataBandMedianPsd_dB, ...
    "omitnan");
dataBandPowerDeltaDb = median( ...
    comparisonMetricTable.ReferenceMinusSurveillanceDataBandPower_dB, ...
    "omitnan");
rowTemplate = struct( ...
    "Question", "", ...
    "Metric", "", ...
    "Value", "", ...
    "ReviewLabel", "", ...
    "Rationale", "");
rows = repmat(rowTemplate, 5, 1);

[stabilityLabel, stabilityRationale] = localClassifyPilotStability( ...
    referenceSummary, surveillanceSummary, resolvedOptions);
rows(1) = struct( ...
    "Question", "Where is the dominant pilot-like line in each role?", ...
    "Metric", "Pilot frequency standard deviation", ...
    "Value", sprintf("reference %.3f kHz, surveillance %.3f kHz", ...
    referenceSummary.PilotFrequencyStd_Hz / 1.0e3, ...
    surveillanceSummary.PilotFrequencyStd_Hz / 1.0e3), ...
    "ReviewLabel", stabilityLabel, ...
    "Rationale", stabilityRationale);

[prominenceLabel, prominenceRationale] = localClassifyPilotProminence( ...
    referenceSummary, surveillanceSummary, resolvedOptions);
rows(2) = struct( ...
    "Question", "Does each channel see a strong transmitter pilot?", ...
    "Metric", "Median pilot prominence", ...
    "Value", sprintf("reference %.2f dB, surveillance %.2f dB", ...
    referenceSummary.MedianPilotProminence_dB, ...
    surveillanceSummary.MedianPilotProminence_dB), ...
    "ReviewLabel", prominenceLabel, ...
    "Rationale", prominenceRationale);

[dataBandLabel, dataBandRationale] = localClassifyDataBand( ...
    referenceSummary, surveillanceSummary, resolvedOptions);
rows(3) = struct( ...
    "Question", "Is the pilot-excluded data band smooth?", ...
    "Metric", "Median data-band peak prominence", ...
    "Value", sprintf("reference %.2f dB, surveillance %.2f dB", ...
    referenceSummary.MedianDataBandProminence_dB, ...
    surveillanceSummary.MedianDataBandProminence_dB), ...
    "ReviewLabel", dataBandLabel, ...
    "Rationale", dataBandRationale);

[pilotDeltaLabel, pilotDeltaRationale] = localClassifyPilotDelta( ...
    pilotDeltaMedianDb, resolvedOptions);
rows(4) = struct( ...
    "Question", "Is reference stronger for pilot energy?", ...
    "Metric", "Median reference-minus-surveillance pilot PSD", ...
    "Value", sprintf("%.2f dB", pilotDeltaMedianDb), ...
    "ReviewLabel", pilotDeltaLabel, ...
    "Rationale", pilotDeltaRationale);

[overallLabel, overallRationale] = localClassifyOverallDashboard( ...
    roleSummaryTable, stabilityLabel, prominenceLabel, dataBandLabel, ...
    pilotDeltaLabel);
rows(5) = struct( ...
    "Question", "What should we conclude before G2 Stage 3 work?", ...
    "Metric", "Overall pilot-aware manual review label", ...
    "Value", sprintf("data median delta %.2f dB, data power delta %.2f dB", ...
    dataBandMedianDeltaDb, dataBandPowerDeltaDb), ...
    "ReviewLabel", overallLabel, ...
    "Rationale", overallRationale);

dashboardTable = struct2table(rows);

end

function [label, rationale] = localClassifyPilotStability( ...
    referenceSummary, surveillanceSummary, resolvedOptions)

roleStdHz = [
    referenceSummary.PilotFrequencyStd_Hz
    surveillanceSummary.PilotFrequencyStd_Hz
    ];
roleOffsetErrorHz = abs([
    referenceSummary.MedianPilotOffsetError_Hz
    surveillanceSummary.MedianPilotOffsetError_Hz
    ]);

if all(roleStdHz <= resolvedOptions.PilotFrequencyStableThreshold_Hz) && ...
        all(roleOffsetErrorHz <= ...
        resolvedOptions.PilotFrequencyReadyTolerance_Hz)
    label = "ready";
    rationale = "Both roles show stable pilot-frequency estimates near " + ...
        "the expected ATSC offset.";
elseif all(roleStdHz <= ...
        resolvedOptions.PilotFrequencyCautionStableThreshold_Hz) && ...
        all(roleOffsetErrorHz <= ...
        resolvedOptions.PilotFrequencyCautionTolerance_Hz)
    label = "caution";
    rationale = "Pilot frequency estimates are usable but outside at " + ...
        "least one ready threshold.";
else
    label = "no-confidence";
    rationale = "Pilot frequency estimates are unstable or far from the " + ...
        "expected ATSC offset.";
end

end

function [label, rationale] = localClassifyPilotProminence( ...
    referenceSummary, surveillanceSummary, resolvedOptions)

roleProminenceDb = [
    referenceSummary.MedianPilotProminence_dB
    surveillanceSummary.MedianPilotProminence_dB
    ];

if all(roleProminenceDb >= ...
        resolvedOptions.PilotProminenceReadyThreshold_dB)
    label = "ready";
    rationale = "Both accepted roles show ready-level pilot prominence.";
elseif any(roleProminenceDb >= ...
        resolvedOptions.PilotProminenceCautionThreshold_dB)
    label = "caution";
    rationale = "At least one role shows pilot-like prominence, but the " + ...
        "two-role evidence is uneven.";
else
    label = "no-confidence";
    rationale = "Neither accepted role has enough pilot prominence.";
end

end

function [label, rationale] = localClassifyDataBand( ...
    referenceSummary, surveillanceSummary, resolvedOptions)

roleDataProminenceDb = [
    referenceSummary.MedianDataBandProminence_dB
    surveillanceSummary.MedianDataBandProminence_dB
    ];

if all(roleDataProminenceDb <= ...
        resolvedOptions.DataBandProminenceReadyThreshold_dB)
    label = "ready";
    rationale = "Pilot-excluded data-band peaks stay within the smooth " + ...
        "ready range.";
elseif all(roleDataProminenceDb <= ...
        resolvedOptions.DataBandProminenceCautionThreshold_dB)
    label = "caution";
    rationale = "The pilot-excluded data band has visible structure but " + ...
        "does not exceed the no-confidence threshold.";
else
    label = "no-confidence";
    rationale = "Pilot-excluded data-band structure is dominated by " + ...
        "large non-pilot peaks.";
end

end

function [label, rationale] = localClassifyPilotDelta( ...
    pilotDeltaMedianDb, resolvedOptions)

if pilotDeltaMedianDb >= ...
        resolvedOptions.ReferencePilotDeltaReadyThreshold_dB
    label = "ready";
    rationale = "Accepted reference has at least as much pilot PSD as " + ...
        "surveillance at the median repetition.";
elseif pilotDeltaMedianDb >= ...
        resolvedOptions.ReferencePilotDeltaCautionThreshold_dB
    label = "caution";
    rationale = "Reference pilot PSD is weaker than surveillance but " + ...
        "within the caution band.";
else
    label = "no-confidence";
    rationale = "Reference pilot PSD is materially weaker than the " + ...
        "accepted surveillance role.";
end

end

function [label, rationale] = localClassifyOverallDashboard( ...
    roleSummaryTable, stabilityLabel, prominenceLabel, dataBandLabel, ...
    pilotDeltaLabel)

referenceLabel = string(roleSummaryTable.PilotConfidenceLabel( ...
    roleSummaryTable.Role == "reference"));
surveillanceLabel = string(roleSummaryTable.PilotConfidenceLabel( ...
    roleSummaryTable.Role == "surveillance"));
roleLabels = [referenceLabel; surveillanceLabel];

if all(roleLabels == "ready") && stabilityLabel == "ready" && ...
        prominenceLabel == "ready" && dataBandLabel ~= "no-confidence" && ...
        pilotDeltaLabel ~= "no-confidence"
    label = "ready";
    rationale = "Pilot-aware evidence is strong enough for the next " + ...
        "development review question.";
elseif any(roleLabels ~= "no-confidence") && ...
        prominenceLabel ~= "no-confidence"
    label = "caution";
    rationale = "Pilot evidence exists, but at least one role, delta, or " + ...
        "data-band check remains caveated.";
else
    label = "no-confidence";
    rationale = "Pilot-aware evidence is too weak for a transmitter-" + ...
        "specific RF-health conclusion.";
end

end

function metrics = localBuildMetrics(analysis)

referenceSummary = analysis.RoleSummaryTable( ...
    analysis.RoleSummaryTable.Role == "reference", :);
surveillanceSummary = analysis.RoleSummaryTable( ...
    analysis.RoleSummaryTable.Role == "surveillance", :);
overallRow = analysis.DashboardTable(end, :);

metrics = struct();
metrics.stage_id = analysis.StageId;
metrics.dataset_id = analysis.DatasetId;
metrics.reference_label = analysis.RoleInfo.ReferenceLabel;
metrics.surveillance_label = analysis.RoleInfo.SurveillanceLabel;
metrics.role_source = analysis.RoleInfo.RoleSource;
metrics.sample_rate_hz = analysis.Options.SampleRateHz;
metrics.center_frequency_hz = analysis.Options.CenterFrequencyHz;
metrics.expected_pilot_offset_hz = ...
    analysis.Options.ExpectedPilotOffsetHz;
metrics.expected_pilot_frequency_hz = ...
    analysis.Options.ExpectedPilotFrequencyHz;
metrics.repetition_count = height(analysis.ComparisonMetricTable);
metrics.reference_median_pilot_prominence_db = ...
    referenceSummary.MedianPilotProminence_dB;
metrics.surveillance_median_pilot_prominence_db = ...
    surveillanceSummary.MedianPilotProminence_dB;
metrics.reference_pilot_frequency_std_hz = ...
    referenceSummary.PilotFrequencyStd_Hz;
metrics.surveillance_pilot_frequency_std_hz = ...
    surveillanceSummary.PilotFrequencyStd_Hz;
metrics.reference_pilot_confidence_label = ...
    referenceSummary.PilotConfidenceLabel;
metrics.surveillance_pilot_confidence_label = ...
    surveillanceSummary.PilotConfidenceLabel;
metrics.median_reference_minus_surveillance_pilot_psd_db = median( ...
    analysis.ComparisonMetricTable.ReferenceMinusSurveillancePilotPsd_dB, ...
    "omitnan");
metrics.median_reference_minus_surveillance_data_band_median_psd_db = ...
    median( ...
    analysis.ComparisonMetricTable.ReferenceMinusSurveillanceDataBandMedianPsd_dB, ...
    "omitnan");
metrics.median_reference_minus_surveillance_data_band_power_db = median( ...
    analysis.ComparisonMetricTable.ReferenceMinusSurveillanceDataBandPower_dB, ...
    "omitnan");
metrics.overall_review_label = overallRow.ReviewLabel;
metrics.overall_review_rationale = overallRow.Rationale;

end

function optionsForOutput = localStripRuntimeOptions(resolvedOptions)

optionsForOutput = rmfield(resolvedOptions, "WelchWindow");

end
