function views = helperBuildTargetCenteredMapViews(maps, truthTable, options)
%HELPERBUILDTARGETCENTEREDMAPVIEWS Build compact geometry-centered map views.

arguments
    maps (:, 1) struct
    truthTable table
    options.RowCount (1, 1) {mustBeNumeric, mustBeReal, ...
        mustBeFinite, mustBeInteger, mustBePositive} = 401
    options.ColumnCount (1, 1) {mustBeNumeric, mustBeReal, ...
        mustBeFinite, mustBeInteger, mustBePositive} = 32
    options.DynamicRange_dB (1, 1) {mustBeNumeric, mustBeReal, ...
        mustBeFinite, mustBePositive} = 50
end

requiredMapFields = [ ...
    "CaseId", "CandidateName", "MapLinear", ...
    "DelayAxis_s", "DopplerAxis_Hz"];
requiredTruthVariables = [ ...
    "ExpectedDelay_s", "ExpectedDoppler_Hz"];

if ~all(isfield(maps, requiredMapFields))
    error("helperBuildTargetCenteredMapViews:MissingMapField", ...
        "Maps must contain case, candidate, power, delay, and Doppler data.");
end
if ~all(ismember(requiredTruthVariables, ...
        string(truthTable.Properties.VariableNames)))
    error("helperBuildTargetCenteredMapViews:MissingTruthVariable", ...
        "Truth must contain expected delay and Doppler coordinates.");
end

viewTemplate = struct( ...
    CaseId="", ...
    CandidateName="", ...
    ViewRole="geometry_centered_compact_display", ...
    TargetRegionPower_dB=single.empty(0, 0), ...
    DelayAxis_s=zeros(1, 0), ...
    DopplerAxis_Hz=zeros(0, 1), ...
    ExpectedDelay_s=zeros(0, 1), ...
    ExpectedDoppler_Hz=zeros(0, 1), ...
    TargetWithinView=false);
views = repmat(viewTemplate, numel(maps), 1);

for mapIndex = 1:numel(maps)
    map = maps(mapIndex);
    delayAxis_s = double(map.DelayAxis_s(:).');
    dopplerAxis_Hz = double(map.DopplerAxis_Hz(:));
    mapPower = double(map.MapLinear);
    localValidateMap(mapPower, delayAxis_s, dopplerAxis_Hz);

    mapTruth = localSelectMapTruth(truthTable, map);
    expectedDelay_s = double(mapTruth.ExpectedDelay_s(:));
    expectedDoppler_Hz = double(mapTruth.ExpectedDoppler_Hz(:));
    if any(~isfinite(expectedDelay_s)) || ...
            any(~isfinite(expectedDoppler_Hz))
        error("helperBuildTargetCenteredMapViews:InvalidTruth", ...
            "Expected delay and Doppler coordinates must be finite.");
    end

    delayIndices = localSelectWindow( ...
        delayAxis_s, expectedDelay_s, options.ColumnCount, "delay");
    dopplerIndices = localSelectWindow( ...
        dopplerAxis_Hz, expectedDoppler_Hz, options.RowCount, "Doppler");
    cropPower = mapPower(dopplerIndices, delayIndices);
    maximumPower = max(cropPower, [], "all");
    if ~(isfinite(maximumPower) && maximumPower > 0)
        error("helperBuildTargetCenteredMapViews:InvalidPower", ...
            "The selected map view must contain positive finite power.");
    end

    normalizedPower = cropPower ./ maximumPower;
    powerFloor = 10.0 ^ (-double(options.DynamicRange_dB) ./ 10.0);
    viewDelayAxis_s = delayAxis_s(delayIndices);
    viewDopplerAxis_Hz = dopplerAxis_Hz(dopplerIndices);
    targetWithinView = all( ...
        expectedDelay_s >= min(viewDelayAxis_s) & ...
        expectedDelay_s <= max(viewDelayAxis_s) & ...
        expectedDoppler_Hz >= min(viewDopplerAxis_Hz) & ...
        expectedDoppler_Hz <= max(viewDopplerAxis_Hz));

    views(mapIndex) = struct( ...
        CaseId=string(map.CaseId), ...
        CandidateName=string(map.CandidateName), ...
        ViewRole="geometry_centered_compact_display", ...
        TargetRegionPower_dB=single(10.0 .* log10(max( ...
        normalizedPower, powerFloor))), ...
        DelayAxis_s=viewDelayAxis_s, ...
        DopplerAxis_Hz=viewDopplerAxis_Hz, ...
        ExpectedDelay_s=expectedDelay_s, ...
        ExpectedDoppler_Hz=expectedDoppler_Hz, ...
        TargetWithinView=targetWithinView);
end
end

function localValidateMap(mapPower, delayAxis_s, dopplerAxis_Hz)
if ~ismatrix(mapPower) || ...
        ~isequal(size(mapPower), ...
        [numel(dopplerAxis_Hz), numel(delayAxis_s)])
    error("helperBuildTargetCenteredMapViews:MapSize", ...
        "Map dimensions must match the Doppler and delay axes.");
end
if isempty(delayAxis_s) || isempty(dopplerAxis_Hz) || ...
        any(~isfinite(delayAxis_s)) || ...
        any(~isfinite(dopplerAxis_Hz))
    error("helperBuildTargetCenteredMapViews:InvalidAxis", ...
        "Map axes must be nonempty and finite.");
end
if any(~isfinite(mapPower), "all") || any(mapPower < 0, "all")
    error("helperBuildTargetCenteredMapViews:InvalidPower", ...
        "Map power must be finite and nonnegative.");
end
end

function mapTruth = localSelectMapTruth(truthTable, map)
truthMask = true(height(truthTable), 1);
variables = string(truthTable.Properties.VariableNames);
if ismember("CaseId", variables)
    truthMask = truthMask & ...
        string(truthTable.CaseId) == string(map.CaseId);
end
if ismember("CandidateName", variables)
    truthMask = truthMask & ...
        string(truthTable.CandidateName) == string(map.CandidateName);
end
mapTruth = truthTable(truthMask, :);
if isempty(mapTruth)
    error("helperBuildTargetCenteredMapViews:MissingTruth", ...
        "No truth coordinates match map %s / %s.", ...
        string(map.CaseId), string(map.CandidateName));
end
end

function indices = localSelectWindow(axisValues, targetValues, count, axisName)
axisValues = axisValues(:);
targetValues = targetValues(:);
axisMinimum = min(axisValues);
axisMaximum = max(axisValues);
if any(targetValues < axisMinimum) || any(targetValues > axisMaximum)
    error("helperBuildTargetCenteredMapViews:TruthOutsideMap", ...
        "Expected target %s lies outside the full map axis.", axisName);
end

windowCount = min(double(count), numel(axisValues));
[~, targetIndices] = min(abs(axisValues - targetValues.'), [], 1);
firstTargetIndex = min(targetIndices);
lastTargetIndex = max(targetIndices);
if lastTargetIndex - firstTargetIndex + 1 > windowCount
    error("helperBuildTargetCenteredMapViews:TruthSpanExceedsView", ...
        "Expected target %s span exceeds the compact view.", axisName);
end

centerIndex = round(mean([firstTargetIndex, lastTargetIndex]));
firstIndex = centerIndex - floor((windowCount - 1) ./ 2.0);
firstIndex = max(1, min(firstIndex, numel(axisValues) - windowCount + 1));
if firstTargetIndex < firstIndex
    firstIndex = firstTargetIndex;
elseif lastTargetIndex > firstIndex + windowCount - 1
    firstIndex = lastTargetIndex - windowCount + 1;
end
firstIndex = max(1, min(firstIndex, numel(axisValues) - windowCount + 1));
indices = firstIndex:(firstIndex + windowCount - 1);
end
