function analysis = helperAnalyzeG4MapRateValidity(pairInput, options)
%HELPERANALYZEG4MAPRATEVALIDITY Compare native- and reduced-rate maps.
%
%   ANALYSIS = HELPERANALYZEG4MAPRATEVALIDITY(PAIRINPUT, OPTIONS) forms a
%   bounded cross-ambiguity map from an aligned native-rate signal pair,
%   forms the corresponding reduced-rate map using RESAMPLE, and compares
%   both representations on identical physical delay/Doppler cells.
%
%   PAIRINPUT must contain ReferenceSignal, SurveillanceSignal, and
%   NativeSampleRateHz. Optional metadata fields are copied into the compact
%   result row. ReducedReferenceSignal and ReducedSurveillanceSignal may be
%   supplied when reduction was performed before extracting the CPI, as in
%   the established G4/G5 production path. Supplied reduced signals require
%   NativeWindowStartSample and ReducedWindowStartSample provenance.
%
%   Native ambiguity magnitude is evaluated with AMBGFUN Doppler cuts and
%   converted to linear power before native samples are averaged into the
%   reduced-rate physical cells. ReducedMapFormation controls whether the
%   reduced map uses streamed Doppler cuts or a transient production full map.
%   No complete map is retained in either mode.

arguments
    pairInput (1,1) struct
    options (1,1) struct = struct()
end

localValidateNativeFunctions();
resolvedOptions = localResolveOptions(options);
localValidatePairInput(pairInput, resolvedOptions);

factorCount = numel(resolvedOptions.DecimationFactors);
rows = repmat(localPairRowTemplate(), factorCount, 1);
mapProducts = cell(factorCount, 1);

for factorIndex = 1:factorCount
    decimationFactor = resolvedOptions.DecimationFactors(factorIndex);
    [rows(factorIndex), mapProducts{factorIndex}] = ...
        localEvaluateFactor(pairInput, decimationFactor, resolvedOptions);
end

pairTable = struct2table(rows);
factorSummaryTable = localBuildFactorSummaryTable(pairTable, ...
    resolvedOptions);

if any(factorSummaryTable.DecimationFactor == ...
        resolvedOptions.InitialDecimationFactor)
    selection = helperSelectG4RDecimationFactor(factorSummaryTable, ...
        resolvedOptions.InitialDecimationFactor, ...
        resolvedOptions.RetuneFactors);
else
    selection = struct( ...
        "Decision", "factor_evaluation_only", ...
        "Outcome", "retune", ...
        "SelectedDecimationFactor", NaN, ...
        "NextAction", ...
        "Combine these rows with the factor-200 pilot result.");
end

representativeComparisons = localSelectRepresentativeComparisons( ...
    mapProducts, pairTable, resolvedOptions);

analysis = struct();
analysis.SchemaVersion = "g4r_map_rate_validity_v1";
analysis.StageId = "G4_R_Map_Rate_Validity";
analysis.AnalysisTimestampZ = string(datetime("now", TimeZone="UTC", ...
    Format="yyyyMMdd'T'HHmmssSSS'Z'"));
analysis.Configuration = localBuildConfiguration(resolvedOptions);
analysis.PairTable = pairTable;
analysis.FactorSummaryTable = factorSummaryTable;
analysis.PilotDecision = selection.Decision;
analysis.Outcome = selection.Outcome;
analysis.SelectedDecimationFactor = selection.SelectedDecimationFactor;
analysis.NextAction = selection.NextAction;
analysis.RepresentativeComparisons = representativeComparisons;
analysis.FormalG5Enabled = false;
analysis.FormalG6Enabled = false;
analysis.FormalG8Enabled = false;
analysis.CompactResultAudit = localBuildCompactResultAudit(analysis);

end

function localValidateNativeFunctions()

if exist("ambgfun", "file") ~= 2
    error("helperAnalyzeG4MapRateValidity:MissingAmbgfun", ...
        "G4-R requires ambgfun from Phased Array System Toolbox.");
end

if exist("resample", "file") ~= 2
    error("helperAnalyzeG4MapRateValidity:MissingResample", ...
        "G4-R requires resample from Signal Processing Toolbox.");
end

end

function resolvedOptions = localResolveOptions(options)

resolvedOptions = struct();
resolvedOptions.InitialDecimationFactor = 200.0;
resolvedOptions.RetuneFactors = [100.0 50.0 20.0];
resolvedOptions.DecimationFactors = 200.0;
resolvedOptions.DelaySupport_s = [-1.2e-3 0.15e-3];
resolvedOptions.DopplerSupport_Hz = [-750.0 750.0];
resolvedOptions.NativeCutBatchSize = 16.0;
resolvedOptions.ReducedCutBatchSize = 32.0;
resolvedOptions.NativeDopplerSamplesPerCell = 2.0;
resolvedOptions.ReductionInputClass = "production_double";
resolvedOptions.PowerSemantics = "legacy_double";
resolvedOptions.ReducedMapFormation = "streamed_cuts";
resolvedOptions.OriginDelayRadius_s = 6.510416666666667e-5;
resolvedOptions.OriginDopplerRadius_Hz = 25.0;
resolvedOptions.DirectPathExclusionDelayRadius_s = 1.953125e-4;
resolvedOptions.DirectPathExclusionDopplerRadius_Hz = 25.0;
resolvedOptions.ZeroDopplerRidgeHalfWidth_Hz = 25.0;
resolvedOptions.TargetSearchDelayHalfExtent_s = 6.510416666666667e-5;
resolvedOptions.TargetSearchDopplerHalfExtent_Hz = 15.0;
resolvedOptions.PeakCellTolerance = 1.0;
resolvedOptions.MinimumMedianNormalizedMapCorrelation = 0.90;
resolvedOptions.MinimumPairNormalizedMapCorrelation = 0.80;
resolvedOptions.MaximumOffOriginEnergyFractionDifference = 0.05;
resolvedOptions.MaximumZeroDopplerEnergyFractionDifference = 0.10;
resolvedOptions.MaximumDirectPathToOffRidgeDifference_dB = 6.0;
resolvedOptions.RetainComparisonMaps = true;
resolvedOptions.MaximumRetainedComparisons = 2.0;
resolvedOptions.EvaluationScope = "pilot";

optionNames = fieldnames(options);

for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    resolvedOptions.(optionName) = options.(optionName);
end

resolvedOptions.DecimationFactors = double( ...
    resolvedOptions.DecimationFactors(:).');
resolvedOptions.RetuneFactors = double( ...
    resolvedOptions.RetuneFactors(:).');
resolvedOptions.DelaySupport_s = double( ...
    resolvedOptions.DelaySupport_s(:).');
resolvedOptions.DopplerSupport_Hz = double( ...
    resolvedOptions.DopplerSupport_Hz(:).');
resolvedOptions.NativeCutBatchSize = round(double( ...
    resolvedOptions.NativeCutBatchSize));
resolvedOptions.ReducedCutBatchSize = round(double( ...
    resolvedOptions.ReducedCutBatchSize));
resolvedOptions.NativeDopplerSamplesPerCell = double( ...
    resolvedOptions.NativeDopplerSamplesPerCell);
resolvedOptions.MaximumRetainedComparisons = round(double( ...
    resolvedOptions.MaximumRetainedComparisons));
resolvedOptions.RetainComparisonMaps = logical( ...
    resolvedOptions.RetainComparisonMaps);
resolvedOptions.EvaluationScope = lower(string( ...
    resolvedOptions.EvaluationScope));
resolvedOptions.ReductionInputClass = lower(string( ...
    resolvedOptions.ReductionInputClass));
resolvedOptions.PowerSemantics = lower(string( ...
    resolvedOptions.PowerSemantics));
resolvedOptions.ReducedMapFormation = lower(string( ...
    resolvedOptions.ReducedMapFormation));

if isempty(resolvedOptions.DecimationFactors) || ...
        any(~isfinite(resolvedOptions.DecimationFactors)) || ...
        any(resolvedOptions.DecimationFactors < 1.0) || ...
        any(resolvedOptions.DecimationFactors ~= ...
        round(resolvedOptions.DecimationFactors))
    error("helperAnalyzeG4MapRateValidity:InvalidDecimationFactors", ...
        "DecimationFactors must contain positive integers.");
end

if numel(unique(resolvedOptions.DecimationFactors)) ~= ...
        numel(resolvedOptions.DecimationFactors)
    error("helperAnalyzeG4MapRateValidity:DuplicateDecimationFactors", ...
        "DecimationFactors must be unique.");
end

if numel(resolvedOptions.DelaySupport_s) ~= 2 || ...
        resolvedOptions.DelaySupport_s(1) >= ...
        resolvedOptions.DelaySupport_s(2)
    error("helperAnalyzeG4MapRateValidity:InvalidDelaySupport", ...
        "DelaySupport_s must be a strictly increasing two-element vector.");
end

if numel(resolvedOptions.DopplerSupport_Hz) ~= 2 || ...
        resolvedOptions.DopplerSupport_Hz(1) >= ...
        resolvedOptions.DopplerSupport_Hz(2)
    error("helperAnalyzeG4MapRateValidity:InvalidDopplerSupport", ...
        "DopplerSupport_Hz must be a strictly increasing two-element vector.");
end

if resolvedOptions.NativeCutBatchSize < 1 || ...
        resolvedOptions.ReducedCutBatchSize < 1
    error("helperAnalyzeG4MapRateValidity:InvalidBatchSize", ...
        "Cut batch sizes must be positive integers.");
end

if ~isscalar(resolvedOptions.NativeDopplerSamplesPerCell) || ...
        ~isfinite(resolvedOptions.NativeDopplerSamplesPerCell) || ...
        resolvedOptions.NativeDopplerSamplesPerCell < 1 || ...
        resolvedOptions.NativeDopplerSamplesPerCell ~= round( ...
        resolvedOptions.NativeDopplerSamplesPerCell)
    error("helperAnalyzeG4MapRateValidity:InvalidDopplerQuadrature", ...
        "NativeDopplerSamplesPerCell must be a positive integer.");
end

if ~isscalar(resolvedOptions.RetainComparisonMaps)
    error("helperAnalyzeG4MapRateValidity:InvalidRetentionOption", ...
        "RetainComparisonMaps must be a logical scalar.");
end

if ~isscalar(resolvedOptions.ReductionInputClass) || ...
        ~ismember(resolvedOptions.ReductionInputClass, ...
        ["production_double", "legacy_input_class"])
    error("helperAnalyzeG4MapRateValidity:InvalidReductionInputClass", ...
        "ReductionInputClass must be production_double or legacy_input_class.");
end

if ~isscalar(resolvedOptions.PowerSemantics) || ...
        ~ismember(resolvedOptions.PowerSemantics, ...
        ["legacy_double", "production_g4"])
    error("helperAnalyzeG4MapRateValidity:InvalidPowerSemantics", ...
        "PowerSemantics must be legacy_double or production_g4.");
end

if ~isscalar(resolvedOptions.ReducedMapFormation) || ...
        ~ismember(resolvedOptions.ReducedMapFormation, ...
        ["streamed_cuts", "production_full_map"])
    error("helperAnalyzeG4MapRateValidity:InvalidReducedMapFormation", ...
        "ReducedMapFormation must be streamed_cuts or production_full_map.");
end

end

function localValidatePairInput(pairInput, resolvedOptions)

requiredFields = [ ...
    "ReferenceSignal"; ...
    "SurveillanceSignal"; ...
    "NativeSampleRateHz" ...
    ];

for fieldIndex = 1:numel(requiredFields)
    if ~isfield(pairInput, requiredFields(fieldIndex))
        error("helperAnalyzeG4MapRateValidity:MissingPairField", ...
            "pairInput is missing %s.", requiredFields(fieldIndex));
    end
end

referenceSignal = pairInput.ReferenceSignal;
surveillanceSignal = pairInput.SurveillanceSignal;
sampleRateHz = double(pairInput.NativeSampleRateHz);

if ~isvector(referenceSignal) || ~isvector(surveillanceSignal) || ...
        isempty(referenceSignal) || ...
        numel(referenceSignal) ~= numel(surveillanceSignal)
    error("helperAnalyzeG4MapRateValidity:InvalidSignalPair", ...
        "ReferenceSignal and SurveillanceSignal must be equal-length vectors.");
end

if any(~isfinite(referenceSignal), "all") || ...
        any(~isfinite(surveillanceSignal), "all")
    error("helperAnalyzeG4MapRateValidity:NonfiniteSignalPair", ...
        "The signal pair must contain only finite samples.");
end

if ~isscalar(sampleRateHz) || ~isfinite(sampleRateHz) || sampleRateHz <= 0
    error("helperAnalyzeG4MapRateValidity:InvalidSampleRate", ...
        "NativeSampleRateHz must be a positive finite scalar.");
end

cpiDuration_s = localResolveNumericMetadata(pairInput, ...
    "CpiDuration_s", numel(referenceSignal) ./ sampleRateHz);

if abs(cpiDuration_s .* sampleRateHz - numel(referenceSignal)) > 1.0
    error("helperAnalyzeG4MapRateValidity:InconsistentCpiDuration", ...
        "CpiDuration_s is inconsistent with the native signal length.");
end

maximumAbsoluteDelay_s = (numel(referenceSignal) - 1.0) ./ sampleRateHz;

delaySupportOutsideCpi = [ ...
    resolvedOptions.DelaySupport_s(1) < -maximumAbsoluteDelay_s, ...
    resolvedOptions.DelaySupport_s(2) > maximumAbsoluteDelay_s ...
    ];

if any(delaySupportOutsideCpi)
    error("helperAnalyzeG4MapRateValidity:DelaySupportOutsideCpi", ...
        "DelaySupport_s lies outside the available CPI lag support.");
end

for factorIndex = 1:numel(resolvedOptions.DecimationFactors)
    factor = resolvedOptions.DecimationFactors(factorIndex);
    reducedSampleRateHz = sampleRateHz ./ factor;

    if any(max(abs(resolvedOptions.DopplerSupport_Hz)) >= ...
            reducedSampleRateHz ./ 2.0)
        error("helperAnalyzeG4MapRateValidity:DopplerSupportOutsideRate", ...
            "DopplerSupport_Hz exceeds the Nyquist support at factor %d.", ...
            factor);
    end
end

end

function [row, mapProduct] = localEvaluateFactor( ...
    pairInput, decimationFactor, resolvedOptions)

factorTimer = tic;
referenceNative = pairInput.ReferenceSignal(:);
surveillanceNative = pairInput.SurveillanceSignal(:);
nativeSampleRateHz = double(pairInput.NativeSampleRateHz);
cpiDuration_s = localResolveNumericMetadata(pairInput, ...
    "CpiDuration_s", numel(referenceNative) ./ nativeSampleRateHz);
reducedSampleRateHz = nativeSampleRateHz ./ decimationFactor;

[referenceReduced, surveillanceReduced, cpiAlignment] = ...
    localResolveReducedSignals(pairInput, referenceNative, ...
    surveillanceNative, nativeSampleRateHz, decimationFactor, ...
    resolvedOptions.ReductionInputClass);
[commonDelayAxis_s, commonDopplerAxis_Hz] = localBuildCommonAxes( ...
    numel(referenceReduced), reducedSampleRateHz, resolvedOptions);
prfVector_Hz = [1.0 ./ cpiDuration_s 1.0 ./ cpiDuration_s];

reducedTimer = tic;
[reducedCellPower, reducedCost] = localBuildReducedCellPower( ...
    referenceReduced, surveillanceReduced, reducedSampleRateHz, ...
    prfVector_Hz, commonDelayAxis_s, commonDopplerAxis_Hz, ...
    resolvedOptions);
reducedElapsed_s = toc(reducedTimer);

nativeTimer = tic;
[nativeCellPower, nativeCost] = localBuildNativeCellPower( ...
    referenceNative, surveillanceNative, nativeSampleRateHz, ...
    prfVector_Hz, commonDelayAxis_s, commonDopplerAxis_Hz, ...
    resolvedOptions);
nativeElapsed_s = toc(nativeTimer);

comparison = localCompareMaps(nativeCellPower, reducedCellPower, ...
    commonDelayAxis_s, commonDopplerAxis_Hz, pairInput, ...
    resolvedOptions);
row = localBuildPairRow(pairInput, decimationFactor, ...
    nativeSampleRateHz, reducedSampleRateHz, commonDelayAxis_s, ...
    commonDopplerAxis_Hz, nativeCost, reducedCost, nativeElapsed_s, ...
    reducedElapsed_s, toc(factorTimer), cpiAlignment, comparison);
mapProduct = localBuildMapProduct(pairInput, decimationFactor, ...
    commonDelayAxis_s, commonDopplerAxis_Hz, nativeCellPower, ...
    reducedCellPower, comparison);

end

function [referenceReduced, surveillanceReduced, cpiAlignment] = ...
    localResolveReducedSignals(pairInput, referenceNative, ...
    surveillanceNative, nativeSampleRateHz, decimationFactor, ...
    reductionInputClass)

hasReference = isfield(pairInput, "ReducedReferenceSignal");
hasSurveillance = isfield(pairInput, "ReducedSurveillanceSignal");
hasFullReference = isfield(pairInput, "FullReferenceSignal");
hasFullSurveillance = isfield(pairInput, "FullSurveillanceSignal");
hasWindowStart = isfield(pairInput, "NativeWindowStartSample");
hasReducedWindowStart = isfield(pairInput, "ReducedWindowStartSample");

if xor(hasReference, hasSurveillance)
    error("helperAnalyzeG4MapRateValidity:IncompleteReducedPair", ...
        "Both reduced signals must be supplied together.");
end

if hasReference
    if ~hasWindowStart || ~hasReducedWindowStart
        error("helperAnalyzeG4MapRateValidity:MissingReducedAlignment", ...
            "Supplied reduced signals require native and reduced window start samples.");
    end

    suppliedFactor = localResolveNumericMetadata(pairInput, ...
        "ReducedSignalDecimationFactor", decimationFactor);

    if suppliedFactor ~= decimationFactor
        error("helperAnalyzeG4MapRateValidity:ReducedFactorMismatch", ...
            "Supplied reduced signals do not match factor %d.", ...
            decimationFactor);
    end

    referenceReduced = pairInput.ReducedReferenceSignal(:);
    surveillanceReduced = pairInput.ReducedSurveillanceSignal(:);
    cpiAlignment = helperMeasureG4RCpiAlignment( ...
        double(pairInput.NativeWindowStartSample), numel(referenceNative), ...
        nativeSampleRateHz, decimationFactor);
    expectedReducedCount = cpiAlignment.ReducedSampleCount(1);
    expectedReducedStart = cpiAlignment.ReducedWindowStartSample(1);
    suppliedReducedStart = localResolveNumericMetadata(pairInput, ...
        "ReducedWindowStartSample", NaN);

    if numel(referenceReduced) ~= expectedReducedCount
        error("helperAnalyzeG4MapRateValidity:ReducedLengthMismatch", ...
            "Supplied reduced signals do not match the expected CPI sample count.");
    end

    if suppliedReducedStart ~= expectedReducedStart
        error("helperAnalyzeG4MapRateValidity:ReducedStartMismatch", ...
            "The supplied reduced window start violates the CPI alignment rule.");
    end
elseif hasFullReference && hasFullSurveillance && hasWindowStart
    fullReference = pairInput.FullReferenceSignal(:);
    fullSurveillance = pairInput.FullSurveillanceSignal(:);

    if numel(fullReference) ~= numel(fullSurveillance)
        error("helperAnalyzeG4MapRateValidity:InvalidFullSignalPair", ...
            "Full native signals must have equal lengths.");
    end

    if reductionInputClass == "production_double"
        fullReferenceReduced = helperResampleG4FullRepetition( ...
            fullReference, decimationFactor);
        fullSurveillanceReduced = helperResampleG4FullRepetition( ...
            fullSurveillance, decimationFactor);
    else
        fullReferenceReduced = single(resample(fullReference, 1, ...
            decimationFactor));
        fullSurveillanceReduced = single(resample(fullSurveillance, 1, ...
            decimationFactor));
    end
    cpiAlignment = helperMeasureG4RCpiAlignment( ...
        double(pairInput.NativeWindowStartSample), ...
        numel(referenceNative), nativeSampleRateHz, decimationFactor);
    reducedStartSample = cpiAlignment.ReducedWindowStartSample(1);
    reducedSampleCount = cpiAlignment.ReducedSampleCount(1);
    reducedStopSample = reducedStartSample + reducedSampleCount - 1.0;

    if reducedStartSample < 1 || ...
            reducedStopSample > numel(fullReferenceReduced)
        error("helperAnalyzeG4MapRateValidity:InvalidReducedWindow", ...
            "The reduced-domain CPI window lies outside the full signal.");
    end

    referenceReduced = fullReferenceReduced( ...
        reducedStartSample:reducedStopSample);
    surveillanceReduced = fullSurveillanceReduced( ...
        reducedStartSample:reducedStopSample);
elseif hasFullReference || hasFullSurveillance || hasWindowStart
    error("helperAnalyzeG4MapRateValidity:IncompleteFullSignalContext", ...
        "Full-signal reduction requires both full signals and a native window start.");
else
    if reductionInputClass == "production_double"
        referenceReduced = helperResampleG4FullRepetition( ...
            referenceNative, decimationFactor);
        surveillanceReduced = helperResampleG4FullRepetition( ...
            surveillanceNative, decimationFactor);
    else
        referenceReduced = single(resample(referenceNative, 1, ...
            decimationFactor));
        surveillanceReduced = single(resample(surveillanceNative, 1, ...
            decimationFactor));
    end
    cpiAlignment = helperMeasureG4RCpiAlignment( ...
        1.0, numel(referenceNative), nativeSampleRateHz, ...
        decimationFactor);
end

if isempty(referenceReduced) || ...
        numel(referenceReduced) ~= numel(surveillanceReduced)
    error("helperAnalyzeG4MapRateValidity:InvalidReducedPair", ...
        "Reduced signals must be nonempty equal-length vectors.");
end

end

function [delayAxis_s, dopplerAxis_Hz] = localBuildCommonAxes( ...
    sampleCount, sampleRateHz, resolvedOptions)

fullDelayAxis_s = (-(sampleCount - 1):(sampleCount - 1)) ./ sampleRateHz;
dopplerFftLength = 2 .^ nextpow2(2 .* sampleCount - 1);
fullDopplerAxis_Hz = (-dopplerFftLength ./ 2: ...
    dopplerFftLength ./ 2 - 1).' .* ...
    sampleRateHz ./ dopplerFftLength;
delayMask = fullDelayAxis_s >= resolvedOptions.DelaySupport_s(1) & ...
    fullDelayAxis_s <= resolvedOptions.DelaySupport_s(2);
dopplerMask = ...
    fullDopplerAxis_Hz >= resolvedOptions.DopplerSupport_Hz(1) & ...
    fullDopplerAxis_Hz <= resolvedOptions.DopplerSupport_Hz(2);
delayAxis_s = double(fullDelayAxis_s(delayMask));
dopplerAxis_Hz = double(fullDopplerAxis_Hz(dopplerMask));

if numel(delayAxis_s) < 3 || numel(dopplerAxis_Hz) < 3
    error("helperAnalyzeG4MapRateValidity:InsufficientCommonSupport", ...
        "The requested physical support must contain at least three cells.");
end

end

function [cellPower, cost] = localBuildReducedCellPower( ...
    referenceSignal, surveillanceSignal, sampleRateHz, prfVector_Hz, ...
    delayAxis_s, dopplerAxis_Hz, resolvedOptions)

if resolvedOptions.ReducedMapFormation == "production_full_map"
    productionMap = helperFormG4ProductionMap( ...
        referenceSignal, surveillanceSignal, sampleRateHz, prfVector_Hz);
    [cellPower, cellCounts] = helperAggregateG4RMapPower( ...
        double(productionMap.Power), productionMap.DelayAxis_s, ...
        productionMap.DopplerAxis_Hz, delayAxis_s, dopplerAxis_Hz);
    cost = localBuildProductionMapCost(cellCounts);
    localValidateCellPower(cellPower, "reduced");
    return
end

signalPair = localBuildStreamedSignalPair(referenceSignal, ...
    surveillanceSignal, sampleRateHz, prfVector_Hz);
[cellPower, cost] = helperFormG4RStreamedCellPower( ...
    signalPair, delayAxis_s, dopplerAxis_Hz, ...
    DopplerSampleAxis_Hz=dopplerAxis_Hz, ...
    CutBatchSize=resolvedOptions.ReducedCutBatchSize, ...
    PowerSemantics=resolvedOptions.PowerSemantics);
localValidateCellPower(cellPower, "reduced");

end

function cost = localBuildProductionMapCost(cellCounts)

cost = struct();
cost.DopplerCutCount = 0.0;
cost.MinimumDopplerSamplesPerCell = min(cellCounts, [], "all");
cost.MaximumDopplerSamplesPerCell = max(cellCounts, [], "all");
cost.AggregationImplementation = "helperAggregateG4RMapPower";

end

function [cellPower, cost] = localBuildNativeCellPower( ...
    referenceSignal, surveillanceSignal, sampleRateHz, prfVector_Hz, ...
    delayAxis_s, dopplerAxis_Hz, resolvedOptions)

signalPair = localBuildStreamedSignalPair(referenceSignal, ...
    surveillanceSignal, sampleRateHz, prfVector_Hz);
[cellPower, cost] = helperFormG4RStreamedCellPower( ...
    signalPair, delayAxis_s, dopplerAxis_Hz, ...
    DopplerSamplesPerCell= ...
    resolvedOptions.NativeDopplerSamplesPerCell, ...
    CutBatchSize=resolvedOptions.NativeCutBatchSize, ...
    PowerSemantics=resolvedOptions.PowerSemantics);
localValidateCellPower(cellPower, "native");

end

function signalPair = localBuildStreamedSignalPair( ...
    referenceSignal, surveillanceSignal, sampleRateHz, prfVector_Hz)

signalPair = struct( ...
    "ReferenceSignal", referenceSignal, ...
    "SurveillanceSignal", surveillanceSignal, ...
    "SampleRateHz", sampleRateHz, ...
    "PrfVector_Hz", prfVector_Hz);

end

function localValidateCellPower(cellPower, mapLabel)

if isempty(cellPower) || any(~isfinite(cellPower), "all") || ...
        any(cellPower < 0.0, "all") || sum(cellPower, "all") <= 0.0
    error("helperAnalyzeG4MapRateValidity:InvalidMapPower", ...
        "The %s-rate common-cell map is invalid.", mapLabel);
end

end

function comparison = localCompareMaps(nativePower, reducedPower, ...
    delayAxis_s, dopplerAxis_Hz, pairInput, resolvedOptions)

nativeNormalized = nativePower ./ sum(nativePower, "all");
reducedNormalized = reducedPower ./ sum(reducedPower, "all");
normalizedCorrelation = localLinearCorrelation( ...
    nativeNormalized, reducedNormalized);
[nativePeakRow, nativePeakColumn] = localMaximumLocation(nativePower);
[reducedPeakRow, reducedPeakColumn] = ...
    localMaximumLocation(reducedPower);
delayPeakDifference_cells = abs( ...
    nativePeakColumn - reducedPeakColumn);
dopplerPeakDifference_cells = abs( ...
    nativePeakRow - reducedPeakRow);
peakAgreement = delayPeakDifference_cells <= ...
    resolvedOptions.PeakCellTolerance && ...
    dopplerPeakDifference_cells <= resolvedOptions.PeakCellTolerance;

nativeMetrics = localBuildPhysicalMetrics(nativePower, delayAxis_s, ...
    dopplerAxis_Hz, pairInput, resolvedOptions);
reducedMetrics = localBuildPhysicalMetrics(reducedPower, delayAxis_s, ...
    dopplerAxis_Hz, pairInput, resolvedOptions);
offOriginDifference = abs( ...
    nativeMetrics.OffOriginEnergyFraction - ...
    reducedMetrics.OffOriginEnergyFraction);
zeroDopplerDifference = abs( ...
    nativeMetrics.ZeroDopplerEnergyFraction - ...
    reducedMetrics.ZeroDopplerEnergyFraction);
directPathToOffRidgeDifference_dB = abs( ...
    nativeMetrics.DirectPathToOffRidge_dB - ...
    reducedMetrics.DirectPathToOffRidge_dB);
directPathClassificationUnchanged = ...
    nativeMetrics.DirectPathClassification == ...
    reducedMetrics.DirectPathClassification;
targetClassificationUnchanged = ...
    nativeMetrics.TargetClassification == ...
    reducedMetrics.TargetClassification;

comparison = struct();
comparison.NativeNormalized = nativeNormalized;
comparison.ReducedNormalized = reducedNormalized;
comparison.NormalizedMapCorrelation = normalizedCorrelation;
comparison.NativePeakDelay_s = delayAxis_s(nativePeakColumn);
comparison.NativePeakDoppler_Hz = ...
    dopplerAxis_Hz(nativePeakRow);
comparison.ReducedPeakDelay_s = delayAxis_s(reducedPeakColumn);
comparison.ReducedPeakDoppler_Hz = ...
    dopplerAxis_Hz(reducedPeakRow);
comparison.DelayPeakDifference_cells = delayPeakDifference_cells;
comparison.DopplerPeakDifference_cells = ...
    dopplerPeakDifference_cells;
comparison.PeakAgreement = peakAgreement;
comparison.NativeMetrics = nativeMetrics;
comparison.ReducedMetrics = reducedMetrics;
comparison.OffOriginEnergyFractionDifference = offOriginDifference;
comparison.ZeroDopplerEnergyFractionDifference = zeroDopplerDifference;
comparison.DirectPathToOffRidgeDifference_dB = ...
    directPathToOffRidgeDifference_dB;
comparison.DirectPathClassificationUnchanged = ...
    directPathClassificationUnchanged;
comparison.TargetClassificationUnchanged = ...
    targetClassificationUnchanged;
comparison.AllCriteriaPass = peakAgreement && ...
    normalizedCorrelation >= ...
    resolvedOptions.MinimumPairNormalizedMapCorrelation && ...
    offOriginDifference <= ...
    resolvedOptions.MaximumOffOriginEnergyFractionDifference && ...
    zeroDopplerDifference <= ...
    resolvedOptions.MaximumZeroDopplerEnergyFractionDifference && ...
    directPathToOffRidgeDifference_dB <= ...
    resolvedOptions.MaximumDirectPathToOffRidgeDifference_dB && ...
    directPathClassificationUnchanged && targetClassificationUnchanged;

end

function value = localLinearCorrelation(firstMap, secondMap)

firstValues = double(firstMap(:));
secondValues = double(secondMap(:));

if std(firstValues) == 0.0 || std(secondValues) == 0.0
    value = double(isequal(firstValues, secondValues));
    return
end

correlationMatrix = corrcoef(firstValues, secondValues);
value = correlationMatrix(1, 2);

end

function [rowIndex, columnIndex] = localMaximumLocation(mapPower)

[~, linearIndex] = max(mapPower, [], "all");
[rowIndex, columnIndex] = ind2sub(size(mapPower), linearIndex);

end

function metrics = localBuildPhysicalMetrics(mapPower, delayAxis_s, ...
    dopplerAxis_Hz, pairInput, resolvedOptions)

[delayGrid_s, dopplerGrid_Hz] = meshgrid( ...
    delayAxis_s, dopplerAxis_Hz);
originMask = abs(delayGrid_s) <= ...
    resolvedOptions.OriginDelayRadius_s & ...
    abs(dopplerGrid_Hz) <= ...
    resolvedOptions.OriginDopplerRadius_Hz;
directPathExclusionMask = abs(delayGrid_s) <= ...
    resolvedOptions.DirectPathExclusionDelayRadius_s & ...
    abs(dopplerGrid_Hz) <= ...
    resolvedOptions.DirectPathExclusionDopplerRadius_Hz;
zeroDopplerMask = abs(dopplerGrid_Hz) <= ...
    resolvedOptions.ZeroDopplerRidgeHalfWidth_Hz;
offOriginMask = ~directPathExclusionMask;
offRidgeMask = offOriginMask & ~zeroDopplerMask;
totalPower = sum(mapPower, "all");
directPathPower = max(mapPower(originMask), [], "all");
offRidgeValues = mapPower(offRidgeMask);

if isempty(offRidgeValues)
    error("helperAnalyzeG4MapRateValidity:EmptyOffRidgeRegion", ...
        "Physical support leaves no off-ridge comparison cells.");
end

[globalRow, globalColumn] = localMaximumLocation(mapPower);
globalPeakInOrigin = originMask(globalRow, globalColumn);

if globalPeakInOrigin
    directPathClassification = "origin_peak";
else
    directPathClassification = "off_origin_peak";
end

targetClassification = "not_applicable";
targetDelayError_cells = NaN;
targetDopplerError_cells = NaN;

if localResolveLogicalMetadata(pairInput, "HasInjectedTarget", false)
    expectedDelay_s = localResolveNumericMetadata(pairInput, ...
        "ExpectedTargetDelay_s", NaN);
    expectedDoppler_Hz = localResolveNumericMetadata(pairInput, ...
        "ExpectedTargetDoppler_Hz", NaN);

    if ~isfinite(expectedDelay_s) || ~isfinite(expectedDoppler_Hz)
        error("helperAnalyzeG4MapRateValidity:MissingTargetCoordinates", ...
            "Injected-target pairs require expected physical coordinates.");
    end

    targetMask = abs(delayGrid_s - expectedDelay_s) <= ...
        resolvedOptions.TargetSearchDelayHalfExtent_s & ...
        abs(dopplerGrid_Hz - expectedDoppler_Hz) <= ...
        resolvedOptions.TargetSearchDopplerHalfExtent_Hz;

    if ~any(targetMask, "all")
        error("helperAnalyzeG4MapRateValidity:TargetOutsideSupport", ...
            "The expected target search region is outside common support.");
    end

    targetMap = mapPower;
    targetMap(~targetMask) = -Inf;
    [targetRow, targetColumn] = localMaximumLocation(targetMap);
    delaySpacing_s = median(diff(delayAxis_s));
    dopplerSpacing_Hz = median(diff(dopplerAxis_Hz));
    targetDelayError_cells = abs( ...
        delayAxis_s(targetColumn) - expectedDelay_s) ./ delaySpacing_s;
    targetDopplerError_cells = abs( ...
        dopplerAxis_Hz(targetRow) - expectedDoppler_Hz) ./ ...
        dopplerSpacing_Hz;

    targetPeakWithinTolerance = all([ ...
        targetDelayError_cells <= 1.0, ...
        targetDopplerError_cells <= 1.0 ...
        ]);

    if targetPeakWithinTolerance
        targetClassification = "expected_cell_peak";
    else
        targetClassification = "search_region_peak_offset";
    end
end

metrics = struct();
metrics.OffOriginEnergyFraction = ...
    sum(mapPower(offOriginMask), "all") ./ totalPower;
metrics.ZeroDopplerEnergyFraction = ...
    sum(mapPower(zeroDopplerMask), "all") ./ totalPower;
metrics.DirectPathToOffRidge_dB = pow2db( ...
    max(directPathPower, eps) ./ ...
    max(median(offRidgeValues, "omitnan"), eps));
metrics.DirectPathClassification = directPathClassification;
metrics.TargetClassification = targetClassification;
metrics.TargetDelayError_cells = targetDelayError_cells;
metrics.TargetDopplerError_cells = targetDopplerError_cells;

end

function row = localBuildPairRow(pairInput, decimationFactor, ...
    nativeSampleRateHz, reducedSampleRateHz, delayAxis_s, ...
    dopplerAxis_Hz, nativeCost, reducedCost, nativeElapsed_s, ...
    reducedElapsed_s, totalElapsed_s, cpiAlignment, comparison)

row = localPairRowTemplate();
row.BackgroundId = localResolveStringMetadata(pairInput, ...
    "BackgroundId", "unspecified");
row.SceneId = localResolveStringMetadata(pairInput, ...
    "SceneId", "real_only");
row.ProductName = localResolveStringMetadata(pairInput, ...
    "ProductName", "none");
row.WindowLabel = localResolveStringMetadata(pairInput, ...
    "WindowLabel", "center");
row.CpiDuration_s = localResolveNumericMetadata(pairInput, ...
    "CpiDuration_s", numel(pairInput.ReferenceSignal) ./ ...
    nativeSampleRateHz);
row.Repetition = localResolveNumericMetadata(pairInput, ...
    "Repetition", 1.0);
row.DecimationFactor = double(decimationFactor);
row.NativeSampleRateHz = nativeSampleRateHz;
row.ReducedSampleRateHz = reducedSampleRateHz;
row.DelayCellWidth_s = median(diff(delayAxis_s));
row.DopplerCellWidth_Hz = median(diff(dopplerAxis_Hz));
row.DelayCellCount = double(numel(delayAxis_s));
row.DopplerCellCount = double(numel(dopplerAxis_Hz));
row.NativeDopplerCutCount = nativeCost.DopplerCutCount;
row.NativeRetainedDelaySampleCount = ...
    nativeCost.RetainedDelaySampleCount;
row.NativeEstimatedLargestBatchBytes = ...
    nativeCost.EstimatedLargestCutBatchBytes;
row.ReducedDopplerCutCount = reducedCost.DopplerCutCount;
row.NativeDopplerSamplesPerCell = ...
    nativeCost.RequestedDopplerSamplesPerCell;
row.NativeMinimumDopplerSamplesPerCell = ...
    nativeCost.MinimumDopplerSamplesPerCell;
row.NativeMaximumDopplerSamplesPerCell = ...
    nativeCost.MaximumDopplerSamplesPerCell;
row.ReducedMinimumDopplerSamplesPerCell = ...
    reducedCost.MinimumDopplerSamplesPerCell;
row.ReducedMaximumDopplerSamplesPerCell = ...
    reducedCost.MaximumDopplerSamplesPerCell;
row.NativeAggregationImplementation = ...
    nativeCost.AggregationImplementation;
row.ReducedAggregationImplementation = ...
    reducedCost.AggregationImplementation;
row.NativeCpiStartTime_s = cpiAlignment.NativeStartTime_s(1);
row.ReducedCpiStartTime_s = cpiAlignment.ReducedStartTime_s(1);
row.CpiStartTimeOffset_s = cpiAlignment.StartTimeOffset_s(1);
row.CpiStartTimeOffset_reducedSamples = ...
    cpiAlignment.StartTimeOffset_reducedSamples(1);
row.CpiAlignmentWithinHalfReducedSample = ...
    cpiAlignment.WithinHalfReducedSample(1);
row.CpiStopBoundaryOffset_s = ...
    cpiAlignment.StopBoundaryOffset_s(1);
row.NativeElapsed_s = nativeElapsed_s;
row.ReducedElapsed_s = reducedElapsed_s;
row.TotalElapsed_s = totalElapsed_s;
row.NativePeakDelay_s = comparison.NativePeakDelay_s;
row.NativePeakDoppler_Hz = comparison.NativePeakDoppler_Hz;
row.ReducedPeakDelay_s = comparison.ReducedPeakDelay_s;
row.ReducedPeakDoppler_Hz = comparison.ReducedPeakDoppler_Hz;
row.DelayPeakDifference_cells = ...
    comparison.DelayPeakDifference_cells;
row.DopplerPeakDifference_cells = ...
    comparison.DopplerPeakDifference_cells;
row.PeakAgreement = comparison.PeakAgreement;
row.NormalizedMapCorrelation = ...
    comparison.NormalizedMapCorrelation;
row.NativeOffOriginEnergyFraction = ...
    comparison.NativeMetrics.OffOriginEnergyFraction;
row.ReducedOffOriginEnergyFraction = ...
    comparison.ReducedMetrics.OffOriginEnergyFraction;
row.OffOriginEnergyFractionDifference = ...
    comparison.OffOriginEnergyFractionDifference;
row.NativeZeroDopplerEnergyFraction = ...
    comparison.NativeMetrics.ZeroDopplerEnergyFraction;
row.ReducedZeroDopplerEnergyFraction = ...
    comparison.ReducedMetrics.ZeroDopplerEnergyFraction;
row.ZeroDopplerEnergyFractionDifference = ...
    comparison.ZeroDopplerEnergyFractionDifference;
row.NativeDirectPathToOffRidge_dB = ...
    comparison.NativeMetrics.DirectPathToOffRidge_dB;
row.ReducedDirectPathToOffRidge_dB = ...
    comparison.ReducedMetrics.DirectPathToOffRidge_dB;
row.DirectPathToOffRidgeDifference_dB = ...
    comparison.DirectPathToOffRidgeDifference_dB;
row.NativeDirectPathClassification = ...
    comparison.NativeMetrics.DirectPathClassification;
row.ReducedDirectPathClassification = ...
    comparison.ReducedMetrics.DirectPathClassification;
row.DirectPathClassificationUnchanged = ...
    comparison.DirectPathClassificationUnchanged;
row.NativeTargetClassification = ...
    comparison.NativeMetrics.TargetClassification;
row.ReducedTargetClassification = ...
    comparison.ReducedMetrics.TargetClassification;
row.TargetClassificationUnchanged = ...
    comparison.TargetClassificationUnchanged;
row.AllPairCriteriaPass = comparison.AllCriteriaPass;

end

function row = localPairRowTemplate()

row = struct( ...
    "BackgroundId", "", ...
    "SceneId", "", ...
    "ProductName", "", ...
    "WindowLabel", "", ...
    "CpiDuration_s", NaN, ...
    "Repetition", NaN, ...
    "DecimationFactor", NaN, ...
    "NativeSampleRateHz", NaN, ...
    "ReducedSampleRateHz", NaN, ...
    "DelayCellWidth_s", NaN, ...
    "DopplerCellWidth_Hz", NaN, ...
    "DelayCellCount", NaN, ...
    "DopplerCellCount", NaN, ...
    "NativeDopplerCutCount", NaN, ...
    "NativeRetainedDelaySampleCount", NaN, ...
    "NativeEstimatedLargestBatchBytes", NaN, ...
    "ReducedDopplerCutCount", NaN, ...
    "NativeDopplerSamplesPerCell", NaN, ...
    "NativeMinimumDopplerSamplesPerCell", NaN, ...
    "NativeMaximumDopplerSamplesPerCell", NaN, ...
    "ReducedMinimumDopplerSamplesPerCell", NaN, ...
    "ReducedMaximumDopplerSamplesPerCell", NaN, ...
    "NativeAggregationImplementation", "", ...
    "ReducedAggregationImplementation", "", ...
    "NativeCpiStartTime_s", NaN, ...
    "ReducedCpiStartTime_s", NaN, ...
    "CpiStartTimeOffset_s", NaN, ...
    "CpiStartTimeOffset_reducedSamples", NaN, ...
    "CpiAlignmentWithinHalfReducedSample", false, ...
    "CpiStopBoundaryOffset_s", NaN, ...
    "NativeElapsed_s", NaN, ...
    "ReducedElapsed_s", NaN, ...
    "TotalElapsed_s", NaN, ...
    "NativePeakDelay_s", NaN, ...
    "NativePeakDoppler_Hz", NaN, ...
    "ReducedPeakDelay_s", NaN, ...
    "ReducedPeakDoppler_Hz", NaN, ...
    "DelayPeakDifference_cells", NaN, ...
    "DopplerPeakDifference_cells", NaN, ...
    "PeakAgreement", false, ...
    "NormalizedMapCorrelation", NaN, ...
    "NativeOffOriginEnergyFraction", NaN, ...
    "ReducedOffOriginEnergyFraction", NaN, ...
    "OffOriginEnergyFractionDifference", NaN, ...
    "NativeZeroDopplerEnergyFraction", NaN, ...
    "ReducedZeroDopplerEnergyFraction", NaN, ...
    "ZeroDopplerEnergyFractionDifference", NaN, ...
    "NativeDirectPathToOffRidge_dB", NaN, ...
    "ReducedDirectPathToOffRidge_dB", NaN, ...
    "DirectPathToOffRidgeDifference_dB", NaN, ...
    "NativeDirectPathClassification", "", ...
    "ReducedDirectPathClassification", "", ...
    "DirectPathClassificationUnchanged", false, ...
    "NativeTargetClassification", "", ...
    "ReducedTargetClassification", "", ...
    "TargetClassificationUnchanged", false, ...
    "AllPairCriteriaPass", false);

end

function summaryTable = localBuildFactorSummaryTable( ...
    pairTable, resolvedOptions)

factors = unique(pairTable.DecimationFactor, "stable");
rows = repmat(struct( ...
    "DecimationFactor", NaN, ...
    "PairCount", NaN, ...
    "MedianNormalizedMapCorrelation", NaN, ...
    "MinimumNormalizedMapCorrelation", NaN, ...
    "MaximumOffOriginEnergyFractionDifference", NaN, ...
    "MaximumZeroDopplerEnergyFractionDifference", NaN, ...
    "MaximumDirectPathToOffRidgeDifference_dB", NaN, ...
    "AllPeaksAgree", false, ...
    "AllDirectPathClassificationsUnchanged", false, ...
    "AllTargetClassificationsUnchanged", false, ...
    "AllCriteriaPass", false), numel(factors), 1);

for factorIndex = 1:numel(factors)
    factor = factors(factorIndex);
    subset = pairTable(pairTable.DecimationFactor == factor, :);
    rows(factorIndex).DecimationFactor = factor;
    rows(factorIndex).PairCount = double(height(subset));
    rows(factorIndex).MedianNormalizedMapCorrelation = ...
        median(subset.NormalizedMapCorrelation);
    rows(factorIndex).MinimumNormalizedMapCorrelation = ...
        min(subset.NormalizedMapCorrelation);
    rows(factorIndex).MaximumOffOriginEnergyFractionDifference = ...
        max(subset.OffOriginEnergyFractionDifference);
    rows(factorIndex).MaximumZeroDopplerEnergyFractionDifference = ...
        max(subset.ZeroDopplerEnergyFractionDifference);
    rows(factorIndex).MaximumDirectPathToOffRidgeDifference_dB = ...
        max(subset.DirectPathToOffRidgeDifference_dB);
    rows(factorIndex).AllPeaksAgree = all(subset.PeakAgreement);
    rows(factorIndex).AllDirectPathClassificationsUnchanged = ...
        all(subset.DirectPathClassificationUnchanged);
    rows(factorIndex).AllTargetClassificationsUnchanged = ...
        all(subset.TargetClassificationUnchanged);
    rows(factorIndex).AllCriteriaPass = ...
        rows(factorIndex).MedianNormalizedMapCorrelation >= ...
        resolvedOptions.MinimumMedianNormalizedMapCorrelation && ...
        rows(factorIndex).MinimumNormalizedMapCorrelation >= ...
        resolvedOptions.MinimumPairNormalizedMapCorrelation && ...
        rows(factorIndex).MaximumOffOriginEnergyFractionDifference <= ...
        resolvedOptions.MaximumOffOriginEnergyFractionDifference && ...
        rows(factorIndex).MaximumZeroDopplerEnergyFractionDifference <= ...
        resolvedOptions.MaximumZeroDopplerEnergyFractionDifference && ...
        rows(factorIndex).MaximumDirectPathToOffRidgeDifference_dB <= ...
        resolvedOptions.MaximumDirectPathToOffRidgeDifference_dB && ...
        rows(factorIndex).AllPeaksAgree && ...
        rows(factorIndex).AllDirectPathClassificationsUnchanged && ...
        rows(factorIndex).AllTargetClassificationsUnchanged;
end

summaryTable = struct2table(rows);

end

function comparisons = localSelectRepresentativeComparisons( ...
    mapProducts, pairTable, resolvedOptions)

comparisons = repmat(localMapProductTemplate(), 0, 1);

if ~resolvedOptions.RetainComparisonMaps || isempty(mapProducts) || ...
        resolvedOptions.MaximumRetainedComparisons == 0
    return
end

selectedIndices = 1;

if numel(mapProducts) > 1 && ...
        resolvedOptions.MaximumRetainedComparisons > 1
    [~, bestIndex] = max(pairTable.NormalizedMapCorrelation);

    if bestIndex ~= 1
        selectedIndices(end + 1) = bestIndex;
    end
end

selectedIndices = selectedIndices(1:min(numel(selectedIndices), ...
    resolvedOptions.MaximumRetainedComparisons));
comparisons = vertcat(mapProducts{selectedIndices});

end

function mapProduct = localBuildMapProduct(pairInput, decimationFactor, ...
    delayAxis_s, dopplerAxis_Hz, nativePower, reducedPower, comparison)

mapProduct = localMapProductTemplate();
mapProduct.BackgroundId = localResolveStringMetadata(pairInput, ...
    "BackgroundId", "unspecified");
mapProduct.SceneId = localResolveStringMetadata(pairInput, ...
    "SceneId", "real_only");
mapProduct.ProductName = localResolveStringMetadata(pairInput, ...
    "ProductName", "none");
mapProduct.WindowLabel = localResolveStringMetadata(pairInput, ...
    "WindowLabel", "center");
mapProduct.CpiDuration_s = localResolveNumericMetadata(pairInput, ...
    "CpiDuration_s", NaN);
mapProduct.DecimationFactor = decimationFactor;
mapProduct.DelayAxis_s = delayAxis_s;
mapProduct.DopplerAxis_Hz = dopplerAxis_Hz;
mapProduct.NativeNormalizedPower = ...
    comparison.NativeNormalized;
mapProduct.ReducedNormalizedPower = ...
    comparison.ReducedNormalized;
mapProduct.NativePeakPower = max(nativePower, [], "all");
mapProduct.ReducedPeakPower = max(reducedPower, [], "all");

end

function mapProduct = localMapProductTemplate()

mapProduct = struct( ...
    "BackgroundId", "", ...
    "SceneId", "", ...
    "ProductName", "", ...
    "WindowLabel", "", ...
    "CpiDuration_s", NaN, ...
    "DecimationFactor", NaN, ...
    "DelayAxis_s", zeros(1, 0), ...
    "DopplerAxis_Hz", zeros(0, 1), ...
    "NativeNormalizedPower", zeros(0, 0), ...
    "ReducedNormalizedPower", zeros(0, 0), ...
    "NativePeakPower", NaN, ...
    "ReducedPeakPower", NaN);

end

function configuration = localBuildConfiguration(resolvedOptions)

configuration = resolvedOptions;
configuration.NativeMapMethod = ...
    "ambgfun_doppler_cuts_streamed_to_common_physical_cells";
if resolvedOptions.ReducedMapFormation == "production_full_map"
    configuration.ReducedMapMethod = ...
        "resample_then_full_production_ambgfun_then_common_cell_aggregation";
else
    configuration.ReducedMapMethod = ...
        "resample_then_ambgfun_doppler_cuts";
end
configuration.PowerDefinition = ...
    "squared_normalized_ambgfun_magnitude";
configuration.NativeCellAggregation = ...
    "arithmetic_mean_of_native_raw_linear_power_within_each_reduced_cell";
configuration.StreamingAggregationImplementation = ...
    "helperAggregateG4RMapPower";
configuration.DopplerQuadrature = ...
    "equal_weight_midpoint_samples_within_each_common_cell";
configuration.MapNormalization = ...
    "unit_sum_after_common_cell_aggregation";
configuration.MapCorrelation = ...
    "Pearson_linear_correlation_of_unit_sum_common_cell_power";
configuration.AxisOrientation = "rows_doppler_columns_delay";
configuration.CpiAlignmentRule = ...
    "nearest_reduced_sample_round_half_toward_later_sample";
configuration.FullNativeMapMaterialized = false;
configuration.FullReducedMapMaterialized = ...
    resolvedOptions.ReducedMapFormation == "production_full_map";

end

function audit = localBuildCompactResultAudit(analysis)

audit = struct();
audit.RawIqPresent = isfield(analysis, "ReferenceSignal") || ...
    isfield(analysis, "SurveillanceSignal");
audit.FullMapCollectionPresent = false;
audit.RetainedComparisonCount = ...
    double(numel(analysis.RepresentativeComparisons));
audit.MaximumRetainedComparisonCount = ...
    double(analysis.Configuration.MaximumRetainedComparisons);
audit.Compact = ~audit.RawIqPresent && ...
    ~audit.FullMapCollectionPresent && ...
    audit.RetainedComparisonCount <= ...
    audit.MaximumRetainedComparisonCount;

end

function value = localResolveStringMetadata(inputStruct, fieldName, ...
    defaultValue)

value = string(defaultValue);

if isfield(inputStruct, fieldName)
    candidate = string(inputStruct.(fieldName));

    if isscalar(candidate) && strlength(candidate) > 0
        value = candidate;
    end
end

end

function value = localResolveNumericMetadata(inputStruct, fieldName, ...
    defaultValue)

value = double(defaultValue);

if isfield(inputStruct, fieldName)
    candidate = double(inputStruct.(fieldName));

    if isscalar(candidate)
        value = candidate;
    end
end

end

function value = localResolveLogicalMetadata(inputStruct, fieldName, ...
    defaultValue)

value = logical(defaultValue);

if isfield(inputStruct, fieldName)
    candidate = logical(inputStruct.(fieldName));

    if isscalar(candidate)
        value = candidate;
    end
end

end
