function analysis = helperAnalyzeDirectPathQuickView( ...
    baselineDatasetId, candidateDatasetId, repoRoot, options)
%HELPERANALYZEDIRECTPATHQUICKVIEW Compare direct-path capture evidence.
%
%   ANALYSIS = HELPERANALYZEDIRECTPATHQUICKVIEW(BASELINEID, CANDIDATEID,
%   REPOROOT, OPTIONS) reads manifest-listed baseband captures, enforces
%   RF0 as surveillance and RF1 as reference, and returns channel and
%   pairwise measurements. Quick mode uses centered 125 ms windows from
%   the first, middle, and last repetitions. Confirm mode uses the same
%   centered window from every repetition.

arguments
    baselineDatasetId (1,1) string
    candidateDatasetId (1,1) string
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

repoRoot = helperResolveRepoRoot(repoRoot);
resolvedOptions = localResolveOptions(options);
metricDefinitions = localBuildMetricDefinitions();
pairwiseMetricDefinitions = localBuildPairwiseMetricDefinitions();

baseline = localAnalyzeSession(baselineDatasetId, repoRoot, ...
    resolvedOptions, metricDefinitions, pairwiseMetricDefinitions);
candidate = localAnalyzeSession(candidateDatasetId, repoRoot, ...
    resolvedOptions, metricDefinitions, pairwiseMetricDefinitions);
localValidateComparableAcquisition(baseline, candidate);

comparisonTable = localBuildComparisonTable(baseline, candidate, ...
    metricDefinitions);
pairwiseComparisonTable = localBuildPairwiseComparisonTable( ...
    baseline, candidate, pairwiseMetricDefinitions);
evidenceTable = localBuildEvidenceTable(baseline, candidate, ...
    comparisonTable, resolvedOptions);

analysis = struct();
analysis.AnalysisId = "DirectPathQuickView";
analysis.BaselineDatasetId = baseline.DatasetId;
analysis.CandidateDatasetId = candidate.DatasetId;
analysis.Mode = resolvedOptions.Mode;
analysis.WindowDuration_s = baseline.AnalysisWindowDuration_s;
analysis.WindowDescription = baseline.WindowDescription;
analysis.Mapping = struct( ...
    "Reference", resolvedOptions.ReferenceRfChain, ...
    "Surveillance", resolvedOptions.SurveillanceRfChain, ...
    "Source", "fixed analysis contract");
analysis.Options = resolvedOptions;
analysis.MetricDefinitions = struct2table(metricDefinitions);
analysis.PairwiseMetricDefinitions = ...
    struct2table(pairwiseMetricDefinitions);
analysis.Baseline = baseline;
analysis.Candidate = candidate;
analysis.ComparisonTable = comparisonTable;
analysis.PairwiseComparisonTable = pairwiseComparisonTable;
analysis.EvidenceTable = evidenceTable;
analysis.Trend = localBuildTrend(evidenceTable);
analysis.LocalizationSuitability = localBuildLocalizationAssessment( ...
    evidenceTable);

end

function options = localResolveOptions(userOptions)

options = struct();
options.Mode = "quick";
options.WindowDuration_s = 0.125;
options.ReferenceRfChain = "RF1";
options.SurveillanceRfChain = "RF0";
options.ReferenceChannelLabel = "RF1:RX2";
options.SurveillanceChannelLabel = "RF0:RX2";
options.ExpectedPilotOffset_Hz = -2.690559441e6;
options.PilotSearchHalfWidth_Hz = 150.0e3;
options.PilotExclusionHalfWidth_Hz = 50.0e3;
options.AtscBandHalfWidth_Hz = 3.0e6;
options.WelchLength = 8192;
options.WelchOverlap = 4096;
options.WelchNfft = 8192;
options.NearRailThresholdFraction = 0.98;
options.DcSpikeLocalHalfWidth_Hz = 50.0e3;
options.DcSpikeExclusionHalfWidth_Hz = 5.0e3;
options.CorrelationSampleCount = 131072;
options.CorrelationMaxLag_samples = 4096;
options.ControlStabilityThreshold_dB = 2.0;
options.MaterialChangeThreshold_dB = 3.0;
options.PilotFrequencyTolerance_kHz = 20.0;
options.PilotProminenceThreshold_dB = 8.0;
options.NearRailLimit_ppm = 100.0;
options.HeadroomWarningThreshold_dB = 3.0;

optionNames = fieldnames(userOptions);

for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    options.(optionName) = userOptions.(optionName);
end

options.Mode = lower(string(options.Mode));

if ~ismember(options.Mode, ["quick", "confirm"])
    error("helperAnalyzeDirectPathQuickView:InvalidMode", ...
        "Mode must be either ""quick"" or ""confirm"".");
end

if options.WindowDuration_s <= 0
    error("helperAnalyzeDirectPathQuickView:InvalidWindowDuration", ...
        "WindowDuration_s must be positive.");
end

if options.WelchLength < 32 || ...
        options.WelchOverlap < 0 || ...
        options.WelchOverlap >= options.WelchLength
    error("helperAnalyzeDirectPathQuickView:InvalidWelchSettings", ...
        "WelchLength and WelchOverlap do not define a valid PSD setup.");
end

options.WelchNfft = max(options.WelchNfft, options.WelchLength);

end

function definitions = localBuildMetricDefinitions()

definitions = [ ...
    localMetric("atsc_band_power", "ATSC-band power", "dBFS", ...
    "PilotExcludedAtscBandPower_dBFS", "%.2f", true, ""); ...
    localMetric("atsc_pilot_psd", "ATSC pilot PSD", "dBFS/Hz", ...
    "AtscPilotPsd_dBFSHz", "%.2f", true, ""); ...
    localMetric("mean_iq_power", "Mean IQ power", "dBFS", ...
    "MeanIqPower_dBFS", "%.2f", true, ""); ...
    localMetric("data_band_median_psd", "Data-band median PSD", ...
    "dBFS/Hz", "DataBandMedianPsd_dBFSHz", "%.2f", true, ""); ...
    localMetric("pilot_prominence", "Pilot prominence", "dB", ...
    "PilotProminence_dB", "%.2f", true, ""); ...
    localMetric("pilot_frequency_error", "Pilot-frequency error", "kHz", ...
    "PilotFrequencyError_kHz", "%.2f", true, ""); ...
    localMetric("data_band_peak_prominence", ...
    "Data-band peak prominence", "dB", ...
    "DataBandPeakProminence_dB", "%.2f", true, ""); ...
    localMetric("occupied_bandwidth", "Occupied bandwidth", "MHz", ...
    "OccupiedBandwidth_MHz", "%.3f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("peak_to_average_ratio", "Peak-to-average ratio", "dB", ...
    "PeakToAverageRatio_dB", "%.2f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("peak_headroom", "Peak headroom", "dB", ...
    "PeakHeadroom_dB", "%.2f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("near_rail_occupancy", "Near-rail occupancy", "ppm", ...
    "NearRailOccupancy_ppm", "%.1f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("exact_rail_sample_count", "Exact-rail sample count", ...
    "samples", "ExactRailSampleCount", "%.0f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("dc_spike", "DC spike", "dB", "DcSpike_dB", ...
    "%.2f", false, "N/A: evaluate channels separately"); ...
    localMetric("iq_amplitude_imbalance", "IQ amplitude imbalance", "dB", ...
    "IqAmplitudeImbalance_dB", "%.3f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("iq_phase_proxy", "IQ phase proxy", "degrees", ...
    "IqPhaseProxy_deg", "%.3f", false, ...
    "N/A: evaluate channels separately"); ...
    localMetric("iq_impropriety", "IQ impropriety", "unitless", ...
    "IqImpropriety", "%.4f", false, ...
    "N/A: evaluate channels separately") ...
    ];

end

function definition = localMetric(id, displayName, unit, fieldName, ...
    displayFormat, differenceApplicable, differenceNote)

definition = struct( ...
    "MetricId", string(id), ...
    "DisplayName", string(displayName), ...
    "Unit", string(unit), ...
    "FieldName", string(fieldName), ...
    "DisplayFormat", string(displayFormat), ...
    "DifferenceApplicable", logical(differenceApplicable), ...
    "DifferenceNote", string(differenceNote));

end

function definitions = localBuildPairwiseMetricDefinitions()

definitions = [ ...
    localPairwiseMetric("mean_band_coherence", "Mean band coherence", ...
    "unitless", "MeanBandCoherence", "%.3f"); ...
    localPairwiseMetric("peak_normalized_correlation", ...
    "Peak normalized correlation", "unitless", ...
    "PeakNormalizedCorrelation", "%.3f"); ...
    localPairwiseMetric("peak_correlation_lag", ...
    "Peak correlation lag", "samples", ...
    "PeakCorrelationLag_samples", "%.0f") ...
    ];

end

function definition = localPairwiseMetric(id, displayName, unit, ...
    fieldName, displayFormat)

definition = struct( ...
    "MetricId", string(id), ...
    "DisplayName", string(displayName), ...
    "Unit", string(unit), ...
    "FieldName", string(fieldName), ...
    "DisplayFormat", string(displayFormat));

end

function session = localAnalyzeSession(datasetId, repoRoot, options, ...
    metricDefinitions, pairwiseMetricDefinitions)

datasetRoot = fullfile(repoRoot, datasetId);
manifestPath = fullfile(datasetRoot, "session_manifest.json");
manifest = localReadManifest(manifestPath);
localValidateManifest(manifest, datasetId);

radarRelativePaths = string(manifest.radar_files(:));
repetitionIndices = localSelectRepetitions(numel(radarRelativePaths), ...
    options.Mode);
gainVector = localParseGainSpec(manifest.gain_spec);
channelRows = repmat(localEmptyChannelRow(), ...
    numel(repetitionIndices) * 2, 1);
pairwiseRows = repmat(localEmptyPairwiseRow(), ...
    numel(repetitionIndices), 1);
sampleRateHz = double(manifest.sdr_defaults.sample_rate_hz);
centerFrequencyHz = double(manifest.sdr_defaults.center_frequency_hz);

for selectionIndex = 1:numel(repetitionIndices)
    manifestIndex = repetitionIndices(selectionIndex);
    relativePath = radarRelativePaths(manifestIndex);
    capturePath = fullfile(datasetRoot, ...
        strrep(relativePath, "/", filesep));
    scan = helperScanBasebandCaptureFile(capturePath, true);
    [referenceIndex, surveillanceIndex] = localValidateCapture( ...
        scan, manifest, options, capturePath);
    windowIndices = localAnalysisWindowIndices(scan.NumSamples, ...
        sampleRateHz, options);
    referenceSamples = double(scan.Samples(windowIndices, referenceIndex));
    surveillanceSamples = double( ...
        scan.Samples(windowIndices, surveillanceIndex));
    referenceMetrics = localComputeChannelMetrics(referenceSamples, ...
        sampleRateHz, options);
    surveillanceMetrics = localComputeChannelMetrics( ...
        surveillanceSamples, sampleRateHz, options);
    pairwiseMetrics = localComputePairwiseMetrics(referenceSamples, ...
        surveillanceSamples, sampleRateHz, options);

    referenceRowIndex = (selectionIndex - 1) * 2 + 1;
    surveillanceRowIndex = referenceRowIndex + 1;
    channelRows(referenceRowIndex) = localBuildChannelRow(datasetId, ...
        scan.Repetition, manifestIndex, relativePath, "reference", ...
        options.ReferenceChannelLabel, windowIndices, referenceMetrics);
    channelRows(surveillanceRowIndex) = localBuildChannelRow(datasetId, ...
        scan.Repetition, manifestIndex, relativePath, "surveillance", ...
        options.SurveillanceChannelLabel, windowIndices, ...
        surveillanceMetrics);
    pairwiseRows(selectionIndex) = localBuildPairwiseRow(datasetId, ...
        scan.Repetition, manifestIndex, relativePath, windowIndices, ...
        pairwiseMetrics);
end

channelMetricTable = struct2table(channelRows);
pairwiseMetricTable = struct2table(pairwiseRows);
channelSummaryTable = localBuildChannelSummary(channelMetricTable, ...
    metricDefinitions);
pairwiseSummaryTable = localBuildPairwiseSummary(pairwiseMetricTable, ...
    pairwiseMetricDefinitions);

session = struct();
session.DatasetId = string(datasetId);
session.DatasetRoot = string(datasetRoot);
session.ManifestPath = string(manifestPath);
session.ManifestGainSpec = string(manifest.gain_spec);
session.SurveillanceGain_dB = gainVector(1);
session.ReferenceGain_dB = gainVector(2);
session.SampleRate_Hz = sampleRateHz;
session.CenterFrequency_Hz = centerFrequencyHz;
session.AnalysisWindowDuration_s = ...
    (channelMetricTable.WindowEndSample(1) - ...
    channelMetricTable.WindowStartSample(1) + 1) / sampleRateHz;
session.WindowDescription = localWindowDescription(options.Mode);
session.SelectedManifestIndices = repetitionIndices(:).';
session.SelectedRepetitions = unique(channelMetricTable.Repetition, ...
    "stable").';
session.ChannelMetricTable = channelMetricTable;
session.PairwiseMetricTable = pairwiseMetricTable;
session.ChannelSummaryTable = channelSummaryTable;
session.PairwiseSummaryTable = pairwiseSummaryTable;

end

function manifest = localReadManifest(manifestPath)

if ~isfile(manifestPath)
    error("helperAnalyzeDirectPathQuickView:MissingManifest", ...
        "Manifest not found: %s", manifestPath);
end

try
    manifest = jsondecode(fileread(manifestPath));
catch manifestException
    error("helperAnalyzeDirectPathQuickView:ReadManifestFailed", ...
        "Failed to read %s: %s", manifestPath, ...
        manifestException.message);
end

end

function localValidateManifest(manifest, datasetId)

requiredFields = ["session_id", "gain_spec", "radar_files", ...
    "sdr_defaults"];

for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);

    if ~isfield(manifest, fieldName)
        error("helperAnalyzeDirectPathQuickView:IncompleteManifest", ...
            "Manifest for %s is missing %s.", datasetId, fieldName);
    end
end

if string(manifest.session_id) ~= datasetId
    error("helperAnalyzeDirectPathQuickView:SessionIdMismatch", ...
        "Manifest session_id %s does not match requested dataset %s.", ...
        string(manifest.session_id), datasetId);
end

if ~isfield(manifest.sdr_defaults, "sample_rate_hz") || ...
        ~isfield(manifest.sdr_defaults, "center_frequency_hz")
    error("helperAnalyzeDirectPathQuickView:IncompleteManifestSettings", ...
        "Manifest for %s lacks sample-rate or center-frequency settings.", ...
        datasetId);
end

if isempty(manifest.radar_files)
    error("helperAnalyzeDirectPathQuickView:NoRadarFiles", ...
        "Manifest for %s contains no radar files.", datasetId);
end

end

function indices = localSelectRepetitions(repetitionCount, mode)

if mode == "confirm"
    indices = 1:repetitionCount;
    return
end

middleIndex = round((repetitionCount + 1) / 2);
indices = unique([1, middleIndex, repetitionCount], "stable");

end

function gains = localParseGainSpec(gainSpec)

gainTokens = split(strtrim(string(gainSpec)), ",");
gains = str2double(strtrim(gainTokens));

if numel(gains) ~= 2 || any(~isfinite(gains))
    error("helperAnalyzeDirectPathQuickView:InvalidGainSpec", ...
        "Expected manifest gain_spec to contain two numeric values.");
end

gains = double(gains(:).');

end

function [referenceIndex, surveillanceIndex] = localValidateCapture( ...
    scan, manifest, options, capturePath)

channelLabels = [string(scan.Antenna1), string(scan.Antenna2)];
referenceIndex = find(channelLabels == ...
    options.ReferenceChannelLabel, 1, "first");
surveillanceIndex = find(channelLabels == ...
    options.SurveillanceChannelLabel, 1, "first");

if isempty(referenceIndex) || isempty(surveillanceIndex) || ...
        referenceIndex == surveillanceIndex
    error("helperAnalyzeDirectPathQuickView:ChannelMappingMismatch", ...
        "Capture %s must contain exactly the enforced mapping " + ...
        "SURV=%s and REF=%s.", capturePath, ...
        options.SurveillanceChannelLabel, options.ReferenceChannelLabel);
end

manifestSampleRateHz = double(manifest.sdr_defaults.sample_rate_hz);
manifestCenterFrequencyHz = ...
    double(manifest.sdr_defaults.center_frequency_hz);

if scan.SampleRate ~= manifestSampleRateHz || ...
        scan.CenterFrequency ~= manifestCenterFrequencyHz
    error("helperAnalyzeDirectPathQuickView:HeaderManifestMismatch", ...
        "Capture header settings disagree with the manifest for %s.", ...
        capturePath);
end

if scan.DataType ~= "int16"
    error("helperAnalyzeDirectPathQuickView:UnsupportedDataType", ...
        "Direct-path dBFS normalization currently requires int16 IQ.");
end

end

function indices = localAnalysisWindowIndices(numSamples, sampleRateHz, ...
    options)

if options.Mode == "confirm"
    indices = 1:numSamples;
    return
end

windowSampleCount = round(options.WindowDuration_s * sampleRateHz);

if windowSampleCount > numSamples
    error("helperAnalyzeDirectPathQuickView:WindowTooLong", ...
        "The requested analysis window exceeds the capture duration.");
end

startIndex = floor((numSamples - windowSampleCount) / 2) + 1;
indices = startIndex:(startIndex + windowSampleCount - 1);

end

function description = localWindowDescription(mode)

if mode == "confirm"
    description = "full capture";
else
    description = "centered window";
end

end

function metrics = localComputeChannelMetrics(samples, sampleRateHz, ...
    options)

fullScale = double(intmax("int16"));
samples = double(samples(:));
normalizedSamples = samples ./ fullScale;
welchWindow = hann(options.WelchLength, "periodic");
[psdValues, frequencyHz] = pwelch(normalizedSamples, welchWindow, ...
    options.WelchOverlap, options.WelchNfft, sampleRateHz, "centered");
psdValues = max(real(double(psdValues(:))), eps);
frequencyHz = double(frequencyHz(:));

pilotSearchMask = abs(frequencyHz - options.ExpectedPilotOffset_Hz) <= ...
    options.PilotSearchHalfWidth_Hz;

if ~any(pilotSearchMask)
    error("helperAnalyzeDirectPathQuickView:EmptyPilotSearchBand", ...
        "The expected ATSC pilot search band is outside the PSD support.");
end

pilotSearchMetrics = helperComputePilotAwarePsdMetrics( ...
    frequencyHz(pilotSearchMask), psdValues(pilotSearchMask), ...
    options.PilotExclusionHalfWidth_Hz);
pilotFrequencyHz = pilotSearchMetrics.PilotFrequency_Hz;
pilotPsd = db2pow(pilotSearchMetrics.PilotPsd_dB);
bandLowerHz = max(-options.AtscBandHalfWidth_Hz, min(frequencyHz));
bandUpperHz = min(options.AtscBandHalfWidth_Hz, max(frequencyHz));
dataBandMask = frequencyHz >= bandLowerHz;
dataBandMask = dataBandMask & frequencyHz <= bandUpperHz;
dataBandMask = dataBandMask & ...
    abs(frequencyHz - pilotFrequencyHz) > ...
    options.PilotExclusionHalfWidth_Hz;

if ~any(dataBandMask)
    error("helperAnalyzeDirectPathQuickView:EmptyDataBand", ...
        "Pilot exclusion removed the entire ATSC data band.");
end

dataBandPsd = psdValues(dataBandMask);
dataBandMedianPsd = median(dataBandPsd, "omitnan");
dataBandPeakPsd = max(dataBandPsd, [], "omitnan");
fullBandPower = bandpower(psdValues, frequencyHz, ...
    [bandLowerHz, bandUpperHz], "psd");
pilotBandLowerHz = max(bandLowerHz, ...
    pilotFrequencyHz - options.PilotExclusionHalfWidth_Hz);
pilotBandUpperHz = min(bandUpperHz, ...
    pilotFrequencyHz + options.PilotExclusionHalfWidth_Hz);
pilotBandPower = bandpower(psdValues, frequencyHz, ...
    [pilotBandLowerHz, pilotBandUpperHz], "psd");
pilotExcludedBandPower = max(fullBandPower - pilotBandPower, eps);

meanPower = mean(abs(normalizedSamples) .^ 2);
maxMagnitude = max(abs(normalizedSamples));
maxComponentAbs = max([ ...
    max(abs(real(samples))), ...
    max(abs(imag(samples))) ...
    ]);
nearRailMask = abs(real(samples)) >= ...
    options.NearRailThresholdFraction * fullScale;
nearRailMask = nearRailMask | abs(imag(samples)) >= ...
    options.NearRailThresholdFraction * fullScale;
exactRailMask = abs(real(samples)) >= fullScale;
exactRailMask = exactRailMask | abs(imag(samples)) >= fullScale;
realSamples = real(normalizedSamples);
imagSamples = imag(normalizedSamples);
realCentered = realSamples - mean(realSamples);
imagCentered = imagSamples - mean(imagSamples);
realScale = sqrt(mean(realCentered .^ 2));
imagScale = sqrt(mean(imagCentered .^ 2));
iqCorrelation = localNormalizedCorrelation(realCentered, imagCentered);
phaseProxyDegrees = asind(max(min(iqCorrelation, 1.0), -1.0));
iqAmplitudeImbalanceDb = 20.0 * log10( ...
    max(realScale, eps) / max(imagScale, eps));
iqImpropriety = abs(mean(normalizedSamples .^ 2)) / ...
    max(meanPower, eps);
dcSpikeDb = localComputeDcSpike(psdValues, frequencyHz, options);

try
    occupiedBandwidthHz = obw(normalizedSamples, sampleRateHz);
catch bandwidthException
    error("helperAnalyzeDirectPathQuickView:OccupiedBandwidthFailed", ...
        "Occupied-bandwidth calculation failed: %s", ...
        bandwidthException.message);
end

metrics = struct();
metrics.PilotExcludedAtscBandPower_dBFS = ...
    pow2db(pilotExcludedBandPower);
metrics.AtscPilotPsd_dBFSHz = pow2db(max(pilotPsd, eps));
metrics.MeanIqPower_dBFS = pow2db(max(meanPower, eps));
metrics.DataBandMedianPsd_dBFSHz = ...
    pow2db(max(dataBandMedianPsd, eps));
metrics.PilotProminence_dB = pow2db( ...
    max(pilotPsd, eps) / max(dataBandMedianPsd, eps));
metrics.PilotFrequencyError_kHz = ...
    (pilotFrequencyHz - options.ExpectedPilotOffset_Hz) / 1.0e3;
metrics.DataBandPeakProminence_dB = pow2db( ...
    max(dataBandPeakPsd, eps) / max(dataBandMedianPsd, eps));
metrics.OccupiedBandwidth_MHz = occupiedBandwidthHz / 1.0e6;
metrics.PeakToAverageRatio_dB = pow2db( ...
    (maxMagnitude ^ 2) / max(meanPower, eps));
metrics.PeakHeadroom_dB = 20.0 * log10( ...
    fullScale / max(maxComponentAbs, eps));
metrics.NearRailOccupancy_ppm = mean(nearRailMask) * 1.0e6;
metrics.ExactRailSampleCount = double(nnz(exactRailMask));
metrics.DcSpike_dB = dcSpikeDb;
metrics.IqAmplitudeImbalance_dB = iqAmplitudeImbalanceDb;
metrics.IqPhaseProxy_deg = phaseProxyDegrees;
metrics.IqImpropriety = iqImpropriety;

end

function value = localComputeDcSpike(psdValues, frequencyHz, options)

[~, dcIndex] = min(abs(frequencyHz));
localMask = abs(frequencyHz) <= ...
    options.DcSpikeLocalHalfWidth_Hz;
localMask = localMask & abs(frequencyHz) >= ...
    options.DcSpikeExclusionHalfWidth_Hz;

if ~any(localMask)
    value = NaN;
    return
end

localMedian = median(psdValues(localMask), "omitnan");
value = pow2db(psdValues(dcIndex) / max(localMedian, eps));

end

function value = localNormalizedCorrelation(firstValues, secondValues)

denominator = sqrt(sum(abs(firstValues) .^ 2) * ...
    sum(abs(secondValues) .^ 2));

if denominator <= eps
    value = 0.0;
    return
end

value = real(sum(firstValues .* conj(secondValues)) / denominator);

end

function metrics = localComputePairwiseMetrics(referenceSamples, ...
    surveillanceSamples, sampleRateHz, options)

fullScale = double(intmax("int16"));
referenceSamples = double(referenceSamples(:)) ./ fullScale;
surveillanceSamples = double(surveillanceSamples(:)) ./ fullScale;
welchWindow = hann(options.WelchLength, "periodic");
[coherenceValues, coherenceFrequencyHz] = mscohere(referenceSamples, ...
    surveillanceSamples, welchWindow, options.WelchOverlap, ...
    options.WelchNfft, sampleRateHz, "centered");
bandMask = abs(coherenceFrequencyHz) <= options.AtscBandHalfWidth_Hz;
meanBandCoherence = mean(coherenceValues(bandMask), "omitnan");

correlationSampleCount = min(numel(referenceSamples), ...
    options.CorrelationSampleCount);
correlationStart = floor((numel(referenceSamples) - ...
    correlationSampleCount) / 2) + 1;
correlationIndices = correlationStart:( ...
    correlationStart + correlationSampleCount - 1);
[correlationValues, correlationLags] = xcorr( ...
    referenceSamples(correlationIndices), ...
    surveillanceSamples(correlationIndices), ...
    options.CorrelationMaxLag_samples, "normalized");
[peakCorrelation, peakIndex] = max(abs(correlationValues));

metrics = struct();
metrics.MeanBandCoherence = double(meanBandCoherence);
metrics.PeakNormalizedCorrelation = double(peakCorrelation);
metrics.PeakCorrelationLag_samples = ...
    double(correlationLags(peakIndex));

end

function row = localEmptyChannelRow()

row = struct( ...
    "DatasetId", "", ...
    "Repetition", NaN, ...
    "ManifestIndex", NaN, ...
    "RelativePath", "", ...
    "Role", "", ...
    "ChannelLabel", "", ...
    "WindowStartSample", NaN, ...
    "WindowEndSample", NaN, ...
    "PilotExcludedAtscBandPower_dBFS", NaN, ...
    "AtscPilotPsd_dBFSHz", NaN, ...
    "MeanIqPower_dBFS", NaN, ...
    "DataBandMedianPsd_dBFSHz", NaN, ...
    "PilotProminence_dB", NaN, ...
    "PilotFrequencyError_kHz", NaN, ...
    "DataBandPeakProminence_dB", NaN, ...
    "OccupiedBandwidth_MHz", NaN, ...
    "PeakToAverageRatio_dB", NaN, ...
    "PeakHeadroom_dB", NaN, ...
    "NearRailOccupancy_ppm", NaN, ...
    "ExactRailSampleCount", NaN, ...
    "DcSpike_dB", NaN, ...
    "IqAmplitudeImbalance_dB", NaN, ...
    "IqPhaseProxy_deg", NaN, ...
    "IqImpropriety", NaN);

end

function row = localBuildChannelRow(datasetId, repetition, manifestIndex, ...
    relativePath, role, channelLabel, windowIndices, metrics)

row = localEmptyChannelRow();
row.DatasetId = string(datasetId);
row.Repetition = double(repetition);
row.ManifestIndex = double(manifestIndex);
row.RelativePath = string(relativePath);
row.Role = string(role);
row.ChannelLabel = string(channelLabel);
row.WindowStartSample = double(windowIndices(1));
row.WindowEndSample = double(windowIndices(end));
metricNames = fieldnames(metrics);

for metricIndex = 1:numel(metricNames)
    metricName = metricNames{metricIndex};
    row.(metricName) = metrics.(metricName);
end

end

function row = localEmptyPairwiseRow()

row = struct( ...
    "DatasetId", "", ...
    "Repetition", NaN, ...
    "ManifestIndex", NaN, ...
    "RelativePath", "", ...
    "WindowStartSample", NaN, ...
    "WindowEndSample", NaN, ...
    "MeanBandCoherence", NaN, ...
    "PeakNormalizedCorrelation", NaN, ...
    "PeakCorrelationLag_samples", NaN);

end

function row = localBuildPairwiseRow(datasetId, repetition, ...
    manifestIndex, relativePath, windowIndices, metrics)

row = localEmptyPairwiseRow();
row.DatasetId = string(datasetId);
row.Repetition = double(repetition);
row.ManifestIndex = double(manifestIndex);
row.RelativePath = string(relativePath);
row.WindowStartSample = double(windowIndices(1));
row.WindowEndSample = double(windowIndices(end));
row.MeanBandCoherence = metrics.MeanBandCoherence;
row.PeakNormalizedCorrelation = metrics.PeakNormalizedCorrelation;
row.PeakCorrelationLag_samples = metrics.PeakCorrelationLag_samples;

end

function summaryTable = localBuildChannelSummary(channelMetricTable, ...
    metricDefinitions)

rowTemplate = struct( ...
    "MetricId", "", ...
    "DisplayName", "", ...
    "Unit", "", ...
    "FieldName", "", ...
    "DisplayFormat", "", ...
    "DifferenceApplicable", false, ...
    "DifferenceNote", "", ...
    "ReferenceMedian", NaN, ...
    "ReferenceIQR", NaN, ...
    "ReferenceMin", NaN, ...
    "ReferenceMax", NaN, ...
    "SurveillanceMedian", NaN, ...
    "SurveillanceIQR", NaN, ...
    "SurveillanceMin", NaN, ...
    "SurveillanceMax", NaN, ...
    "ReferenceMinusSurveillanceMedian", NaN, ...
    "ReferenceMinusSurveillanceIQR", NaN, ...
    "ReferenceMinusSurveillanceMin", NaN, ...
    "ReferenceMinusSurveillanceMax", NaN);
rows = repmat(rowTemplate, numel(metricDefinitions), 1);
referenceRows = channelMetricTable( ...
    channelMetricTable.Role == "reference", :);
surveillanceRows = channelMetricTable( ...
    channelMetricTable.Role == "surveillance", :);

for metricIndex = 1:numel(metricDefinitions)
    definition = metricDefinitions(metricIndex);
    fieldName = char(definition.FieldName);
    referenceValues = referenceRows.(fieldName);
    surveillanceValues = surveillanceRows.(fieldName);
    referenceStats = localComputeStats(referenceValues);
    surveillanceStats = localComputeStats(surveillanceValues);
    differenceStats = localEmptyStats();

    if definition.DifferenceApplicable
        differenceValues = referenceValues - surveillanceValues;
        differenceStats = localComputeStats(differenceValues);
    end

    rows(metricIndex) = struct( ...
        "MetricId", definition.MetricId, ...
        "DisplayName", definition.DisplayName, ...
        "Unit", definition.Unit, ...
        "FieldName", definition.FieldName, ...
        "DisplayFormat", definition.DisplayFormat, ...
        "DifferenceApplicable", definition.DifferenceApplicable, ...
        "DifferenceNote", definition.DifferenceNote, ...
        "ReferenceMedian", referenceStats.Median, ...
        "ReferenceIQR", referenceStats.IQR, ...
        "ReferenceMin", referenceStats.Min, ...
        "ReferenceMax", referenceStats.Max, ...
        "SurveillanceMedian", surveillanceStats.Median, ...
        "SurveillanceIQR", surveillanceStats.IQR, ...
        "SurveillanceMin", surveillanceStats.Min, ...
        "SurveillanceMax", surveillanceStats.Max, ...
        "ReferenceMinusSurveillanceMedian", ...
        differenceStats.Median, ...
        "ReferenceMinusSurveillanceIQR", differenceStats.IQR, ...
        "ReferenceMinusSurveillanceMin", differenceStats.Min, ...
        "ReferenceMinusSurveillanceMax", differenceStats.Max);
end

summaryTable = struct2table(rows);

end

function stats = localComputeStats(values)

values = double(values(:));
values = values(isfinite(values));

if isempty(values)
    stats = localEmptyStats();
    return
end

quartiles = prctile(values, [25, 75]);
stats = struct();
stats.Median = median(values);
stats.IQR = quartiles(2) - quartiles(1);
stats.Min = min(values);
stats.Max = max(values);

end

function stats = localEmptyStats()

stats = struct("Median", NaN, "IQR", NaN, "Min", NaN, "Max", NaN);

end

function summaryTable = localBuildPairwiseSummary(pairwiseMetricTable, ...
    definitions)

rowTemplate = struct( ...
    "MetricId", "", ...
    "DisplayName", "", ...
    "Unit", "", ...
    "FieldName", "", ...
    "DisplayFormat", "", ...
    "Median", NaN, ...
    "IQR", NaN, ...
    "Min", NaN, ...
    "Max", NaN);
rows = repmat(rowTemplate, numel(definitions), 1);

for metricIndex = 1:numel(definitions)
    definition = definitions(metricIndex);
    stats = localComputeStats( ...
        pairwiseMetricTable.(char(definition.FieldName)));
    rows(metricIndex) = struct( ...
        "MetricId", definition.MetricId, ...
        "DisplayName", definition.DisplayName, ...
        "Unit", definition.Unit, ...
        "FieldName", definition.FieldName, ...
        "DisplayFormat", definition.DisplayFormat, ...
        "Median", stats.Median, ...
        "IQR", stats.IQR, ...
        "Min", stats.Min, ...
        "Max", stats.Max);
end

summaryTable = struct2table(rows);

end

function localValidateComparableAcquisition(baseline, candidate)

if baseline.SampleRate_Hz ~= candidate.SampleRate_Hz
    error("helperAnalyzeDirectPathQuickView:SampleRateMismatch", ...
        "Baseline and candidate manifest sample rates differ.");
end

if baseline.CenterFrequency_Hz ~= candidate.CenterFrequency_Hz
    error("helperAnalyzeDirectPathQuickView:CenterFrequencyMismatch", ...
        "Baseline and candidate manifest center frequencies differ.");
end

end

function comparisonTable = localBuildComparisonTable(baseline, candidate, ...
    definitions)

rowTemplate = struct( ...
    "MetricId", "", ...
    "DisplayName", "", ...
    "Unit", "", ...
    "FieldName", "", ...
    "DisplayFormat", "", ...
    "DifferenceApplicable", false, ...
    "DifferenceNote", "", ...
    "BaselineReference", NaN, ...
    "BaselineSurveillance", NaN, ...
    "BaselineReferenceMinusSurveillance", NaN, ...
    "CandidateReference", NaN, ...
    "CandidateSurveillance", NaN, ...
    "CandidateReferenceMinusSurveillance", NaN, ...
    "DeltaReference", NaN, ...
    "DeltaSurveillance", NaN, ...
    "DeltaReferenceMinusSurveillance", NaN);
rows = repmat(rowTemplate, numel(definitions), 1);

for metricIndex = 1:numel(definitions)
    definition = definitions(metricIndex);
    baselineRow = baseline.ChannelSummaryTable(metricIndex, :);
    candidateRow = candidate.ChannelSummaryTable(metricIndex, :);
    baselineDifference = NaN;
    candidateDifference = NaN;
    differenceOfDifferences = NaN;

    if definition.DifferenceApplicable
        baselineDifference = ...
            baselineRow.ReferenceMinusSurveillanceMedian;
        candidateDifference = ...
            candidateRow.ReferenceMinusSurveillanceMedian;
        differenceOfDifferences = candidateDifference - ...
            baselineDifference;
    end

    rows(metricIndex) = struct( ...
        "MetricId", definition.MetricId, ...
        "DisplayName", definition.DisplayName, ...
        "Unit", definition.Unit, ...
        "FieldName", definition.FieldName, ...
        "DisplayFormat", definition.DisplayFormat, ...
        "DifferenceApplicable", definition.DifferenceApplicable, ...
        "DifferenceNote", definition.DifferenceNote, ...
        "BaselineReference", baselineRow.ReferenceMedian, ...
        "BaselineSurveillance", baselineRow.SurveillanceMedian, ...
        "BaselineReferenceMinusSurveillance", baselineDifference, ...
        "CandidateReference", candidateRow.ReferenceMedian, ...
        "CandidateSurveillance", candidateRow.SurveillanceMedian, ...
        "CandidateReferenceMinusSurveillance", candidateDifference, ...
        "DeltaReference", candidateRow.ReferenceMedian - ...
        baselineRow.ReferenceMedian, ...
        "DeltaSurveillance", candidateRow.SurveillanceMedian - ...
        baselineRow.SurveillanceMedian, ...
        "DeltaReferenceMinusSurveillance", differenceOfDifferences);
end

comparisonTable = struct2table(rows);

end

function tableOut = localBuildPairwiseComparisonTable(baseline, ...
    candidate, definitions)

rowTemplate = struct( ...
    "MetricId", "", ...
    "DisplayName", "", ...
    "Unit", "", ...
    "DisplayFormat", "", ...
    "Baseline", NaN, ...
    "Candidate", NaN, ...
    "Change", NaN);
rows = repmat(rowTemplate, numel(definitions), 1);

for metricIndex = 1:numel(definitions)
    definition = definitions(metricIndex);
    baselineValue = baseline.PairwiseSummaryTable.Median(metricIndex);
    candidateValue = candidate.PairwiseSummaryTable.Median(metricIndex);
    rows(metricIndex) = struct( ...
        "MetricId", definition.MetricId, ...
        "DisplayName", definition.DisplayName, ...
        "Unit", definition.Unit, ...
        "DisplayFormat", definition.DisplayFormat, ...
        "Baseline", baselineValue, ...
        "Candidate", candidateValue, ...
        "Change", candidateValue - baselineValue);
end

tableOut = struct2table(rows);

end

function tableOut = localBuildEvidenceTable(baseline, candidate, ...
    comparisonTable, options)

gainComparable = ...
    baseline.SurveillanceGain_dB == candidate.SurveillanceGain_dB;
gainComparable = gainComparable && ...
    baseline.ReferenceGain_dB == candidate.ReferenceGain_dB;
gainResult = localChoose(gainComparable, "Met", "Not met");
gainExplanation = localChoose(gainComparable, ...
    "Both manifest gain vectors match exactly.", ...
    "Manifest gain vectors differ; amplitude changes are not controlled.");

meanPowerRow = localFindMetric(comparisonTable, "mean_iq_power");
pilotPsdRow = localFindMetric(comparisonTable, "atsc_pilot_psd");
bandPowerRow = localFindMetric(comparisonTable, "atsc_band_power");
controlDeltas = [ ...
    meanPowerRow.DeltaSurveillance, ...
    pilotPsdRow.DeltaSurveillance ...
    ];
controlStable = all(abs(controlDeltas) <= ...
    options.ControlStabilityThreshold_dB);
controlResult = localChoose(controlStable, "Met", "Not met");
controlExplanation = localChoose(controlStable, ...
    "Both RF0 amplitude deltas remain within the control tolerance.", ...
    "At least one RF0 amplitude delta exceeds the control tolerance.");

referenceDeltas = [ ...
    meanPowerRow.DeltaReference, ...
    pilotPsdRow.DeltaReference, ...
    bandPowerRow.DeltaReference ...
    ];
referenceResult = localClassifyThreeMetricChange(referenceDeltas, ...
    options.MaterialChangeThreshold_dB);
referenceExplanation = localDescribeThreeMetricChange(referenceResult, ...
    "RF1");
relativeDeltas = [ ...
    meanPowerRow.DeltaReferenceMinusSurveillance, ...
    pilotPsdRow.DeltaReferenceMinusSurveillance, ...
    bandPowerRow.DeltaReferenceMinusSurveillance ...
    ];
relativeResult = localClassifyThreeMetricChange(relativeDeltas, ...
    options.MaterialChangeThreshold_dB);
relativeExplanation = localDescribeThreeMetricChange(relativeResult, ...
    "control-corrected REF-SURV");

pilotErrorRow = localFindMetric(comparisonTable, ...
    "pilot_frequency_error");
pilotIdentityMet = ...
    abs(pilotErrorRow.CandidateReference) <= ...
    options.PilotFrequencyTolerance_kHz;
pilotIdentityMet = pilotIdentityMet && ...
    abs(pilotErrorRow.CandidateSurveillance) <= ...
    options.PilotFrequencyTolerance_kHz;
pilotIdentityResult = localChoose(pilotIdentityMet, "Met", "Not met");
pilotIdentityExplanation = localChoose(pilotIdentityMet, ...
    "Both candidate channels place the pilot within tolerance.", ...
    "At least one candidate channel places the pilot outside tolerance.");

pilotProminenceRow = localFindMetric(comparisonTable, ...
    "pilot_prominence");
pilotProminenceMet = ...
    pilotProminenceRow.CandidateReference >= ...
    options.PilotProminenceThreshold_dB;
pilotProminenceMet = pilotProminenceMet && ...
    pilotProminenceRow.CandidateSurveillance >= ...
    options.PilotProminenceThreshold_dB;
pilotProminenceResult = localChoose(pilotProminenceMet, "Met", ...
    "Not met");
pilotProminenceExplanation = localChoose(pilotProminenceMet, ...
    "Both candidate channels exceed the pilot-prominence threshold.", ...
    "At least one candidate channel is below the pilot-prominence threshold.");

candidateRows = candidate.ChannelMetricTable;
candidateReferenceRows = candidateRows( ...
    candidateRows.Role == "reference", :);
candidateSurveillanceRows = candidateRows( ...
    candidateRows.Role == "surveillance", :);
worstExactRailCount = max(candidateRows.ExactRailSampleCount);
worstNearRailPpm = max(candidateRows.NearRailOccupancy_ppm);
clippingMet = worstExactRailCount == 0;
clippingMet = clippingMet && ...
    worstNearRailPpm < options.NearRailLimit_ppm;
clippingResult = localChoose(clippingMet, "Met", "Clipping detected");
clippingExplanation = localChoose(clippingMet, ...
    "No exact rails and near-rail occupancy stays below the limit.", ...
    "Exact rails or excessive near-rail occupancy occur in the candidate.");

referenceHeadroom = min(candidateReferenceRows.PeakHeadroom_dB);
surveillanceHeadroom = min(candidateSurveillanceRows.PeakHeadroom_dB);
headroomResult = localHeadroomResult(referenceHeadroom, ...
    surveillanceHeadroom, options.HeadroomWarningThreshold_dB);
headroomExplanation = localHeadroomExplanation(headroomResult);

trend = localClassifyTrend(gainComparable, ...
    bandPowerRow.DeltaReference, ...
    bandPowerRow.DeltaReferenceMinusSurveillance, ...
    options.MaterialChangeThreshold_dB);
trendExplanation = localTrendExplanation(trend, ...
    bandPowerRow.DeltaReference, bandPowerRow.DeltaSurveillance, ...
    bandPowerRow.DeltaReferenceMinusSurveillance);

rows = [ ...
    localEvidenceRow("Gain comparability", ...
    sprintf("BASE=%.15g,%.15g; CAND=%.15g,%.15g", ...
    baseline.SurveillanceGain_dB, baseline.ReferenceGain_dB, ...
    candidate.SurveillanceGain_dB, candidate.ReferenceGain_dB), ...
    "manifest dB gain settings", ...
    "candidate manifest versus baseline manifest", ...
    "Exact manifest match", "existing G2", gainResult, ...
    gainExplanation); ...
    localEvidenceRow("RF0 control stability", ...
    sprintf("Delta power=%+.2f; Delta pilot=%+.2f", controlDeltas), ...
    "dB", "candidate SURV minus baseline SURV", ...
    sprintf("|each| <= %.1f dB", ...
    options.ControlStabilityThreshold_dB), ...
    "field-screen heuristic", controlResult, controlExplanation); ...
    localEvidenceRow("RF1 amplitude change", ...
    sprintf("power=%+.2f; pilot=%+.2f; band=%+.2f", ...
    referenceDeltas), "dB", ...
    "candidate REF minus baseline REF", ...
    sprintf("Improvement >= +%.1f dB; degradation <= -%.1f dB", ...
    options.MaterialChangeThreshold_dB, ...
    options.MaterialChangeThreshold_dB), ...
    "field-screen heuristic", referenceResult, referenceExplanation); ...
    localEvidenceRow("Relative advantage", ...
    sprintf("Delta R-S=%+.2f,%+.2f,%+.2f", relativeDeltas), ...
    "dB", "candidate paired REF-SURV minus baseline paired REF-SURV", ...
    sprintf("Improvement >= +%.1f dB; degradation <= -%.1f dB", ...
    options.MaterialChangeThreshold_dB, ...
    options.MaterialChangeThreshold_dB), ...
    "field-screen heuristic", relativeResult, relativeExplanation); ...
    localEvidenceRow("Pilot identity", ...
    sprintf("error REF=%+.2f; SURV=%+.2f", ...
    pilotErrorRow.CandidateReference, ...
    pilotErrorRow.CandidateSurveillance), ...
    "kHz", "absolute candidate error from expected ATSC pilot", ...
    sprintf("Each <= %.1f kHz", ...
    options.PilotFrequencyTolerance_kHz), ...
    "existing G2", pilotIdentityResult, pilotIdentityExplanation); ...
    localEvidenceRow("Pilot prominence", ...
    sprintf("REF=%.2f; SURV=%.2f", ...
    pilotProminenceRow.CandidateReference, ...
    pilotProminenceRow.CandidateSurveillance), ...
    "dB", "candidate pilot PSD above pilot-excluded data median", ...
    sprintf("Each >= %.1f dB", ...
    options.PilotProminenceThreshold_dB), ...
    "existing G2", pilotProminenceResult, ...
    pilotProminenceExplanation); ...
    localEvidenceRow("Clipping", ...
    sprintf("worst exact rails=%.0f; worst near rails=%.1f", ...
    worstExactRailCount, worstNearRailPpm), ...
    "samples; ppm", "worst selected candidate repetition and channel", ...
    sprintf("0 samples and < %.1f ppm", options.NearRailLimit_ppm), ...
    "existing G2", clippingResult, clippingExplanation); ...
    localEvidenceRow("Headroom", ...
    sprintf("minimum REF=%.2f; SURV=%.2f", ...
    referenceHeadroom, surveillanceHeadroom), ...
    "dB", "minimum selected candidate repetition per channel", ...
    sprintf("Warning below %.1f dB", ...
    options.HeadroomWarningThreshold_dB), ...
    "field-screen heuristic", headroomResult, headroomExplanation); ...
    localEvidenceRow("Observed reference-path trend", ...
    sprintf("RF1 band Delta=%+.2f; RF0 band Delta=%+.2f; " + ...
    "Delta(R-S)=%+.2f", ...
    bandPowerRow.DeltaReference, bandPowerRow.DeltaSurveillance, ...
    bandPowerRow.DeltaReferenceMinusSurveillance), ...
    "dB", "candidate minus baseline; positive favors candidate REF", ...
    sprintf("Improved >= +%.1f dB; worse <= -%.1f dB for both RF1 " + ...
    "and control-corrected band changes", ...
    options.MaterialChangeThreshold_dB, ...
    options.MaterialChangeThreshold_dB), ...
    "field-screen heuristic", trend, trendExplanation); ...
    localEvidenceRow("Localization suitability", ...
    "No G3 synchronization or G4 localization evidence analyzed", ...
    "not applicable", "outside this direct-path measurement scope", ...
    "Requires G3/G4 evidence", "informational", "NOT ASSESSED", ...
    "Direct-path RF measurements cannot establish localization suitability") ...
    ];

tableOut = struct2table(rows);

end

function row = localFindMetric(comparisonTable, metricId)

row = comparisonTable(comparisonTable.MetricId == metricId, :);

if height(row) ~= 1
    error("helperAnalyzeDirectPathQuickView:MissingMetric", ...
        "Expected exactly one comparison row for %s.", metricId);
end

end

function value = localChoose(condition, trueValue, falseValue)

if condition
    value = string(trueValue);
else
    value = string(falseValue);
end

end

function result = localClassifyThreeMetricChange(values, threshold)

if all(values >= threshold)
    result = "Better";
elseif all(values <= -threshold)
    result = "Worse";
else
    result = "Mixed / below threshold";
end

end

function explanation = localDescribeThreeMetricChange(result, subject)

switch result
    case "Better"
        explanation = subject + ...
            " improved by at least the material-change threshold in all " + ...
            "three amplitude measurements.";
    case "Worse"
        explanation = subject + ...
            " degraded by at least the material-change threshold in all " + ...
            "three amplitude measurements.";
    otherwise
        explanation = subject + ...
            " changes are mixed or below the material-change threshold.";
end

end

function result = localHeadroomResult(referenceHeadroom, ...
    surveillanceHeadroom, threshold)

referenceWarning = referenceHeadroom < threshold;
surveillanceWarning = surveillanceHeadroom < threshold;

if referenceWarning && surveillanceWarning
    result = "REF and SURV warning";
elseif referenceWarning
    result = "REF warning";
elseif surveillanceWarning
    result = "SURV warning";
else
    result = "Met";
end

end

function explanation = localHeadroomExplanation(result)

if result == "Met"
    explanation = ...
        "Both candidate channels retain the requested peak headroom.";
else
    explanation = ...
        "The named candidate channel falls below the headroom warning level.";
end

end

function result = localClassifyTrend(gainComparable, ...
    referenceBandDelta, relativeBandDelta, threshold)

if ~gainComparable
    result = "NOT ASSESSED";
elseif referenceBandDelta >= threshold && ...
        relativeBandDelta >= threshold
    result = "IMPROVED";
elseif referenceBandDelta <= -threshold && ...
        relativeBandDelta <= -threshold
    result = "WORSE";
elseif abs(referenceBandDelta) < threshold && ...
        abs(relativeBandDelta) < threshold
    result = "NO MATERIAL CHANGE";
else
    result = "MIXED";
end

end

function explanation = localTrendExplanation(result, referenceBandDelta, ...
    surveillanceBandDelta, relativeBandDelta)

if result == "NOT ASSESSED"
    explanation = ...
        "Manifest gain comparability is not established.";
    return
end

explanation = sprintf( ...
    "RF1 ATSC-band power changed %+.2f dB while RF0 changed " + ...
    "%+.2f dB; the control-corrected REF-SURV advantage changed " + ...
    "%+.2f dB.", ...
    referenceBandDelta, surveillanceBandDelta, relativeBandDelta);

end

function row = localEvidenceRow(checkName, observedValues, units, ...
    comparisonDirection, criterion, source, result, explanation)

row = struct( ...
    "Check", string(checkName), ...
    "ObservedValues", string(observedValues), ...
    "Units", string(units), ...
    "ComparisonDirection", string(comparisonDirection), ...
    "Criterion", string(criterion), ...
    "Source", string(source), ...
    "Result", string(result), ...
    "Explanation", string(explanation));

end

function trend = localBuildTrend(evidenceTable)

row = evidenceTable(evidenceTable.Check == ...
    "Observed reference-path trend", :);
trend = struct( ...
    "Label", row.Result, ...
    "ObservedValues", row.ObservedValues, ...
    "Units", row.Units, ...
    "ComparisonDirection", row.ComparisonDirection, ...
    "Criterion", row.Criterion, ...
    "Source", row.Source, ...
    "Explanation", row.Explanation);

end

function assessment = localBuildLocalizationAssessment(evidenceTable)

row = evidenceTable(evidenceTable.Check == ...
    "Localization suitability", :);
assessment = struct( ...
    "Label", row.Result, ...
    "ObservedValues", row.ObservedValues, ...
    "Units", row.Units, ...
    "ComparisonDirection", row.ComparisonDirection, ...
    "Criterion", row.Criterion, ...
    "Source", row.Source, ...
    "Explanation", row.Explanation);

end
