function layout = helperBuildG2CustomerFlowPptLayout(spec, projectRoot, pptPath)
%HELPERBUILDG2CUSTOMERFLOWPPTLAYOUT Build the customer-facing G2 slide layout.

arguments
    spec (1, 1) struct
    projectRoot (1, :) char
    pptPath (1, :) char
end

relativeMarkdownPath = strrep(char(spec.MarkdownPath), ...
    [projectRoot filesep], "");
relativeArtifactDir = strrep(fileparts(pptPath), [projectRoot filesep], "");

colors = localBuildColorPalette();
slideWidth = 960;
slideHeight = 540;

slide1Texts = localBuildSlide1Texts(spec, colors, relativeMarkdownPath, ...
    relativeArtifactDir);
[slide1Boxes, slide1Headers] = localBuildSlide1Boxes(spec, colors);
slide1Lines = localBuildSlide1Lines(slide1Boxes, colors);

slide2Texts = localBuildSlide2Texts(spec, colors, relativeMarkdownPath, ...
    relativeArtifactDir);
slide2Boxes = localBuildSlide2Boxes(spec, colors);
slide2Lines = localBuildSlide2Lines(slide2Boxes, colors);

layout = struct();
layout.SlideWidth = slideWidth;
layout.SlideHeight = slideHeight;
layout.ExportSlideIndex = 1;
layout.Slides = [ ...
    struct( ...
        "Title", "G2 Customer Flow", ...
        "Boxes", [slide1Headers slide1Boxes], ...
        "Texts", slide1Texts, ...
        "Lines", slide1Lines ...
    ) ...
    struct( ...
        "Title", "G2 Requirement Coverage", ...
        "Boxes", slide2Boxes, ...
        "Texts", slide2Texts, ...
        "Lines", slide2Lines ...
    ) ...
    ];
end

function colors = localBuildColorPalette()

colors = struct();
colors.Text = "#0F172A";
colors.SubtleText = "#475569";
colors.NoteFill = "#FFFBF2";
colors.NoteLine = "#D6C5A3";
colors.FooterFill = "#F8FAFC";
colors.FooterLine = "#CBD5E1";
colors.Line = "#64748B";
colors.HeaderText = "#F8FAFC";
colors.DecisionText = "#F8FAFC";
colors.DecisionFill = "#111827";
colors.DecisionLine = "#F59E0B";
colors.StageHeader = [ ...
    "#0F766E"; ...
    "#B45309"; ...
    "#1D4ED8"; ...
    "#9D174D"; ...
    "#111827" ...
    ];
colors.StageFill = [ ...
    "#F0FDFA"; ...
    "#FFF7ED"; ...
    "#EFF6FF"; ...
    "#FDF2F8"; ...
    "#1F2937" ...
    ];
colors.StageLine = [ ...
    "#0F766E"; ...
    "#B45309"; ...
    "#1D4ED8"; ...
    "#9D174D"; ...
    "#F59E0B" ...
    ];
end

function texts = localBuildSlide1Texts(spec, colors, relativeMarkdownPath, ...
    relativeArtifactDir)

overviewText = strjoin(spec.Overview, newline);
codePathText = strjoin([ ...
    "Planned code path"; ...
    "- loadIQData freezes the G1 input contract."; ...
    "- runG2RFHealth will orchestrate native MATLAB checks."; ...
    "- summary.md, metrics.json, metrics.mat, and figures carry the evidence." ...
    ], newline);
valueText = strjoin([ ...
    "Why this matters"; ...
    "- Tells us whether the hardware setup was proven."; ...
    "- Tells us whether the RF scene is usable for passive processing."; ...
    "- Tells us whether aircraft-related analysis is technically justified." ...
    ], newline);

texts = [ ...
    localMakeText( ...
        spec.Title, 24, 16, 912, 24, 24, true, false, "left", ...
        colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "Customer-facing WHY / HOW / decision view for the planned G2 RF-health gate", ...
        24, 44, 912, 16, 11, false, false, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        overviewText, 24, 68, 912, 32, 10, false, false, "left", ...
        colors.Text, colors.NoteFill, colors.NoteLine ...
    ) ...
    localMakeText( ...
        codePathText, 24, 404, 434, 90, 10, false, false, "left", ...
        colors.Text, colors.FooterFill, colors.FooterLine ...
    ) ...
    localMakeText( ...
        valueText, 502, 404, 434, 90, 10, false, false, "left", ...
        colors.Text, colors.FooterFill, colors.FooterLine ...
    ) ...
    localMakeText( ...
        sprintf("Source markdown: %s", relativeMarkdownPath), ...
        24, 502, 430, 14, 9, false, true, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        sprintf("Communication assets: %s", relativeArtifactDir), ...
        452, 502, 484, 14, 9, false, true, "right", ...
        colors.SubtleText, "", "" ...
    ) ...
    ];
end

function [boxes, headers] = localBuildSlide1Boxes(spec, colors)

stageCount = 5;
cardWidth = 176;
cardHeight = 246;
headerHeight = 24;
startX = 20;
startY = 130;
gap = 10;

boxes = repmat(localBoxTemplate(), 1, stageCount);
headers = repmat(localBoxTemplate(), 1, stageCount);

for stageIndex = 1:stageCount
    currentStage = spec.Stages(stageIndex);
    currentX = startX + (stageIndex - 1) * (cardWidth + gap);
    isDecisionStage = stageIndex == stageCount;

    if isDecisionStage
        bodyFill = colors.DecisionFill;
        bodyLine = colors.DecisionLine;
        bodyFont = colors.DecisionText;
    else
        bodyFill = colors.StageFill(stageIndex);
        bodyLine = colors.StageLine(stageIndex);
        bodyFont = colors.Text;
    end

    headers(stageIndex) = localMakeBox( ...
        "HEADER_" + string(stageIndex), currentStage.Title, currentX, 104, ...
        cardWidth, headerHeight, colors.StageHeader(stageIndex), ...
        colors.StageLine(stageIndex), 11, true, colors.HeaderText, 1, ...
        "center", 3);
    boxes(stageIndex) = localMakeBox( ...
        "BODY_" + string(stageIndex), localFormatStageBody(currentStage), ...
        currentX, startY, cardWidth, cardHeight, bodyFill, bodyLine, 8.5, ...
        false, bodyFont, 1, "left", 1);
end
end

function lines = localBuildSlide1Lines(boxes, colors)

lineCount = numel(boxes) - 1;
lines = repmat(localLineTemplate(), 1, lineCount);

for lineIndex = 1:lineCount
    sourceBox = boxes(lineIndex);
    targetBox = boxes(lineIndex + 1);

    lines(lineIndex) = localMakeLine( ...
        sourceBox.X + sourceBox.Width, ...
        sourceBox.Y + sourceBox.Height / 2, ...
        targetBox.X, ...
        targetBox.Y + targetBox.Height / 2, ...
        colors.Line, ...
        1.75, ...
        true, ...
        "", ...
        0, ...
        0, ...
        0, ...
        0, ...
        0, ...
        "center" ...
    );
end
end

function texts = localBuildSlide2Texts(~, colors, relativeMarkdownPath, ...
    relativeArtifactDir)

bottomNote = strjoin([ ...
    "Decision-policy note"; ...
    "- This customer asset communicates approved question coverage and branch logic."; ...
    "- Numeric cut points will be frozen later in code and evidence, not invented here." ...
    ], newline);

texts = [ ...
    localMakeText( ...
        "G2 Question Coverage by Requirement Family", ...
        24, 16, 912, 24, 24, true, false, "left", ...
        colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "Actual planned questions, MATLAB methods, and expected gate effects grouped by RFH family", ...
        24, 44, 912, 16, 11, false, false, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        bottomNote, 24, 470, 912, 42, 10, false, false, "left", ...
        colors.Text, colors.FooterFill, colors.FooterLine ...
    ) ...
    localMakeText( ...
        sprintf("Source markdown: %s", relativeMarkdownPath), ...
        24, 518, 430, 14, 9, false, true, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        sprintf("Communication assets: %s", relativeArtifactDir), ...
        452, 518, 484, 14, 9, false, true, "right", ...
        colors.SubtleText, "", "" ...
    ) ...
    ];
end

function boxes = localBuildSlide2Boxes(spec, colors)

columnWidth = 286;
columnHeight = 334;
headerHeight = 24;
startX = 24;
startY = 106;
gap = 27;

columns = localBuildRequirementColumns(spec);
boxes = repmat(localBoxTemplate(), 1, 6);

for columnIndex = 1:3
    currentX = startX + (columnIndex - 1) * (columnWidth + gap);
    headerFill = colors.StageHeader(columnIndex);
    headerLine = colors.StageLine(columnIndex);
    bodyFill = colors.StageFill(columnIndex);
    bodyLine = colors.StageLine(columnIndex);

    boxes(2 * columnIndex - 1) = localMakeBox( ...
        "REQ_HEADER_" + string(columnIndex), columns(columnIndex).Title, ...
        currentX, startY, columnWidth, headerHeight, headerFill, headerLine, ...
        11, true, colors.HeaderText, 1, "center", 3);
    boxes(2 * columnIndex) = localMakeBox( ...
        "REQ_BODY_" + string(columnIndex), columns(columnIndex).BodyText, ...
        currentX, startY + 28, columnWidth, columnHeight, bodyFill, ...
        bodyLine, 9, false, colors.Text, 1, "left", 1);
end
end

function lines = localBuildSlide2Lines(~, ~)

lines = repmat(localLineTemplate(), 0, 1);
end

function columns = localBuildRequirementColumns(spec)

stage1 = spec.Stages(1);
stage2 = spec.Stages(2);
stage3 = spec.Stages(3);
stage4 = spec.Stages(4);
stage5 = spec.Stages(5);

columns = repmat(struct("Title", "", "BodyText", ""), 3, 1);
columns(1).Title = "RFH-001 | Setup and Receiver Integrity";
columns(1).BodyText = localFormatRequirementBody([ ...
    "Key questions"; ...
    localSegmentLines(stage1.Questions); ...
    localSegmentLines(stage2.Questions); ...
    ""; ...
    "Planned MATLAB methods"; ...
    localSegmentLines(stage1.MATLABPath); ...
    localSegmentLines(stage2.MATLABPath); ...
    ""; ...
    "Expected gate effect"; ...
    localSegmentLines(stage1.ExpectedCriteria); ...
    localSegmentLines(stage2.ExpectedCriteria) ...
    ]);

columns(2).Title = "RFH-002 | Spectral and Coherent Usability";
columns(2).BodyText = localFormatRequirementBody([ ...
    "Key questions"; ...
    localSegmentLines(stage3.Questions); ...
    localSegmentLines(stage4.Questions); ...
    ""; ...
    "Planned MATLAB methods"; ...
    localSegmentLines(stage3.MATLABPath); ...
    localSegmentLines(stage4.MATLABPath); ...
    ""; ...
    "Expected gate effect"; ...
    localSegmentLines(stage3.ExpectedCriteria); ...
    localSegmentLines(stage4.ExpectedCriteria) ...
    ]);

columns(3).Title = "RFH-003 | Session Decision and Message";
columns(3).BodyText = localFormatRequirementBody([ ...
    "Key questions"; ...
    localSegmentLines(stage5.Questions); ...
    ""; ...
    "Planned MATLAB methods"; ...
    localSegmentLines(stage5.MATLABPath); ...
    ""; ...
    "Expected gate effect"; ...
    localSegmentLines(stage5.ExpectedCriteria); ...
    ""; ...
    "Carry-forward outputs"; ...
    localSegmentLines(spec.Outputs(1)); ...
    localSegmentLines(spec.Outputs(2)); ...
    localSegmentLines(spec.Outputs(3)); ...
    localSegmentLines(spec.Outputs(4)) ...
    ]);
end

function bodyText = localFormatStageBody(stage)

bodyLines = [ ...
    "Customer questions"; ...
    localSegmentLines(stage.Questions, 2); ...
    ""; ...
    "Planned MATLAB code"; ...
    localSegmentLines(stage.MATLABPath, 2); ...
    ""; ...
    "Expected decision"; ...
    localSegmentLines(stage.ExpectedCriteria, 2) ...
    ];
bodyText = strjoin(bodyLines, newline);
end

function bodyText = localFormatRequirementBody(lines)

bodyText = strjoin(lines, newline);
end

function lines = localSegmentLines(value, maxSegments)

if nargin < 2
    maxSegments = inf;
end

segments = split(string(value), ";");
segments = strtrim(segments);
segments = segments(strlength(segments) > 0);

if isfinite(maxSegments)
    segments = segments(1:min(numel(segments), maxSegments));
end

lines = "- " + segments;
end

function textSpec = localMakeText(textValue, xValue, yValue, widthValue, ...
    heightValue, fontSizeValue, boldValue, italicValue, alignValue, ...
    fontColorValue, fillColorValue, lineColorValue)

textSpec = struct( ...
    "Text", char(string(textValue)), ...
    "X", xValue, ...
    "Y", yValue, ...
    "Width", widthValue, ...
    "Height", heightValue, ...
    "FontSize", fontSizeValue, ...
    "Bold", boldValue, ...
    "Italic", italicValue, ...
    "Align", alignValue, ...
    "FontColor", fontColorValue, ...
    "FillColor", fillColorValue, ...
    "LineColor", lineColorValue ...
    );
end

function boxSpec = localMakeBox(idValue, textValue, xValue, yValue, ...
    widthValue, heightValue, fillColorValue, lineColorValue, ...
    fontSizeValue, boldValue, fontColorValue, shapeTypeValue, alignValue, ...
    verticalAnchorValue)

boxSpec = struct( ...
    "Id", char(string(idValue)), ...
    "Text", char(string(textValue)), ...
    "X", xValue, ...
    "Y", yValue, ...
    "Width", widthValue, ...
    "Height", heightValue, ...
    "FillColor", fillColorValue, ...
    "LineColor", lineColorValue, ...
    "FontSize", fontSizeValue, ...
    "Bold", boldValue, ...
    "FontColor", fontColorValue, ...
    "ShapeType", shapeTypeValue, ...
    "Align", alignValue, ...
    "VerticalAnchor", verticalAnchorValue ...
    );
end

function lineSpec = localMakeLine(x1Value, y1Value, x2Value, y2Value, ...
    colorValue, weightValue, arrowValue, labelValue, labelXValue, ...
    labelYValue, labelWidthValue, labelHeightValue, labelFontSizeValue, ...
    labelAlignValue)

lineSpec = struct( ...
    "X1", x1Value, ...
    "Y1", y1Value, ...
    "X2", x2Value, ...
    "Y2", y2Value, ...
    "Color", colorValue, ...
    "Weight", weightValue, ...
    "Arrow", arrowValue, ...
    "Label", char(string(labelValue)), ...
    "LabelX", labelXValue, ...
    "LabelY", labelYValue, ...
    "LabelWidth", labelWidthValue, ...
    "LabelHeight", labelHeightValue, ...
    "LabelFontSize", labelFontSizeValue, ...
    "LabelAlign", labelAlignValue ...
    );
end

function template = localBoxTemplate()

template = struct( ...
    "Id", "", ...
    "Text", "", ...
    "X", 0, ...
    "Y", 0, ...
    "Width", 0, ...
    "Height", 0, ...
    "FillColor", "", ...
    "LineColor", "", ...
    "FontSize", 0, ...
    "Bold", false, ...
    "FontColor", "", ...
    "ShapeType", 1, ...
    "Align", "center", ...
    "VerticalAnchor", 3 ...
    );
end

function template = localLineTemplate()

template = struct( ...
    "X1", 0, ...
    "Y1", 0, ...
    "X2", 0, ...
    "Y2", 0, ...
    "Color", "", ...
    "Weight", 0, ...
    "Arrow", false, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
    );
end
