function analysis = helperAnalyzeG2ReceiverIntegrity(sessionData, ...
    collectionMetadataInfo, options)
%HELPERANALYZEG2RECEIVERINTEGRITY Analyze Stage 2 receiver-integrity metrics.

arguments
    sessionData (1,1) struct
    collectionMetadataInfo (1,1) struct
    options (1,1) struct = struct()
end

resolvedOptions = localResolveOptions(sessionData, options);
roleInfo = localResolveRoleInfo(sessionData, collectionMetadataInfo, ...
    resolvedOptions);
[receiverIntegrityTable, channelSummaryTable, roleEvidence] = ...
    localBuildReceiverIntegrityTables(sessionData, roleInfo, ...
    resolvedOptions);
[receiverIntegrityVerdict, legalGateRecommendation, ...
    datasetClassificationRecommendation, classificationImpact, ...
    decisionTraceTable] = localDetermineStage2Verdicts( ...
    receiverIntegrityTable, channelSummaryTable, roleInfo, ...
    resolvedOptions);
[analysisValidity, developmentReadiness, developmentBlockingReason, ...
    analysisInterpretation, developmentInterpretation] = ...
    localDetermineDevelopmentStatus(receiverIntegrityTable, ...
    channelSummaryTable, roleInfo, receiverIntegrityVerdict, ...
    resolvedOptions);

analysis = struct();
analysis.StageId = "Stage2_ReceiverIntegrity";
analysis.DatasetId = string(sessionData.DatasetId);
analysis.RoleInfo = roleInfo;
analysis.ReceiverIntegrityTable = receiverIntegrityTable;
analysis.ChannelSummaryTable = channelSummaryTable;
analysis.ReceiverIntegrityVerdict = receiverIntegrityVerdict;
analysis.LegalGateRecommendation = legalGateRecommendation;
analysis.DatasetClassificationRecommendation = ...
    datasetClassificationRecommendation;
analysis.ClassificationImpact = classificationImpact;
analysis.AnalysisValidity = analysisValidity;
analysis.DevelopmentReadiness = developmentReadiness;
analysis.DevelopmentBlockingReason = developmentBlockingReason;
analysis.AnalysisInterpretation = analysisInterpretation;
analysis.DevelopmentInterpretation = developmentInterpretation;
analysis.DecisionTraceTable = decisionTraceTable;
analysis.RoleEvidence = roleEvidence;
analysis.CollectionMetadataInfo = collectionMetadataInfo;
analysis.Options = rmfield(resolvedOptions, "WelchWindow");
analysis.Metrics = localBuildMetrics(receiverIntegrityTable, ...
    channelSummaryTable, roleInfo, roleEvidence, ...
    receiverIntegrityVerdict, legalGateRecommendation, ...
    datasetClassificationRecommendation, classificationImpact, ...
    analysisValidity, developmentReadiness, ...
    developmentBlockingReason, analysisInterpretation, ...
    developmentInterpretation);

end

function resolvedOptions = localResolveOptions(sessionData, options)

sampleRateVector = unique(sessionData.RadarTable.SampleRate_Hz);

resolvedOptions = struct();
resolvedOptions.SampleRateHz = sampleRateVector(1);
resolvedOptions.WelchLength = 4096;
resolvedOptions.WelchOverlap = 2048;
resolvedOptions.WelchNfft = 4096;
resolvedOptions.NearRailThresholdFraction = 0.98;
resolvedOptions.SevereClippingFractionThreshold = 1.0e-4;
resolvedOptions.ClippingRiskFractionThreshold = 0.0;
resolvedOptions.ReferencePowerMinimumThreshold_dB = 0.0;
resolvedOptions.ReferencePowerTargetMarginThreshold_dB = 3.0;
resolvedOptions.QuantizationRiskThreshold_dBFS = -35.0;
resolvedOptions.SevereQuantizationThreshold_dBFS = -45.0;
resolvedOptions.DcMeanRatioDiagnosticThreshold_dB = -60.0;
resolvedOptions.DcMeanRatioSevereThreshold_dB = -40.0;
resolvedOptions.DcSpikeDiagnosticThreshold_dB = 3.0;
resolvedOptions.DcSpikeSevereThreshold_dB = 10.0;
resolvedOptions.DcBandHalfWidthHz = 3000.0;
resolvedOptions.DcSpikeLocalHalfWidthHz = 50000.0;
resolvedOptions.DcSpikeExclusionHalfWidthHz = 5000.0;
resolvedOptions.IqAmplitudeImbalanceDiagnosticThreshold_dB = 1.0;
resolvedOptions.IqAmplitudeImbalanceSevereThreshold_dB = 3.0;
resolvedOptions.IqPhaseProxyDiagnosticThreshold_deg = 3.0;
resolvedOptions.IqPhaseProxySevereThreshold_deg = 10.0;
resolvedOptions.IqImproprietyDiagnosticThreshold = 0.05;
resolvedOptions.IqImproprietySevereThreshold = 0.15;
resolvedOptions.WelchWindow = hann(resolvedOptions.WelchLength, ...
    "periodic");

optionFields = fieldnames(options);

for idx = 1:numel(optionFields)
    fieldName = optionFields{idx};
    resolvedOptions.(fieldName) = options.(fieldName);
end

resolvedOptions.WelchOverlap = min(resolvedOptions.WelchOverlap, ...
    resolvedOptions.WelchLength - 1);
resolvedOptions.WelchWindow = hann(resolvedOptions.WelchLength, ...
    "periodic");

end

function roleInfo = localResolveRoleInfo(sessionData, ...
    collectionMetadataInfo, resolvedOptions)

roleInfo = helperResolveChannelRoles(sessionData, collectionMetadataInfo, ...
    resolvedOptions);

end

function [receiverIntegrityTable, channelSummaryTable, roleEvidence] = ...
    localBuildReceiverIntegrityTables(sessionData, roleInfo, ...
    resolvedOptions)

radarTable = sessionData.RadarTable;
repetitionCount = height(radarTable);
referencePsdAccumulator = [];
surveillancePsdAccumulator = [];
psdFrequencyHz = [];

rowTemplate = struct( ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "ReferenceChannelLabel", "", ...
    "SurveillanceChannelLabel", "", ...
    "ReferenceMeanPower_dBFS", NaN, ...
    "SurveillanceMeanPower_dBFS", NaN, ...
    "ReferenceMinusSurveillancePower_dB", NaN, ...
    "ReferencePAR_dB", NaN, ...
    "SurveillancePAR_dB", NaN, ...
    "ReferencePeakHeadroom_dB", NaN, ...
    "SurveillancePeakHeadroom_dB", NaN, ...
    "ReferenceNearRailFraction", NaN, ...
    "SurveillanceNearRailFraction", NaN, ...
    "ReferenceExactRailFraction", NaN, ...
    "SurveillanceExactRailFraction", NaN, ...
    "ReferenceDcMeanRatio_dB", NaN, ...
    "SurveillanceDcMeanRatio_dB", NaN, ...
    "ReferenceDcSpike_dB", NaN, ...
    "SurveillanceDcSpike_dB", NaN, ...
    "ReferenceLowFrequencyBandFraction_dB", NaN, ...
    "SurveillanceLowFrequencyBandFraction_dB", NaN, ...
    "ReferenceIqAmplitudeImbalance_dB", NaN, ...
    "SurveillanceIqAmplitudeImbalance_dB", NaN, ...
    "ReferenceIqPhaseProxy_deg", NaN, ...
    "SurveillanceIqPhaseProxy_deg", NaN, ...
    "ReferenceIqImpropriety", NaN, ...
    "SurveillanceIqImpropriety", NaN, ...
    "ReferenceIqCompensationCoeffMagnitude", NaN, ...
    "SurveillanceIqCompensationCoeffMagnitude", NaN, ...
    "ReferencePowerFlag", "", ...
    "RepetitionVerdict", "", ...
    "CaveatNotes", "" ...
    );
rows = repmat(rowTemplate, repetitionCount, 1);

for idx = 1:repetitionCount
    samples = helperResolveRadarSamples(sessionData, idx);
    referenceSamples = double(samples(:, roleInfo.ReferenceColumnIndex));
    surveillanceSamples = double(samples(:, ...
        roleInfo.SurveillanceColumnIndex));

    [referenceMetrics, referencePsd, psdFrequencyHz] = ...
        localComputeChannelMetrics(referenceSamples, resolvedOptions);
    [surveillanceMetrics, surveillancePsd, ~] = ...
        localComputeChannelMetrics(surveillanceSamples, resolvedOptions);

    if isempty(referencePsdAccumulator)
        referencePsdAccumulator = zeros(size(referencePsd));
        surveillancePsdAccumulator = zeros(size(surveillancePsd));
    end

    referencePsdAccumulator = referencePsdAccumulator + referencePsd;
    surveillancePsdAccumulator = surveillancePsdAccumulator + ...
        surveillancePsd;

    referenceMinusSurveillancePowerDb = ...
        referenceMetrics.MeanPower_dBFS - surveillanceMetrics.MeanPower_dBFS;
    [powerFlag, repetitionVerdict, caveatNotes] = ...
        localClassifyRepetition(referenceMinusSurveillancePowerDb, ...
        referenceMetrics, surveillanceMetrics, resolvedOptions);

    rows(idx) = struct( ...
        "Repetition", radarTable.Repetition(idx), ...
        "RelativePath", radarTable.RelativePath(idx), ...
        "ReferenceChannelLabel", roleInfo.ReferenceLabel, ...
        "SurveillanceChannelLabel", roleInfo.SurveillanceLabel, ...
        "ReferenceMeanPower_dBFS", referenceMetrics.MeanPower_dBFS, ...
        "SurveillanceMeanPower_dBFS", ...
        surveillanceMetrics.MeanPower_dBFS, ...
        "ReferenceMinusSurveillancePower_dB", ...
        referenceMinusSurveillancePowerDb, ...
        "ReferencePAR_dB", referenceMetrics.PAR_dB, ...
        "SurveillancePAR_dB", surveillanceMetrics.PAR_dB, ...
        "ReferencePeakHeadroom_dB", ...
        referenceMetrics.PeakHeadroom_dB, ...
        "SurveillancePeakHeadroom_dB", ...
        surveillanceMetrics.PeakHeadroom_dB, ...
        "ReferenceNearRailFraction", ...
        referenceMetrics.NearRailFraction, ...
        "SurveillanceNearRailFraction", ...
        surveillanceMetrics.NearRailFraction, ...
        "ReferenceExactRailFraction", ...
        referenceMetrics.ExactRailFraction, ...
        "SurveillanceExactRailFraction", ...
        surveillanceMetrics.ExactRailFraction, ...
        "ReferenceDcMeanRatio_dB", referenceMetrics.DcMeanRatio_dB, ...
        "SurveillanceDcMeanRatio_dB", ...
        surveillanceMetrics.DcMeanRatio_dB, ...
        "ReferenceDcSpike_dB", referenceMetrics.DcSpike_dB, ...
        "SurveillanceDcSpike_dB", surveillanceMetrics.DcSpike_dB, ...
        "ReferenceLowFrequencyBandFraction_dB", ...
        referenceMetrics.LowFrequencyBandFraction_dB, ...
        "SurveillanceLowFrequencyBandFraction_dB", ...
        surveillanceMetrics.LowFrequencyBandFraction_dB, ...
        "ReferenceIqAmplitudeImbalance_dB", ...
        referenceMetrics.IqAmplitudeImbalance_dB, ...
        "SurveillanceIqAmplitudeImbalance_dB", ...
        surveillanceMetrics.IqAmplitudeImbalance_dB, ...
        "ReferenceIqPhaseProxy_deg", ...
        referenceMetrics.IqPhaseProxy_deg, ...
        "SurveillanceIqPhaseProxy_deg", ...
        surveillanceMetrics.IqPhaseProxy_deg, ...
        "ReferenceIqImpropriety", referenceMetrics.IqImpropriety, ...
        "SurveillanceIqImpropriety", ...
        surveillanceMetrics.IqImpropriety, ...
        "ReferenceIqCompensationCoeffMagnitude", ...
        referenceMetrics.IqCompensationCoeffMagnitude, ...
        "SurveillanceIqCompensationCoeffMagnitude", ...
        surveillanceMetrics.IqCompensationCoeffMagnitude, ...
        "ReferencePowerFlag", powerFlag, ...
        "RepetitionVerdict", repetitionVerdict, ...
        "CaveatNotes", caveatNotes ...
        );
end

receiverIntegrityTable = struct2table(rows);
channelSummaryTable = localBuildChannelSummaryTable( ...
    receiverIntegrityTable, roleInfo);
roleEvidence = struct();
roleEvidence.PsdFrequencyHz = psdFrequencyHz;
roleEvidence.ReferenceMeanPsd = referencePsdAccumulator ./ repetitionCount;
roleEvidence.SurveillanceMeanPsd = surveillancePsdAccumulator ./ ...
    repetitionCount;
roleEvidence.ReferencePowerMinimumFraction = mean( ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB >= ...
    resolvedOptions.ReferencePowerMinimumThreshold_dB);
roleEvidence.ReferencePowerTargetFraction = mean( ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB >= ...
    resolvedOptions.ReferencePowerTargetMarginThreshold_dB);
roleEvidence.ReferenceMinusSurveillancePower_dB_Min = min( ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB);
roleEvidence.ReferenceMinusSurveillancePower_dB_Median = median( ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB);
roleEvidence.ReferenceMinusSurveillancePower_dB_Max = max( ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB);

end

function [channelMetrics, pxx, frequencyHz] = localComputeChannelMetrics( ...
    samples, resolvedOptions)

fullScale = double(intmax("int16"));
meanPower = mean(abs(samples).^2);
maxMagnitude = max(abs(samples));
maxComponentAbs = max([max(abs(real(samples))), max(abs(imag(samples)))]);
realRailMask = abs(real(samples)) >= fullScale;
imagRailMask = abs(imag(samples)) >= fullScale;
nearRailMask = abs(real(samples)) >= ...
    resolvedOptions.NearRailThresholdFraction * fullScale | ...
    abs(imag(samples)) >= ...
    resolvedOptions.NearRailThresholdFraction * fullScale;
channelMean = mean(samples);

[pxx, frequencyHz] = pwelch(samples, resolvedOptions.WelchWindow, ...
    resolvedOptions.WelchOverlap, resolvedOptions.WelchNfft, ...
    resolvedOptions.SampleRateHz, "centered");

dcBandPower = bandpower(pxx, frequencyHz, ...
    [-resolvedOptions.DcBandHalfWidthHz, ...
    resolvedOptions.DcBandHalfWidthHz], "psd");
dcSpikeDb = localComputeDcSpikeDb(pxx, frequencyHz, resolvedOptions);

realSamples = real(samples);
imagSamples = imag(samples);
realCentered = realSamples - mean(realSamples);
imagCentered = imagSamples - mean(imagSamples);
realScale = sqrt(mean(realCentered.^2));
imagScale = sqrt(mean(imagCentered.^2));
iqCorrelation = localComputeNormalizedCorrelation(realCentered, ...
    imagCentered);
phaseProxyDeg = asind(max(min(iqCorrelation, 1.0), -1.0));
iqAmplitudeImbalanceDb = 20.0 * log10( ...
    max(realScale, eps) / max(imagScale, eps));
iqImpropriety = abs(mean(samples.^2)) / max(meanPower, eps);
iqCompensationCoeff = iqimbal2coef(iqAmplitudeImbalanceDb, ...
    phaseProxyDeg);

channelMetrics = struct();
channelMetrics.MeanPower_dBFS = pow2db(meanPower / (fullScale ^ 2) + eps);
channelMetrics.PAR_dB = pow2db((maxMagnitude ^ 2) / max(meanPower, eps));
channelMetrics.PeakHeadroom_dB = 20.0 * log10( ...
    fullScale / max(maxComponentAbs, eps));
channelMetrics.NearRailFraction = mean(nearRailMask);
channelMetrics.ExactRailFraction = mean(realRailMask | imagRailMask);
channelMetrics.DcMeanRatio_dB = pow2db( ...
    (abs(channelMean) ^ 2) / max(meanPower, eps) + eps);
channelMetrics.DcSpike_dB = dcSpikeDb;
channelMetrics.LowFrequencyBandFraction_dB = pow2db( ...
    dcBandPower / max(meanPower, eps) + eps);
channelMetrics.IqAmplitudeImbalance_dB = iqAmplitudeImbalanceDb;
channelMetrics.IqPhaseProxy_deg = phaseProxyDeg;
channelMetrics.IqImpropriety = iqImpropriety;
channelMetrics.IqCompensationCoeffMagnitude = abs(iqCompensationCoeff);

end

function dcSpikeDb = localComputeDcSpikeDb(pxx, frequencyHz, resolvedOptions)

dcIndex = find(abs(frequencyHz) == min(abs(frequencyHz)), 1, "first");
localMask = abs(frequencyHz) <= ...
    resolvedOptions.DcSpikeLocalHalfWidthHz & ...
    abs(frequencyHz) >= resolvedOptions.DcSpikeExclusionHalfWidthHz;

if ~any(localMask)
    dcSpikeDb = NaN;
    return
end

localMedian = median(pxx(localMask));
dcSpikeDb = pow2db(pxx(dcIndex) / max(localMedian, eps));

end

function correlationValue = localComputeNormalizedCorrelation(x, y)

denominator = sqrt(sum(x .^ 2) * sum(y .^ 2));

if denominator <= eps
    correlationValue = 0.0;
    return
end

correlationValue = sum(x .* y) / denominator;
correlationValue = real(correlationValue);

end

function [powerFlag, repetitionVerdict, caveatNotes] = ...
    localClassifyRepetition(referenceMinusSurveillancePowerDb, ...
    referenceMetrics, surveillanceMetrics, resolvedOptions)

caveatTokens = strings(0, 1);

if referenceMinusSurveillancePowerDb < ...
        resolvedOptions.ReferencePowerMinimumThreshold_dB
    powerFlag = "reference_weaker_than_surveillance";
    caveatTokens(end + 1, 1) = powerFlag;
elseif referenceMinusSurveillancePowerDb < ...
        resolvedOptions.ReferencePowerTargetMarginThreshold_dB
    powerFlag = "reference_margin_below_target";
    caveatTokens(end + 1, 1) = powerFlag;
else
    powerFlag = "reference_margin_ok";
end

severeClipping = localHasSevereClipping(referenceMetrics, ...
    surveillanceMetrics, resolvedOptions);
clippingRisk = localHasClippingRisk(referenceMetrics, ...
    surveillanceMetrics, resolvedOptions);
quantizationRisk = localHasQuantizationRisk(referenceMetrics, ...
    surveillanceMetrics, resolvedOptions);
dcIssue = localHasDcIssue(referenceMetrics, surveillanceMetrics, ...
    resolvedOptions);
iqIssue = localHasIqIssue(referenceMetrics, surveillanceMetrics, ...
    resolvedOptions);

if clippingRisk
    caveatTokens(end + 1, 1) = "near_rail_occupancy_observed";
end

if quantizationRisk
    caveatTokens(end + 1, 1) = "low_rms_scale_usage_detected";
end

if dcIssue
    caveatTokens(end + 1, 1) = "dc_or_lo_contamination_risk";
end

if iqIssue
    caveatTokens(end + 1, 1) = "iq_image_risk";
end

if severeClipping
    repetitionVerdict = "reject_candidate";
elseif powerFlag ~= "reference_margin_ok" || clippingRisk || ...
        quantizationRisk || dcIssue || iqIssue
    repetitionVerdict = "retune_candidate";
else
    repetitionVerdict = "acceptable";
end

caveatNotes = localJoinNotes(caveatTokens);

end

function value = localHasSevereClipping(referenceMetrics, ...
    surveillanceMetrics, resolvedOptions)

value = referenceMetrics.NearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold || ...
    surveillanceMetrics.NearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold || ...
    referenceMetrics.ExactRailFraction > 0.0 || ...
    surveillanceMetrics.ExactRailFraction > 0.0;

end

function value = localHasClippingRisk(referenceMetrics, surveillanceMetrics, ...
    resolvedOptions)

value = referenceMetrics.NearRailFraction > ...
    resolvedOptions.ClippingRiskFractionThreshold || ...
    surveillanceMetrics.NearRailFraction > ...
    resolvedOptions.ClippingRiskFractionThreshold;

end

function value = localHasQuantizationRisk(referenceMetrics, ...
    surveillanceMetrics, resolvedOptions)

value = referenceMetrics.MeanPower_dBFS <= ...
    resolvedOptions.QuantizationRiskThreshold_dBFS || ...
    surveillanceMetrics.MeanPower_dBFS <= ...
    resolvedOptions.QuantizationRiskThreshold_dBFS;

end

function value = localHasDcIssue(referenceMetrics, surveillanceMetrics, ...
    resolvedOptions)

value = referenceMetrics.DcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioDiagnosticThreshold_dB || ...
    surveillanceMetrics.DcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioDiagnosticThreshold_dB || ...
    referenceMetrics.DcSpike_dB >= ...
    resolvedOptions.DcSpikeDiagnosticThreshold_dB || ...
    surveillanceMetrics.DcSpike_dB >= ...
    resolvedOptions.DcSpikeDiagnosticThreshold_dB;

end

function value = localHasIqIssue(referenceMetrics, surveillanceMetrics, ...
    resolvedOptions)

value = abs(referenceMetrics.IqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceDiagnosticThreshold_dB || ...
    abs(surveillanceMetrics.IqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceDiagnosticThreshold_dB || ...
    abs(referenceMetrics.IqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxyDiagnosticThreshold_deg || ...
    abs(surveillanceMetrics.IqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxyDiagnosticThreshold_deg || ...
    referenceMetrics.IqImpropriety >= ...
    resolvedOptions.IqImproprietyDiagnosticThreshold || ...
    surveillanceMetrics.IqImpropriety >= ...
    resolvedOptions.IqImproprietyDiagnosticThreshold;

end

function channelSummaryTable = localBuildChannelSummaryTable( ...
    receiverIntegrityTable, roleInfo)

summaryRows = struct( ...
    "ChannelRole", {}, ...
    "ChannelLabel", {}, ...
    "MedianMeanPower_dBFS", {}, ...
    "MinPeakHeadroom_dB", {}, ...
    "MedianPAR_dB", {}, ...
    "MaxNearRailFraction", {}, ...
    "MaxDcMeanRatio_dB", {}, ...
    "MaxDcSpike_dB", {}, ...
    "MedianLowFrequencyBandFraction_dB", {}, ...
    "MedianIqAmplitudeImbalance_dB", {}, ...
    "MedianIqPhaseProxy_deg", {}, ...
    "MaxIqImpropriety", {} ...
    );

summaryRows(end + 1) = struct( ... %#ok<AGROW>
    "ChannelRole", "reference", ...
    "ChannelLabel", roleInfo.ReferenceLabel, ...
    "MedianMeanPower_dBFS", median( ...
    receiverIntegrityTable.ReferenceMeanPower_dBFS), ...
    "MinPeakHeadroom_dB", min( ...
    receiverIntegrityTable.ReferencePeakHeadroom_dB), ...
    "MedianPAR_dB", median(receiverIntegrityTable.ReferencePAR_dB), ...
    "MaxNearRailFraction", max( ...
    receiverIntegrityTable.ReferenceNearRailFraction), ...
    "MaxDcMeanRatio_dB", max( ...
    receiverIntegrityTable.ReferenceDcMeanRatio_dB), ...
    "MaxDcSpike_dB", max(receiverIntegrityTable.ReferenceDcSpike_dB), ...
    "MedianLowFrequencyBandFraction_dB", median( ...
    receiverIntegrityTable.ReferenceLowFrequencyBandFraction_dB), ...
    "MedianIqAmplitudeImbalance_dB", median( ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB), ...
    "MedianIqPhaseProxy_deg", median( ...
    receiverIntegrityTable.ReferenceIqPhaseProxy_deg), ...
    "MaxIqImpropriety", max( ...
    receiverIntegrityTable.ReferenceIqImpropriety) ...
    );

summaryRows(end + 1) = struct( ... %#ok<AGROW>
    "ChannelRole", "surveillance", ...
    "ChannelLabel", roleInfo.SurveillanceLabel, ...
    "MedianMeanPower_dBFS", median( ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS), ...
    "MinPeakHeadroom_dB", min( ...
    receiverIntegrityTable.SurveillancePeakHeadroom_dB), ...
    "MedianPAR_dB", median(receiverIntegrityTable.SurveillancePAR_dB), ...
    "MaxNearRailFraction", max( ...
    receiverIntegrityTable.SurveillanceNearRailFraction), ...
    "MaxDcMeanRatio_dB", max( ...
    receiverIntegrityTable.SurveillanceDcMeanRatio_dB), ...
    "MaxDcSpike_dB", max( ...
    receiverIntegrityTable.SurveillanceDcSpike_dB), ...
    "MedianLowFrequencyBandFraction_dB", median( ...
    receiverIntegrityTable.SurveillanceLowFrequencyBandFraction_dB), ...
    "MedianIqAmplitudeImbalance_dB", median( ...
    receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB), ...
    "MedianIqPhaseProxy_deg", median( ...
    receiverIntegrityTable.SurveillanceIqPhaseProxy_deg), ...
    "MaxIqImpropriety", max( ...
    receiverIntegrityTable.SurveillanceIqImpropriety) ...
    );

channelSummaryTable = struct2table(summaryRows);

end

function [receiverIntegrityVerdict, legalGateRecommendation, ...
    datasetClassificationRecommendation, classificationImpact, ...
    decisionTraceTable] = localDetermineStage2Verdicts( ...
    receiverIntegrityTable, ~, ~, ...
    resolvedOptions)

referencePowerVector = ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB;
referenceMinimumPassFraction = mean(referencePowerVector >= ...
    resolvedOptions.ReferencePowerMinimumThreshold_dB);
referenceTargetPassFraction = mean(referencePowerVector >= ...
    resolvedOptions.ReferencePowerTargetMarginThreshold_dB);

severeClippingMask = receiverIntegrityTable.RepetitionVerdict == ...
    "reject_candidate" & ( ...
    receiverIntegrityTable.ReferenceNearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.SurveillanceNearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.ReferenceExactRailFraction > 0.0 | ...
    receiverIntegrityTable.SurveillanceExactRailFraction > 0.0);
severeReferencePowerDeficitMask = referencePowerVector < ...
    resolvedOptions.ReferencePowerMinimumThreshold_dB;
quantizationRiskMask = ...
    receiverIntegrityTable.ReferenceMeanPower_dBFS <= ...
    resolvedOptions.QuantizationRiskThreshold_dBFS | ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS <= ...
    resolvedOptions.QuantizationRiskThreshold_dBFS;
severeQuantizationRiskMask = ...
    receiverIntegrityTable.ReferenceMeanPower_dBFS <= ...
    resolvedOptions.SevereQuantizationThreshold_dBFS | ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS <= ...
    resolvedOptions.SevereQuantizationThreshold_dBFS;
dcIssueMask = receiverIntegrityTable.ReferenceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioDiagnosticThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioDiagnosticThreshold_dB | ...
    receiverIntegrityTable.ReferenceDcSpike_dB >= ...
    resolvedOptions.DcSpikeDiagnosticThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcSpike_dB >= ...
    resolvedOptions.DcSpikeDiagnosticThreshold_dB;
severeDcIssueMask = receiverIntegrityTable.ReferenceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioSevereThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioSevereThreshold_dB | ...
    receiverIntegrityTable.ReferenceDcSpike_dB >= ...
    resolvedOptions.DcSpikeSevereThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcSpike_dB >= ...
    resolvedOptions.DcSpikeSevereThreshold_dB;
iqIssueMask = abs( ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceDiagnosticThreshold_dB | ...
    abs(receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceDiagnosticThreshold_dB | ...
    abs(receiverIntegrityTable.ReferenceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxyDiagnosticThreshold_deg | ...
    abs(receiverIntegrityTable.SurveillanceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxyDiagnosticThreshold_deg | ...
    receiverIntegrityTable.ReferenceIqImpropriety >= ...
    resolvedOptions.IqImproprietyDiagnosticThreshold | ...
    receiverIntegrityTable.SurveillanceIqImpropriety >= ...
    resolvedOptions.IqImproprietyDiagnosticThreshold;
severeIqIssueMask = abs( ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceSevereThreshold_dB | ...
    abs(receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceSevereThreshold_dB | ...
    abs(receiverIntegrityTable.ReferenceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxySevereThreshold_deg | ...
    abs(receiverIntegrityTable.SurveillanceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxySevereThreshold_deg | ...
    receiverIntegrityTable.ReferenceIqImpropriety >= ...
    resolvedOptions.IqImproprietySevereThreshold | ...
    receiverIntegrityTable.SurveillanceIqImpropriety >= ...
    resolvedOptions.IqImproprietySevereThreshold;

systemicSevereDcOrIq = mean(severeDcIssueMask | severeIqIssueMask) >= 0.5;
anyModerateIssue = any(severeReferencePowerDeficitMask) || ...
    any(quantizationRiskMask) || any(dcIssueMask) || any(iqIssueMask) || ...
    any(receiverIntegrityTable.RepetitionVerdict == "retune_candidate");

if any(severeClippingMask) || any(severeQuantizationRiskMask) || ...
        systemicSevereDcOrIq
    receiverIntegrityVerdict = "receiver_integrity_hard_fail";
    legalGateRecommendation = "reject";
    datasetClassificationRecommendation = "rejected";
    classificationImpact = "Stage 2 identifies a severe " + ...
        "receiver-integrity failure. The current data should not be " + ...
        "carried into later stages without collection changes.";
elseif anyModerateIssue
    receiverIntegrityVerdict = "receiver_integrity_caveated";
    legalGateRecommendation = "retune";
    datasetClassificationRecommendation = "diagnostic";
    classificationImpact = "Stage 2 keeps the dataset diagnostic because " + ...
        "receiver-integrity caveats remain. The accepted reference channel " + ...
        "is not stronger than surveillance and later stages should be " + ...
        "reviewed against that limitation.";
else
    receiverIntegrityVerdict = "receiver_integrity_acceptable";
    legalGateRecommendation = "pass";

    if referenceTargetPassFraction >= 0.9
        datasetClassificationRecommendation = "golden";
        classificationImpact = "Stage 2 finds healthy receiver-integrity " + ...
            "margin with the reference channel stronger than surveillance " + ...
            "across the session.";
    else
        datasetClassificationRecommendation = "diagnostic";
        classificationImpact = "Stage 2 passes the receiver-integrity " + ...
            "screen but retains diagnostic classification because the " + ...
            "reference strength margin is not consistently healthy.";
    end
end

decisionRows = struct( ...
    "DecisionItem", {}, ...
    "MetricOrEvidence", {}, ...
    "ThresholdRule", {}, ...
    "WorstCaseIndex", {}, ...
    "Effect", {} ...
    );

decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "reference_power_order", ...
    sprintf("Reference minus surveillance power median = %.3f dB", ...
    median(referencePowerVector)), ...
    sprintf("Reference should exceed surveillance by >= %.1f dB", ...
    resolvedOptions.ReferencePowerMinimumThreshold_dB), ...
    localWorstCaseRepetitionNumber(referencePowerVector, ...
    receiverIntegrityTable.Repetition, "min"), ...
    localPowerOrderEffect(referenceMinimumPassFraction));
decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "clipping_and_headroom", ...
    sprintf("Worst near-rail fraction = %.9f | worst exact-rail fraction = %.9f", ...
    max([receiverIntegrityTable.ReferenceNearRailFraction; ...
    receiverIntegrityTable.SurveillanceNearRailFraction]), ...
    max([receiverIntegrityTable.ReferenceExactRailFraction; ...
    receiverIntegrityTable.SurveillanceExactRailFraction])), ...
    sprintf("Reject if near-rail fraction >= %.1e or exact rails occur", ...
    resolvedOptions.SevereClippingFractionThreshold), ...
    localWorstNearRailRepetition(receiverIntegrityTable), ...
    localBooleanEffect(any(severeClippingMask), ...
    "severe clipping present", "no severe clipping observed"));
decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "quantization_margin", ...
    sprintf("Lowest mean power = %.3f dBFS", ...
    min([receiverIntegrityTable.ReferenceMeanPower_dBFS; ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS])), ...
    sprintf("Retune below %.1f dBFS, severe below %.1f dBFS", ...
    resolvedOptions.QuantizationRiskThreshold_dBFS, ...
    resolvedOptions.SevereQuantizationThreshold_dBFS), ...
    localWorstMeanPowerRepetition(receiverIntegrityTable), ...
    localBooleanEffect(any(quantizationRiskMask), ...
    "scale-usage caveat present", "no quantization-risk evidence"));
decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "dc_lo_contamination", ...
    sprintf("Worst DC spike = %.3f dB", ...
    max([receiverIntegrityTable.ReferenceDcSpike_dB; ...
    receiverIntegrityTable.SurveillanceDcSpike_dB])), ...
    sprintf("Retune above %.1f dB, severe above %.1f dB", ...
    resolvedOptions.DcSpikeDiagnosticThreshold_dB, ...
    resolvedOptions.DcSpikeSevereThreshold_dB), ...
    localWorstDcRepetition(receiverIntegrityTable), ...
    localBooleanEffect(any(dcIssueMask), ...
    "DC or LO caveat present", "DC spike and mean offset remain low"));
decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "iq_image_risk", ...
    sprintf("Worst impropriety = %.4f", ...
    max([receiverIntegrityTable.ReferenceIqImpropriety; ...
    receiverIntegrityTable.SurveillanceIqImpropriety])), ...
    sprintf("Retune above %.3f, severe above %.3f", ...
    resolvedOptions.IqImproprietyDiagnosticThreshold, ...
    resolvedOptions.IqImproprietySevereThreshold), ...
    localWorstIqRepetition(receiverIntegrityTable), ...
    localBooleanEffect(any(iqIssueMask), ...
    "IQ/image caveat present", "IQ/image proxies remain low"));
decisionRows(end + 1) = localMakeDecisionRow( ... %#ok<AGROW>
    "stage2_receiver_integrity_verdict", ...
    sprintf("%s | %s", receiverIntegrityVerdict, ...
    datasetClassificationRecommendation), ...
    "Worst-case repetition behavior overrides favorable averages", ...
    NaN, ...
    classificationImpact);

decisionTraceTable = struct2table(decisionRows);

end

function [analysisValidity, developmentReadiness, ...
    developmentBlockingReason, analysisInterpretation, ...
    developmentInterpretation] = localDetermineDevelopmentStatus( ...
    receiverIntegrityTable, channelSummaryTable, roleInfo, ...
    receiverIntegrityVerdict, resolvedOptions)

hasVerifiedRoleMapping = ismember(roleInfo.RoleSource, [ ...
    "collection_metadata_manual_mapping"; ...
    "explicit_generator_contract"; ...
    "explicit_option_mapping" ...
    ]);
hasFiniteReceiverMetrics = localTableHasFiniteNumericValues( ...
    receiverIntegrityTable);
hasFiniteChannelMetrics = localTableHasFiniteNumericValues( ...
    channelSummaryTable);
analysisIsComplete = hasFiniteReceiverMetrics && hasFiniteChannelMetrics;

if ~hasVerifiedRoleMapping
    analysisValidity = "invalid";
    developmentReadiness = "blocked";
    developmentBlockingReason = "missing_role_mapping";
    analysisInterpretation = "Stage 2 computed sample statistics, but " + ...
        "the reference and surveillance roles were not verified from " + ...
        "session-matched collection metadata.";
    developmentInterpretation = "Downstream development stays blocked " + ...
        "until the role mapping is explicitly validated for this session.";
    return
end

if ~analysisIsComplete
    analysisValidity = "invalid";
    developmentReadiness = "blocked";
    developmentBlockingReason = "stage2_analysis_incomplete";
    analysisInterpretation = "Stage 2 did not produce a complete finite " + ...
        "metrics set across the session.";
    developmentInterpretation = "Downstream development stays blocked " + ...
        "until the Stage 2 metrics are complete and trustworthy.";
    return
end

analysisValidity = "valid";
analysisInterpretation = "Stage 2 used a verified role mapping and " + ...
    "produced a complete finite metrics set, so the current result is " + ...
    "analytically trustworthy.";

if receiverIntegrityVerdict == "receiver_integrity_acceptable"
    developmentReadiness = "ready_for_gate_progression";
    developmentBlockingReason = "ready_for_gate_progression";
    developmentInterpretation = "The current Stage 2 RF result supports " + ...
        "formal progression review once the next stage is implemented.";
    return
end

developmentReadiness = "unblocked_with_dataset_caveat";
developmentBlockingReason = localDetermineDatasetCaveatReason( ...
    receiverIntegrityTable, resolvedOptions);
developmentInterpretation = "The current limitation is attributed to " + ...
    "dataset, hardware, or acquisition behavior rather than a broken " + ...
    "Stage 2 analysis path. Development may continue under caveat, but " + ...
    "this does not formally approve Stage 3.";

end

function developmentBlockingReason = localDetermineDatasetCaveatReason( ...
    receiverIntegrityTable, resolvedOptions)

referencePowerVector = ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB;
severeClippingMask = receiverIntegrityTable.ReferenceNearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.SurveillanceNearRailFraction >= ...
    resolvedOptions.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.ReferenceExactRailFraction > 0.0 | ...
    receiverIntegrityTable.SurveillanceExactRailFraction > 0.0;
severeQuantizationRiskMask = ...
    receiverIntegrityTable.ReferenceMeanPower_dBFS <= ...
    resolvedOptions.SevereQuantizationThreshold_dBFS | ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS <= ...
    resolvedOptions.SevereQuantizationThreshold_dBFS;
severeDcIssueMask = receiverIntegrityTable.ReferenceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioSevereThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcMeanRatio_dB >= ...
    resolvedOptions.DcMeanRatioSevereThreshold_dB | ...
    receiverIntegrityTable.ReferenceDcSpike_dB >= ...
    resolvedOptions.DcSpikeSevereThreshold_dB | ...
    receiverIntegrityTable.SurveillanceDcSpike_dB >= ...
    resolvedOptions.DcSpikeSevereThreshold_dB;
severeIqIssueMask = abs( ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceSevereThreshold_dB | ...
    abs(receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB) >= ...
    resolvedOptions.IqAmplitudeImbalanceSevereThreshold_dB | ...
    abs(receiverIntegrityTable.ReferenceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxySevereThreshold_deg | ...
    abs(receiverIntegrityTable.SurveillanceIqPhaseProxy_deg) >= ...
    resolvedOptions.IqPhaseProxySevereThreshold_deg | ...
    receiverIntegrityTable.ReferenceIqImpropriety >= ...
    resolvedOptions.IqImproprietySevereThreshold | ...
    receiverIntegrityTable.SurveillanceIqImpropriety >= ...
    resolvedOptions.IqImproprietySevereThreshold;

if any(severeClippingMask) || any(severeQuantizationRiskMask) || ...
        mean(severeDcIssueMask | severeIqIssueMask) >= 0.5
    developmentBlockingReason = "severe_receiver_impairment";
    return
end

if all(referencePowerVector < ...
        resolvedOptions.ReferencePowerMinimumThreshold_dB)
    developmentBlockingReason = "weak_reference_power_ordering";
    return
end

developmentBlockingReason = "receiver_caveats_present";

end

function row = localMakeDecisionRow(decisionItem, metricOrEvidence, ...
    thresholdRule, worstCaseIndex, effect)

row = struct();
row.DecisionItem = string(decisionItem);
row.MetricOrEvidence = string(metricOrEvidence);
row.ThresholdRule = string(thresholdRule);
row.WorstCaseIndex = double(worstCaseIndex);
row.Effect = string(effect);

end

function effectText = localPowerOrderEffect(referenceMinimumPassFraction)

if referenceMinimumPassFraction >= 0.9
    effectText = "reference power ordering supports later stages";
elseif referenceMinimumPassFraction > 0.0
    effectText = "reference power ordering is inconsistent";
else
    effectText = "reference is weaker than surveillance in every repetition";
end

end

function effectText = localBooleanEffect(condition, trueText, falseText)

if condition
    effectText = trueText;
else
    effectText = falseText;
end

end

function value = localWorstCaseRepetitionNumber(metricVector, ...
    repetitionVector, directionText)

if directionText == "min"
    [~, index] = min(metricVector);
else
    [~, index] = max(metricVector);
end

value = repetitionVector(index);

end

function value = localWorstNearRailRepetition(receiverIntegrityTable)

[~, index] = max([ ...
    receiverIntegrityTable.ReferenceNearRailFraction; ...
    receiverIntegrityTable.SurveillanceNearRailFraction ...
    ]);

if index > height(receiverIntegrityTable)
    index = index - height(receiverIntegrityTable);
end

value = receiverIntegrityTable.Repetition(index);

end

function value = localWorstMeanPowerRepetition(receiverIntegrityTable)

[~, index] = min([ ...
    receiverIntegrityTable.ReferenceMeanPower_dBFS; ...
    receiverIntegrityTable.SurveillanceMeanPower_dBFS ...
    ]);

if index > height(receiverIntegrityTable)
    index = index - height(receiverIntegrityTable);
end

value = receiverIntegrityTable.Repetition(index);

end

function value = localWorstDcRepetition(receiverIntegrityTable)

[~, index] = max([ ...
    receiverIntegrityTable.ReferenceDcSpike_dB; ...
    receiverIntegrityTable.SurveillanceDcSpike_dB ...
    ]);

if index > height(receiverIntegrityTable)
    index = index - height(receiverIntegrityTable);
end

value = receiverIntegrityTable.Repetition(index);

end

function value = localWorstIqRepetition(receiverIntegrityTable)

[~, index] = max([ ...
    receiverIntegrityTable.ReferenceIqImpropriety; ...
    receiverIntegrityTable.SurveillanceIqImpropriety ...
    ]);

if index > height(receiverIntegrityTable)
    index = index - height(receiverIntegrityTable);
end

value = receiverIntegrityTable.Repetition(index);

end

function metrics = localBuildMetrics(receiverIntegrityTable, ...
    channelSummaryTable, roleInfo, roleEvidence, ...
    receiverIntegrityVerdict, legalGateRecommendation, ...
    datasetClassificationRecommendation, classificationImpact, ...
    analysisValidity, developmentReadiness, ...
    developmentBlockingReason, analysisInterpretation, ...
    developmentInterpretation)

metrics = struct();
metrics.stage_id = "Stage2_ReceiverIntegrity";
metrics.receiver_integrity_verdict = receiverIntegrityVerdict;
metrics.legal_gate_recommendation = legalGateRecommendation;
metrics.dataset_classification_recommendation = ...
    datasetClassificationRecommendation;
metrics.classification_impact = classificationImpact;
metrics.analysis_validity = analysisValidity;
metrics.development_readiness = developmentReadiness;
metrics.development_blocking_reason = developmentBlockingReason;
metrics.analysis_interpretation = analysisInterpretation;
metrics.development_interpretation = developmentInterpretation;
metrics.role_source = roleInfo.RoleSource;
metrics.reference_label = roleInfo.ReferenceLabel;
metrics.surveillance_label = roleInfo.SurveillanceLabel;
metrics.reference_column_index = roleInfo.ReferenceColumnIndex;
metrics.surveillance_column_index = roleInfo.SurveillanceColumnIndex;
metrics.reference_power_minimum_fraction = ...
    roleEvidence.ReferencePowerMinimumFraction;
metrics.reference_power_target_fraction = ...
    roleEvidence.ReferencePowerTargetFraction;
metrics.reference_minus_surveillance_power_db_min = ...
    roleEvidence.ReferenceMinusSurveillancePower_dB_Min;
metrics.reference_minus_surveillance_power_db_median = ...
    roleEvidence.ReferenceMinusSurveillancePower_dB_Median;
metrics.reference_minus_surveillance_power_db_max = ...
    roleEvidence.ReferenceMinusSurveillancePower_dB_Max;
metrics.receiver_integrity_table = table2struct(receiverIntegrityTable);
metrics.channel_summary_table = table2struct(channelSummaryTable);

end

function value = localTableHasFiniteNumericValues(inputTable)

if isempty(inputTable) || height(inputTable) == 0
    value = false;
    return
end

numericTable = inputTable(:, vartype("numeric"));

if width(numericTable) == 0
    value = true;
    return
end

value = all(isfinite(numericTable{:,:}), "all");

end

function joinedText = localJoinNotes(noteTokens)

noteTokens = string(noteTokens);
noteTokens = strtrim(noteTokens);
noteTokens = noteTokens(strlength(noteTokens) > 0);

if isempty(noteTokens)
    joinedText = "";
    return
end

joinedText = strjoin(noteTokens, " | ");

end
