function [analysis, fullMapProducts] = helperAnalyzeG5Mitigation(sessionData, ...
    collectionMetadataInfo, g3SyncResults, g4Analysis, options)
%HELPERANALYZEG5MITIGATION Analyze the first G5 mitigation slice.
%
%   ANALYSIS = HELPERANALYZEG5MITIGATION(SESSIONDATA, ...
%   COLLECTIONMETADATAINFO, G3SYNCRESULTS, G4ANALYSIS, OPTIONS) compares
%   none, conservative_lms, and aggressive_lms mitigation candidates on a
%   bounded set of G4 map rows. LMS candidates use dsp.LMSFilter, and all
%   candidate maps are recomputed with ambgfun.
%
%   [ANALYSIS, FULLMAPPRODUCTS] also returns the full candidate maps for
%   immediate downstream diagnostics. The optional output is not retained
%   in ANALYSIS, so the established one-output behavior remains compact.

arguments
    sessionData (1,1) struct
    collectionMetadataInfo (1,1) struct
    g3SyncResults (1,1) struct
    g4Analysis (1,1) struct
    options (1,1) struct = struct()
end

localValidateNativeFunctions();
localValidateG4Analysis(g4Analysis);

resolvedOptions = localResolveOptions(sessionData, g4Analysis, options);
candidateProfiles = localBuildCandidateProfiles(resolvedOptions);
candidateTable = localBuildCandidateTable(candidateProfiles, ...
    resolvedOptions);
roleInfo = localResolveRoleInfo(sessionData, collectionMetadataInfo, ...
    g4Analysis, resolvedOptions);
appliedCorrection = localResolveAppliedCorrection(g4Analysis);
productDefinition = localResolveProductDefinition(g4Analysis, ...
    resolvedOptions);
selectedRows = localSelectG4Rows(g4Analysis.MapSummaryTable, ...
    resolvedOptions);
preprocessedSignals = localBuildPreprocessedSignals(sessionData, ...
    selectedRows, roleInfo, appliedCorrection, resolvedOptions);

[metricTable, protectedDetailTable, residualErrorPowerTable, ...
    representativeMaps, targetEvidenceTable, targetRegionViews, ...
    fullMapProducts] = ...
    localEvaluateCandidates(selectedRows, ...
    preprocessedSignals, candidateProfiles, appliedCorrection, ...
    productDefinition, resolvedOptions, nargout > 1);
suppressionSummaryTable = localBuildSuppressionSummary(metricTable, ...
    candidateProfiles);
protectedRetentionTable = localBuildProtectedRetentionSummary( ...
    protectedDetailTable, candidateProfiles, resolvedOptions);
detectabilityProxyTable = localBuildDetectabilityProxyTable( ...
    metricTable, protectedRetentionTable, candidateProfiles, ...
    resolvedOptions);
upstreamCaveatTable = localBuildUpstreamCaveatTable(g3SyncResults, ...
    g4Analysis);
causalAssessmentTable = localBuildCausalAssessmentTable( ...
    suppressionSummaryTable, protectedRetentionTable, ...
    detectabilityProxyTable, upstreamCaveatTable, candidateProfiles, ...
    resolvedOptions);
acquisitionImplicationTable = localBuildAcquisitionImplicationTable( ...
    causalAssessmentTable, g4Analysis);
decisionComparisonTable = localBuildDecisionComparisonTable( ...
    suppressionSummaryTable, protectedRetentionTable, ...
    detectabilityProxyTable, causalAssessmentTable, candidateProfiles, ...
    g4Analysis);
decision = localBuildDecision(decisionComparisonTable, ...
    causalAssessmentTable, g4Analysis, resolvedOptions);
requirementsCoverageTable = localBuildRequirementsCoverageTable( ...
    decision, selectedRows);

analysis = struct();
analysis.DatasetId = string(sessionData.DatasetId);
analysis.StageId = "G5_Mitigation";
analysis.AnalysisStageId = "G5_Mitigation_First_Slice";
analysis.AnalysisScope = string(resolvedOptions.AnalysisScope);
analysis.Options = localBuildOptionsOutput(resolvedOptions);
analysis.RoleInfo = roleInfo;
analysis.AppliedCorrection = appliedCorrection;
analysis.BaselineProductDefinition = productDefinition;
analysis.SelectedG4MapRows = selectedRows;
analysis.G4OverallLabel = localResolveG4Label(g4Analysis, "OverallLabel");
analysis.G4SceneObservabilityLabel = localResolveG4Label(g4Analysis, ...
    "SceneObservabilityLabel");
analysis.G4FullRateAuditAgreementLabel = localResolveG4Label(g4Analysis, ...
    "FullRateAuditAgreementLabel");
analysis.GateDecision = decision.GateDecision;
analysis.ReviewStatus = decision.ReviewStatus;
analysis.DecisionLabel = decision.DecisionLabel;
analysis.DecisionRationale = decision.Rationale;
analysis.NextBranch = decision.NextBranch;
analysis.FormalGateDecisionEmitted = decision.FormalGateDecisionEmitted;
analysis.MitigationCandidateTable = candidateTable;
analysis.MitigationMetricTable = metricTable;
analysis.SuppressionSummaryTable = suppressionSummaryTable;
analysis.ProtectedRegionRetentionTable = protectedRetentionTable;
analysis.ProtectedRegionRetentionDetailTable = protectedDetailTable;
analysis.ResidualErrorPowerTable = residualErrorPowerTable;
analysis.DetectabilityProxyTable = detectabilityProxyTable;
analysis.MitigationCausalAssessmentTable = causalAssessmentTable;
analysis.AcquisitionImplicationTable = acquisitionImplicationTable;
analysis.DecisionComparisonTable = decisionComparisonTable;
analysis.UpstreamCaveatsCarriedForward = upstreamCaveatTable;
analysis.RequirementsCoverageTable = requirementsCoverageTable;
analysis.RepresentativeMaps = representativeMaps;
analysis.SyntheticTargetEvidenceTable = targetEvidenceTable;
analysis.SyntheticTargetRegionViews = targetRegionViews;
analysis.TargetRetentionPolicy = localResolveTargetRetentionPolicy( ...
    resolvedOptions);

end

function localValidateNativeFunctions()

if exist("ambgfun", "file") ~= 2
    error("helperAnalyzeG5Mitigation:MissingAmbgfun", ...
        "G5 map recomputation requires ambgfun.");
end

if exist("dsp.LMSFilter", "class") ~= 8
    error("helperAnalyzeG5Mitigation:MissingLMSFilter", ...
        "G5 LMS candidates require dsp.LMSFilter.");
end

end

function localValidateG4Analysis(g4Analysis)

requiredFields = ["Interpretation"; "MapSummaryTable"; ...
    "BaselineProductDefinition"];

for idx = 1:numel(requiredFields)
    if ~isfield(g4Analysis, requiredFields(idx))
        error("helperAnalyzeG5Mitigation:MissingG4Field", ...
            "G5 requires g4Analysis.%s.", requiredFields(idx));
    end
end

if ~istable(g4Analysis.MapSummaryTable) || isempty(g4Analysis.MapSummaryTable)
    error("helperAnalyzeG5Mitigation:InvalidG4MapSummary", ...
        "G5 requires a nonempty G4 MapSummaryTable.");
end

requiredVariables = ["Repetition"; "RelativePath"; "CpiLabel"; ...
    "WindowLabel"; "WindowStartSample"; "WindowIndex"; ...
    "CpiDuration_s"; "CpiSamples"];
variableNames = string(g4Analysis.MapSummaryTable.Properties.VariableNames);

for idx = 1:numel(requiredVariables)
    if ~any(variableNames == requiredVariables(idx))
        error("helperAnalyzeG5Mitigation:MissingG4MapVariable", ...
            "G4 MapSummaryTable is missing %s.", requiredVariables(idx));
    end
end

end

function resolvedOptions = localResolveOptions(sessionData, g4Analysis, ...
    options)

sampleRateVector = unique(sessionData.RadarTable.SampleRate_Hz);

if numel(sampleRateVector) ~= 1
    error("helperAnalyzeG5Mitigation:SampleRateMismatch", ...
        "G5 requires one sample rate across the session.");
end

g4Options = struct();

if isfield(g4Analysis, "Options") && isstruct(g4Analysis.Options)
    g4Options = g4Analysis.Options;
end

sampleRateHz = double(sampleRateVector(1));
mapDecimationFactor = localResolveNumericOption(g4Options, ...
    "MapDecimationFactor", 200.0);
resolvedOptions = struct();
resolvedOptions.AnalysisScope = ...
    "diagnostic_first_slice_recommended_cpi_center_windows";
resolvedOptions.CandidateNames = ["none"; "conservative_lms"; ...
    "aggressive_lms"];
resolvedOptions.ReviewCpiLabels = localDefaultReviewCpiLabels(g4Analysis);
resolvedOptions.ReviewWindowLabels = "center";
resolvedOptions.ReviewRepetitions = localDefaultReviewRepetitions( ...
    g4Analysis.MapSummaryTable, g4Options);
resolvedOptions.MaxReviewRows = Inf;
resolvedOptions.SampleRateHz = sampleRateHz;
resolvedOptions.MapDecimationFactor = mapDecimationFactor;
resolvedOptions.MapSampleRateHz = localResolveNumericOption(g4Options, ...
    "MapSampleRateHz", sampleRateHz ./ mapDecimationFactor);
resolvedOptions.MapRateMode = "reduced_rate_g5_candidate_product";
resolvedOptions.ReviewMapRows = localResolveNumericOption(g4Options, ...
    "ReviewMapRows", 512.0);
resolvedOptions.ReviewMapCols = localResolveNumericOption(g4Options, ...
    "ReviewMapCols", 512.0);
resolvedOptions.FigureFloor_dB = localResolveNumericOption(g4Options, ...
    "FigureFloor_dB", -60.0);
resolvedOptions.OriginMinDelayRadius_samples = localResolveNumericOption( ...
    g4Options, "OriginMinDelayRadius_samples", 2.0);
resolvedOptions.OriginMinDopplerRadius_Hz = localResolveNumericOption( ...
    g4Options, "OriginMinDopplerRadius_Hz", 5.0);
resolvedOptions.DirectPathExclusionDelayRadius_samples = ...
    localResolveNumericOption(g4Options, ...
    "DirectPathExclusionDelayRadius_samples", 6.0);
resolvedOptions.DirectPathExclusionDopplerRadius_Hz = ...
    localResolveNumericOption(g4Options, ...
    "DirectPathExclusionDopplerRadius_Hz", 25.0);
resolvedOptions.ZeroDopplerRidgeExclusion_Hz = ...
    localResolveNumericOption(g4Options, ...
    "ZeroDopplerRidgeExclusion_Hz", 25.0);
resolvedOptions.LocalProminenceOuterRadius_bins = ...
    localResolveNumericOption(g4Options, ...
    "LocalProminenceOuterRadius_bins", 12.0);
resolvedOptions.SceneCaveatedOffOriginNonzeroDopplerEnergyFraction = ...
    localResolveNumericOption(g4Options, ...
    "SceneCaveatedOffOriginNonzeroDopplerEnergyFraction", 0.03);
resolvedOptions.SceneCaveatedOffOriginOccupiedFraction = ...
    localResolveNumericOption(g4Options, ...
    "SceneCaveatedOffOriginOccupiedFraction", 0.001);
resolvedOptions.SceneCaveatedMaxZeroDopplerRidgeEnergyFraction = ...
    localResolveNumericOption(g4Options, ...
    "SceneCaveatedMaxZeroDopplerRidgeEnergyFraction", 0.80);
resolvedOptions.SceneCaveatedMaxDirectPathToOffRidgeEnergy_dB = ...
    localResolveNumericOption(g4Options, ...
    "SceneCaveatedMaxDirectPathToOffRidgeEnergy_dB", 70.0);
resolvedOptions.SceneScoreOffOriginEnergyWeight = ...
    localResolveNumericOption(g4Options, ...
    "SceneScoreOffOriginEnergyWeight", 100.0);
resolvedOptions.SceneScoreOccupiedFractionWeight = ...
    localResolveNumericOption(g4Options, ...
    "SceneScoreOccupiedFractionWeight", 1000.0);
resolvedOptions.SceneScoreZeroDopplerPenaltyWeight = ...
    localResolveNumericOption(g4Options, ...
    "SceneScoreZeroDopplerPenaltyWeight", 25.0);
resolvedOptions.SceneScoreDirectPathDominancePenaltyWeight = ...
    localResolveNumericOption(g4Options, ...
    "SceneScoreDirectPathDominancePenaltyWeight", 0.20);
resolvedOptions.SceneScoreDirectPathDominanceReference_dB = ...
    localResolveNumericOption(g4Options, ...
    "SceneScoreDirectPathDominanceReference_dB", 60.0);
resolvedOptions.DirectPathSuppressionForCandidate_dB = 3.0;
resolvedOptions.SceneScoreImprovementForReveal = 0.50;
resolvedOptions.OffOriginEnergyImprovementForReveal = 0.005;
resolvedOptions.OffOriginOccupiedImprovementForReveal = 0.0005;
resolvedOptions.ProtectedRegionMinRetentionRatio = 0.50;
resolvedOptions.ProtectedRegionThresholdRelativeToDirectPath_dB = -20.0;
resolvedOptions.LmsMethod = "Normalized LMS";
resolvedOptions.ConservativeLmsLength = 16.0;
resolvedOptions.ConservativeLmsStepSize = 0.02;
resolvedOptions.ConservativeLmsLeakageFactor = 1.0;
resolvedOptions.AggressiveLmsLength = 64.0;
resolvedOptions.AggressiveLmsStepSize = 0.15;
resolvedOptions.AggressiveLmsLeakageFactor = 0.999;
resolvedOptions.DataProfile = "field_capture";
resolvedOptions.RunPostHocSyntheticTargetEvidence = false;
resolvedOptions.SyntheticTruth = struct();
resolvedOptions.TargetLagUncertainty_samples = NaN;
resolvedOptions.TargetResidualFrequencyUncertainty_Hz = NaN;

optionFields = fieldnames(options);

for idx = 1:numel(optionFields)
    fieldName = optionFields{idx};
    resolvedOptions.(fieldName) = options.(fieldName);
end

resolvedOptions.CandidateNames = string(resolvedOptions.CandidateNames(:));
localValidateCandidateNames(resolvedOptions.CandidateNames);
resolvedOptions.ReviewCpiLabels = string(resolvedOptions.ReviewCpiLabels(:));
resolvedOptions.ReviewWindowLabels = string( ...
    resolvedOptions.ReviewWindowLabels(:));
resolvedOptions.ReviewRepetitions = double( ...
    resolvedOptions.ReviewRepetitions(:));
resolvedOptions.MaxReviewRows = double(resolvedOptions.MaxReviewRows);
resolvedOptions.MapDecimationFactor = round( ...
    double(resolvedOptions.MapDecimationFactor));
resolvedOptions.MapSampleRateHz = double(resolvedOptions.MapSampleRateHz);
resolvedOptions.ReviewMapRows = round(double(resolvedOptions.ReviewMapRows));
resolvedOptions.ReviewMapCols = round(double(resolvedOptions.ReviewMapCols));
resolvedOptions.DataProfile = lower(strtrim( ...
    string(resolvedOptions.DataProfile)));
resolvedOptions.RunPostHocSyntheticTargetEvidence = logical( ...
    resolvedOptions.RunPostHocSyntheticTargetEvidence);

if ~ismember(resolvedOptions.DataProfile, ...
        ["field_capture", "synthetic"])
    error("helperAnalyzeG5Mitigation:InvalidDataProfile", ...
        "DataProfile must be ""field_capture"" or ""synthetic"".");
end

if resolvedOptions.RunPostHocSyntheticTargetEvidence && ...
        resolvedOptions.DataProfile ~= "synthetic"
    error("helperAnalyzeG5Mitigation:InvalidTargetEvidenceProfile", ...
        "Post-hoc scenario truth is supported only for synthetic data.");
end

end

function value = localResolveNumericOption(inputStruct, fieldName, ...
    defaultValue)

value = defaultValue;

if isstruct(inputStruct) && isfield(inputStruct, fieldName)
    value = double(inputStruct.(fieldName));
end

end

function defaultLabels = localDefaultReviewCpiLabels(g4Analysis)

defaultLabels = "";

if isfield(g4Analysis, "RecommendedBaselineCpiLabel")
    defaultLabels = string(g4Analysis.RecommendedBaselineCpiLabel);
end

if strlength(defaultLabels) == 0
    defaultLabels = string(g4Analysis.MapSummaryTable.CpiLabel(1));
end

end

function defaultRepetitions = localDefaultReviewRepetitions(mapSummaryTable, ...
    g4Options)

if isfield(g4Options, "FullRateAuditRepetitions")
    defaultRepetitions = double(g4Options.FullRateAuditRepetitions(:));
    return
end

availableRepetitions = unique(double(mapSummaryTable.Repetition));

if numel(availableRepetitions) <= 3
    defaultRepetitions = availableRepetitions(:);
    return
end

middleIndex = ceil(numel(availableRepetitions) ./ 2.0);
defaultRepetitions = [availableRepetitions(1); ...
    availableRepetitions(middleIndex); availableRepetitions(end)];

end

function localValidateCandidateNames(candidateNames)

requiredNames = ["none"; "conservative_lms"; "aggressive_lms"];

if ~isequal(sort(candidateNames), sort(requiredNames))
    error("helperAnalyzeG5Mitigation:InvalidCandidateSet", ...
        "G5 requires exactly none, conservative_lms, and aggressive_lms.");
end

end

function candidateProfiles = localBuildCandidateProfiles(resolvedOptions)

candidateNames = resolvedOptions.CandidateNames;
candidateProfiles = repmat(localBuildCandidateProfileTemplate(), ...
    numel(candidateNames), 1);

for idx = 1:numel(candidateNames)
    candidateName = candidateNames(idx);
    profile = localBuildCandidateProfileTemplate();
    profile.CandidateName = candidateName;
    profile.ReferenceInput = "corrected_reference_map_window";
    profile.DesiredInput = "corrected_surveillance_map_window";
    profile.AdaptationSpan = "current_cpi_window_only";
    profile.LeakageFactor = 1.0;

    if candidateName == "none"
        profile.Intent = "baseline_no_mitigation";
        profile.MitigationMethod = "none";
        profile.ToolboxFunction = "none";
        profile.UsesDspLMSFilter = false;
        profile.ReferenceInput = "not_used";
        profile.AdaptationSpan = "none";
        profile.EligibilityLabel = "baseline_required";
        profile.Rationale = "Required no-mitigation baseline.";
    elseif candidateName == "conservative_lms"
        profile.Intent = "lower_risk_adaptive_leakage_cancellation";
        profile.MitigationMethod = "lms_residual_error";
        profile.ToolboxFunction = "dsp.LMSFilter";
        profile.UsesDspLMSFilter = true;
        profile.LmsMethod = string(resolvedOptions.LmsMethod);
        profile.FilterLength = double(resolvedOptions.ConservativeLmsLength);
        profile.StepSize = double(resolvedOptions.ConservativeLmsStepSize);
        profile.LeakageFactor = ...
            double(resolvedOptions.ConservativeLmsLeakageFactor);
        profile.EligibilityLabel = "candidate_required";
        profile.Rationale = "Lower step size and shorter filter length.";
    else
        profile.Intent = "higher_suppression_adaptive_cancellation";
        profile.MitigationMethod = "lms_residual_error";
        profile.ToolboxFunction = "dsp.LMSFilter";
        profile.UsesDspLMSFilter = true;
        profile.LmsMethod = string(resolvedOptions.LmsMethod);
        profile.FilterLength = double(resolvedOptions.AggressiveLmsLength);
        profile.StepSize = double(resolvedOptions.AggressiveLmsStepSize);
        profile.LeakageFactor = ...
            double(resolvedOptions.AggressiveLmsLeakageFactor);
        profile.EligibilityLabel = "candidate_required";
        profile.Rationale = "Higher step size and longer filter length.";
    end

    candidateProfiles(idx) = profile;
end

end

function profile = localBuildCandidateProfileTemplate()

profile = struct( ...
    "CandidateName", "", ...
    "Intent", "", ...
    "MitigationMethod", "", ...
    "ToolboxFunction", "", ...
    "UsesDspLMSFilter", false, ...
    "LmsMethod", "", ...
    "ReferenceInput", "", ...
    "DesiredInput", "", ...
    "FilterLength", 0.0, ...
    "StepSize", 0.0, ...
    "LeakageFactor", 1.0, ...
    "AdaptationSpan", "", ...
    "EligibilityLabel", "", ...
    "Rationale", "" ...
    );

end

function candidateTable = localBuildCandidateTable(candidateProfiles, ...
    resolvedOptions)

candidateTable = struct2table(candidateProfiles);

if resolvedOptions.DataProfile == "synthetic"
    protectedRegionPolicy = "descriptive_no_target_retention_cutoff";
    minimumRetentionRatio = NaN;
else
    protectedRegionPolicy = ...
        "baseline_off_origin_nonzero_doppler_above_peak_minus_20db";
    minimumRetentionRatio = double( ...
        resolvedOptions.ProtectedRegionMinRetentionRatio);
end

candidateTable.ProtectedRegionPolicy = repmat( ...
    protectedRegionPolicy, height(candidateTable), 1);
candidateTable.MinProtectedRetentionRatio = repmat( ...
    minimumRetentionRatio, height(candidateTable), 1);

end

function roleInfo = localResolveRoleInfo(sessionData, ...
    collectionMetadataInfo, g4Analysis, resolvedOptions)

roleInfo = helperResolveChannelRoles(sessionData, collectionMetadataInfo, ...
    resolvedOptions);
g4ReferenceLabel = localResolveG4Label(g4Analysis, "ReferenceLabel");
g4SurveillanceLabel = localResolveG4Label(g4Analysis, ...
    "SurveillanceLabel");

if strlength(g4ReferenceLabel) > 0 && ...
        roleInfo.ReferenceLabel ~= g4ReferenceLabel
    error("helperAnalyzeG5Mitigation:ReferenceRoleMismatch", ...
        "Explicit G5 reference role does not match the G4 result.");
end

if strlength(g4SurveillanceLabel) > 0 && ...
        roleInfo.SurveillanceLabel ~= g4SurveillanceLabel
    error("helperAnalyzeG5Mitigation:SurveillanceRoleMismatch", ...
        "Explicit G5 surveillance role does not match the G4 result.");
end

end

function appliedCorrection = localResolveAppliedCorrection(g4Analysis)

definition = g4Analysis.BaselineProductDefinition;
appliedCorrection = struct();
appliedCorrection.AppliedLag_samples = double(definition.AppliedLag_samples);
appliedCorrection.AppliedResidualFrequency_Hz = ...
    double(definition.AppliedResidualFrequency_Hz);
appliedCorrection.Source = "g4_baseline_product_definition";

if isfield(definition, "AppliedCorrectionSource")
    appliedCorrection.Source = string(definition.AppliedCorrectionSource);
end

end

function productDefinition = localResolveProductDefinition(g4Analysis, ...
    resolvedOptions)

productDefinition = g4Analysis.BaselineProductDefinition;
productDefinition.MapRateMode = resolvedOptions.MapRateMode;
productDefinition.MapSampleRateHz = resolvedOptions.MapSampleRateHz;
productDefinition.MapDecimationFactor = resolvedOptions.MapDecimationFactor;
productDefinition = localEnsureDefinitionField(productDefinition, ...
    "OriginSearchDelayRadius_samples", ...
    resolvedOptions.OriginMinDelayRadius_samples);
productDefinition = localEnsureDefinitionField(productDefinition, ...
    "OriginSearchDopplerRadius_Hz", ...
    resolvedOptions.OriginMinDopplerRadius_Hz);
productDefinition = localEnsureDefinitionField(productDefinition, ...
    "ExclusionDelayRadius_samples", ...
    resolvedOptions.DirectPathExclusionDelayRadius_samples);
productDefinition = localEnsureDefinitionField(productDefinition, ...
    "ExclusionDopplerRadius_Hz", ...
    resolvedOptions.DirectPathExclusionDopplerRadius_Hz);
productDefinition = localEnsureDefinitionField(productDefinition, ...
    "ZeroDopplerRidgeExclusion_Hz", ...
    resolvedOptions.ZeroDopplerRidgeExclusion_Hz);

end

function outputStruct = localEnsureDefinitionField(inputStruct, ...
    fieldName, defaultValue)

outputStruct = inputStruct;

if ~isfield(outputStruct, fieldName)
    outputStruct.(fieldName) = defaultValue;
end

end

function selectedRows = localSelectG4Rows(mapSummaryTable, resolvedOptions)

rowMask = ismember(string(mapSummaryTable.CpiLabel), ...
    resolvedOptions.ReviewCpiLabels) & ...
    ismember(string(mapSummaryTable.WindowLabel), ...
    resolvedOptions.ReviewWindowLabels) & ...
    ismember(double(mapSummaryTable.Repetition), ...
    resolvedOptions.ReviewRepetitions);
selectedRows = sortrows(mapSummaryTable(rowMask, :), ...
    ["Repetition", "CpiLabel", "WindowStartSample"]);

if isempty(selectedRows)
    error("helperAnalyzeG5Mitigation:NoSelectedG4Rows", ...
        "No G4 rows matched the requested G5 review slice.");
end

if isfinite(resolvedOptions.MaxReviewRows)
    keepCount = min(height(selectedRows), ...
        round(resolvedOptions.MaxReviewRows));
    selectedRows = selectedRows(1:keepCount, :);
end

end

function preprocessedSignals = localBuildPreprocessedSignals(sessionData, ...
    selectedRows, roleInfo, appliedCorrection, resolvedOptions)

neededRepetitions = unique(double(selectedRows.Repetition));
preprocessedSignals = repmat(struct( ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "ReferenceMapSamples", single([]), ...
    "SurveillanceMapSamples", single([]) ...
    ), max(neededRepetitions), 1);

for idx = 1:numel(neededRepetitions)
    repetitionValue = neededRepetitions(idx);
    scan = localResolveScanWithSamples(sessionData, repetitionValue);
    referenceSamples = double(scan.Samples(:, ...
        roleInfo.ReferenceColumnIndex));
    surveillanceSamples = double(scan.Samples(:, ...
        roleInfo.SurveillanceColumnIndex));
    correctedSurveillance = localApplyIntegerDelay(surveillanceSamples, ...
        appliedCorrection.AppliedLag_samples);
    correctedSurveillance = localApplyResidualFrequencyCorrection( ...
        correctedSurveillance, ...
        appliedCorrection.AppliedResidualFrequency_Hz, ...
        resolvedOptions.SampleRateHz);
    preprocessedSignals(repetitionValue).Repetition = repetitionValue;
    preprocessedSignals(repetitionValue).RelativePath = ...
        string(scan.RelativePath);
    preprocessedSignals(repetitionValue).ReferenceMapSamples = ...
        single(resample(referenceSamples, 1, ...
        resolvedOptions.MapDecimationFactor));
    preprocessedSignals(repetitionValue).SurveillanceMapSamples = ...
        single(resample(correctedSurveillance, 1, ...
        resolvedOptions.MapDecimationFactor));
end

end

function [metricTable, protectedDetailTable, residualErrorPowerTable, ...
    representativeMaps, targetEvidenceTable, targetRegionViews, ...
    fullMapProducts] = ...
    localEvaluateCandidates(selectedRows, ...
    preprocessedSignals, candidateProfiles, appliedCorrection, ...
    productDefinition, resolvedOptions, returnFullMaps)

rowCount = height(selectedRows);
candidateCount = numel(candidateProfiles);
metricRows = repmat(localMetricRowTemplate(), rowCount * candidateCount, 1);
protectedRows = repmat(localProtectedRowTemplate(), ...
    rowCount * candidateCount, 1);
residualRows = repmat(localResidualRowTemplate(), ...
    rowCount * candidateCount, 1);
representativeMaps = repmat(localRepresentativeMapTemplate(), ...
    candidateCount, 1);
metricIndex = 0;
protectedIndex = 0;
residualIndex = 0;
targetEvidenceTable = table();
targetRegionViews = struct([]);
fullMapProducts = repmat(localFullMapProductTemplate(), 0, 1);

if returnFullMaps
    fullMapProducts = repmat(localFullMapProductTemplate(), ...
        rowCount * candidateCount, 1);
end

for rowIndex = 1:rowCount
    selectedRow = selectedRows(rowIndex, :);
    repetitionValue = double(selectedRow.Repetition(1));
    signal = preprocessedSignals(repetitionValue);
    mapWindowStart = localConvertStartSampleToMapDomain( ...
        selectedRow.WindowStartSample(1), ...
        resolvedOptions.MapDecimationFactor);
    mapWindowStop = mapWindowStart + double(selectedRow.CpiSamples(1)) - 1;

    if mapWindowStop > numel(signal.ReferenceMapSamples)
        error("helperAnalyzeG5Mitigation:InvalidMapWindow", ...
            "Map-domain window [%d %d] does not fit repetition %d.", ...
            mapWindowStart, mapWindowStop, repetitionValue);
    end

    referenceWindow = signal.ReferenceMapSamples(mapWindowStart: ...
        mapWindowStop);
    surveillanceWindow = signal.SurveillanceMapSamples(mapWindowStart: ...
        mapWindowStop);
    cpiDefinition = localBuildCpiDefinition(selectedRow);
    candidateProducts = cell(candidateCount, 1);

    for candidateIndex = 1:candidateCount
        profile = candidateProfiles(candidateIndex);
        [candidateSurveillance, residualInfo] = localApplyCandidate( ...
            referenceWindow, surveillanceWindow, profile);
        mapProduct = localBuildMapProduct(referenceWindow, ...
            candidateSurveillance, cpiDefinition, productDefinition, ...
            resolvedOptions);
        if returnFullMaps
            outputIndex = (rowIndex - 1) * candidateCount + ...
                candidateIndex;
            fullMapProducts(outputIndex) = localBuildFullMapProduct( ...
                string(selectedRow.CpiLabel(1)), ...
                string(selectedRow.WindowLabel(1)), ...
                double(selectedRow.Repetition(1)), profile, mapProduct);
        end
        if resolvedOptions.RunPostHocSyntheticTargetEvidence
            evidenceContext = localBuildTargetEvidenceContext( ...
                selectedRow, mapProduct, profile, appliedCorrection, ...
                resolvedOptions);
            targetEvidence = helperAnalyzeSyntheticTargetEvidence( ...
                mapProduct.MapLinear, mapProduct.RawDelayAxis_s, ...
                mapProduct.RawDopplerAxis_Hz, ...
                resolvedOptions.SyntheticTruth, evidenceContext);
            targetEvidenceTable = [targetEvidenceTable; ...
                targetEvidence.TargetTable]; %#ok<AGROW>

            if isempty(targetRegionViews)
                targetRegionViews = targetEvidence.TargetRegionViews;
            else
                targetRegionViews = [targetRegionViews; ...
                    targetEvidence.TargetRegionViews]; %#ok<AGROW>
            end
        end
        [interpretationLabel, rationale] = localClassifyMapProduct( ...
            mapProduct, resolvedOptions);
        candidateProducts{candidateIndex} = mapProduct;
        metricIndex = metricIndex + 1;
        metricRows(metricIndex) = localBuildMetricRow(rowIndex, ...
            selectedRow, profile, mapProduct, appliedCorrection, ...
            interpretationLabel, rationale);
        residualIndex = residualIndex + 1;
        residualRows(residualIndex) = localBuildResidualRow(rowIndex, ...
            selectedRow, profile, residualInfo);

        if rowIndex == 1
            representativeMaps(candidateIndex) = ...
                localBuildRepresentativeMap(profile, selectedRow, ...
                mapProduct);
        end
    end

    localValidateCandidateCoordinates(candidateProducts, selectedRow);
    protectedRegion = localBuildProtectedRegion(candidateProducts{1}, ...
        productDefinition, resolvedOptions);

    for candidateIndex = 1:candidateCount
        protectedIndex = protectedIndex + 1;
        protectedRows(protectedIndex) = localBuildProtectedRow( ...
            rowIndex, selectedRow, candidateProfiles(candidateIndex), ...
            protectedRegion, candidateProducts{candidateIndex}, ...
            resolvedOptions);
    end
end

metricTable = struct2table(metricRows(1:metricIndex));
protectedDetailTable = struct2table(protectedRows(1:protectedIndex));
residualErrorPowerTable = struct2table(residualRows(1:residualIndex));

if ~isempty(targetEvidenceTable)
    targetEvidenceTable = localAddNoneCandidateChanges( ...
        targetEvidenceTable);
end

end

function output = localBuildFullMapProduct( ...
    cpiLabel, windowLabel, repetition, profile, mapProduct)

output = localFullMapProductTemplate();
output.CandidateName = string(profile.CandidateName);
output.CpiLabel = string(cpiLabel);
output.WindowLabel = string(windowLabel);
output.Repetition = double(repetition);
output.MapSampleRateHz = double(mapProduct.MapSampleRateHz);
output.AxisOrientation = string(mapProduct.AxisOrientation);
output.MapLinear = mapProduct.MapLinear;
output.DelayAxis_s = mapProduct.RawDelayAxis_s;
output.DopplerAxis_Hz = mapProduct.RawDopplerAxis_Hz;

end

function output = localFullMapProductTemplate()

output = struct( ...
    "CandidateName", "", ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "Repetition", NaN, ...
    "MapSampleRateHz", NaN, ...
    "AxisOrientation", "rows_doppler_columns_delay", ...
    "MapLinear", single.empty(0, 0), ...
    "DelayAxis_s", zeros(1, 0), ...
    "DopplerAxis_Hz", zeros(0, 1));

end

function context = localBuildTargetEvidenceContext(selectedRow, mapProduct, ...
    profile, appliedCorrection, resolvedOptions)

repetition = double(selectedRow.Repetition(1));
partStartOffsets_s = double( ...
    resolvedOptions.SyntheticTruth.part_start_offsets_s(:));

if repetition > numel(partStartOffsets_s)
    error("helperAnalyzeG5Mitigation:MissingTruthPartOffset", ...
        "Scenario truth has no start offset for repetition %d.", ...
        repetition);
end

context = struct();
context.CandidateName = string(profile.CandidateName);
context.Repetition = repetition;
context.CpiLabel = string(selectedRow.CpiLabel(1));
context.WindowLabel = string(selectedRow.WindowLabel(1));
context.NativeSampleRateHz = double(resolvedOptions.SampleRateHz);
context.MapSampleRateHz = double(resolvedOptions.MapSampleRateHz);
context.PartStartOffset_s = partStartOffsets_s(repetition);
context.CpiStart_s = (double(selectedRow.WindowStartSample(1)) - 1.0) ./ ...
    double(resolvedOptions.SampleRateHz);
context.CpiDuration_s = double(selectedRow.CpiDuration_s(1));
context.DirectPathDelay_s = double(mapProduct.DirectPathDelay_s);
context.DirectPathDoppler_Hz = double(mapProduct.DirectPathDoppler_Hz);
context.AppliedLag_samples = double(appliedCorrection.AppliedLag_samples);
context.AppliedResidualFrequency_Hz = ...
    double(appliedCorrection.AppliedResidualFrequency_Hz);
context.LagUncertainty_samples = ...
    double(resolvedOptions.TargetLagUncertainty_samples);
context.ResidualFrequencyUncertainty_Hz = ...
    double(resolvedOptions.TargetResidualFrequencyUncertainty_Hz);

end

function targetEvidenceTable = localAddNoneCandidateChanges( ...
    targetEvidenceTable)

for rowIndex = 1:height(targetEvidenceTable)
    row = targetEvidenceTable(rowIndex, :);
    baselineMask = ...
        targetEvidenceTable.CandidateName == "none" & ...
        targetEvidenceTable.Repetition == row.Repetition & ...
        targetEvidenceTable.CpiLabel == row.CpiLabel & ...
        targetEvidenceTable.WindowLabel == row.WindowLabel & ...
        targetEvidenceTable.SourceCaseId == row.SourceCaseId & ...
        targetEvidenceTable.TargetId == row.TargetId;
    baselineRow = targetEvidenceTable(baselineMask, :);

    if height(baselineRow) ~= 1
        error("helperAnalyzeG5Mitigation:MissingTargetBaseline", ...
            "Expected one no-mitigation baseline for target %s.", ...
            row.TargetId);
    end

    delayChange_s = row.AssociatedDelay_s - ...
        baselineRow.AssociatedDelay_s;
    dopplerChange_Hz = row.AssociatedDoppler_Hz - ...
        baselineRow.AssociatedDoppler_Hz;
    targetEvidenceTable.TargetLevelChangeFromNone_dB(rowIndex) = ...
        row.TargetLevel_dB - baselineRow.TargetLevel_dB;
    targetEvidenceTable.LocalProminenceChangeFromNone_dB(rowIndex) = ...
        row.LocalProminence_dB - baselineRow.LocalProminence_dB;
    targetEvidenceTable.DelayCoordinateChangeFromNone_samples(rowIndex) = ...
        delayChange_s ./ row.MapDelaySpacing_s;
    targetEvidenceTable.DopplerCoordinateChangeFromNone_Hz(rowIndex) = ...
        dopplerChange_Hz;
    targetEvidenceTable.CoordinateChangeFromNone_bins(rowIndex) = hypot( ...
        delayChange_s ./ row.MapDelaySpacing_s, ...
        dopplerChange_Hz ./ row.MapDopplerSpacing_Hz);
end

end

function localValidateCandidateCoordinates(candidateProducts, selectedRow)

referenceProduct = candidateProducts{1};

for idx = 2:numel(candidateProducts)
    candidateProduct = candidateProducts{idx};
    sameMapSize = isequal(size(candidateProduct.MapLinear), ...
        size(referenceProduct.MapLinear));
    sameDelayAxis = isequal(candidateProduct.RawDelayAxis_samples, ...
        referenceProduct.RawDelayAxis_samples);
    sameDopplerAxis = isequal(candidateProduct.RawDopplerAxis_Hz, ...
        referenceProduct.RawDopplerAxis_Hz);

    if ~(sameMapSize && sameDelayAxis && sameDopplerAxis)
        error("helperAnalyzeG5Mitigation:CandidateCoordinateMismatch", ...
            "G5 candidate maps differ in size or axes for repetition %d.", ...
            selectedRow.Repetition(1));
    end
end

end

function row = localMetricRowTemplate()

row = struct( ...
    "MapRowId", NaN, ...
    "CandidateName", "", ...
    "Repetition", NaN, ...
    "RelativePath", "", ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "WindowStartSample", NaN, ...
    "WindowIndex", NaN, ...
    "CpiDuration_s", NaN, ...
    "CpiSamples", NaN, ...
    "FullMapRows", NaN, ...
    "FullMapColumns", NaN, ...
    "MapFinite", false, ...
    "AxisOrientation", "", ...
    "DelayAxisStart_s", NaN, ...
    "DelayAxisEnd_s", NaN, ...
    "DelayAxisSpacing_s", NaN, ...
    "DopplerAxisStart_Hz", NaN, ...
    "DopplerAxisEnd_Hz", NaN, ...
    "DopplerAxisSpacing_Hz", NaN, ...
    "MapRateMode", "", ...
    "MapDecimationFactor", NaN, ...
    "MapSampleRateHz", NaN, ...
    "AppliedLag_samples", NaN, ...
    "AppliedResidualFrequency_Hz", NaN, ...
    "GlobalPeakDelay_samples", NaN, ...
    "GlobalPeakDoppler_Hz", NaN, ...
    "GlobalPeak_dB", NaN, ...
    "OriginNeighborhoodContainsGlobalPeak", false, ...
    "DirectPathDelay_samples", NaN, ...
    "DirectPathDoppler_Hz", NaN, ...
    "DirectPathPeak_dB", NaN, ...
    "DirectPathLocalProminence_dB", NaN, ...
    "DirectPathToClutter_dB", NaN, ...
    "DirectPathToFloor_dB", NaN, ...
    "OffOriginEnergyFraction", NaN, ...
    "OffOriginNonzeroDopplerEnergyFraction", NaN, ...
    "ZeroDopplerRidgeEnergyFraction", NaN, ...
    "OffOriginOccupiedFraction_abovePeakMinus20dB", NaN, ...
    "DirectPathToOffRidgeEnergy_dB", NaN, ...
    "OffOriginPeakToBackground_dB", NaN, ...
    "SceneObservabilityScore", NaN, ...
    "InterpretationLabel", "", ...
    "Rationale", "" ...
    );

end

function row = localBuildMetricRow(mapRowId, selectedRow, profile, ...
    mapProduct, appliedCorrection, interpretationLabel, rationale)

row = localMetricRowTemplate();
row.MapRowId = double(mapRowId);
row.CandidateName = string(profile.CandidateName);
row.Repetition = double(selectedRow.Repetition(1));
row.RelativePath = string(selectedRow.RelativePath(1));
row.CpiLabel = string(selectedRow.CpiLabel(1));
row.WindowLabel = string(selectedRow.WindowLabel(1));
row.WindowStartSample = double(selectedRow.WindowStartSample(1));
row.WindowIndex = double(selectedRow.WindowIndex(1));
row.CpiDuration_s = double(selectedRow.CpiDuration_s(1));
row.CpiSamples = double(selectedRow.CpiSamples(1));
row.FullMapRows = double(mapProduct.FullMapSize(1));
row.FullMapColumns = double(mapProduct.FullMapSize(2));
row.MapFinite = logical(mapProduct.MapFinite);
row.AxisOrientation = string(mapProduct.AxisOrientation);
row.DelayAxisStart_s = double(mapProduct.RawDelayAxis_s(1));
row.DelayAxisEnd_s = double(mapProduct.RawDelayAxis_s(end));
row.DelayAxisSpacing_s = median(diff( ...
    mapProduct.RawDelayAxis_s));
row.DopplerAxisStart_Hz = double(mapProduct.RawDopplerAxis_Hz(1));
row.DopplerAxisEnd_Hz = double(mapProduct.RawDopplerAxis_Hz(end));
row.DopplerAxisSpacing_Hz = median(diff( ...
    mapProduct.RawDopplerAxis_Hz));
row.MapRateMode = string(mapProduct.MapRateMode);
row.MapDecimationFactor = double(mapProduct.MapDecimationFactor);
row.MapSampleRateHz = double(mapProduct.MapSampleRateHz);
row.AppliedLag_samples = double(appliedCorrection.AppliedLag_samples);
row.AppliedResidualFrequency_Hz = ...
    double(appliedCorrection.AppliedResidualFrequency_Hz);
row.GlobalPeakDelay_samples = double(mapProduct.GlobalPeakDelay_samples);
row.GlobalPeakDoppler_Hz = double(mapProduct.GlobalPeakDoppler_Hz);
row.GlobalPeak_dB = double(mapProduct.GlobalPeak_dB);
row.OriginNeighborhoodContainsGlobalPeak = ...
    logical(mapProduct.OriginNeighborhoodContainsGlobalPeak);
row.DirectPathDelay_samples = double(mapProduct.DirectPathDelay_samples);
row.DirectPathDoppler_Hz = double(mapProduct.DirectPathDoppler_Hz);
row.DirectPathPeak_dB = double(mapProduct.DirectPathPeak_dB);
row.DirectPathLocalProminence_dB = ...
    double(mapProduct.DirectPathLocalProminence_dB);
row.DirectPathToClutter_dB = double(mapProduct.DirectPathToClutter_dB);
row.DirectPathToFloor_dB = double(mapProduct.DirectPathToFloor_dB);
row.OffOriginEnergyFraction = double(mapProduct.OffOriginEnergyFraction);
row.OffOriginNonzeroDopplerEnergyFraction = ...
    double(mapProduct.OffOriginNonzeroDopplerEnergyFraction);
row.ZeroDopplerRidgeEnergyFraction = ...
    double(mapProduct.ZeroDopplerRidgeEnergyFraction);
row.OffOriginOccupiedFraction_abovePeakMinus20dB = ...
    double(mapProduct.OffOriginOccupiedFraction_abovePeakMinus20dB);
row.DirectPathToOffRidgeEnergy_dB = ...
    double(mapProduct.DirectPathToOffRidgeEnergy_dB);
row.OffOriginPeakToBackground_dB = ...
    double(mapProduct.OffOriginPeakToBackground_dB);
row.SceneObservabilityScore = double(mapProduct.SceneObservabilityScore);
row.InterpretationLabel = string(interpretationLabel);
row.Rationale = string(rationale);

end

function row = localProtectedRowTemplate()

row = struct( ...
    "MapRowId", NaN, ...
    "CandidateName", "", ...
    "Repetition", NaN, ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "ProtectedRegionDefinition", "", ...
    "ProtectedCellCount", NaN, ...
    "BaselineProtectedPower", NaN, ...
    "CandidateProtectedPower", NaN, ...
    "ProtectedRetentionRatio", NaN, ...
    "ProtectedRetention_dB", NaN, ...
    "RetentionLabel", "", ...
    "Rationale", "" ...
    );

end

function row = localBuildProtectedRow(mapRowId, selectedRow, profile, ...
    protectedRegion, candidateProduct, resolvedOptions)

candidatePower = sum(candidateProduct.MapLinear(protectedRegion.Mask), ...
    "all");
baselinePower = max(protectedRegion.BaselineProtectedPower, ...
    eps("single"));
retentionRatio = max(double(candidatePower) ./ double(baselinePower), eps);
retention_dB = pow2db(retentionRatio);

if resolvedOptions.DataProfile == "synthetic"
    retentionLabel = "diagnostic_only_no_cutoff";
    rationale = "Synthetic protected-region retention is descriptive; " + ...
        "no target-retention cutoff is imposed.";
elseif string(profile.CandidateName) == "none"
    retentionLabel = "baseline_reference";
    rationale = "No mitigation defines the protected-region reference.";
elseif retentionRatio >= resolvedOptions.ProtectedRegionMinRetentionRatio
    retentionLabel = "retained";
    rationale = sprintf("Protected-region retention %.2f dB met the " + ...
        "minimum ratio %.3f.", retention_dB, ...
        resolvedOptions.ProtectedRegionMinRetentionRatio);
else
    retentionLabel = "over_cancel_risk";
    rationale = sprintf("Protected-region retention %.2f dB fell below " + ...
        "the minimum ratio %.3f.", retention_dB, ...
        resolvedOptions.ProtectedRegionMinRetentionRatio);
end

row = localProtectedRowTemplate();
row.MapRowId = double(mapRowId);
row.CandidateName = string(profile.CandidateName);
row.Repetition = double(selectedRow.Repetition(1));
row.CpiLabel = string(selectedRow.CpiLabel(1));
row.WindowLabel = string(selectedRow.WindowLabel(1));
row.ProtectedRegionDefinition = protectedRegion.Definition;
row.ProtectedCellCount = double(protectedRegion.CellCount);
row.BaselineProtectedPower = double(protectedRegion.BaselineProtectedPower);
row.CandidateProtectedPower = double(candidatePower);
row.ProtectedRetentionRatio = double(retentionRatio);
row.ProtectedRetention_dB = double(retention_dB);
row.RetentionLabel = retentionLabel;
row.Rationale = string(rationale);

end

function row = localResidualRowTemplate()

row = struct( ...
    "MapRowId", NaN, ...
    "CandidateName", "", ...
    "Repetition", NaN, ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "InputReferencePower_dB", NaN, ...
    "InputSurveillancePower_dB", NaN, ...
    "ModeledLeakagePower_dB", NaN, ...
    "ResidualErrorPower_dB", NaN, ...
    "ResidualToInputPower_dB", NaN, ...
    "FinalWeightsNorm", NaN, ...
    "LmsConvergedFinite", false ...
    );

end

function row = localBuildResidualRow(mapRowId, selectedRow, profile, ...
    residualInfo)

row = localResidualRowTemplate();
row.MapRowId = double(mapRowId);
row.CandidateName = string(profile.CandidateName);
row.Repetition = double(selectedRow.Repetition(1));
row.CpiLabel = string(selectedRow.CpiLabel(1));
row.WindowLabel = string(selectedRow.WindowLabel(1));
row.InputReferencePower_dB = localPowerToDb( ...
    residualInfo.InputReferencePower);
row.InputSurveillancePower_dB = localPowerToDb( ...
    residualInfo.InputSurveillancePower);
row.ModeledLeakagePower_dB = localPowerToDb( ...
    residualInfo.ModeledLeakagePower);
row.ResidualErrorPower_dB = localPowerToDb( ...
    residualInfo.ResidualErrorPower);
row.ResidualToInputPower_dB = pow2db(max( ...
    double(residualInfo.ResidualErrorPower) ./ ...
    max(double(residualInfo.InputSurveillancePower), eps), eps));
row.FinalWeightsNorm = double(residualInfo.FinalWeightsNorm);
row.LmsConvergedFinite = logical(residualInfo.LmsConvergedFinite);

end

function [candidateSurveillance, residualInfo] = localApplyCandidate( ...
    referenceWindow, surveillanceWindow, profile)

referenceWindow = referenceWindow(:);
surveillanceWindow = surveillanceWindow(:);
residualInfo = struct();
residualInfo.InputReferencePower = mean(abs(referenceWindow) .^ 2, ...
    "omitnan");
residualInfo.InputSurveillancePower = mean(abs(surveillanceWindow) .^ 2, ...
    "omitnan");

if string(profile.CandidateName) == "none"
    modeledLeakage = zeros(size(surveillanceWindow), "like", ...
        surveillanceWindow);
    residualError = surveillanceWindow;
    weights = zeros(0, 1);
else
    lmsFilter = dsp.LMSFilter( ...
        "Method", char(profile.LmsMethod), ...
        "Length", round(double(profile.FilterLength)), ...
        "StepSize", double(profile.StepSize), ...
        "LeakageFactor", double(profile.LeakageFactor));
    [modeledLeakage, residualError, weights] = lmsFilter( ...
        referenceWindow, surveillanceWindow);
end

candidateSurveillance = single(residualError(:));
residualInfo.ModeledLeakagePower = mean(abs(modeledLeakage) .^ 2, ...
    "omitnan");
residualInfo.ResidualErrorPower = mean(abs(residualError) .^ 2, ...
    "omitnan");
residualInfo.FinalWeightsNorm = norm(double(weights(:)));
residualInfo.LmsConvergedFinite = all(isfinite(residualError), "all") && ...
    all(isfinite(weights), "all");

end

function cpiDefinition = localBuildCpiDefinition(selectedRow)

cpiDuration_s = double(selectedRow.CpiDuration_s(1));
cpiDefinition = struct();
cpiDefinition.Label = string(selectedRow.CpiLabel(1));
cpiDefinition.Duration_s = cpiDuration_s;
cpiDefinition.MapSamples = double(selectedRow.CpiSamples(1));
cpiDefinition.PRFVector_Hz = [1.0 ./ cpiDuration_s, ...
    1.0 ./ cpiDuration_s];

end

function mapProduct = localBuildMapProduct(referenceWindow, ...
    surveillanceWindow, cpiDefinition, productDefinition, resolvedOptions)

[mapMagnitude, delayAxis_s, dopplerAxis_Hz] = ambgfun( ...
    referenceWindow, surveillanceWindow, resolvedOptions.MapSampleRateHz, ...
    cpiDefinition.PRFVector_Hz);
mapLinear = max(single(mapMagnitude) .^ 2, eps("single"));
delayAxis_s = double(delayAxis_s(:).');
dopplerAxis_Hz = double(dopplerAxis_Hz(:));

if size(mapLinear, 1) ~= numel(dopplerAxis_Hz) || ...
        size(mapLinear, 2) ~= numel(delayAxis_s)
    error("helperAnalyzeG5Mitigation:MapAxisMismatch", ...
        "Map rows must match Doppler and columns must match delay.");
end

if any(~isfinite(mapLinear), "all") || ...
        any(~isfinite(delayAxis_s)) || any(~isfinite(dopplerAxis_Hz)) || ...
        any(diff(delayAxis_s) <= 0) || any(diff(dopplerAxis_Hz) <= 0)
    error("helperAnalyzeG5Mitigation:InvalidMapIntegrity", ...
        "The ambiguity map and axes must be finite and increasing.");
end

delayAxis_samples = delayAxis_s .* resolvedOptions.MapSampleRateHz;
[globalPeakPower, globalPeakIndex] = max(mapLinear, [], "all");
[globalPeakRow, globalPeakCol] = ind2sub(size(mapLinear), ...
    globalPeakIndex);
globalPeakDelay_samples = delayAxis_samples(globalPeakCol);
globalPeakDoppler_Hz = dopplerAxis_Hz(globalPeakRow);
originMask = localBuildOriginMask(delayAxis_samples, dopplerAxis_Hz, ...
    productDefinition);
originCandidateIndices = find(originMask);

if isempty(originCandidateIndices)
    error("helperAnalyzeG5Mitigation:EmptyOriginSearchMask", ...
        "The G5 origin-search mask is empty for CPI %s.", ...
        cpiDefinition.Label);
end

[directPathPower, originPeakIndex] = max(mapLinear(originMask));
directPathIndex = originCandidateIndices(originPeakIndex);
[directPathRow, directPathCol] = ind2sub(size(mapLinear), ...
    directPathIndex);
directPathDelay_samples = delayAxis_samples(directPathCol);
directPathDoppler_Hz = dopplerAxis_Hz(directPathRow);
localAnnulusValues = localBuildLocalAnnulus(mapLinear, directPathRow, ...
    directPathCol, resolvedOptions.LocalProminenceOuterRadius_bins);
clutterValues = localBuildClutterValues(mapLinear, delayAxis_samples, ...
    dopplerAxis_Hz, directPathDelay_samples, ...
    productDefinition.ExclusionDelayRadius_samples);
backgroundValues = localBuildBackgroundValues(mapLinear, ...
    delayAxis_samples, dopplerAxis_Hz, productDefinition);
directPathExclusionMask = localBuildDirectPathExclusionMask( ...
    delayAxis_samples, dopplerAxis_Hz, directPathDelay_samples, ...
    directPathDoppler_Hz, productDefinition);
offOriginMask = ~directPathExclusionMask;
zeroDopplerRidgeMask = repmat(abs(dopplerAxis_Hz) <= ...
    productDefinition.ZeroDopplerRidgeExclusion_Hz, ...
    1, numel(delayAxis_samples));
offOriginNonzeroDopplerMask = offOriginMask & ~zeroDopplerRidgeMask;
totalMapPower = max(sum(mapLinear, "all"), eps("single"));
offOriginValues = double(mapLinear(offOriginNonzeroDopplerMask));
offOriginEnergyFraction = double(sum(mapLinear( ...
    offOriginNonzeroDopplerMask), "all") ./ totalMapPower);
zeroDopplerEnergyFraction = double(sum(mapLinear( ...
    zeroDopplerRidgeMask), "all") ./ totalMapPower);
occupiedThreshold = max(single(directPathPower) .* single(10.0 .^ ...
    (resolvedOptions.ProtectedRegionThresholdRelativeToDirectPath_dB ./ ...
    10.0)), eps("single"));

if nnz(offOriginNonzeroDopplerMask) == 0
    occupiedFraction = 0.0;
else
    occupiedFraction = double(nnz(mapLinear( ...
        offOriginNonzeroDopplerMask) >= occupiedThreshold) ./ ...
        nnz(offOriginNonzeroDopplerMask));
end

if isempty(offOriginValues)
    offOriginValues = eps;
end

directPathToOffRidge_dB = pow2db(double(directPathPower) ./ ...
    max(median(offOriginValues, "omitnan"), eps));
offOriginPeakToBackground_dB = pow2db(max(max(offOriginValues), eps) ./ ...
    max(median(backgroundValues, "omitnan"), eps));
sceneScore = localComputeSceneScore(offOriginEnergyFraction, ...
    occupiedFraction, zeroDopplerEnergyFraction, ...
    directPathToOffRidge_dB, resolvedOptions);
reviewLinearMap = single(imresize(mapLinear, ...
    [resolvedOptions.ReviewMapRows, resolvedOptions.ReviewMapCols], ...
    "bilinear"));
reviewDelayAxis_samples = linspace(delayAxis_samples(1), ...
    delayAxis_samples(end), resolvedOptions.ReviewMapCols);
reviewDopplerAxis_Hz = linspace(dopplerAxis_Hz(1), ...
    dopplerAxis_Hz(end), resolvedOptions.ReviewMapRows).';

mapProduct = struct();
mapProduct.MapRateMode = string(resolvedOptions.MapRateMode);
mapProduct.MapDecimationFactor = ...
    double(resolvedOptions.MapDecimationFactor);
mapProduct.MapSampleRateHz = double(resolvedOptions.MapSampleRateHz);
mapProduct.FullMapSize = double(size(mapLinear));
mapProduct.MapFinite = true;
mapProduct.AxisOrientation = "rows_doppler_columns_delay";
mapProduct.MapLinear = mapLinear;
mapProduct.RawDelayAxis_s = delayAxis_s;
mapProduct.RawDelayAxis_samples = delayAxis_samples;
mapProduct.RawDopplerAxis_Hz = dopplerAxis_Hz;
mapProduct.GlobalPeakDelay_samples = double(globalPeakDelay_samples);
mapProduct.GlobalPeakDoppler_Hz = double(globalPeakDoppler_Hz);
mapProduct.GlobalPeak_dB = pow2db(double(globalPeakPower));
mapProduct.OriginNeighborhoodContainsGlobalPeak = ...
    logical(originMask(globalPeakIndex));
mapProduct.DirectPathDelay_samples = double(directPathDelay_samples);
mapProduct.DirectPathDelay_s = double(directPathDelay_samples) ./ ...
    double(resolvedOptions.MapSampleRateHz);
mapProduct.DirectPathDoppler_Hz = double(directPathDoppler_Hz);
mapProduct.DirectPathPower = single(directPathPower);
mapProduct.DirectPathPeak_dB = pow2db(double(directPathPower));
mapProduct.DirectPathLocalProminence_dB = pow2db( ...
    double(directPathPower) ./ max(double(max(localAnnulusValues)), eps));
mapProduct.DirectPathToClutter_dB = pow2db(double(directPathPower) ./ ...
    max(double(median(clutterValues, "omitnan")), eps));
mapProduct.DirectPathToFloor_dB = pow2db(double(directPathPower) ./ ...
    max(double(median(backgroundValues, "omitnan")), eps));
mapProduct.OffOriginEnergyFraction = double(sum(mapLinear( ...
    offOriginMask), "all") ./ totalMapPower);
mapProduct.OffOriginNonzeroDopplerEnergyFraction = ...
    offOriginEnergyFraction;
mapProduct.ZeroDopplerRidgeEnergyFraction = zeroDopplerEnergyFraction;
mapProduct.OffOriginOccupiedFraction_abovePeakMinus20dB = ...
    occupiedFraction;
mapProduct.DirectPathToOffRidgeEnergy_dB = ...
    double(directPathToOffRidge_dB);
mapProduct.OffOriginPeakToBackground_dB = ...
    double(offOriginPeakToBackground_dB);
mapProduct.SceneObservabilityScore = double(sceneScore);
mapProduct.OffOriginNonzeroDopplerMask = offOriginNonzeroDopplerMask;
mapProduct.ZeroDopplerRidgeMask = zeroDopplerRidgeMask;
reviewMagnitude = sqrt(max(reviewLinearMap, eps("single")));
mapProduct.ReviewMap_dB = max(mag2db(reviewMagnitude), ...
    resolvedOptions.FigureFloor_dB);
mapProduct.ReviewDelayAxis_samples = reviewDelayAxis_samples;
mapProduct.ReviewDopplerAxis_Hz = reviewDopplerAxis_Hz;

end

function originMask = localBuildOriginMask(delayAxis_samples, ...
    dopplerAxis_Hz, productDefinition)

delayMask = abs(delayAxis_samples) <= ...
    productDefinition.OriginSearchDelayRadius_samples;
dopplerMask = abs(dopplerAxis_Hz) <= ...
    productDefinition.OriginSearchDopplerRadius_Hz;
originMask = logical(dopplerMask & delayMask);

end

function exclusionMask = localBuildDirectPathExclusionMask( ...
    delayAxis_samples, dopplerAxis_Hz, directPathDelay_samples, ...
    directPathDoppler_Hz, productDefinition)

delayMask = abs(delayAxis_samples - directPathDelay_samples) <= ...
    productDefinition.ExclusionDelayRadius_samples;
dopplerMask = abs(dopplerAxis_Hz - directPathDoppler_Hz) <= ...
    productDefinition.ExclusionDopplerRadius_Hz;
exclusionMask = logical(dopplerMask & delayMask);

end

function exclusionMask = localBuildOriginExclusionMask(delayAxis_samples, ...
    dopplerAxis_Hz, productDefinition)

delayMask = abs(delayAxis_samples) <= ...
    productDefinition.ExclusionDelayRadius_samples;
dopplerMask = abs(dopplerAxis_Hz) <= ...
    productDefinition.ExclusionDopplerRadius_Hz;
exclusionMask = logical(dopplerMask & delayMask);

end

function annulusValues = localBuildLocalAnnulus(mapLinear, ...
    directPathRow, directPathCol, radiusBins)

radiusBins = round(double(radiusBins));
rowIndices = max(1, directPathRow - radiusBins): ...
    min(size(mapLinear, 1), directPathRow + radiusBins);
colIndices = max(1, directPathCol - radiusBins): ...
    min(size(mapLinear, 2), directPathCol + radiusBins);
[columnGrid, rowGrid] = meshgrid(colIndices, rowIndices);
distanceGrid = max(abs(rowGrid - directPathRow), ...
    abs(columnGrid - directPathCol));
annulusMask = distanceGrid >= 2 & distanceGrid <= radiusBins;
localPatch = mapLinear(rowIndices, colIndices);
annulusValues = double(localPatch(annulusMask));

if isempty(annulusValues)
    annulusValues = double(mapLinear(:));
end

end

function clutterValues = localBuildClutterValues(mapLinear, ...
    delayAxis_samples, dopplerAxis_Hz, directPathDelay_samples, ...
    exclusionDelayRadius_samples)

delayMask = abs(delayAxis_samples - directPathDelay_samples) <= ...
    exclusionDelayRadius_samples;
dopplerMask = abs(dopplerAxis_Hz) <= 25.0;
clutterMask = dopplerMask & ~delayMask;
clutterValues = double(mapLinear(clutterMask));

if isempty(clutterValues)
    clutterValues = double(mapLinear(:));
end

end

function backgroundValues = localBuildBackgroundValues(mapLinear, ...
    delayAxis_samples, dopplerAxis_Hz, productDefinition)

backgroundMask = ~localBuildOriginExclusionMask(delayAxis_samples, ...
    dopplerAxis_Hz, productDefinition) & ...
    abs(dopplerAxis_Hz) > productDefinition.ZeroDopplerRidgeExclusion_Hz;
backgroundValues = double(mapLinear(backgroundMask));

if isempty(backgroundValues)
    backgroundValues = double(mapLinear(:));
end

end

function score = localComputeSceneScore(offOriginEnergyFraction, ...
    occupiedFraction, zeroDopplerEnergyFraction, directPathToOffRidge_dB, ...
    resolvedOptions)

score = ...
    resolvedOptions.SceneScoreOffOriginEnergyWeight .* ...
    double(offOriginEnergyFraction) + ...
    resolvedOptions.SceneScoreOccupiedFractionWeight .* ...
    double(occupiedFraction) - ...
    resolvedOptions.SceneScoreZeroDopplerPenaltyWeight .* ...
    double(zeroDopplerEnergyFraction) - ...
    resolvedOptions.SceneScoreDirectPathDominancePenaltyWeight .* ...
    max(double(directPathToOffRidge_dB) - ...
    resolvedOptions.SceneScoreDirectPathDominanceReference_dB, 0.0);

end

function [label, rationale] = localClassifyMapProduct(mapProduct, ...
    resolvedOptions)

if ~mapProduct.OriginNeighborhoodContainsGlobalPeak
    label = "implementation_suspect";
    rationale = "Global peak did not stay inside the origin neighborhood.";
    return
end

sceneReviewable = mapProduct.OffOriginNonzeroDopplerEnergyFraction >= ...
    resolvedOptions.SceneCaveatedOffOriginNonzeroDopplerEnergyFraction && ...
    mapProduct.OffOriginOccupiedFraction_abovePeakMinus20dB >= ...
    resolvedOptions.SceneCaveatedOffOriginOccupiedFraction && ...
    mapProduct.ZeroDopplerRidgeEnergyFraction <= ...
    resolvedOptions.SceneCaveatedMaxZeroDopplerRidgeEnergyFraction && ...
    mapProduct.DirectPathToOffRidgeEnergy_dB <= ...
    resolvedOptions.SceneCaveatedMaxDirectPathToOffRidgeEnergy_dB;

if sceneReviewable
    label = "reviewable_scene_present";
else
    label = "scene_limited_direct_path_dominated";
end

rationale = sprintf("off_origin=%.3f | occupied_minus20dB=%.4f | " + ...
    "zero_doppler=%.3f | direct_path_to_off_ridge=%.2f dB", ...
    mapProduct.OffOriginNonzeroDopplerEnergyFraction, ...
    mapProduct.OffOriginOccupiedFraction_abovePeakMinus20dB, ...
    mapProduct.ZeroDopplerRidgeEnergyFraction, ...
    mapProduct.DirectPathToOffRidgeEnergy_dB);

end

function protectedRegion = localBuildProtectedRegion(baselineProduct, ...
    productDefinition, resolvedOptions)

candidateMask = baselineProduct.OffOriginNonzeroDopplerMask & ...
    ~baselineProduct.ZeroDopplerRidgeMask;
threshold = max(baselineProduct.DirectPathPower .* single(10.0 .^ ...
    (resolvedOptions.ProtectedRegionThresholdRelativeToDirectPath_dB ./ ...
    10.0)), eps("single"));
protectedMask = candidateMask & baselineProduct.MapLinear >= threshold;
definition = ...
    "baseline_off_origin_nonzero_doppler_above_peak_minus_20db";

if nnz(protectedMask) == 0
    protectedMask = candidateMask;
    definition = ...
        "baseline_off_origin_nonzero_doppler_floor_region_no_occupied_cells";
end

if nnz(protectedMask) == 0
    protectedMask = ~localBuildOriginExclusionMask( ...
        baselineProduct.RawDelayAxis_samples, ...
        baselineProduct.RawDopplerAxis_Hz, productDefinition);
    definition = "fallback_non_direct_path_region";
end

protectedRegion = struct();
protectedRegion.Mask = protectedMask;
protectedRegion.Definition = definition;
protectedRegion.CellCount = nnz(protectedMask);
protectedRegion.BaselineProtectedPower = max(sum( ...
    baselineProduct.MapLinear(protectedMask), "all"), eps("single"));

end

function representativeMap = localBuildRepresentativeMap(profile, ...
    selectedRow, mapProduct)

representativeMap = localRepresentativeMapTemplate();
representativeMap.CandidateName = string(profile.CandidateName);
representativeMap.CpiLabel = string(selectedRow.CpiLabel(1));
representativeMap.WindowLabel = string(selectedRow.WindowLabel(1));
representativeMap.RepresentativeRepetition = ...
    double(selectedRow.Repetition(1));
representativeMap.Map_dB = mapProduct.ReviewMap_dB;
representativeMap.DelayAxis_samples = mapProduct.ReviewDelayAxis_samples;
representativeMap.DopplerAxis_Hz = mapProduct.ReviewDopplerAxis_Hz;
representativeMap.DirectPathDelay_samples = ...
    mapProduct.DirectPathDelay_samples;
representativeMap.DirectPathDoppler_Hz = ...
    mapProduct.DirectPathDoppler_Hz;
representativeMap.DisplayDelayAxis_samples = ...
    representativeMap.DelayAxis_samples - ...
    representativeMap.DirectPathDelay_samples;
representativeMap.DisplayDopplerAxis_Hz = ...
    representativeMap.DopplerAxis_Hz - ...
    representativeMap.DirectPathDoppler_Hz;

end

function representativeMap = localRepresentativeMapTemplate()

representativeMap = struct( ...
    "CandidateName", "", ...
    "CpiLabel", "", ...
    "WindowLabel", "", ...
    "RepresentativeRepetition", NaN, ...
    "Map_dB", single([]), ...
    "DelayAxis_samples", [], ...
    "DisplayDelayAxis_samples", [], ...
    "DopplerAxis_Hz", [], ...
    "DisplayDopplerAxis_Hz", [], ...
    "DirectPathDelay_samples", NaN, ...
    "DirectPathDoppler_Hz", NaN ...
    );

end

function summaryTable = localBuildSuppressionSummary(metricTable, ...
    candidateProfiles)

rows = repmat(localSuppressionRowTemplate(), numel(candidateProfiles), 1);

for idx = 1:numel(candidateProfiles)
    candidateName = string(candidateProfiles(idx).CandidateName);
    candidateRows = metricTable(metricTable.CandidateName == ...
        candidateName, :);
    baselineRows = localMatchBaselineRows(metricTable, candidateRows);
    directPathSuppression = baselineRows.DirectPathPeak_dB - ...
        candidateRows.DirectPathPeak_dB;
    zeroDopplerReduction = ...
        baselineRows.ZeroDopplerRidgeEnergyFraction - ...
        candidateRows.ZeroDopplerRidgeEnergyFraction;
    offOriginDelta = ...
        candidateRows.OffOriginNonzeroDopplerEnergyFraction - ...
        baselineRows.OffOriginNonzeroDopplerEnergyFraction;
    occupiedDelta = ...
        candidateRows.OffOriginOccupiedFraction_abovePeakMinus20dB - ...
        baselineRows.OffOriginOccupiedFraction_abovePeakMinus20dB;
    sceneScoreDelta = candidateRows.SceneObservabilityScore - ...
        baselineRows.SceneObservabilityScore;
    rows(idx) = struct( ...
        "CandidateName", candidateName, ...
        "MapRowCount", height(candidateRows), ...
        "MedianDirectPathPeak_dB", median( ...
        candidateRows.DirectPathPeak_dB, "omitnan"), ...
        "MedianDirectPathSuppression_dB", median( ...
        directPathSuppression, "omitnan"), ...
        "MedianZeroDopplerRidgeEnergyFraction", median( ...
        candidateRows.ZeroDopplerRidgeEnergyFraction, "omitnan"), ...
        "MedianZeroDopplerRidgeReduction", median( ...
        zeroDopplerReduction, "omitnan"), ...
        "MedianOffOriginNonzeroDopplerEnergyFraction", median( ...
        candidateRows.OffOriginNonzeroDopplerEnergyFraction, ...
        "omitnan"), ...
        "MedianOffOriginEnergyFractionDelta", median( ...
        offOriginDelta, "omitnan"), ...
        "MedianOffOriginOccupiedFractionDelta", median( ...
        occupiedDelta, "omitnan"), ...
        "MedianDirectPathToOffRidgeEnergy_dB", median( ...
        candidateRows.DirectPathToOffRidgeEnergy_dB, "omitnan"), ...
        "MedianSceneScoreDelta", median(sceneScoreDelta, "omitnan"), ...
        "MedianOffOriginPeakToBackground_dB", median( ...
        candidateRows.OffOriginPeakToBackground_dB, "omitnan") ...
        );
end

summaryTable = struct2table(rows);

end

function row = localSuppressionRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "MapRowCount", NaN, ...
    "MedianDirectPathPeak_dB", NaN, ...
    "MedianDirectPathSuppression_dB", NaN, ...
    "MedianZeroDopplerRidgeEnergyFraction", NaN, ...
    "MedianZeroDopplerRidgeReduction", NaN, ...
    "MedianOffOriginNonzeroDopplerEnergyFraction", NaN, ...
    "MedianOffOriginEnergyFractionDelta", NaN, ...
    "MedianOffOriginOccupiedFractionDelta", NaN, ...
    "MedianDirectPathToOffRidgeEnergy_dB", NaN, ...
    "MedianSceneScoreDelta", NaN, ...
    "MedianOffOriginPeakToBackground_dB", NaN ...
    );

end

function baselineRows = localMatchBaselineRows(metricTable, candidateRows)

baselineRowsAll = metricTable(metricTable.CandidateName == "none", :);
[isMember, baselineIndex] = ismember(candidateRows.MapRowId, ...
    baselineRowsAll.MapRowId);

if ~all(isMember)
    error("helperAnalyzeG5Mitigation:MissingBaselineRows", ...
        "Every candidate row must have a no-mitigation baseline row.");
end

baselineRows = baselineRowsAll(baselineIndex, :);

end

function summaryTable = localBuildProtectedRetentionSummary( ...
    protectedDetailTable, candidateProfiles, resolvedOptions)

rows = repmat(localProtectedSummaryRowTemplate(), ...
    numel(candidateProfiles), 1);

for idx = 1:numel(candidateProfiles)
    candidateName = string(candidateProfiles(idx).CandidateName);
    candidateRows = protectedDetailTable( ...
        protectedDetailTable.CandidateName == candidateName, :);
    retentionRatio = candidateRows.ProtectedRetentionRatio;
    belowBudgetCount = sum(retentionRatio < ...
        resolvedOptions.ProtectedRegionMinRetentionRatio);
    minimumRequiredRetentionRatio = ...
        double(resolvedOptions.ProtectedRegionMinRetentionRatio);

    if resolvedOptions.DataProfile == "synthetic"
        belowBudgetCount = 0;
        minimumRequiredRetentionRatio = NaN;
        retentionLabel = "diagnostic_only_no_cutoff";
    elseif candidateName == "none"
        retentionLabel = "baseline_reference";
    elseif belowBudgetCount == 0
        retentionLabel = "retained";
    else
        retentionLabel = "over_cancel_risk";
    end

    rows(idx) = struct( ...
        "CandidateName", candidateName, ...
        "ProtectedRegionDefinition", strjoin(unique( ...
        candidateRows.ProtectedRegionDefinition), " | "), ...
        "EvaluatedRows", height(candidateRows), ...
        "MedianProtectedRetentionRatio", median(retentionRatio, ...
        "omitnan"), ...
        "MinimumProtectedRetentionRatio", min(retentionRatio), ...
        "MedianProtectedRetention_dB", median( ...
        candidateRows.ProtectedRetention_dB, "omitnan"), ...
        "RowsBelowRetentionBudget", double(belowBudgetCount), ...
        "RetentionLabel", retentionLabel, ...
        "MinRequiredRetentionRatio", minimumRequiredRetentionRatio ...
        );
end

summaryTable = struct2table(rows);

end

function row = localProtectedSummaryRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "ProtectedRegionDefinition", "", ...
    "EvaluatedRows", NaN, ...
    "MedianProtectedRetentionRatio", NaN, ...
    "MinimumProtectedRetentionRatio", NaN, ...
    "MedianProtectedRetention_dB", NaN, ...
    "RowsBelowRetentionBudget", NaN, ...
    "RetentionLabel", "", ...
    "MinRequiredRetentionRatio", NaN ...
    );

end

function proxyTable = localBuildDetectabilityProxyTable(metricTable, ...
    protectedRetentionTable, candidateProfiles, resolvedOptions)

rows = repmat(localDetectabilityRowTemplate(), numel(candidateProfiles), 1);

for idx = 1:numel(candidateProfiles)
    candidateName = string(candidateProfiles(idx).CandidateName);
    candidateRows = metricTable(metricTable.CandidateName == ...
        candidateName, :);
    baselineRows = localMatchBaselineRows(metricTable, candidateRows);
    protectedRow = protectedRetentionTable( ...
        protectedRetentionTable.CandidateName == candidateName, :);
    sceneScoreDelta = candidateRows.SceneObservabilityScore - ...
        baselineRows.SceneObservabilityScore;
    contrastDelta = candidateRows.OffOriginPeakToBackground_dB - ...
        baselineRows.OffOriginPeakToBackground_dB;
    directPathSuppression = baselineRows.DirectPathPeak_dB - ...
        candidateRows.DirectPathPeak_dB;
    offOriginDelta = ...
        candidateRows.OffOriginNonzeroDopplerEnergyFraction - ...
        baselineRows.OffOriginNonzeroDopplerEnergyFraction;
    occupiedDelta = ...
        candidateRows.OffOriginOccupiedFraction_abovePeakMinus20dB - ...
        baselineRows.OffOriginOccupiedFraction_abovePeakMinus20dB;
    proxyLabel = localResolveProxyLabel(candidateName, ...
        median(sceneScoreDelta, "omitnan"), ...
        median(contrastDelta, "omitnan"), ...
        median(directPathSuppression, "omitnan"), ...
        median(offOriginDelta, "omitnan"), ...
        median(occupiedDelta, "omitnan"), ...
        protectedRow.RetentionLabel(1), resolvedOptions);
    rows(idx) = struct( ...
        "CandidateName", candidateName, ...
        "MedianSceneScore", median( ...
        candidateRows.SceneObservabilityScore, "omitnan"), ...
        "MedianSceneScoreDelta", median(sceneScoreDelta, "omitnan"), ...
        "MedianOffOriginPeakToBackground_dB", median( ...
        candidateRows.OffOriginPeakToBackground_dB, "omitnan"), ...
        "MedianOffOriginPeakToBackgroundDelta_dB", median( ...
        contrastDelta, "omitnan"), ...
        "MedianDirectPathSuppression_dB", median( ...
        directPathSuppression, "omitnan"), ...
        "MedianOffOriginEnergyFractionDelta", median( ...
        offOriginDelta, "omitnan"), ...
        "MedianOffOriginOccupiedFractionDelta", median( ...
        occupiedDelta, "omitnan"), ...
        "MedianProtectedRetentionRatio", ...
        protectedRow.MedianProtectedRetentionRatio(1), ...
        "DetectabilityProxyLabel", proxyLabel ...
        );
end

proxyTable = struct2table(rows);

end

function row = localDetectabilityRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "MedianSceneScore", NaN, ...
    "MedianSceneScoreDelta", NaN, ...
    "MedianOffOriginPeakToBackground_dB", NaN, ...
    "MedianOffOriginPeakToBackgroundDelta_dB", NaN, ...
    "MedianDirectPathSuppression_dB", NaN, ...
    "MedianOffOriginEnergyFractionDelta", NaN, ...
    "MedianOffOriginOccupiedFractionDelta", NaN, ...
    "MedianProtectedRetentionRatio", NaN, ...
    "DetectabilityProxyLabel", "" ...
    );

end

function label = localResolveProxyLabel(candidateName, sceneScoreDelta, ...
    contrastDelta_dB, directPathSuppression_dB, offOriginDelta, ...
    occupiedDelta, retentionLabel, resolvedOptions)

if candidateName == "none"
    label = "baseline_reference";
    return
end

if retentionLabel == "over_cancel_risk"
    label = "not_usable_over_cancel";
    return
end

suppressionImproved = directPathSuppression_dB >= ...
    resolvedOptions.DirectPathSuppressionForCandidate_dB;
sceneImproved = sceneScoreDelta >= ...
    resolvedOptions.SceneScoreImprovementForReveal || ...
    offOriginDelta >= ...
    resolvedOptions.OffOriginEnergyImprovementForReveal || ...
    occupiedDelta >= ...
    resolvedOptions.OffOriginOccupiedImprovementForReveal;

if suppressionImproved && sceneImproved
    label = "proxy_improved";
elseif suppressionImproved && contrastDelta_dB > 0.0
    label = "visual_or_leakage_only";
elseif sceneScoreDelta < 0.0
    label = "proxy_worse";
else
    label = "no_material_change";
end

end

function caveatTable = localBuildUpstreamCaveatTable(g3SyncResults, ...
    g4Analysis)

sourceGate = "G2_RF_Health";
caveatCode = "g2_dataset_rf_caveat_carried_forward";
caveatLabel = "carried_forward";
rationale = "Current project status keeps G2/G3/G4 caveats visible to G5.";

g3OverallLabel = localResolveStructStringField(g3SyncResults, ...
    "OverallLabel");

if strlength(g3OverallLabel) == 0 && isfield(g3SyncResults, ...
        "Interpretation")
    g3OverallLabel = localResolveStructStringField( ...
        g3SyncResults.Interpretation, "OverallLabel");
end

if strlength(g3OverallLabel) > 0 && g3OverallLabel ~= "ready"
    sourceGate(end + 1, 1) = "G3_Sync";
    caveatCode(end + 1, 1) = "g3_overall_" + g3OverallLabel;
    caveatLabel(end + 1, 1) = g3OverallLabel;
    rationale(end + 1, 1) = "G3 overall label carried into G5.";
end

g4OverallLabel = localResolveG4Label(g4Analysis, "OverallLabel");
sourceGate(end + 1, 1) = "G4_Passive_Baseline_Map";
caveatCode(end + 1, 1) = "g4_overall_" + g4OverallLabel;
caveatLabel(end + 1, 1) = g4OverallLabel;
rationale(end + 1, 1) = string(g4Analysis.Interpretation.OverallRationale);

if isfield(g4Analysis.Interpretation, "CaveatCodes")
    g4Caveats = string(g4Analysis.Interpretation.CaveatCodes(:));
    g4CaveatCount = numel(g4Caveats);

    if g4CaveatCount > 0
        sourceGate = [sourceGate; repmat("G4_Passive_Baseline_Map", ...
            g4CaveatCount, 1)];
        caveatCode = [caveatCode; g4Caveats];
        caveatLabel = [caveatLabel; repmat("caveat_code", ...
            g4CaveatCount, 1)];
        rationale = [rationale; repmat("G4 caveat code carried forward.", ...
            g4CaveatCount, 1)];
    end
end

caveatTable = table(sourceGate, caveatCode, caveatLabel, rationale, ...
    VariableNames = {'SourceGate', 'CaveatCode', 'CaveatLabel', ...
    'Rationale'});

end

function causalTable = localBuildCausalAssessmentTable( ...
    suppressionTable, protectedTable, proxyTable, caveatTable, ...
    candidateProfiles, resolvedOptions)

rows = repmat(localCausalRowTemplate(), numel(candidateProfiles), 1);
rateCaveated = any(contains(caveatTable.CaveatCode, ...
    "rate", IgnoreCase = true));

for idx = 1:numel(candidateProfiles)
    candidateName = string(candidateProfiles(idx).CandidateName);
    suppressionRow = suppressionTable(suppressionTable.CandidateName == ...
        candidateName, :);
    protectedRow = protectedTable(protectedTable.CandidateName == ...
        candidateName, :);
    proxyRow = proxyTable(proxyTable.CandidateName == candidateName, :);
    [causalLabel, rateImpactLabel, rationale] = ...
        localResolveCausalLabel(candidateName, suppressionRow, ...
        protectedRow, proxyRow, rateCaveated, resolvedOptions);
    rows(idx) = struct( ...
        "CandidateName", candidateName, ...
        "CausalLabel", causalLabel, ...
        "RateAgreementImpactLabel", rateImpactLabel, ...
        "DirectPathSuppression_dB", ...
        suppressionRow.MedianDirectPathSuppression_dB(1), ...
        "SceneScoreDelta", proxyRow.MedianSceneScoreDelta(1), ...
        "ProtectedRetentionRatio", ...
        protectedRow.MedianProtectedRetentionRatio(1), ...
        "DetectabilityProxyLabel", proxyRow.DetectabilityProxyLabel(1), ...
        "Rationale", rationale ...
        );
end

causalTable = struct2table(rows);

end

function row = localCausalRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "CausalLabel", "", ...
    "RateAgreementImpactLabel", "", ...
    "DirectPathSuppression_dB", NaN, ...
    "SceneScoreDelta", NaN, ...
    "ProtectedRetentionRatio", NaN, ...
    "DetectabilityProxyLabel", "", ...
    "Rationale", "" ...
    );

end

function [causalLabel, rateImpactLabel, rationale] = ...
    localResolveCausalLabel(candidateName, suppressionRow, protectedRow, ...
    proxyRow, rateCaveated, resolvedOptions)

rateImpactLabel = "not_recomputed_in_first_slice";

if rateCaveated
    rateImpactLabel = "upstream_rate_caveat_carried_forward";
end

if candidateName == "none"
    causalLabel = "baseline_reference";
    rationale = "No mitigation is the comparison baseline.";
    return
end

if protectedRow.RetentionLabel == "over_cancel_risk"
    causalLabel = "over_cancelled_scene";
    rationale = "Candidate failed protected-region retention.";
    return
end

directPathSuppressed = ...
    suppressionRow.MedianDirectPathSuppression_dB(1) >= ...
    resolvedOptions.DirectPathSuppressionForCandidate_dB;
sceneImproved = proxyRow.MedianSceneScoreDelta(1) >= ...
    resolvedOptions.SceneScoreImprovementForReveal || ...
    proxyRow.MedianOffOriginEnergyFractionDelta(1) >= ...
    resolvedOptions.OffOriginEnergyImprovementForReveal || ...
    proxyRow.MedianOffOriginOccupiedFractionDelta(1) >= ...
    resolvedOptions.OffOriginOccupiedImprovementForReveal;

if directPathSuppressed && sceneImproved && rateCaveated
    causalLabel = "rate_caveated";
    rationale = "Reduced-rate proxies improved, but upstream rate caveats remain.";
elseif directPathSuppressed && sceneImproved
    causalLabel = "scene_revealed";
    rationale = "Suppression coincided with increased off-origin proxy evidence.";
elseif directPathSuppressed && ...
        proxyRow.DetectabilityProxyLabel == "visual_or_leakage_only"
    causalLabel = "visual_only_improvement";
    rationale = "Contrast changed without enough off-origin scene gain.";
elseif directPathSuppressed
    causalLabel = "leakage_cleaned_scene_still_limited";
    rationale = "Direct-path leakage dropped, but scene proxies stayed limited.";
else
    causalLabel = "visual_only_improvement";
    rationale = "Candidate did not produce scene-recovery evidence.";
end

end

function implicationTable = localBuildAcquisitionImplicationTable( ...
    causalTable, g4Analysis)

nonBaselineRows = causalTable(causalTable.CandidateName ~= "none", :);
sceneRevealed = any(nonBaselineRows.CausalLabel == "scene_revealed");
implicationArea = [ ...
    "reference_surveillance_role_separation"; ...
    "surveillance_direct_path_rejection"; ...
    "antenna_isolation"; ...
    "gain_staging"; ...
    "front_end_linearity"; ...
    "illuminator_geometry"; ...
    "collection_geometry" ...
    ];
implication = [ ...
    "Preserve or improve separation between reference and surveillance antenna roles."; ...
    "Add surveillance-path direct-path rejection before expecting digital mitigation to recover missing scene energy."; ...
    "Increase RF isolation so direct-path leakage does not dominate surveillance."; ...
    "Revisit gain staging so reference usability does not bury surveillance returns."; ...
    "Check front-end linearity because digital cancellation cannot undo compression products."; ...
    "Review illuminator geometry for target-reflection energy in surveillance."; ...
    "Review collection geometry and dwell for nonzero-Doppler structure." ...
    ];

if sceneRevealed
    evidenceLabel = repmat("monitor_after_candidate_review", ...
        numel(implicationArea), 1);
else
    evidenceLabel = repmat("acquisition_improvement_candidate", ...
        numel(implicationArea), 1);
end

g4OverallLabel = repmat(localResolveG4Label(g4Analysis, "OverallLabel"), ...
    numel(implicationArea), 1);
implicationTable = table(implicationArea, evidenceLabel, g4OverallLabel, ...
    implication, VariableNames = {'ImplicationArea', 'EvidenceLabel', ...
    'G4OverallLabel', 'Implication'});

end

function decisionTable = localBuildDecisionComparisonTable( ...
    suppressionTable, protectedTable, proxyTable, causalTable, ...
    candidateProfiles, g4Analysis)

rows = repmat(localDecisionRowTemplate(), numel(candidateProfiles), 1);
g4OverallLabel = localResolveG4Label(g4Analysis, "OverallLabel");

for idx = 1:numel(candidateProfiles)
    candidateName = string(candidateProfiles(idx).CandidateName);
    suppressionRow = suppressionTable(suppressionTable.CandidateName == ...
        candidateName, :);
    protectedRow = protectedTable(protectedTable.CandidateName == ...
        candidateName, :);
    proxyRow = proxyTable(proxyTable.CandidateName == candidateName, :);
    causalRow = causalTable(causalTable.CandidateName == candidateName, :);
    rankScore = suppressionRow.MedianDirectPathSuppression_dB(1) + ...
        10.0 .* proxyRow.MedianSceneScoreDelta(1) + ...
        3.0 .* log2(max(protectedRow.MedianProtectedRetentionRatio(1), ...
        eps));
    decisionRole = localResolveDecisionRole(candidateName, causalRow, ...
        protectedRow, g4OverallLabel);
    rows(idx) = struct( ...
        "CandidateName", candidateName, ...
        "CandidateRankScore", double(rankScore), ...
        "MedianDirectPathSuppression_dB", ...
        suppressionRow.MedianDirectPathSuppression_dB(1), ...
        "MedianSceneScoreDelta", proxyRow.MedianSceneScoreDelta(1), ...
        "MedianProtectedRetentionRatio", ...
        protectedRow.MedianProtectedRetentionRatio(1), ...
        "CausalLabel", causalRow.CausalLabel(1), ...
        "DetectabilityProxyLabel", proxyRow.DetectabilityProxyLabel(1), ...
        "DecisionRole", decisionRole, ...
        "Rationale", string(causalRow.Rationale(1)) ...
        );
end

decisionTable = sortrows(struct2table(rows), "CandidateRankScore", ...
    "descend");
decisionTable.CandidateRank = (1:height(decisionTable)).';
decisionTable = movevars(decisionTable, "CandidateRank", ...
    "Before", "CandidateName");

end

function row = localDecisionRowTemplate()

row = struct( ...
    "CandidateName", "", ...
    "CandidateRankScore", NaN, ...
    "MedianDirectPathSuppression_dB", NaN, ...
    "MedianSceneScoreDelta", NaN, ...
    "MedianProtectedRetentionRatio", NaN, ...
    "CausalLabel", "", ...
    "DetectabilityProxyLabel", "", ...
    "DecisionRole", "", ...
    "Rationale", "" ...
    );

end

function decisionRole = localResolveDecisionRole(candidateName, causalRow, ...
    protectedRow, g4OverallLabel)

if g4OverallLabel == "blocked"
    decisionRole = "not_selectable_upstream_blocked";
elseif candidateName == "none"
    decisionRole = "baseline_reference";
elseif protectedRow.RetentionLabel == "over_cancel_risk"
    decisionRole = "reject_over_cancel";
elseif causalRow.CausalLabel == "scene_revealed"
    decisionRole = "selectable_candidate";
elseif causalRow.CausalLabel == "rate_caveated"
    decisionRole = "manual_review_rate_caveated";
elseif causalRow.CausalLabel == "leakage_cleaned_scene_still_limited"
    decisionRole = "diagnostic_only";
else
    decisionRole = "reject_visual_only";
end

end

function decision = localBuildDecision(decisionTable, causalTable, ...
    g4Analysis, resolvedOptions)

g4OverallLabel = localResolveG4Label(g4Analysis, "OverallLabel");
decision = struct();
decision.FormalGateDecisionEmitted = ...
    resolvedOptions.AnalysisScope == "formal_full_g5_comparison";

if resolvedOptions.DataProfile == "synthetic"
    decision.GateDecision = "NOT_APPLICABLE_SYNTHETIC_PROFILE";
    decision.ReviewStatus = "synthetic_comparison_complete";
    decision.DecisionLabel = "descriptive_no_target_retention_cutoff";
    decision.NextBranch = "review_post_hoc_target_evidence";
    decision.Rationale = "Synthetic LMS candidates are reported " + ...
        "descriptively without a target-retention cutoff or field gate.";
    decision.FormalGateDecisionEmitted = false;
    return
end

if g4OverallLabel == "blocked"
    decision.GateDecision = "reject";
    decision.ReviewStatus = "manual_review_required";
    decision.DecisionLabel = "blocked_by_g4";
    decision.NextBranch = "hold_at_g5_diagnostic_review";
    decision.Rationale = "G4 OverallLabel is blocked; G5 ran only as diagnostic/manual-review.";
    decision.FormalGateDecisionEmitted = false;
    return
end

selectableRows = decisionTable( ...
    decisionTable.DecisionRole == "selectable_candidate", :);
rateCaveatedRows = decisionTable( ...
    decisionTable.DecisionRole == "manual_review_rate_caveated", :);
overCancelRows = causalTable(causalTable.CausalLabel == ...
    "over_cancelled_scene", :);

if ~isempty(selectableRows)
    selectedCandidate = selectableRows.CandidateName(1);
    decision.GateDecision = "pass";
    decision.ReviewStatus = "ready_for_gate_decision";
    decision.DecisionLabel = "select_" + selectedCandidate;
    decision.NextBranch = "proceed_to_g6_with_selected_g5_posture";
    decision.Rationale = "An LMS candidate improved suppression and scene proxies while retaining protected energy.";
elseif ~isempty(rateCaveatedRows)
    decision.GateDecision = "retune";
    decision.ReviewStatus = "manual_review_required";
    decision.DecisionLabel = "retune_mitigation";
    decision.NextBranch = "explain_rate_caveat_or_rerun_g5_raw_rate_audit";
    decision.Rationale = "Reduced-rate proxies improved, but rate caveats prevent automatic candidate selection.";
elseif ~isempty(overCancelRows)
    decision.GateDecision = "retune";
    decision.ReviewStatus = "manual_review_required";
    decision.DecisionLabel = "retune_mitigation";
    decision.NextBranch = "retune_g5_lms_knobs";
    decision.Rationale = "At least one LMS candidate over-cancelled protected-region content.";
else
    decision.GateDecision = "pass";
    decision.ReviewStatus = "ready_for_gate_decision";
    decision.DecisionLabel = "select_no_mitigation";
    decision.NextBranch = "proceed_to_g6_with_no_mitigation_posture";
    decision.Rationale = "No LMS candidate beat the no-mitigation baseline, so no mitigation is retained.";
end

if ~decision.FormalGateDecisionEmitted
    decision.ReviewStatus = "manual_review_required";
end

end

function coverageTable = localBuildRequirementsCoverageTable(decision, ...
    selectedRows)

requirementId = ["MIT-001"; "MIT-002"; "MIT-003"];
coverageStatus = repmat("covered_first_slice", 3, 1);
evidenceReference = [ ...
    "MitigationCandidateTable, SuppressionSummaryTable, DecisionComparisonTable"; ...
    "ProtectedRegionRetentionTable"; ...
    "DetectabilityProxyTable, MitigationCausalAssessmentTable" ...
    ];
note = repmat("selected_g4_rows=" + string(height(selectedRows)) + ...
    " | formal_gate_emitted=" + ...
    string(decision.FormalGateDecisionEmitted), 3, 1);
coverageTable = table(requirementId, coverageStatus, evidenceReference, ...
    note, VariableNames = {'RequirementId', 'CoverageStatus', ...
    'EvidenceReference', 'Note'});

end

function optionsOutput = localBuildOptionsOutput(resolvedOptions)

optionsOutput = resolvedOptions;

if isfield(optionsOutput, "SyntheticTruth")
    optionsOutput = rmfield(optionsOutput, "SyntheticTruth");
end

end

function policy = localResolveTargetRetentionPolicy(resolvedOptions)

if resolvedOptions.DataProfile == "synthetic"
    policy = "descriptive_no_cutoff";
else
    policy = "field_protected_region_threshold";
end

end

function label = localResolveG4Label(g4Analysis, fieldName)

label = "";

if isfield(g4Analysis, "Interpretation") && ...
        isfield(g4Analysis.Interpretation, fieldName)
    label = string(g4Analysis.Interpretation.(fieldName));
end

if strlength(label) == 0 && fieldName == "OverallLabel"
    label = "unknown";
end

end

function value = localResolveStructStringField(inputStruct, fieldName)

value = "";

if isstruct(inputStruct) && isfield(inputStruct, fieldName)
    value = string(inputStruct.(fieldName));
end

end

function scan = localResolveScanWithSamples(sessionData, repetitionIndex)

scan = sessionData.RadarScans(repetitionIndex);

if ~isempty(scan.Samples)
    return
end

absoluteFilePath = fullfile(string(sessionData.DatasetRoot), ...
    strrep(sessionData.RadarTable.RelativePath(repetitionIndex), ...
    "/", filesep));

try
    scan = helperScanBasebandCaptureFile(absoluteFilePath, true);
catch readException
    error("helperAnalyzeG5Mitigation:ReadSamplesFailed", ...
        "Failed to load samples for %s: %s", absoluteFilePath, ...
        readException.message);
end

end

function delayedSignal = localApplyIntegerDelay(inputSignal, sampleDelay)

sampleDelay = double(sampleDelay);
signalLength = numel(inputSignal);

if sampleDelay == 0 || signalLength == 0
    delayedSignal = inputSignal;
    return
end

if sampleDelay > 0
    if sampleDelay >= signalLength
        delayedSignal = zeros(size(inputSignal), "like", inputSignal);
        return
    end

    delayedSignal = [zeros(sampleDelay, 1, "like", inputSignal); ...
        inputSignal(1:end - sampleDelay)];
    return
end

advanceCount = abs(sampleDelay);

if advanceCount >= signalLength
    delayedSignal = zeros(size(inputSignal), "like", inputSignal);
    return
end

delayedSignal = [inputSignal(advanceCount + 1:end); ...
    zeros(advanceCount, 1, "like", inputSignal)];

end

function correctedSignal = localApplyResidualFrequencyCorrection( ...
    inputSignal, residualFrequencyHz, sampleRateHz)

sampleCount = numel(inputSignal);
sampleIndex = (0:sampleCount - 1).';
correctionPhase = exp(-1j * 2.0 * pi * residualFrequencyHz .* ...
    sampleIndex ./ sampleRateHz);
correctedSignal = inputSignal(:) .* correctionPhase;

end

function mapStartSample = localConvertStartSampleToMapDomain( ...
    inputDomainStartSample, decimationFactor)

mapStartSample = round((double(inputDomainStartSample) - 1.0) ./ ...
    double(decimationFactor)) + 1.0;

end

function value_dB = localPowerToDb(powerValue)

value_dB = pow2db(max(double(powerValue), eps));

end
