function analysis = helperAnalyzeG2AcquisitionEvidence(sessionData, ...
    captureLogInfo, collectionMetadataInfo, options)
%HELPERANALYZEG2ACQUISITIONEVIDENCE Analyze Stage 1 acquisition evidence.

arguments
    sessionData (1,1) struct
    captureLogInfo (1,1) struct
    collectionMetadataInfo (1,1) struct
    options (1,1) struct = struct()
end

resolvedOptions = localResolveOptions(sessionData, options);
roleInfo = helperResolveChannelRoles(sessionData, collectionMetadataInfo, ...
    resolvedOptions);
[metadataAuditTable, auditFlags] = localBuildMetadataAuditTable( ...
    sessionData, captureLogInfo, collectionMetadataInfo, resolvedOptions);
receiverStateTable = localBuildReceiverStateTable(sessionData, ...
    captureLogInfo, collectionMetadataInfo);
[channelRoleEvidenceTable, roleEvidence] = localBuildChannelRoleEvidence( ...
    sessionData, roleInfo, resolvedOptions);
[collectionValidityVerdict, aircraftReadinessImpact, ...
    classificationImpact, decisionTrace] = localDetermineStageVerdicts( ...
    auditFlags, roleEvidence, roleInfo, resolvedOptions);

missingRequiredMask = metadataAuditTable.Required & ...
    ~metadataAuditTable.Present;
missingRequiredItems = metadataAuditTable.EvidenceItem(missingRequiredMask);

analysis = struct();
analysis.StageId = "Stage1_AcquisitionEvidence";
analysis.DatasetId = string(sessionData.DatasetId);
analysis.MetadataAuditTable = metadataAuditTable;
analysis.ReceiverStateTable = receiverStateTable;
analysis.ChannelRoleEvidenceTable = channelRoleEvidenceTable;
analysis.CollectionValidityVerdict = collectionValidityVerdict;
analysis.AircraftReadinessImpact = aircraftReadinessImpact;
analysis.ClassificationImpact = classificationImpact;
analysis.DecisionTrace = decisionTrace;
analysis.MissingRequiredItems = missingRequiredItems;
analysis.RoleEvidence = roleEvidence;
analysis.RoleInfo = roleInfo;
analysis.DataProfile = string(resolvedOptions.DataProfile);
analysis.CollectionMetadataInfo = collectionMetadataInfo;
analysis.Options = rmfield(resolvedOptions, "WelchWindow");
analysis.Metrics = localBuildMetrics(metadataAuditTable, auditFlags, ...
    captureLogInfo, collectionMetadataInfo, roleEvidence, ...
    collectionValidityVerdict, aircraftReadinessImpact, ...
    classificationImpact, missingRequiredItems);

end

function resolvedOptions = localResolveOptions(sessionData, options)

sampleRateVector = unique(sessionData.RadarTable.SampleRate_Hz);

resolvedOptions = struct();
resolvedOptions.SampleRateHz = sampleRateVector(1);
resolvedOptions.WelchLength = 4096;
resolvedOptions.WelchOverlap = 2048;
resolvedOptions.WelchNfft = 4096;
resolvedOptions.CorrelationSampleCount = 131072;
resolvedOptions.CorrelationMaxLagSamples = 4096;
resolvedOptions.ReferenceCandidatePowerDeltaThreshold_dB = 3.0;
resolvedOptions.DataProfile = "field_capture";
resolvedOptions.WelchWindow = hann(resolvedOptions.WelchLength, ...
    "periodic");

optionFields = fieldnames(options);

for idx = 1:numel(optionFields)
    fieldName = optionFields{idx};
    resolvedOptions.(fieldName) = options.(fieldName);
end

resolvedOptions.WelchOverlap = min(resolvedOptions.WelchOverlap, ...
    resolvedOptions.WelchLength - 1);
resolvedOptions.WelchWindow = hann(resolvedOptions.WelchLength, ...
    "periodic");

end

function [metadataAuditTable, auditFlags] = localBuildMetadataAuditTable( ...
    sessionData, captureLogInfo, collectionMetadataInfo, resolvedOptions)

manifest = sessionData.Manifest;
radarTable = sessionData.RadarTable;
radioNameValue = localGetManifestSdrField(manifest, "radio_name");
centerFrequencyValue = localGetManifestSdrField(manifest, ...
    "center_frequency_hz");
sampleRateValue = localGetManifestSdrField(manifest, "sample_rate_hz");
gainSpecValue = localGetManifestField(manifest, "gain_spec");

auditFlags = struct();
auditFlags.ManifestSessionIdPresent = ...
    strlength(string(manifest.session_id)) > 0;
auditFlags.RadioNamePresent = ...
    isfield(manifest, "sdr_defaults") && ...
    isfield(manifest.sdr_defaults, "radio_name") && ...
    strlength(string(manifest.sdr_defaults.radio_name)) > 0;
auditFlags.CenterFrequencyPresent = ...
    isfield(manifest, "sdr_defaults") && ...
    isfield(manifest.sdr_defaults, "center_frequency_hz") && ...
    ~isempty(manifest.sdr_defaults.center_frequency_hz);
auditFlags.SampleRatePresent = ...
    isfield(manifest, "sdr_defaults") && ...
    isfield(manifest.sdr_defaults, "sample_rate_hz") && ...
    ~isempty(manifest.sdr_defaults.sample_rate_hz);
auditFlags.ManifestGainSpecPresent = ...
    isfield(manifest, "gain_spec") && ...
    strlength(string(manifest.gain_spec)) > 0;
auditFlags.CaptureLogPresent = captureLogInfo.LogPresent;
auditFlags.CaptureLogSessionIdMatches = captureLogInfo.SessionIdsAgree;
auditFlags.SelectedAntennasPresent = ...
    strlength(captureLogInfo.SelectedAntennas) > 0;
auditFlags.RadioProductPresent = ...
    strlength(captureLogInfo.RadioProduct) > 0;
auditFlags.SerialNumberPresent = ...
    strlength(captureLogInfo.RadioSerial) > 0;
auditFlags.ClockSourcePresent = ...
    strlength(captureLogInfo.ClockSource) > 0;
auditFlags.TimeSourcePresent = ...
    strlength(captureLogInfo.TimeSource) > 0;
auditFlags.CaptureRoundsMatch = ...
    captureLogInfo.RoundCount == manifest.capture_repetitions && ...
    captureLogInfo.CollectionStartedCount == manifest.capture_repetitions;
auditFlags.OverrunCountersPresent = captureLogInfo.ContainsOverrunText;
auditFlags.LockStatusPresent = captureLogInfo.ContainsLockStatusText;
auditFlags.ChannelLabelsStable = ...
    all(radarTable.Antenna1 == radarTable.Antenna1(1)) && ...
    all(radarTable.Antenna2 == radarTable.Antenna2(1));
auditFlags.RecordingUtcPresent = all(~isnan(radarTable.RecordingUTC));
auditFlags.CollectionMetadataPresent = collectionMetadataInfo.MetadataPresent;
auditFlags.CollectionMetadataSessionIdMatches = ...
    collectionMetadataInfo.SessionIdMatches;
auditFlags.PhysicalAntennaIdentityPresent = ...
    localHasPhysicalAntennaIdentity(collectionMetadataInfo);
auditFlags.PerChannelGainMappingPresent = ...
    strlength(collectionMetadataInfo.AcquisitionControls.GainMappingNote) > 0;
auditFlags.AgcStatePresent = captureLogInfo.ContainsAgcText || ...
    strlength(collectionMetadataInfo.AcquisitionControls.GainModeNote) > 0;
auditFlags.MappingVerificationCapturePresent = ...
    captureLogInfo.ContainsMappingVerificationText || ...
    strlength(collectionMetadataInfo.AcquisitionControls. ...
    ChannelMappingVerificationNote) > 0;
auditFlags.OperatorSiteNotePresent = ...
    localHasOperatorSiteNote(collectionMetadataInfo);

rows = struct("Category", {}, "EvidenceItem", {}, "Source", {}, ...
    "Required", {}, "Present", {}, "ObservedValue", {}, "Note", {});

rows(end + 1) = localMakeAuditRow("manifest", "manifest_session_id", ...
    "session_manifest.json", true, auditFlags.ManifestSessionIdPresent, ...
    string(manifest.session_id), "Frozen dataset identifier."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manifest", "radio_name", ...
    "session_manifest.json", true, auditFlags.RadioNamePresent, ...
    radioNameValue, ...
    "Manifest-level SDR name."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manifest", "center_frequency_hz", ...
    "session_manifest.json", true, auditFlags.CenterFrequencyPresent, ...
    centerFrequencyValue, ...
    "Manifest-level center frequency."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manifest", "sample_rate_hz", ...
    "session_manifest.json", true, auditFlags.SampleRatePresent, ...
    sampleRateValue, ...
    "Manifest-level sample rate."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manifest", "gain_spec", ...
    "session_manifest.json", true, auditFlags.ManifestGainSpecPresent, ...
    gainSpecValue, ...
    "Manifest-level gain text exists but does not prove per-channel mapping."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "capture_log_present", ...
    "logs/flighttest_capture_*.log", true, auditFlags.CaptureLogPresent, ...
    captureLogInfo.LogPath, "Primary Stage 1 capture log."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manual_metadata", ...
    "collection_metadata_present", "collection_metadata.json", false, ...
    auditFlags.CollectionMetadataPresent, ...
    collectionMetadataInfo.MetadataPath, ...
    "Dataset-local manual metadata sidecar for post-collection evidence."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("manual_metadata", ...
    "collection_metadata_session_id_matches_manifest", ...
    "collection_metadata.json", false, ...
    auditFlags.CollectionMetadataSessionIdMatches, ...
    collectionMetadataInfo.SessionId, ...
    "Manual metadata should match the manifest dataset ID."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", ...
    "capture_log_session_id_matches_manifest", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.CaptureLogSessionIdMatches, captureLogInfo.CaptureSessionId, ...
    "Capture log session ID should agree with the manifest."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "selected_antennas", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.SelectedAntennasPresent, captureLogInfo.SelectedAntennas, ...
    "RF chain labels recorded at collection time."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "radio_product", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.RadioProductPresent, captureLogInfo.RadioProduct, ...
    "Device product from UHD initialization args."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "radio_serial", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.SerialNumberPresent, captureLogInfo.RadioSerial, ...
    "Device serial from UHD initialization args."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "clock_source", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.ClockSourcePresent, captureLogInfo.ClockSource, ...
    "Clock source from UHD initialization args."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "time_source", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.TimeSourcePresent, captureLogInfo.TimeSource, ...
    "Time source from UHD initialization args."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "capture_round_count", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.CaptureRoundsMatch, ...
    sprintf("%d observed of %d expected", captureLogInfo.RoundCount, ...
    manifest.capture_repetitions), ...
    "Round count and collection-start count should match the manifest."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", ...
    "explicit_overrun_or_drop_counters", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.OverrunCountersPresent, ...
    localLogicalText(captureLogInfo.ContainsOverrunText), ...
    "Current log does not expose explicit overrun or dropped-sample counters."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("capture_log", "explicit_lock_status", ...
    "logs/flighttest_capture_*.log", true, ...
    auditFlags.LockStatusPresent, ...
    localLogicalText(captureLogInfo.ContainsLockStatusText), ...
    "Current log does not record reference-lock evidence."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("radar_headers", ...
    "channel_labels_stable_in_headers", ...
    "embedded radar headers", true, auditFlags.ChannelLabelsStable, ...
    radarTable.Antenna1(1) + " | " + radarTable.Antenna2(1), ...
    "Header-level RF chain labels are stable across repetitions."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("radar_headers", ...
    "recording_utc_present_per_file", ...
    "embedded radar headers", true, auditFlags.RecordingUtcPresent, ...
    sprintf("%d repetitions", height(radarTable)), ...
    "Each repetition carries RecordingUTC evidence."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("controls", ...
    "physical_antenna_identity_recorded", ...
    "collection_metadata.json", true, ...
    auditFlags.PhysicalAntennaIdentityPresent, ...
    localBuildAntennaIdentitySummary(collectionMetadataInfo), ...
    "Manual collection metadata can establish antenna identity even when the automatic capture log only records RF chain labels."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("controls", ...
    "explicit_per_channel_gain_mapping", ...
    "collection_metadata.json", true, ...
    auditFlags.PerChannelGainMappingPresent, ...
    collectionMetadataInfo.AcquisitionControls.GainMappingNote, ...
    "The manifest gain text should be mapped explicitly to named RF chains or ports."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("controls", ...
    "agc_or_manual_gain_state_recorded", ...
    "capture log + collection_metadata.json", true, ...
    auditFlags.AgcStatePresent, ...
    localFirstNonemptyText(localLogicalText(captureLogInfo.ContainsAgcText), ...
    collectionMetadataInfo.AcquisitionControls.GainModeNote), ...
    "AGC or manual-gain state should be recorded explicitly in automatic or manual metadata."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("controls", ...
    "channel_mapping_verification_capture", ...
    "capture log + collection_metadata.json", true, ...
    auditFlags.MappingVerificationCapturePresent, ...
    localFirstNonemptyText( ...
    localLogicalText(captureLogInfo.ContainsMappingVerificationText), ...
    collectionMetadataInfo.AcquisitionControls. ...
    ChannelMappingVerificationNote), ...
    "Operator-declared mapping is useful, but a dedicated verification capture or injected-tone proof remains the stronger evidence."); %#ok<AGROW>
rows(end + 1) = localMakeAuditRow("controls", ...
    "operator_or_site_note_recorded", ...
    "collection_metadata.json", false, ...
    auditFlags.OperatorSiteNotePresent, ...
    localBuildSiteNoteSummary(collectionMetadataInfo), ...
    "Manual site and geometry notes help interpret later null results."); %#ok<AGROW>

metadataAuditTable = struct2table(rows);

if strcmpi(string(resolvedOptions.DataProfile), "synthetic")
    fieldOnlyMask = ismember(metadataAuditTable.Category, ...
        ["capture_log", "manual_metadata", "controls"]);
    metadataAuditTable.Required(fieldOnlyMask) = false;
    metadataAuditTable.Present(fieldOnlyMask) = false;
    metadataAuditTable.ObservedValue(fieldOnlyMask) = "NOT_APPLICABLE";
    metadataAuditTable.Note(fieldOnlyMask) = ...
        "NOT_APPLICABLE for packaged synthetic data.";
end

end

function receiverStateTable = localBuildReceiverStateTable(sessionData, ...
    captureLogInfo, collectionMetadataInfo)

manifest = sessionData.Manifest;
radioNameValue = localGetManifestSdrField(manifest, "radio_name");
sampleRateValue = localGetManifestSdrField(manifest, "sample_rate_hz");
centerFrequencyValue = localGetManifestSdrField(manifest, ...
    "center_frequency_hz");
gainSpecValue = localGetManifestField(manifest, "gain_spec");
rows = struct("StateItem", {}, "ObservedValue", {}, "Source", {}, ...
    "Confidence", {}, "Comment", {});

rows(end + 1) = localMakeReceiverStateRow("dataset_id", ...
    string(sessionData.DatasetId), "session_manifest.json", ...
    "direct_manifest", "Frozen dataset identifier."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("radio_name", ...
    radioNameValue, "session_manifest.json", ...
    "direct_manifest", "Manifest-level SDR name."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("radio_product", ...
    captureLogInfo.RadioProduct, "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "UHD initialization product."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("radio_serial", ...
    captureLogInfo.RadioSerial, "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "UHD initialization serial."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("sample_rate_hz", ...
    sampleRateValue, ...
    "session_manifest.json", "direct_manifest", ...
    "Manifest-level sample rate."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("center_frequency_hz", ...
    centerFrequencyValue, ...
    "session_manifest.json", "direct_manifest", ...
    "Manifest-level center frequency."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("gain_spec", ...
    gainSpecValue, "session_manifest.json", ...
    "partial_manifest", ...
    "Gain text exists but is not explicitly mapped to RF chain labels."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("collection_metadata_path", ...
    collectionMetadataInfo.MetadataPath, "collection_metadata.json", ...
    localConfidenceText(collectionMetadataInfo.MetadataPresent), ...
    "Dataset-local manual collection metadata sidecar."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("reference_channel_manual_metadata", ...
    localBuildChannelSummary(collectionMetadataInfo.ReferenceChannel), ...
    "collection_metadata.json", ...
    localConfidenceText(localHasChannelIdentity( ...
    collectionMetadataInfo.ReferenceChannel)), ...
    "Manual reference-channel antenna identity and role declaration."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("reference_channel_spec_summary", ...
    localBuildChannelSpecSummary(collectionMetadataInfo.ReferenceChannel), ...
    "collection_metadata.json", ...
    localConfidenceText(strlength(localBuildChannelSpecSummary( ...
    collectionMetadataInfo.ReferenceChannel)) > 0), ...
    "Reference-channel antenna specification summary from manual metadata."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow( ...
    "surveillance_channel_manual_metadata", ...
    localBuildChannelSummary(collectionMetadataInfo.SurveillanceChannel), ...
    "collection_metadata.json", ...
    localConfidenceText(localHasChannelIdentity( ...
    collectionMetadataInfo.SurveillanceChannel)), ...
    "Manual surveillance-channel antenna identity and role declaration."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow( ...
    "surveillance_channel_spec_summary", ...
    localBuildChannelSpecSummary(collectionMetadataInfo.SurveillanceChannel), ...
    "collection_metadata.json", ...
    localConfidenceText(strlength(localBuildChannelSpecSummary( ...
    collectionMetadataInfo.SurveillanceChannel)) > 0), ...
    "Surveillance-channel antenna specification summary from manual metadata."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("selected_antennas", ...
    captureLogInfo.SelectedAntennas, "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "Collection-time RF chain labels."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("clock_source", ...
    captureLogInfo.ClockSource, "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "Clock source from UHD initialization."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("time_source", ...
    captureLogInfo.TimeSource, "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "Time source from UHD initialization."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("master_clock_rate_hz", ...
    string(captureLogInfo.MasterClockRate_Hz), ...
    "logs/flighttest_capture_*.log", "direct_capture_log", ...
    "Master clock rate from UHD initialization."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("capture_round_count", ...
    string(captureLogInfo.RoundCount), "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "Observed capture rounds in the log."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("capture_warning_count", ...
    string(captureLogInfo.WarningCount), "logs/flighttest_capture_*.log", ...
    "direct_capture_log", "Capture-log warnings require manual review but are not treated as hard failures in Stage 1."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("explicit_overrun_indicator", ...
    localLogicalText(captureLogInfo.ContainsOverrunText), ...
    "logs/flighttest_capture_*.log", "missing", ...
    "No explicit overrun or dropped-sample counters were logged."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("explicit_lock_status", ...
    localLogicalText(captureLogInfo.ContainsLockStatusText), ...
    "logs/flighttest_capture_*.log", "missing", ...
    "No explicit lock-status evidence was logged."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("mapping_verification_capture", ...
    localLogicalText(captureLogInfo.ContainsMappingVerificationText), ...
    "logs/flighttest_capture_*.log", "missing", ...
    "No explicit mapping-verification capture evidence was logged."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow( ...
    "surveillance_boresight_description", ...
    collectionMetadataInfo.SiteContext.SurveillanceBoresightDescription, ...
    "collection_metadata.json", ...
    localConfidenceText(strlength( ...
    collectionMetadataInfo.SiteContext.SurveillanceBoresightDescription) > 0), ...
    "Manual boresight or pointing description for the surveillance antenna."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("expected_air_traffic_note", ...
    collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote, ...
    "collection_metadata.json", ...
    localConfidenceText(strlength( ...
    collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote) > 0), ...
    "Manual scene expectation note for aircraft traffic."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("gain_mapping_note", ...
    collectionMetadataInfo.AcquisitionControls.GainMappingNote, ...
    "collection_metadata.json", ...
    localConfidenceText(strlength( ...
    collectionMetadataInfo.AcquisitionControls.GainMappingNote) > 0), ...
    "Manual mapping of gain values to RF chains."); %#ok<AGROW>
rows(end + 1) = localMakeReceiverStateRow("gain_mode_note", ...
    collectionMetadataInfo.AcquisitionControls.GainModeNote, ...
    "collection_metadata.json", ...
    localConfidenceText(strlength( ...
    collectionMetadataInfo.AcquisitionControls.GainModeNote) > 0), ...
    "Manual AGC/manual-gain state note."); %#ok<AGROW>

receiverStateTable = struct2table(rows);

end

function [channelRoleEvidenceTable, roleEvidence] = ...
    localBuildChannelRoleEvidence(sessionData, roleInfo, resolvedOptions)

radarTable = sessionData.RadarTable;
repetitionCount = height(radarTable);
sampleRateHz = resolvedOptions.SampleRateHz;

channelPowerDeltaDb = radarTable.ChannelPowerDelta_dB;
meanCoherence = zeros(repetitionCount, 1);
maxCoherence = zeros(repetitionCount, 1);
zeroLagCorrelationMagnitude = zeros(repetitionCount, 1);
peakCorrelationMagnitude = zeros(repetitionCount, 1);
peakCorrelationLagSamples = zeros(repetitionCount, 1);
roleInference = strings(repetitionCount, 1);
referenceCandidateIsChannel1 = false(repetitionCount, 1);
channel1PsdAccumulator = [];
channel2PsdAccumulator = [];
coherenceAccumulator = [];
correlationAccumulator = [];
psdFrequencyHz = [];
coherenceFrequencyHz = [];
correlationLags = [];

for idx = 1:repetitionCount
    samples = helperResolveRadarSamples(sessionData, idx);
    channel1 = double(samples(:, 1));
    channel2 = double(samples(:, 2));

    [channel1Psd, psdFrequencyHz] = pwelch(channel1, ...
        resolvedOptions.WelchWindow, resolvedOptions.WelchOverlap, ...
        resolvedOptions.WelchNfft, sampleRateHz);
    [channel2Psd, ~] = pwelch(channel2, resolvedOptions.WelchWindow, ...
        resolvedOptions.WelchOverlap, resolvedOptions.WelchNfft, ...
        sampleRateHz);
    [coherenceValues, coherenceFrequencyHz] = mscohere(channel1, channel2, ...
        resolvedOptions.WelchWindow, resolvedOptions.WelchOverlap, ...
        resolvedOptions.WelchNfft, sampleRateHz);

    correlationSampleCount = min(numel(channel1), ...
        resolvedOptions.CorrelationSampleCount);
    [correlationValues, correlationLags] = xcorr( ...
        channel1(1:correlationSampleCount), ...
        channel2(1:correlationSampleCount), ...
        resolvedOptions.CorrelationMaxLagSamples, "normalized");

    if isempty(channel1PsdAccumulator)
        channel1PsdAccumulator = zeros(size(channel1Psd));
        channel2PsdAccumulator = zeros(size(channel2Psd));
        coherenceAccumulator = zeros(size(coherenceValues));
        correlationAccumulator = zeros(numel(correlationValues), ...
            repetitionCount);
    end

    channel1PsdAccumulator = channel1PsdAccumulator + channel1Psd;
    channel2PsdAccumulator = channel2PsdAccumulator + channel2Psd;
    coherenceAccumulator = coherenceAccumulator + coherenceValues;
    correlationAccumulator(:, idx) = abs(correlationValues);
    meanCoherence(idx) = mean(coherenceValues, "omitnan");
    maxCoherence(idx) = max(coherenceValues);
    zeroLagIndex = find(correlationLags == 0, 1, "first");
    zeroLagCorrelationMagnitude(idx) = abs(correlationValues(zeroLagIndex));
    [peakCorrelationMagnitude(idx), peakIndex] = max(abs(correlationValues));
    peakCorrelationLagSamples(idx) = correlationLags(peakIndex);
    referenceCandidateIsChannel1(idx) = channelPowerDeltaDb(idx) >= ...
        resolvedOptions.ReferenceCandidatePowerDeltaThreshold_dB;
    roleInference(idx) = localDetermineRoleInference( ...
        channelPowerDeltaDb(idx), ...
        resolvedOptions.ReferenceCandidatePowerDeltaThreshold_dB);
end

meanChannel1Psd = channel1PsdAccumulator ./ repetitionCount;
meanChannel2Psd = channel2PsdAccumulator ./ repetitionCount;
meanCoherenceSpectrum = coherenceAccumulator ./ repetitionCount;
medianCorrelationMagnitude = median(correlationAccumulator, 2);

[psdFrequencyHz, meanChannel1Psd, meanChannel2Psd] = localCenterTwoSided( ...
    psdFrequencyHz, meanChannel1Psd, meanChannel2Psd, sampleRateHz);
[coherenceFrequencyHz, meanCoherenceSpectrum] = localCenterSingleSpectrum( ...
    coherenceFrequencyHz, meanCoherenceSpectrum, sampleRateHz);

channelRoleEvidenceTable = table(radarTable.Repetition, ...
    radarTable.RelativePath, repmat(radarTable.Antenna1(1), repetitionCount, 1), ...
    repmat(radarTable.Antenna2(1), repetitionCount, 1), channelPowerDeltaDb, ...
    meanCoherence, maxCoherence, zeroLagCorrelationMagnitude, ...
    peakCorrelationMagnitude, peakCorrelationLagSamples, ...
    referenceCandidateIsChannel1, roleInference, ...
    VariableNames = {'Repetition', 'RelativePath', 'Channel1Label', ...
    'Channel2Label', 'ChannelPowerDelta_dB', 'MeanCoherence', ...
    'MaxCoherence', 'ZeroLagCorrelationMagnitude', ...
    'PeakCorrelationMagnitude', 'PeakCorrelationLagSamples', ...
    'ReferenceCandidateIsChannel1', 'RoleInference'});

roleEvidence = struct();
roleEvidence.PsdFrequencyHz = psdFrequencyHz;
roleEvidence.MeanChannel1Psd = meanChannel1Psd;
roleEvidence.MeanChannel2Psd = meanChannel2Psd;
roleEvidence.ReferenceMeanPsd = localSelectRolePsd( ...
    meanChannel1Psd, meanChannel2Psd, roleInfo.ReferenceColumnIndex);
roleEvidence.SurveillanceMeanPsd = localSelectRolePsd( ...
    meanChannel1Psd, meanChannel2Psd, ...
    roleInfo.SurveillanceColumnIndex);
roleEvidence.ReferenceLabel = roleInfo.ReferenceLabel;
roleEvidence.SurveillanceLabel = roleInfo.SurveillanceLabel;
roleEvidence.RoleSource = roleInfo.RoleSource;
roleEvidence.CoherenceFrequencyHz = coherenceFrequencyHz;
roleEvidence.MeanCoherenceSpectrum = meanCoherenceSpectrum;
roleEvidence.CorrelationLagsSamples = correlationLags;
roleEvidence.MedianCorrelationMagnitude = medianCorrelationMagnitude;
expectedInference = "channel_" + ...
    string(roleInfo.ReferenceColumnIndex) + "_reference_candidate";
roleEvidence.ReferenceCandidatePassFraction = mean( ...
    roleInference == expectedInference);
roleEvidence.ChannelPowerDelta_dB_Min = min(channelPowerDeltaDb);
roleEvidence.ChannelPowerDelta_dB_Max = max(channelPowerDeltaDb);
roleEvidence.ChannelPowerDelta_dB_Median = median(channelPowerDeltaDb);
roleEvidence.MeanCoherence_Median = median(meanCoherence);
roleEvidence.PeakCorrelationMagnitude_Median = ...
    median(peakCorrelationMagnitude);
roleEvidence.PeakCorrelationLagSamples_Median = ...
    median(peakCorrelationLagSamples);
roleEvidence.IqOnlyMappingInference = localSummarizeRoleInference( ...
    roleInference, peakCorrelationMagnitude);

end

function spectrum = localSelectRolePsd(channel1Psd, channel2Psd, ...
    channelIndex)

if channelIndex == 1
    spectrum = channel1Psd;
else
    spectrum = channel2Psd;
end

end

function [collectionValidityVerdict, aircraftReadinessImpact, ...
    classificationImpact, decisionTrace] = localDetermineStageVerdicts( ...
    auditFlags, roleEvidence, roleInfo, resolvedOptions)

if strcmpi(string(resolvedOptions.DataProfile), "synthetic")
    collectionValidityVerdict = "synthetic_hardware_checks_not_applicable";
    aircraftReadinessImpact = "synthetic_numeric_analysis_only";
    classificationImpact = "Field-hardware evidence is NOT_APPLICABLE; " + ...
        "the explicit generator channel contract governs this run.";
    decisionTrace = [ ...
        "Data profile: synthetic"; ...
        "Field hardware checks: NOT_APPLICABLE"; ...
        "Role source: " + roleInfo.RoleSource; ...
        sprintf("Reference-role power-order support fraction: %.3f", ...
        roleEvidence.ReferenceCandidatePassFraction); ...
        sprintf("Median peak correlation magnitude: %.3f", ...
        roleEvidence.PeakCorrelationMagnitude_Median) ...
        ];
    return;
end

coreEvidencePresent = all([ ...
    auditFlags.ManifestSessionIdPresent; ...
    auditFlags.RadioNamePresent; ...
    auditFlags.CenterFrequencyPresent; ...
    auditFlags.SampleRatePresent; ...
    auditFlags.CaptureLogPresent; ...
    auditFlags.CaptureLogSessionIdMatches; ...
    auditFlags.SelectedAntennasPresent; ...
    auditFlags.RadioProductPresent; ...
    auditFlags.SerialNumberPresent; ...
    auditFlags.ClockSourcePresent; ...
    auditFlags.TimeSourcePresent; ...
    auditFlags.CaptureRoundsMatch; ...
    auditFlags.ChannelLabelsStable; ...
    auditFlags.RecordingUtcPresent ...
    ]);

advancedValidationPresent = all([ ...
    auditFlags.OverrunCountersPresent; ...
    auditFlags.LockStatusPresent; ...
    auditFlags.PhysicalAntennaIdentityPresent; ...
    auditFlags.PerChannelGainMappingPresent; ...
    auditFlags.AgcStatePresent; ...
    auditFlags.MappingVerificationCapturePresent ...
    ]);

iqMappingConsistent = ...
    roleEvidence.ReferenceCandidatePassFraction >= 0.9 && ...
    roleEvidence.PeakCorrelationMagnitude_Median >= 0.05;

if coreEvidencePresent && advancedValidationPresent && iqMappingConsistent
    collectionValidityVerdict = "hardware_configuration_validated";
elseif coreEvidencePresent
    collectionValidityVerdict = "hardware_state_partially_evidenced";
else
    collectionValidityVerdict = "hardware_state_not_established";
end

if collectionValidityVerdict == "hardware_configuration_validated"
    aircraftReadinessImpact = "fit_for_later_aircraft_related_analysis";
elseif coreEvidencePresent && iqMappingConsistent
    aircraftReadinessImpact = "diagnostic_use_only";
else
    aircraftReadinessImpact = "insufficient_evidence";
end

if auditFlags.MappingVerificationCapturePresent
    classificationImpact = ...
        "Stage 1 leaves the dataset classification open for later G2 " + ...
        "stages because explicit mapping proof is available.";
elseif iqMappingConsistent
    classificationImpact = ...
        "Stage 1 holds the dataset at diagnostic until explicit mapping " + ...
        "proof and the missing acquisition evidence are collected.";
else
    classificationImpact = ...
        "Stage 1 keeps the dataset diagnostic because the current " + ...
        "acquisition evidence does not prove channel mapping.";
end

decisionTrace = [ ...
    sprintf("Core acquisition evidence present: %d", coreEvidencePresent); ...
    sprintf("Advanced validation evidence present: %d", ...
    advancedValidationPresent); ...
    sprintf("IQ-only mapping inference: %s", ...
    roleEvidence.IqOnlyMappingInference); ...
    sprintf("Reference candidate pass fraction: %.3f", ...
    roleEvidence.ReferenceCandidatePassFraction); ...
    sprintf("Median peak correlation magnitude: %.3f", ...
    roleEvidence.PeakCorrelationMagnitude_Median) ...
    ];

end

function metrics = localBuildMetrics(metadataAuditTable, auditFlags, ...
    captureLogInfo, collectionMetadataInfo, roleEvidence, ...
    collectionValidityVerdict, aircraftReadinessImpact, ...
    classificationImpact, missingRequiredItems)

requiredMask = metadataAuditTable.Required;
presentRequiredMask = requiredMask & metadataAuditTable.Present;

metrics = struct();
metrics.stage_id = "Stage1_AcquisitionEvidence";
metrics.collection_validity_verdict = collectionValidityVerdict;
metrics.aircraft_readiness_impact = aircraftReadinessImpact;
metrics.classification_impact = classificationImpact;
metrics.missing_required_items = missingRequiredItems;
metrics.metadata_presence = struct();
metrics.metadata_presence.required_item_count = nnz(requiredMask);
metrics.metadata_presence.present_required_item_count = ...
    nnz(presentRequiredMask);
metrics.metadata_presence.missing_required_item_count = ...
    nnz(requiredMask) - nnz(presentRequiredMask);
metrics.audit_flags = auditFlags;
metrics.capture_log = struct();
metrics.capture_log.warning_count = captureLogInfo.WarningCount;
metrics.capture_log.round_count = captureLogInfo.RoundCount;
metrics.capture_log.collection_started_count = ...
    captureLogInfo.CollectionStartedCount;
metrics.capture_log.capture_file_count = captureLogInfo.CaptureFileCount;
metrics.capture_log.contains_overrun_text = ...
    captureLogInfo.ContainsOverrunText;
metrics.capture_log.contains_lock_status_text = ...
    captureLogInfo.ContainsLockStatusText;
metrics.capture_log.contains_mapping_verification_text = ...
    captureLogInfo.ContainsMappingVerificationText;
metrics.collection_metadata = struct();
metrics.collection_metadata.present = collectionMetadataInfo.MetadataPresent;
metrics.collection_metadata.session_id_matches = ...
    collectionMetadataInfo.SessionIdMatches;
metrics.collection_metadata.reference_channel = ...
    localBuildChannelSummary(collectionMetadataInfo.ReferenceChannel);
metrics.collection_metadata.surveillance_channel = ...
    localBuildChannelSummary(collectionMetadataInfo.SurveillanceChannel);
metrics.collection_metadata.site_context = ...
    localBuildSiteNoteSummary(collectionMetadataInfo);
metrics.role_evidence = struct();
metrics.role_evidence.reference_candidate_pass_fraction = ...
    roleEvidence.ReferenceCandidatePassFraction;
metrics.role_evidence.channel_power_delta_db_min = ...
    roleEvidence.ChannelPowerDelta_dB_Min;
metrics.role_evidence.channel_power_delta_db_max = ...
    roleEvidence.ChannelPowerDelta_dB_Max;
metrics.role_evidence.channel_power_delta_db_median = ...
    roleEvidence.ChannelPowerDelta_dB_Median;
metrics.role_evidence.mean_coherence_median = ...
    roleEvidence.MeanCoherence_Median;
metrics.role_evidence.peak_correlation_magnitude_median = ...
    roleEvidence.PeakCorrelationMagnitude_Median;
metrics.role_evidence.peak_correlation_lag_samples_median = ...
    roleEvidence.PeakCorrelationLagSamples_Median;
metrics.role_evidence.iq_only_mapping_inference = ...
    roleEvidence.IqOnlyMappingInference;

end

function roleText = localDetermineRoleInference(powerDeltaDb, thresholdDb)

if powerDeltaDb >= thresholdDb
    roleText = "channel_1_reference_candidate";
elseif powerDeltaDb <= -thresholdDb
    roleText = "channel_2_reference_candidate";
else
    roleText = "ambiguous";
end

end

function summaryText = localSummarizeRoleInference(roleInference, ...
    peakCorrelationMagnitude)

if all(roleInference == "channel_1_reference_candidate") && ...
        median(peakCorrelationMagnitude) >= 0.05
    summaryText = "consistent_channel_1_reference_candidate";
elseif all(roleInference == "channel_2_reference_candidate") && ...
        median(peakCorrelationMagnitude) >= 0.05
    summaryText = "consistent_channel_2_reference_candidate";
else
    summaryText = "ambiguous_from_iq_only";
end

end

function [frequencyHz, spectrum1, spectrum2] = localCenterTwoSided( ...
    frequencyHz, spectrum1, spectrum2, sampleRateHz)

if max(frequencyHz) <= sampleRateHz / 2
    return
end

frequencyHz = frequencyHz - sampleRateHz / 2;
spectrum1 = fftshift(spectrum1);
spectrum2 = fftshift(spectrum2);

end

function [frequencyHz, spectrum] = localCenterSingleSpectrum( ...
    frequencyHz, spectrum, sampleRateHz)

if max(frequencyHz) <= sampleRateHz / 2
    return
end

frequencyHz = frequencyHz - sampleRateHz / 2;
spectrum = fftshift(spectrum);

end

function row = localMakeAuditRow(category, evidenceItem, source, required, ...
    present, observedValue, note)

row = struct();
row.Category = string(category);
row.EvidenceItem = string(evidenceItem);
row.Source = string(source);
row.Required = logical(required);
row.Present = logical(present);
row.ObservedValue = string(observedValue);
row.Note = string(note);

end

function row = localMakeReceiverStateRow(stateItem, observedValue, source, ...
    confidence, comment)

row = struct();
row.StateItem = string(stateItem);
row.ObservedValue = string(observedValue);
row.Source = string(source);
row.Confidence = string(confidence);
row.Comment = string(comment);

end

function text = localLogicalText(value)

if value
    text = "yes";
else
    text = "no";
end

end

function value = localHasPhysicalAntennaIdentity(collectionMetadataInfo)

value = localHasChannelIdentity(collectionMetadataInfo.ReferenceChannel) && ...
    localHasChannelIdentity(collectionMetadataInfo.SurveillanceChannel);

end

function value = localHasChannelIdentity(channelInfo)

value = strlength(channelInfo.ChannelLabel) > 0 && ...
    strlength(channelInfo.Role) > 0 && ...
    strlength(channelInfo.AntennaName) > 0;

end

function value = localHasOperatorSiteNote(collectionMetadataInfo)

value = strlength(collectionMetadataInfo.SiteContext.SiteRegion) > 0 || ...
    strlength(collectionMetadataInfo.SiteContext. ...
    SurveillanceBoresightDescription) > 0 || ...
    strlength(collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote) > 0 || ...
    strlength(collectionMetadataInfo.AcquisitionControls.OperatorNotes) > 0;

end

function summaryText = localBuildAntennaIdentitySummary(collectionMetadataInfo)

summaryText = strjoin([ ...
    localBuildChannelSummary(collectionMetadataInfo.ReferenceChannel); ...
    localBuildChannelSummary(collectionMetadataInfo.SurveillanceChannel) ...
    ], " | ");

end

function summaryText = localBuildSiteNoteSummary(collectionMetadataInfo)

summaryText = strjoin([ ...
    collectionMetadataInfo.SiteContext.SiteRegion; ...
    collectionMetadataInfo.SiteContext.SurveillanceBoresightDescription; ...
    collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote; ...
    collectionMetadataInfo.AcquisitionControls.OperatorNotes ...
    ], " | ");
summaryText = localRemoveEmptyJoinArtifacts(summaryText);

end

function summaryText = localBuildChannelSummary(channelInfo)

summaryText = strjoin([ ...
    channelInfo.ChannelLabel; ...
    channelInfo.Role; ...
    channelInfo.AntennaName; ...
    channelInfo.AntennaType; ...
    localFormatChannelNote(channelInfo) ...
    ], " | ");
summaryText = localRemoveEmptyJoinArtifacts(summaryText);

end

function summaryText = localBuildChannelSpecSummary(channelInfo)

summaryText = strjoin([ ...
    channelInfo.Manufacturer; ...
    channelInfo.Model; ...
    channelInfo.NominalFrequencyRange; ...
    localFormatCableSummary(channelInfo); ...
    channelInfo.PublishedProductGainNote; ...
    channelInfo.PublishedNoiseFigureNote; ...
    localFormatImpedanceSummary(channelInfo); ...
    channelInfo.PublishedMaxOutputLevelNote; ...
    channelInfo.PublishedPowerRequirement; ...
    channelInfo.PublishedOperatingTemperatureNote; ...
    channelInfo.PreampOrAttenuator ...
    ], " | ");
summaryText = localRemoveEmptyJoinArtifacts(summaryText);

end

function noteText = localFormatChannelNote(channelInfo)

if strlength(channelInfo.AntennaTunedFrequencyHz) > 0
    noteText = "tuned_hz=" + channelInfo.AntennaTunedFrequencyHz;
elseif strlength(channelInfo.Notes) > 0
    noteText = channelInfo.Notes;
else
    noteText = "";
end

end

function summaryText = localFormatCableSummary(channelInfo)

summaryText = "";

if strlength(channelInfo.CableType) > 0 && ...
        strlength(channelInfo.CableLengthFt) > 0
    summaryText = channelInfo.CableType + " | cable_length_ft=" + ...
        channelInfo.CableLengthFt;
elseif strlength(channelInfo.CableType) > 0
    summaryText = channelInfo.CableType;
elseif strlength(channelInfo.CableLengthM) > 0
    summaryText = "cable_length_m=" + channelInfo.CableLengthM;
end

end

function summaryText = localFormatImpedanceSummary(channelInfo)

summaryText = "";

if strlength(channelInfo.PublishedImpedanceOhm) > 0
    summaryText = "impedance_ohm=" + channelInfo.PublishedImpedanceOhm;
end

end

function outputText = localRemoveEmptyJoinArtifacts(inputText)

tokens = split(string(inputText), "|");
tokens = strtrim(tokens);
tokens = tokens(strlength(tokens) > 0);

if isempty(tokens)
    outputText = "";
else
    outputText = strjoin(tokens, " | ");
end

end

function text = localFirstNonemptyText(varargin)

text = "";

for idx = 1:nargin
    candidate = strtrim(string(varargin{idx}));

    if strlength(candidate) > 0 && candidate ~= "no"
        text = candidate;
        return
    end
end

if nargin > 0
    text = strtrim(string(varargin{1}));
end

end

function text = localConfidenceText(value)

if value
    text = "manual_metadata_present";
else
    text = "missing";
end

end

function value = localGetManifestField(manifest, fieldName)

value = "";

if isfield(manifest, fieldName)
    value = string(manifest.(fieldName));
end

end

function value = localGetManifestSdrField(manifest, fieldName)

value = "";

if ~isfield(manifest, "sdr_defaults")
    return
end

if ~isfield(manifest.sdr_defaults, fieldName)
    return
end

value = string(manifest.sdr_defaults.(fieldName));

end
