function layout = helperBuildG2ButterflyPptLayout(spec, projectRoot, pptPath)
%HELPERBUILDG2BUTTERFLYPPTLAYOUT Build the G2 butterfly slide layout.

arguments
    spec (1, 1) struct
    projectRoot (1, :) char
    pptPath (1, :) char
end

relativeMarkdownPath = strrep(char(spec.MarkdownPath), ...
    [projectRoot filesep], "");
relativeArtifactDir = strrep(fileparts(pptPath), [projectRoot filesep], "");

colors = localBuildColorPalette();

slideWidth = 960;
slideHeight = 540;

slide1Texts = localBuildSlide1Texts(spec, colors, relativeMarkdownPath, ...
    relativeArtifactDir);
slide1Boxes = localBuildSlide1Boxes(spec, colors);
slide1Lines = localBuildSlide1Lines(slide1Boxes, colors);

slide2Texts = localBuildSlide2Texts(spec, colors, relativeMarkdownPath);
slide2Boxes = localBuildSlide2Boxes(spec, colors);
slide2Lines = localBuildSlide2Lines(slide2Boxes, colors);

layout = struct();
layout.SlideWidth = slideWidth;
layout.SlideHeight = slideHeight;
layout.ExportSlideIndex = 1;
layout.Slides = [ ...
    struct( ...
        "Title", "G2 Butterfly", ...
        "Boxes", slide1Boxes, ...
        "Texts", slide1Texts, ...
        "Lines", slide1Lines ...
    ) ...
    struct( ...
        "Title", "G2 Technical Flow", ...
        "Boxes", slide2Boxes, ...
        "Texts", slide2Texts, ...
        "Lines", slide2Lines ...
    ) ...
    ];
end

function colors = localBuildColorPalette()

colors = struct();
colors.Text = "#111827";
colors.SubtleText = "#334155";
colors.LeftFill = "#E8F1FF";
colors.LeftLine = "#24518A";
colors.CenterFill = "#FFF5D9";
colors.CenterLine = "#C07A00";
colors.RightFill = "#E9F7EF";
colors.RightLine = "#2F6B2F";
colors.NoteFill = "#FFFFFF";
colors.NoteLine = "#CBD5E1";
colors.FlowFill = "#F8FAFC";
colors.FlowLine = "#64748B";
colors.AlertFill = "#FDECEC";
colors.AlertLine = "#B42318";
colors.PrimaryLine = "#24518A";
colors.SecondaryLine = "#64748B";
end

function texts = localBuildSlide1Texts(spec, colors, relativeMarkdownPath, ...
    relativeArtifactDir)

overviewText = strjoin(spec.Overview, newline);
flowText = strjoin(localFormatFlowFooter(spec.FlowSteps), "  ->  ");

texts = [ ...
    localMakeText( ...
        spec.Title, 24, 16, 912, 22, 24, true, false, "left", ...
        colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "G2 RF-health butterfly view for technical and customer communication", ...
        24, 42, 912, 16, 11, false, false, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        overviewText, 24, 72, 912, 42, 11, false, false, "left", ...
        colors.Text, colors.NoteFill, colors.NoteLine ...
    ) ...
    localMakeText( ...
        "Inputs and checks", 64, 124, 200, 18, 13, true, false, "center", ...
        colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "Gate decisions", 350, 124, 260, 18, 13, true, false, "center", ...
        colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "Outputs and advisories", 696, 124, 200, 18, 13, true, false, ...
        "center", colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        sprintf("Technical flow: %s", flowText), ...
        24, 462, 912, 32, 10, false, false, "left", ...
        colors.Text, colors.NoteFill, colors.NoteLine ...
    ) ...
    localMakeText( ...
        sprintf("Source markdown: %s", relativeMarkdownPath), ...
        24, 505, 420, 14, 9, false, true, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        sprintf("Asset folder: %s", relativeArtifactDir), ...
        452, 505, 484, 14, 9, false, true, "right", ...
        colors.SubtleText, "", "" ...
    ) ...
    ];
end

function boxes = localBuildSlide1Boxes(spec, colors)

leftTexts = localFormatWingBoxes(spec.LeftWing);
doubleNewline = string(newline) + string(newline);
centerText = strjoin(localFormatCenterItems(spec.Center), doubleNewline);
rightTexts = localFormatWingBoxes(spec.RightWing);

leftX = 34;
rightX = 706;
boxWidth = 220;
boxHeight = 64;
boxGap = 14;
startY = 156;

leftBoxes = repmat(localBoxTemplate(), 1, numel(leftTexts));
rightBoxes = repmat(localBoxTemplate(), 1, numel(rightTexts));

for boxIndex = 1:numel(leftTexts)
    currentY = startY + (boxIndex - 1) * (boxHeight + boxGap);
    leftBoxes(boxIndex) = localMakeBox( ...
        "LEFT_" + string(boxIndex), leftTexts(boxIndex), leftX, currentY, ...
        boxWidth, boxHeight, colors.LeftFill, colors.LeftLine, 11, true, ...
        colors.Text, 1, "center");
end

for boxIndex = 1:numel(rightTexts)
    currentY = startY + (boxIndex - 1) * (boxHeight + boxGap);
    rightBoxes(boxIndex) = localMakeBox( ...
        "RIGHT_" + string(boxIndex), rightTexts(boxIndex), rightX, currentY, ...
        boxWidth, boxHeight, colors.RightFill, colors.RightLine, 11, true, ...
        colors.Text, 1, "center");
end

centerBox = localMakeBox( ...
    "CENTER_GATE", centerText, 328, 184, 304, 168, colors.CenterFill, ...
    colors.CenterLine, 13, true, colors.Text, 1, "center");

boxes = [leftBoxes centerBox rightBoxes];
end

function lines = localBuildSlide1Lines(boxes, colors)

leftBoxes = boxes(contains(string({boxes.Id}), "LEFT_"));
centerBox = boxes(strcmp(string({boxes.Id}), "CENTER_GATE"));
rightBoxes = boxes(contains(string({boxes.Id}), "RIGHT_"));

lineCount = numel(leftBoxes) + numel(rightBoxes);
lines = repmat(localLineTemplate(), 1, lineCount);
lineIndex = 0;

for boxIndex = 1:numel(leftBoxes)
    currentBox = leftBoxes(boxIndex);
    lineIndex = lineIndex + 1;
    lines(lineIndex) = localMakeLine( ...
        currentBox.X + currentBox.Width, ...
        currentBox.Y + currentBox.Height / 2, ...
        centerBox.X, ...
        centerBox.Y + centerBox.Height / 2, ...
        colors.PrimaryLine, ...
        1.75, ...
        true, ...
        "" ...
    );
end

for boxIndex = 1:numel(rightBoxes)
    currentBox = rightBoxes(boxIndex);
    lineIndex = lineIndex + 1;
    lines(lineIndex) = localMakeLine( ...
        centerBox.X + centerBox.Width, ...
        centerBox.Y + centerBox.Height / 2, ...
        currentBox.X, ...
        currentBox.Y + currentBox.Height / 2, ...
        colors.PrimaryLine, ...
        1.75, ...
        true, ...
        "" ...
    );
end
end

function texts = localBuildSlide2Texts(spec, colors, relativeMarkdownPath)

evidenceText = strjoin(spec.EvidenceOutputs, newline);
notesText = strjoin(spec.VisualNotes, newline);

texts = [ ...
    localMakeText( ...
        "G2 Technical Flow", 24, 16, 912, 22, 24, true, false, ...
        "left", colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        "Sequential view of the planned G2 checks and output decisions", ...
        24, 42, 912, 16, 11, false, false, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    localMakeText( ...
        "Evidence outputs", 36, 286, 420, 18, 13, true, false, ...
        "left", colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        evidenceText, 36, 308, 430, 140, 10, false, false, ...
        "left", colors.Text, colors.NoteFill, colors.NoteLine ...
    ) ...
    localMakeText( ...
        "Visual notes", 496, 286, 420, 18, 13, true, false, ...
        "left", colors.Text, "", "" ...
    ) ...
    localMakeText( ...
        notesText, 496, 308, 430, 140, 10, false, false, ...
        "left", colors.Text, colors.NoteFill, colors.NoteLine ...
    ) ...
    localMakeText( ...
        sprintf("Source markdown: %s", relativeMarkdownPath), ...
        24, 500, 912, 14, 9, false, true, "left", ...
        colors.SubtleText, "", "" ...
    ) ...
    ];
end

function boxes = localBuildSlide2Boxes(spec, colors)

stepTexts = localFormatFlowSteps(spec.FlowSteps);
boxWidth = 122;
boxHeight = 68;
startX = 36;
startY = 138;
gap = 10;

boxes = repmat(localBoxTemplate(), 1, numel(stepTexts));

for boxIndex = 1:numel(stepTexts)
    currentX = startX + (boxIndex - 1) * (boxWidth + gap);
    boxes(boxIndex) = localMakeBox( ...
        "FLOW_" + string(boxIndex), stepTexts(boxIndex), currentX, startY, ...
        boxWidth, boxHeight, colors.FlowFill, colors.FlowLine, 11, true, ...
        colors.Text, 1, "center");
end
end

function lines = localBuildSlide2Lines(boxes, colors)

lineCount = max(0, numel(boxes) - 1);
lines = repmat(localLineTemplate(), 1, lineCount);

for lineIndex = 1:lineCount
    sourceBox = boxes(lineIndex);
    targetBox = boxes(lineIndex + 1);
    lines(lineIndex) = localMakeLine( ...
        sourceBox.X + sourceBox.Width, ...
        sourceBox.Y + sourceBox.Height / 2, ...
        targetBox.X, ...
        targetBox.Y + targetBox.Height / 2, ...
        colors.SecondaryLine, ...
        1.75, ...
        true, ...
        "" ...
    );
end
end

function formatted = localFormatWingBoxes(rawValues)

formatted = strings(size(rawValues));

for valueIndex = 1:numel(rawValues)
    formatted(valueIndex) = localBreakAtFirstColon(rawValues(valueIndex));
end
end

function formatted = localFormatCenterItems(rawValues)

formatted = strings(size(rawValues));

for valueIndex = 1:numel(rawValues)
    formatted(valueIndex) = "- " + rawValues(valueIndex);
end
end

function formatted = localFormatFlowSteps(rawValues)

formatted = strings(size(rawValues));

for valueIndex = 1:numel(rawValues)
    currentValue = rawValues(valueIndex);
    currentValue = regexprep(currentValue, "^\s*(\d+)\.\s*", ...
        "$1" + string(newline));
    formatted(valueIndex) = localBreakAtFirstColon(currentValue);
end
end

function formatted = localFormatFlowFooter(rawValues)

formatted = strings(size(rawValues));

for valueIndex = 1:numel(rawValues)
    currentValue = regexprep(rawValues(valueIndex), "^\s*\d+\.\s*", "");
    currentValue = strrep(currentValue, ": ", " - ");
    formatted(valueIndex) = currentValue;
end
end

function value = localBreakAtFirstColon(value)

colonIndex = strfind(value, ": ");

if isempty(colonIndex)
    return;
end

firstIndex = colonIndex(1);
value = extractBefore(value, firstIndex) + newline + ...
    extractAfter(value, firstIndex + 1);
end

function textSpec = localMakeText(textValue, xValue, yValue, widthValue, ...
    heightValue, fontSizeValue, boldValue, italicValue, alignValue, ...
    fontColorValue, fillColorValue, lineColorValue)

textSpec = struct( ...
    "Text", char(string(textValue)), ...
    "X", xValue, ...
    "Y", yValue, ...
    "Width", widthValue, ...
    "Height", heightValue, ...
    "FontSize", fontSizeValue, ...
    "Bold", boldValue, ...
    "Italic", italicValue, ...
    "Align", alignValue, ...
    "FontColor", fontColorValue, ...
    "FillColor", fillColorValue, ...
    "LineColor", lineColorValue ...
    );
end

function boxSpec = localMakeBox(idValue, textValue, xValue, yValue, ...
    widthValue, heightValue, fillColorValue, lineColorValue, ...
    fontSizeValue, boldValue, fontColorValue, shapeTypeValue, alignValue)

boxSpec = struct( ...
    "Id", char(string(idValue)), ...
    "Text", char(string(textValue)), ...
    "X", xValue, ...
    "Y", yValue, ...
    "Width", widthValue, ...
    "Height", heightValue, ...
    "FillColor", fillColorValue, ...
    "LineColor", lineColorValue, ...
    "FontSize", fontSizeValue, ...
    "Bold", boldValue, ...
    "FontColor", fontColorValue, ...
    "ShapeType", shapeTypeValue, ...
    "Align", alignValue ...
    );
end

function lineSpec = localMakeLine(x1Value, y1Value, x2Value, y2Value, ...
    colorValue, weightValue, arrowValue, labelValue)

lineSpec = struct( ...
    "X1", x1Value, ...
    "Y1", y1Value, ...
    "X2", x2Value, ...
    "Y2", y2Value, ...
    "Color", colorValue, ...
    "Weight", weightValue, ...
    "Arrow", arrowValue, ...
    "Label", char(string(labelValue)), ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
    );
end

function template = localBoxTemplate()

template = struct( ...
    "Id", "", ...
    "Text", "", ...
    "X", 0, ...
    "Y", 0, ...
    "Width", 0, ...
    "Height", 0, ...
    "FillColor", "", ...
    "LineColor", "", ...
    "FontSize", 0, ...
    "Bold", false, ...
    "FontColor", "", ...
    "ShapeType", 1, ...
    "Align", "center" ...
    );
end

function template = localLineTemplate()

template = struct( ...
    "X1", 0, ...
    "Y1", 0, ...
    "X2", 0, ...
    "Y2", 0, ...
    "Color", "", ...
    "Weight", 0, ...
    "Arrow", false, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
    );
end
