function layout = helperBuildPipelinePptLayout(spec, projectRoot, outputPath)
%HELPERBUILDPIPELINEPPTLAYOUT Create the slide geometry and text used for the PPT deck.

arguments
    spec (1, 1) struct
    projectRoot (1, :) char
    outputPath (1, :) char
end

requiredIds = { ...
    "G1", "G2", "G3", "G4", "G5", ...
    "G6", "G7", "G8", "G9", "G10", ...
    "IVV", "CUST", "RJ", "DIAG", "M4", "M8", "MT", "MC", "RU" ...
};

for idIndex = 1:numel(requiredIds)
    if ~isKey(spec.LabelMap, char(requiredIds{idIndex}))
        error( ...
            "helperBuildPipelinePptLayout:MissingNode", ...
            "Required node %s is missing from %s", ...
            requiredIds{idIndex}, ...
            spec.MarkdownPath ...
        );
    end
end

relativeMarkdownPath = strrep(spec.MarkdownPath, [projectRoot filesep], "");
relativeOutputPath = strrep(outputPath, [projectRoot filesep], "");

colors = struct;
colors.GateFill = "#EEF5FF";
colors.GateLine = "#1F4E79";
colors.LaneFill = "#F3F4F6";
colors.LaneLine = "#64748B";
colors.OutcomeFill = "#FFF4E6";
colors.OutcomeLine = "#C47F00";
colors.RejectFill = "#FDECEC";
colors.RejectLine = "#B42318";
colors.SupportFill = "#E8F5E9";
colors.SupportLine = "#2F6B2F";
colors.NoteFill = "#FFFFFF";
colors.NoteLine = "#CBD5E1";
colors.Text = "#111827";
colors.PassLine = "#1F4E79";
colors.EvidenceLine = "#64748B";
colors.ReopenLine = "#2F6B2F";
colors.OutcomeLineSoft = "#C47F00";
colors.RejectLineSoft = "#B42318";

gateStartX = 25;
gateY = 224;
gateWidth = 82;
gateHeight = 48;
gateGap = 10;
gateIds = { ...
    "G1", "G2", "G3", "G4", "G5", ...
    "G6", "G7", "G8", "G9", "G10" ...
};

boxTemplate = struct( ...
    "Id", "", ...
    "Text", "", ...
    "X", 0, ...
    "Y", 0, ...
    "Width", 0, ...
    "Height", 0, ...
    "FillColor", "", ...
    "LineColor", "", ...
    "FontSize", 0, ...
    "Bold", false, ...
    "FontColor", "", ...
    "ShapeType", 0, ...
    "Align", "" ...
);

gateBoxes = repmat(boxTemplate, 1, numel(gateIds));

for gateIndex = 1:numel(gateIds)
    gateId = char(gateIds{gateIndex});
    gateBoxes(gateIndex) = struct( ...
        "Id", gateId, ...
        "Text", spec.LabelMap(gateId), ...
        "X", gateStartX + (gateIndex - 1) * (gateWidth + gateGap), ...
        "Y", gateY, ...
        "Width", gateWidth, ...
        "Height", gateHeight, ...
        "FillColor", colors.GateFill, ...
        "LineColor", colors.GateLine, ...
        "FontSize", 10, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    );
end

slide1Boxes = [ ...
    gateBoxes ...
    struct( ...
        "Id", "IVV", ...
        "Text", spec.LabelMap("IVV"), ...
        "X", 245, ...
        "Y", 84, ...
        "Width", 220, ...
        "Height", 36, ...
        "FillColor", colors.LaneFill, ...
        "LineColor", colors.LaneLine, ...
        "FontSize", 14, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "CUST", ...
        "Text", spec.LabelMap("CUST"), ...
        "X", 645, ...
        "Y", 84, ...
        "Width", 220, ...
        "Height", 36, ...
        "FillColor", colors.LaneFill, ...
        "LineColor", colors.LaneLine, ...
        "FontSize", 14, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "RU", ...
        "Text", sprintf("%s\nTargets: G1, G3, G4, G6, G7, G8, G9", spec.LabelMap("RU")), ...
        "X", 370, ...
        "Y", 136, ...
        "Width", 220, ...
        "Height", 52, ...
        "FillColor", colors.SupportFill, ...
        "LineColor", colors.SupportLine, ...
        "FontSize", 11, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "RJ", ...
        "Text", spec.LabelMap("RJ"), ...
        "X", 68, ...
        "Y", 332, ...
        "Width", 160, ...
        "Height", 40, ...
        "FillColor", colors.RejectFill, ...
        "LineColor", colors.RejectLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "M4", ...
        "Text", spec.LabelMap("M4"), ...
        "X", 276, ...
        "Y", 332, ...
        "Width", 150, ...
        "Height", 40, ...
        "FillColor", colors.OutcomeFill, ...
        "LineColor", colors.OutcomeLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "M8", ...
        "Text", spec.LabelMap("M8"), ...
        "X", 632, ...
        "Y", 332, ...
        "Width", 160, ...
        "Height", 40, ...
        "FillColor", colors.OutcomeFill, ...
        "LineColor", colors.OutcomeLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "MT", ...
        "Text", spec.LabelMap("MT"), ...
        "X", 804, ...
        "Y", 332, ...
        "Width", 130, ...
        "Height", 40, ...
        "FillColor", colors.OutcomeFill, ...
        "LineColor", colors.OutcomeLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "DIAG", ...
        "Text", spec.LabelMap("DIAG"), ...
        "X", 540, ...
        "Y", 388, ...
        "Width", 160, ...
        "Height", 40, ...
        "FillColor", colors.RejectFill, ...
        "LineColor", colors.RejectLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "MC", ...
        "Text", spec.LabelMap("MC"), ...
        "X", 772, ...
        "Y", 388, ...
        "Width", 162, ...
        "Height", 40, ...
        "FillColor", colors.OutcomeFill, ...
        "LineColor", colors.OutcomeLine, ...
        "FontSize", 12, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
];

slide1Texts = [ ...
    struct( ...
        "Text", "Passive Bistatic Restart", ...
        "X", 24, ...
        "Y", 16, ...
        "Width", 912, ...
        "Height", 22, ...
        "FontSize", 24, ...
        "Bold", true, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
    struct( ...
        "Text", "Pipeline Flowchart (editable PowerPoint butterfly view)", ...
        "X", 24, ...
        "Y", 42, ...
        "Width", 912, ...
        "Height", 16, ...
        "FontSize", 11, ...
        "Bold", false, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
    struct( ...
        "Text", char(strjoin([ ...
            "Legend", ...
            "Blue: pass progression", ...
            "Red: reject or blocked", ...
            "Green: reopen upstream", ...
            "Orange: milestone state", ...
            "Retune: stays local" ...
        ], newline)), ...
        "X", 20, ...
        "Y", 82, ...
        "Width", 185, ...
        "Height", 96, ...
        "FontSize", 10, ...
        "Bold", false, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", colors.NoteFill, ...
        "LineColor", colors.NoteLine ...
    ) ...
    struct( ...
        "Text", sprintf("Source markdown: %s", relativeMarkdownPath), ...
        "X", 24, ...
        "Y", 500, ...
        "Width", 455, ...
        "Height", 14, ...
        "FontSize", 9, ...
        "Bold", false, ...
        "Italic", true, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
    struct( ...
        "Text", sprintf("Generated artifact: %s", relativeOutputPath), ...
        "X", 500, ...
        "Y", 500, ...
        "Width", 436, ...
        "Height", 14, ...
        "FontSize", 9, ...
        "Bold", false, ...
        "Italic", true, ...
        "Align", "right", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
];

lineTemplate = struct( ...
    "X1", 0, ...
    "Y1", 0, ...
    "X2", 0, ...
    "Y2", 0, ...
    "Color", "", ...
    "Weight", 0, ...
    "Arrow", false, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

slide1LineCount = 19;
slide1Lines = repmat(lineTemplate, 1, slide1LineCount);
lineIndex = 0;

for gateIndex = 1:(numel(gateBoxes) - 1)
    sourceBox = gateBoxes(gateIndex);
    targetBox = gateBoxes(gateIndex + 1);
    lineIndex = lineIndex + 1;
    slide1Lines(lineIndex) = struct( ...
        "X1", sourceBox.X + sourceBox.Width, ...
        "Y1", sourceBox.Y + sourceBox.Height / 2, ...
        "X2", targetBox.X, ...
        "Y2", targetBox.Y + targetBox.Height / 2, ...
        "Color", colors.PassLine, ...
        "Weight", 2.25, ...
        "Arrow", true, ...
        "Label", "", ...
        "LabelX", 0, ...
        "LabelY", 0, ...
        "LabelWidth", 0, ...
        "LabelHeight", 0, ...
        "LabelFontSize", 0, ...
        "LabelAlign", "center" ...
    );
end

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(4).X + gateBoxes(4).Width / 2, ...
    "Y1", gateBoxes(4).Y, ...
    "X2", 480, ...
    "Y2", 188, ...
    "Color", colors.ReopenLine, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(6).X + gateBoxes(6).Width / 2, ...
    "Y1", gateBoxes(6).Y, ...
    "X2", 480, ...
    "Y2", 188, ...
    "Color", colors.ReopenLine, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(8).X + gateBoxes(8).Width / 2, ...
    "Y1", gateBoxes(8).Y, ...
    "X2", 480, ...
    "Y2", 188, ...
    "Color", colors.ReopenLine, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(10).X + gateBoxes(10).Width / 2, ...
    "Y1", gateBoxes(10).Y, ...
    "X2", 480, ...
    "Y2", 188, ...
    "Color", colors.ReopenLine, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(2).X + gateBoxes(2).Width / 2, ...
    "Y1", gateBoxes(2).Y + gateBoxes(2).Height, ...
    "X2", 148, ...
    "Y2", 332, ...
    "Color", colors.RejectLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "G1-G3 reject", ...
    "LabelX", 70, ...
    "LabelY", 300, ...
    "LabelWidth", 160, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(4).X + gateBoxes(4).Width / 2, ...
    "Y1", gateBoxes(4).Y + gateBoxes(4).Height, ...
    "X2", 350, ...
    "Y2", 332, ...
    "Color", colors.OutcomeLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "validated passive baseline", ...
    "LabelX", 250, ...
    "LabelY", 300, ...
    "LabelWidth", 200, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(8).X + gateBoxes(8).Width / 2, ...
    "Y1", gateBoxes(8).Y + gateBoxes(8).Height, ...
    "X2", 712, ...
    "Y2", 332, ...
    "Color", colors.OutcomeLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "first success milestone", ...
    "LabelX", 620, ...
    "LabelY", 300, ...
    "LabelWidth", 190, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(9).X + gateBoxes(9).Width / 2, ...
    "Y1", gateBoxes(9).Y + gateBoxes(9).Height, ...
    "X2", 712, ...
    "Y2", 332, ...
    "Color", colors.OutcomeLineSoft, ...
    "Weight", 1.5, ...
    "Arrow", true, ...
    "Label", "G9 hold", ...
    "LabelX", 676, ...
    "LabelY", 316, ...
    "LabelWidth", 76, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 8, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(7).X + gateBoxes(7).Width / 2, ...
    "Y1", gateBoxes(7).Y + gateBoxes(7).Height, ...
    "X2", 620, ...
    "Y2", 388, ...
    "Color", colors.RejectLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "truth blocked", ...
    "LabelX", 555, ...
    "LabelY", 356, ...
    "LabelWidth", 128, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(10).X + gateBoxes(10).Width / 2, ...
    "Y1", gateBoxes(10).Y + gateBoxes(10).Height, ...
    "X2", 868, ...
    "Y2", 332, ...
    "Color", colors.OutcomeLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "track-level pass", ...
    "LabelX", 800, ...
    "LabelY", 300, ...
    "LabelWidth", 138, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(10).X + gateBoxes(10).Width / 2, ...
    "Y1", gateBoxes(10).Y + gateBoxes(10).Height, ...
    "X2", 852, ...
    "Y2", 388, ...
    "Color", colors.OutcomeLineSoft, ...
    "Weight", 1.75, ...
    "Arrow", true, ...
    "Label", "truth-correlated pass", ...
    "LabelX", 770, ...
    "LabelY", 432, ...
    "LabelWidth", 170, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 9, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(1).X + gateBoxes(1).Width / 2, ...
    "Y1", gateBoxes(1).Y, ...
    "X2", 300, ...
    "Y2", 120, ...
    "Color", colors.EvidenceLine, ...
    "Weight", 1.25, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(4).X + gateBoxes(4).Width / 2, ...
    "Y1", gateBoxes(4).Y, ...
    "X2", 355, ...
    "Y2", 120, ...
    "Color", colors.EvidenceLine, ...
    "Weight", 1.25, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(8).X + gateBoxes(8).Width / 2, ...
    "Y1", gateBoxes(8).Y, ...
    "X2", 420, ...
    "Y2", 120, ...
    "Color", colors.EvidenceLine, ...
    "Weight", 1.25, ...
    "Arrow", true, ...
    "Label", "", ...
    "LabelX", 0, ...
    "LabelY", 0, ...
    "LabelWidth", 0, ...
    "LabelHeight", 0, ...
    "LabelFontSize", 0, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", gateBoxes(10).X + gateBoxes(10).Width / 2, ...
    "Y1", gateBoxes(10).Y, ...
    "X2", 450, ...
    "Y2", 120, ...
    "Color", colors.EvidenceLine, ...
    "Weight", 1.25, ...
    "Arrow", true, ...
    "Label", "evidence", ...
    "LabelX", 416, ...
    "LabelY", 138, ...
    "LabelWidth", 70, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 8, ...
    "LabelAlign", "center" ...
);

lineIndex = lineIndex + 1;
slide1Lines(lineIndex) = struct( ...
    "X1", 465, ...
    "Y1", 102, ...
    "X2", 645, ...
    "Y2", 102, ...
    "Color", colors.EvidenceLine, ...
    "Weight", 1.5, ...
    "Arrow", true, ...
    "Label", "approved outputs", ...
    "LabelX", 520, ...
    "LabelY", 84, ...
    "LabelWidth", 130, ...
    "LabelHeight", 14, ...
    "LabelFontSize", 8, ...
    "LabelAlign", "center" ...
);

slide1Lines = slide1Lines(1:lineIndex);

slide2Boxes = [ ...
    struct( ...
        "Id", "SRC", ...
        "Text", sprintf("Source markdown\n%s", relativeMarkdownPath), ...
        "X", 48, ...
        "Y", 188, ...
        "Width", 180, ...
        "Height", 82, ...
        "FillColor", colors.LaneFill, ...
        "LineColor", colors.LaneLine, ...
        "FontSize", 13, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "GEN", ...
        "Text", char(strjoin([ ...
            "MATLAB generator", ...
            "generatePipelineFlowchartPpt.m" ...
        ], newline)), ...
        "X", 278, ...
        "Y", 188, ...
        "Width", 190, ...
        "Height", 82, ...
        "FillColor", colors.GateFill, ...
        "LineColor", colors.GateLine, ...
        "FontSize", 13, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "ART", ...
        "Text", sprintf("Editable PPT artifact\n%s", relativeOutputPath), ...
        "X", 522, ...
        "Y", 188, ...
        "Width", 190, ...
        "Height", 82, ...
        "FillColor", colors.OutcomeFill, ...
        "LineColor", colors.OutcomeLine, ...
        "FontSize", 13, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
    struct( ...
        "Id", "LOOP", ...
        "Text", char(strjoin([ ...
            "Update loop", ...
            "edit markdown -> rerun", ...
            "generator -> review" ...
        ], newline)), ...
        "X", 760, ...
        "Y", 188, ...
        "Width", 160, ...
        "Height", 82, ...
        "FillColor", colors.SupportFill, ...
        "LineColor", colors.SupportLine, ...
        "FontSize", 13, ...
        "Bold", true, ...
        "FontColor", colors.Text, ...
        "ShapeType", 1, ...
        "Align", "center" ...
    ) ...
];

slide2Texts = [ ...
    struct( ...
        "Text", "PowerPoint Conversion Pipeline", ...
        "X", 24, ...
        "Y", 16, ...
        "Width", 912, ...
        "Height", 22, ...
        "FontSize", 24, ...
        "Bold", true, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
    struct( ...
        "Text", "Repo-controlled source of truth and regeneration path", ...
        "X", 24, ...
        "Y", 42, ...
        "Width", 912, ...
        "Height", 16, ...
        "FontSize", 11, ...
        "Bold", false, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", "", ...
        "LineColor", "" ...
    ) ...
    struct( ...
        "Text", char(strjoin([ ...
            "Regeneration notes", ...
            "- Markdown remains the human-editable source of truth.", ...
            "- The generator reuses the node labels from the Mermaid block and applies a stable PowerPoint layout.", ...
            "- PowerPoint for Windows is required because the deck is created through MATLAB COM automation." ...
        ], newline)), ...
        "X", 48, ...
        "Y", 318, ...
        "Width", 872, ...
        "Height", 90, ...
        "FontSize", 12, ...
        "Bold", false, ...
        "Italic", false, ...
        "Align", "left", ...
        "FontColor", colors.Text, ...
        "FillColor", colors.NoteFill, ...
        "LineColor", colors.NoteLine ...
    ) ...
];

slide2Lines = [ ...
    struct( ...
        "X1", 228, ...
        "Y1", 229, ...
        "X2", 278, ...
        "Y2", 229, ...
        "Color", colors.PassLine, ...
        "Weight", 2.25, ...
        "Arrow", true, ...
        "Label", "", ...
        "LabelX", 0, ...
        "LabelY", 0, ...
        "LabelWidth", 0, ...
        "LabelHeight", 0, ...
        "LabelFontSize", 0, ...
        "LabelAlign", "center" ...
    ) ...
    struct( ...
        "X1", 468, ...
        "Y1", 229, ...
        "X2", 522, ...
        "Y2", 229, ...
        "Color", colors.PassLine, ...
        "Weight", 2.25, ...
        "Arrow", true, ...
        "Label", "", ...
        "LabelX", 0, ...
        "LabelY", 0, ...
        "LabelWidth", 0, ...
        "LabelHeight", 0, ...
        "LabelFontSize", 0, ...
        "LabelAlign", "center" ...
    ) ...
    struct( ...
        "X1", 712, ...
        "Y1", 229, ...
        "X2", 760, ...
        "Y2", 229, ...
        "Color", colors.PassLine, ...
        "Weight", 2.25, ...
        "Arrow", true, ...
        "Label", "", ...
        "LabelX", 0, ...
        "LabelY", 0, ...
        "LabelWidth", 0, ...
        "LabelHeight", 0, ...
        "LabelFontSize", 0, ...
        "LabelAlign", "center" ...
    ) ...
];

layout = struct;
layout.Slides = [ ...
    struct( ...
        "Title", "Pipeline Flowchart", ...
        "Boxes", slide1Boxes, ...
        "Texts", slide1Texts, ...
        "Lines", slide1Lines ...
    ) ...
    struct( ...
        "Title", "Conversion Pipeline", ...
        "Boxes", slide2Boxes, ...
        "Texts", slide2Texts, ...
        "Lines", slide2Lines ...
    ) ...
];
end
