function results = runG4PassiveBaselineMap(datasetId, repoRoot, options)
%RUNG4PASSIVEBASELINEMAP Execute the Stage 4 manual-review runner.
%
%   RESULTS = RUNG4PASSIVEBASELINEMAP() runs the current Stage 4 passive
%   baseline map review and writes an evidence bundle under:
%   artifacts/<datasetId>/G4_Passive_Baseline_Map/<runTimestampZ>/
%
%   This runner formalizes the implemented G4 helper slice. It does not
%   emit a formal pass / retune / reject gate decision.

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

totalTimer = tic;
stepTimer = tic;
stageArtifactId = "G4_Passive_Baseline_Map";
repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
[g4Options, runnerOptions] = localResolveRunnerOptions(options);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
bundleRoot = fullfile(repoRoot, "artifacts", datasetId, stageArtifactId, ...
    runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");
timingRows = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", 0.0, runnerOptions.ExecutionMode);
timingRows(1) = [];
timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", toc(stepTimer), runnerOptions.ExecutionMode, ...
    NaN, NaN, NaN, NaN, NaN, "");

fprintf("Running G4 Passive Baseline Map manual review for dataset %s\n", ...
    datasetId);
fprintf("Repository root:\t%s\n", repoRoot);
fprintf("Execution mode:\t%s\n", runnerOptions.ExecutionMode);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);

    stepTimer = tic;
    loadOptions = struct();
    loadOptions.IncludeSamples = true;
    sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    inputRepetitionCount = double(numel(sessionData.RadarScans));
    inputSampleCount = double(sum([sessionData.RadarScans.NumSamples]));
    collectionMetadataPath = fullfile(sessionData.DatasetRoot, ...
        "collection_metadata.json");
    collectionMetadataInfo = helperReadCollectionMetadata( ...
        collectionMetadataPath, datasetId);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "load_session_with_samples", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "loadIQData IncludeSamples=true plus collection metadata parse.");

    stepTimer = tic;
    if isempty(fieldnames(runnerOptions.G3SyncResults))
        g3SyncResults = helperAnalyzeG3SyncCore(sessionData, ...
            collectionMetadataInfo, runnerOptions.G3Options);
        g3ResolutionNote = "Computed G3 sync results from current session.";
    else
        g3SyncResults = runnerOptions.G3SyncResults;
        g3ResolutionNote = "Used supplied G3 sync results.";
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "resolve_g3_sync_results", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, g3ResolutionNote);

    stepTimer = tic;
    analysis = helperAnalyzeG4PassiveBaselineMap(sessionData, ...
        collectionMetadataInfo, g3SyncResults, g4Options);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "run_g4_passive_baseline_helper", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "G4 passive-baseline map analysis helper.");

    stepTimer = tic;
    reviewSummaryTable = localBuildReviewSummaryTable(analysis);
    interpretationSummaryTable = localBuildInterpretationSummaryTable( ...
        analysis);
    cpiDefinitionsTable = localBuildCpiDefinitionTable(analysis);
    cpiComparisonTable = localBuildCpiComparisonTable(analysis);
    mapLabelCountsTable = localBuildMapLabelCountTable( ...
        analysis.MapSummaryTable);
    sceneMetricMediansTable = localBuildSceneMetricMedianTable( ...
        analysis.MapSummaryTable);
    representativeMapIndexTable = localBuildRepresentativeMapIndexTable( ...
        analysis.RepresentativeMaps);
    comparisonSummaryTable = localBuildComparisonSummaryTable(analysis);

    configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
        bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
        runnerOptions, reviewSummaryTable);
    metricsJson = localBuildMetricsJson(runTimestampZ, bundleRoot, ...
        analysis, reviewSummaryTable);
    comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
        runTimestampZ, bundleRoot, collectionMetadataInfo, analysis, ...
        comparisonSummaryTable);
    summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
        collectionMetadataInfo, analysis, reviewSummaryTable);
    interpretationNoteLines = localBuildInterpretationNoteLines( ...
        analysis, reviewSummaryTable);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "build_review_artifacts", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "Review tables, snapshots, metrics JSON, and text payloads.");

    summaryPath = fullfile(bundleRoot, "summary.md");
    interpretationNotePath = fullfile(bundleRoot, ...
        "passive_baseline_interpretation_note.md");
    configSnapshotPath = fullfile(bundleRoot, "config_snapshot.json");
    metricsJsonPath = fullfile(bundleRoot, "metrics.json");
    metricsMatPath = fullfile(bundleRoot, "metrics.mat");
    rawMapFigurePath = fullfile(figureRoot, ...
        "figure_01_representative_maps_raw_axis.png");
    displayMapFigurePath = fullfile(figureRoot, ...
        "figure_02_representative_maps_display_axis.png");
    directPathFigurePath = fullfile(figureRoot, ...
        "figure_03_direct_path_trends.png");

    stepTimer = tic;
    localWriteRunnerTables(bundleRoot, reviewSummaryTable, ...
        interpretationSummaryTable, cpiDefinitionsTable, ...
        cpiComparisonTable, mapLabelCountsTable, sceneMetricMediansTable, ...
        representativeMapIndexTable, comparisonSummaryTable, analysis);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_tables", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 13, 0, NaN, ...
        "Current Stage 4 CSV table artifact set.");

    stepTimer = tic;
    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(interpretationNotePath, interpretationNoteLines);
    localWriteJsonFile(configSnapshotPath, configSnapshot);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_text_artifacts", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 3, 0, NaN, ...
        "summary.md; passive baseline note; config_snapshot.json");

    stepTimer = tic;
    localWriteJsonFile(metricsJsonPath, metricsJson);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_metrics_json", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 1, 0, NaN, "metrics.json");

    stepTimer = tic;
    localWriteMetricsMat(metricsMatPath, analysis, g3SyncResults);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_metrics_mat", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 1, 0, NaN, ...
        "metrics.mat");

    stepTimer = tic;
    try
        comparisonSnapshotPath = helperWriteComparisonSnapshot( ...
            string(bundleRoot), comparisonSnapshot);
    catch saveException
        error("runG4PassiveBaselineMap:SaveComparisonSnapshotFailed", ...
            "Failed to write Stage 4 comparison snapshot: %s", ...
            saveException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_comparison_snapshot", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 1, 0, NaN, "comparison_snapshot.mat");

    stepTimer = tic;
    localRenderRepresentativeMapFigure(analysis.RepresentativeMaps, ...
        "raw", rawMapFigurePath, runnerOptions.ShowFigures);
    localRenderRepresentativeMapFigure(analysis.RepresentativeMaps, ...
        "display", displayMapFigurePath, runnerOptions.ShowFigures);
    localRenderDirectPathTrendFigure(analysis.MapSummaryTable, ...
        directPathFigurePath, runnerOptions.ShowFigures);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "render_figures", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 3, 3, NaN, ...
        "Raw-axis maps, display-axis maps, and direct-path trends.");

    [timingSummaryTable, performanceSummary] = ...
        helperFinalizePerformanceInstrumentation(stageArtifactId, ...
        datasetId, string(bundleRoot), runTimestampZ, ...
        runnerOptions.ExecutionMode, runnerOptions.ShowFigures, ...
        timingRows, totalTimer, inputSampleCount, ...
        inputRepetitionCount, string(metricsMatPath));

    results = localBuildResults(datasetId, stageArtifactId, runTimestampZ, ...
        bundleRoot, analysis, reviewSummaryTable, ...
        interpretationSummaryTable, comparisonSnapshotPath, ...
        [string(rawMapFigurePath); string(displayMapFigurePath); ...
        string(directPathFigurePath)], timingSummaryTable, ...
        performanceSummary);

    fprintf("Overall label:\t%s\n", results.OverallLabel);
    fprintf("Analysis execution:\t%s\n", ...
        results.AnalysisExecutionAssessment);
    fprintf("Limitation source:\t%s\n", results.LimitationSourceLabel);
    fprintf("Recommended CPI:\t%s\n", ...
        results.RecommendedBaselineCpiLabel);
    fprintf("Full-rate audit agreement:\t%s\n", ...
        results.FullRateAuditAgreementLabel);
    fprintf("Bundle root:\t%s\n", bundleRoot);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end
function [g4Options, runnerOptions] = localResolveRunnerOptions(options)

g4Options = options;
runnerOptions = struct();
runnerOptions.ExecutionMode = helperResolveExecutionMode(options);
runnerOptions.ShowFigures = usejava("desktop");
runnerOptions.G3SyncResults = struct();
runnerOptions.G3Options = struct();

if runnerOptions.ExecutionMode == "analysis_only"
    runnerOptions.ShowFigures = false;
end

if isfield(g4Options, "G4Options")
    explicitG4Options = g4Options.G4Options;
    g4Options = rmfield(g4Options, "G4Options");
    g4Options = localMergeStructs(g4Options, explicitG4Options);
end

if isfield(g4Options, "ShowFigures")
    runnerOptions.ShowFigures = logical(g4Options.ShowFigures);
    g4Options = rmfield(g4Options, "ShowFigures");
end

if isfield(g4Options, "G3SyncResults")
    runnerOptions.G3SyncResults = g4Options.G3SyncResults;
    g4Options = rmfield(g4Options, "G3SyncResults");
end

if isfield(g4Options, "G3Options")
    runnerOptions.G3Options = g4Options.G3Options;
    g4Options = rmfield(g4Options, "G3Options");
end

if isfield(g4Options, "ExecutionMode")
    g4Options = rmfield(g4Options, "ExecutionMode");
end

end

function mergedStruct = localMergeStructs(baseStruct, overrideStruct)

mergedStruct = baseStruct;
overrideFields = fieldnames(overrideStruct);

for idx = 1:numel(overrideFields)
    mergedStruct.(overrideFields{idx}) = overrideStruct.(overrideFields{idx});
end

end

function results = localBuildResults(datasetId, stageArtifactId, ...
    runTimestampZ, bundleRoot, analysis, reviewSummaryTable, ...
    interpretationSummaryTable, comparisonSnapshotPath, figurePaths, ...
    timingSummaryTable, performanceSummary)

results = struct();
results.DatasetId = datasetId;
results.StageId = stageArtifactId;
results.AnalysisStageId = string(analysis.StageId);
results.RunTimestampZ = runTimestampZ;
results.BundleRoot = string(bundleRoot);
results.OverallLabel = string(analysis.Interpretation.OverallLabel);
results.OverallRationale = string(analysis.Interpretation.OverallRationale);
results.AnalysisExecutionAssessment = ...
    reviewSummaryTable.AnalysisExecutionAssessment(1);
results.LimitationSourceLabel = reviewSummaryTable.LimitationSourceLabel(1);
results.SceneObservabilityLabel = string( ...
    analysis.Interpretation.SceneObservabilityLabel);
results.ImplementationConfidenceLabel = string( ...
    analysis.Interpretation.ImplementationConfidenceLabel);
results.FullRateAuditAgreementLabel = string( ...
    analysis.Interpretation.FullRateAuditAgreementLabel);
results.RecommendedBaselineCpiLabel = string( ...
    analysis.RecommendedBaselineCpiLabel);
results.RecommendedBaselineCpiScope = string( ...
    analysis.Interpretation.RecommendedBaselineCpiScope);
results.ReferenceLabel = string(analysis.Interpretation.ReferenceLabel);
results.SurveillanceLabel = string(analysis.Interpretation.SurveillanceLabel);
results.QuestionSummaries = analysis.QuestionSummaries;
results.MapSummaryTable = analysis.MapSummaryTable;
results.RepeatabilityTable = analysis.RepeatabilityTable;
results.CpiSelectionTable = analysis.CpiSelectionTable;
results.FullRateAuditSummaryTable = analysis.FullRateAuditSummaryTable;
results.ReviewSummaryTable = reviewSummaryTable;
results.InterpretationSummaryTable = interpretationSummaryTable;
results.Interpretation = analysis.Interpretation;
results.Options = analysis.Options;
results.Analysis = analysis;
results.FigurePaths = figurePaths;
results.ComparisonSnapshotPath = string(comparisonSnapshotPath);
results.TimingSummaryTable = timingSummaryTable;
results.PerformanceSummary = performanceSummary;

end

function reviewSummary = localBuildReviewSummaryTable(analysis)

interpretation = analysis.Interpretation;
analysisExecutionAssessment = localResolveAnalysisExecutionAssessment( ...
    interpretation);
limitationSourceLabel = localResolveLimitationSourceLabel(interpretation);
manualReviewGuidance = localResolveManualReviewGuidance(interpretation);

reviewSummary = table( ...
    "G4_Passive_Baseline_Map", ...
    string(analysis.StageId), ...
    string(interpretation.OverallLabel), ...
    analysisExecutionAssessment, ...
    limitationSourceLabel, ...
    string(interpretation.SceneObservabilityLabel), ...
    string(interpretation.ImplementationConfidenceLabel), ...
    string(interpretation.FullRateAuditAgreementLabel), ...
    string(analysis.RecommendedBaselineCpiLabel), ...
    height(analysis.MapSummaryTable), ...
    height(analysis.RepeatabilityTable), ...
    height(analysis.CpiSelectionTable), ...
    height(analysis.FullRateAuditSummaryTable), ...
    string(interpretation.RecommendedBaselineCpiScope), ...
    manualReviewGuidance, ...
    VariableNames = {'StageId', 'AnalysisStageId', 'OverallLabel', ...
    'AnalysisExecutionAssessment', 'LimitationSourceLabel', ...
    'SceneObservabilityLabel', 'ImplementationConfidenceLabel', ...
    'FullRateAuditAgreementLabel', 'RecommendedBaselineCpiLabel', ...
    'MapSummaryRows', 'RepeatabilityRows', 'CpiSelectionRows', ...
    'FullRateAuditRows', 'RecommendedCpiScope', ...
    'ManualReviewGuidance'});

end

function assessment = localResolveAnalysisExecutionAssessment(interpretation)

if string(interpretation.ImplementationConfidenceLabel) == "blocked"
    assessment = "analysis_path_blocked";
else
    assessment = "analysis_executed_no_helper_failure";
end

end

function label = localResolveLimitationSourceLabel(interpretation)

sceneLabel = string(interpretation.SceneObservabilityLabel);
rateAuditLabel = string(interpretation.FullRateAuditAgreementLabel);
implementationLabel = string(interpretation.ImplementationConfidenceLabel);

if implementationLabel == "blocked"
    label = "analysis_or_implementation_blocked";
elseif sceneLabel == "blocked" && rateAuditLabel == "disagreement"
    label = "dataset_scene_limited_with_raw_rate_audit_disagreement";
elseif sceneLabel == "blocked"
    label = "dataset_scene_limited";
elseif rateAuditLabel == "disagreement"
    label = "raw_rate_audit_disagreement";
elseif string(interpretation.OverallLabel) == "ready"
    label = "none_ready";
else
    label = "mixed_caveat";
end

end

function guidance = localResolveManualReviewGuidance(interpretation)

implementationLabel = string(interpretation.ImplementationConfidenceLabel);
sceneLabel = string(interpretation.SceneObservabilityLabel);
rateAuditLabel = string(interpretation.FullRateAuditAgreementLabel);

if implementationLabel == "blocked"
    guidance = "Inspect G4 implementation confidence and direct-path " + ...
        "localization before attributing this result to the dataset.";
elseif sceneLabel == "blocked" || rateAuditLabel == "disagreement"
    guidance = "G4 executed successfully. Treat the block as current " + ...
        "dataset scene limitation or rate-preservation caveat, not as a " + ...
        "helper execution failure.";
else
    guidance = "G4 executed successfully and did not identify a dataset " + ...
        "scene limitation in the current runner slice.";
end

end
function interpretationSummary = localBuildInterpretationSummaryTable(analysis)

interpretation = analysis.Interpretation;
interpretationSummary = table( ...
    string(interpretation.OverallLabel), ...
    string(interpretation.OverallRationale), ...
    string(interpretation.UpstreamValidityLabel), ...
    string(interpretation.SceneObservabilityLabel), ...
    string(interpretation.ImplementationConfidenceLabel), ...
    string(interpretation.FullRateAuditAgreementLabel), ...
    strjoin(string(interpretation.CaveatCodes(:)), " | "), ...
    string(interpretation.ReferenceLabel), ...
    string(interpretation.SurveillanceLabel), ...
    string(analysis.RecommendedBaselineCpiLabel), ...
    string(interpretation.RecommendedBaselineCpiScope), ...
    double(interpretation.ImplementationSuspectFraction), ...
    double(interpretation.SceneLimitedMapFraction), ...
    double(interpretation.RepeatabilityBlockedCount), ...
    VariableNames = {'OverallLabel', 'OverallRationale', ...
    'UpstreamValidityLabel', 'SceneObservabilityLabel', ...
    'ImplementationConfidenceLabel', 'FullRateAuditAgreementLabel', ...
    'CaveatCodes', 'ReferenceLabel', 'SurveillanceLabel', ...
    'RecommendedBaselineCpiLabel', 'RecommendedBaselineCpiScope', ...
    'ImplementationSuspectFraction', 'SceneLimitedMapFraction', ...
    'RepeatabilityBlockedCount'});

end

function cpiDefinitionTable = localBuildCpiDefinitionTable(analysis)

cpiDefinitions = analysis.CpiDefinitions;
cpiCount = numel(cpiDefinitions);
cpiLabel = strings(cpiCount, 1);
duration_s = zeros(cpiCount, 1);
mapSamples = zeros(cpiCount, 1);
mapSampleRate_Hz = repmat(double(analysis.Options.MapSampleRateHz), ...
    cpiCount, 1);
mapDecimationFactor = repmat(double(analysis.Options.MapDecimationFactor), ...
    cpiCount, 1);

for idx = 1:cpiCount
    cpiLabel(idx) = string(cpiDefinitions(idx).Label);
    duration_s(idx) = double(cpiDefinitions(idx).Duration_s);
    mapSamples(idx) = double(cpiDefinitions(idx).MapSamples);
end

cpiDefinitionTable = table(cpiLabel, duration_s, mapSamples, ...
    mapSampleRate_Hz, mapDecimationFactor, VariableNames = {'CpiLabel', ...
    'Duration_s', 'MapSamples', 'MapSampleRate_Hz', ...
    'MapDecimationFactor'});

end

function cpiComparison = localBuildCpiComparisonTable(analysis)

cpiComparison = analysis.CpiSelectionTable(:, { ...
    'CpiLabel', ...
    'G3EligibilityLabel', ...
    'SceneObservabilityScore', ...
    'RepeatabilityScore', ...
    'CoordinateStabilityScore', ...
    'RateAuditAgreementLabel', ...
    'SensitivitySetMember', ...
    'SceneInterpretationLabel', ...
    'RepeatabilityInterpretationLabel', ...
    'ProvisionalRank' ...
    });

end

function mapLabelCounts = localBuildMapLabelCountTable(mapSummaryTable)

labelValues = unique(mapSummaryTable.InterpretationLabel);
labelValues = sort(labelValues);
labelCount = zeros(numel(labelValues), 1);

for idx = 1:numel(labelValues)
    labelCount(idx) = sum(mapSummaryTable.InterpretationLabel == ...
        labelValues(idx));
end

mapLabelCounts = table(labelValues, labelCount, VariableNames = ...
    {'InterpretationLabel', 'MapCount'});

end

function sceneMetricMedians = localBuildSceneMetricMedianTable(mapSummaryTable)

groupKeys = unique(mapSummaryTable(:, {'CpiLabel', 'WindowLabel'}), ...
    'rows');
rowCount = height(groupKeys);
cpiLabel = strings(rowCount, 1);
windowLabel = strings(rowCount, 1);
sceneObservabilityScore = zeros(rowCount, 1);
offOriginNonzeroDopplerEnergyFraction = zeros(rowCount, 1);
offOriginOccupiedFraction = zeros(rowCount, 1);
zeroDopplerRidgeEnergyFraction = zeros(rowCount, 1);
directPathToOffRidgeEnergy_dB = zeros(rowCount, 1);

for idx = 1:rowCount
    subset = mapSummaryTable(mapSummaryTable.CpiLabel == ...
        groupKeys.CpiLabel(idx) & mapSummaryTable.WindowLabel == ...
        groupKeys.WindowLabel(idx), :);
    cpiLabel(idx) = string(groupKeys.CpiLabel(idx));
    windowLabel(idx) = string(groupKeys.WindowLabel(idx));
    sceneObservabilityScore(idx) = median( ...
        subset.SceneObservabilityScore, "omitnan");
    offOriginNonzeroDopplerEnergyFraction(idx) = median( ...
        subset.OffOriginNonzeroDopplerEnergyFraction, "omitnan");
    offOriginOccupiedFraction(idx) = median( ...
        subset.OffOriginOccupiedFraction_abovePeakMinus20dB, "omitnan");
    zeroDopplerRidgeEnergyFraction(idx) = median( ...
        subset.ZeroDopplerRidgeEnergyFraction, "omitnan");
    directPathToOffRidgeEnergy_dB(idx) = median( ...
        subset.DirectPathToOffRidgeEnergy_dB, "omitnan");
end

sceneMetricMedians = table(cpiLabel, windowLabel, ...
    sceneObservabilityScore, offOriginNonzeroDopplerEnergyFraction, ...
    offOriginOccupiedFraction, zeroDopplerRidgeEnergyFraction, ...
    directPathToOffRidgeEnergy_dB, VariableNames = {'CpiLabel', ...
    'WindowLabel', 'SceneObservabilityScore', ...
    'OffOriginNonzeroDopplerEnergyFraction', ...
    'OffOriginOccupiedFraction_abovePeakMinus20dB', ...
    'ZeroDopplerRidgeEnergyFraction', ...
    'DirectPathToOffRidgeEnergy_dB'});
sceneMetricMedians = sortrows(sceneMetricMedians, ...
    {'CpiLabel', 'WindowLabel'});

end

function representativeMapIndex = localBuildRepresentativeMapIndexTable( ...
    representativeMaps)

mapCount = numel(representativeMaps);
cpiLabel = strings(mapCount, 1);
windowLabel = strings(mapCount, 1);
representativeRepetition = zeros(mapCount, 1);
directPathDelay_samples = zeros(mapCount, 1);
directPathDoppler_Hz = zeros(mapCount, 1);
mapRows = zeros(mapCount, 1);
mapColumns = zeros(mapCount, 1);

for idx = 1:mapCount
    representativeMap = representativeMaps(idx);
    cpiLabel(idx) = string(representativeMap.CpiLabel);
    windowLabel(idx) = string(representativeMap.WindowLabel);
    representativeRepetition(idx) = double( ...
        representativeMap.RepresentativeRepetition);
    directPathDelay_samples(idx) = double( ...
        representativeMap.DirectPathDelay_samples);
    directPathDoppler_Hz(idx) = double( ...
        representativeMap.DirectPathDoppler_Hz);
    mapRows(idx) = size(representativeMap.Map_dB, 1);
    mapColumns(idx) = size(representativeMap.Map_dB, 2);
end

representativeMapIndex = table(cpiLabel, windowLabel, ...
    representativeRepetition, directPathDelay_samples, ...
    directPathDoppler_Hz, mapRows, mapColumns, VariableNames = ...
    {'CpiLabel', 'WindowLabel', 'RepresentativeRepetition', ...
    'DirectPathDelay_samples', 'DirectPathDoppler_Hz', 'MapRows', ...
    'MapColumns'});

end
function comparisonSummary = localBuildComparisonSummaryTable(analysis)

rows = [ ...
    helperMakeComparisonMetricRow("overall_label", "Overall Label", ...
    analysis.Interpretation.OverallLabel, "", ...
    "Overall G4 manual-review interpretation."); ...
    helperMakeComparisonMetricRow("scene_observability_label", ...
    "Scene Observability Label", ...
    analysis.Interpretation.SceneObservabilityLabel, "", ...
    "Scene-first readiness label."); ...
    helperMakeComparisonMetricRow("implementation_confidence_label", ...
    "Implementation Confidence Label", ...
    analysis.Interpretation.ImplementationConfidenceLabel, "", ...
    "Direct-path localization and axis plausibility label."); ...
    helperMakeComparisonMetricRow("full_rate_audit_agreement_label", ...
    "Full-Rate Audit Agreement Label", ...
    analysis.Interpretation.FullRateAuditAgreementLabel, "", ...
    "Bounded raw-rate audit agreement label."); ...
    helperMakeComparisonMetricRow("recommended_baseline_cpi_label", ...
    "Recommended Baseline CPI Label", ...
    analysis.RecommendedBaselineCpiLabel, "", ...
    "Provisional G4 due-diligence CPI label, not a G6 freeze."); ...
    helperMakeComparisonMetricRow("map_summary_rows", ...
    "Map Summary Rows", height(analysis.MapSummaryTable), "rows", ...
    "Reduced-rate map summary row count."); ...
    helperMakeComparisonMetricRow("repeatability_rows", ...
    "Repeatability Rows", height(analysis.RepeatabilityTable), "rows", ...
    "Repeatability row count."); ...
    helperMakeComparisonMetricRow("full_rate_audit_rows", ...
    "Full-Rate Audit Rows", ...
    height(analysis.FullRateAuditSummaryTable), "rows", ...
    "Bounded raw-rate audit row count."); ...
    helperMakeComparisonMetricRow("implementation_suspect_fraction", ...
    "Implementation Suspect Fraction", ...
    analysis.Interpretation.ImplementationSuspectFraction, "fraction", ...
    "Fraction of reduced-rate maps labeled implementation suspect."); ...
    helperMakeComparisonMetricRow("scene_limited_map_fraction", ...
    "Scene-Limited Map Fraction", ...
    analysis.Interpretation.SceneLimitedMapFraction, "fraction", ...
    "Fraction of reduced-rate maps labeled scene limited."); ...
    helperMakeComparisonMetricRow("map_decimation_factor", ...
    "Map Decimation Factor", analysis.Options.MapDecimationFactor, ...
    "samples", "Main G4 reduced-rate decimation factor."); ...
    helperMakeComparisonMetricRow("map_sample_rate_hz", ...
    "Map Sample Rate", analysis.Options.MapSampleRateHz, "Hz", ...
    "Main G4 reduced-rate sample rate.") ...
    ];

comparisonSummary = struct2table(rows);
comparisonSummary.DisplayOrder = (1:height(comparisonSummary)).';

end

function configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
    bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
    runnerOptions, reviewSummaryTable)

configSnapshot = struct();
configSnapshot.dataset_id = datasetId;
configSnapshot.stage_id = "G4_Passive_Baseline_Map";
configSnapshot.analysis_stage_id = string(analysis.StageId);
configSnapshot.entry_point = "runG4PassiveBaselineMap";
configSnapshot.repo_root = repoRoot;
configSnapshot.bundle_root = string(bundleRoot);
configSnapshot.run_timestamp_z = runTimestampZ;
configSnapshot.collection_metadata_path = ...
    collectionMetadataInfo.MetadataPath;
configSnapshot.collection_metadata_present = ...
    collectionMetadataInfo.MetadataPresent;
configSnapshot.collection_metadata_session_id_matches = ...
    collectionMetadataInfo.SessionIdMatches;
configSnapshot.show_figures = runnerOptions.ShowFigures;
configSnapshot.execution_mode = runnerOptions.ExecutionMode;
configSnapshot.used_supplied_g3_sync_results = ...
    ~isempty(fieldnames(runnerOptions.G3SyncResults));
configSnapshot.overall_label = analysis.Interpretation.OverallLabel;
configSnapshot.analysis_execution_assessment = ...
    reviewSummaryTable.AnalysisExecutionAssessment(1);
configSnapshot.limitation_source_label = ...
    reviewSummaryTable.LimitationSourceLabel(1);
configSnapshot.scene_observability_label = ...
    analysis.Interpretation.SceneObservabilityLabel;
configSnapshot.implementation_confidence_label = ...
    analysis.Interpretation.ImplementationConfidenceLabel;
configSnapshot.full_rate_audit_agreement_label = ...
    analysis.Interpretation.FullRateAuditAgreementLabel;
configSnapshot.recommended_baseline_cpi_label = ...
    analysis.RecommendedBaselineCpiLabel;
configSnapshot.recommended_baseline_cpi_scope = ...
    analysis.Interpretation.RecommendedBaselineCpiScope;
configSnapshot.reference_label = analysis.Interpretation.ReferenceLabel;
configSnapshot.surveillance_label = ...
    analysis.Interpretation.SurveillanceLabel;
configSnapshot.map_rate_mode = analysis.Options.MapRateMode;
configSnapshot.map_decimation_factor = analysis.Options.MapDecimationFactor;
configSnapshot.map_sample_rate_hz = analysis.Options.MapSampleRateHz;
configSnapshot.full_rate_audit_method = analysis.Options.FullRateAuditMethod;
configSnapshot.analysis_options = analysis.Options;
configSnapshot.matlab_version = string(version);
configSnapshot.matlab_release = string(version("-release"));
configSnapshot.computer = string(computer);

end

function metricsJson = localBuildMetricsJson(runTimestampZ, bundleRoot, ...
    analysis, reviewSummaryTable)

metricsJson = struct();
metricsJson.stage_id = "G4_Passive_Baseline_Map";
metricsJson.analysis_stage_id = string(analysis.StageId);
metricsJson.run_timestamp_z = runTimestampZ;
metricsJson.bundle_root = string(bundleRoot);
metricsJson.overall_label = analysis.Interpretation.OverallLabel;
metricsJson.overall_rationale = analysis.Interpretation.OverallRationale;
metricsJson.analysis_execution_assessment = ...
    reviewSummaryTable.AnalysisExecutionAssessment(1);
metricsJson.limitation_source_label = ...
    reviewSummaryTable.LimitationSourceLabel(1);
metricsJson.scene_observability_label = ...
    analysis.Interpretation.SceneObservabilityLabel;
metricsJson.implementation_confidence_label = ...
    analysis.Interpretation.ImplementationConfidenceLabel;
metricsJson.full_rate_audit_agreement_label = ...
    analysis.Interpretation.FullRateAuditAgreementLabel;
metricsJson.recommended_baseline_cpi_label = ...
    analysis.RecommendedBaselineCpiLabel;
metricsJson.map_summary_rows = height(analysis.MapSummaryTable);
metricsJson.repeatability_rows = height(analysis.RepeatabilityTable);
metricsJson.cpi_selection_rows = height(analysis.CpiSelectionTable);
metricsJson.full_rate_audit_rows = height(analysis.FullRateAuditSummaryTable);
metricsJson.implementation_suspect_fraction = ...
    analysis.Interpretation.ImplementationSuspectFraction;
metricsJson.scene_limited_map_fraction = ...
    analysis.Interpretation.SceneLimitedMapFraction;
metricsJson.repeatability_blocked_count = ...
    analysis.Interpretation.RepeatabilityBlockedCount;
metricsJson.map_rate_mode = analysis.Options.MapRateMode;
metricsJson.map_decimation_factor = analysis.Options.MapDecimationFactor;
metricsJson.map_sample_rate_hz = analysis.Options.MapSampleRateHz;
metricsJson.full_rate_audit_method = analysis.Options.FullRateAuditMethod;

end

function comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
    runTimestampZ, bundleRoot, collectionMetadataInfo, analysis, ...
    comparisonSummaryTable)

comparisonSnapshot = struct();
comparisonSnapshot.DatasetId = string(datasetId);
comparisonSnapshot.StageId = "G4_Passive_Baseline_Map";
comparisonSnapshot.AnalysisStageId = string(analysis.StageId);
comparisonSnapshot.RunTimestampZ = string(runTimestampZ);
comparisonSnapshot.BundleRoot = string(bundleRoot);
comparisonSnapshot.CollectionMetadataPath = ...
    string(collectionMetadataInfo.MetadataPath);
comparisonSnapshot.OverallLabel = string( ...
    analysis.Interpretation.OverallLabel);
comparisonSnapshot.OverallRationale = string( ...
    analysis.Interpretation.OverallRationale);
comparisonSnapshot.SceneObservabilityLabel = string( ...
    analysis.Interpretation.SceneObservabilityLabel);
comparisonSnapshot.ImplementationConfidenceLabel = string( ...
    analysis.Interpretation.ImplementationConfidenceLabel);
comparisonSnapshot.FullRateAuditAgreementLabel = string( ...
    analysis.Interpretation.FullRateAuditAgreementLabel);
comparisonSnapshot.RecommendedBaselineCpiLabel = string( ...
    analysis.RecommendedBaselineCpiLabel);
comparisonSnapshot.RecommendedBaselineCpiScope = string( ...
    analysis.Interpretation.RecommendedBaselineCpiScope);
comparisonSnapshot.ReferenceLabel = string( ...
    analysis.Interpretation.ReferenceLabel);
comparisonSnapshot.SurveillanceLabel = string( ...
    analysis.Interpretation.SurveillanceLabel);
comparisonSnapshot.QuestionSummaries = analysis.QuestionSummaries;
comparisonSnapshot.CpiSelectionTable = analysis.CpiSelectionTable;
comparisonSnapshot.FullRateAuditSummaryTable = ...
    analysis.FullRateAuditSummaryTable;
comparisonSnapshot.SummaryTable = comparisonSummaryTable;

end
function localWriteRunnerTables(bundleRoot, reviewSummaryTable, ...
    interpretationSummaryTable, cpiDefinitionsTable, cpiComparisonTable, ...
    mapLabelCountsTable, sceneMetricMediansTable, ...
    representativeMapIndexTable, comparisonSummaryTable, analysis)

try
    writetable(reviewSummaryTable, fullfile(bundleRoot, ...
        "review_summary.csv"));
    writetable(analysis.QuestionSummaries, fullfile(bundleRoot, ...
        "question_summaries.csv"));
    writetable(analysis.MapSummaryTable, fullfile(bundleRoot, ...
        "map_summary_table.csv"));
    writetable(analysis.RepeatabilityTable, fullfile(bundleRoot, ...
        "repeatability_table.csv"));
    writetable(analysis.CpiSelectionTable, fullfile(bundleRoot, ...
        "cpi_selection_table.csv"));
    writetable(analysis.FullRateAuditSummaryTable, fullfile(bundleRoot, ...
        "full_rate_audit_summary_table.csv"));
    writetable(interpretationSummaryTable, fullfile(bundleRoot, ...
        "interpretation_summary.csv"));
    writetable(cpiDefinitionsTable, fullfile(bundleRoot, ...
        "cpi_definitions.csv"));
    writetable(cpiComparisonTable, fullfile(bundleRoot, ...
        "cpi_comparison.csv"));
    writetable(mapLabelCountsTable, fullfile(bundleRoot, ...
        "map_label_counts.csv"));
    writetable(sceneMetricMediansTable, fullfile(bundleRoot, ...
        "scene_metric_medians.csv"));
    writetable(representativeMapIndexTable, fullfile(bundleRoot, ...
        "representative_map_index.csv"));
    writetable(comparisonSummaryTable, fullfile(bundleRoot, ...
        "comparison_summary.csv"));
catch writeTableException
    error("runG4PassiveBaselineMap:WriteTableFailed", ...
        "Failed to write a Stage 4 table artifact: %s", ...
        writeTableException.message);
end

end

function localWriteMetricsMat(metricsMatPath, analysis, g3SyncResults)

try
    save(metricsMatPath, "analysis", "g3SyncResults");
catch saveException
    error("runG4PassiveBaselineMap:SaveMetricsFailed", ...
        "Failed to write Stage 4 metrics.mat: %s", ...
        saveException.message);
end

end

function summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
    collectionMetadataInfo, analysis, reviewSummaryTable)

summaryLines = [ ...
    "# G4 Passive Baseline Map Summary"; ...
    ""; ...
    sprintf("- Dataset: `%s`", analysis.DatasetId); ...
    "- Scope: `G4_Passive_Baseline_Map` manual-review runner"; ...
    "- Entry point: `runG4PassiveBaselineMap`"; ...
    "- Formal gate decision: not emitted by this runner"; ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    sprintf("- Overall label: `%s`", ...
    analysis.Interpretation.OverallLabel); ...
    sprintf("- Overall rationale: %s", ...
    analysis.Interpretation.OverallRationale); ...
    sprintf("- Analysis execution assessment: `%s`", ...
    reviewSummaryTable.AnalysisExecutionAssessment(1)); ...
    sprintf("- Limitation source: `%s`", ...
    reviewSummaryTable.LimitationSourceLabel(1)); ...
    sprintf("- Recommended baseline CPI: `%s`", ...
    analysis.RecommendedBaselineCpiLabel); ...
    sprintf("- Recommended CPI scope: `%s`", ...
    analysis.Interpretation.RecommendedBaselineCpiScope); ...
    sprintf("- Collection metadata path: `%s`", ...
    collectionMetadataInfo.MetadataPath); ...
    ""; ...
    "## Question Summary"; ...
    localBuildQuestionSummaryLines(analysis.QuestionSummaries); ...
    ""; ...
    "## Key Findings"; ...
    sprintf("- Map summary rows: `%d`", ...
    height(analysis.MapSummaryTable)); ...
    sprintf("- Repeatability rows: `%d`", ...
    height(analysis.RepeatabilityTable)); ...
    sprintf("- CPI selection rows: `%d`", ...
    height(analysis.CpiSelectionTable)); ...
    sprintf("- Full-rate audit rows: `%d`", ...
    height(analysis.FullRateAuditSummaryTable)); ...
    sprintf("- Full-rate audit method: `%s`", ...
    analysis.Options.FullRateAuditMethod); ...
    sprintf("- Full-rate audit agreement: `%s`", ...
    analysis.Interpretation.FullRateAuditAgreementLabel); ...
    sprintf("- Scene-limited map fraction: `%.3f`", ...
    analysis.Interpretation.SceneLimitedMapFraction); ...
    sprintf("- Implementation-suspect map fraction: `%.3f`", ...
    analysis.Interpretation.ImplementationSuspectFraction); ...
    ""; ...
    "## Output Files"; ...
    "- `review_summary.csv`"; ...
    "- `question_summaries.csv`"; ...
    "- `map_summary_table.csv`"; ...
    "- `repeatability_table.csv`"; ...
    "- `cpi_selection_table.csv`"; ...
    "- `full_rate_audit_summary_table.csv`"; ...
    "- `interpretation_summary.csv`"; ...
    "- `cpi_definitions.csv`"; ...
    "- `cpi_comparison.csv`"; ...
    "- `map_label_counts.csv`"; ...
    "- `scene_metric_medians.csv`"; ...
    "- `representative_map_index.csv`"; ...
    "- `comparison_summary.csv`"; ...
    "- `passive_baseline_interpretation_note.md`"; ...
    "- `config_snapshot.json`"; ...
    "- `metrics.json`"; ...
    "- `metrics.mat`"; ...
    "- `timing_summary.csv`"; ...
    "- `performance_summary.json`"; ...
    "- `comparison_snapshot.mat`"; ...
    "- `figures/figure_01_representative_maps_raw_axis.png`"; ...
    "- `figures/figure_02_representative_maps_display_axis.png`"; ...
    "- `figures/figure_03_direct_path_trends.png`" ...
    ];

end

function questionSummaryLines = localBuildQuestionSummaryLines( ...
    questionSummaries)

questionCount = height(questionSummaries);
questionSummaryLines = strings(questionCount, 1);

for idx = 1:questionCount
    questionSummaryLines(idx) = sprintf("- `%s` (`%s`): %s | metrics: %s", ...
        string(questionSummaries.QuestionId(idx)), ...
        string(questionSummaries.InterpretationLabel(idx)), ...
        string(questionSummaries.QuestionText(idx)), ...
        string(questionSummaries.SummaryMetrics(idx)));
end

end

function interpretationNoteLines = localBuildInterpretationNoteLines( ...
    analysis, reviewSummaryTable)

if analysis.Interpretation.ImplementationConfidenceLabel == "blocked"
    reviewerGuidanceLines = [ ...
        "- The implementation confidence label is blocked."; ...
        "- Inspect direct-path localization, axis plausibility, and G3 correction assumptions before treating this as a dataset-only issue." ...
        ];
elseif analysis.Interpretation.SceneObservabilityLabel == "blocked" || ...
        analysis.Interpretation.FullRateAuditAgreementLabel == "disagreement"
    reviewerGuidanceLines = [ ...
        "- The G4 helper executed and preserved direct-path localization."; ...
        "- The current block is attributed to dataset scene limitation or reduced-rate/raw-rate disagreement, not a helper execution crash."; ...
        "- A downstream phase may consume the bundle as evidence, but it should not treat the recommended CPI as a G6 freeze." ...
        ];
else
    reviewerGuidanceLines = [ ...
        "- The G4 helper executed without a dataset-scene block in this runner slice."; ...
        "- The recommended CPI remains provisional G4 due diligence until G6 freezes detector-facing integration policy." ...
        ];
end

interpretationNoteLines = [ ...
    "# Passive Baseline Interpretation Note"; ...
    ""; ...
    sprintf("- Current overall label: `%s`", ...
    analysis.Interpretation.OverallLabel); ...
    sprintf("- Overall rationale: %s", ...
    analysis.Interpretation.OverallRationale); ...
    sprintf("- Analysis execution assessment: `%s`", ...
    reviewSummaryTable.AnalysisExecutionAssessment(1)); ...
    sprintf("- Limitation source: `%s`", ...
    reviewSummaryTable.LimitationSourceLabel(1)); ...
    sprintf("- Scene observability label: `%s`", ...
    analysis.Interpretation.SceneObservabilityLabel); ...
    sprintf("- Implementation confidence label: `%s`", ...
    analysis.Interpretation.ImplementationConfidenceLabel); ...
    sprintf("- Full-rate audit agreement label: `%s`", ...
    analysis.Interpretation.FullRateAuditAgreementLabel); ...
    sprintf("- Recommended baseline CPI: `%s`", ...
    analysis.RecommendedBaselineCpiLabel); ...
    sprintf("- Recommended CPI scope: `%s`", ...
    analysis.Interpretation.RecommendedBaselineCpiScope); ...
    ""; ...
    "## Question Assessments"; ...
    localBuildQuestionAssessmentLines(analysis.QuestionSummaries); ...
    ""; ...
    "## Reviewer Guidance"; ...
    reviewerGuidanceLines ...
    ];

end

function questionAssessmentLines = localBuildQuestionAssessmentLines( ...
    questionSummaries)

questionCount = height(questionSummaries);
questionAssessmentLines = strings(questionCount, 1);

for idx = 1:questionCount
    questionAssessmentLines(idx) = sprintf("- `%s` (`%s`): %s", ...
        string(questionSummaries.QuestionId(idx)), ...
        string(questionSummaries.InterpretationLabel(idx)), ...
        string(questionSummaries.Rationale(idx)));
end

end
function localRenderRepresentativeMapFigure(representativeMaps, axisMode, ...
    figurePath, showFigures)

axisMode = string(axisMode);
figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G4 Passive Baseline Representative Maps", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
layoutHandle = tiledlayout(3, 5, "TileSpacing", "compact", ...
    "Padding", "compact");

for idx = 1:numel(representativeMaps)
    nexttile(layoutHandle);
    representativeMap = representativeMaps(idx);

    if axisMode == "display"
        delayAxis = representativeMap.DisplayDelayAxis_samples;
        dopplerAxis = representativeMap.DisplayDopplerAxis_Hz;
        axisLabel = "display";
    else
        delayAxis = representativeMap.DelayAxis_samples;
        dopplerAxis = representativeMap.DopplerAxis_Hz;
        axisLabel = "raw";
    end

    imagesc(delayAxis, dopplerAxis, representativeMap.Map_dB);
    axis xy
    xlabel("Delay [samples]");
    ylabel("Doppler [Hz]");
    title(sprintf("%s %s %s", string(representativeMap.CpiLabel), ...
        string(representativeMap.WindowLabel), axisLabel));
    colorbar;
end

drawnow
localExportGraphics(layoutHandle, figurePath);
clear cleanupObject

end

function localRenderDirectPathTrendFigure(mapSummaryTable, figurePath, ...
    showFigures)

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G4 Passive Baseline Direct Path Trends", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
layoutHandle = tiledlayout(2, 1, "TileSpacing", "compact", ...
    "Padding", "compact");
cpiLabels = unique(mapSummaryTable.CpiLabel);
colorMap = lines(numel(cpiLabels));

nexttile(layoutHandle);
hold on
for idx = 1:numel(cpiLabels)
    subset = sortrows(mapSummaryTable(mapSummaryTable.CpiLabel == ...
        cpiLabels(idx) & mapSummaryTable.WindowLabel == "center", :), ...
        "Repetition");
    plot(subset.Repetition, subset.RawDirectPathDelayOffset_samples, ...
        "-o", "Color", colorMap(idx, :), "DisplayName", cpiLabels(idx));
end
hold off
grid on
xlabel("Repetition");
ylabel("Raw direct-path delay [samples]");
title("G4 Center-Window Direct-Path Delay Trend");
legend("Location", "best");

nexttile(layoutHandle);
hold on
for idx = 1:numel(cpiLabels)
    subset = sortrows(mapSummaryTable(mapSummaryTable.CpiLabel == ...
        cpiLabels(idx) & mapSummaryTable.WindowLabel == "center", :), ...
        "Repetition");
    plot(subset.Repetition, subset.RawDirectPathDopplerOffset_Hz, ...
        "-o", "Color", colorMap(idx, :), "DisplayName", cpiLabels(idx));
end
hold off
grid on
xlabel("Repetition");
ylabel("Raw direct-path Doppler [Hz]");
title("G4 Center-Window Direct-Path Doppler Trend");
legend("Location", "best");
drawnow

localExportGraphics(layoutHandle, figurePath);
clear cleanupObject

end

function localExportGraphics(exportTarget, figurePath)

try
    exportgraphics(exportTarget, figurePath);
catch exportException
    error("runG4PassiveBaselineMap:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, ...
        exportException.message);
end

end

function visibility = localResolveFigureVisibility(showFigures)

if showFigures
    visibility = "on";
else
    visibility = "off";
end

end

function cleanupObject = localCreateFigureCleanup(figureHandle, showFigures)

if showFigures
    cleanupObject = [];
    return
end

cleanupObject = onCleanup(@() close(figureHandle));

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG4PassiveBaselineMap:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

try
    fileIdentifier = fopen(filePath, "w");
catch openException
    error("runG4PassiveBaselineMap:OpenTextFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        openException.message);
end

if fileIdentifier == -1
    error("runG4PassiveBaselineMap:OpenTextFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileIdentifier));
lines = string(lines);

for idx = 1:numel(lines)
    fprintf(fileIdentifier, "%s\n", lines(idx));
end

clear cleanupObject

end

function localWriteJsonFile(filePath, inputStruct)

try
    jsonText = jsonencode(inputStruct, PrettyPrint = true);
catch encodeException
    error("runG4PassiveBaselineMap:JsonEncodeFailed", ...
        "Failed to encode JSON for %s: %s", filePath, ...
        encodeException.message);
end

localWriteTextFile(filePath, jsonText);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return
end

if ~isfolder(bundleRoot)
    try
        mkdir(bundleRoot);
    catch
        return
    end
end

try
    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G4 Passive Baseline Map Summary"; ...
        ""; ...
        "- Stage status: `failed`"; ...
        sprintf("- Failure message: `%s`", mainException.message); ...
        "- See `failure_cause.txt` for the captured exception details." ...
        ]);
catch
end

stackLines = strings(numel(mainException.stack), 1);

for idx = 1:numel(mainException.stack)
    stackFrame = mainException.stack(idx);
    stackLines(idx) = sprintf("%s (line %d)", ...
        string(stackFrame.name), double(stackFrame.line));
end

if isempty(stackLines)
    stackLines = "none";
end

try
    localWriteTextFile(fullfile(bundleRoot, "failure_cause.txt"), [ ...
        "Stage: G4_Passive_Baseline_Map"; ...
        sprintf("Identifier: %s", string(mainException.identifier)); ...
        sprintf("Message: %s", string(mainException.message)); ...
        "Stack:"; ...
        stackLines ...
        ]);
catch
end

end