function results = runG2Stage1AcquisitionEvidence(datasetId, repoRoot, ...
    options)
%RUNG2STAGE1ACQUISITIONEVIDENCE Execute the Stage 1 G2 manual-review slice.
%
%   RESULTS = RUNG2STAGE1ACQUISITIONEVIDENCE() runs only the Acquisition
%   Evidence stage of G2 on the reference dataset and writes a manual-review
%   evidence bundle under:
%   artifacts/<datasetId>/G2_RF_Health_Stage1_AcquisitionEvidence/<runTimestampZ>/
%
%   This is not the final G2 gate runner. It exists so Stage 1 can be
%   reviewed independently before the later G2 stages are implemented.

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

totalTimer = tic;
stepTimer = tic;
stageArtifactId = "G2_RF_Health_Stage1_AcquisitionEvidence";
repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
[analysisOptions, runnerOptions] = localResolveRunnerOptions(options);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
bundleRoot = fullfile(repoRoot, "artifacts", datasetId, stageArtifactId, ...
    runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");
timingRows = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", 0.0, runnerOptions.ExecutionMode);
timingRows(1) = [];
timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", toc(stepTimer), runnerOptions.ExecutionMode, ...
    NaN, NaN, NaN, NaN, NaN, "");
fprintf("Running G2 Stage 1 Acquisition Evidence for dataset %s\n", ...
    datasetId);
fprintf("Repository root:\t%s\n", repoRoot);
fprintf("Execution mode:\t%s\n", runnerOptions.ExecutionMode);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);

    stepTimer = tic;
    loadOptions = struct();
    loadOptions.IncludeSamples = false;
    sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    inputRepetitionCount = double(numel(sessionData.RadarScans));
    inputSampleCount = double(sum([sessionData.RadarScans.NumSamples]));
    captureLogPath = localResolveCaptureLogPath(sessionData);
    collectionMetadataPath = fullfile(sessionData.DatasetRoot, ...
        "collection_metadata.json");

    if strlength(captureLogPath) > 0 && isfile(captureLogPath)
        captureLogInfo = helperParseG2CaptureLog(captureLogPath);
    else
        captureLogInfo = localBuildMissingCaptureLogInfo(captureLogPath);
    end

    collectionMetadataInfo = helperReadCollectionMetadata( ...
        collectionMetadataPath, datasetId);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "load_session_metadata", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "loadIQData IncludeSamples=false plus capture-log and metadata parse.");

    stepTimer = tic;
    analysis = helperAnalyzeG2AcquisitionEvidence(sessionData, ...
        captureLogInfo, collectionMetadataInfo, analysisOptions);
    configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
        bundleRoot, runTimestampZ, captureLogInfo, ...
        collectionMetadataInfo, analysis, runnerOptions);
    comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
        runTimestampZ, bundleRoot, analysis, collectionMetadataInfo);
    summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
        captureLogInfo, collectionMetadataInfo, analysis);
    collectionValidityLines = localBuildCollectionValidityNoteLines( ...
        captureLogInfo, collectionMetadataInfo, analysis);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "run_acquisition_evidence_helper", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "Analysis helper plus bundle summary preparation.");

    summaryPath = fullfile(bundleRoot, "summary.md");
    collectionValidityNotePath = fullfile(bundleRoot, ...
        "collection_validity_note.md");
    metadataAuditPath = fullfile(bundleRoot, "metadata_presence_audit.csv");
    receiverStatePath = fullfile(bundleRoot, "receiver_state_table.csv");
    channelRoleEvidencePath = fullfile(bundleRoot, ...
        "channel_role_evidence.csv");
    configSnapshotPath = fullfile(bundleRoot, "config_snapshot.json");
    metricsJsonPath = fullfile(bundleRoot, "metrics.json");
    metricsMatPath = fullfile(bundleRoot, "metrics.mat");
    averagePsdFigurePath = fullfile(figureRoot, ...
        "figure_01_average_channel_psd.png");
    consistencyFigurePath = fullfile(figureRoot, ...
        "figure_02_channel_consistency.png");

    stepTimer = tic;
    try
        writetable(analysis.MetadataAuditTable, metadataAuditPath);
        writetable(analysis.ReceiverStateTable, receiverStatePath);
        writetable(analysis.ChannelRoleEvidenceTable, ...
            channelRoleEvidencePath);
    catch writeTableException
        error("runG2Stage1AcquisitionEvidence:WriteTableFailed", ...
            "Failed to write a Stage 1 table artifact: %s", ...
            writeTableException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_tables", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 3, 0, NaN, ...
        "metadata, receiver state, and channel role evidence CSVs.");

    stepTimer = tic;
    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(collectionValidityNotePath, ...
        collectionValidityLines);
    localWriteJsonFile(configSnapshotPath, configSnapshot);
    localWriteJsonFile(metricsJsonPath, analysis.Metrics);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_text_artifacts", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 4, 0, NaN, ...
        "Summary, collection note, config JSON, and metrics JSON.");

    stepTimer = tic;
    try
        save(metricsMatPath, "analysis");
    catch saveException
        error("runG2Stage1AcquisitionEvidence:SaveMetricsFailed", ...
            "Failed to write Stage 1 metrics.mat: %s", ...
            saveException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_metrics_mat", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 1, 0, NaN, ...
        "metrics.mat");

    stepTimer = tic;
    try
        comparisonSnapshotPath = helperWriteComparisonSnapshot( ...
            string(bundleRoot), comparisonSnapshot);
    catch saveException
        error("runG2Stage1AcquisitionEvidence:SaveComparisonSnapshotFailed", ...
            "Failed to write Stage 1 comparison snapshot: %s", ...
            saveException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_comparison_snapshot", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 1, 0, NaN, "comparison_snapshot.mat");

    stepTimer = tic;
    localRenderAveragePsdFigure(analysis, averagePsdFigurePath, ...
        runnerOptions.ShowFigures);
    localRenderConsistencyFigure(analysis, consistencyFigurePath, ...
        runnerOptions.ShowFigures);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "render_figures", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 2, 2, NaN, ...
        "Average PSD and channel consistency figures.");

    [timingSummaryTable, performanceSummary] = ...
        helperFinalizePerformanceInstrumentation(stageArtifactId, ...
        datasetId, string(bundleRoot), runTimestampZ, ...
        runnerOptions.ExecutionMode, runnerOptions.ShowFigures, ...
        timingRows, totalTimer, inputSampleCount, ...
        inputRepetitionCount, string(metricsMatPath));

    results = struct();
    results.DatasetId = datasetId;
    results.StageId = "Stage1_AcquisitionEvidence";
    results.RunTimestampZ = runTimestampZ;
    results.BundleRoot = string(bundleRoot);
    results.CollectionValidityVerdict = ...
        analysis.CollectionValidityVerdict;
    results.AircraftReadinessImpact = ...
        analysis.AircraftReadinessImpact;
    results.ClassificationImpact = analysis.ClassificationImpact;
    results.CaptureLogPath = captureLogInfo.LogPath;
    results.CollectionMetadataPath = collectionMetadataInfo.MetadataPath;
    results.MissingRequiredItems = analysis.MissingRequiredItems;
    results.MetadataAuditTable = analysis.MetadataAuditTable;
    results.ReceiverStateTable = analysis.ReceiverStateTable;
    results.ChannelRoleEvidenceTable = analysis.ChannelRoleEvidenceTable;
    results.DecisionTrace = analysis.DecisionTrace;
    results.Metrics = analysis.Metrics;
    results.FigurePaths = [string(averagePsdFigurePath); ...
        string(consistencyFigurePath)];
    results.ComparisonSnapshotPath = string(comparisonSnapshotPath);
    results.TimingSummaryTable = timingSummaryTable;
    results.PerformanceSummary = performanceSummary;

    fprintf("Collection-validity verdict:\t%s\n", ...
        results.CollectionValidityVerdict);
    fprintf("Aircraft-readiness impact:\t%s\n", ...
        results.AircraftReadinessImpact);
    fprintf("Bundle root:\t%s\n", bundleRoot);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end

function [analysisOptions, runnerOptions] = localResolveRunnerOptions(options)

analysisOptions = options;
runnerOptions = struct();
runnerOptions.ExecutionMode = helperResolveExecutionMode(options);
runnerOptions.ShowFigures = usejava("desktop");

if runnerOptions.ExecutionMode == "analysis_only"
    runnerOptions.ShowFigures = false;
end

if isfield(options, "ShowFigures")
    runnerOptions.ShowFigures = logical(options.ShowFigures);
    analysisOptions = rmfield(analysisOptions, "ShowFigures");
end

if isfield(analysisOptions, "ExecutionMode")
    analysisOptions = rmfield(analysisOptions, "ExecutionMode");
end

end

function captureLogPath = localResolveCaptureLogPath(sessionData)

captureLogPath = "";
logRelativePaths = string(sessionData.Manifest.log_files(:));
captureLogMask = contains(logRelativePaths, "flighttest_capture");

if ~any(captureLogMask)
    return
end

relativePath = logRelativePaths(find(captureLogMask, 1, "first"));
captureLogPath = fullfile(sessionData.DatasetRoot, ...
    strrep(relativePath, "/", filesep));

end

function captureLogInfo = localBuildMissingCaptureLogInfo(logPath)

captureLogInfo = struct();
captureLogInfo.LogPath = string(logPath);
captureLogInfo.LogPresent = false;
captureLogInfo.SessionId = "";
captureLogInfo.CaptureSessionId = "";
captureLogInfo.SessionIdsAgree = false;
captureLogInfo.Dtg = "";
captureLogInfo.SelectedAntennas = "";
captureLogInfo.PlannedDuration_s = NaN;
captureLogInfo.PlannedSampleRate_Msps = NaN;
captureLogInfo.PlannedChannelCount = NaN;
captureLogInfo.RadioProduct = "";
captureLogInfo.RadioSerial = "";
captureLogInfo.RadioName = "";
captureLogInfo.RadioType = "";
captureLogInfo.RadioMgmtAddress = "";
captureLogInfo.RadioAddress = "";
captureLogInfo.ClockSource = "";
captureLogInfo.TimeSource = "";
captureLogInfo.MasterClockRate_Hz = NaN;
captureLogInfo.CaptureRecordingUTC = NaN;
captureLogInfo.UhdInfoLine = "";
captureLogInfo.WarningLines = strings(0, 1);
captureLogInfo.WarningCount = 0;
captureLogInfo.RoundNumbers = zeros(0, 1);
captureLogInfo.RoundTotal = NaN;
captureLogInfo.RoundCount = 0;
captureLogInfo.CollectionStartedCount = 0;
captureLogInfo.CaptureFileCount = 0;
captureLogInfo.CaptureFilePaths = strings(0, 1);
captureLogInfo.ContainsOverrunText = false;
captureLogInfo.ContainsLockStatusText = false;
captureLogInfo.ContainsAgcText = false;
captureLogInfo.ContainsMappingVerificationText = false;

end

function configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
    bundleRoot, runTimestampZ, captureLogInfo, collectionMetadataInfo, ...
    analysis, runnerOptions)

configSnapshot = struct();
configSnapshot.dataset_id = datasetId;
configSnapshot.stage_id = "Stage1_AcquisitionEvidence";
configSnapshot.entry_point = "runG2Stage1AcquisitionEvidence";
configSnapshot.repo_root = repoRoot;
configSnapshot.bundle_root = string(bundleRoot);
configSnapshot.run_timestamp_z = runTimestampZ;
configSnapshot.capture_log_path = captureLogInfo.LogPath;
configSnapshot.collection_metadata_path = ...
    collectionMetadataInfo.MetadataPath;
configSnapshot.collection_metadata_present = ...
    collectionMetadataInfo.MetadataPresent;
configSnapshot.show_figures = runnerOptions.ShowFigures;
configSnapshot.execution_mode = runnerOptions.ExecutionMode;
configSnapshot.sample_rate_hz = analysis.Options.SampleRateHz;
configSnapshot.welch_length = analysis.Options.WelchLength;
configSnapshot.welch_overlap = analysis.Options.WelchOverlap;
configSnapshot.welch_nfft = analysis.Options.WelchNfft;
configSnapshot.correlation_sample_count = ...
    analysis.Options.CorrelationSampleCount;
configSnapshot.correlation_max_lag_samples = ...
    analysis.Options.CorrelationMaxLagSamples;
configSnapshot.reference_candidate_power_delta_threshold_db = ...
    analysis.Options.ReferenceCandidatePowerDeltaThreshold_dB;
configSnapshot.matlab_version = string(version);
configSnapshot.matlab_release = string(version("-release"));
configSnapshot.computer = string(computer);

end

function comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
    runTimestampZ, bundleRoot, analysis, collectionMetadataInfo)

referenceLabel = strtrim(string( ...
    collectionMetadataInfo.ReferenceChannel.ChannelLabel));
surveillanceLabel = strtrim(string( ...
    collectionMetadataInfo.SurveillanceChannel.ChannelLabel));
roleSourceSummary = localBuildRoleSourceSummary(collectionMetadataInfo, ...
    analysis);
summaryTable = localBuildComparisonSummaryTable(analysis, ...
    collectionMetadataInfo, roleSourceSummary, referenceLabel, ...
    surveillanceLabel);

comparisonSnapshot = struct();
comparisonSnapshot.DatasetId = string(datasetId);
comparisonSnapshot.StageId = string(analysis.StageId);
comparisonSnapshot.RunTimestampZ = string(runTimestampZ);
comparisonSnapshot.BundleRoot = string(bundleRoot);
comparisonSnapshot.CollectionValidityVerdict = string( ...
    analysis.CollectionValidityVerdict);
comparisonSnapshot.AircraftReadinessImpact = string( ...
    analysis.AircraftReadinessImpact);
comparisonSnapshot.ClassificationImpact = string( ...
    analysis.ClassificationImpact);
comparisonSnapshot.RoleSourceSummary = roleSourceSummary;
comparisonSnapshot.ReferenceLabel = referenceLabel;
comparisonSnapshot.SurveillanceLabel = surveillanceLabel;
comparisonSnapshot.IqOnlyMappingInference = string( ...
    analysis.RoleEvidence.IqOnlyMappingInference);
comparisonSnapshot.MissingRequiredItemCount = double( ...
    analysis.Metrics.metadata_presence.missing_required_item_count);
comparisonSnapshot.ReferenceCandidatePassFraction = double( ...
    analysis.RoleEvidence.ReferenceCandidatePassFraction);
comparisonSnapshot.PeakCorrelationMagnitudeMedian = double( ...
    analysis.RoleEvidence.PeakCorrelationMagnitude_Median);
comparisonSnapshot.MeanCoherenceMedian = double( ...
    analysis.RoleEvidence.MeanCoherence_Median);
comparisonSnapshot.DecisionTrace = string(analysis.DecisionTrace(:));
comparisonSnapshot.MissingRequiredItems = string( ...
    analysis.MissingRequiredItems(:));
comparisonSnapshot.SummaryTable = summaryTable;

end

function summaryTable = localBuildComparisonSummaryTable(analysis, ...
    collectionMetadataInfo, roleSourceSummary, referenceLabel, ...
    surveillanceLabel)

rows = [ ...
    helperMakeComparisonMetricRow("collection_validity_verdict", ...
    "Collection Validity Verdict", analysis.CollectionValidityVerdict, ...
    "", "Stage 1 collection-validity verdict."); ...
    helperMakeComparisonMetricRow("aircraft_readiness_impact", ...
    "Aircraft-Readiness Impact", analysis.AircraftReadinessImpact, "", ...
    "Stage 1 aircraft-readiness impact."); ...
    helperMakeComparisonMetricRow("classification_impact", ...
    "Classification Impact", analysis.ClassificationImpact, "", ...
    "Narrative classification impact emitted by Stage 1."); ...
    helperMakeComparisonMetricRow("role_source_summary", ...
    "Role-Source Summary", roleSourceSummary, "", ...
    "Combined manual-metadata and IQ-only role evidence summary."); ...
    helperMakeComparisonMetricRow("reference_label", ...
    "Manual Reference Label", referenceLabel, "", ...
    "Reference label declared in collection_metadata.json."); ...
    helperMakeComparisonMetricRow("surveillance_label", ...
    "Manual Surveillance Label", surveillanceLabel, "", ...
    "Surveillance label declared in collection_metadata.json."); ...
    helperMakeComparisonMetricRow("collection_metadata_present", ...
    "Collection Metadata Present", ...
    collectionMetadataInfo.MetadataPresent, "", ...
    "True when dataset-local manual metadata exists."); ...
    helperMakeComparisonMetricRow("iq_only_mapping_inference", ...
    "IQ-Only Mapping Inference", ...
    analysis.RoleEvidence.IqOnlyMappingInference, "", ...
    "Role inference derived from power, coherence, and correlation only."); ...
    helperMakeComparisonMetricRow("missing_required_item_count", ...
    "Missing Required Item Count", ...
    analysis.Metrics.metadata_presence.missing_required_item_count, ...
    "count", ...
    "Required acquisition-evidence items still missing after Stage 1."); ...
    helperMakeComparisonMetricRow("present_required_item_count", ...
    "Present Required Item Count", ...
    analysis.Metrics.metadata_presence.present_required_item_count, ...
    "count", ...
    "Required acquisition-evidence items present in this session."); ...
    helperMakeComparisonMetricRow("reference_candidate_pass_fraction", ...
    "Reference-Candidate Pass Fraction", ...
    analysis.RoleEvidence.ReferenceCandidatePassFraction, "fraction", ...
    "Fraction of repetitions that support the inferred reference candidate."); ...
    helperMakeComparisonMetricRow("mean_coherence_median", ...
    "Mean Coherence Median", ...
    analysis.RoleEvidence.MeanCoherence_Median, "", ...
    "Median mean coherence across repetitions."); ...
    helperMakeComparisonMetricRow("peak_correlation_magnitude_median", ...
    "Peak Correlation Magnitude Median", ...
    analysis.RoleEvidence.PeakCorrelationMagnitude_Median, "", ...
    "Median peak correlation magnitude across repetitions."); ...
    helperMakeComparisonMetricRow("peak_correlation_lag_samples_median", ...
    "Peak Correlation Lag Median", ...
    analysis.RoleEvidence.PeakCorrelationLagSamples_Median, ...
    "samples", ...
    "Median peak-correlation lag across repetitions.") ...
    ];

summaryTable = struct2table(rows);
summaryTable.DisplayOrder = (1:height(summaryTable)).';

end

function roleSourceSummary = localBuildRoleSourceSummary( ...
    collectionMetadataInfo, analysis)

referenceLabel = strtrim(string( ...
    collectionMetadataInfo.ReferenceChannel.ChannelLabel));
surveillanceLabel = strtrim(string( ...
    collectionMetadataInfo.SurveillanceChannel.ChannelLabel));
manualRoleSummary = "collection_metadata does not declare both roles";

if strlength(referenceLabel) > 0 && strlength(surveillanceLabel) > 0
    manualRoleSummary = sprintf( ...
        "collection_metadata declares reference %s and surveillance %s", ...
        char(referenceLabel), char(surveillanceLabel));
elseif strlength(referenceLabel) > 0 || strlength(surveillanceLabel) > 0
    manualRoleSummary = sprintf( ...
        "collection_metadata partially declares roles: reference %s | surveillance %s", ...
        char(referenceLabel), char(surveillanceLabel));
end

verificationSummary = "no explicit mapping-verification evidence noted";

if isfield(analysis.Metrics, "audit_flags") && ...
        isfield(analysis.Metrics.audit_flags, ...
        "MappingVerificationCapturePresent") && ...
        analysis.Metrics.audit_flags.MappingVerificationCapturePresent
    verificationSummary = "explicit mapping-verification evidence present";
end

roleSourceSummary = manualRoleSummary + ...
    " | IQ-only inference " + ...
    string(analysis.RoleEvidence.IqOnlyMappingInference) + ...
    " | " + verificationSummary;

end

function summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
    captureLogInfo, collectionMetadataInfo, analysis)

metadataAuditTable = analysis.MetadataAuditTable;
requiredMask = metadataAuditTable.Required;
presentRequiredMask = requiredMask & metadataAuditTable.Present;

summaryLines = [ ...
    "# G2 Stage 1 Acquisition Evidence Summary"; ...
    ""; ...
    sprintf("- Dataset: `%s`", analysis.DatasetId); ...
    "- Scope: `G2_RF_Health` Stage 1 only"; ...
    "- Entry point: `runG2Stage1AcquisitionEvidence`"; ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    sprintf("- Collection-validity verdict: `%s`", ...
    analysis.CollectionValidityVerdict); ...
    sprintf("- Aircraft-readiness impact: `%s`", ...
    analysis.AircraftReadinessImpact); ...
    sprintf("- Classification impact: %s", ...
    analysis.ClassificationImpact); ...
    sprintf("- Capture log path: `%s`", captureLogInfo.LogPath); ...
    sprintf("- Collection metadata path: `%s`", ...
    collectionMetadataInfo.MetadataPath); ...
    ""; ...
    "## Key Findings"; ...
    sprintf("- Required evidence items present: `%d/%d`", ...
    nnz(presentRequiredMask), nnz(requiredMask)); ...
    sprintf("- Capture-log warnings observed: `%d`", ...
    captureLogInfo.WarningCount); ...
    sprintf("- Manual antenna mapping: `%s`", ...
    localBuildAntennaSummaryLine(collectionMetadataInfo)); ...
    sprintf("- Manual site note: `%s`", ...
    localBuildSiteSummaryLine(collectionMetadataInfo)); ...
    sprintf("- Channel 1 stronger than channel 2 in `%0.1f%%` of repetitions using a `%0.1f dB` threshold.", ...
    100 * analysis.RoleEvidence.ReferenceCandidatePassFraction, ...
    analysis.Options.ReferenceCandidatePowerDeltaThreshold_dB); ...
    sprintf("- Channel power delta range: `%.3f dB` to `%.3f dB`", ...
    analysis.RoleEvidence.ChannelPowerDelta_dB_Min, ...
    analysis.RoleEvidence.ChannelPowerDelta_dB_Max); ...
    sprintf("- Median mean coherence: `%.3f`", ...
    analysis.RoleEvidence.MeanCoherence_Median); ...
    sprintf("- Median peak correlation magnitude: `%.3f`", ...
    analysis.RoleEvidence.PeakCorrelationMagnitude_Median); ...
    sprintf("- IQ-only mapping inference: `%s`", ...
    analysis.RoleEvidence.IqOnlyMappingInference); ...
    ""; ...
    "## Missing Required Evidence"; ...
    localBuildMissingEvidenceLines(analysis.MissingRequiredItems); ...
    ""; ...
    "## Output Files"; ...
    "- `metadata_presence_audit.csv`"; ...
    "- `receiver_state_table.csv`"; ...
    "- `channel_role_evidence.csv`"; ...
    "- `collection_validity_note.md`"; ...
    "- `config_snapshot.json`"; ...
    "- `metrics.json`"; ...
    "- `metrics.mat`"; ...
    "- `figures/figure_01_average_channel_psd.png`"; ...
    "- `figures/figure_02_channel_consistency.png`" ...
    ];

end

function lines = localBuildMissingEvidenceLines(missingRequiredItems)

if isempty(missingRequiredItems)
    lines = "- None.";
    return
end

lines = "- `" + missingRequiredItems + "`";

end

function lines = localBuildCollectionValidityNoteLines(captureLogInfo, ...
    collectionMetadataInfo, analysis)

lines = [ ...
    "# Collection Validity Note"; ...
    ""; ...
    sprintf("- Current Stage 1 verdict: `%s`", ...
    analysis.CollectionValidityVerdict); ...
    sprintf("- Aircraft-readiness impact: `%s`", ...
    analysis.AircraftReadinessImpact); ...
    sprintf("- Classification impact: %s", ...
    analysis.ClassificationImpact); ...
    ""; ...
    "## Positive Evidence"; ...
    "- Manifest, capture-log, and embedded-header evidence agree on dataset identity, sample rate, center frequency, and RF chain labels."; ...
    sprintf("- Capture log records product `%s`, serial `%s`, clock source `%s`, and time source `%s`.", ...
    captureLogInfo.RadioProduct, captureLogInfo.RadioSerial, ...
    captureLogInfo.ClockSource, captureLogInfo.TimeSource); ...
    sprintf("- Manual metadata identifies `%s` as the reference antenna and `%s` as the surveillance antenna.", ...
    localFormatManualChannelLabel(collectionMetadataInfo.ReferenceChannel), ...
    localFormatManualChannelLabel(collectionMetadataInfo.SurveillanceChannel)); ...
    sprintf("- Manual site metadata records the surveillance boresight as `%s` and notes `%s`.", ...
    collectionMetadataInfo.SiteContext.SurveillanceBoresightDescription, ...
    collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote); ...
    sprintf("- IQ-only role evidence currently supports channel 1 as the stronger reference-view candidate in `%0.1f%%` of repetitions.", ...
    100 * analysis.RoleEvidence.ReferenceCandidatePassFraction); ...
    ""; ...
    "## Missing or Partial Evidence"; ...
    "- Explicit overrun or dropped-sample counters are not recorded in the current capture log."; ...
    "- Explicit reference-lock or timing-lock evidence is not recorded in the current capture log."; ...
    "- Physical antenna identities are now recorded manually, but explicit per-channel gain mapping is still not established."; ...
    "- No dedicated channel-mapping verification capture or injected-tone proof was found."; ...
    ""; ...
    "## Stage 1 Interpretation"; ...
    "- The current evidence is strong enough to say the receiver state is partially evidenced and that the RF chain labels are internally consistent."; ...
    "- The current evidence is not strong enough to claim that the hardware configuration was fully validated for later aircraft-related analysis."; ...
    "- Later G2 stages may improve RF-health confidence, but they should not erase the Stage 1 caveats without new acquisition evidence." ...
    ];

end

function summaryLine = localBuildAntennaSummaryLine(collectionMetadataInfo)

summaryLine = strjoin([ ...
    localFormatManualChannelLabel(collectionMetadataInfo.ReferenceChannel); ...
    localFormatManualChannelLabel(collectionMetadataInfo.SurveillanceChannel) ...
    ], " | ");

end

function summaryLine = localBuildSiteSummaryLine(collectionMetadataInfo)

summaryLine = strjoin([ ...
    collectionMetadataInfo.SiteContext.SiteRegion; ...
    collectionMetadataInfo.SiteContext.SurveillanceBoresightDescription; ...
    collectionMetadataInfo.SiteContext.ExpectedAirTrafficNote ...
    ], " | ");
summaryLine = localRemoveEmptyJoinArtifacts(summaryLine);

end

function labelText = localFormatManualChannelLabel(channelInfo)

labelText = strjoin([ ...
    channelInfo.ChannelLabel; ...
    channelInfo.Role; ...
    channelInfo.AntennaName ...
    ], " | ");
labelText = localRemoveEmptyJoinArtifacts(labelText);

end

function outputText = localRemoveEmptyJoinArtifacts(inputText)

tokens = split(string(inputText), "|");
tokens = strtrim(tokens);
tokens = tokens(strlength(tokens) > 0);

if isempty(tokens)
    outputText = "";
else
    outputText = strjoin(tokens, " | ");
end

end

function localRenderAveragePsdFigure(analysis, figurePath, showFigures)

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G2 Stage 1 Average Channel PSD", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
tiledlayout(1, 1);
nexttile;
plot(analysis.RoleEvidence.PsdFrequencyHz / 1e6, ...
    pow2db(analysis.RoleEvidence.MeanChannel1Psd + eps), ...
    "LineWidth", 1.4);
hold on
plot(analysis.RoleEvidence.PsdFrequencyHz / 1e6, ...
    pow2db(analysis.RoleEvidence.MeanChannel2Psd + eps), ...
    "LineWidth", 1.4);
hold off
grid on
xlabel("Frequency [MHz]");
ylabel("PSD [dB/Hz]");
title("G2 Stage 1 Average Channel PSD");
legend("Channel 1", "Channel 2", Location = "best");
drawnow

try
    exportgraphics(figureHandle, figurePath);
catch exportException
    error("runG2Stage1AcquisitionEvidence:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, exportException.message);
end

clear cleanupObject

end

function localRenderConsistencyFigure(analysis, figurePath, showFigures)

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G2 Stage 1 Channel Consistency", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
tiledlayout(2, 1);

nexttile;
plot(analysis.RoleEvidence.CoherenceFrequencyHz / 1e6, ...
    analysis.RoleEvidence.MeanCoherenceSpectrum, "LineWidth", 1.4);
grid on
xlabel("Frequency [MHz]");
ylabel("Coherence");
title("G2 Stage 1 Mean Cross-Channel Coherence");

nexttile;
plot(analysis.RoleEvidence.CorrelationLagsSamples, ...
    analysis.RoleEvidence.MedianCorrelationMagnitude, ...
    "LineWidth", 1.4);
grid on
xlabel("Lag [samples]");
ylabel("Correlation Magnitude");
title("G2 Stage 1 Median Normalized Cross-Correlation");
drawnow

try
    exportgraphics(figureHandle, figurePath);
catch exportException
    error("runG2Stage1AcquisitionEvidence:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, exportException.message);
end

clear cleanupObject

end

function visibility = localResolveFigureVisibility(showFigures)

if showFigures
    visibility = "on";
else
    visibility = "off";
end

end

function cleanupObject = localCreateFigureCleanup(figureHandle, showFigures)

if showFigures
    cleanupObject = [];
    return
end

cleanupObject = onCleanup(@() close(figureHandle));

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG2Stage1AcquisitionEvidence:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

try
    fileIdentifier = fopen(filePath, "w");
catch openException
    error("runG2Stage1AcquisitionEvidence:OpenTextFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        openException.message);
end

if fileIdentifier == -1
    error("runG2Stage1AcquisitionEvidence:OpenTextFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileIdentifier));
lines = string(lines);

for idx = 1:numel(lines)
    fprintf(fileIdentifier, "%s\n", lines(idx));
end

clear cleanupObject

end

function localWriteJsonFile(filePath, inputStruct)

try
    jsonText = jsonencode(inputStruct, PrettyPrint = true);
catch encodeException
    error("runG2Stage1AcquisitionEvidence:JsonEncodeFailed", ...
        "Failed to encode JSON for %s: %s", filePath, ...
        encodeException.message);
end

localWriteTextFile(filePath, jsonText);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return
end

if ~isfolder(bundleRoot)
    try
        mkdir(bundleRoot);
    catch
        return
    end
end

try
    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G2 Stage 1 Acquisition Evidence Summary"; ...
        ""; ...
        "- Stage status: `failed`"; ...
        sprintf("- Failure message: `%s`", mainException.message) ...
        ]);
catch
end

end
