function results = runG2Stage2ReceiverIntegrity(datasetId, repoRoot, ...
    options)
%RUNG2STAGE2RECEIVERINTEGRITY Execute the Stage 2 G2 manual-review slice.
%
%   RESULTS = RUNG2STAGE2RECEIVERINTEGRITY() runs only the Receiver
%   Integrity stage of G2 on the reference dataset and writes a
%   manual-review evidence bundle under:
%   artifacts/<datasetId>/G2_RF_Health_Stage2_ReceiverIntegrity/<runTimestampZ>/
%
%   This is not the final G2 gate runner. It exists so Stage 2 can be
%   reviewed independently before the later G2 stages are implemented.

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

stageArtifactId = "G2_RF_Health_Stage2_ReceiverIntegrity";
repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
[analysisOptions, runnerOptions] = localResolveRunnerOptions(options);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
bundleRoot = fullfile(repoRoot, "artifacts", datasetId, stageArtifactId, ...
    runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");

fprintf("Running G2 Stage 2 Receiver Integrity for dataset %s\n", ...
    datasetId);
fprintf("Repository root:\t%s\n", repoRoot);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);

    loadOptions = struct();
    loadOptions.IncludeSamples = false;
    sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    collectionMetadataPath = fullfile(sessionData.DatasetRoot, ...
        "collection_metadata.json");
    collectionMetadataInfo = helperReadCollectionMetadata( ...
        collectionMetadataPath, datasetId);
    analysis = helperAnalyzeG2ReceiverIntegrity(sessionData, ...
        collectionMetadataInfo, analysisOptions);
    configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
        bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
        runnerOptions);
    comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
        runTimestampZ, bundleRoot, analysis);
    summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
        collectionMetadataInfo, analysis);
    receiverIntegrityNoteLines = localBuildReceiverIntegrityNoteLines( ...
        collectionMetadataInfo, analysis);

    summaryPath = fullfile(bundleRoot, "summary.md");
    receiverIntegrityNotePath = fullfile(bundleRoot, ...
        "receiver_integrity_note.md");
    receiverIntegrityTablePath = fullfile(bundleRoot, ...
        "receiver_integrity_table.csv");
    channelSummaryPath = fullfile(bundleRoot, "channel_summary_table.csv");
    decisionTracePath = fullfile(bundleRoot, ...
        "decision_traceability_table.csv");
    configSnapshotPath = fullfile(bundleRoot, "config_snapshot.json");
    metricsJsonPath = fullfile(bundleRoot, "metrics.json");
    metricsMatPath = fullfile(bundleRoot, "metrics.mat");
    averagePsdFigurePath = fullfile(figureRoot, ...
        "figure_01_average_role_psd.png");
    receiverMetricsFigurePath = fullfile(figureRoot, ...
        "figure_02_receiver_metrics_overview.png");
    contaminationFigurePath = fullfile(figureRoot, ...
        "figure_03_dc_iq_and_clipping_overview.png");

    try
        writetable(analysis.ReceiverIntegrityTable, ...
            receiverIntegrityTablePath);
        writetable(analysis.ChannelSummaryTable, channelSummaryPath);
        writetable(analysis.DecisionTraceTable, decisionTracePath);
    catch writeTableException
        error("runG2Stage2ReceiverIntegrity:WriteTableFailed", ...
            "Failed to write a Stage 2 table artifact: %s", ...
            writeTableException.message);
    end

    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(receiverIntegrityNotePath, ...
        receiverIntegrityNoteLines);
    localWriteJsonFile(configSnapshotPath, configSnapshot);
    localWriteJsonFile(metricsJsonPath, analysis.Metrics);

    try
        save(metricsMatPath, "analysis");
    catch saveException
        error("runG2Stage2ReceiverIntegrity:SaveMetricsFailed", ...
            "Failed to write Stage 2 metrics.mat: %s", ...
            saveException.message);
    end

    try
        comparisonSnapshotPath = helperWriteComparisonSnapshot( ...
            string(bundleRoot), comparisonSnapshot);
    catch saveException
        error("runG2Stage2ReceiverIntegrity:SaveComparisonSnapshotFailed", ...
            "Failed to write Stage 2 comparison snapshot: %s", ...
            saveException.message);
    end

    localRenderAveragePsdFigure(analysis, averagePsdFigurePath, ...
        runnerOptions.ShowFigures);
    localRenderReceiverMetricsFigure(analysis, ...
        receiverMetricsFigurePath, runnerOptions.ShowFigures);
    localRenderContaminationFigure(analysis, contaminationFigurePath, ...
        runnerOptions.ShowFigures);

    results = struct();
    results.DatasetId = datasetId;
    results.StageId = "Stage2_ReceiverIntegrity";
    results.RunTimestampZ = runTimestampZ;
    results.BundleRoot = string(bundleRoot);
    results.ReceiverIntegrityVerdict = ...
        analysis.ReceiverIntegrityVerdict;
    results.LegalGateRecommendation = ...
        analysis.LegalGateRecommendation;
    results.DatasetClassificationRecommendation = ...
        analysis.DatasetClassificationRecommendation;
    results.AnalysisValidity = analysis.AnalysisValidity;
    results.DevelopmentReadiness = analysis.DevelopmentReadiness;
    results.DevelopmentBlockingReason = ...
        analysis.DevelopmentBlockingReason;
    results.AnalysisInterpretation = analysis.AnalysisInterpretation;
    results.DevelopmentInterpretation = ...
        analysis.DevelopmentInterpretation;
    results.RoleSource = analysis.RoleInfo.RoleSource;
    results.RoleNote = analysis.RoleInfo.RoleNote;
    results.ReferenceLabel = analysis.RoleInfo.ReferenceLabel;
    results.SurveillanceLabel = analysis.RoleInfo.SurveillanceLabel;
    results.CollectionMetadataPath = collectionMetadataInfo.MetadataPath;
    results.ReceiverIntegrityTable = analysis.ReceiverIntegrityTable;
    results.ChannelSummaryTable = analysis.ChannelSummaryTable;
    results.DecisionTraceTable = analysis.DecisionTraceTable;
    results.Metrics = analysis.Metrics;
    results.Options = analysis.Options;
    results.FigurePaths = [string(averagePsdFigurePath); ...
        string(receiverMetricsFigurePath); ...
        string(contaminationFigurePath)];
    results.ComparisonSnapshotPath = string(comparisonSnapshotPath);

    fprintf("Receiver-integrity verdict:\t%s\n", ...
        results.ReceiverIntegrityVerdict);
    fprintf("Legal recommendation:\t%s\n", ...
        results.LegalGateRecommendation);
    fprintf("Classification recommendation:\t%s\n", ...
        results.DatasetClassificationRecommendation);
    fprintf("Analysis validity:\t%s\n", ...
        results.AnalysisValidity);
    fprintf("Development readiness:\t%s\n", ...
        results.DevelopmentReadiness);
    fprintf("Development reason:\t%s\n", ...
        results.DevelopmentBlockingReason);
    fprintf("Bundle root:\t%s\n", bundleRoot);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end

function [analysisOptions, runnerOptions] = localResolveRunnerOptions(options)

analysisOptions = options;
runnerOptions = struct();
runnerOptions.ShowFigures = usejava("desktop");

if ~isfield(options, "ShowFigures")
    return
end

runnerOptions.ShowFigures = logical(options.ShowFigures);
analysisOptions = rmfield(analysisOptions, "ShowFigures");

end

function configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
    bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
    runnerOptions)

configSnapshot = struct();
configSnapshot.dataset_id = datasetId;
configSnapshot.stage_id = "Stage2_ReceiverIntegrity";
configSnapshot.entry_point = "runG2Stage2ReceiverIntegrity";
configSnapshot.repo_root = repoRoot;
configSnapshot.bundle_root = string(bundleRoot);
configSnapshot.run_timestamp_z = runTimestampZ;
configSnapshot.collection_metadata_path = ...
    collectionMetadataInfo.MetadataPath;
configSnapshot.collection_metadata_present = ...
    collectionMetadataInfo.MetadataPresent;
configSnapshot.collection_metadata_session_id_matches = ...
    collectionMetadataInfo.SessionIdMatches;
configSnapshot.show_figures = runnerOptions.ShowFigures;
configSnapshot.role_source = analysis.RoleInfo.RoleSource;
configSnapshot.role_note = analysis.RoleInfo.RoleNote;
configSnapshot.reference_label = analysis.RoleInfo.ReferenceLabel;
configSnapshot.surveillance_label = analysis.RoleInfo.SurveillanceLabel;
configSnapshot.reference_column_index = ...
    analysis.RoleInfo.ReferenceColumnIndex;
configSnapshot.surveillance_column_index = ...
    analysis.RoleInfo.SurveillanceColumnIndex;
configSnapshot.analysis_validity = analysis.AnalysisValidity;
configSnapshot.development_readiness = analysis.DevelopmentReadiness;
configSnapshot.development_blocking_reason = ...
    analysis.DevelopmentBlockingReason;
configSnapshot.analysis_interpretation = ...
    analysis.AnalysisInterpretation;
configSnapshot.development_interpretation = ...
    analysis.DevelopmentInterpretation;
configSnapshot.sample_rate_hz = analysis.Options.SampleRateHz;
configSnapshot.welch_length = analysis.Options.WelchLength;
configSnapshot.welch_overlap = analysis.Options.WelchOverlap;
configSnapshot.welch_nfft = analysis.Options.WelchNfft;
configSnapshot.near_rail_threshold_fraction = ...
    analysis.Options.NearRailThresholdFraction;
configSnapshot.severe_clipping_fraction_threshold = ...
    analysis.Options.SevereClippingFractionThreshold;
configSnapshot.reference_power_minimum_threshold_db = ...
    analysis.Options.ReferencePowerMinimumThreshold_dB;
configSnapshot.reference_power_target_margin_threshold_db = ...
    analysis.Options.ReferencePowerTargetMarginThreshold_dB;
configSnapshot.quantization_risk_threshold_dbfs = ...
    analysis.Options.QuantizationRiskThreshold_dBFS;
configSnapshot.severe_quantization_threshold_dbfs = ...
    analysis.Options.SevereQuantizationThreshold_dBFS;
configSnapshot.dc_mean_ratio_diagnostic_threshold_db = ...
    analysis.Options.DcMeanRatioDiagnosticThreshold_dB;
configSnapshot.dc_mean_ratio_severe_threshold_db = ...
    analysis.Options.DcMeanRatioSevereThreshold_dB;
configSnapshot.dc_spike_diagnostic_threshold_db = ...
    analysis.Options.DcSpikeDiagnosticThreshold_dB;
configSnapshot.dc_spike_severe_threshold_db = ...
    analysis.Options.DcSpikeSevereThreshold_dB;
configSnapshot.dc_band_half_width_hz = ...
    analysis.Options.DcBandHalfWidthHz;
configSnapshot.dc_spike_local_half_width_hz = ...
    analysis.Options.DcSpikeLocalHalfWidthHz;
configSnapshot.dc_spike_exclusion_half_width_hz = ...
    analysis.Options.DcSpikeExclusionHalfWidthHz;
configSnapshot.iq_amplitude_imbalance_diagnostic_threshold_db = ...
    analysis.Options.IqAmplitudeImbalanceDiagnosticThreshold_dB;
configSnapshot.iq_amplitude_imbalance_severe_threshold_db = ...
    analysis.Options.IqAmplitudeImbalanceSevereThreshold_dB;
configSnapshot.iq_phase_proxy_diagnostic_threshold_deg = ...
    analysis.Options.IqPhaseProxyDiagnosticThreshold_deg;
configSnapshot.iq_phase_proxy_severe_threshold_deg = ...
    analysis.Options.IqPhaseProxySevereThreshold_deg;
configSnapshot.iq_impropriety_diagnostic_threshold = ...
    analysis.Options.IqImproprietyDiagnosticThreshold;
configSnapshot.iq_impropriety_severe_threshold = ...
    analysis.Options.IqImproprietySevereThreshold;
configSnapshot.matlab_version = string(version);
configSnapshot.matlab_release = string(version("-release"));
configSnapshot.computer = string(computer);

end

function comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
    runTimestampZ, bundleRoot, analysis)

worstMetrics = localComputeWorstMetrics(analysis.ReceiverIntegrityTable);
summaryTable = localBuildComparisonSummaryTable(analysis, worstMetrics);

comparisonSnapshot = struct();
comparisonSnapshot.DatasetId = string(datasetId);
comparisonSnapshot.StageId = string(analysis.StageId);
comparisonSnapshot.RunTimestampZ = string(runTimestampZ);
comparisonSnapshot.BundleRoot = string(bundleRoot);
comparisonSnapshot.ReceiverIntegrityVerdict = string( ...
    analysis.ReceiverIntegrityVerdict);
comparisonSnapshot.LegalGateRecommendation = string( ...
    analysis.LegalGateRecommendation);
comparisonSnapshot.DatasetClassificationRecommendation = string( ...
    analysis.DatasetClassificationRecommendation);
comparisonSnapshot.AnalysisValidity = string( ...
    analysis.AnalysisValidity);
comparisonSnapshot.DevelopmentReadiness = string( ...
    analysis.DevelopmentReadiness);
comparisonSnapshot.DevelopmentBlockingReason = string( ...
    analysis.DevelopmentBlockingReason);
comparisonSnapshot.AnalysisInterpretation = string( ...
    analysis.AnalysisInterpretation);
comparisonSnapshot.DevelopmentInterpretation = string( ...
    analysis.DevelopmentInterpretation);
comparisonSnapshot.ClassificationImpact = string( ...
    analysis.ClassificationImpact);
comparisonSnapshot.RoleSource = string(analysis.RoleInfo.RoleSource);
comparisonSnapshot.ReferenceLabel = string( ...
    analysis.RoleInfo.ReferenceLabel);
comparisonSnapshot.SurveillanceLabel = string( ...
    analysis.RoleInfo.SurveillanceLabel);
comparisonSnapshot.ReferenceMinusSurveillancePowerMin_dB = double( ...
    analysis.Metrics.reference_minus_surveillance_power_db_min);
comparisonSnapshot.ReferenceMinusSurveillancePowerMedian_dB = double( ...
    analysis.Metrics.reference_minus_surveillance_power_db_median);
comparisonSnapshot.ReferenceMinusSurveillancePowerMax_dB = double( ...
    analysis.Metrics.reference_minus_surveillance_power_db_max);
comparisonSnapshot.MinimumPeakHeadroom_dB = ...
    worstMetrics.MinimumPeakHeadroom_dB;
comparisonSnapshot.WorstNearRailFraction = ...
    worstMetrics.WorstNearRailFraction;
comparisonSnapshot.WorstExactRailFraction = ...
    worstMetrics.WorstExactRailFraction;
comparisonSnapshot.WorstDcMeanRatio_dB = ...
    worstMetrics.WorstDcMeanRatio_dB;
comparisonSnapshot.WorstDcSpike_dB = worstMetrics.WorstDcSpike_dB;
comparisonSnapshot.WorstIqAmplitudeImbalance_dB = ...
    worstMetrics.WorstIqAmplitudeImbalance_dB;
comparisonSnapshot.WorstIqPhaseProxy_deg = ...
    worstMetrics.WorstIqPhaseProxy_deg;
comparisonSnapshot.WorstIqImpropriety = ...
    worstMetrics.WorstIqImpropriety;
comparisonSnapshot.DecisionTraceTable = analysis.DecisionTraceTable;
comparisonSnapshot.SummaryTable = summaryTable;

end

function summaryTable = localBuildComparisonSummaryTable(analysis, ...
    worstMetrics)

rows = [ ...
    helperMakeComparisonMetricRow("receiver_integrity_verdict", ...
    "Receiver Integrity Verdict", ...
    analysis.ReceiverIntegrityVerdict, "", ...
    "Stage 2 receiver-integrity verdict."); ...
    helperMakeComparisonMetricRow("legal_gate_recommendation", ...
    "Legal Gate Recommendation", ...
    analysis.LegalGateRecommendation, "", ...
    "Legal branch recommendation emitted by Stage 2."); ...
    helperMakeComparisonMetricRow( ...
    "dataset_classification_recommendation", ...
    "Dataset Classification Recommendation", ...
    analysis.DatasetClassificationRecommendation, "", ...
    "Stage 2 dataset classification recommendation."); ...
    helperMakeComparisonMetricRow("analysis_validity", ...
    "Analysis Validity", analysis.AnalysisValidity, "", ...
    "Whether Stage 2 produced a trustworthy interpretation."); ...
    helperMakeComparisonMetricRow("development_readiness", ...
    "Development Readiness", analysis.DevelopmentReadiness, "", ...
    "Whether later development is blocked, caveated, or ready."); ...
    helperMakeComparisonMetricRow("development_blocking_reason", ...
    "Development Reason", analysis.DevelopmentBlockingReason, "", ...
    "Primary machine-readable reason for the development status."); ...
    helperMakeComparisonMetricRow("classification_impact", ...
    "Classification Impact", analysis.ClassificationImpact, "", ...
    "Narrative explanation of the Stage 2 classification impact."); ...
    helperMakeComparisonMetricRow("role_source", ...
    "Role Source", analysis.RoleInfo.RoleSource, "", ...
    "Role-source selection used for Stage 2."); ...
    helperMakeComparisonMetricRow("reference_label", ...
    "Reference Label", analysis.RoleInfo.ReferenceLabel, "", ...
    "Reference-channel label used by Stage 2."); ...
    helperMakeComparisonMetricRow("surveillance_label", ...
    "Surveillance Label", analysis.RoleInfo.SurveillanceLabel, "", ...
    "Surveillance-channel label used by Stage 2."); ...
    helperMakeComparisonMetricRow("reference_power_minimum_fraction", ...
    "Reference Power Minimum Fraction", ...
    analysis.Metrics.reference_power_minimum_fraction, "fraction", ...
    "Fraction of repetitions where reference power exceeds surveillance."); ...
    helperMakeComparisonMetricRow("reference_power_target_fraction", ...
    "Reference Power Target Fraction", ...
    analysis.Metrics.reference_power_target_fraction, "fraction", ...
    "Fraction of repetitions where reference margin reaches the target."); ...
    helperMakeComparisonMetricRow( ...
    "reference_minus_surveillance_power_db_min", ...
    "Reference Minus Surveillance Power Min", ...
    analysis.Metrics.reference_minus_surveillance_power_db_min, "dB", ...
    "Minimum reference-minus-surveillance power difference."); ...
    helperMakeComparisonMetricRow( ...
    "reference_minus_surveillance_power_db_median", ...
    "Reference Minus Surveillance Power Median", ...
    analysis.Metrics.reference_minus_surveillance_power_db_median, ...
    "dB", ...
    "Median reference-minus-surveillance power difference."); ...
    helperMakeComparisonMetricRow( ...
    "reference_minus_surveillance_power_db_max", ...
    "Reference Minus Surveillance Power Max", ...
    analysis.Metrics.reference_minus_surveillance_power_db_max, "dB", ...
    "Maximum reference-minus-surveillance power difference."); ...
    helperMakeComparisonMetricRow("minimum_peak_headroom_db", ...
    "Minimum Peak Headroom", worstMetrics.MinimumPeakHeadroom_dB, "dB", ...
    "Worst peak headroom observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_near_rail_fraction", ...
    "Worst Near-Rail Fraction", ...
    worstMetrics.WorstNearRailFraction, "fraction", ...
    "Largest near-rail fraction observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_exact_rail_fraction", ...
    "Worst Exact-Rail Fraction", ...
    worstMetrics.WorstExactRailFraction, "fraction", ...
    "Largest exact-rail fraction observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_dc_mean_ratio_db", ...
    "Worst DC Mean Ratio", worstMetrics.WorstDcMeanRatio_dB, "dB", ...
    "Largest DC mean-ratio proxy observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_dc_spike_db", ...
    "Worst DC Spike", worstMetrics.WorstDcSpike_dB, "dB", ...
    "Largest DC spike observed across both roles."); ...
    helperMakeComparisonMetricRow( ...
    "worst_iq_amplitude_imbalance_db", ...
    "Worst IQ Amplitude Imbalance", ...
    worstMetrics.WorstIqAmplitudeImbalance_dB, "dB", ...
    "Largest absolute IQ amplitude imbalance observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_iq_phase_proxy_deg", ...
    "Worst IQ Phase Proxy", ...
    worstMetrics.WorstIqPhaseProxy_deg, "deg", ...
    "Largest absolute IQ phase proxy observed across both roles."); ...
    helperMakeComparisonMetricRow("worst_iq_impropriety", ...
    "Worst IQ Impropriety", worstMetrics.WorstIqImpropriety, "", ...
    "Largest IQ impropriety metric observed across both roles.") ...
    ];

summaryTable = struct2table(rows);
summaryTable.DisplayOrder = (1:height(summaryTable)).';

end

function worstMetrics = localComputeWorstMetrics(receiverIntegrityTable)

worstMetrics = struct();
worstMetrics.MinimumPeakHeadroom_dB = min([ ...
    receiverIntegrityTable.ReferencePeakHeadroom_dB; ...
    receiverIntegrityTable.SurveillancePeakHeadroom_dB ...
    ]);
worstMetrics.WorstNearRailFraction = max([ ...
    receiverIntegrityTable.ReferenceNearRailFraction; ...
    receiverIntegrityTable.SurveillanceNearRailFraction ...
    ]);
worstMetrics.WorstExactRailFraction = max([ ...
    receiverIntegrityTable.ReferenceExactRailFraction; ...
    receiverIntegrityTable.SurveillanceExactRailFraction ...
    ]);
worstMetrics.WorstDcMeanRatio_dB = max([ ...
    receiverIntegrityTable.ReferenceDcMeanRatio_dB; ...
    receiverIntegrityTable.SurveillanceDcMeanRatio_dB ...
    ]);
worstMetrics.WorstDcSpike_dB = max([ ...
    receiverIntegrityTable.ReferenceDcSpike_dB; ...
    receiverIntegrityTable.SurveillanceDcSpike_dB ...
    ]);
worstMetrics.WorstIqAmplitudeImbalance_dB = max(abs([ ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB; ...
    receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB ...
    ]));
worstMetrics.WorstIqPhaseProxy_deg = max(abs([ ...
    receiverIntegrityTable.ReferenceIqPhaseProxy_deg; ...
    receiverIntegrityTable.SurveillanceIqPhaseProxy_deg ...
    ]));
worstMetrics.WorstIqImpropriety = max([ ...
    receiverIntegrityTable.ReferenceIqImpropriety; ...
    receiverIntegrityTable.SurveillanceIqImpropriety ...
    ]);

end

function summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
    collectionMetadataInfo, analysis)

receiverIntegrityTable = analysis.ReceiverIntegrityTable;
referencePowerVector = ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB;
maxReferenceExactRailFraction = max( ...
    receiverIntegrityTable.ReferenceExactRailFraction);
maxSurveillanceExactRailFraction = max( ...
    receiverIntegrityTable.SurveillanceExactRailFraction);

summaryLines = [ ...
    "# G2 Stage 2 Receiver Integrity Summary"; ...
    ""; ...
    sprintf("- Dataset: `%s`", analysis.DatasetId); ...
    "- Scope: `G2_RF_Health` Stage 2 only"; ...
    "- Entry point: `runG2Stage2ReceiverIntegrity`"; ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    sprintf("- Receiver-integrity verdict: `%s`", ...
    analysis.ReceiverIntegrityVerdict); ...
    sprintf("- Legal recommendation: `%s`", ...
    analysis.LegalGateRecommendation); ...
    sprintf("- Dataset classification recommendation: `%s`", ...
    analysis.DatasetClassificationRecommendation); ...
    sprintf("- Analysis validity: `%s`", analysis.AnalysisValidity); ...
    sprintf("- Development readiness: `%s`", ...
    analysis.DevelopmentReadiness); ...
    sprintf("- Development reason: `%s`", ...
    analysis.DevelopmentBlockingReason); ...
    sprintf("- Classification impact: %s", ...
    analysis.ClassificationImpact); ...
    sprintf("- Role source: `%s`", analysis.RoleInfo.RoleSource); ...
    sprintf("- Reference label: `%s`", analysis.RoleInfo.ReferenceLabel); ...
    sprintf("- Surveillance label: `%s`", ...
    analysis.RoleInfo.SurveillanceLabel); ...
    sprintf("- Collection metadata path: `%s`", ...
    collectionMetadataInfo.MetadataPath); ...
    ""; ...
    "## Key Findings"; ...
    sprintf("- Accepted role mapping note: %s", ...
    analysis.RoleInfo.RoleNote); ...
    sprintf("- Analysis interpretation: %s", ...
    analysis.AnalysisInterpretation); ...
    sprintf("- Development interpretation: %s", ...
    analysis.DevelopmentInterpretation); ...
    sprintf("- Reference minus surveillance power range: `%.3f dB` to `%.3f dB` with median `%.3f dB`.", ...
    min(referencePowerVector), max(referencePowerVector), ...
    median(referencePowerVector)); ...
    sprintf("- Reference stronger than surveillance in `%0.1f%%` of repetitions at a `%.1f dB` minimum threshold.", ...
    100.0 * analysis.RoleEvidence.ReferencePowerMinimumFraction, ...
    analysis.Options.ReferencePowerMinimumThreshold_dB); ...
    sprintf("- Reference reaches the target `%.1f dB` margin in `%0.1f%%` of repetitions.", ...
    analysis.Options.ReferencePowerTargetMarginThreshold_dB, ...
    100.0 * analysis.RoleEvidence.ReferencePowerTargetFraction); ...
    sprintf("- Worst peak headroom: reference `%.3f dB`, surveillance `%.3f dB`.", ...
    min(receiverIntegrityTable.ReferencePeakHeadroom_dB), ...
    min(receiverIntegrityTable.SurveillancePeakHeadroom_dB)); ...
    sprintf("- Maximum near-rail fraction: reference `%.6f`, surveillance `%.6f`.", ...
    max(receiverIntegrityTable.ReferenceNearRailFraction), ...
    max(receiverIntegrityTable.SurveillanceNearRailFraction)); ...
    sprintf("- Maximum exact-rail fraction: reference `%.9f`, surveillance `%.9f`.", ...
    maxReferenceExactRailFraction, maxSurveillanceExactRailFraction); ...
    sprintf("- Worst DC spike: reference `%.3f dB`, surveillance `%.3f dB`.", ...
    max(receiverIntegrityTable.ReferenceDcSpike_dB), ...
    max(receiverIntegrityTable.SurveillanceDcSpike_dB)); ...
    sprintf("- Worst IQ impropriety: reference `%.4f`, surveillance `%.4f`.", ...
    max(receiverIntegrityTable.ReferenceIqImpropriety), ...
    max(receiverIntegrityTable.SurveillanceIqImpropriety)); ...
    ""; ...
    "## Decision Traceability"; ...
    localBuildDecisionTraceLines(analysis.DecisionTraceTable); ...
    ""; ...
    "## Output Files"; ...
    "- `receiver_integrity_table.csv`"; ...
    "- `channel_summary_table.csv`"; ...
    "- `decision_traceability_table.csv`"; ...
    "- `receiver_integrity_note.md`"; ...
    "- `config_snapshot.json`"; ...
    "- `metrics.json`"; ...
    "- `metrics.mat`"; ...
    "- `comparison_snapshot.mat`"; ...
    "- `figures/figure_01_average_role_psd.png`"; ...
    "- `figures/figure_02_receiver_metrics_overview.png`"; ...
    "- `figures/figure_03_dc_iq_and_clipping_overview.png`" ...
    ];

end

function lines = localBuildDecisionTraceLines(decisionTraceTable)

lineCount = height(decisionTraceTable);
lines = strings(lineCount, 1);

for idx = 1:lineCount
    if isnan(decisionTraceTable.WorstCaseIndex(idx))
        worstCaseText = "n/a";
    else
        worstCaseText = sprintf("%d", decisionTraceTable.WorstCaseIndex(idx));
    end

    formatText = "- `%s`: %s | threshold rule: %s | " + ...
        "worst-case repetition: %s | effect: %s";
    lines(idx) = string(sprintf(char(formatText), ...
        char(string(decisionTraceTable.DecisionItem(idx))), ...
        char(string(decisionTraceTable.MetricOrEvidence(idx))), ...
        char(string(decisionTraceTable.ThresholdRule(idx))), ...
        char(string(worstCaseText)), ...
        char(string(decisionTraceTable.Effect(idx)))));
end

end

function lines = localBuildReceiverIntegrityNoteLines( ...
    collectionMetadataInfo, analysis)

receiverIntegrityTable = analysis.ReceiverIntegrityTable;
referencePowerVector = ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB;
maxReferenceNearRailFraction = max( ...
    receiverIntegrityTable.ReferenceNearRailFraction);
maxSurveillanceNearRailFraction = max( ...
    receiverIntegrityTable.SurveillanceNearRailFraction);
maxReferenceExactRailFraction = max( ...
    receiverIntegrityTable.ReferenceExactRailFraction);
maxSurveillanceExactRailFraction = max( ...
    receiverIntegrityTable.SurveillanceExactRailFraction);
maxReferenceImpropriety = max(receiverIntegrityTable.ReferenceIqImpropriety);
maxSurveillanceImpropriety = max( ...
    receiverIntegrityTable.SurveillanceIqImpropriety);
maxReferenceDcSpike = max(receiverIntegrityTable.ReferenceDcSpike_dB);
maxSurveillanceDcSpike = max( ...
    receiverIntegrityTable.SurveillanceDcSpike_dB);
hasSevereClipping = any( ...
    receiverIntegrityTable.ReferenceNearRailFraction >= ...
    analysis.Options.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.SurveillanceNearRailFraction >= ...
    analysis.Options.SevereClippingFractionThreshold | ...
    receiverIntegrityTable.ReferenceExactRailFraction > 0.0 | ...
    receiverIntegrityTable.SurveillanceExactRailFraction > 0.0);
hasSevereIqIssue = any( ...
    receiverIntegrityTable.ReferenceIqImpropriety >= ...
    analysis.Options.IqImproprietySevereThreshold | ...
    receiverIntegrityTable.SurveillanceIqImpropriety >= ...
    analysis.Options.IqImproprietySevereThreshold);
hasModerateIqIssue = any( ...
    receiverIntegrityTable.ReferenceIqImpropriety >= ...
    analysis.Options.IqImproprietyDiagnosticThreshold | ...
    receiverIntegrityTable.SurveillanceIqImpropriety >= ...
    analysis.Options.IqImproprietyDiagnosticThreshold);

positiveEvidenceLines = [ ...
    sprintf("- Role mapping source is `%s`, using reference `%s` and surveillance `%s`.", ...
    analysis.RoleInfo.RoleSource, analysis.RoleInfo.ReferenceLabel, ...
    analysis.RoleInfo.SurveillanceLabel); ...
    sprintf("- Manual antenna metadata remains available at `%s`.", ...
    collectionMetadataInfo.MetadataPath); ...
    sprintf("- DC mean-offset and DC-spike metrics remain below the current diagnostic threshold, with worst DC spikes of reference `%.3f dB` and surveillance `%.3f dB` relative to local PSD floor.", ...
    maxReferenceDcSpike, maxSurveillanceDcSpike) ...
    ];

caveatLines = [ ...
    sprintf("- The accepted reference channel is weaker than surveillance in every repetition, with reference-minus-surveillance power ranging from `%.3f dB` to `%.3f dB`.", ...
    min(referencePowerVector), max(referencePowerVector)); ...
    sprintf("- Median mean power is reference `%.3f dBFS` versus surveillance `%.3f dBFS`, so the current role-based power ordering does not match the preferred Stage 2 condition.", ...
    median(receiverIntegrityTable.ReferenceMeanPower_dBFS), ...
    median(receiverIntegrityTable.SurveillanceMeanPower_dBFS)); ...
    sprintf("- Surveillance headroom is tighter than reference, with minimum peak headroom `%.3f dB` versus `%.3f dB`.", ...
    min(receiverIntegrityTable.SurveillancePeakHeadroom_dB), ...
    min(receiverIntegrityTable.ReferencePeakHeadroom_dB)) ...
    ];

if hasSevereClipping
    caveatLines(end + 1, 1) = sprintf("- Severe clipping criteria were met because exact-rail samples or severe near-rail occupancy were observed; maximum near-rail fractions are reference `%.9f` and surveillance `%.9f`, and maximum exact-rail fractions are reference `%.9f` and surveillance `%.9f`.", ...
        maxReferenceNearRailFraction, maxSurveillanceNearRailFraction, ...
        maxReferenceExactRailFraction, maxSurveillanceExactRailFraction);
elseif maxReferenceNearRailFraction > 0.0 || maxSurveillanceNearRailFraction > 0.0
    caveatLines(end + 1, 1) = "- Minor nonzero near-rail occupancy is present even though no exact-rail samples were observed.";
else
    positiveEvidenceLines(end + 1, 1) = sprintf("- No exact-rail samples were observed; maximum near-rail fractions are reference `%.9f` and surveillance `%.9f`.", ...
        maxReferenceNearRailFraction, maxSurveillanceNearRailFraction);
end

if hasSevereIqIssue
    caveatLines(end + 1, 1) = sprintf("- IQ/image-risk proxies are severe on at least one channel; worst impropriety is reference `%.4f` and surveillance `%.4f`.", ...
        maxReferenceImpropriety, maxSurveillanceImpropriety);
elseif hasModerateIqIssue
    caveatLines(end + 1, 1) = sprintf("- IQ/image-risk proxies exceed the current diagnostic threshold on at least one channel; worst impropriety is reference `%.4f` and surveillance `%.4f`.", ...
        maxReferenceImpropriety, maxSurveillanceImpropriety);
else
    positiveEvidenceLines(end + 1, 1) = sprintf("- IQ/image-risk proxies remain below the current diagnostic threshold, with worst impropriety of reference `%.4f` and surveillance `%.4f`.", maxReferenceImpropriety, ...
        maxSurveillanceImpropriety);
end

if analysis.AnalysisValidity == "invalid"
    interpretationLines = [ ...
        "- Stage 2 did not establish a trustworthy receiver-integrity " + ...
        "interpretation for this session."; ...
        "- The current blocker is analysis validity rather than the RF " + ...
        "verdict itself."; ...
        "- Repair the role mapping or incomplete metrics before using " + ...
        "this session to justify later stages." ...
        ];
elseif analysis.ReceiverIntegrityVerdict == "receiver_integrity_hard_fail"
    interpretationLines = [ ...
        "- Receiver integrity shows a hard failure in this session."; ...
        "- The dominant hard-fail driver is severe IQ/image-risk behavior, while the accepted reference channel also remains weaker than surveillance."; ...
        "- Stage 2 therefore recommends `reject` and the dataset should not be carried forward without collection changes or a justified re-interpretation of the channel roles." ...
        ];
elseif analysis.ReceiverIntegrityVerdict == "receiver_integrity_caveated"
    interpretationLines = [ ...
        "- Receiver integrity does not show a hard clipping or DC failure in this session."; ...
        "- The main Stage 2 concern is role-based power ordering: the accepted reference channel is not stronger than surveillance."; ...
        "- Stage 2 therefore recommends `retune` and keeps the dataset `diagnostic` until later stages or a future recollection show a stronger reference view." ...
        ];
else
    interpretationLines = [ ...
        "- Receiver integrity metrics remain within the current Stage 2 thresholds."; ...
        "- The accepted reference channel behavior is consistent enough to support downstream review."; ...
        "- Stage 2 therefore recommends `pass` on receiver integrity for this dataset." ...
        ];
end

lines = [ ...
    "# Receiver Integrity Note"; ...
    ""; ...
    sprintf("- Current Stage 2 verdict: `%s`", ...
    analysis.ReceiverIntegrityVerdict); ...
    sprintf("- Legal recommendation: `%s`", ...
    analysis.LegalGateRecommendation); ...
    sprintf("- Dataset classification recommendation: `%s`", ...
    analysis.DatasetClassificationRecommendation); ...
    sprintf("- Analysis validity: `%s`", ...
    analysis.AnalysisValidity); ...
    sprintf("- Development readiness: `%s`", ...
    analysis.DevelopmentReadiness); ...
    sprintf("- Development reason: `%s`", ...
    analysis.DevelopmentBlockingReason); ...
    ""; ...
    "## Positive Evidence"; ...
    positiveEvidenceLines; ...
    ""; ...
    "## Caveats"; ...
    caveatLines; ...
    ""; ...
    "## Analysis And Development Interpretation"; ...
    sprintf("- Analysis interpretation: %s", ...
    analysis.AnalysisInterpretation); ...
    sprintf("- Development interpretation: %s", ...
    analysis.DevelopmentInterpretation); ...
    ""; ...
    "## Stage 2 Interpretation"; ...
    interpretationLines ...
    ];

end

function localRenderAveragePsdFigure(analysis, figurePath, showFigures)

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G2 Stage 2 Average PSD by Accepted Role", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
tiledlayout(1, 1);
nexttile;
plot(analysis.RoleEvidence.PsdFrequencyHz / 1.0e6, ...
    pow2db(analysis.RoleEvidence.ReferenceMeanPsd + eps), ...
    "LineWidth", 1.4);
hold on
plot(analysis.RoleEvidence.PsdFrequencyHz / 1.0e6, ...
    pow2db(analysis.RoleEvidence.SurveillanceMeanPsd + eps), ...
    "LineWidth", 1.4);
hold off
grid on
xlabel("Frequency [MHz]");
ylabel("PSD [dB/Hz]");
title("G2 Stage 2 Average PSD by Accepted Role");
legend("Reference", "Surveillance", Location = "best");
drawnow

try
    exportgraphics(figureHandle, figurePath);
catch exportException
    error("runG2Stage2ReceiverIntegrity:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, ...
        exportException.message);
end

clear cleanupObject

end

function localRenderReceiverMetricsFigure(analysis, figurePath, showFigures)

receiverIntegrityTable = analysis.ReceiverIntegrityTable;
repetitionVector = receiverIntegrityTable.Repetition;

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G2 Stage 2 Receiver Metrics Overview", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
tiledlayout(3, 1);

nexttile;
plot(repetitionVector, receiverIntegrityTable.ReferenceMeanPower_dBFS, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, receiverIntegrityTable.SurveillanceMeanPower_dBFS, ...
    "-o", "LineWidth", 1.2);
hold off
grid on
xlabel("Repetition");
ylabel("Mean Power [dBFS]");
title("Receiver Mean Power by Accepted Role");
legend("Reference", "Surveillance", Location = "best");

nexttile;
plot(repetitionVector, ...
    receiverIntegrityTable.ReferenceMinusSurveillancePower_dB, ...
    "-o", "LineWidth", 1.2);
hold on
yline(analysis.Options.ReferencePowerMinimumThreshold_dB, "--", ...
    "LineWidth", 1.0);
yline(analysis.Options.ReferencePowerTargetMarginThreshold_dB, "--", ...
    "LineWidth", 1.0);
hold off
grid on
xlabel("Repetition");
ylabel("Reference - Surveillance [dB]");
title("Reference Power Advantage");
legend("Observed", "Minimum", "Target", Location = "best");

nexttile;
plot(repetitionVector, receiverIntegrityTable.ReferencePeakHeadroom_dB, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, ...
    receiverIntegrityTable.SurveillancePeakHeadroom_dB, ...
    "-o", "LineWidth", 1.2);
hold off
grid on
xlabel("Repetition");
ylabel("Peak Headroom [dB]");
title("Peak Headroom by Accepted Role");
legend("Reference", "Surveillance", Location = "best");
drawnow

try
    exportgraphics(figureHandle, figurePath);
catch exportException
    error("runG2Stage2ReceiverIntegrity:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, ...
        exportException.message);
end

clear cleanupObject

end

function localRenderContaminationFigure(analysis, figurePath, showFigures)

receiverIntegrityTable = analysis.ReceiverIntegrityTable;
repetitionVector = receiverIntegrityTable.Repetition;

figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G2 Stage 2 DC, IQ, and Clipping Overview", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
tiledlayout(2, 2);

nexttile;
plot(repetitionVector, receiverIntegrityTable.ReferenceNearRailFraction, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, ...
    receiverIntegrityTable.SurveillanceNearRailFraction, ...
    "-o", "LineWidth", 1.2);
yline(analysis.Options.SevereClippingFractionThreshold, "--", ...
    "LineWidth", 1.0);
hold off
grid on
xlabel("Repetition");
ylabel("Near-Rail Fraction");
title("Near-Rail Occupancy");
legend("Reference", "Surveillance", "Severe Threshold", ...
    Location = "best");

nexttile;
plot(repetitionVector, receiverIntegrityTable.ReferenceDcSpike_dB, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, receiverIntegrityTable.SurveillanceDcSpike_dB, ...
    "-o", "LineWidth", 1.2);
yline(analysis.Options.DcSpikeDiagnosticThreshold_dB, "--", ...
    "LineWidth", 1.0);
hold off
grid on
xlabel("Repetition");
ylabel("DC Spike [dB]");
title("DC Spike Relative to Local PSD Floor");
legend("Reference", "Surveillance", "Diagnostic Threshold", ...
    Location = "best");

nexttile;
plot(repetitionVector, ...
    receiverIntegrityTable.ReferenceIqAmplitudeImbalance_dB, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, ...
    receiverIntegrityTable.SurveillanceIqAmplitudeImbalance_dB, ...
    "-o", "LineWidth", 1.2);
yline(analysis.Options.IqAmplitudeImbalanceDiagnosticThreshold_dB, "--", ...
    "LineWidth", 1.0);
yline(-analysis.Options.IqAmplitudeImbalanceDiagnosticThreshold_dB, "--", ...
    "LineWidth", 1.0);
hold off
grid on
xlabel("Repetition");
ylabel("Amplitude Imbalance [dB]");
title("I/Q Amplitude Imbalance Proxy");
legend("Reference", "Surveillance", "Diagnostic Threshold", ...
    Location = "best");

nexttile;
plot(repetitionVector, receiverIntegrityTable.ReferenceIqImpropriety, ...
    "-o", "LineWidth", 1.2);
hold on
plot(repetitionVector, receiverIntegrityTable.SurveillanceIqImpropriety, ...
    "-o", "LineWidth", 1.2);
yline(analysis.Options.IqImproprietyDiagnosticThreshold, "--", ...
    "LineWidth", 1.0);
hold off
grid on
xlabel("Repetition");
ylabel("Impropriety");
title("I/Q Image-Risk Proxy");
legend("Reference", "Surveillance", "Diagnostic Threshold", ...
    Location = "best");
drawnow

try
    exportgraphics(figureHandle, figurePath);
catch exportException
    error("runG2Stage2ReceiverIntegrity:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, ...
        exportException.message);
end

clear cleanupObject

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG2Stage2ReceiverIntegrity:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

try
    fileIdentifier = fopen(filePath, "w");
catch openException
    error("runG2Stage2ReceiverIntegrity:OpenTextFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        openException.message);
end

if fileIdentifier == -1
    error("runG2Stage2ReceiverIntegrity:OpenTextFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileIdentifier));
lines = string(lines);

for idx = 1:numel(lines)
    fprintf(fileIdentifier, "%s\n", lines(idx));
end

clear cleanupObject

end

function localWriteJsonFile(filePath, inputStruct)

try
    jsonText = jsonencode(inputStruct, PrettyPrint = true);
catch encodeException
    error("runG2Stage2ReceiverIntegrity:JsonEncodeFailed", ...
        "Failed to encode JSON for %s: %s", filePath, ...
        encodeException.message);
end

localWriteTextFile(filePath, jsonText);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return
end

if ~isfolder(bundleRoot)
    try
        mkdir(bundleRoot);
    catch
        return
    end
end

try
    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G2 Stage 2 Receiver Integrity Summary"; ...
        ""; ...
        "- Stage status: `failed`"; ...
        sprintf("- Failure message: `%s`", mainException.message) ...
        ]);
catch
end

end

function visibility = localResolveFigureVisibility(showFigures)

if showFigures
    visibility = "on";
else
    visibility = "off";
end

end

function cleanupObject = localCreateFigureCleanup(figureHandle, showFigures)

if showFigures
    cleanupObject = [];
    return
end

cleanupObject = onCleanup(@() close(figureHandle));

end
