function results = runG3SyncCore(datasetId, repoRoot, options)
%RUNG3SYNCCORE Execute the Stage 3 manual-review sync-core runner.
%
%   RESULTS = RUNG3SYNCCORE() runs the current standalone Stage 3
%   sync-analysis core on the reference dataset and writes a manual-review
%   evidence bundle under:
%   artifacts/<datasetId>/G3_Sync_Core/<runTimestampZ>/
%
%   This is not the final G3 gate runner. It exists so the implemented
%   Stage 3 sync review can be run, exported, and reviewed independently
%   while the whole-gate acceptance logic remains non-final.

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

totalTimer = tic;
stepTimer = tic;
stageArtifactId = "G3_Sync_Core";
repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
[analysisOptions, runnerOptions] = localResolveRunnerOptions(options);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
bundleRoot = fullfile(repoRoot, "artifacts", datasetId, stageArtifactId, ...
    runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");
timingRows = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", 0.0, runnerOptions.ExecutionMode);
timingRows(1) = [];
timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
    "resolve_inputs", toc(stepTimer), runnerOptions.ExecutionMode, ...
    NaN, NaN, NaN, NaN, NaN, "");
fprintf("Running G3 Sync Core manual review for dataset %s\n", datasetId);
fprintf("Repository root:\t%s\n", repoRoot);
fprintf("Execution mode:\t%s\n", runnerOptions.ExecutionMode);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);

    stepTimer = tic;
    loadOptions = struct();
    loadOptions.IncludeSamples = true;
    sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    inputRepetitionCount = double(numel(sessionData.RadarScans));
    inputSampleCount = double(sum([sessionData.RadarScans.NumSamples]));
    collectionMetadataPath = fullfile(sessionData.DatasetRoot, ...
        "collection_metadata.json");
    collectionMetadataInfo = helperReadCollectionMetadata( ...
        collectionMetadataPath, datasetId);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "load_session_with_samples", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "loadIQData IncludeSamples=true plus collection metadata parse.");

    stepTimer = tic;
    analysis = helperAnalyzeG3SyncCore(sessionData, ...
        collectionMetadataInfo, analysisOptions);
    cpiDefinitionsTable = localBuildCpiDefinitionTable(analysis.Options);
    interpretationSummaryTable = localBuildInterpretationSummaryTable( ...
        analysis);
    configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
        bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
        runnerOptions);
    comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
        runTimestampZ, bundleRoot, collectionMetadataInfo, analysis);
    summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
        collectionMetadataInfo, analysis);
    syncInterpretationNoteLines = localBuildSyncInterpretationNoteLines( ...
        collectionMetadataInfo, analysis);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "run_g3_sync_helper", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, NaN, NaN, NaN, ...
        "G3 sync analysis helper plus bundle summary preparation.");

    summaryPath = fullfile(bundleRoot, "summary.md");
    interpretationNotePath = fullfile(bundleRoot, ...
        "sync_interpretation_note.md");
    questionSummariesPath = fullfile(bundleRoot, "question_summaries.csv");
    lagTablePath = fullfile(bundleRoot, "lag_table.csv");
    residualFrequencyTablePath = fullfile(bundleRoot, ...
        "residual_frequency_table.csv");
    cpiCoherenceTablePath = fullfile(bundleRoot, ...
        "cpi_coherence_table.csv");
    strategyComparisonTablePath = fullfile(bundleRoot, ...
        "strategy_comparison_table.csv");
    cpiDefinitionsPath = fullfile(bundleRoot, "cpi_definitions.csv");
    interpretationSummaryPath = fullfile(bundleRoot, ...
        "interpretation_summary.csv");
    blockingFindingsPath = fullfile(bundleRoot, "blocking_findings.csv");
    configSnapshotPath = fullfile(bundleRoot, "config_snapshot.json");
    metricsJsonPath = fullfile(bundleRoot, "metrics.json");
    metricsMatPath = fullfile(bundleRoot, "metrics.mat");
    lagFigurePath = fullfile(figureRoot, ...
        "figure_01_lag_stability_overview.png");
    residualFrequencyFigurePath = fullfile(figureRoot, ...
        "figure_02_residual_frequency_overview.png");
    coherenceStrategyFigurePath = fullfile(figureRoot, ...
        "figure_03_coherence_and_strategy_overview.png");

    stepTimer = tic;
    try
        writetable(analysis.QuestionSummaries, questionSummariesPath);
        writetable(analysis.LagTable, lagTablePath);
        writetable(analysis.ResidualFrequencyTable, ...
            residualFrequencyTablePath);
        writetable(analysis.CpiCoherenceTable, cpiCoherenceTablePath);
        writetable(analysis.StrategyComparisonTable, ...
            strategyComparisonTablePath);
        writetable(cpiDefinitionsTable, cpiDefinitionsPath);
        writetable(interpretationSummaryTable, interpretationSummaryPath);

        if ~isempty(analysis.BlockingFindings)
            writetable(localBuildBlockingFindingsTable( ...
                analysis.BlockingFindings), blockingFindingsPath);
        end
    catch writeTableException
        error("runG3SyncCore:WriteTableFailed", ...
            "Failed to write a Stage 3 table artifact: %s", ...
            writeTableException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_tables", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, ...
        7 + double(~isempty(analysis.BlockingFindings)), 0, NaN, ...
        "Question, lag, residual-frequency, coherence, strategy, CPI, interpretation, and optional blocking CSVs.");

    stepTimer = tic;
    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(interpretationNotePath, ...
        syncInterpretationNoteLines);
    localWriteJsonFile(configSnapshotPath, configSnapshot);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_text_artifacts", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 3, 0, NaN, ...
        "Summary, interpretation note, and config JSON.");

    stepTimer = tic;
    localWriteJsonFile(metricsJsonPath, analysis.Metrics);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_metrics_json", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 1, 0, NaN, "metrics.json");

    stepTimer = tic;
    try
        save(metricsMatPath, "analysis");
    catch saveException
        error("runG3SyncCore:SaveMetricsFailed", ...
            "Failed to write Stage 3 metrics.mat: %s", ...
            saveException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_metrics_mat", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 1, 0, NaN, ...
        "metrics.mat");

    stepTimer = tic;
    try
        comparisonSnapshotPath = helperWriteComparisonSnapshot( ...
            string(bundleRoot), comparisonSnapshot);
    catch saveException
        error("runG3SyncCore:SaveComparisonSnapshotFailed", ...
            "Failed to write Stage 3 comparison snapshot: %s", ...
            saveException.message);
    end
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "write_comparison_snapshot", toc(stepTimer), ...
        runnerOptions.ExecutionMode, inputSampleCount, ...
        inputRepetitionCount, 1, 0, NaN, "comparison_snapshot.mat");

    stepTimer = tic;
    localRenderLagOverviewFigure(analysis, lagFigurePath, ...
        runnerOptions.ShowFigures);
    localRenderResidualFrequencyFigure(analysis, ...
        residualFrequencyFigurePath, runnerOptions.ShowFigures);
    localRenderCoherenceStrategyFigure(analysis, ...
        coherenceStrategyFigurePath, runnerOptions.ShowFigures);
    timingRows(end + 1) = helperMakeTimingSummaryRow(stageArtifactId, ...
        "render_figures", toc(stepTimer), runnerOptions.ExecutionMode, ...
        inputSampleCount, inputRepetitionCount, 3, 3, NaN, ...
        "Lag, residual-frequency, and coherence/strategy figures.");

    [timingSummaryTable, performanceSummary] = ...
        helperFinalizePerformanceInstrumentation(stageArtifactId, ...
        datasetId, string(bundleRoot), runTimestampZ, ...
        runnerOptions.ExecutionMode, runnerOptions.ShowFigures, ...
        timingRows, totalTimer, inputSampleCount, ...
        inputRepetitionCount, string(metricsMatPath));

    results = struct();
    results.DatasetId = datasetId;
    results.StageId = string(analysis.StageId);
    results.RunTimestampZ = runTimestampZ;
    results.BundleRoot = string(bundleRoot);
    results.OverallLabel = string(analysis.Interpretation.OverallLabel);
    results.OverallRationale = string( ...
        analysis.Interpretation.OverallRationale);
    results.RecommendedStrategyCandidate = string( ...
        analysis.RecommendedStrategyCandidate);
    results.ReferenceLabel = string( ...
        analysis.Interpretation.ReferenceLabel);
    results.SurveillanceLabel = string( ...
        analysis.Interpretation.SurveillanceLabel);
    results.BlockingFindings = string(analysis.BlockingFindings(:));
    results.QuestionSummaries = analysis.QuestionSummaries;
    results.LagTable = analysis.LagTable;
    results.ResidualFrequencyTable = analysis.ResidualFrequencyTable;
    results.CpiCoherenceTable = analysis.CpiCoherenceTable;
    results.StrategyComparisonTable = analysis.StrategyComparisonTable;
    results.Interpretation = analysis.Interpretation;
    results.Metrics = analysis.Metrics;
    results.Options = analysis.Options;
    results.FigurePaths = [string(lagFigurePath); ...
        string(residualFrequencyFigurePath); ...
        string(coherenceStrategyFigurePath)];
    results.ComparisonSnapshotPath = string(comparisonSnapshotPath);
    results.TimingSummaryTable = timingSummaryTable;
    results.PerformanceSummary = performanceSummary;

    fprintf("Overall label:\t%s\n", results.OverallLabel);
    fprintf("Recommended strategy:\t%s\n", ...
        results.RecommendedStrategyCandidate);
    fprintf("Blocking findings:\t%d\n", numel(results.BlockingFindings));
    fprintf("Bundle root:\t%s\n", bundleRoot);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end

function [analysisOptions, runnerOptions] = localResolveRunnerOptions(options)

analysisOptions = options;
runnerOptions = struct();
runnerOptions.ExecutionMode = helperResolveExecutionMode(options);
runnerOptions.ShowFigures = usejava("desktop");

if runnerOptions.ExecutionMode == "analysis_only"
    runnerOptions.ShowFigures = false;
end

if isfield(options, "ShowFigures")
    runnerOptions.ShowFigures = logical(options.ShowFigures);
    analysisOptions = rmfield(analysisOptions, "ShowFigures");
end

if isfield(analysisOptions, "ExecutionMode")
    analysisOptions = rmfield(analysisOptions, "ExecutionMode");
end

end

function cpiDefinitionTable = localBuildCpiDefinitionTable(optionsOutput)

cpiDefinitions = optionsOutput.CpiDefinitions;
cpiCount = numel(cpiDefinitions);
cpiLabel = strings(cpiCount, 1);
duration_s = zeros(cpiCount, 1);
samples = zeros(cpiCount, 1);
windowHopSamples = zeros(cpiCount, 1);

for idx = 1:cpiCount
    cpiLabel(idx) = string(cpiDefinitions(idx).Label);
    duration_s(idx) = double(cpiDefinitions(idx).Duration_s);
    samples(idx) = double(cpiDefinitions(idx).Samples);
    windowHopSamples(idx) = double(cpiDefinitions(idx).WindowHopSamples);
end

cpiDefinitionTable = table(cpiLabel, duration_s, samples, ...
    windowHopSamples, VariableNames = {'CpiLabel', 'Duration_s', ...
    'Samples', 'WindowHopSamples'});

end

function interpretationSummaryTable = localBuildInterpretationSummaryTable( ...
    analysis)

blockingFindingsText = localJoinStringVector(analysis.BlockingFindings);
interpretationSummaryTable = table( ...
    string(analysis.Interpretation.OverallLabel), ...
    string(analysis.Interpretation.OverallRationale), ...
    string(analysis.RecommendedStrategyCandidate), ...
    string(analysis.Interpretation.ReferenceLabel), ...
    string(analysis.Interpretation.SurveillanceLabel), ...
    double(analysis.Interpretation.BlockingFindingCount), ...
    blockingFindingsText, ...
    VariableNames = {'OverallLabel', 'OverallRationale', ...
    'RecommendedStrategyCandidate', 'ReferenceLabel', ...
    'SurveillanceLabel', 'BlockingFindingCount', ...
    'BlockingFindingsText'});

end

function blockingFindingsTable = localBuildBlockingFindingsTable( ...
    blockingFindings)

blockingFindingsTable = table(string(blockingFindings(:)), ...
    VariableNames = {'BlockingFinding'});

end

function configSnapshot = localBuildConfigSnapshot(datasetId, repoRoot, ...
    bundleRoot, runTimestampZ, collectionMetadataInfo, analysis, ...
    runnerOptions)

configSnapshot = struct();
configSnapshot.dataset_id = datasetId;
configSnapshot.stage_id = "G3_Sync_Core";
configSnapshot.entry_point = "runG3SyncCore";
configSnapshot.repo_root = repoRoot;
configSnapshot.bundle_root = string(bundleRoot);
configSnapshot.run_timestamp_z = runTimestampZ;
configSnapshot.collection_metadata_path = ...
    collectionMetadataInfo.MetadataPath;
configSnapshot.collection_metadata_present = ...
    collectionMetadataInfo.MetadataPresent;
configSnapshot.collection_metadata_session_id_matches = ...
    collectionMetadataInfo.SessionIdMatches;
configSnapshot.show_figures = runnerOptions.ShowFigures;
configSnapshot.execution_mode = runnerOptions.ExecutionMode;
configSnapshot.reference_label = ...
    analysis.Interpretation.ReferenceLabel;
configSnapshot.surveillance_label = ...
    analysis.Interpretation.SurveillanceLabel;
configSnapshot.role_source = string(analysis.Metrics.role_source);
configSnapshot.role_note = analysis.Interpretation.RoleNote;
configSnapshot.analysis_options = analysis.Options;
configSnapshot.matlab_version = string(version);
configSnapshot.matlab_release = string(version("-release"));
configSnapshot.computer = string(computer);

end

function comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
    runTimestampZ, bundleRoot, collectionMetadataInfo, analysis)

summaryTable = localBuildComparisonSummaryTable(analysis);

comparisonSnapshot = struct();
comparisonSnapshot.DatasetId = string(datasetId);
comparisonSnapshot.StageId = string(analysis.StageId);
comparisonSnapshot.RunTimestampZ = string(runTimestampZ);
comparisonSnapshot.BundleRoot = string(bundleRoot);
comparisonSnapshot.CollectionMetadataPath = ...
    string(collectionMetadataInfo.MetadataPath);
comparisonSnapshot.OverallLabel = string( ...
    analysis.Interpretation.OverallLabel);
comparisonSnapshot.OverallRationale = string( ...
    analysis.Interpretation.OverallRationale);
comparisonSnapshot.RecommendedStrategyCandidate = string( ...
    analysis.RecommendedStrategyCandidate);
comparisonSnapshot.ReferenceLabel = string( ...
    analysis.Interpretation.ReferenceLabel);
comparisonSnapshot.SurveillanceLabel = string( ...
    analysis.Interpretation.SurveillanceLabel);
comparisonSnapshot.RoleSource = string(analysis.Metrics.role_source);
comparisonSnapshot.BlockingFindingCount = double( ...
    analysis.Interpretation.BlockingFindingCount);
comparisonSnapshot.BlockingFindings = string(analysis.BlockingFindings(:));
comparisonSnapshot.QuestionSummaries = analysis.QuestionSummaries;
comparisonSnapshot.StrategyComparisonTable = ...
    analysis.StrategyComparisonTable;
comparisonSnapshot.SummaryTable = summaryTable;

end

function summaryTable = localBuildComparisonSummaryTable(analysis)

globalRow = localExtractStrategyRow(analysis.StrategyComparisonTable, ...
    "global_session_correction");
perCaptureRow = localExtractStrategyRow(analysis.StrategyComparisonTable, ...
    "per_capture_correction");
subwindowRow = localExtractStrategyRow(analysis.StrategyComparisonTable, ...
    "subwindow_correction");

rows = [ ...
    helperMakeComparisonMetricRow("overall_label", ...
    "Overall Label", analysis.Interpretation.OverallLabel, "", ...
    "Overall Stage 3 manual-review interpretation."); ...
    helperMakeComparisonMetricRow("recommended_strategy_candidate", ...
    "Recommended Strategy Candidate", ...
    analysis.RecommendedStrategyCandidate, "", ...
    "Recommended correction strategy candidate."); ...
    helperMakeComparisonMetricRow("reference_label", ...
    "Reference Label", analysis.Interpretation.ReferenceLabel, "", ...
    "Reference-channel label fixed from Stage 2."); ...
    helperMakeComparisonMetricRow("surveillance_label", ...
    "Surveillance Label", analysis.Interpretation.SurveillanceLabel, "", ...
    "Surveillance-channel label fixed from Stage 2."); ...
    helperMakeComparisonMetricRow("blocking_finding_count", ...
    "Blocking Finding Count", ...
    analysis.Interpretation.BlockingFindingCount, "count", ...
    "Number of machine-readable blocking findings."); ...
    helperMakeComparisonMetricRow("max_lag_spread_samples", ...
    "Max Lag Spread", max(analysis.LagTable.LagWindowSpread_samples), ...
    "samples", ...
    "Worst lag spread across repetition and CPI subsets."); ...
    helperMakeComparisonMetricRow("min_delay_agreement_fraction", ...
    "Min Delay Agreement Fraction", ...
    min(analysis.LagTable.DelayEstimateAgreementFraction), ...
    "fraction", ...
    "Worst agreement between finddelay and xcorr lag estimates."); ...
    helperMakeComparisonMetricRow("min_peak_to_sidelobe_db", ...
    "Min Peak-to-Sidelobe", ...
    min(analysis.LagTable.PeakToSidelobeMin_dB), "dB", ...
    "Worst lag peak sharpness across repetition and CPI subsets."); ...
    helperMakeComparisonMetricRow( ...
    "median_abs_residual_frequency_hz", ...
    "Median Absolute Residual Frequency", ...
    median(analysis.ResidualFrequencyTable.ResidualFrequencyAbsMedian_Hz), ...
    "Hz", "Median residual-frequency magnitude across subsets."); ...
    helperMakeComparisonMetricRow("max_phase_excursion_deg", ...
    "Max Phase Excursion", ...
    max(analysis.ResidualFrequencyTable.PhaseExcursionMax_deg), "deg", ...
    "Worst phase excursion across repetition and CPI subsets."); ...
    helperMakeComparisonMetricRow("min_coherence_pass_fraction", ...
    "Min Coherence Pass Fraction", ...
    min(analysis.CpiCoherenceTable.CoherencePassFraction), ...
    "fraction", ...
    "Worst coherence pass fraction across repetition and CPI subsets."); ...
    helperMakeComparisonMetricRow("median_coherence", ...
    "Median Coherence", median(analysis.CpiCoherenceTable.CoherenceMedian), ...
    "", "Median band-mean coherence across repetition and CPI subsets."); ...
    helperMakeComparisonMetricRow( ...
    "global_strategy_pass_fraction", ...
    "Global Strategy Pass Fraction", ...
    globalRow.ObservablePassFraction, "fraction", ...
    "Observable pass fraction for the global-session candidate."); ...
    helperMakeComparisonMetricRow( ...
    "per_capture_strategy_pass_fraction", ...
    "Per-Capture Strategy Pass Fraction", ...
    perCaptureRow.ObservablePassFraction, "fraction", ...
    "Observable pass fraction for the per-capture candidate."); ...
    helperMakeComparisonMetricRow( ...
    "subwindow_strategy_pass_fraction", ...
    "Subwindow Strategy Pass Fraction", ...
    subwindowRow.ObservablePassFraction, "fraction", ...
    "Observable pass fraction for the subwindow candidate.") ...
    ];

summaryTable = struct2table(rows);
summaryTable.DisplayOrder = (1:height(summaryTable)).';

end

function strategyRow = localExtractStrategyRow(strategyComparisonTable, ...
    strategyCandidate)

strategyRow = strategyComparisonTable( ...
    strategyComparisonTable.StrategyCandidate == strategyCandidate, :);

if height(strategyRow) ~= 1
    error("runG3SyncCore:MissingStrategyRow", ...
        "Expected one strategy row for %s.", strategyCandidate);
end

end

function summaryLines = localBuildSummaryLines(bundleRoot, runTimestampZ, ...
    collectionMetadataInfo, analysis)

summaryLines = [ ...
    "# G3 Sync Core Summary"; ...
    ""; ...
    sprintf("- Dataset: `%s`", analysis.DatasetId); ...
    "- Scope: `G3_Sync` manual-review slice only"; ...
    "- Entry point: `runG3SyncCore`"; ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    sprintf("- Overall label: `%s`", ...
    analysis.Interpretation.OverallLabel); ...
    sprintf("- Overall rationale: %s", ...
    analysis.Interpretation.OverallRationale); ...
    sprintf("- Recommended strategy candidate: `%s`", ...
    analysis.RecommendedStrategyCandidate); ...
    sprintf("- Reference label: `%s`", ...
    analysis.Interpretation.ReferenceLabel); ...
    sprintf("- Surveillance label: `%s`", ...
    analysis.Interpretation.SurveillanceLabel); ...
    sprintf("- Role source: `%s`", string(analysis.Metrics.role_source)); ...
    sprintf("- Collection metadata path: `%s`", ...
    collectionMetadataInfo.MetadataPath); ...
    ""; ...
    "## Question Summary"; ...
    localBuildQuestionSummaryLines(analysis.QuestionSummaries); ...
    ""; ...
    "## Key Findings"; ...
    sprintf("- Recommended strategy remains `%s` at the `%s` review CPI.", ...
    analysis.RecommendedStrategyCandidate, ...
    analysis.Options.StrategyComparisonCpiLabel); ...
    sprintf("- Maximum lag spread is `%.1f` samples, with minimum delay-agreement fraction `%.2f`.", ...
    max(analysis.LagTable.LagWindowSpread_samples), ...
    min(analysis.LagTable.DelayEstimateAgreementFraction)); ...
    sprintf("- Median absolute residual frequency is `%.3f Hz`, and maximum phase excursion is `%.2f deg`.", ...
    median(analysis.ResidualFrequencyTable.ResidualFrequencyAbsMedian_Hz), ...
    max(analysis.ResidualFrequencyTable.PhaseExcursionMax_deg)); ...
    sprintf("- Minimum coherence pass fraction is `%.2f`, with median coherence `%.3f`.", ...
    min(analysis.CpiCoherenceTable.CoherencePassFraction), ...
    median(analysis.CpiCoherenceTable.CoherenceMedian)); ...
    sprintf("- Blocking-finding count: `%d`", ...
    analysis.Interpretation.BlockingFindingCount); ...
    ""; ...
    "## Output Files"; ...
    "- `question_summaries.csv`"; ...
    "- `lag_table.csv`"; ...
    "- `residual_frequency_table.csv`"; ...
    "- `cpi_coherence_table.csv`"; ...
    "- `strategy_comparison_table.csv`"; ...
    "- `cpi_definitions.csv`"; ...
    "- `interpretation_summary.csv`"; ...
    "- `blocking_findings.csv` when nonempty"; ...
    "- `sync_interpretation_note.md`"; ...
    "- `config_snapshot.json`"; ...
    "- `metrics.json`"; ...
    "- `metrics.mat`"; ...
    "- `comparison_snapshot.mat`"; ...
    "- `figures/figure_01_lag_stability_overview.png`"; ...
    "- `figures/figure_02_residual_frequency_overview.png`"; ...
    "- `figures/figure_03_coherence_and_strategy_overview.png`" ...
    ];

end

function questionSummaryLines = localBuildQuestionSummaryLines( ...
    questionSummaries)

questionCount = height(questionSummaries);
questionSummaryLines = strings(questionCount, 1);

for idx = 1:questionCount
    questionSummaryLines(idx) = sprintf("- `%s` (`%s`): %s | metrics: %s", ...
        string(questionSummaries.QuestionId(idx)), ...
        string(questionSummaries.InterpretationLabel(idx)), ...
        string(questionSummaries.QuestionText(idx)), ...
        string(questionSummaries.SummaryMetrics(idx)));
end

end

function interpretationNoteLines = localBuildSyncInterpretationNoteLines( ...
    collectionMetadataInfo, analysis)

questionSummaries = analysis.QuestionSummaries;
recommendedRow = analysis.StrategyComparisonTable( ...
    analysis.StrategyComparisonTable.Recommended, :);

if analysis.Interpretation.OverallLabel == "ready"
    readinessLines = [ ...
        "- All four Stage 3 review questions remain analytically supported on the frozen baseline session."; ...
        "- The current sync-core evidence is suitable for downstream progression review, but it is still not a formal whole-gate G3 approval."; ...
        "- The recommended strategy candidate is simple enough to carry forward without reopening the Stage 2 role contract." ...
        ];
elseif analysis.Interpretation.OverallLabel == "caveated"
    readinessLines = [ ...
        "- At least one Stage 3 question remains caveated even though none are blocked."; ...
        "- Downstream review can continue under caveat, but the exported bundle should be treated as a manual-review evidence set rather than a final G3 gate decision."; ...
        "- Any later G4/G5 work should keep the current sync caveats visible in its assumptions and evidence bundle." ...
        ];
else
    readinessLines = [ ...
        "- At least one Stage 3 question is blocked on the baseline session."; ...
        "- The current sync-core evidence should not be treated as downstream-ready until the blocking findings are resolved or explicitly waived."; ...
        "- The exported bundle is still useful because it freezes which observable failed and why." ...
        ];
end

interpretationNoteLines = [ ...
    "# Sync Interpretation Note"; ...
    ""; ...
    sprintf("- Current overall label: `%s`", ...
    analysis.Interpretation.OverallLabel); ...
    sprintf("- Overall rationale: %s", ...
    analysis.Interpretation.OverallRationale); ...
    sprintf("- Reference label: `%s`", ...
    analysis.Interpretation.ReferenceLabel); ...
    sprintf("- Surveillance label: `%s`", ...
    analysis.Interpretation.SurveillanceLabel); ...
    sprintf("- Role mapping note: %s", ...
    analysis.Interpretation.RoleNote); ...
    sprintf("- Collection metadata path: `%s`", ...
    collectionMetadataInfo.MetadataPath); ...
    sprintf("- Recommended strategy candidate: `%s`", ...
    analysis.RecommendedStrategyCandidate); ...
    sprintf("- Recommended strategy rationale: %s", ...
    string(recommendedRow.Rationale(1))); ...
    ""; ...
    "## Question Assessments"; ...
    localBuildQuestionAssessmentLines(questionSummaries); ...
    ""; ...
    "## Blocking Findings"; ...
    localBuildBlockingFindingLines(analysis.BlockingFindings); ...
    ""; ...
    "## Reviewer Guidance"; ...
    readinessLines ...
    ];

end

function questionAssessmentLines = localBuildQuestionAssessmentLines( ...
    questionSummaries)

questionCount = height(questionSummaries);
questionAssessmentLines = strings(questionCount, 1);

for idx = 1:questionCount
    questionAssessmentLines(idx) = sprintf("- `%s` (`%s`): %s", ...
        string(questionSummaries.QuestionId(idx)), ...
        string(questionSummaries.InterpretationLabel(idx)), ...
        string(questionSummaries.Rationale(idx)));
end

end

function blockingFindingLines = localBuildBlockingFindingLines( ...
    blockingFindings)

if isempty(blockingFindings)
    blockingFindingLines = "- None.";
    return
end

blockingFindingLines = strings(numel(blockingFindings), 1);

for idx = 1:numel(blockingFindings)
    blockingFindingLines(idx) = sprintf("- `%s`", ...
        string(blockingFindings(idx)));
end

end

function joinedText = localJoinStringVector(inputVector)

inputVector = string(inputVector(:));
inputVector = strtrim(inputVector);
inputVector = inputVector(strlength(inputVector) > 0);

if isempty(inputVector)
    joinedText = "none";
    return
end

joinedText = strjoin(inputVector, " | ");

end

function localRenderLagOverviewFigure(analysis, figurePath, showFigures)

lagTable = analysis.LagTable;
cpiLabels = localExtractCpiLabels(analysis.Options);
colorMap = lines(numel(cpiLabels));
figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G3 Sync Core Lag Stability Overview", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
layoutHandle = tiledlayout(3, 1);

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(lagTable(lagTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.XcorrLagMedian_samples, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.LagWindowSpread_samples, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " spread";
end

hold off
grid on
xlabel("Repetition");
ylabel("Lag / Spread [samples]");
title("Lag Median and Spread by CPI");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(lagTable(lagTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.DelayEstimateAgreementFraction, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx);
end

if isfield(analysis.Options, "DelayAgreementReadyThreshold")
    legendHandles(end + 1, 1) = yline( ...
        analysis.Options.DelayAgreementReadyThreshold, "--", ...
        "LineWidth", 1.0);
    legendEntries(end + 1, 1) = "ready threshold";
end

if isfield(analysis.Options, "DelayAgreementBlockedThreshold")
    legendHandles(end + 1, 1) = yline( ...
        analysis.Options.DelayAgreementBlockedThreshold, ":", ...
        "LineWidth", 1.0);
    legendEntries(end + 1, 1) = "blocked threshold";
end

hold off
grid on
xlabel("Repetition");
ylabel("Agreement Fraction");
title("finddelay / xcorr Delay Agreement");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(lagTable(lagTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PeakToSidelobeMedian_dB, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PeakToSidelobeMin_dB, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " minimum";
end

legendHandles(end + 1, 1) = yline( ...
    analysis.Options.LagReadySharpnessThreshold_dB, "--", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "ready threshold";
legendHandles(end + 1, 1) = yline( ...
    analysis.Options.LagBlockedSharpnessThreshold_dB, ":", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "blocked threshold";
hold off
grid on
xlabel("Repetition");
ylabel("Peak-to-Sidelobe [dB]");
title("Correlation Peak Sharpness");
legend(legendHandles, cellstr(legendEntries), Location = "best");
drawnow

localExportGraphics(layoutHandle, figurePath);

clear cleanupObject

end

function localRenderResidualFrequencyFigure(analysis, figurePath, ...
    showFigures)

residualFrequencyTable = analysis.ResidualFrequencyTable;
cpiLabels = localExtractCpiLabels(analysis.Options);
colorMap = lines(numel(cpiLabels));
figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G3 Sync Core Residual Frequency Overview", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
layoutHandle = tiledlayout(3, 1);

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(residualFrequencyTable( ...
        residualFrequencyTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.ResidualFrequencyAbsMedian_Hz, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.ResidualFrequencyAbsMax_Hz, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " maximum";
end

hold off
grid on
xlabel("Repetition");
ylabel("Residual Frequency [Hz]");
title("Residual Frequency Magnitude");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(residualFrequencyTable( ...
        residualFrequencyTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PhaseExcursionMedian_deg, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PhaseExcursionMax_deg, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " maximum";
end

legendHandles(end + 1, 1) = yline( ...
    analysis.Options.PhaseExcursionReadyThreshold_deg, "--", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "ready threshold";
legendHandles(end + 1, 1) = yline( ...
    analysis.Options.PhaseExcursionBlockedThreshold_deg, ":", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "blocked threshold";
hold off
grid on
xlabel("Repetition");
ylabel("Phase Excursion [deg]");
title("Phase Excursion Across CPI");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(residualFrequencyTable( ...
        residualFrequencyTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PhaseFitRmseMedian_deg, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.PhaseFitRmseMax_deg, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " maximum";
end

legendHandles(end + 1, 1) = yline( ...
    analysis.Options.PhaseFitRmseReadyThreshold_deg, "--", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "ready threshold";
legendHandles(end + 1, 1) = yline( ...
    analysis.Options.PhaseFitRmseBlockedThreshold_deg, ":", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "blocked threshold";
hold off
grid on
xlabel("Repetition");
ylabel("Phase-Fit RMSE [deg]");
title("Phase-Fit RMSE");
legend(legendHandles, cellstr(legendEntries), Location = "best");
drawnow

localExportGraphics(layoutHandle, figurePath);

clear cleanupObject

end

function localRenderCoherenceStrategyFigure(analysis, figurePath, ...
    showFigures)

cpiCoherenceTable = analysis.CpiCoherenceTable;
strategyComparisonTable = analysis.StrategyComparisonTable;
cpiLabels = localExtractCpiLabels(analysis.Options);
colorMap = lines(numel(cpiLabels));
figureHandle = figure("Visible", ...
    localResolveFigureVisibility(showFigures), ...
    "Name", "G3 Sync Core Coherence and Strategy Overview", ...
    "NumberTitle", "off");
cleanupObject = localCreateFigureCleanup(figureHandle, showFigures); %#ok<NASGU>
layoutHandle = tiledlayout(2, 2);

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(cpiCoherenceTable( ...
        cpiCoherenceTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.CoherenceMedian, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " median";
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.CoherenceP10, "--", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx) + " p10";
end

legendHandles(end + 1, 1) = yline(analysis.Options.CoherencePassThreshold, ...
    "--", "LineWidth", 1.0);
legendEntries(end + 1, 1) = "pass threshold";
hold off
grid on
xlabel("Repetition");
ylabel("Band-Mean Coherence");
title("Coherence Median and P10");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
hold on
legendHandles = gobjects(0, 1);
legendEntries = strings(0, 1);

for idx = 1:numel(cpiLabels)
    subset = sortrows(cpiCoherenceTable( ...
        cpiCoherenceTable.CpiLabel == cpiLabels(idx), :), ...
        "Repetition");
    legendHandles(end + 1, 1) = plot(subset.Repetition, ...
        subset.CoherencePassFraction, "-o", "Color", ...
        colorMap(idx, :), "LineWidth", 1.2);
    legendEntries(end + 1, 1) = cpiLabels(idx);
end

legendHandles(end + 1, 1) = yline( ...
    analysis.Options.CoherenceReadyPassFractionThreshold, "--", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "ready threshold";
legendHandles(end + 1, 1) = yline( ...
    analysis.Options.CoherenceBlockedPassFractionThreshold, ":", ...
    "LineWidth", 1.0);
legendEntries(end + 1, 1) = "blocked threshold";
hold off
grid on
xlabel("Repetition");
ylabel("Pass Fraction");
title("Coherence Pass Fraction by CPI");
legend(legendHandles, cellstr(legendEntries), Location = "best");

nexttile(layoutHandle);
strategyDisplayLabels = localBuildStrategyDisplayLabels( ...
    strategyComparisonTable.StrategyCandidate);
barHandle = bar(strategyDisplayLabels, ...
    strategyComparisonTable.ObservablePassFraction, 0.6);
barHandle.FaceColor = "flat";
barHandle.CData = repmat([0.20 0.45 0.75], ...
    height(strategyComparisonTable), 1);
recommendedMask = strategyComparisonTable.Recommended;
barHandle.CData(recommendedMask, :) = repmat([0.85 0.33 0.10], ...
    nnz(recommendedMask), 1);
grid on
xlabel("Strategy Candidate");
ylabel("Observable Pass Fraction");
title("Strategy Pass Fraction");

nexttile(layoutHandle);
yyaxis left
bar(strategyDisplayLabels, strategyComparisonTable.LagResidualMedian_samples, ...
    0.45, FaceColor = [0.25 0.60 0.35]);
ylabel("Lag Residual Median [samples]");
yyaxis right
plot(strategyDisplayLabels, ...
    strategyComparisonTable.PhaseResidualMedian_deg, "-o", ...
    "Color", [0.80 0.25 0.25], "LineWidth", 1.4);
ylabel("Phase Residual Median [deg]");
grid on
xlabel("Strategy Candidate");
title("Strategy Residual Summary");
drawnow

localExportGraphics(layoutHandle, figurePath);

clear cleanupObject

end

function strategyDisplayLabels = localBuildStrategyDisplayLabels( ...
    strategyCandidates)

strategyCandidates = string(strategyCandidates(:));
strategyDisplayStrings = strings(numel(strategyCandidates), 1);

for idx = 1:numel(strategyCandidates)
    strategyDisplayStrings(idx) = strrep(strategyCandidates(idx), ...
        "_correction", "");
    strategyDisplayStrings(idx) = strrep(strategyDisplayStrings(idx), ...
        "_", " ");
end

strategyDisplayLabels = categorical(strategyDisplayStrings, ...
    cellstr(strategyDisplayStrings));

end

function cpiLabels = localExtractCpiLabels(optionsOutput)

cpiDefinitions = optionsOutput.CpiDefinitions;
cpiLabels = strings(numel(cpiDefinitions), 1);

for idx = 1:numel(cpiDefinitions)
    cpiLabels(idx) = string(cpiDefinitions(idx).Label);
end

end

function localExportGraphics(exportTarget, figurePath)

try
    exportgraphics(exportTarget, figurePath);
catch exportException
    error("runG3SyncCore:ExportFigureFailed", ...
        "Failed to export %s: %s", figurePath, ...
        exportException.message);
end

end

function visibility = localResolveFigureVisibility(showFigures)

if showFigures
    visibility = "on";
else
    visibility = "off";
end

end

function cleanupObject = localCreateFigureCleanup(figureHandle, showFigures)

if showFigures
    cleanupObject = [];
    return
end

cleanupObject = onCleanup(@() close(figureHandle));

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG3SyncCore:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

try
    fileIdentifier = fopen(filePath, "w");
catch openException
    error("runG3SyncCore:OpenTextFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        openException.message);
end

if fileIdentifier == -1
    error("runG3SyncCore:OpenTextFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileIdentifier));
lines = string(lines);

for idx = 1:numel(lines)
    fprintf(fileIdentifier, "%s\n", lines(idx));
end

clear cleanupObject

end

function localWriteJsonFile(filePath, inputStruct)

try
    jsonText = jsonencode(inputStruct, PrettyPrint = true);
catch encodeException
    error("runG3SyncCore:JsonEncodeFailed", ...
        "Failed to encode JSON for %s: %s", filePath, ...
        encodeException.message);
end

localWriteTextFile(filePath, jsonText);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return
end

if ~isfolder(bundleRoot)
    try
        mkdir(bundleRoot);
    catch
        return
    end
end

try
    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G3 Sync Core Summary"; ...
        ""; ...
        "- Stage status: `failed`"; ...
        sprintf("- Failure message: `%s`", mainException.message); ...
        "- See `failure_cause.txt` for the captured exception details." ...
        ]);
catch
end

stackLines = strings(numel(mainException.stack), 1);

for idx = 1:numel(mainException.stack)
    stackFrame = mainException.stack(idx);
    stackLines(idx) = sprintf("%s (line %d)", ...
        string(stackFrame.name), double(stackFrame.line));
end

if isempty(stackLines)
    stackLines = "none";
end

try
    localWriteTextFile(fullfile(bundleRoot, "failure_cause.txt"), [ ...
        "Stage: G3_Sync_Core"; ...
        sprintf("Identifier: %s", string(mainException.identifier)); ...
        sprintf("Message: %s", string(mainException.message)); ...
        "Stack:"; ...
        stackLines ...
        ]);
catch
end

end
