function result = runG4RCancellationCharacterization(repoRoot, options)
%RUNG4RCANCELLATIONCHARACTERIZATION Isolate the failed R5A cancellation path.
%
%   RESULT = RUNG4RCANCELLATIONCHARACTERIZATION(REPOROOT, OPTIONS) runs a
%   separate G4-R diagnostic over three fixed saved backgrounds. It compares
%   native-first cancellation with the historical independently reset
%   native/reduced NLMS behavior. This runner does not alter R5A evidence,
%   detector support, G5 selection, or formal G5/G6/G8 status.

arguments
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

repoRoot = helperResolveRepoRoot(repoRoot);
resolvedOptions = localResolveOptions(repoRoot, options);
runTimestampZ = string(datetime("now", TimeZone="UTC", ...
    Format="yyyyMMdd'T'HHmmssSSS'Z'"));
bundleRoot = localResolveBundleRoot(repoRoot, resolvedOptions, runTimestampZ);
totalTimer = tic;
manifest = localBuildManifest(resolvedOptions);

if resolvedOptions.SaveResult
    localEnsureFolder(bundleRoot);
end

try
    if resolvedOptions.ExecutionMode == "dry_run"
        result = localBuildDryRunResult( ...
            runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
            toc(totalTimer));
        localWriteResultBundle(result, resolvedOptions, false);
        return
    end

    selectionTimer = tic;
    shardBenchmark = localLoadShardBenchmarkContract(resolvedOptions);

    if resolvedOptions.ExecutionMode == "background_shard"
        selectionStage = localBuildShardSelectionStage(shardBenchmark, ...
            resolvedOptions);
    else
        selectionStage = localRunWienerSelectionStage( ...
            repoRoot, resolvedOptions, manifest);
    end

    selectionElapsed_s = toc(selectionTimer);

    if resolvedOptions.ExecutionMode == "background_shard"
        shard = localRunBackgroundShard( ...
            repoRoot, resolvedOptions.BackgroundId, selectionStage, ...
            resolvedOptions, manifest);
        result = localBuildResult( ...
            runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
            selectionStage, shard, localEmptyProjection(), ...
            toc(totalTimer));
        localWriteResultBundle(result, resolvedOptions, false);
        return
    end

    benchmarkBackgroundId = resolvedOptions.BackgroundIds(1);
    benchmarkTimer = tic;
    benchmarkShard = localRunBackgroundShard( ...
        repoRoot, benchmarkBackgroundId, selectionStage, ...
        resolvedOptions, manifest);
    benchmarkElapsed_s = toc(benchmarkTimer);
    projection = localBuildProjection( ...
        selectionElapsed_s, benchmarkElapsed_s, resolvedOptions);

    if resolvedOptions.ExecutionMode == "benchmark"
        result = localBuildResult( ...
            runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
            selectionStage, benchmarkShard, projection, toc(totalTimer));
        result.Outcome = "benchmark_completed_not_full_characterization";
        result.NextAction = localBenchmarkNextAction(projection);
        localWriteResultBundle(result, resolvedOptions, false);
        return
    end

    if ~projection.FitsAuthorizedBudget
        result = localBuildResult( ...
            runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
            selectionStage, benchmarkShard, projection, toc(totalTimer));
        result.Outcome = "full_study_not_launched_time_projection";
        result.NextAction = localBenchmarkNextAction(projection);
        localWriteResultBundle(result, resolvedOptions, false);
        return
    end

    if resolvedOptions.ExecutionMode == "auto"
        result = localBuildResult( ...
            runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
            selectionStage, benchmarkShard, projection, toc(totalTimer));
        result.Outcome = ...
            "benchmark_fit_requires_isolated_background_shards";
        result.DecisionRationale = ...
            "The measured projection fits the authorized budget, but the study contract requires three isolated background shards and an exact coordinator audit rather than serial execution.";
        result.NextAction = localBuildShardLaunchAction( ...
            bundleRoot, selectionStage.Selection);
        localWriteResultBundle(result, resolvedOptions, false);
        return
    end

catch runException
    localWriteFailure(bundleRoot, runException);
    rethrow(runException)
end

end

function resolvedOptions = localResolveOptions(repoRoot, options)

resolvedOptions = struct();
resolvedOptions.ExecutionMode = "benchmark";
resolvedOptions.BackgroundIds = [ ...
    "20260622T102123"; ...
    "20260827T135456"; ...
    "20260827T141524" ...
    ];
resolvedOptions.BackgroundId = "";
resolvedOptions.TimeBudget_s = 7200.0;
resolvedOptions.SafetyMarginFraction = 0.20;
resolvedOptions.SaveResult = true;
resolvedOptions.RunTargetGuard = true;
resolvedOptions.DecimationFactor = 200.0;
resolvedOptions.CpiDuration_s = 0.100;
resolvedOptions.FirTapCounts = [1.0 8.0 32.0 128.0 512.0];
resolvedOptions.WienerRegularizationFraction = 1.0e-3;
resolvedOptions.NlmsLength = 16.0;
resolvedOptions.NlmsStepSize = 0.02;
resolvedOptions.NlmsLeakageFactor = 1.0;
resolvedOptions.DelaySupport_s = [-1.2e-3 0.15e-3];
resolvedOptions.DopplerSupport_Hz = [-750.0 750.0];
resolvedOptions.NativeCutBatchSize = 16.0;
resolvedOptions.ReducedCutBatchSize = 32.0;
resolvedOptions.NativeDopplerSamplesPerCell = 2.0;
resolvedOptions.ProducerRoot = fullfile(fileparts(repoRoot), ...
    "flightTest_SynthDataBranch");
resolvedOptions.OutputRoot = fullfile(repoRoot, "artifacts", ...
    "20260622T102123", "G4_R_Cancellation_Characterization");
resolvedOptions.SelectedWienerTapCount = NaN;
resolvedOptions.BenchmarkResultPath = "";

optionNames = fieldnames(options);

for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    resolvedOptions.(optionName) = options.(optionName);
end

resolvedOptions.ExecutionMode = lower(string( ...
    resolvedOptions.ExecutionMode));
resolvedOptions.BackgroundIds = string(resolvedOptions.BackgroundIds(:));
resolvedOptions.BackgroundId = string(resolvedOptions.BackgroundId);
resolvedOptions.TimeBudget_s = double(resolvedOptions.TimeBudget_s);
resolvedOptions.SafetyMarginFraction = double( ...
    resolvedOptions.SafetyMarginFraction);
resolvedOptions.SaveResult = logical(resolvedOptions.SaveResult);
resolvedOptions.RunTargetGuard = logical(resolvedOptions.RunTargetGuard);
resolvedOptions.DecimationFactor = double( ...
    resolvedOptions.DecimationFactor);
resolvedOptions.CpiDuration_s = double(resolvedOptions.CpiDuration_s);
resolvedOptions.FirTapCounts = double(resolvedOptions.FirTapCounts(:).');
resolvedOptions.WienerRegularizationFraction = double( ...
    resolvedOptions.WienerRegularizationFraction);
resolvedOptions.NlmsLength = round(double(resolvedOptions.NlmsLength));
resolvedOptions.NlmsStepSize = double(resolvedOptions.NlmsStepSize);
resolvedOptions.NlmsLeakageFactor = double( ...
    resolvedOptions.NlmsLeakageFactor);
resolvedOptions.DelaySupport_s = double( ...
    resolvedOptions.DelaySupport_s(:).');
resolvedOptions.DopplerSupport_Hz = double( ...
    resolvedOptions.DopplerSupport_Hz(:).');
resolvedOptions.NativeCutBatchSize = round(double( ...
    resolvedOptions.NativeCutBatchSize));
resolvedOptions.ReducedCutBatchSize = round(double( ...
    resolvedOptions.ReducedCutBatchSize));
resolvedOptions.NativeDopplerSamplesPerCell = double( ...
    resolvedOptions.NativeDopplerSamplesPerCell);
resolvedOptions.ProducerRoot = string(resolvedOptions.ProducerRoot);
resolvedOptions.OutputRoot = string(resolvedOptions.OutputRoot);
resolvedOptions.SelectedWienerTapCount = double( ...
    resolvedOptions.SelectedWienerTapCount);
resolvedOptions.BenchmarkResultPath = string( ...
    resolvedOptions.BenchmarkResultPath);

if ~ismember(resolvedOptions.ExecutionMode, ...
        ["dry_run"; "benchmark"; "background_shard"; "auto"])
    error("runG4RCancellationCharacterization:ExecutionMode", ...
        "ExecutionMode must be dry_run, benchmark, background_shard, or auto.");
end

if resolvedOptions.ExecutionMode == "background_shard" && ...
        (strlength(resolvedOptions.BackgroundId) == 0 || ...
        ~ismember(resolvedOptions.BackgroundId, resolvedOptions.BackgroundIds))
    error("runG4RCancellationCharacterization:BackgroundShard", ...
        "background_shard mode requires a valid BackgroundId.");
end

if resolvedOptions.ExecutionMode == "background_shard" && ...
        strlength(resolvedOptions.BenchmarkResultPath) == 0
    error("runG4RCancellationCharacterization:ShardBenchmark", ...
        "background_shard mode requires a passing BenchmarkResultPath.");
end

if resolvedOptions.TimeBudget_s <= 0.0 || ...
        resolvedOptions.SafetyMarginFraction < 0.0 || ...
        resolvedOptions.SafetyMarginFraction >= 1.0
    error("runG4RCancellationCharacterization:TimeBudget", ...
        "TimeBudget_s must be positive and SafetyMarginFraction in [0, 1).");
end

if resolvedOptions.DecimationFactor ~= 200.0 || ...
        ~isequal(resolvedOptions.DelaySupport_s, [-1.2e-3 0.15e-3]) || ...
        ~isequal(resolvedOptions.DopplerSupport_Hz, [-750.0 750.0])
    error("runG4RCancellationCharacterization:MapContract", ...
        "The diagnostic must retain the passed R4 factor-200 map contract.");
end

if resolvedOptions.CpiDuration_s ~= 0.100 || ...
        ~isequal(resolvedOptions.FirTapCounts, [1.0 8.0 32.0 128.0 512.0])
    error("runG4RCancellationCharacterization:StudyContract", ...
        "G4-R cancellation characterization uses fixed 100 ms and FIR taps [1 8 32 128 512].");
end

end

function contract = localLoadShardBenchmarkContract(resolvedOptions)

contract = struct( ...
    "Available", false, ...
    "ResultPath", "", ...
    "WienerSelection", struct(), ...
    "WienerSelectionTable", table(), ...
    "WienerSearchDetailTable", table(), ...
    "Projection", struct());

if resolvedOptions.ExecutionMode ~= "background_shard"
    return
end

resultPath = resolvedOptions.BenchmarkResultPath;
localRequire(isfile(resultPath), ...
    "runG4RCancellationCharacterization:ShardBenchmark", ...
    "Benchmark result is missing: %s", resultPath);
loaded = load(resultPath, "result");
localRequire(isfield(loaded, "result"), ...
    "runG4RCancellationCharacterization:ShardBenchmark", ...
    "Benchmark file does not contain result: %s", resultPath);
benchmarkResult = loaded.result;
localRequire(isfield(benchmarkResult, "Projection") && ...
    isfield(benchmarkResult.Projection, "FitsAuthorizedBudget") && ...
    logical(benchmarkResult.Projection.FitsAuthorizedBudget), ...
    "runG4RCancellationCharacterization:ShardBudget", ...
    "Benchmark projection must fit the authorized budget before any shard launches.");
localRequire(isfield(benchmarkResult, "Manifest") && ...
    isfield(benchmarkResult.Manifest, "ExpectedControlCount") && ...
    double(benchmarkResult.Manifest.ExpectedControlCount) == 9.0, ...
    "runG4RCancellationCharacterization:ShardManifest", ...
    "Benchmark result does not contain the required nine-control manifest.");
localRequire(isfield(benchmarkResult, "WienerSelection") && ...
    isfield(benchmarkResult, "WienerSelectionTable") && ...
    isfield(benchmarkResult, "WienerSearchDetailTable"), ...
    "runG4RCancellationCharacterization:ShardSelection", ...
    "Benchmark result does not contain the global Wiener selection.");

contract.Available = true;
contract.ResultPath = resultPath;
contract.WienerSelection = benchmarkResult.WienerSelection;
contract.WienerSelectionTable = benchmarkResult.WienerSelectionTable;
contract.WienerSearchDetailTable = benchmarkResult.WienerSearchDetailTable;
contract.Projection = benchmarkResult.Projection;

end

function selectionStage = localBuildShardSelectionStage( ...
        contract, resolvedOptions)

localRequire(contract.Available, ...
    "runG4RCancellationCharacterization:ShardBenchmark", ...
    "A validated benchmark contract is required for a background shard.");

if isfinite(resolvedOptions.SelectedWienerTapCount)
    localRequire(logical(contract.WienerSelection.Nominated) && ...
        resolvedOptions.SelectedWienerTapCount == ...
        contract.WienerSelection.SelectedTapCount, ...
        "runG4RCancellationCharacterization:ShardTap", ...
        "SelectedWienerTapCount must match the passing benchmark contract.");
end

selectionStage = struct();
selectionStage.DetailTable = contract.WienerSearchDetailTable;
selectionStage.WienerSelectionTable = contract.WienerSelectionTable;
selectionStage.Selection = contract.WienerSelection;
selectionStage.BenchmarkResultPath = contract.ResultPath;
selectionStage.BenchmarkProjection = contract.Projection;

end

function bundleRoot = localResolveBundleRoot(repoRoot, resolvedOptions, ...
        runTimestampZ)

if resolvedOptions.ExecutionMode == "background_shard"
    bundleRoot = fullfile(repoRoot, "artifacts", "20260622T102123", ...
        "G4_R_Cancellation_Characterization", "shards", ...
        runTimestampZ + "_" + resolvedOptions.BackgroundId);
else
    bundleRoot = fullfile(resolvedOptions.OutputRoot, runTimestampZ);
end

end

function manifest = localBuildManifest(resolvedOptions)

pairIds = ["1_to_2"; "4_to_5"; "9_to_10"];
calibrationRepetition = [1.0; 4.0; 9.0];
scoreRepetition = [2.0; 5.0; 10.0];
pairPosition = ["early"; "center"; "late"];
rows = repmat(struct( ...
    "BackgroundId", "", ...
    "TimePairId", "", ...
    "PairPosition", "", ...
    "CalibrationRepetition", NaN, ...
    "ScoreRepetition", NaN, ...
    "CalibrationTargetFree", false, ...
    "CpiDuration_s", NaN), ...
    numel(resolvedOptions.BackgroundIds) .* numel(pairIds), 1);
rowIndex = 0;

for backgroundIndex = 1:numel(resolvedOptions.BackgroundIds)
    for pairIndex = 1:numel(pairIds)
        rowIndex = rowIndex + 1;
        rows(rowIndex) = struct( ...
            "BackgroundId", resolvedOptions.BackgroundIds(backgroundIndex), ...
            "TimePairId", pairIds(pairIndex), ...
            "PairPosition", pairPosition(pairIndex), ...
            "CalibrationRepetition", calibrationRepetition(pairIndex), ...
            "ScoreRepetition", scoreRepetition(pairIndex), ...
            "CalibrationTargetFree", true, ...
            "CpiDuration_s", resolvedOptions.CpiDuration_s);
    end
end

manifest = struct();
manifest.ControlTable = struct2table(rows);
manifest.ExpectedControlCount = double(height(manifest.ControlTable));
manifest.TimePairContract = ...
    "nonoverlapping_adjacent_100ms_calibration_to_score_pairs";
manifest.MapMethods = [ ...
    "none"; "wiener_fir"; "current_reset_nlms"; "frozen_native_nlms" ...
    ];
manifest.TargetGuardBackgroundId = "20260622T102123";
manifest.TargetGuardTimePairId = "4_to_5";

end

function result = localBuildDryRunResult( ...
        runTimestampZ, bundleRoot, resolvedOptions, manifest, totalElapsed_s)

result = localEmptyResult();
result.SchemaVersion = "g4r_cancellation_characterization_v1";
result.StageId = "G4_R_Cancellation_Characterization";
result.AnalysisTimestampZ = runTimestampZ;
result.BundleRoot = string(bundleRoot);
result.ExecutionMode = resolvedOptions.ExecutionMode;
result.Configuration = localConfiguration(resolvedOptions);
result.Manifest = manifest;
result.Outcome = "dry_run_passed_not_evidence";
result.MapRateValidityStatus = "retune_pending_bounded_correction";
result.CollectionSuitabilityStatus = ...
    "blocked_pending_reviewed_adsb_timing_geometry_policy";
result.FormalG5Enabled = false;
result.FormalG6Enabled = false;
result.FormalG8Enabled = false;
result.NextAction = "Run a one-background benchmark before launching isolated background shards.";
result.DecisionRationale = ...
    "Dry run validated the fixed study contract without reading IQ.";
result.TotalElapsed_s = totalElapsed_s;
result.CompactResultAudit = localCompactAudit(result);

end

function selectionStage = localRunWienerSelectionStage( ...
        repoRoot, resolvedOptions, manifest)

backgroundIds = resolvedOptions.BackgroundIds;

if resolvedOptions.ExecutionMode == "background_shard"
    backgroundIds = resolvedOptions.BackgroundId;
end

details = table();
hardwareEvidence = table();
sourceFingerprints = table();
backgroundContracts = table();

for backgroundIndex = 1:numel(backgroundIds)
    background = localPrepareBackground( ...
        repoRoot, backgroundIds(backgroundIndex), resolvedOptions);
    selection = localEvaluateWienerCandidates( ...
        background, manifest, resolvedOptions);
    details = [details; selection.DetailTable]; %#ok<AGROW>
    hardwareEvidence = [hardwareEvidence; ...
        background.HardwareEvidenceTable]; %#ok<AGROW>
    sourceFingerprints = [sourceFingerprints; ...
        background.SourceFingerprintTable]; %#ok<AGROW>
    backgroundContracts = [backgroundContracts; ...
        background.BackgroundContractTable]; %#ok<AGROW>
end

selectionStage = struct();
selectionStage.DetailTable = details;
selectionStage.WienerSelectionTable = localSummarizeWienerSelection( ...
    details, resolvedOptions);
selectionStage.Selection = localSelectWienerTap( ...
    selectionStage.WienerSelectionTable);
selectionStage.HardwareEvidenceTable = hardwareEvidence;
selectionStage.SourceFingerprintTable = sourceFingerprints;
selectionStage.BackgroundContractTable = backgroundContracts;

if isfinite(resolvedOptions.SelectedWienerTapCount)
    localRequire(ismember(resolvedOptions.SelectedWienerTapCount, ...
        resolvedOptions.FirTapCounts), ...
        "runG4RCancellationCharacterization:SelectedTap", ...
        "SelectedWienerTapCount must be one fixed study tap count.");
    selectionStage.Selection.SelectedTapCount = ...
        resolvedOptions.SelectedWienerTapCount;
    selectionStage.Selection.Nominated = true;
    selectionStage.Selection.SelectionReason = ...
        "externally_supplied_fixed_tap_for_isolated_background_shard";
end

end

function background = localPrepareBackground( ...
        repoRoot, backgroundId, ~)

sessionData = loadIQData(backgroundId, repoRoot, ...
    struct(IncludeSamples=false));
metadataPath = fullfile(sessionData.DatasetRoot, ...
    "collection_metadata.json");
collectionMetadataInfo = helperReadCollectionMetadata( ...
    metadataPath, backgroundId);

if backgroundId == "20260622T102123"
    [g3Cache, cacheStatus] = helperResolveG4RG3Cache( ...
        sessionData, collectionMetadataInfo, repoRoot, ...
        struct("ForceRebuild", false));
    localRequire(cacheStatus.Action == "loaded_validated", ...
        "runG4RCancellationCharacterization:G3Cache", ...
        "The reference background must use the validated R3 G3 cache.");
    syncPrep = g3Cache.SyncPrep;
    sourceFingerprintTable = g3Cache.SourceFingerprint.FileRows;
    sourceFingerprintTable = addvars(sourceFingerprintTable, ...
        repmat(backgroundId, height(sourceFingerprintTable), 1), ...
        Before=1, NewVariableNames="BackgroundId");
    correctionSource = "validated_r3_g3_cache";
else
    g3Options = localBuildG3Options(sessionData);
    g3Results = helperAnalyzeG3SyncCore( ...
        sessionData, collectionMetadataInfo, g3Options);
    syncPrep = helperPrepareG3SyncInputs( ...
        sessionData, collectionMetadataInfo, g3Options, g3Results);
    sourceFingerprintTable = localBuildSelectedSourceFingerprints( ...
        sessionData, metadataPath, backgroundId);
    correctionSource = "g3_recomputed_for_saved_background";
end

metadata = jsondecode(fileread(metadataPath));
hardwareEvidence = localBuildHardwareEvidence( ...
    backgroundId, metadata, metadataPath);
configurationFingerprint = helperG4RSha256( ...
    jsonencode(metadata), InputType="text");
backgroundContract = table( ...
    backgroundId, string(sessionData.DatasetRoot), ...
    configurationFingerprint, correctionSource, ...
    "single_configuration_not_compared", ...
    "not_established_from_this_study", ...
    VariableNames=["BackgroundId", "DatasetRoot", ...
    "ConfigurationFingerprint", "CorrectionSource", ...
    "HardwareConfigurationStatus", "HardwareSufficiencyStatus"]);

background = struct();
background.BackgroundId = backgroundId;
background.SessionData = sessionData;
background.SyncPrep = syncPrep;
background.MetadataPath = string(metadataPath);
background.HardwareEvidenceTable = hardwareEvidence;
background.SourceFingerprintTable = sourceFingerprintTable;
background.BackgroundContractTable = backgroundContract;

end

function g3Options = localBuildG3Options(sessionData)

g3Options = struct();
g3Options.DataProfile = "field_capture";
g3Options.ReferenceChannelIndex = 2.0;
g3Options.SurveillanceChannelIndex = 1.0;
g3Options.ExpectedDatasetId = string(sessionData.DatasetId);
g3Options.ExpectedReferenceLabel = string(sessionData.RadarTable.Antenna2(1));
g3Options.ExpectedSurveillanceLabel = ...
    string(sessionData.RadarTable.Antenna1(1));
g3Options.ExpectedRepetitionCount = double(height(sessionData.RadarTable));

end

function sourceTable = localBuildSelectedSourceFingerprints( ...
        sessionData, metadataPath, backgroundId)

selectedRepetitions = [1.0; 2.0; 4.0; 5.0; 9.0; 10.0];
rowCount = numel(selectedRepetitions) + 2;
paths = strings(rowCount, 1);
categories = strings(rowCount, 1);
paths(1:2) = [string(sessionData.ManifestPath); string(metadataPath)];
categories(1:2) = ["session_manifest"; "collection_metadata"];

for repetitionIndex = 1:numel(selectedRepetitions)
    repetition = selectedRepetitions(repetitionIndex);
    outputIndex = repetitionIndex + 2;
    paths(outputIndex) = fullfile(sessionData.DatasetRoot, strrep( ...
        sessionData.RadarTable.RelativePath(repetition), "/", filesep));
    categories(outputIndex) = "iq_source_selected_pair";
end

bytes = zeros(rowCount, 1);
modifiedDatenum = zeros(rowCount, 1);
sha256 = strings(rowCount, 1);

for rowIndex = 1:rowCount
    localRequire(isfile(paths(rowIndex)), ...
        "runG4RCancellationCharacterization:FingerprintSource", ...
        "Fingerprint source is missing: %s", paths(rowIndex));
    fileInfo = dir(paths(rowIndex));
    bytes(rowIndex) = double(fileInfo.bytes);
    modifiedDatenum(rowIndex) = double(fileInfo.datenum);
    sha256(rowIndex) = helperG4RSha256(paths(rowIndex));
end

sourceTable = table( ...
    repmat(backgroundId, rowCount, 1), categories, paths, bytes, ...
    modifiedDatenum, sha256, ...
    VariableNames=["BackgroundId", "Category", "Path", "Bytes", ...
    "ModifiedDatenum", "Sha256"]);

end

function evidenceTable = localBuildHardwareEvidence( ...
        backgroundId, metadata, metadataPath)

paths = [ ...
    "channel_assignments.reference_channel.channel_label"; ...
    "channel_assignments.reference_channel.antenna_name"; ...
    "channel_assignments.reference_channel.antenna_type"; ...
    "channel_assignments.surveillance_channel.channel_label"; ...
    "channel_assignments.surveillance_channel.antenna_name"; ...
    "channel_assignments.surveillance_channel.antenna_type"; ...
    "acquisition_controls.gain_mapping_note"; ...
    "acquisition_controls.gain_mode_note"; ...
    "acquisition_controls.lock_status_note"; ...
    "acquisition_controls.overrun_note"; ...
    "acquisition_controls.channel_mapping_verification_note" ...
    ];
categories = [ ...
    "channel"; "antenna"; "antenna"; "channel"; "antenna"; "antenna"; ...
    "gain"; "gain"; "lock"; "overrun"; "channel_mapping" ...
    ];
rowCount = numel(paths);
recordedValue = strings(rowCount, 1);
evidenceStatus = strings(rowCount, 1);

for rowIndex = 1:rowCount
    recordedValue(rowIndex) = localReadMetadataPath(metadata, paths(rowIndex));

    if strlength(strtrim(recordedValue(rowIndex))) == 0
        evidenceStatus(rowIndex) = "missing_not_inferred";
    else
        evidenceStatus(rowIndex) = "recorded";
    end
end

evidenceTable = table( ...
    repmat(backgroundId, rowCount, 1), categories, paths, recordedValue, ...
    evidenceStatus, repmat(string(metadataPath), rowCount, 1), ...
    repmat("single_configuration_not_compared", rowCount, 1), ...
    repmat("not_established_from_this_study", rowCount, 1), ...
    VariableNames=["BackgroundId", "EvidenceCategory", "MetadataField", ...
    "RecordedValue", "EvidenceStatus", "MetadataPath", ...
    "HardwareConfigurationStatus", "HardwareSufficiencyStatus"]);

end

function value = localReadMetadataPath(metadata, dottedPath)

value = "";
pathParts = split(string(dottedPath), ".");
current = metadata;

for partIndex = 1:numel(pathParts)
    fieldName = char(pathParts(partIndex));

    if ~isstruct(current) || ~isfield(current, fieldName)
        return
    end

    current = current.(fieldName);
end

if ischar(current) || isstring(current)
    value = string(current);
elseif isnumeric(current) || islogical(current)
    value = string(current);
else
    value = string(jsonencode(current));
end

end

function selection = localEvaluateWienerCandidates( ...
        background, manifest, resolvedOptions)

backgroundRows = manifest.ControlTable( ...
    manifest.ControlTable.BackgroundId == background.BackgroundId, :);
rows = table();

for pairIndex = 1:height(backgroundRows)
    pairRow = backgroundRows(pairIndex, :);
    calibration = localLoadCorrectedRepetition( ...
        background, pairRow.CalibrationRepetition);
    score = localLoadCorrectedRepetition( ...
        background, pairRow.ScoreRepetition);
    calibrationWindow = localCenterWindow( ...
        calibration.Reference, calibration.Surveillance, ...
        calibration.SampleRateHz, resolvedOptions.CpiDuration_s);
    scoreWindow = localCenterWindow( ...
        score.Reference, score.Surveillance, score.SampleRateHz, ...
        resolvedOptions.CpiDuration_s);

    for tapIndex = 1:numel(resolvedOptions.FirTapCounts)
        tapCount = resolvedOptions.FirTapCounts(tapIndex);
        estimate = helperEstimateG4RWienerFir( ...
            calibrationWindow.Reference, calibrationWindow.Surveillance, ...
            tapCount, struct("RegularizationFraction", ...
            resolvedOptions.WienerRegularizationFraction));
        application = helperApplyG4RNativeFirstCancellation( ...
            calibrationWindow.Reference, calibrationWindow.Surveillance, ...
            scoreWindow.Reference, scoreWindow.Surveillance, "wiener_fir", ...
            struct("WienerCoefficients", estimate.Coefficients));
        metrics = helperComputeG4RCancellationMetrics( ...
            scoreWindow.Reference, scoreWindow.Surveillance, ...
            application.ResidualSignal);
        impulse = localImpulseMetrics( ...
            estimate.Coefficients, score.SampleRateHz);
        row = table( ...
            background.BackgroundId, pairRow.TimePairId, ...
            pairRow.PairPosition, pairRow.CalibrationRepetition, ...
            pairRow.ScoreRepetition, tapCount, ...
            impulse.FirSpan_us, impulse.EnergyCentroidDelay_us, ...
            impulse.Energy95Delay_us, estimate.Regularization, ...
            estimate.RegularizedMatrixConditionNumber, ...
            metrics.InputSurveillancePower_dB, metrics.ResidualPower_dB, ...
            metrics.CancellationDepth_dB, ...
            metrics.ResidualCoherenceSquared, ...
            VariableNames=["BackgroundId", "TimePairId", "PairPosition", ...
            "CalibrationRepetition", "ScoreRepetition", "TapCount", ...
            "FirSpan_us", "ImpulseEnergyCentroidDelay_us", ...
            "ImpulseEnergy95Delay_us", "Regularization", ...
            "RegularizedMatrixConditionNumber", ...
            "InputSurveillancePower_dB", "ResidualPower_dB", ...
            "CancellationDepth_dB", "ResidualCoherenceSquared"]);
        rows = [rows; row]; %#ok<AGROW>
    end
end

selection = struct();
selection.DetailTable = rows;

end

function impulse = localImpulseMetrics(coefficients, sampleRateHz)

energy = abs(double(coefficients(:))) .^ 2;
energy = energy ./ max(sum(energy), eps);
delay_us = (0:numel(coefficients) - 1).' ./ sampleRateHz .* 1.0e6;
first95Index = find(cumsum(energy) >= 0.95, 1, "first");

impulse = struct();
impulse.FirSpan_us = delay_us(end);
impulse.EnergyCentroidDelay_us = sum(delay_us .* energy);
impulse.Energy95Delay_us = delay_us(first95Index);

end

function summaryTable = localSummarizeWienerSelection( ...
        detailTable, resolvedOptions)

rows = repmat(struct( ...
    "TapCount", NaN, ...
    "FirSpan_us", NaN, ...
    "ImpulseEnergyCentroidDelay_us", NaN, ...
    "ImpulseEnergy95Delay_us", NaN, ...
    "MedianHeldOutCancellationDepth_dB", NaN, ...
    "MinimumHeldOutCancellationDepth_dB", NaN, ...
    "AllControlsNonnegativeCancellation", false, ...
    "WithinOneDbOfBestMedian", false, ...
    "Nominated", false), numel(resolvedOptions.FirTapCounts), 1);

for tapIndex = 1:numel(resolvedOptions.FirTapCounts)
    tapCount = resolvedOptions.FirTapCounts(tapIndex);
    subset = detailTable(detailTable.TapCount == tapCount, :);
    medianCancellation = median(subset.CancellationDepth_dB);
    minimumCancellation = min(subset.CancellationDepth_dB);
    rows(tapIndex) = struct( ...
        "TapCount", tapCount, ...
        "FirSpan_us", median(subset.FirSpan_us), ...
        "ImpulseEnergyCentroidDelay_us", ...
        median(subset.ImpulseEnergyCentroidDelay_us), ...
        "ImpulseEnergy95Delay_us", ...
        median(subset.ImpulseEnergy95Delay_us), ...
        "MedianHeldOutCancellationDepth_dB", medianCancellation, ...
        "MinimumHeldOutCancellationDepth_dB", minimumCancellation, ...
        "AllControlsNonnegativeCancellation", minimumCancellation >= 0.0, ...
        "WithinOneDbOfBestMedian", false, ...
        "Nominated", false);
end

summaryTable = struct2table(rows);
bestMedian = max(summaryTable.MedianHeldOutCancellationDepth_dB);
summaryTable.WithinOneDbOfBestMedian = ...
    summaryTable.MedianHeldOutCancellationDepth_dB >= bestMedian - 1.0;
eligible = summaryTable.AllControlsNonnegativeCancellation & ...
    summaryTable.WithinOneDbOfBestMedian;

if any(eligible)
    smallestTap = min(summaryTable.TapCount(eligible));
    summaryTable.Nominated(summaryTable.TapCount == smallestTap) = true;
end

end

function selection = localSelectWienerTap(summaryTable)

nominatedRows = summaryTable(summaryTable.Nominated, :);
selection = struct();
selection.Nominated = height(nominatedRows) == 1;
selection.SelectedTapCount = NaN;
selection.SelectionReason = ...
    "no_fixed_fir_within_one_db_and_nonnegative_every_control";

if selection.Nominated
    selection.SelectedTapCount = nominatedRows.TapCount(1);
    selection.SelectionReason = ...
        "smallest_fir_within_one_db_of_best_median_and_nonnegative_every_control";
end

end

function shard = localRunBackgroundShard( ...
        repoRoot, backgroundId, selectionStage, resolvedOptions, manifest)

background = localPrepareBackground(repoRoot, backgroundId, resolvedOptions);
backgroundRows = manifest.ControlTable( ...
    manifest.ControlTable.BackgroundId == backgroundId, :);
methodMetrics = table();
mapMetrics = table();
wienerCoefficients = repmat(localCoefficientRecordTemplate(), 0, 1);

for pairIndex = 1:height(backgroundRows)
    pairRow = backgroundRows(pairIndex, :);
    calibration = localLoadCorrectedRepetition( ...
        background, pairRow.CalibrationRepetition);
    score = localLoadCorrectedRepetition( ...
        background, pairRow.ScoreRepetition);
    scoreProducts = localBuildScoreProducts( ...
        calibration, score, pairRow, selectionStage.Selection, ...
        resolvedOptions);
    methodMetrics = [methodMetrics; scoreProducts.HeldOutMetricTable]; %#ok<AGROW>
    mapMetrics = [mapMetrics; scoreProducts.MapRateMetricTable]; %#ok<AGROW>
    wienerCoefficients = [wienerCoefficients; ...
        scoreProducts.WienerCoefficientRecords]; %#ok<AGROW>
end

targetGuard = table();

if resolvedOptions.RunTargetGuard && ...
        backgroundId == manifest.TargetGuardBackgroundId
    targetGuard = localRunTargetGuard( ...
        repoRoot, background, selectionStage.Selection, resolvedOptions, ...
        manifest);
end

shard = struct();
shard.BackgroundId = backgroundId;
shard.HeldOutMetricTable = methodMetrics;
shard.MapRateMetricTable = mapMetrics;
shard.TargetGuardTable = targetGuard;
shard.WienerCoefficientRecords = wienerCoefficients;
shard.HardwareEvidenceTable = background.HardwareEvidenceTable;
shard.SourceFingerprintTable = background.SourceFingerprintTable;
shard.BackgroundContractTable = background.BackgroundContractTable;
shard.ShardStatus = "completed_compact_background_result";

end

function products = localBuildScoreProducts( ...
        calibration, score, pairRow, selection, resolvedOptions)

calibrationWindow = localCenterWindow( ...
    calibration.Reference, calibration.Surveillance, ...
    calibration.SampleRateHz, resolvedOptions.CpiDuration_s);
scoreWindow = localCenterWindow( ...
    score.Reference, score.Surveillance, score.SampleRateHz, ...
    resolvedOptions.CpiDuration_s);
scoreDomain = localBuildR4Domain( ...
    score.Reference, score.Surveillance, ...
    resolvedOptions.DecimationFactor);
alignment = helperMeasureG4RCpiAlignment( ...
    scoreWindow.StartSample, scoreWindow.SampleCount, ...
    score.SampleRateHz, resolvedOptions.DecimationFactor);
reducedStart = alignment.ReducedWindowStartSample(1);
reducedStop = reducedStart + alignment.ReducedSampleCount(1) - 1.0;

methodNames = ["none"; "current_reset_nlms"; "frozen_native_nlms"];

if selection.Nominated
    methodNames = [methodNames; "wiener_fir"];
end

heldOutRows = table();
mapRows = table();
coefficientRecords = repmat(localCoefficientRecordTemplate(), 0, 1);

for methodIndex = 1:numel(methodNames)
    method = methodNames(methodIndex);
    [methodProduct, coefficientRecord] = localApplyStudyMethod( ...
        method, calibrationWindow, score, scoreWindow, scoreDomain, ...
        reducedStart, reducedStop, selection, resolvedOptions);
    heldOutRows = [heldOutRows; localBuildHeldOutMetricRows( ...
        pairRow, methodProduct, method, score.SampleRateHz, ...
        resolvedOptions.DecimationFactor)]; %#ok<AGROW>
    mapRows = [mapRows; localEvaluateMapRate( ...
        pairRow, method, methodProduct, score.SampleRateHz, ...
        resolvedOptions)]; %#ok<AGROW>

    if ~isempty(coefficientRecord)
        coefficientRecord.BackgroundId = string(pairRow.BackgroundId);
        coefficientRecord.TimePairId = string(pairRow.TimePairId);
        coefficientRecord.CalibrationRepetition = ...
            double(pairRow.CalibrationRepetition);
        coefficientRecord.ScoreRepetition = double(pairRow.ScoreRepetition);
        coefficientRecords(end + 1, 1) = coefficientRecord; %#ok<AGROW>
    end
end

products = struct();
products.HeldOutMetricTable = heldOutRows;
products.MapRateMetricTable = mapRows;
products.WienerCoefficientRecords = coefficientRecords;

end

function domain = localBuildR4Domain( ...
        referenceFull, surveillanceFull, decimationFactor)

[referenceReduced, filterCoefficients] = helperResampleG4FullRepetition( ...
    referenceFull, decimationFactor);
surveillanceReduced = helperResampleG4FullRepetition( ...
    surveillanceFull, decimationFactor);
referenceReconstruction = helperReconstructG4Resample( ...
    referenceFull, decimationFactor, filterCoefficients);
surveillanceReconstruction = helperReconstructG4Resample( ...
    surveillanceFull, decimationFactor, filterCoefficients);

domain = struct();
domain.ReferenceReduced = double(referenceReduced(:));
domain.SurveillanceReduced = double(surveillanceReduced(:));
domain.FilteredNativeReference = double( ...
    referenceReconstruction.FilteredNativeOutput(:));
domain.FilteredNativeSurveillance = double( ...
    surveillanceReconstruction.FilteredNativeOutput(:));
domain.FilterCoefficients = filterCoefficients(:);

end

function [product, coefficientRecord] = localApplyStudyMethod( ...
        method, calibrationWindow, score, scoreWindow, scoreDomain, ...
        reducedStart, reducedStop, selection, resolvedOptions)

nativeReference = scoreDomain.FilteredNativeReference( ...
    scoreWindow.StartSample:scoreWindow.StopSample);
reducedReference = scoreDomain.ReferenceReduced(reducedStart:reducedStop);
coefficientRecord = repmat(localCoefficientRecordTemplate(), 0, 1);

switch method
    case "none"
        nativeResidual = scoreDomain.FilteredNativeSurveillance( ...
            scoreWindow.StartSample:scoreWindow.StopSample);
        reducedResidual = scoreDomain.SurveillanceReduced( ...
            reducedStart:reducedStop);
        nativeInfo = localNoneInfo();
        reducedInfo = localNoneInfo();
        nativeInput = nativeResidual;
        reducedInput = reducedResidual;
        filterOrder = "r4_filter_then_no_cancellation";
    case "current_reset_nlms"
        nativeInput = scoreDomain.FilteredNativeSurveillance( ...
            scoreWindow.StartSample:scoreWindow.StopSample);
        reducedInput = scoreDomain.SurveillanceReduced( ...
            reducedStart:reducedStop);
        nativeInfo = localApplyResetNlms( ...
            nativeReference, nativeInput, resolvedOptions);
        reducedInfo = localApplyResetNlms( ...
            reducedReference, reducedInput, resolvedOptions);
        nativeResidual = nativeInfo.ResidualSignal;
        reducedResidual = reducedInfo.ResidualSignal;
        filterOrder = "r4_filter_then_independent_reset_nlms_at_each_rate";
    case "frozen_native_nlms"
        nativeInfo = helperApplyG4RNativeFirstCancellation( ...
            calibrationWindow.Reference, calibrationWindow.Surveillance, ...
            score.Reference, score.Surveillance, "frozen_nlms", ...
            localNativeFirstOptions(resolvedOptions));
        [nativeResidual, reducedResidual] = localResampleNativeResidual( ...
            nativeInfo.ResidualSignal, scoreWindow, reducedStart, ...
            reducedStop, scoreDomain.FilterCoefficients, ...
            resolvedOptions.DecimationFactor);
        nativeInput = scoreDomain.FilteredNativeSurveillance( ...
            scoreWindow.StartSample:scoreWindow.StopSample);
        reducedInput = scoreDomain.SurveillanceReduced( ...
            reducedStart:reducedStop);
        reducedInfo = nativeInfo;
        filterOrder = "native_nlms_calibration_then_frozen_score_then_r4_resample";
    case "wiener_fir"
        estimate = helperEstimateG4RWienerFir( ...
            calibrationWindow.Reference, calibrationWindow.Surveillance, ...
            selection.SelectedTapCount, ...
            struct("RegularizationFraction", ...
            resolvedOptions.WienerRegularizationFraction));
        nativeInfo = helperApplyG4RNativeFirstCancellation( ...
            calibrationWindow.Reference, calibrationWindow.Surveillance, ...
            score.Reference, score.Surveillance, "wiener_fir", ...
            struct("WienerCoefficients", estimate.Coefficients));
        [nativeResidual, reducedResidual] = localResampleNativeResidual( ...
            nativeInfo.ResidualSignal, scoreWindow, reducedStart, ...
            reducedStop, scoreDomain.FilterCoefficients, ...
            resolvedOptions.DecimationFactor);
        nativeInput = scoreDomain.FilteredNativeSurveillance( ...
            scoreWindow.StartSample:scoreWindow.StopSample);
        reducedInput = scoreDomain.SurveillanceReduced( ...
            reducedStart:reducedStop);
        reducedInfo = nativeInfo;
        filterOrder = "native_wiener_fir_then_r4_resample";
        coefficientRecord = localCoefficientRecord( ...
            selection.SelectedTapCount, estimate);
    otherwise
        error("runG4RCancellationCharacterization:Method", ...
            "Unexpected study method %s.", method);
end

product = struct();
product.NativeReference = nativeReference;
product.NativeInput = nativeInput;
product.NativeResidual = nativeResidual;
product.ReducedReference = reducedReference;
product.ReducedInput = reducedInput;
product.ReducedResidual = reducedResidual;
product.NativeInfo = nativeInfo;
product.ReducedInfo = reducedInfo;
product.FilterOrder = filterOrder;
product.NativeWindowStartSample = scoreWindow.StartSample;
product.ReducedWindowStartSample = reducedStart;

end

function options = localNativeFirstOptions(resolvedOptions)

options = struct( ...
    "NlmsLength", resolvedOptions.NlmsLength, ...
    "NlmsStepSize", resolvedOptions.NlmsStepSize, ...
    "NlmsLeakageFactor", resolvedOptions.NlmsLeakageFactor);

end

function [nativeWindowResidual, reducedWindowResidual] = ...
        localResampleNativeResidual( ...
        residualFull, scoreWindow, reducedStart, reducedStop, ...
        filterCoefficients, decimationFactor)

residualReduced = helperResampleG4FullRepetition( ...
    residualFull, decimationFactor);
residualReconstruction = helperReconstructG4Resample( ...
    residualFull, decimationFactor, filterCoefficients);
nativeWindowResidual = double(residualReconstruction.FilteredNativeOutput( ...
    scoreWindow.StartSample:scoreWindow.StopSample));
reducedWindowResidual = double(residualReduced( ...
    reducedStart:reducedStop));

end

function info = localApplyResetNlms( ...
        referenceSignal, surveillanceSignal, resolvedOptions)

lmsFilter = dsp.LMSFilter( ...
    "Method", "Normalized LMS", ...
    "Length", resolvedOptions.NlmsLength, ...
    "StepSize", resolvedOptions.NlmsStepSize, ...
    "LeakageFactor", resolvedOptions.NlmsLeakageFactor, ...
    "WeightsOutputPort", true);
[modeledSignal, residualSignal, weights] = lmsFilter( ...
    referenceSignal(:), surveillanceSignal(:));
localRequire(all(isfinite(residualSignal), "all"), ...
    "runG4RCancellationCharacterization:ResetNlms", ...
    "Reset NLMS output contains a non-finite value.");

info = struct();
info.ModeledSignal = double(modeledSignal(:));
info.ResidualSignal = double(residualSignal(:));
info.Coefficients = double(weights(:));
info.FilterLength = resolvedOptions.NlmsLength;
info.StepSize = resolvedOptions.NlmsStepSize;
info.MaxStepSize = double(maxstep(lmsFilter, referenceSignal));
info.FinalWeightsNorm = norm(double(weights(:)));
info.ToolboxFunction = "dsp.LMSFilter";
info.ScoreAdaptationEnabled = true;

end

function info = localNoneInfo()

info = struct();
info.ModeledSignal = [];
info.ResidualSignal = [];
info.Coefficients = [];
info.FilterLength = 0.0;
info.StepSize = NaN;
info.MaxStepSize = NaN;
info.FinalWeightsNorm = 0.0;
info.ToolboxFunction = "none";
info.ScoreAdaptationEnabled = false;

end

function rows = localBuildHeldOutMetricRows( ...
        pairRow, product, method, nativeSampleRateHz, decimationFactor)

nativeMetrics = helperComputeG4RCancellationMetrics( ...
    product.NativeReference, product.NativeInput, product.NativeResidual);
reducedMetrics = helperComputeG4RCancellationMetrics( ...
    product.ReducedReference, product.ReducedInput, product.ReducedResidual);
rows = [ ...
    localMetricRow(pairRow, method, "native", nativeSampleRateHz, ...
    nativeMetrics, product.NativeInfo, product.FilterOrder); ...
    localMetricRow(pairRow, method, "reduced", ...
    nativeSampleRateHz ./ decimationFactor, reducedMetrics, ...
    product.ReducedInfo, product.FilterOrder) ...
    ];

end

function row = localMetricRow( ...
        pairRow, method, processingRate, sampleRateHz, metrics, info, ...
        filterOrder)

row = table( ...
    pairRow.BackgroundId, pairRow.TimePairId, pairRow.PairPosition, ...
    pairRow.CalibrationRepetition, pairRow.ScoreRepetition, method, ...
    processingRate, sampleRateHz, metrics.InputSurveillancePower_dB, ...
    metrics.ResidualPower_dB, metrics.CancellationDepth_dB, ...
    metrics.ResidualCoherenceSquared, info.FilterLength, info.StepSize, ...
    info.MaxStepSize, info.FinalWeightsNorm, info.ScoreAdaptationEnabled, ...
    string(info.ToolboxFunction), filterOrder, ...
    VariableNames=["BackgroundId", "TimePairId", "PairPosition", ...
    "CalibrationRepetition", "ScoreRepetition", "Method", ...
    "ProcessingRate", "SampleRateHz", "InputSurveillancePower_dB", ...
    "ResidualPower_dB", "CancellationDepth_dB", ...
    "ResidualCoherenceSquared", "FilterLength", "StepSize", ...
    "MaxStepSize", "FinalWeightsNorm", "ScoreAdaptationEnabled", ...
    "ToolboxFunction", "FilterOrder"]);

end

function rows = localEvaluateMapRate( ...
        pairRow, method, product, nativeSampleRateHz, resolvedOptions)

pairInput = struct();
pairInput.ReferenceSignal = product.NativeReference;
pairInput.SurveillanceSignal = product.NativeResidual;
pairInput.ReducedReferenceSignal = product.ReducedReference;
pairInput.ReducedSurveillanceSignal = product.ReducedResidual;
pairInput.ReducedSignalDecimationFactor = ...
    resolvedOptions.DecimationFactor;
pairInput.NativeWindowStartSample = product.NativeWindowStartSample;
pairInput.ReducedWindowStartSample = product.ReducedWindowStartSample;
pairInput.NativeSampleRateHz = nativeSampleRateHz;
pairInput.BackgroundId = string(pairRow.BackgroundId);
pairInput.SceneId = "real_only_target_free";
pairInput.ProductName = string(method);
pairInput.WindowLabel = string(pairRow.PairPosition);
pairInput.CpiDuration_s = resolvedOptions.CpiDuration_s;
pairInput.Repetition = double(pairRow.ScoreRepetition);
pairInput.HasInjectedTarget = false;

analysis = helperAnalyzeG4MapRateValidity( ...
    pairInput, localMapOptions(resolvedOptions));
rows = addvars(analysis.PairTable, pairRow.TimePairId, ...
    pairRow.CalibrationRepetition, pairRow.ScoreRepetition, ...
    repmat(string(method), height(analysis.PairTable), 1), ...
    Before=1, NewVariableNames=["TimePairId", ...
    "CalibrationRepetition", "ScoreRepetition", "Method"]);

end

function options = localMapOptions(resolvedOptions)

options = struct();
options.InitialDecimationFactor = resolvedOptions.DecimationFactor;
options.RetuneFactors = [100.0 50.0 20.0];
options.DecimationFactors = resolvedOptions.DecimationFactor;
options.DelaySupport_s = resolvedOptions.DelaySupport_s;
options.DopplerSupport_Hz = resolvedOptions.DopplerSupport_Hz;
options.NativeCutBatchSize = resolvedOptions.NativeCutBatchSize;
options.ReducedCutBatchSize = resolvedOptions.ReducedCutBatchSize;
options.NativeDopplerSamplesPerCell = ...
    resolvedOptions.NativeDopplerSamplesPerCell;
options.ReductionInputClass = "production_double";
options.PowerSemantics = "production_g4";
options.ReducedMapFormation = "production_full_map";
options.RetainComparisonMaps = false;
options.MaximumRetainedComparisons = 0.0;
options.EvaluationScope = "g4r_cancellation_characterization";

end

function targetGuard = localRunTargetGuard( ...
        repoRoot, background, selection, resolvedOptions, manifest)

targetPair = manifest.ControlTable( ...
    manifest.ControlTable.BackgroundId == manifest.TargetGuardBackgroundId & ...
    manifest.ControlTable.TimePairId == manifest.TargetGuardTimePairId, :);
localRequire(height(targetPair) == 1, ...
    "runG4RCancellationCharacterization:TargetGuardPair", ...
    "The fixed target guard requires exactly one center score pair.");
calibration = localLoadCorrectedRepetition( ...
    background, targetPair.CalibrationRepetition);
scoreControl = localLoadCorrectedRepetition( ...
    background, targetPair.ScoreRepetition);
injected = localGenerateFixedTargetScore( ...
    repoRoot, background, targetPair.ScoreRepetition, resolvedOptions);
localRequire(injected.ControlExactlyMatchesScore, ...
    "runG4RCancellationCharacterization:TargetGuardControlMismatch", ...
    "Generated target-guard control does not exactly match the saved score capture.");
localRequire(injected.ControlEpochMatchesScore, ...
    "runG4RCancellationCharacterization:TargetGuardControlEpochMismatch", ...
    "Generated target-guard control does not retain the saved score-capture epoch.");
calibrationWindow = localCenterWindow( ...
    calibration.Reference, calibration.Surveillance, ...
    calibration.SampleRateHz, resolvedOptions.CpiDuration_s);
scoreControlWindow = localCenterWindow( ...
    scoreControl.Reference, scoreControl.Surveillance, ...
    scoreControl.SampleRateHz, resolvedOptions.CpiDuration_s);
scoreInjectedWindow = localCenterWindow( ...
    injected.Reference, injected.Surveillance, injected.SampleRateHz, ...
    resolvedOptions.CpiDuration_s);
scoreControlDomain = localBuildR4Domain( ...
    scoreControl.Reference, scoreControl.Surveillance, ...
    resolvedOptions.DecimationFactor);
scoreInjectedDomain = localBuildR4Domain( ...
    injected.Reference, injected.Surveillance, ...
    resolvedOptions.DecimationFactor);
alignment = helperMeasureG4RCpiAlignment( ...
    scoreControlWindow.StartSample, scoreControlWindow.SampleCount, ...
    scoreControl.SampleRateHz, resolvedOptions.DecimationFactor);
reducedStart = alignment.ReducedWindowStartSample(1);
reducedStop = reducedStart + alignment.ReducedSampleCount(1) - 1.0;
methods = ["none"; "current_reset_nlms"; "frozen_native_nlms"];

if selection.Nominated
    methods = [methods; "wiener_fir"];
end

expected = localResolveExpectedTargetCoordinates( ...
    injected.Truth, scoreInjectedWindow.StartSample, ...
    resolvedOptions.CpiDuration_s, injected.SampleRateHz);
targetGuard = table();

for methodIndex = 1:numel(methods)
    method = methods(methodIndex);
    controlProduct = localApplyStudyMethod( ...
        method, calibrationWindow, scoreControl, scoreControlWindow, ...
        scoreControlDomain, reducedStart, reducedStop, selection, ...
        resolvedOptions);
    injectedProduct = localApplyStudyMethod( ...
        method, calibrationWindow, injected, scoreInjectedWindow, ...
        scoreInjectedDomain, reducedStart, reducedStop, selection, ...
        resolvedOptions);
    controlTruth = localEvaluateTruthWindow( ...
        controlProduct.ReducedReference, controlProduct.ReducedResidual, ...
        injected.SampleRateHz ./ resolvedOptions.DecimationFactor, ...
        expected.Delay_s, expected.Doppler_Hz, resolvedOptions.CpiDuration_s);
    injectedTruth = localEvaluateTruthWindow( ...
        injectedProduct.ReducedReference, injectedProduct.ReducedResidual, ...
        injected.SampleRateHz ./ resolvedOptions.DecimationFactor, ...
        expected.Delay_s, expected.Doppler_Hz, resolvedOptions.CpiDuration_s);
    row = table( ...
        string(method), targetPair.BackgroundId, targetPair.TimePairId, ...
        targetPair.CalibrationRepetition, targetPair.ScoreRepetition, ...
        true, injected.ControlExactlyMatchesScore, ...
        injected.ControlEpochMatchesScore, expected.Delay_s, expected.Doppler_Hz, ...
        injectedTruth.PeakDelay_s, injectedTruth.PeakDoppler_Hz, ...
        injectedTruth.DelayError_cells, injectedTruth.DopplerError_cells, ...
        injectedTruth.PeakWithinOneCell, ...
        controlTruth.TruthWindowEnergy, injectedTruth.TruthWindowEnergy, ...
        pow2db(max(injectedTruth.TruthWindowEnergy, eps) ./ ...
        max(controlTruth.TruthWindowEnergy, eps)), ...
        injectedTruth.LocalTruthToBackground_dB, ...
        VariableNames=["Method", "BackgroundId", "TimePairId", ...
        "CalibrationRepetition", "ScoreRepetition", ...
        "CalibrationTargetFree", "GeneratedControlMatchesScore", ...
        "GeneratedControlEpochMatchesScore", "ExpectedDelay_s", ...
        "ExpectedDoppler_Hz", "TruthPeakDelay_s", "TruthPeakDoppler_Hz", ...
        "TruthPeakDelayError_cells", "TruthPeakDopplerError_cells", ...
        "TruthPeakWithinOneCell", "ControlTruthWindowEnergy", ...
        "InjectedTruthWindowEnergy", "InjectedVsControlTruthContrast_dB", ...
        "LocalTruthToBackground_dB"]);
    targetGuard = [targetGuard; row]; %#ok<AGROW>
end

end

function injected = localGenerateFixedTargetScore( ...
        repoRoot, background, scoreRepetition, resolvedOptions)

generatorPath = fullfile(resolvedOptions.ProducerRoot, ...
    "SyntheticHDTVSimulation", "generateRealBackgroundSyntheticSuite.m");
localRequire(isfolder(resolvedOptions.ProducerRoot) && isfile(generatorPath), ...
    "runG4RCancellationCharacterization:MissingSyntheticProducer", ...
    "The fixed field-background synthetic generator is unavailable.");

temporaryRoot = string(tempname);
localEnsureFolder(temporaryRoot);
temporaryCleanup = onCleanup(@() localRemoveTemporaryFolder(temporaryRoot));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(fullfile(resolvedOptions.ProducerRoot, ...
    "SyntheticHDTVSimulation"), "-end");
addpath(fullfile(resolvedOptions.ProducerRoot, ...
    "BistaticDataAnalysis"), "-end");

baseManifest = fullfile(repoRoot, background.BackgroundId, ...
    "session_manifest.json");
scoreScan = background.SessionData.RadarScans(scoreRepetition);
scoreManifest = helperBuildG4RSelectedScoreManifest( ...
    string(baseManifest), scoreScan, temporaryRoot);
baseScenario = buildSyntheticHDTVBaselineScenarioConfig( ...
    SeedSourcePath=baseManifest, TruthSourceMode="capture_adsb_v1");
targets = localBuildFixedTarget(baseScenario.rx_lla_deg_m);
caseDefinitions = localBuildFixedTargetCases(targets);
suiteId = "g4r_cancellation_guard_" + background.BackgroundId + "_" + ...
    string(datetime("now", TimeZone="UTC", ...
    Format="yyyyMMdd'T'HHmmssSSS'Z'"));
suiteArtifact = generateRealBackgroundSyntheticSuite( ...
    SuiteID=suiteId, OutputRoot=temporaryRoot, ...
    BaseSessionManifest=scoreManifest.ManifestPath, BasePartIndex=1, ...
    TruthWindowMaxS=1.0, TruthSamplePeriodS=0.01, ...
    TruthSourceMode="geo_trajectory_v1", ...
    GeoTrajectoryTargets=targets, CaseDefinitions=caseDefinitions, ...
    DirectPathLagSamples=0.0, SeedEchoConditioningEnabled=true, ...
    RunValidation=true, WriteReadme=false, RetainSampleArrays=false);
controlRoot = fullfile(suiteArtifact.suite_folder, "field_only_control");
injectedRoot = fullfile(suiteArtifact.suite_folder, ...
    "field_plus_geo_target");
controlSession = loadIQData("field_only_control", repoRoot, ...
    struct(SessionRoot=controlRoot, IncludeSamples=true, PartSelection=1));
injectedSession = loadIQData("field_plus_geo_target", repoRoot, ...
    struct(SessionRoot=injectedRoot, IncludeSamples=true, PartSelection=1));
controlSamples = controlSession.RadarScans(1).Samples;
injectedSamples = injectedSession.RadarScans(1).Samples;
referenceColumn = background.SyncPrep.RoleInfo.ReferenceColumnIndex;
surveillanceColumn = background.SyncPrep.RoleInfo.SurveillanceColumnIndex;
savedScore = localResolveScanWithSamples( ...
    background.SessionData, scoreRepetition).Samples;
controlExactlyMatchesScore = isequal( ...
    controlSamples(:, referenceColumn), savedScore(:, referenceColumn)) && ...
    isequal(controlSamples(:, surveillanceColumn), ...
    savedScore(:, surveillanceColumn));
controlEpochMatchesScore = abs( ...
    double(controlSession.RadarScans(1).RecordingUTC) - ...
    scoreManifest.ScoreCaptureRecordingUTC) <= 1.0e-6;
truthEntry = localFindGeneratedEntry( ...
    suiteArtifact.datasets, "field_plus_geo_target");
truth = helperAdaptG45TruthForPostHocEvidence( ...
    truthEntry.output_truth_path, "field_plus_geo_target");
[reference, surveillance, sampleRateHz] = localCorrectSampleMatrix( ...
    injectedSamples, background.SyncPrep);

injected = struct();
injected.Reference = reference;
injected.Surveillance = surveillance;
injected.SampleRateHz = sampleRateHz;
injected.Truth = truth;
injected.ControlExactlyMatchesScore = controlExactlyMatchesScore;
injected.ControlEpochMatchesScore = controlEpochMatchesScore;

clear controlSamples injectedSamples controlSession injectedSession
clear pathCleanup temporaryCleanup

end

function targets = localBuildFixedTarget(receiverLla_deg_m)

times_s = [0.0; 0.5; 1.0];
north_m = 15000.0 + 150.0 .* times_s;
east_m = zeros(size(times_s));
altitude_m = repmat(3000.0, numel(times_s), 1);
waypoints = table(times_s, north_m, east_m, altitude_m, ...
    VariableNames=["Time_s", "North_m", "East_m", "Altitude_m"]);
targets = helperBuildGeoTrajectoryTargetsFromReceiverLocalWaypoints( ...
    waypoints, ReceiverLla_deg_m=double(receiverLla_deg_m), ...
    TargetId="G4R_GUARD_15KM", IcaoHex="G4R015", Callsign="G4RGUARD", ...
    EchoGainDB=-18.0);

end

function cases = localBuildFixedTargetCases(targets)

control = struct( ...
    "dataset_id", "field_only_control", ...
    "difficulty_label", "control", ...
    "injection_enabled", false, ...
    "target_ids", strings(0, 1), ...
    "target_echo_gain_db", [], ...
    "intended_use", "G4-R target-preservation paired control.", ...
    "expected_gate_outcome", "No detector execution.", ...
    "comments", "Reference and surveillance copied unchanged.");
injected = struct( ...
    "dataset_id", "field_plus_geo_target", ...
    "difficulty_label", "single_near_negative_m18db", ...
    "injection_enabled", true, ...
    "target_ids", string({targets.icao_hex}).', ...
    "target_echo_gain_db", -18.0, ...
    "intended_use", "G4-R map-preservation guard only.", ...
    "expected_gate_outcome", "No CFAR, NMS, or detector claim.", ...
    "comments", "15 km northbound surveillance-only geometry-driven target.");
cases = [control, injected];

end

function truth = localEvaluateTruthWindow( ...
        referenceSignal, residualSignal, sampleRateHz, expectedDelay_s, ...
        expectedDoppler_Hz, cpiDuration_s)

mapProduct = helperFormG4ProductionMap( ...
    referenceSignal, residualSignal, sampleRateHz, ...
    [1.0 ./ cpiDuration_s 1.0 ./ cpiDuration_s]);
power = double(mapProduct.Power);
delayAxis_s = mapProduct.DelayAxis_s;
dopplerAxis_Hz = mapProduct.DopplerAxis_Hz;
delaySpacing_s = median(diff(delayAxis_s));
dopplerSpacing_Hz = median(diff(dopplerAxis_Hz));
[delayGrid_s, dopplerGrid_Hz] = meshgrid(delayAxis_s, dopplerAxis_Hz);
truthMask = abs(delayGrid_s - expectedDelay_s) <= delaySpacing_s & ...
    abs(dopplerGrid_Hz - expectedDoppler_Hz) <= dopplerSpacing_Hz;
localRequire(any(truthMask, "all"), ...
    "runG4RCancellationCharacterization:TruthWindow", ...
    "The fixed target truth window lies outside the map.");
truthMap = power;
truthMap(~truthMask) = -Inf;
[~, peakIndex] = max(truthMap, [], "all");
[peakRow, peakColumn] = ind2sub(size(truthMap), peakIndex);
localMask = abs(delayGrid_s - expectedDelay_s) <= ...
    4.0 .* delaySpacing_s & abs(dopplerGrid_Hz - expectedDoppler_Hz) <= ...
    4.0 .* dopplerSpacing_Hz;
backgroundMask = localMask & ~truthMask;
backgroundValues = power(backgroundMask);

if isempty(backgroundValues)
    backgroundValues = power(~truthMask);
end

truth = struct();
truth.TruthWindowEnergy = sum(power(truthMask), "all");
truth.PeakDelay_s = delayAxis_s(peakColumn);
truth.PeakDoppler_Hz = dopplerAxis_Hz(peakRow);
truth.DelayError_cells = abs( ...
    truth.PeakDelay_s - expectedDelay_s) ./ delaySpacing_s;
truth.DopplerError_cells = abs( ...
    truth.PeakDoppler_Hz - expectedDoppler_Hz) ./ dopplerSpacing_Hz;
truth.PeakWithinOneCell = truth.DelayError_cells <= 1.0 && ...
    truth.DopplerError_cells <= 1.0;
truth.LocalTruthToBackground_dB = pow2db( ...
    max(max(power(truthMask)), eps) ./ ...
    max(median(backgroundValues, "omitnan"), eps));

clear power mapProduct

end

function expected = localResolveExpectedTargetCoordinates( ...
        truth, nativeStartSample, cpiDuration_s, nativeSampleRateHz)

tracks = truth.truth_bundle.bistatic_tracks;
localRequire(isscalar(tracks), ...
    "runG4RCancellationCharacterization:TargetCount", ...
    "The fixed target guard requires exactly one target.");
track = tracks(1);
relativeTimes_s = double(track.t_utc(:)) - ...
    double(truth.truth_bundle.radar_epoch_utc);
evaluationTime_s = (nativeStartSample - 1.0) ./ nativeSampleRateHz + ...
    cpiDuration_s ./ 2.0;
rangeExcess_m = interp1(relativeTimes_s, double(track.R_excess_m(:)), ...
    evaluationTime_s, "linear", "extrap");
bistaticDoppler_Hz = interp1(relativeTimes_s, double(track.f_D_hz(:)), ...
    evaluationTime_s, "linear", "extrap");
expected = struct();
expected.Delay_s = -rangeExcess_m ./ physconst("LightSpeed");
expected.Doppler_Hz = -bistaticDoppler_Hz;

end

function entry = localFindGeneratedEntry(entries, datasetId)

entryMask = string({entries.dataset_id}) == datasetId;

if nnz(entryMask) ~= 1
    error("runG4RCancellationCharacterization:GeneratedDataset", ...
        "Expected one generated dataset named %s.", datasetId);
end

entry = entries(entryMask);

end

function [reference, surveillance, sampleRateHz] = ...
        localCorrectSampleMatrix(sampleMatrix, syncPrep)

reference = double(sampleMatrix(:, ...
    syncPrep.RoleInfo.ReferenceColumnIndex));
surveillance = double(sampleMatrix(:, ...
    syncPrep.RoleInfo.SurveillanceColumnIndex));
surveillance = localApplyIntegerDelay( ...
    surveillance, syncPrep.GlobalCorrection.AppliedLag_samples);
sampleRateHz = double(syncPrep.ResolvedOptions.SampleRateHz);
surveillance = localApplyResidualFrequencyCorrection( ...
    surveillance, ...
    syncPrep.GlobalCorrection.AppliedResidualFrequency_Hz, sampleRateHz);

end

function repetition = localLoadCorrectedRepetition(background, repetitionIndex)

scan = localResolveScanWithSamples( ...
    background.SessionData, repetitionIndex);
[reference, surveillance, sampleRateHz] = localCorrectSampleMatrix( ...
    scan.Samples, background.SyncPrep);
repetition = struct();
repetition.Reference = reference;
repetition.Surveillance = surveillance;
repetition.SampleRateHz = sampleRateHz;
repetition.Repetition = double(repetitionIndex);

end

function window = localCenterWindow( ...
        referenceSignal, surveillanceSignal, sampleRateHz, cpiDuration_s)

sampleCount = round(cpiDuration_s .* sampleRateHz);
startSample = floor((numel(referenceSignal) - sampleCount) ./ 2.0) + 1.0;
stopSample = startSample + sampleCount - 1.0;

if startSample < 1 || stopSample > numel(referenceSignal)
    error("runG4RCancellationCharacterization:CpiWindow", ...
        "The fixed 100 ms center window lies outside the score capture.");
end

window = struct();
window.Reference = double(referenceSignal(startSample:stopSample));
window.Surveillance = double(surveillanceSignal(startSample:stopSample));
window.StartSample = double(startSample);
window.StopSample = double(stopSample);
window.SampleCount = double(sampleCount);

end

function scan = localResolveScanWithSamples(sessionData, repetitionIndex)

scan = sessionData.RadarScans(repetitionIndex);

if ~isempty(scan.Samples)
    return
end

absolutePath = fullfile(string(sessionData.DatasetRoot), strrep( ...
    sessionData.RadarTable.RelativePath(repetitionIndex), "/", filesep));
scan = helperScanBasebandCaptureFile(absolutePath, true);

end

function delayedSignal = localApplyIntegerDelay(inputSignal, sampleDelay)

sampleDelay = round(double(sampleDelay));
signalLength = numel(inputSignal);

if sampleDelay > 0
    delayedSignal = [ ...
        zeros(sampleDelay, 1, "like", inputSignal); ...
        inputSignal(1:signalLength - sampleDelay) ...
        ];
elseif sampleDelay < 0
    advanceCount = abs(sampleDelay);
    delayedSignal = [ ...
        inputSignal(advanceCount + 1:end); ...
        zeros(advanceCount, 1, "like", inputSignal) ...
        ];
else
    delayedSignal = inputSignal(:);
end

end

function correctedSignal = localApplyResidualFrequencyCorrection( ...
        inputSignal, residualFrequencyHz, sampleRateHz)

sampleIndex = (0:numel(inputSignal) - 1).';
correctionPhase = exp(-1j .* 2.0 .* pi .* residualFrequencyHz .* ...
    sampleIndex ./ sampleRateHz);
correctedSignal = inputSignal(:) .* correctionPhase;

end

function record = localCoefficientRecord(tapCount, estimate)

record = localCoefficientRecordTemplate();
record.TapCount = double(tapCount);
record.Coefficients = estimate.Coefficients(:);
record.Regularization = estimate.Regularization;
record.RegularizedMatrixConditionNumber = ...
    estimate.RegularizedMatrixConditionNumber;

end

function record = localCoefficientRecordTemplate()

record = struct( ...
    "BackgroundId", "", ...
    "TimePairId", "", ...
    "CalibrationRepetition", NaN, ...
    "ScoreRepetition", NaN, ...
    "TapCount", NaN, ...
    "Coefficients", zeros(0, 1), ...
    "Regularization", NaN, ...
    "RegularizedMatrixConditionNumber", NaN);

end

function projection = localBuildProjection( ...
        selectionElapsed_s, benchmarkElapsed_s, resolvedOptions)

backgroundCount = numel(resolvedOptions.BackgroundIds);
preMargin_s = selectionElapsed_s + backgroundCount .* benchmarkElapsed_s;
safetyMargin_s = preMargin_s .* resolvedOptions.SafetyMarginFraction;
projection = struct();
projection.SelectionElapsed_s = selectionElapsed_s;
projection.BenchmarkBackgroundElapsed_s = benchmarkElapsed_s;
projection.BackgroundCount = double(backgroundCount);
projection.PreMarginProjected_s = preMargin_s;
projection.SafetyMargin_s = safetyMargin_s;
projection.TotalProjected_s = preMargin_s + safetyMargin_s;
projection.AuthorizedBudget_s = resolvedOptions.TimeBudget_s;
projection.FitsAuthorizedBudget = projection.TotalProjected_s <= ...
    projection.AuthorizedBudget_s;
projection.ExecutionIsolation = ...
    "one_compact_background_shard_per_saved_configuration";

end

function nextAction = localBenchmarkNextAction(projection)

if projection.FitsAuthorizedBudget
    nextAction = "Projection fits the authorized budget; launch the three compact background shards and combine only the exact manifest-complete results.";
else
    nextAction = "Projection exceeds the authorized budget; preserve the benchmark and request a larger bounded execution authorization before launching background shards.";
end

end

function nextAction = localBuildShardLaunchAction( ...
        benchmarkBundleRoot, wienerSelection)

benchmarkResultPath = fullfile(benchmarkBundleRoot, ...
    "g4rCancellationCharacterizationResults.mat");

if logical(wienerSelection.Nominated)
    wienerText = "The globally nominated Wiener FIR is " + ...
        string(wienerSelection.SelectedTapCount) + " taps.";
else
    wienerText = "No fixed Wiener FIR is nominated; retain the benchmark selection state.";
end

nextAction = "Launch three isolated background_shard runs using BenchmarkResultPath='" + ...
    string(benchmarkResultPath) + "', then combine only their exact, manifest-complete compact results with the cancellation-characterization coordinator. " + ...
    wienerText;

end

function result = localBuildResult( ...
        runTimestampZ, bundleRoot, resolvedOptions, manifest, ...
        selectionStage, shard, projection, totalElapsed_s)

result = localEmptyResult();
result.SchemaVersion = "g4r_cancellation_characterization_v1";
result.StageId = "G4_R_Cancellation_Characterization";
result.AnalysisTimestampZ = runTimestampZ;
result.BundleRoot = string(bundleRoot);
result.ExecutionMode = resolvedOptions.ExecutionMode;
result.Configuration = localConfiguration(resolvedOptions);
result.Manifest = manifest;
result.WienerSearchDetailTable = selectionStage.DetailTable;
result.WienerSelectionTable = selectionStage.WienerSelectionTable;
result.WienerSelection = selectionStage.Selection;
result.HeldOutMetricTable = shard.HeldOutMetricTable;
result.MapRateMetricTable = shard.MapRateMetricTable;
result.TargetGuardTable = shard.TargetGuardTable;
result.WienerCoefficientRecords = shard.WienerCoefficientRecords;
result.HardwareEvidenceTable = shard.HardwareEvidenceTable;
result.SourceFingerprintTable = shard.SourceFingerprintTable;
result.BackgroundContractTable = shard.BackgroundContractTable;
result.Projection = projection;
decision = helperEvaluateG4RCancellationDecision( ...
    result.MapRateMetricTable, result.TargetGuardTable, ...
    selectionStage.Selection);
result.MethodDecisionTable = decision.MethodDecisionTable;
result.MapRateValidityStatus = "retune_pending_bounded_correction";
result.CollectionSuitabilityStatus = ...
    "blocked_pending_reviewed_adsb_timing_geometry_policy";
result.FormalG5Enabled = false;
result.FormalG6Enabled = false;
result.FormalG8Enabled = false;
result.Outcome = decision.Outcome;
result.DecisionRationale = decision.DecisionRationale;
result.NextAction = decision.NextAction;
result.TotalElapsed_s = totalElapsed_s;
result.ArtifactLinkTable = localBuildArtifactLinkTable(result);
result.CompactResultAudit = localCompactAudit(result);

end

function configuration = localConfiguration(resolvedOptions)

configuration = struct();
configuration.CpiDuration_s = resolvedOptions.CpiDuration_s;
configuration.TimePairs = ["1_to_2"; "4_to_5"; "9_to_10"];
configuration.FirTapCounts = resolvedOptions.FirTapCounts;
configuration.WienerRegularizationFraction = ...
    resolvedOptions.WienerRegularizationFraction;
configuration.NlmsContract = ...
    "normalized_lms_length16_step0.02_leakage1";
configuration.CurrentComparator = ...
    "independently_reset_native_and_reduced_nlms_on_score_window";
configuration.NativeFirstContract = ...
    "cancel_native_then_resample_residual_with_r4_production_path";
configuration.MapContract = ...
    "r4_factor200_production_full_map_common_physical_grid";
configuration.TargetGuard = ...
    "15km_minus18db_center_pair_4_to_5_map_preservation_only";
configuration.NoDetectorExecution = true;
configuration.BenchmarkResultPath = resolvedOptions.BenchmarkResultPath;

end

function linkTable = localBuildArtifactLinkTable(~)

linkTable = helperBuildG4RCancellationArtifactLinks();

end

function audit = localCompactAudit(~)

audit = struct();
audit.RawIqPresent = false;
audit.FullMapCollectionPresent = false;
audit.DetectorExecuted = false;
audit.FormalG5Enabled = false;
audit.FormalG6Enabled = false;
audit.FormalG8Enabled = false;
audit.TargetGuardIsMapPreservationOnly = true;
audit.Compact = ~audit.RawIqPresent && ...
    ~audit.FullMapCollectionPresent && ~audit.DetectorExecuted;

end

function result = localEmptyResult()

result = struct();
result.WienerSearchDetailTable = table();
result.WienerSelectionTable = table();
result.HeldOutMetricTable = table();
result.MapRateMetricTable = table();
result.TargetGuardTable = table();
result.HardwareEvidenceTable = table();
result.SourceFingerprintTable = table();
result.BackgroundContractTable = table();
result.MethodDecisionTable = table();
result.ArtifactLinkTable = table();

end

function projection = localEmptyProjection()

projection = struct( ...
    "SelectionElapsed_s", NaN, ...
    "BenchmarkBackgroundElapsed_s", NaN, ...
    "BackgroundCount", NaN, ...
    "PreMarginProjected_s", NaN, ...
    "SafetyMargin_s", NaN, ...
    "TotalProjected_s", NaN, ...
    "AuthorizedBudget_s", NaN, ...
    "FitsAuthorizedBudget", false, ...
    "ExecutionIsolation", "");

end

function localWriteResultBundle(result, resolvedOptions, writeReport)

if ~resolvedOptions.SaveResult
    return
end

bundleRoot = string(result.BundleRoot);
localEnsureFolder(bundleRoot);
resultPath = fullfile(bundleRoot, ...
    "g4rCancellationCharacterizationResults.mat");
result.ResultPath = string(resultPath);
save(resultPath, "result", "-v7.3");
writetable(result.Manifest.ControlTable, fullfile(bundleRoot, ...
    "control_manifest.csv"));
localWriteTableIfPresent(result.WienerSearchDetailTable, bundleRoot, ...
    "wiener_search_detail.csv");
localWriteTableIfPresent(result.WienerSelectionTable, bundleRoot, ...
    "wiener_selection.csv");
localWriteTableIfPresent(result.HeldOutMetricTable, bundleRoot, ...
    "heldout_metrics.csv");
localWriteTableIfPresent(result.MapRateMetricTable, bundleRoot, ...
    "map_rate_metrics.csv");
localWriteTableIfPresent(result.TargetGuardTable, bundleRoot, ...
    "target_guard.csv");
localWriteTableIfPresent(result.HardwareEvidenceTable, bundleRoot, ...
    "hardware_evidence.csv");
localWriteTableIfPresent(result.SourceFingerprintTable, bundleRoot, ...
    "source_fingerprints.csv");
localWriteTableIfPresent(result.BackgroundContractTable, bundleRoot, ...
    "background_contracts.csv");
localWriteTableIfPresent(result.MethodDecisionTable, bundleRoot, ...
    "method_decision.csv");
writetable(result.ArtifactLinkTable, fullfile(bundleRoot, ...
    "artifact_links.csv"));
writelines(jsonencode(result.Configuration, PrettyPrint=true), ...
    fullfile(bundleRoot, "configuration.json"));
writelines(localSummaryLines(result), fullfile(bundleRoot, "summary.md"));

if writeReport
    report = helperBuildG4RCancellationHtmlReport(result, bundleRoot);
    result.HtmlReport = report;
    save(resultPath, "result", "-v7.3");
    manifest = localBuildReportManifest(result, bundleRoot);
    writelines(jsonencode(manifest, PrettyPrint=true), ...
        fullfile(bundleRoot, "report_manifest.json"));
end

end

function localWriteTableIfPresent(inputTable, bundleRoot, fileName)

if ~isempty(inputTable)
    writetable(inputTable, fullfile(bundleRoot, fileName));
end

end

function lines = localSummaryLines(result)

lines = [ ...
    "# G4-R Cancellation Characterization"; ...
    ""; ...
    "- Outcome: `" + string(result.Outcome) + "`"; ...
    "- Map-rate validity: `" + string(result.MapRateValidityStatus) + "`"; ...
    "- Collection suitability: `" + ...
    string(result.CollectionSuitabilityStatus) + "`"; ...
    "- Formal G5/G6/G8 enabled: `false`"; ...
    "- Target guard is map-preservation only: `true`"; ...
    "- Raw IQ retained: `false`"; ...
    "- Full maps retained: `false`"; ...
    "- Decision rationale: " + string(result.DecisionRationale); ...
    "- Next action: " + string(result.NextAction) ...
    ];

end

function manifest = localBuildReportManifest(result, bundleRoot)

entries = dir(fullfile(bundleRoot, "**", "*"));
entries = entries(~[entries.isdir]);
filePath = string(fullfile({entries.folder}, {entries.name})).';
relativePath = erase(filePath, string(bundleRoot) + filesep);
bytes = double([entries.bytes]).';
sha256 = strings(numel(entries), 1);
rowCount = nan(numel(entries), 1);

for entryIndex = 1:numel(entries)
    sha256(entryIndex) = helperG4RSha256(filePath(entryIndex));

    if endsWith(lower(relativePath(entryIndex)), ".csv")
        try
            rowCount(entryIndex) = height(readtable(filePath(entryIndex)));
        catch
            rowCount(entryIndex) = NaN;
        end
    end
end

manifest = struct();
manifest.SchemaVersion = "g4r_cancellation_report_manifest_v1";
manifest.ArtifactTable = table(relativePath, bytes, sha256, rowCount);
manifest.HtmlPath = "summary.html";
manifest.HtmlLinks = result.ArtifactLinkTable;
manifest.ExternalDependencyFree = isfield(result, "HtmlReport") && ...
    result.HtmlReport.ExternalDependencyFree;

end

function localWriteFailure(bundleRoot, runException)

if strlength(bundleRoot) == 0 || ~isfolder(bundleRoot)
    return
end

writelines([ ...
    "# G4-R Cancellation Characterization"; ...
    ""; ...
    "- Outcome: `failed_before_completion`"; ...
    "- Identifier: `" + string(runException.identifier) + "`"; ...
    "- Message: " + string(runException.message) ...
    ], fullfile(bundleRoot, "summary.md"));

end

function localEnsureFolder(folderPath)

if ~isfolder(folderPath)
    mkdir(folderPath);
end

end

function localRemoveTemporaryFolder(folderPath)

if isfolder(folderPath)
    rmdir(folderPath, "s");
end

end

function localRequire(condition, identifier, message, varargin)

if ~condition
    error(identifier, message, varargin{:});
end

end
