function results = runG1Ingest(datasetId, repoRoot)
%RUNG1INGEST Execute the G1 ingest gate for a passive bistatic session.
%
%   RESULTS = RUNG1INGEST() runs G1 on the reference dataset
%   20260622T102123 and writes an evidence bundle under:
%   artifacts/<datasetId>/G1_Ingest/<runTimestampZ>/
%
%   RESULTS = RUNG1INGEST(DATASETID, REPOROOT) allows the dataset ID and
%   repository root to be overridden. This gate runner uses LOADIQDATA as
%   its reusable session-ingest dependency.

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
end

gateId = "G1_Ingest";
repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
bundleRoot = fullfile(repoRoot, "artifacts", datasetId, gateId, runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");
logRoot = fullfile(bundleRoot, "logs");

fprintf("Running %s for dataset %s\n", gateId, datasetId);
fprintf("Repository root:\t%s\n", repoRoot);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);
    localEnsureFolder(logRoot);

    loadOptions = struct();
    loadOptions.IncludeSamples = false;
    sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    manifest = sessionData.Manifest;
    manifestTable = sessionData.ManifestInventoryTable;
    radarScans = sessionData.RadarScans;
    radarTable = sessionData.RadarTable;
    seamTable = sessionData.SeamTable;
    readerContract = sessionData.NativeReaderContract;
    [decision, failureCause, nextBranch, passFlags] = localDetermineDecision( ...
        manifest, manifestTable, radarScans, seamTable);

    summaryLines = localBuildSummaryLines(manifest, passFlags, ...
        decision, nextBranch, manifestTable, radarScans, seamTable, ...
        bundleRoot, runTimestampZ, readerContract);
    captureProvenanceLines = localBuildCaptureProvenanceLines(manifest, ...
        radarScans, readerContract);
    decodeContractLines = localBuildDecodeContractLines(radarScans, ...
        readerContract);
    timingContractLines = localBuildTimingContractLines(manifest, radarScans);
    cpiContractLines = localBuildCpiContractLines(radarScans);
    decodeFigureLines = localBuildDecodeFigureLines(radarScans, ...
        readerContract);

    requirementsCoverageTable = table( ...
        ["ING-001"; "ING-002"; "ING-003"; "ING-004"], ...
        repmat(decision, 4, 1), ...
        [ ...
            "manifest_vs_observed.csv; figures/figure_01_manifest_vs_observed.png"; ...
            "decode_contract_summary.md; radar_metadata_scan.csv; figures/figure_03_decode_contract_summary.png"; ...
            "timing_contract_note.md; seam_continuity_summary.csv; figures/figure_02_seam_continuity_summary.png"; ...
            "cpi_segmentation_contract_summary.md; summary.md" ...
            ], ...
        [ ...
            "Required radar, truth, and log artifacts reconciled against the manifest."; ...
            "Decode contract frozen with channel order, wrapper-overhead reconciliation, and native-reader fallback provenance when needed."; ...
            "Per-file sample-span timing separated from wall-clock repetition timing."; ...
            "Intra-file-only CPI segmentation frozen for downstream gates." ...
            ], ...
        VariableNames = {'RequirementId', 'Status', 'EvidenceReference', 'Notes'});

    configSnapshot = localBuildConfigSnapshot(manifest, datasetId, gateId, ...
        repoRoot, bundleRoot, runTimestampZ, sessionData);
    metrics = localBuildMetrics(manifest, manifestTable, radarScans, seamTable, ...
        passFlags, decision, nextBranch, readerContract);
    comparisonSnapshot = localBuildComparisonSnapshot(datasetId, gateId, ...
        runTimestampZ, bundleRoot, decision, nextBranch, passFlags, metrics);

    manifestCsvPath = fullfile(bundleRoot, "manifest_vs_observed.csv");
    radarScanCsvPath = fullfile(bundleRoot, "radar_metadata_scan.csv");
    seamCsvPath = fullfile(bundleRoot, "seam_continuity_summary.csv");
    summaryPath = fullfile(bundleRoot, "summary.md");
    captureProvenancePath = fullfile(bundleRoot, ...
        "capture_provenance_interpretation_summary.md");
    decodeContractPath = fullfile(bundleRoot, "decode_contract_summary.md");
    timingContractPath = fullfile(bundleRoot, "timing_contract_note.md");
    cpiContractPath = fullfile(bundleRoot, ...
        "cpi_segmentation_contract_summary.md");
    requirementsCoveragePath = fullfile(bundleRoot, "requirements_coverage.csv");
    configSnapshotPath = fullfile(bundleRoot, "config_snapshot.json");
    metricsJsonPath = fullfile(bundleRoot, "metrics.json");
    metricsMatPath = fullfile(bundleRoot, "metrics.mat");
    decisionPath = fullfile(bundleRoot, "decision.txt");
    nextBranchPath = fullfile(bundleRoot, "next_branch.txt");
    failureCausePath = fullfile(bundleRoot, "failure_cause.txt");
    manifestFigurePath = fullfile(figureRoot, ...
        "figure_01_manifest_vs_observed.png");
    seamFigurePath = fullfile(figureRoot, ...
        "figure_02_seam_continuity_summary.png");
    decodeFigurePath = fullfile(figureRoot, ...
        "figure_03_decode_contract_summary.png");

    try
        writetable(manifestTable, manifestCsvPath);
        writetable(radarTable, radarScanCsvPath);
        writetable(seamTable, seamCsvPath);
        writetable(requirementsCoverageTable, requirementsCoveragePath);
    catch writeTableException
        error("runG1Ingest:WriteTableFailed", ...
            "Failed to write a bundle table artifact: %s", ...
            writeTableException.message);
    end

    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(captureProvenancePath, captureProvenanceLines);
    localWriteTextFile(decodeContractPath, decodeContractLines);
    localWriteTextFile(timingContractPath, timingContractLines);
    localWriteTextFile(cpiContractPath, cpiContractLines);
    localWriteTextFile(decisionPath, decision);
    localWriteTextFile(nextBranchPath, nextBranch);

    if decision ~= "pass"
        localWriteTextFile(failureCausePath, failureCause);
    end

    localWriteJsonFile(configSnapshotPath, configSnapshot);
    localWriteJsonFile(metricsJsonPath, metrics);

    try
        save(metricsMatPath, "metrics", "manifestTable", "radarTable", ...
            "seamTable", "requirementsCoverageTable");
    catch saveException
        error("runG1Ingest:SaveMetricsFailed", ...
            "Failed to write metrics.mat: %s", saveException.message);
    end

    try
        comparisonSnapshotPath = helperWriteComparisonSnapshot( ...
            string(bundleRoot), comparisonSnapshot);
    catch saveException
        error("runG1Ingest:SaveComparisonSnapshotFailed", ...
            "Failed to write G1 comparison snapshot: %s", ...
            saveException.message);
    end

    helperRenderTextSummaryFigure(localTableDisplayLines(manifestTable), ...
        "G1 Manifest vs Observed", manifestFigurePath);
    helperRenderTextSummaryFigure(localTableDisplayLines(seamTable), ...
        "G1 Seam Continuity Summary", seamFigurePath);
    helperRenderTextSummaryFigure(decodeFigureLines, ...
        "G1 Decode Contract Summary", decodeFigurePath);

    results = struct();
    results.DatasetId = datasetId;
    results.GateId = gateId;
    results.RunTimestampZ = runTimestampZ;
    results.BundleRoot = string(bundleRoot);
    results.Decision = decision;
    results.NextBranch = nextBranch;
    results.PassFlags = passFlags;
    results.Metrics = metrics;
    results.ComparisonSnapshotPath = string(comparisonSnapshotPath);

    fprintf("Decision:\t%s\n", decision);
    fprintf("Next branch:\t%s\n", nextBranch);
    fprintf("Bundle root:\t%s\n", bundleRoot);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end

function [decision, failureCause, nextBranch, passFlags] = localDetermineDecision( ...
    manifest, manifestTable, radarScans, seamTable)

requiredRows = manifestTable.RequiredByManifest;
missingRequiredCount = nnz(requiredRows & ~manifestTable.Observed);
unexpectedSourceArtifactCount = nnz( ...
    manifestTable.Status == "unexpected_extra_source_artifact");
scanCount = numel(radarScans);

repetitionVector = zeros(scanCount, 1);
sampleSpanVector = zeros(scanCount, 1);
durationVector = zeros(scanCount, 1);
recordingUtcVector = zeros(scanCount, 1);
sampleRateVector = zeros(scanCount, 1);
centerFrequencyVector = zeros(scanCount, 1);
channelCountVector = zeros(scanCount, 1);
isComplexVector = false(scanCount, 1);
channel1Labels = strings(scanCount, 1);
channel2Labels = strings(scanCount, 1);
sessionIdVector = strings(scanCount, 1);

for idx = 1:scanCount
    repetitionVector(idx) = radarScans(idx).Repetition;
    sampleSpanVector(idx) = radarScans(idx).SampleSpan_s;
    durationVector(idx) = radarScans(idx).Duration_s;
    recordingUtcVector(idx) = radarScans(idx).RecordingUTC;
    sampleRateVector(idx) = radarScans(idx).SampleRate;
    centerFrequencyVector(idx) = radarScans(idx).CenterFrequency;
    channelCountVector(idx) = radarScans(idx).NumChannels;
    isComplexVector(idx) = radarScans(idx).IsComplex;
    channel1Labels(idx) = radarScans(idx).Antenna1;
    channel2Labels(idx) = radarScans(idx).Antenna2;
    sessionIdVector(idx) = radarScans(idx).SessionID;
end

recordingUtcDelta = diff(recordingUtcVector);
requestedSpacingSeconds = manifest.capture_repetition_spacing_s;
sampleSpanBoundaryVector = sampleSpanVector(1:end - 1);
wallClockMinusSampleSpan = recordingUtcDelta - sampleSpanBoundaryVector;
wallClockMinusSampleSpanAndRequestedSpacing = wallClockMinusSampleSpan - ...
    requestedSpacingSeconds;
dateTimeVsRecordingMs = [radarScans.DateTimeVsRecording_ms].';
allWrapperOverheadPositive = all([radarScans.WrapperOverheadBytes].' > 0);
allNativePayloadCountsStable = isscalar(unique([radarScans.NumSamples].'));

passFlags = struct();
passFlags.InventoryReconciled = missingRequiredCount == 0 && ...
    unexpectedSourceArtifactCount == 0;
passFlags.DecodeContractConfirmed = ...
    allNativePayloadCountsStable && ...
    all(sampleRateVector == manifest.sdr_defaults.sample_rate_hz) && ...
    all(centerFrequencyVector == manifest.sdr_defaults.center_frequency_hz) && ...
    all(channelCountVector == 2) && ...
    all(isComplexVector) && ...
    allWrapperOverheadPositive;
passFlags.ChannelContractConfirmed = ...
    all(channel1Labels == "RF0:RX2") && ...
    all(channel2Labels == "RF1:RX2");
passFlags.TimingModelFrozen = ...
    all(abs(sampleSpanVector - manifest.capture_duration_s) < 1e-12) && ...
    all(abs(durationVector - manifest.capture_duration_s) < 1e-12) && ...
    all(wallClockMinusSampleSpan >= -1e-6) && ...
    all(wallClockMinusSampleSpanAndRequestedSpacing >= -1e-6) && ...
    abs(recordingUtcVector(1) - manifest.radar_epoch_utc) < 0.01 && ...
    max(abs(dateTimeVsRecordingMs)) < 25;
passFlags.SeamChecksPassed = isempty(seamTable) || ...
    all(seamTable.RepetitionIncrement == 1) && ...
    all(seamTable.SampleCountStable) && ...
    all(seamTable.MetadataStable) && ...
    all(seamTable.DecodeContractStable) && ...
    all(seamTable.Status == "ok_gap_expected");
passFlags.CpiSegmentationFrozen = true;
passFlags.ManifestOrderConfirmed = isequal(repetitionVector, (1:scanCount).');
passFlags.SessionIdConfirmed = all(sessionIdVector == string(manifest.session_id));

hardReject = ~passFlags.InventoryReconciled || ...
    ~passFlags.DecodeContractConfirmed || ...
    ~passFlags.ChannelContractConfirmed || ...
    ~passFlags.SeamChecksPassed || ...
    ~passFlags.ManifestOrderConfirmed || ...
    ~passFlags.SessionIdConfirmed;
softRetune = ~passFlags.TimingModelFrozen || ~passFlags.CpiSegmentationFrozen;

if hardReject
    decision = "reject";
elseif softRetune
    decision = "retune";
else
    decision = "pass";
end

if decision == "pass"
    failureCause = "";
    nextBranch = "Proceed to G2_RF_Health with the frozen G1 ingest contract.";
elseif decision == "retune"
    failureCause = "Retune G1 timing semantics before downstream processing.";
    nextBranch = "Retune G1 timing assumptions and rerun G1_Ingest.";
else
    failureCause = "Required ingest contract checks did not pass.";
    nextBranch = "Do not open G2. Rework G1 ingest assumptions or reject the dataset.";
end

end

function summaryLines = localBuildSummaryLines(manifest, passFlags, ...
    decision, nextBranch, manifestTable, radarScans, seamTable, bundleRoot, ...
    runTimestampZ, readerContract)

recordingUtcDelta = diff([radarScans.RecordingUTC]);
unexpectedSourceArtifactCount = nnz( ...
    manifestTable.Status == "unexpected_extra_source_artifact");
localSupportArtifactCount = nnz( ...
    manifestTable.Status == "local_support_nonblocking");
sampleSpanVector = [radarScans.SampleSpan_s];
wrapperOverhead = [radarScans.WrapperOverheadBytes];
chosenReader = localJoinStringValues(readerContract.Reader);
fallbackUsedText = localLogicalWord(readerContract.RawFreadFallbackUsed);
failureCategory = localJoinStringValues( ...
    readerContract.NativeReaderFailureCategory);
failureMessage = localJoinStringValues( ...
    readerContract.NativeReaderFailureMessage);

summaryLines = [ ...
    "# G1 Ingest Summary"; ...
    ""; ...
    sprintf("- Dataset: `%s`", manifest.session_id); ...
    "- Gate: `G1_Ingest`"; ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Decision: `%s`", decision); ...
    sprintf("- Next branch: %s", nextBranch); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    ""; ...
    "## Key Findings"; ...
    sprintf("- Required manifest artifacts present: `%d/%d`", ...
        nnz(manifestTable.RequiredByManifest & manifestTable.Observed), ...
        nnz(manifestTable.RequiredByManifest)); ...
    sprintf("- Unexpected extra source artifacts: `%d`", ...
        unexpectedSourceArtifactCount); ...
    sprintf("- Local support artifacts observed: `%d`", ...
        localSupportArtifactCount); ...
    sprintf("- Chosen reader contract: `%s`", chosenReader); ...
    sprintf("- Raw `fread` fallback used: `%s`", fallbackUsedText); ...
    sprintf("- Canonical decoded shape per file: `%d x %d complex int16`", ...
        radarScans(1).NumSamples, radarScans(1).NumChannels); ...
    sprintf("- Channel order frozen as column 1 = `%s`, column 2 = `%s`", ...
        radarScans(1).Antenna1, radarScans(1).Antenna2); ...
    sprintf("- Sample span per file: `%.6f s`", sampleSpanVector(1)); ...
    sprintf("- RecordingUTC boundary deltas: `%.6f s` to `%.6f s`", ...
        min(recordingUtcDelta), max(recordingUtcDelta)); ...
    sprintf("- Wrapper overhead range: `%d` to `%d` bytes", ...
        min(wrapperOverhead), max(wrapperOverhead)); ...
    sprintf("- Seam boundaries checked: `%d`", height(seamTable)); ...
    sprintf("- Inventory reconciled: `%d`", passFlags.InventoryReconciled); ...
    sprintf("- Decode contract confirmed: `%d`", ...
        passFlags.DecodeContractConfirmed); ...
    sprintf("- Timing model frozen: `%d`", passFlags.TimingModelFrozen); ...
    sprintf("- CPI segmentation frozen: `%d`", ...
        passFlags.CpiSegmentationFrozen); ...
    ""; ...
    "## Evidence Files"; ...
    "- `manifest_vs_observed.csv`"; ...
    "- `radar_metadata_scan.csv`"; ...
    "- `seam_continuity_summary.csv`"; ...
    "- `capture_provenance_interpretation_summary.md`"; ...
    "- `decode_contract_summary.md`"; ...
    "- `timing_contract_note.md`"; ...
    "- `cpi_segmentation_contract_summary.md`"; ...
    "- `decision.txt`"; ...
    "- `requirements_coverage.csv`"; ...
    "- `metrics.json`"; ...
    "- `metrics.mat`" ...
    ];

if readerContract.RawFreadFallbackUsed
    summaryLines = [ ...
        summaryLines(1:19); ...
        sprintf("- Preferred native reader failure category: `%s`", ...
        failureCategory); ...
        sprintf("- Preferred native reader failure reason: `%s`", ...
        failureMessage); ...
        summaryLines(20:end) ...
        ];
end

end

function lines = localBuildCaptureProvenanceLines(manifest, radarScans, ...
    readerContract)

recordingUtcDatetime = datetime([radarScans.RecordingUTC], ...
    "ConvertFrom", "posixtime", "TimeZone", "UTC");
recordingUtcDatetime.TimeZone = "America/New_York";

if readerContract.RawFreadFallbackUsed
    decodePathLines = [ ...
        sprintf("- The preferred native reader `%s` was attempted first but could not be used because: `%s`.", ...
        readerContract.PreferredReader, localJoinStringValues( ...
        readerContract.NativeReaderFailureMessage)); ...
        sprintf("- The dual-channel contract is preserved by a calibrated raw fallback that decodes the embedded `BasebandVer2.0.0` wrapper into an `[N x 2]` complex `int16` matrix with payload packing `%s`.", ...
        localJoinStringValues(readerContract.PayloadPacking)) ...
        ];
else
    decodePathLines = ...
        "- The dual-channel contract is preserved natively by `comm.BasebandFileReader` as a two-column complex matrix.";
end

lines = [ ...
    "# Capture Provenance Interpretation Summary"; ...
    ""; ...
    "- The observed radar files match the documented `comm.BasebandFileWriter` provenance."; ...
    "- Each radar file is treated as one capture repetition, not as a shard of a default continuous recording."; ...
    "- The embedded metadata records `Repetition`, `RecordingUTC`, and `DateTime` before the file writer is opened for that repetition."; ...
    decodePathLines; ...
    sprintf("- The first repetition anchor `%s` matches the manifest `radar_epoch_utc` within tolerance.", ...
        string(recordingUtcDatetime(1))); ...
    sprintf("- The manifest declares `%d` repetitions and `%d` radar files were decoded successfully.", ...
        manifest.capture_repetitions, numel(radarScans)); ...
    "- The larger wall-clock gaps between files are interpreted as repetition-level capture timing, including capture blocking time, file-writer overhead, and the requested pause between repetitions." ...
    ];

end

function lines = localBuildDecodeContractLines(radarScans, readerContract)

decodeSummary = localBuildDecodeSummaryStruct(radarScans, readerContract);
chosenReader = localJoinStringValues(readerContract.Reader);
payloadPacking = localJoinStringValues(readerContract.PayloadPacking);

if readerContract.RawFreadFallbackUsed
    lines = [ ...
        "# Decode Contract Summary"; ...
        ""; ...
        sprintf("- Preferred decode path: `%s`.", readerContract.PreferredReader); ...
        sprintf("- Chosen decode path: `%s`.", chosenReader); ...
        sprintf("- Native path failure category: `%s`.", ...
        localJoinStringValues(readerContract.NativeReaderFailureCategory)); ...
        sprintf("- Native path failure reason: `%s`.", ...
        localJoinStringValues(readerContract.NativeReaderFailureMessage)); ...
        "- The raw fallback is used only because the preferred native reader could not open the files in the current environment."; ...
        "- The fallback scans the embedded `BasebandVer2.0.0` wrapper directly, extracts the textual metadata block, and decodes the payload as complex `int16`."; ...
        sprintf("- Raw payload packing is frozen as `%s`.", ...
        payloadPacking); ...
        sprintf("- The observed payload offset range is `%d` to `%d` bytes from file start, which matches the wrapper-overhead range.", ...
        readerContract.PayloadOffsetBytes(1), ...
        readerContract.PayloadOffsetBytes(end)); ...
        "- Header scalar calibration is frozen as: bytes `21:28` = sample rate `double`, bytes `29:32` = data-type code `1 -> int16`, bytes `33:36` = complex flag `1`, and bytes `37:44` = center frequency `double`."; ...
        sprintf("- Canonical decoded representation remains one repetition per file as an `[N x 2]` complex `int16` matrix where `N = %d` samples.", ...
        radarScans(1).NumSamples); ...
        sprintf("- Column order is frozen as column 1 = `%s`, column 2 = `%s`, based on embedded `Antenna1`/`Antenna2` metadata and the decoded two-channel payload.", ...
        radarScans(1).Antenna1, radarScans(1).Antenna2); ...
        ""; ...
        "## Observed Decode Contract"; ...
        localStructDisplayLines(decodeSummary) ...
        ];
else
    lines = [ ...
        "# Decode Contract Summary"; ...
        ""; ...
        sprintf("- Preferred decode path: `%s`.", readerContract.PreferredReader); ...
        sprintf("- Chosen decode path: `%s`.", chosenReader); ...
        "- Raw `fread` fallback was not used because the native reader opened all files, exposed embedded metadata, and reproduced the expected sample and channel counts consistently."; ...
        sprintf("- Canonical decoded representation is one repetition per file as an `[N x 2]` complex `int16` matrix where `N = %d` samples.", ...
        radarScans(1).NumSamples); ...
        sprintf("- Column order is frozen as column 1 = `%s`, column 2 = `%s`, based on embedded `Antenna1`/`Antenna2` metadata and the presence of two distinct loaded channels in every file.", ...
        radarScans(1).Antenna1, radarScans(1).Antenna2); ...
        ""; ...
        "## Observed Decode Contract"; ...
        localStructDisplayLines(decodeSummary) ...
        ];
end

end

function lines = localBuildTimingContractLines(manifest, radarScans)

recordingUtcVector = [radarScans.RecordingUTC].';
recordingUtcDelta = diff(recordingUtcVector);
sampleSpanBoundaryVector = [radarScans(1:end - 1).SampleSpan_s].';
wallClockMinusSampleSpan = recordingUtcDelta - sampleSpanBoundaryVector;
wallClockMinusSampleSpanAndRequestedSpacing = wallClockMinusSampleSpan - ...
    manifest.capture_repetition_spacing_s;
dateTimeVsRecordingMs = [radarScans.DateTimeVsRecording_ms].';

lines = [ ...
    "# Timing Contract Note"; ...
    ""; ...
    sprintf("- Manifest `capture_duration_s` = `%.6f s`.", ...
        manifest.capture_duration_s); ...
    sprintf("- Observed sample span per file = `%.6f s` from `NumSamples / SampleRate`.", ...
        radarScans(1).SampleSpan_s); ...
    sprintf("- Manifest `capture_repetition_spacing_s` = `%.6f s` is treated as requested pause spacing, not as the expected embedded header delta.", ...
        manifest.capture_repetition_spacing_s); ...
    sprintf("- Embedded `RecordingUTC` boundary deltas range from `%.6f s` to `%.6f s`.", ...
        min(recordingUtcDelta), max(recordingUtcDelta)); ...
    sprintf("- Boundary delta minus sample span ranges from `%.6f s` to `%.6f s`.", ...
        min(wallClockMinusSampleSpan), max(wallClockMinusSampleSpan)); ...
    sprintf("- Boundary delta minus `(sample span + manifest repetition spacing)` ranges from `%.6f s` to `%.6f s`.", ...
        min(wallClockMinusSampleSpanAndRequestedSpacing), ...
        max(wallClockMinusSampleSpanAndRequestedSpacing)); ...
    sprintf("- Embedded `DateTime` corroborates `RecordingUTC` within `%.3f ms` max absolute difference.", ...
        max(abs(dateTimeVsRecordingMs))); ...
    sprintf("- Manifest `radar_epoch_utc` differs from repetition 1 `RecordingUTC` by `%.6f s`.", ...
        abs(manifest.radar_epoch_utc - radarScans(1).RecordingUTC)); ...
    "- Authoritative downstream radar time base is frozen as the per-file `RecordingUTC` repetition anchor sequence, with embedded `DateTime` as corroboration."; ...
    "- `radar_epoch_utc` is treated as the session first-repetition anchor because it matches repetition 1 `RecordingUTC` within tolerance."; ...
    "- The positive residual after subtracting `(sample span + requested repetition spacing)` is interpreted as capture-loop and file-writer overhead, not as a seam defect."; ...
    "- The timing contract explicitly separates per-file sample-span time from inter-file wall-clock repetition timing. Inter-file wall-clock gaps are not treated as seam defects by default." ...
    ];

end

function lines = localBuildCpiContractLines(radarScans)

lines = [ ...
    "# CPI Segmentation Contract Summary"; ...
    ""; ...
    "- CPI segmentation is frozen as intra-file only by default."; ...
    "- Each radar file is one repetition boundary and no CPI may start in one file and continue into the next file unless a later gate explicitly reopens G1 and justifies cross-file integration."; ...
    sprintf("- For any future CPI length `L`, allowable 1-based window starts within repetition `r` are `1` through `N-L+1`, where `N = %d` samples for this dataset.", ...
        radarScans(1).NumSamples); ...
    "- Overlap is permitted only when the entire overlapped window remains inside a single repetition."; ...
    "- Downstream G4/G6 work may choose CPI length and overlap, but not reinterpret repetition seams." ...
    ];

end

function decodeSummary = localBuildDecodeSummaryStruct(radarScans, ...
    readerContract)

decodeSummary = struct();
decodeSummary.PreferredReader = readerContract.PreferredReader;
decodeSummary.Reader = readerContract.Reader;
decodeSummary.RawFreadFallbackUsed = readerContract.RawFreadFallbackUsed;
decodeSummary.FileCount = numel(radarScans);
decodeSummary.NumSamplesPerFile = unique([radarScans.NumSamples].');
decodeSummary.NumChannels = unique([radarScans.NumChannels].');
decodeSummary.DataType = unique(string({radarScans.DataType}).');
decodeSummary.ComplexMatrix = all([radarScans.IsComplex].');
decodeSummary.Channel1Label = unique(string({radarScans.Antenna1}).');
decodeSummary.Channel2Label = unique(string({radarScans.Antenna2}).');
decodeSummary.SampleRateHz = unique([radarScans.SampleRate].');
decodeSummary.CenterFrequencyHz = unique([radarScans.CenterFrequency].');
decodeSummary.PayloadBytes = unique([radarScans.PayloadBytes].');
decodeSummary.PayloadOffsetBytes = readerContract.PayloadOffsetBytes;
decodeSummary.WrapperOverheadBytes = [ ...
    min([radarScans.WrapperOverheadBytes].'), ...
    max([radarScans.WrapperOverheadBytes].') ...
    ];
decodeSummary.MetadataSource = readerContract.MetadataSource;

if readerContract.RawFreadFallbackUsed
    decodeSummary.NativeReaderFailureCategory = ...
        localJoinStringValues(readerContract.NativeReaderFailureCategory);
    decodeSummary.NativeReaderFailureMessage = ...
        localJoinStringValues(readerContract.NativeReaderFailureMessage);
    decodeSummary.HeaderVersion = ...
        localJoinStringValues(readerContract.HeaderVersion);
    decodeSummary.PayloadPacking = ...
        localJoinStringValues(readerContract.PayloadPacking);
end

end

function configSnapshot = localBuildConfigSnapshot(manifest, datasetId, gateId, ...
    repoRoot, bundleRoot, runTimestampZ, sessionData)

configSnapshot = struct();
configSnapshot.dataset_id = datasetId;
configSnapshot.gate_id = gateId;
configSnapshot.run_timestamp_z = runTimestampZ;
configSnapshot.entry_point = "runG1Ingest";
configSnapshot.repo_root = repoRoot;
configSnapshot.bundle_root = string(bundleRoot);
configSnapshot.native_reader = sessionData.NativeReaderContract.PreferredReader;
configSnapshot.chosen_decode_path = sessionData.NativeReaderContract.Reader;
configSnapshot.raw_fread_fallback_used = ...
    sessionData.NativeReaderContract.RawFreadFallbackUsed;
configSnapshot.raw_fread_fallback_reason = ...
    sessionData.NativeReaderContract.RawFreadFallbackReason;
configSnapshot.native_reader_failure_category = ...
    sessionData.NativeReaderContract.NativeReaderFailureCategory;
configSnapshot.native_reader_failure_identifier = ...
    sessionData.NativeReaderContract.NativeReaderFailureIdentifier;
configSnapshot.native_reader_failure_message = ...
    sessionData.NativeReaderContract.NativeReaderFailureMessage;
configSnapshot.payload_offset_bytes = ...
    sessionData.NativeReaderContract.PayloadOffsetBytes;
configSnapshot.payload_packing = ...
    sessionData.NativeReaderContract.PayloadPacking;
configSnapshot.iq_loader_entry_point = "loadIQData";
configSnapshot.iq_loader_include_samples = ...
    sessionData.NativeReaderContract.LoadedSamplesIntoMemory;
configSnapshot.capture_duration_s = manifest.capture_duration_s;
configSnapshot.capture_repetition_spacing_s = ...
    manifest.capture_repetition_spacing_s;
configSnapshot.sample_rate_hz = manifest.sdr_defaults.sample_rate_hz;
configSnapshot.center_frequency_hz = ...
    manifest.sdr_defaults.center_frequency_hz;
configSnapshot.matlab_version = string(version);
configSnapshot.matlab_release = string(version("-release"));
configSnapshot.computer = string(computer);

end

function metrics = localBuildMetrics(manifest, manifestTable, radarScans, ...
    seamTable, passFlags, decision, nextBranch, readerContract)

requiredRows = manifestTable.RequiredByManifest;
recordingUtcVector = [radarScans.RecordingUTC].';
recordingUtcDelta = diff(recordingUtcVector);
sampleSpanVector = [radarScans.SampleSpan_s].';
channelPowerRatioDb = 10 * log10([radarScans.MeanPowerCh1].' ./ ...
    [radarScans.MeanPowerCh2].');

metrics = struct();
metrics.dataset_id = string(manifest.session_id);
metrics.gate_id = "G1_Ingest";
metrics.decision = decision;
metrics.next_branch = nextBranch;
metrics.pass_flags = passFlags;

metrics.manifest_inputs = struct();
metrics.manifest_inputs.session_id = string(manifest.session_id);
metrics.manifest_inputs.session_folder = string(manifest.session_folder);
metrics.manifest_inputs.session_created_utc = ...
    string(manifest.session_created_utc);
metrics.manifest_inputs.capture_duration_s = manifest.capture_duration_s;
metrics.manifest_inputs.capture_repetitions = ...
    manifest.capture_repetitions;
metrics.manifest_inputs.capture_repetition_spacing_s = ...
    manifest.capture_repetition_spacing_s;
metrics.manifest_inputs.radar_active_window_s = ...
    manifest.radar_active_window_s;
metrics.manifest_inputs.radar_recorded_iq_seconds_s = ...
    manifest.radar_recorded_iq_seconds_s;
metrics.manifest_inputs.lead_seconds_s = manifest.lead_seconds_s;
metrics.manifest_inputs.tail_seconds_s = manifest.tail_seconds_s;
metrics.manifest_inputs.adsb_target_window_s = ...
    manifest.adsb_target_window_s;
metrics.manifest_inputs.adsb_run_seconds_s = manifest.adsb_run_seconds_s;
metrics.manifest_inputs.adsb_stop_mode = string(manifest.adsb_stop_mode);
metrics.manifest_inputs.capture_file_base = ...
    string(manifest.capture_file_base);
metrics.manifest_inputs.gain_spec = string(manifest.gain_spec);
metrics.manifest_inputs.pi_host = string(manifest.pi_host);
metrics.manifest_inputs.remote_log_file = ...
    string(manifest.remote_log_file);
metrics.manifest_inputs.radar_epoch_utc = manifest.radar_epoch_utc;
metrics.manifest_inputs.radio_name = ...
    string(manifest.sdr_defaults.radio_name);
metrics.manifest_inputs.center_frequency_hz = ...
    manifest.sdr_defaults.center_frequency_hz;
metrics.manifest_inputs.sample_rate_hz = ...
    manifest.sdr_defaults.sample_rate_hz;
metrics.manifest_inputs.lo_offset_hz = ...
    manifest.sdr_defaults.lo_offset_hz;
metrics.manifest_inputs.radar_file_count = numel(manifest.radar_files);
metrics.manifest_inputs.adsb_file_count = numel(manifest.adsb_files);
metrics.manifest_inputs.log_file_count = numel(manifest.log_files);

metrics.inventory = struct();
metrics.inventory.required_manifest_files = nnz(requiredRows);
metrics.inventory.required_present_files = ...
    nnz(requiredRows & manifestTable.Observed);
metrics.inventory.missing_required_files = ...
    nnz(requiredRows & ~manifestTable.Observed);
metrics.inventory.unexpected_extra_source_artifacts = ...
    nnz(manifestTable.Status == "unexpected_extra_source_artifact");
metrics.inventory.local_support_artifacts = ...
    nnz(manifestTable.Status == "local_support_nonblocking");

metrics.decode_contract = struct();
metrics.decode_contract.preferred_reader = readerContract.PreferredReader;
metrics.decode_contract.reader = readerContract.Reader;
metrics.decode_contract.raw_fread_fallback_used = ...
    readerContract.RawFreadFallbackUsed;
metrics.decode_contract.native_reader_failure_category = ...
    readerContract.NativeReaderFailureCategory;
metrics.decode_contract.native_reader_failure_message = ...
    readerContract.NativeReaderFailureMessage;
metrics.decode_contract.file_count = numel(radarScans);
metrics.decode_contract.num_samples_per_file = unique([radarScans.NumSamples].');
metrics.decode_contract.num_channels = unique([radarScans.NumChannels].');
metrics.decode_contract.data_type = unique(string({radarScans.DataType}).');
metrics.decode_contract.is_complex = all([radarScans.IsComplex].');
metrics.decode_contract.payload_offset_bytes_min = ...
    readerContract.PayloadOffsetBytes(1);
metrics.decode_contract.payload_offset_bytes_max = ...
    readerContract.PayloadOffsetBytes(end);
metrics.decode_contract.payload_packing = readerContract.PayloadPacking;
metrics.decode_contract.wrapper_overhead_bytes_min = ...
    min([radarScans.WrapperOverheadBytes].');
metrics.decode_contract.wrapper_overhead_bytes_max = ...
    max([radarScans.WrapperOverheadBytes].');

metrics.channel_contract = struct();
metrics.channel_contract.channel_1_label = unique(string({radarScans.Antenna1}).');
metrics.channel_contract.channel_2_label = unique(string({radarScans.Antenna2}).');
metrics.channel_contract.channel_power_delta_db_min = min(channelPowerRatioDb);
metrics.channel_contract.channel_power_delta_db_max = max(channelPowerRatioDb);
metrics.channel_contract.channel_correlation_magnitude_min = ...
    min([radarScans.ChannelCorrelationMagnitude].');
metrics.channel_contract.channel_correlation_magnitude_max = ...
    max([radarScans.ChannelCorrelationMagnitude].');

metrics.timing = struct();
metrics.timing.sample_span_s = unique(sampleSpanVector);
metrics.timing.manifest_capture_duration_s = manifest.capture_duration_s;
metrics.timing.manifest_capture_repetition_spacing_s = ...
    manifest.capture_repetition_spacing_s;
metrics.timing.recording_utc_delta_s_min = min(recordingUtcDelta);
metrics.timing.recording_utc_delta_s_max = max(recordingUtcDelta);
metrics.timing.recording_utc_delta_s_median = median(recordingUtcDelta);
metrics.timing.wall_clock_minus_sample_span_s_min = ...
    min(recordingUtcDelta - sampleSpanVector(1:end - 1));
metrics.timing.wall_clock_minus_sample_span_s_max = ...
    max(recordingUtcDelta - sampleSpanVector(1:end - 1));
metrics.timing.wall_clock_minus_sample_span_and_requested_spacing_s_min = ...
    min(recordingUtcDelta - sampleSpanVector(1:end - 1) - ...
    manifest.capture_repetition_spacing_s);
metrics.timing.wall_clock_minus_sample_span_and_requested_spacing_s_max = ...
    max(recordingUtcDelta - sampleSpanVector(1:end - 1) - ...
    manifest.capture_repetition_spacing_s);
metrics.timing.max_datetime_vs_recording_ms = ...
    max(abs([radarScans.DateTimeVsRecording_ms].'));
metrics.timing.radar_epoch_minus_first_recording_s = ...
    manifest.radar_epoch_utc - radarScans(1).RecordingUTC;
metrics.timing.authoritative_radar_time_base = ...
    "per-file RecordingUTC repetition anchors";
metrics.timing.radar_epoch_role = ...
    "session first-repetition anchor";

metrics.seam = struct();
metrics.seam.boundary_count = height(seamTable);
metrics.seam.ok_gap_expected_count = nnz(seamTable.Status == "ok_gap_expected");
metrics.seam.warning_count = nnz(startsWith(seamTable.Status, "warning"));
metrics.seam.defect_count = nnz(startsWith(seamTable.Status, "defect"));
metrics.seam.edge_exact_duplicate_count_max = ...
    max([0; seamTable.EdgeExactDuplicateCount]);

metrics.cpi_contract = struct();
metrics.cpi_contract.segmentation_scope = "intra-file only";
metrics.cpi_contract.cross_file_allowed = false;
metrics.cpi_contract.contract_status = "frozen_in_G1";

end

function comparisonSnapshot = localBuildComparisonSnapshot(datasetId, ...
    gateId, runTimestampZ, bundleRoot, decision, nextBranch, passFlags, ...
    metrics)

gainOrderingLines = helperBuildG1GainSpecOrderingLines(metrics);
gainOrderingText = localJoinComparisonTokens(gainOrderingLines);
timingModelSummary = metrics.timing.authoritative_radar_time_base + ...
    sprintf(" | median repetition delta %.6f s", ...
    metrics.timing.recording_utc_delta_s_median);
cpiSegmentationSummary = metrics.cpi_contract.segmentation_scope + ...
    " | status " + metrics.cpi_contract.contract_status;
summaryTable = localBuildComparisonSummaryTable(decision, nextBranch, ...
    passFlags, metrics, gainOrderingText, timingModelSummary, ...
    cpiSegmentationSummary);

comparisonSnapshot = struct();
comparisonSnapshot.DatasetId = string(datasetId);
comparisonSnapshot.StageId = string(gateId);
comparisonSnapshot.RunTimestampZ = string(runTimestampZ);
comparisonSnapshot.BundleRoot = string(bundleRoot);
comparisonSnapshot.Decision = string(decision);
comparisonSnapshot.NextBranch = string(nextBranch);
comparisonSnapshot.Channel1Labels = string( ...
    metrics.channel_contract.channel_1_label);
comparisonSnapshot.Channel2Labels = string( ...
    metrics.channel_contract.channel_2_label);
comparisonSnapshot.Channel1LabelSummary = localJoinComparisonTokens( ...
    metrics.channel_contract.channel_1_label);
comparisonSnapshot.Channel2LabelSummary = localJoinComparisonTokens( ...
    metrics.channel_contract.channel_2_label);
comparisonSnapshot.ManifestGainSpec = string(metrics.manifest_inputs.gain_spec);
comparisonSnapshot.GainOrderingText = gainOrderingText;
comparisonSnapshot.GainOrderingLines = gainOrderingLines(:);
comparisonSnapshot.TimingModelSummary = timingModelSummary;
comparisonSnapshot.CpiSegmentationSummary = cpiSegmentationSummary;
comparisonSnapshot.PassFlags = passFlags;
comparisonSnapshot.SummaryTable = summaryTable;

end

function summaryTable = localBuildComparisonSummaryTable(decision, ...
    nextBranch, passFlags, metrics, gainOrderingText, timingModelSummary, ...
    cpiSegmentationSummary)

rows = [ ...
    helperMakeComparisonMetricRow("decision", "Decision", decision, "", ...
    "G1 gate decision for this single-session baseline review."); ...
    helperMakeComparisonMetricRow("next_branch", "Next Branch", ...
    nextBranch, "", "Downstream branch emitted by G1."); ...
    helperMakeComparisonMetricRow("inventory_reconciled", ...
    "Inventory Reconciled", passFlags.InventoryReconciled, "", ...
    "True when required manifest files reconcile cleanly."); ...
    helperMakeComparisonMetricRow("decode_contract_confirmed", ...
    "Decode Contract Confirmed", ...
    passFlags.DecodeContractConfirmed, "", ...
    "True when the decode contract remains stable across the session."); ...
    helperMakeComparisonMetricRow("channel_contract_confirmed", ...
    "Channel Contract Confirmed", ...
    passFlags.ChannelContractConfirmed, "", ...
    "True when the decoded channel labels match the frozen contract."); ...
    helperMakeComparisonMetricRow("timing_model_frozen", ...
    "Timing Model Frozen", passFlags.TimingModelFrozen, "", ...
    "True when the inherited timing model still holds."); ...
    helperMakeComparisonMetricRow("seam_checks_passed", ...
    "Seam Checks Passed", passFlags.SeamChecksPassed, "", ...
    "True when file-boundary seam checks stay within the G1 contract."); ...
    helperMakeComparisonMetricRow("cpi_segmentation_frozen", ...
    "CPI Segmentation Frozen", passFlags.CpiSegmentationFrozen, "", ...
    "True when CPI segmentation remains frozen in G1."); ...
    helperMakeComparisonMetricRow("missing_required_files", ...
    "Missing Required Files", metrics.inventory.missing_required_files, ...
    "count", "Required manifest files missing from the source tree."); ...
    helperMakeComparisonMetricRow( ...
    "unexpected_extra_source_artifacts", ...
    "Unexpected Extra Source Artifacts", ...
    metrics.inventory.unexpected_extra_source_artifacts, "count", ...
    "Unexpected artifacts found alongside the required source set."); ...
    helperMakeComparisonMetricRow("channel_1_label", "Channel 1 Labels", ...
    localJoinComparisonTokens(metrics.channel_contract.channel_1_label), ...
    "", "Decoded label summary for channel 1."); ...
    helperMakeComparisonMetricRow("channel_2_label", "Channel 2 Labels", ...
    localJoinComparisonTokens(metrics.channel_contract.channel_2_label), ...
    "", "Decoded label summary for channel 2."); ...
    helperMakeComparisonMetricRow("manifest_gain_spec", ...
    "Manifest Gain Spec", metrics.manifest_inputs.gain_spec, "dB", ...
    "Manifest gain text preserved in the decoded channel order."); ...
    helperMakeComparisonMetricRow("gain_ordering_text", ...
    "Manifest-Derived Gain Ordering", gainOrderingText, "", ...
    "Decoded channel-to-gain mapping used during baseline review."); ...
    helperMakeComparisonMetricRow("timing_model_summary", ...
    "Timing Model Summary", timingModelSummary, "", ...
    "Compact timing summary for artifact-only comparison."); ...
    helperMakeComparisonMetricRow("recording_utc_delta_median_s", ...
    "Recording UTC Delta Median", ...
    metrics.timing.recording_utc_delta_s_median, "s", ...
    "Median repetition spacing from embedded RecordingUTC headers."); ...
    helperMakeComparisonMetricRow("wall_clock_minus_span_min_s", ...
    "Wall Clock Minus Sample Span Min", ...
    metrics.timing.wall_clock_minus_sample_span_s_min, "s", ...
    "Minimum gap between wall-clock repetition anchors and sample span."); ...
    helperMakeComparisonMetricRow("wall_clock_minus_span_max_s", ...
    "Wall Clock Minus Sample Span Max", ...
    metrics.timing.wall_clock_minus_sample_span_s_max, "s", ...
    "Maximum gap between wall-clock repetition anchors and sample span."); ...
    helperMakeComparisonMetricRow( ...
    "wall_clock_minus_span_and_spacing_min_s", ...
    "Wall Clock Minus Span and Requested Spacing Min", ...
    metrics.timing.wall_clock_minus_sample_span_and_requested_spacing_s_min, ...
    "s", ...
    "Minimum residual after subtracting sample span and manifest spacing."); ...
    helperMakeComparisonMetricRow( ...
    "wall_clock_minus_span_and_spacing_max_s", ...
    "Wall Clock Minus Span and Requested Spacing Max", ...
    metrics.timing.wall_clock_minus_sample_span_and_requested_spacing_s_max, ...
    "s", ...
    "Maximum residual after subtracting sample span and manifest spacing."); ...
    helperMakeComparisonMetricRow("cpi_segmentation_summary", ...
    "CPI Segmentation Summary", cpiSegmentationSummary, "", ...
    "Compact CPI-contract summary for artifact-only comparison."); ...
    helperMakeComparisonMetricRow("channel_power_delta_db_min", ...
    "Channel Power Delta Min", ...
    metrics.channel_contract.channel_power_delta_db_min, "dB", ...
    "Minimum channel-1 minus channel-2 mean-power delta."); ...
    helperMakeComparisonMetricRow("channel_power_delta_db_max", ...
    "Channel Power Delta Max", ...
    metrics.channel_contract.channel_power_delta_db_max, "dB", ...
    "Maximum channel-1 minus channel-2 mean-power delta.") ...
    ];

summaryTable = struct2table(rows);
summaryTable.DisplayOrder = (1:height(summaryTable)).';

end

function joinedText = localJoinComparisonTokens(values)

tokens = string(values(:));
tokens = strtrim(tokens);
tokens = tokens(strlength(tokens) > 0);

if isempty(tokens)
    joinedText = "";
    return
end

joinedText = strjoin(tokens, " | ");

end

function lines = localStructDisplayLines(inputStruct)

localValue = inputStruct;
displayText = evalc("disp(localValue)");
displayText = strtrim(string(displayText));
lines = splitlines(displayText);
lines = lines(strlength(lines) > 0);

end

function lines = localTableDisplayLines(inputTable)

localValue = inputTable;
displayText = evalc("disp(localValue)");
displayText = strtrim(string(displayText));
lines = splitlines(displayText);
lines = lines(strlength(lines) > 0);

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return;
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG1Ingest:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

try
    fileIdentifier = fopen(filePath, "w");
catch openException
    error("runG1Ingest:OpenTextFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        openException.message);
end

if fileIdentifier == -1
    error("runG1Ingest:OpenTextFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileIdentifier));
lines = string(lines);

for idx = 1:numel(lines)
    fprintf(fileIdentifier, "%s\n", lines(idx));
end

clear cleanupObject

end

function localWriteJsonFile(filePath, inputStruct)

try
    jsonText = jsonencode(inputStruct, PrettyPrint = true);
catch encodeException
    error("runG1Ingest:JsonEncodeFailed", ...
        "Failed to encode JSON for %s: %s", filePath, ...
        encodeException.message);
end

localWriteTextFile(filePath, jsonText);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return;
end

if ~isfolder(bundleRoot)
    try
        mkdir(bundleRoot);
    catch
        return;
    end
end

try
    localWriteTextFile(fullfile(bundleRoot, "decision.txt"), "reject");
    localWriteTextFile(fullfile(bundleRoot, "failure_cause.txt"), ...
        "Unhandled G1 ingest execution failure.");
    localWriteTextFile(fullfile(bundleRoot, "next_branch.txt"), ...
        "Fix G1 execution failure before rerunning.");
    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G1 Ingest Summary"; ...
        ""; ...
        "- Decision: `reject`"; ...
        sprintf("- Failure message: `%s`", mainException.message) ...
        ]);
catch
end

end

function lines = localBuildDecodeFigureLines(radarScans, readerContract)

lines = [ ...
    sprintf("Chosen reader contract: %s", ...
    localJoinStringValues(readerContract.Reader)); ...
    sprintf("Fallback raw fread used: %s", ...
    localLogicalWord(readerContract.RawFreadFallbackUsed)) ...
    ];

if readerContract.RawFreadFallbackUsed
    lines = [ ...
        lines; ...
        sprintf("Native reader failure: %s", ...
        localJoinStringValues(readerContract.NativeReaderFailureMessage)) ...
        ];
end

lines = [ ...
    lines; ...
    ""; ...
    localStructDisplayLines(localBuildDecodeSummaryStruct(radarScans, ...
    readerContract)) ...
    ];

end

function text = localJoinStringValues(values)

values = unique(string(values));
values = regexprep(values, "\s+", " ");
values = strtrim(values);
values = values(strlength(values) > 0);

if isempty(values)
    text = "";
else
    text = join(values, " | ");
    text = text(1);
end

end

function text = localLogicalWord(value)

if value
    text = "yes";
else
    text = "no";
end

end
