function results = runG1G2SessionComparison(baselineDatasetId, ...
    candidateDatasetId, repoRoot, options)
%RUNG1G2SESSIONCOMPARISON Compare saved G1 and G2 artifacts across sessions.
%
%   RESULTS = RUNG1G2SESSIONCOMPARISON(BASELINE, CANDIDATE) loads the
%   latest comparison_snapshot.mat artifacts for G1, G2 Stage 1, and G2
%   Stage 2 from the baseline and candidate sessions, then writes a
%   hardware-iteration comparison bundle under:
%   artifacts/comparisons/<baseline>_vs_<candidate>/<runTimestampZ>/
%
%   This runner is artifact-only. It never re-runs single-session analysis.

arguments
    baselineDatasetId (1,1) string = "20260622T102123"
    candidateDatasetId (1,1) string = ""
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

repoRoot = helperResolveRepoRoot(repoRoot);
baselineDatasetId = string(baselineDatasetId);
candidateDatasetId = string(candidateDatasetId);

if strlength(strtrim(candidateDatasetId)) == 0
    error("runG1G2SessionComparison:MissingCandidateDatasetId", ...
        "Candidate dataset ID is required. Call " + ...
        "runG1G2SessionComparison(""20260622T102123"", " + ...
        """<candidateDatasetId>"", ...).");
end

runnerOptions = localResolveRunnerOptions(options);
runTimestampZ = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
comparisonId = baselineDatasetId + "_vs_" + candidateDatasetId;
bundleRoot = fullfile(repoRoot, "artifacts", "comparisons", ...
    comparisonId, runTimestampZ);
figureRoot = fullfile(bundleRoot, "figures");

fprintf("Running G1/G2 artifact-only session comparison\n");
fprintf("Baseline dataset:\t%s\n", baselineDatasetId);
fprintf("Candidate dataset:\t%s\n", candidateDatasetId);
fprintf("Repository root:\t%s\n", repoRoot);

try
    localEnsureFolder(bundleRoot);
    localEnsureFolder(figureRoot);

    baselineSnapshots = localLoadSnapshotSet(baselineDatasetId, repoRoot);
    candidateSnapshots = localLoadSnapshotSet(candidateDatasetId, repoRoot);

    overallSummaryTable = localBuildOverallSummaryTable( ...
        baselineSnapshots, candidateSnapshots, bundleRoot);
    g1ComparisonTable = localBuildStageComparisonTable( ...
        baselineSnapshots.G1, candidateSnapshots.G1);
    g2Stage1ComparisonTable = localBuildStageComparisonTable( ...
        baselineSnapshots.G2Stage1, candidateSnapshots.G2Stage1);
    g2Stage2ComparisonTable = localBuildStageComparisonTable( ...
        baselineSnapshots.G2Stage2, candidateSnapshots.G2Stage2);

    summaryLines = localBuildSummaryLines(baselineSnapshots, ...
        candidateSnapshots, bundleRoot, runTimestampZ);
    interpretationNoteLines = localBuildInterpretationNoteLines( ...
        baselineSnapshots, candidateSnapshots);

    sessionSummaryPath = fullfile(bundleRoot, ...
        "session_comparison_summary.csv");
    g1ComparisonPath = fullfile(bundleRoot, "g1_comparison_table.csv");
    g2Stage1ComparisonPath = fullfile(bundleRoot, ...
        "g2_stage1_comparison_table.csv");
    g2Stage2ComparisonPath = fullfile(bundleRoot, ...
        "g2_stage2_comparison_table.csv");
    summaryPath = fullfile(bundleRoot, "summary.md");
    interpretationPath = fullfile(bundleRoot, "interpretation_note.md");
    resultsMatPath = fullfile(bundleRoot, "comparison_results.mat");
    rolePowerFigurePath = fullfile(figureRoot, ...
        "figure_01_stage2_role_power_ordering.png");
    worstMetricsFigurePath = fullfile(figureRoot, ...
        "figure_02_stage2_worst_metrics.png");

    try
        writetable(overallSummaryTable, sessionSummaryPath);
        writetable(g1ComparisonTable, g1ComparisonPath);
        writetable(g2Stage1ComparisonTable, g2Stage1ComparisonPath);
        writetable(g2Stage2ComparisonTable, g2Stage2ComparisonPath);
    catch writeTableException
        error("runG1G2SessionComparison:WriteTableFailed", ...
            "Failed to write a comparison table artifact: %s", ...
            writeTableException.message);
    end

    localWriteTextFile(summaryPath, summaryLines);
    localWriteTextFile(interpretationPath, interpretationNoteLines);

    localRenderStage2RolePowerFigure(baselineSnapshots.G2Stage2, ...
        candidateSnapshots.G2Stage2, rolePowerFigurePath, ...
        runnerOptions.ShowFigures);
    localRenderStage2WorstMetricsFigure(baselineSnapshots.G2Stage2, ...
        candidateSnapshots.G2Stage2, worstMetricsFigurePath, ...
        runnerOptions.ShowFigures);

    results = struct();
    results.BaselineDatasetId = baselineDatasetId;
    results.CandidateDatasetId = candidateDatasetId;
    results.RunTimestampZ = runTimestampZ;
    results.BundleRoot = string(bundleRoot);
    results.BaselineSnapshots = baselineSnapshots;
    results.CandidateSnapshots = candidateSnapshots;
    results.OverallSummaryTable = overallSummaryTable;
    results.G1ComparisonTable = g1ComparisonTable;
    results.G2Stage1ComparisonTable = g2Stage1ComparisonTable;
    results.G2Stage2ComparisonTable = g2Stage2ComparisonTable;
    results.InterpretationNoteLines = interpretationNoteLines;
    results.FigurePaths = [string(rolePowerFigurePath); ...
        string(worstMetricsFigurePath)];

    try
        save(resultsMatPath, "results");
    catch saveException
        error("runG1G2SessionComparison:SaveResultsFailed", ...
            "Failed to write comparison_results.mat: %s", ...
            saveException.message);
    end

    fprintf("Comparison bundle:\t%s\n", bundleRoot);
    fprintf("Stage 2 median reference-minus-surveillance delta:\t%.3f dB\n", ...
        candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB - ...
        baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB);
catch mainException
    localWriteFailureBundle(bundleRoot, mainException);
    rethrow(mainException);
end

end

function runnerOptions = localResolveRunnerOptions(options)

runnerOptions = struct();
runnerOptions.ShowFigures = usejava("desktop");

if isfield(options, "ShowFigures")
    runnerOptions.ShowFigures = logical(options.ShowFigures);
end

end

function snapshotSet = localLoadSnapshotSet(datasetId, repoRoot)

[snapshotSet.G1, snapshotSet.G1SnapshotPath, snapshotSet.G1BundleRoot] = ...
    helperLoadLatestComparisonSnapshot(datasetId, "G1_Ingest", repoRoot);
[snapshotSet.G2Stage1, snapshotSet.G2Stage1SnapshotPath, ...
    snapshotSet.G2Stage1BundleRoot] = helperLoadLatestComparisonSnapshot( ...
    datasetId, "G2_RF_Health_Stage1_AcquisitionEvidence", repoRoot);
[snapshotSet.G2Stage2, snapshotSet.G2Stage2SnapshotPath, ...
    snapshotSet.G2Stage2BundleRoot] = helperLoadLatestComparisonSnapshot( ...
    datasetId, "G2_RF_Health_Stage2_ReceiverIntegrity", repoRoot);

snapshotSet.DatasetId = string(datasetId);

end

function overallSummaryTable = localBuildOverallSummaryTable( ...
    baselineSnapshots, candidateSnapshots, bundleRoot)

stage1MissingRequiredDelta = ...
    candidateSnapshots.G2Stage1.MissingRequiredItemCount - ...
    baselineSnapshots.G2Stage1.MissingRequiredItemCount;
stage1ReferenceFractionDelta = ...
    candidateSnapshots.G2Stage1.ReferenceCandidatePassFraction - ...
    baselineSnapshots.G2Stage1.ReferenceCandidatePassFraction;
stage2PowerMedianDelta = ...
    candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB - ...
    baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB;

overallSummaryTable = table( ...
    baselineSnapshots.DatasetId, ...
    candidateSnapshots.DatasetId, ...
    string(baselineSnapshots.G1.Decision), ...
    string(candidateSnapshots.G1.Decision), ...
    string(baselineSnapshots.G2Stage1.CollectionValidityVerdict), ...
    string(candidateSnapshots.G2Stage1.CollectionValidityVerdict), ...
    string(baselineSnapshots.G2Stage1.AircraftReadinessImpact), ...
    string(candidateSnapshots.G2Stage1.AircraftReadinessImpact), ...
    double(baselineSnapshots.G2Stage1.MissingRequiredItemCount), ...
    double(candidateSnapshots.G2Stage1.MissingRequiredItemCount), ...
    double(stage1MissingRequiredDelta), ...
    double(baselineSnapshots.G2Stage1.ReferenceCandidatePassFraction), ...
    double(candidateSnapshots.G2Stage1.ReferenceCandidatePassFraction), ...
    double(stage1ReferenceFractionDelta), ...
    string(baselineSnapshots.G2Stage2.ReceiverIntegrityVerdict), ...
    string(candidateSnapshots.G2Stage2.ReceiverIntegrityVerdict), ...
    string(baselineSnapshots.G2Stage2.LegalGateRecommendation), ...
    string(candidateSnapshots.G2Stage2.LegalGateRecommendation), ...
    string(baselineSnapshots.G2Stage2.DatasetClassificationRecommendation), ...
    string(candidateSnapshots.G2Stage2.DatasetClassificationRecommendation), ...
    double(baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB), ...
    double(candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB), ...
    double(stage2PowerMedianDelta), ...
    double(baselineSnapshots.G2Stage2.WorstNearRailFraction), ...
    double(candidateSnapshots.G2Stage2.WorstNearRailFraction), ...
    double(baselineSnapshots.G2Stage2.WorstDcSpike_dB), ...
    double(candidateSnapshots.G2Stage2.WorstDcSpike_dB), ...
    double(baselineSnapshots.G2Stage2.WorstIqImpropriety), ...
    double(candidateSnapshots.G2Stage2.WorstIqImpropriety), ...
    string(bundleRoot), ...
    VariableNames = {'BaselineDatasetId', 'CandidateDatasetId', ...
    'BaselineG1Decision', 'CandidateG1Decision', ...
    'BaselineStage1CollectionValidityVerdict', ...
    'CandidateStage1CollectionValidityVerdict', ...
    'BaselineStage1AircraftReadinessImpact', ...
    'CandidateStage1AircraftReadinessImpact', ...
    'BaselineStage1MissingRequiredItemCount', ...
    'CandidateStage1MissingRequiredItemCount', ...
    'Stage1MissingRequiredItemDelta', ...
    'BaselineStage1ReferenceCandidatePassFraction', ...
    'CandidateStage1ReferenceCandidatePassFraction', ...
    'Stage1ReferenceCandidatePassFractionDelta', ...
    'BaselineStage2ReceiverIntegrityVerdict', ...
    'CandidateStage2ReceiverIntegrityVerdict', ...
    'BaselineStage2LegalGateRecommendation', ...
    'CandidateStage2LegalGateRecommendation', ...
    'BaselineStage2DatasetClassificationRecommendation', ...
    'CandidateStage2DatasetClassificationRecommendation', ...
    'BaselineStage2ReferenceMinusSurveillanceMedian_dB', ...
    'CandidateStage2ReferenceMinusSurveillanceMedian_dB', ...
    'Stage2ReferenceMinusSurveillanceMedianDelta_dB', ...
    'BaselineStage2WorstNearRailFraction', ...
    'CandidateStage2WorstNearRailFraction', ...
    'BaselineStage2WorstDcSpike_dB', ...
    'CandidateStage2WorstDcSpike_dB', ...
    'BaselineStage2WorstIqImpropriety', ...
    'CandidateStage2WorstIqImpropriety', 'BundleRoot'});

end

function comparisonTable = localBuildStageComparisonTable(baselineSnapshot, ...
    candidateSnapshot)

baselineTable = localPrepareSummaryTable(baselineSnapshot.SummaryTable);
candidateTable = localPrepareSummaryTable(candidateSnapshot.SummaryTable);

baselineTable = renamevars(baselineTable, ...
    ["MetricLabel", "ValueType", "NumericValue", "TextValue", ...
    "Units", "Notes", "DisplayOrder"], ...
    ["BaselineMetricLabel", "BaselineValueType", ...
    "BaselineNumericValue", "BaselineTextValue", "BaselineUnits", ...
    "BaselineNotes", "BaselineDisplayOrder"]);
candidateTable = renamevars(candidateTable, ...
    ["MetricLabel", "ValueType", "NumericValue", "TextValue", ...
    "Units", "Notes", "DisplayOrder"], ...
    ["CandidateMetricLabel", "CandidateValueType", ...
    "CandidateNumericValue", "CandidateTextValue", "CandidateUnits", ...
    "CandidateNotes", "CandidateDisplayOrder"]);

joinedTable = outerjoin(baselineTable, candidateTable, ...
    "Keys", "MetricId", "MergeKeys", true, "Type", "full");

displayOrder = joinedTable.BaselineDisplayOrder;
missingBaselineOrderMask = isnan(displayOrder);
displayOrder(missingBaselineOrderMask) = ...
    joinedTable.CandidateDisplayOrder(missingBaselineOrderMask);

comparisonTable = table();
comparisonTable.MetricId = string(joinedTable.MetricId);
comparisonTable.MetricLabel = localCoalesceString( ...
    joinedTable.BaselineMetricLabel, joinedTable.CandidateMetricLabel);
comparisonTable.ValueType = localCoalesceString( ...
    joinedTable.BaselineValueType, joinedTable.CandidateValueType);
comparisonTable.Units = localCoalesceString( ...
    joinedTable.BaselineUnits, joinedTable.CandidateUnits);
comparisonTable.BaselineValue = string(joinedTable.BaselineTextValue);
comparisonTable.CandidateValue = string(joinedTable.CandidateTextValue);
comparisonTable.BaselineNumericValue = ...
    double(joinedTable.BaselineNumericValue);
comparisonTable.CandidateNumericValue = ...
    double(joinedTable.CandidateNumericValue);
comparisonTable.NumericDelta = NaN(height(joinedTable), 1);
comparisonTable.ChangeAssessment = localBuildChangeAssessment( ...
    comparisonTable.ValueType, comparisonTable.BaselineValue, ...
    comparisonTable.CandidateValue, ...
    comparisonTable.BaselineNumericValue, ...
    comparisonTable.CandidateNumericValue);
comparisonTable.Notes = localCoalesceString( ...
    joinedTable.BaselineNotes, joinedTable.CandidateNotes);

numericMask = comparisonTable.ValueType == "numeric" | ...
    comparisonTable.ValueType == "logical";
availableDeltaMask = numericMask & ...
    ~isnan(comparisonTable.BaselineNumericValue) & ...
    ~isnan(comparisonTable.CandidateNumericValue);
comparisonTable.NumericDelta(availableDeltaMask) = ...
    comparisonTable.CandidateNumericValue(availableDeltaMask) - ...
    comparisonTable.BaselineNumericValue(availableDeltaMask);

comparisonTable.DisplayOrder = displayOrder;
comparisonTable = sortrows(comparisonTable, "DisplayOrder");
comparisonTable.DisplayOrder = [];

end

function summaryTable = localPrepareSummaryTable(summaryTable)

if ~ismember("DisplayOrder", summaryTable.Properties.VariableNames)
    summaryTable.DisplayOrder = (1:height(summaryTable)).';
end

summaryTable.MetricId = string(summaryTable.MetricId);
summaryTable.MetricLabel = string(summaryTable.MetricLabel);
summaryTable.ValueType = string(summaryTable.ValueType);
summaryTable.NumericValue = double(summaryTable.NumericValue);
summaryTable.TextValue = string(summaryTable.TextValue);
summaryTable.Units = string(summaryTable.Units);
summaryTable.Notes = string(summaryTable.Notes);
summaryTable.DisplayOrder = double(summaryTable.DisplayOrder);

end

function outputValues = localCoalesceString(primaryValues, secondaryValues)

primaryValues = string(primaryValues);
secondaryValues = string(secondaryValues);
outputValues = primaryValues;
emptyMask = strlength(strtrim(outputValues)) == 0;
outputValues(emptyMask) = secondaryValues(emptyMask);

end

function changeAssessment = localBuildChangeAssessment(valueType, ...
    baselineValue, candidateValue, baselineNumericValue, ...
    candidateNumericValue)

rowCount = numel(valueType);
changeAssessment = strings(rowCount, 1);

for idx = 1:rowCount
    if valueType(idx) == "numeric" || valueType(idx) == "logical"
        if isnan(baselineNumericValue(idx)) || isnan(candidateNumericValue(idx))
            changeAssessment(idx) = "n/a";
            continue
        end

        deltaValue = candidateNumericValue(idx) - baselineNumericValue(idx);

        if abs(deltaValue) < 1.0e-12
            changeAssessment(idx) = "unchanged";
        elseif deltaValue > 0.0
            changeAssessment(idx) = "candidate higher";
        else
            changeAssessment(idx) = "candidate lower";
        end

        continue
    end

    if strtrim(baselineValue(idx)) == strtrim(candidateValue(idx))
        changeAssessment(idx) = "matched";
    else
        changeAssessment(idx) = "changed";
    end
end

end

function summaryLines = localBuildSummaryLines(baselineSnapshots, ...
    candidateSnapshots, bundleRoot, runTimestampZ)

stage2MedianDelta = ...
    candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB - ...
    baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB;

summaryLines = [ ...
    "# G1/G2 Session Comparison Summary"; ...
    ""; ...
    "- Scope: artifact-only hardware-change evaluation for G1, G2 Stage 1, and G2 Stage 2"; ...
    "- Entry point: `runG1G2SessionComparison`"; ...
    sprintf("- Baseline dataset: `%s`", baselineSnapshots.DatasetId); ...
    sprintf("- Candidate dataset: `%s`", candidateSnapshots.DatasetId); ...
    sprintf("- Run timestamp: `%s`", runTimestampZ); ...
    sprintf("- Bundle root: `%s`", bundleRoot); ...
    "- Important: this comparison is advisory for hardware iteration only. It does not replace the single-session gate review and does not open later stages automatically."; ...
    ""; ...
    "## Loaded Snapshots"; ...
    sprintf("- Baseline G1 snapshot: `%s`", baselineSnapshots.G1BundleRoot); ...
    sprintf("- Baseline G2 Stage 1 snapshot: `%s`", ...
    baselineSnapshots.G2Stage1BundleRoot); ...
    sprintf("- Baseline G2 Stage 2 snapshot: `%s`", ...
    baselineSnapshots.G2Stage2BundleRoot); ...
    sprintf("- Candidate G1 snapshot: `%s`", ...
    candidateSnapshots.G1BundleRoot); ...
    sprintf("- Candidate G2 Stage 1 snapshot: `%s`", ...
    candidateSnapshots.G2Stage1BundleRoot); ...
    sprintf("- Candidate G2 Stage 2 snapshot: `%s`", ...
    candidateSnapshots.G2Stage2BundleRoot); ...
    ""; ...
    "## High-Signal Summary"; ...
    sprintf("- G1 decisions: baseline `%s`, candidate `%s`.", ...
    baselineSnapshots.G1.Decision, candidateSnapshots.G1.Decision); ...
    sprintf("- Stage 1 collection-validity verdicts: baseline `%s`, candidate `%s`.", ...
    baselineSnapshots.G2Stage1.CollectionValidityVerdict, ...
    candidateSnapshots.G2Stage1.CollectionValidityVerdict); ...
    sprintf("- Stage 2 receiver-integrity verdicts: baseline `%s`, candidate `%s`.", ...
    baselineSnapshots.G2Stage2.ReceiverIntegrityVerdict, ...
    candidateSnapshots.G2Stage2.ReceiverIntegrityVerdict); ...
    sprintf("- Stage 2 reference-minus-surveillance median delta: `%.3f dB` candidate minus baseline.", ...
    stage2MedianDelta); ...
    ""; ...
    "## Output Files"; ...
    "- `session_comparison_summary.csv`"; ...
    "- `g1_comparison_table.csv`"; ...
    "- `g2_stage1_comparison_table.csv`"; ...
    "- `g2_stage2_comparison_table.csv`"; ...
    "- `interpretation_note.md`"; ...
    "- `comparison_results.mat`"; ...
    "- `figures/figure_01_stage2_role_power_ordering.png`"; ...
    "- `figures/figure_02_stage2_worst_metrics.png`" ...
    ];

end

function interpretationNoteLines = localBuildInterpretationNoteLines( ...
    baselineSnapshots, candidateSnapshots)

stage1MissingRequiredDelta = ...
    candidateSnapshots.G2Stage1.MissingRequiredItemCount - ...
    baselineSnapshots.G2Stage1.MissingRequiredItemCount;
stage1ReferenceFractionDelta = ...
    candidateSnapshots.G2Stage1.ReferenceCandidatePassFraction - ...
    baselineSnapshots.G2Stage1.ReferenceCandidatePassFraction;
stage2PowerMedianDelta = ...
    candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB - ...
    baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB;
clippingDelta = candidateSnapshots.G2Stage2.WorstNearRailFraction - ...
    baselineSnapshots.G2Stage2.WorstNearRailFraction;
dcSpikeDelta = candidateSnapshots.G2Stage2.WorstDcSpike_dB - ...
    baselineSnapshots.G2Stage2.WorstDcSpike_dB;
iqImproprietyDelta = ...
    candidateSnapshots.G2Stage2.WorstIqImpropriety - ...
    baselineSnapshots.G2Stage2.WorstIqImpropriety;

interpretationNoteLines = [ ...
    "# Hardware-Iteration Interpretation Note"; ...
    ""; ...
    "- Baseline session: `" + baselineSnapshots.DatasetId + "`."; ...
    "- Candidate session: `" + candidateSnapshots.DatasetId + "`."; ...
    "- This note is for hardware-change evaluation only. It does not replace the single-session G1/G2 review and does not create a new legal gate decision."; ...
    ""; ...
    "## Stage 1 Acquisition Evidence"; ...
    sprintf("- Missing required-item count changed by `%+d`, from `%d` to `%d`.", ...
    stage1MissingRequiredDelta, ...
    baselineSnapshots.G2Stage1.MissingRequiredItemCount, ...
    candidateSnapshots.G2Stage1.MissingRequiredItemCount); ...
    sprintf("- Reference-candidate pass fraction changed by `%+.3f`, from `%.3f` to `%.3f`.", ...
    stage1ReferenceFractionDelta, ...
    baselineSnapshots.G2Stage1.ReferenceCandidatePassFraction, ...
    candidateSnapshots.G2Stage1.ReferenceCandidatePassFraction); ...
    sprintf("- Candidate role-source summary: %s.", ...
    candidateSnapshots.G2Stage1.RoleSourceSummary); ...
    ""; ...
    "## Stage 2 Receiver Integrity"; ...
    sprintf("- Reference-minus-surveillance median power changed by `%+.3f dB`, from `%.3f dB` to `%.3f dB`.", ...
    stage2PowerMedianDelta, ...
    baselineSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB, ...
    candidateSnapshots.G2Stage2.ReferenceMinusSurveillancePowerMedian_dB); ...
    sprintf("- Worst near-rail fraction changed by `%+.6f`, from `%.6f` to `%.6f`.", ...
    clippingDelta, ...
    baselineSnapshots.G2Stage2.WorstNearRailFraction, ...
    candidateSnapshots.G2Stage2.WorstNearRailFraction); ...
    sprintf("- Worst DC spike changed by `%+.3f dB`, from `%.3f dB` to `%.3f dB`.", ...
    dcSpikeDelta, ...
    baselineSnapshots.G2Stage2.WorstDcSpike_dB, ...
    candidateSnapshots.G2Stage2.WorstDcSpike_dB); ...
    sprintf("- Worst IQ impropriety changed by `%+.4f`, from `%.4f` to `%.4f`.", ...
    iqImproprietyDelta, ...
    baselineSnapshots.G2Stage2.WorstIqImpropriety, ...
    candidateSnapshots.G2Stage2.WorstIqImpropriety); ...
    sprintf("- Baseline Stage 2 verdict: `%s` with `%s` / `%s`.", ...
    baselineSnapshots.G2Stage2.ReceiverIntegrityVerdict, ...
    baselineSnapshots.G2Stage2.LegalGateRecommendation, ...
    baselineSnapshots.G2Stage2.DatasetClassificationRecommendation); ...
    sprintf("- Candidate Stage 2 verdict: `%s` with `%s` / `%s`.", ...
    candidateSnapshots.G2Stage2.ReceiverIntegrityVerdict, ...
    candidateSnapshots.G2Stage2.LegalGateRecommendation, ...
    candidateSnapshots.G2Stage2.DatasetClassificationRecommendation); ...
    ""; ...
    "## Takeaway"; ...
    "- " + localBuildHardwareTakeaway( ...
    baselineSnapshots.G2Stage2, candidateSnapshots.G2Stage2) ...
    ];

end

function takeawayText = localBuildHardwareTakeaway(baselineStage2, ...
    candidateStage2)

powerMedianDelta = ...
    candidateStage2.ReferenceMinusSurveillancePowerMedian_dB - ...
    baselineStage2.ReferenceMinusSurveillancePowerMedian_dB;

if powerMedianDelta > 0.5
    powerText = sprintf("The candidate improves Stage 2 reference-power ordering by %.3f dB.", ...
        powerMedianDelta);
elseif powerMedianDelta < -0.5
    powerText = sprintf("The candidate weakens Stage 2 reference-power ordering by %.3f dB.", ...
        abs(powerMedianDelta));
else
    powerText = "The candidate leaves Stage 2 reference-power ordering essentially unchanged.";
end

if candidateStage2.ReferenceMinusSurveillancePowerMedian_dB >= 0.0
    thresholdText = "The candidate reaches a non-negative median reference-minus-surveillance power difference.";
else
    thresholdText = "The candidate still has a negative median reference-minus-surveillance power difference, so the accepted reference remains weaker than surveillance on a session-wide basis.";
end

takeawayText = powerText + " " + thresholdText;

end

function localRenderStage2RolePowerFigure(baselineSnapshot, ...
    candidateSnapshot, figurePath, showFigures)

figureHandle = figure("Visible", localFigureVisibility(showFigures));
tiledlayout(1, 1, "TileSpacing", "compact", "Padding", "compact");
nexttile;

categoryNames = categorical(["Minimum", "Median", "Maximum"]);
categoryNames = reordercats(categoryNames, ["Minimum", "Median", "Maximum"]);
powerMatrix = [ ...
    baselineSnapshot.ReferenceMinusSurveillancePowerMin_dB, ...
    baselineSnapshot.ReferenceMinusSurveillancePowerMedian_dB, ...
    baselineSnapshot.ReferenceMinusSurveillancePowerMax_dB; ...
    candidateSnapshot.ReferenceMinusSurveillancePowerMin_dB, ...
    candidateSnapshot.ReferenceMinusSurveillancePowerMedian_dB, ...
    candidateSnapshot.ReferenceMinusSurveillancePowerMax_dB ...
    ];

bar(categoryNames, powerMatrix.');
yline(0.0, "--k", "0 dB threshold");
grid on;
xlabel("Statistic");
ylabel("Reference Minus Surveillance Power [dB]");
title("Stage 2 Role Power Ordering");
legend([string(baselineSnapshot.DatasetId), ...
    string(candidateSnapshot.DatasetId)], "Location", "best");

try
    exportgraphics(figureHandle, figurePath);
catch figureException
    close(figureHandle);
    error("runG1G2SessionComparison:SaveFigureFailed", ...
        "Failed to write figure %s: %s", figurePath, ...
        figureException.message);
end

if ~showFigures
    close(figureHandle);
end

end

function localRenderStage2WorstMetricsFigure(baselineSnapshot, ...
    candidateSnapshot, figurePath, showFigures)

figureHandle = figure("Visible", localFigureVisibility(showFigures));
tiledlayout(1, 3, "TileSpacing", "compact", "Padding", "compact");

sessionLabels = [string(baselineSnapshot.DatasetId), ...
    string(candidateSnapshot.DatasetId)];

nexttile;
clippingCategories = categorical(["Near-Rail", "Exact-Rail"]);
clippingCategories = reordercats(clippingCategories, ...
    ["Near-Rail", "Exact-Rail"]);
clippingMatrix = [ ...
    baselineSnapshot.WorstNearRailFraction, ...
    baselineSnapshot.WorstExactRailFraction; ...
    candidateSnapshot.WorstNearRailFraction, ...
    candidateSnapshot.WorstExactRailFraction ...
    ];
bar(clippingCategories, clippingMatrix.');
grid on;
xlabel("Clipping Metric");
ylabel("Fraction");
title("Stage 2 Worst Clipping Metrics");
legend(sessionLabels, "Location", "best");

nexttile;
dcCategories = categorical(["DC Mean Ratio", "DC Spike"]);
dcCategories = reordercats(dcCategories, ["DC Mean Ratio", "DC Spike"]);
dcMatrix = [ ...
    baselineSnapshot.WorstDcMeanRatio_dB, ...
    baselineSnapshot.WorstDcSpike_dB; ...
    candidateSnapshot.WorstDcMeanRatio_dB, ...
    candidateSnapshot.WorstDcSpike_dB ...
    ];
bar(dcCategories, dcMatrix.');
grid on;
xlabel("DC Metric");
ylabel("Metric Value [dB]");
title("Stage 2 Worst DC Metrics");
legend(sessionLabels, "Location", "best");

nexttile;
iqCategories = categorical(["Amp Imbalance", "Phase Proxy", ...
    "Impropriety"]);
iqCategories = reordercats(iqCategories, ...
    ["Amp Imbalance", "Phase Proxy", "Impropriety"]);
iqMatrix = [ ...
    baselineSnapshot.WorstIqAmplitudeImbalance_dB, ...
    baselineSnapshot.WorstIqPhaseProxy_deg, ...
    baselineSnapshot.WorstIqImpropriety; ...
    candidateSnapshot.WorstIqAmplitudeImbalance_dB, ...
    candidateSnapshot.WorstIqPhaseProxy_deg, ...
    candidateSnapshot.WorstIqImpropriety ...
    ];
bar(iqCategories, iqMatrix.');
grid on;
xlabel("IQ Metric");
ylabel("Absolute Metric Value [mixed]");
title("Stage 2 Worst IQ Metrics");
legend(sessionLabels, "Location", "best");

try
    exportgraphics(figureHandle, figurePath);
catch figureException
    close(figureHandle);
    error("runG1G2SessionComparison:SaveFigureFailed", ...
        "Failed to write figure %s: %s", figurePath, ...
        figureException.message);
end

if ~showFigures
    close(figureHandle);
end

end

function visibilityText = localFigureVisibility(showFigures)

if showFigures
    visibilityText = "on";
else
    visibilityText = "off";
end

end

function localEnsureFolder(folderPath)

if isfolder(folderPath)
    return
end

try
    mkdir(folderPath);
catch mkdirException
    error("runG1G2SessionComparison:CreateFolderFailed", ...
        "Failed to create folder %s: %s", folderPath, ...
        mkdirException.message);
end

end

function localWriteTextFile(filePath, lines)

if isstring(lines)
    lineArray = lines(:);
elseif ischar(lines)
    lineArray = string(lines);
else
    lineArray = string(lines);
end

lineArray = lineArray(:);
textBody = strjoin(lineArray, newline);

try
    fileId = fopen(filePath, "w");
catch fopenException
    error("runG1G2SessionComparison:OpenFileFailed", ...
        "Failed to open %s for writing: %s", filePath, ...
        fopenException.message);
end

if fileId == -1
    error("runG1G2SessionComparison:OpenFileFailed", ...
        "Failed to open %s for writing.", filePath);
end

cleanupObject = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s\n", textBody);

end

function localWriteFailureBundle(bundleRoot, mainException)

if strlength(string(bundleRoot)) == 0
    return
end

try
    if ~isfolder(bundleRoot)
        mkdir(bundleRoot);
    end

    localWriteTextFile(fullfile(bundleRoot, "summary.md"), [ ...
        "# G1/G2 Session Comparison Failure"; ...
        ""; ...
        sprintf("- Error identifier: `%s`", mainException.identifier); ...
        sprintf("- Message: %s", string(mainException.message)) ...
        ]);
catch
    % Ignore secondary failure-bundle errors.
end

end
