function [results, detectorReplaySession] = ...
    runRealBackgroundSyntheticPipeline(options)
%RUNREALBACKGROUNDSYNTHETICPIPELINE Run the paired field-background demo.
%
%   RESULTS = RUNREALBACKGROUNDSYNTHETICPIPELINE() generates an untouched
%   control and one surveillance-only injected case from part 1 of session
%   20260622T102123, derives G3 once from the control, reuses that correction
%   for both cases, and executes the diagnostic G1-G5 plus G6-D path.
%
%   This is an integration demonstration. It does not alter formal G4-R,
%   G5, G6, or G8 gate state and does not make a field-detection claim.

arguments
    options.BaseSessionId (1,1) string = "20260622T102123"
    options.BasePartIndex (1,1) double {mustBeInteger, mustBePositive} = 1
    options.EchoGainDB (1,1) double {mustBeFinite} = -18
    options.TrajectoryNorthOffsetM (1,1) double {mustBeFinite} = 45000
    options.TrajectoryAltitudeM (1,1) double {mustBeFinite} = 3000
    options.TrajectorySpeedMps (1,1) double {mustBeNonnegative} = 150
    options.TrajectoryHeadingDeg (1,1) double {mustBeFinite} = 0
    options.ReceiverLocalWaypointTable table = table()
    options.GeoTrajectoryTargets struct = struct([])
    options.CpiDurationS (1,1) double {mustBePositive} = 0.100
    options.MapDecimationFactor (1,1) double {mustBeInteger, mustBePositive} = 200
    options.TruthSamplePeriodS (1,1) double {mustBePositive} = 0.01
    options.PfaToHighlight (1,1) double {mustBePositive} = 1.0e-3
    options.ProducerRoot (1,1) string = ""
    options.GeneratedIqRoot (1,1) string = ""
    options.ResultRoot (1,1) string = ""
    options.SuiteId (1,1) string = ""
    options.ShowFigures (1,1) logical = false
    options.SaveResult (1,1) logical = true
end

repoRoot = helperResolveRepoRoot(string(fileparts(mfilename("fullpath"))));
detectorReplaySession = struct();
resolved = localResolveOptions(options, repoRoot);
localValidateNativeFunctions(resolved);
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(repoRoot);
addpath(fullfile(resolved.ProducerRoot, "SyntheticHDTVSimulation"), "-end");
addpath(fullfile(resolved.ProducerRoot, "BistaticDataAnalysis"), "-end");

trajectoryTargets = resolved.GeoTrajectoryTargets;
if isempty(trajectoryTargets)
    if isempty(resolved.ReceiverLocalWaypointTable)
        trajectoryTargets = localBuildDefaultTrajectory(resolved);
    else
        trajectoryTargets = ...
            localBuildReceiverLocalTrajectory(resolved);
    end
end
caseDefinitions = localBuildCaseDefinitions(resolved, trajectoryTargets);
suiteArtifact = generateRealBackgroundSyntheticSuite( ...
    SuiteID=resolved.SuiteId, ...
    OutputRoot=resolved.GeneratedIqRoot, ...
    BaseSessionManifest=resolved.BaseSessionManifest, ...
    BasePartIndex=resolved.BasePartIndex, ...
    TruthWindowMaxS=1.0, ...
    TruthSamplePeriodS=resolved.TruthSamplePeriodS, ...
    TruthSourceMode="geo_trajectory_v1", ...
    GeoTrajectoryTargets=trajectoryTargets, ...
    CaseDefinitions=caseDefinitions, ...
    DirectPathLagSamples=0, ...
    SeedEchoConditioningEnabled=true, ...
    RunValidation=true, ...
    WriteReadme=true, ...
    RetainSampleArrays=false);

controlEntry = localFindDataset( ...
    suiteArtifact.datasets, resolved.ControlCaseId);
injectedEntry = localFindDataset( ...
    suiteArtifact.datasets, resolved.InjectedCaseId);
controlRoot = fullfile(suiteArtifact.suite_folder, ...
    resolved.ControlCaseId);
injectedRoot = fullfile(suiteArtifact.suite_folder, ...
    resolved.InjectedCaseId);
controlSession = loadIQData(resolved.ControlCaseId, repoRoot, struct( ...
    SessionRoot=controlRoot, IncludeSamples=true, PartSelection=1));
injectedSession = loadIQData(resolved.InjectedCaseId, repoRoot, struct( ...
    SessionRoot=injectedRoot, IncludeSamples=true, PartSelection=1));
controlMetadata = helperReadCollectionMetadata( ...
    fullfile(controlRoot, "collection_metadata.json"), ...
    resolved.ControlCaseId);
injectedMetadata = helperReadCollectionMetadata( ...
    fullfile(injectedRoot, "collection_metadata.json"), ...
    resolved.InjectedCaseId);
inputIntegrity = localVerifyInputPair( ...
    controlSession, injectedSession, ...
    suiteArtifact.base_capture_path, controlEntry, injectedEntry);
localRequireInputIntegrity(inputIntegrity);

roleOptions = struct( ...
    DataProfile="synthetic", ...
    ReferenceChannelIndex=2.0, ...
    SurveillanceChannelIndex=1.0);
captureLogInfo = localEmptyCaptureLogInfo();
controlG2 = localRunG2( ...
    controlSession, controlMetadata, captureLogInfo, roleOptions);
injectedG2 = localRunG2( ...
    injectedSession, injectedMetadata, captureLogInfo, roleOptions);

g3Options = roleOptions;
g3Options.ExpectedDatasetId = resolved.ControlCaseId;
g3Options.ExpectedReferenceLabel = ...
    string(controlSession.RadarTable.Antenna2(1));
g3Options.ExpectedSurveillanceLabel = ...
    string(controlSession.RadarTable.Antenna1(1));
g3Options.ExpectedRepetitionCount = 1.0;
g3Options.ConfiguredDirectPathLag_samples = ...
    double(suiteArtifact.direct_path_lag_samples);
g3Options.ConfiguredDirectPathResidualFrequency_Hz = 0.0;
g3Options.ConfiguredDirectPathCorrectionSource = ...
    "generated_control_manifest";
controlG3 = helperAnalyzeG3SyncCore( ...
    controlSession, controlMetadata, g3Options);
correction = controlG3.GlobalCorrection;
correction.Source = "field_only_control_g3_global_session_correction";
correctionHash = helperG4RSha256(correction);
g3Visuals = helperBuildG3SyncVisuals(controlSession, controlG3);

scenarioTruth = helperAdaptG45TruthForPostHocEvidence( ...
    injectedEntry.output_truth_path, resolved.InjectedCaseId);
[controlG5, controlMaps, controlG4Contract] = localRunG4G5( ...
    controlSession, controlMetadata, controlG3, correction, ...
    scenarioTruth, resolved);
localVerifyCorrectionReuse( ...
    controlG5, controlG4Contract, correction, "control");
controlMaps = localIdentifyMaps( ...
    controlMaps, resolved, resolved.ControlCaseId);
controlTruth = localBuildDetectorTruth( ...
    controlG5.SyntheticTargetEvidenceTable, resolved, ...
    resolved.ControlCaseId, "matched_control");
controlTargetViews = helperBuildTargetCenteredMapViews( ...
    controlMaps, controlTruth);
g6Context = struct( ...
    CampaignId=resolved.SuiteId, ...
    BackgroundId=resolved.BaseSessionId, ...
    CaseId=resolved.ControlCaseId, ...
    DetectorConfiguration=resolved.DetectorConfiguration, ...
    Finalize=false);
g6Result = helperAnalyzeG6ProductDiscrimination( ...
    controlMaps, controlTruth, g6Context);
controlCrops = localBuildDetectionRegionCrops( ...
    controlMaps, g6Result.Configuration);
if nargout > 1
    replayControlMaps = controlMaps;
    replayControlTruth = controlTruth;
end
clear controlMaps controlSession

[injectedG5, injectedMaps, injectedG4Contract] = localRunG4G5( ...
    injectedSession, injectedMetadata, controlG3, correction, ...
    scenarioTruth, resolved);
localVerifyCorrectionReuse( ...
    injectedG5, injectedG4Contract, correction, "injected");
injectedMaps = localIdentifyMaps( ...
    injectedMaps, resolved, resolved.InjectedCaseId);
injectedTruth = localBuildDetectorTruth( ...
    injectedG5.SyntheticTargetEvidenceTable, resolved, ...
    resolved.InjectedCaseId, "injected");
injectedTargetViews = helperBuildTargetCenteredMapViews( ...
    injectedMaps, injectedTruth);
g6Context.CaseId = resolved.InjectedCaseId;
g6Result = helperAnalyzeG6ProductDiscrimination( ...
    injectedMaps, injectedTruth, g6Context, g6Result);
injectedCrops = localBuildDetectionRegionCrops( ...
    injectedMaps, g6Result.Configuration);
if nargout > 1
    detectorReplaySession = localBuildDetectorReplaySession( ...
        [replayControlMaps; injectedMaps], ...
        [replayControlTruth; injectedTruth], resolved);
end
clear injectedMaps injectedSession

finalContext = struct( ...
    CampaignId=resolved.SuiteId, ...
    Finalize=true, ...
    EnforceCampaignCounts=true, ...
    ExpectedMapCount=6.0, ...
    ExpectedOperatingPointCount=54.0, ...
    ExpectedTruthOpportunityCount=27.0);
g6Result = helperAnalyzeG6ProductDiscrimination( ...
    struct([]), table(), finalContext, g6Result);

detectionRegionViews = [controlCrops; injectedCrops];
targetCenteredViews = [controlTargetViews; injectedTargetViews];
verification = localBuildVerification( ...
    inputIntegrity, controlG3, correctionHash, controlG5, ...
    injectedG5, injectedTruth, g6Result, resolved);
stageSummary = localBuildStageSummary( ...
    controlSessionSummary(controlEntry, controlG2), ...
    injectedSessionSummary(injectedEntry, injectedG2), ...
    controlG3, verification);

results = struct();
results.SchemaVersion = "field_background_synthetic_pipeline_demo_v2";
results.AnalysisTimestampZ = string(datetime("now", TimeZone="UTC", ...
    Format="yyyyMMdd'T'HHmmssSSS'Z'"));
results.ClaimBoundary = struct( ...
    DiagnosticIntegrationOnly=true, ...
    FieldDetectionClaimed=false, ...
    TrackingClaimed=false, ...
    FormalG4RStateChanged=false, ...
    FormalG6OrG8Enabled=false, ...
    TruthUse="post_hoc_association_only");
results.Configuration = localCompactConfiguration(resolved);
results.NativeFunctionAudit = localNativeFunctionAudit();
results.Provenance = localBuildProvenance( ...
    suiteArtifact, controlEntry, injectedEntry, correctionHash, ...
    resolved);
results.Trajectory = localBuildTrajectorySummary( ...
    trajectoryTargets, suiteArtifact.truth_bundle_all);
results.InputIntegrity = inputIntegrity;
results.StageSummary = stageSummary;
results.G2 = struct( ...
    Control=localCompactG2(controlG2), ...
    Injected=localCompactG2(injectedG2));
results.G3 = struct( ...
    DerivedCaseId=resolved.ControlCaseId, ...
    ReusedCaseId=resolved.InjectedCaseId, ...
    OverallLabel=localG3OverallLabel(controlG3), ...
    RecommendedStrategyCandidate= ...
    string(controlG3.RecommendedStrategyCandidate), ...
    Correction=correction, ...
    CorrectionSha256=correctionHash, ...
    Visuals=g3Visuals);
results.G4G5 = struct( ...
    Control=localCompactG5(controlG5, controlG4Contract), ...
    Injected=localCompactG5(injectedG5, injectedG4Contract));
results.G6D = g6Result;
results.DetectionRegionViews = detectionRegionViews;
results.TargetCenteredViews = targetCenteredViews;
results.Verification = verification;
results.Conclusion = localBuildConclusion(verification, resolved);
results.ResultPath = "";
compactAudit = localAuditCompactResult(results);
results.CompactResultAudit = compactAudit;
if ~compactAudit.Compact
    error("runRealBackgroundSyntheticPipeline:CompactRetention", ...
        "The result contains raw IQ or a complete map.");
end

if resolved.SaveResult
    runFolder = fullfile(resolved.ResultRoot, resolved.SuiteId);
    if ~isfolder(runFolder)
        mkdir(runFolder);
    end
    resultPath = fullfile(runFolder, ...
        "fieldBackgroundSyntheticPipelineResults.mat");
    results.ResultPath = string(resultPath);
    save(resultPath, "results");
    savedResult = load(resultPath, "results");
    savedAudit = localAuditCompactResult(savedResult.results);
    if ~savedAudit.Compact
        error("runRealBackgroundSyntheticPipeline:SavedRetention", ...
            "The saved result violates compact-retention requirements.");
    end
end

if resolved.ShowFigures
    localPlotSummary(results);
end
clear pathCleanup
end

function resolved = localResolveOptions(options, repoRoot)
resolved = options;
if strlength(resolved.ProducerRoot) == 0
    resolved.ProducerRoot = fullfile(fileparts(repoRoot), ...
        "flightTest_SynthDataBranch");
end
if strlength(resolved.GeneratedIqRoot) == 0
    resolved.GeneratedIqRoot = fullfile(repoRoot, "artifacts", ...
        "generated_iq", "FieldBackgroundSyntheticDemo");
end
if strlength(resolved.ResultRoot) == 0
    resolved.ResultRoot = fullfile(repoRoot, "artifacts", ...
        resolved.BaseSessionId, "Field_Background_Synthetic_Demo");
end
if strlength(resolved.SuiteId) == 0
    resolved.SuiteId = "field_background_demo_" + ...
        string(datetime("now", TimeZone="UTC", ...
        Format="yyyyMMdd'T'HHmmssSSS"));
end
resolved.BaseSessionManifest = fullfile( ...
    repoRoot, resolved.BaseSessionId, "session_manifest.json");
resolved.ControlCaseId = "field_only_control";
resolved.InjectedCaseId = "field_plus_geo_target";
resolved.RepoRoot = repoRoot;
resolved.DetectorConfiguration = helperBuildG6DDetectorConfiguration();
end

function localValidateNativeFunctions(resolved)
requiredFiles = [ ...
    fullfile(resolved.ProducerRoot, "SyntheticHDTVSimulation", ...
    "generateRealBackgroundSyntheticSuite.m"); ...
    resolved.BaseSessionManifest];
if ~isfolder(resolved.ProducerRoot) || any(~isfile(requiredFiles))
    error("runRealBackgroundSyntheticPipeline:MissingInput", ...
        "Producer root or base session manifest is unavailable.");
end
requiredFunctions = [ ...
    "ambgfun"; "resample"; "imdilate"; "bwconncomp"; ...
    "reckon"; "wgs84Ellipsoid"];
for functionIndex = 1:numel(requiredFunctions)
    if exist(requiredFunctions(functionIndex), "file") ~= 2
        error("runRealBackgroundSyntheticPipeline:MissingFunction", ...
            "Required MATLAB function is unavailable: %s.", ...
            requiredFunctions(functionIndex));
    end
end
if exist("dsp.LMSFilter", "class") ~= 8 || ...
        exist("phased.CFARDetector2D", "class") ~= 8
    error("runRealBackgroundSyntheticPipeline:MissingSystemObject", ...
        "DSP LMS and phased-array CFAR System objects are required.");
end
end

function targets = localBuildDefaultTrajectory(resolved)
times_s = [0; 0.5; 1.0];
north_m = resolved.TrajectoryNorthOffsetM + ...
    resolved.TrajectorySpeedMps .* cosd( ...
    resolved.TrajectoryHeadingDeg) .* times_s;
east_m = resolved.TrajectorySpeedMps .* sind( ...
    resolved.TrajectoryHeadingDeg) .* times_s;
waypointTable = table(times_s, north_m, east_m, ...
    repmat(resolved.TrajectoryAltitudeM, numel(times_s), 1), ...
    VariableNames={'Time_s', 'North_m', 'East_m', 'Altitude_m'});
resolved.ReceiverLocalWaypointTable = waypointTable;
targets = localBuildReceiverLocalTrajectory(resolved);
end

function targets = localBuildReceiverLocalTrajectory(resolved)

baseConfig = buildSyntheticHDTVBaselineScenarioConfig( ...
    SeedSourcePath=resolved.BaseSessionManifest, ...
    TruthSourceMode="capture_adsb_v1", ...
    TruthWindowMaxS=1.0);
targets = helperBuildGeoTrajectoryTargetsFromReceiverLocalWaypoints( ...
    resolved.ReceiverLocalWaypointTable, ...
    ReceiverLla_deg_m=double(baseConfig.rx_lla_deg_m), ...
    EchoGainDB=resolved.EchoGainDB);
end

function cases = localBuildCaseDefinitions(resolved, targets)
control = struct( ...
    dataset_id=char(resolved.ControlCaseId), ...
    difficulty_label="control", ...
    injection_enabled=false, ...
    target_ids=strings(0, 1), ...
    target_echo_gain_db=[], ...
    intended_use="Untouched field-only control.", ...
    expected_gate_outcome="No injected surveillance delta.", ...
    comments="Exact copy of the selected base capture part.");
injected = struct( ...
    dataset_id=char(resolved.InjectedCaseId), ...
    difficulty_label="diagnostic", ...
    injection_enabled=true, ...
    target_ids=string({targets.icao_hex}).', ...
    target_echo_gain_db=repmat( ...
    resolved.EchoGainDB, numel(targets), 1), ...
    intended_use="Field-background synthetic-target integration demo.", ...
    expected_gate_outcome= ...
    "Truth-blind detection followed by post-hoc association.", ...
    comments= ...
    "Geometry drives delay/Doppler; gain is RMS-normalized amplitude.");
cases = [control, injected];
end

function entry = localFindDataset(entries, caseId)
mask = string({entries.dataset_id}) == caseId;
if nnz(mask) ~= 1
    error("runRealBackgroundSyntheticPipeline:DatasetCount", ...
        "Expected exactly one generated dataset for %s.", caseId);
end
entry = entries(mask);
end

function integrity = localVerifyInputPair( ...
    controlSession, injectedSession, baseCapturePath, ...
    controlEntry, injectedEntry)
controlSamples = controlSession.RadarScans(1).Samples;
injectedSamples = injectedSession.RadarScans(1).Samples;
surveillanceDelta = complex( ...
    double(real(injectedSamples(:, 1))) - ...
    double(real(controlSamples(:, 1))), ...
    double(imag(injectedSamples(:, 1))) - ...
    double(imag(controlSamples(:, 1))));
baseHash = helperG4RSha256(baseCapturePath);
controlHash = helperG4RSha256(controlEntry.output_bb_path);
injectedHash = helperG4RSha256(injectedEntry.output_bb_path);
integrity = struct( ...
    ReferenceChannelExactlyUnchanged=isequal( ...
    injectedSamples(:, 2), controlSamples(:, 2)), ...
    ControlCaptureExactlyUnchanged=baseHash == controlHash, ...
    ControlSurveillanceExactlyUnchanged=baseHash == controlHash, ...
    InjectedSurveillanceDeltaFinite=all( ...
    isfinite(surveillanceDelta), "all"), ...
    InjectedSurveillanceDeltaNonzero=any( ...
    surveillanceDelta ~= 0, "all"), ...
    InjectedSurveillanceDeltaRms=rms(double(surveillanceDelta)), ...
    BaseCaptureSha256=baseHash, ...
    ControlCaptureSha256=controlHash, ...
    InjectedCaptureSha256=injectedHash, ...
    ProducerControlValidationPass=logical( ...
    controlEntry.validation_checks.overall_pass), ...
    ProducerInjectedValidationPass=logical( ...
    injectedEntry.validation_checks.overall_pass));
end

function localRequireInputIntegrity(integrity)
required = [ ...
    integrity.ReferenceChannelExactlyUnchanged, ...
    integrity.ControlCaptureExactlyUnchanged, ...
    integrity.ControlSurveillanceExactlyUnchanged, ...
    integrity.InjectedSurveillanceDeltaFinite, ...
    integrity.InjectedSurveillanceDeltaNonzero, ...
    integrity.ProducerControlValidationPass, ...
    integrity.ProducerInjectedValidationPass];
if ~all(required)
    error("runRealBackgroundSyntheticPipeline:InputIntegrity", ...
        "Generated paired inputs failed a channel-preservation invariant.");
end
end

function info = localEmptyCaptureLogInfo()
info = struct( ...
    LogPath="", LogPresent=false, SessionId="", CaptureSessionId="", ...
    SessionIdsAgree=false, SelectedAntennas="", RadioProduct="", ...
    RadioSerial="", ClockSource="", TimeSource="", ...
    MasterClockRate_Hz=NaN, RoundCount=0, CollectionStartedCount=0, ...
    CaptureFileCount=0, WarningCount=0, ContainsOverrunText=false, ...
    ContainsLockStatusText=false, ContainsAgcText=false, ...
    ContainsMappingVerificationText=false);
end

function g2 = localRunG2(session, metadata, captureLogInfo, roleOptions)
g2 = struct();
g2.Acquisition = helperAnalyzeG2AcquisitionEvidence( ...
    session, captureLogInfo, metadata, roleOptions);
g2.Receiver = helperAnalyzeG2ReceiverIntegrity( ...
    session, metadata, roleOptions);
g2.Pilot = helperAnalyzeG2PilotAwareSignalQuality( ...
    session, metadata, roleOptions);
end

function [g5, fullMaps, g4Contract] = localRunG4G5( ...
    session, metadata, controlG3, correction, scenarioTruth, resolved)
g4Contract = localBuildG4Contract(session, correction, resolved);
g5Options = struct( ...
    CandidateNames=[ ...
    "none"; "conservative_lms"; "aggressive_lms"], ...
    ReviewCpiLabels="long", ...
    ReviewWindowLabels="center", ...
    ReviewRepetitions=1.0, ...
    MaxReviewRows=1.0, ...
    MapDecimationFactor=resolved.MapDecimationFactor, ...
    DataProfile="synthetic", ...
    ReferenceChannelIndex=2.0, ...
    SurveillanceChannelIndex=1.0, ...
    RunPostHocSyntheticTargetEvidence=true, ...
    SyntheticTruth=scenarioTruth, ...
    TargetLagUncertainty_samples= ...
    correction.LagResidualMax_samples, ...
    TargetResidualFrequencyUncertainty_Hz= ...
    correction.ResidualFrequencySpread_Hz, ...
    ReviewMapRows=128.0, ...
    ReviewMapCols=128.0);
[g5, fullMaps] = helperAnalyzeG5Mitigation( ...
    session, metadata, controlG3, g4Contract, g5Options);
end

function g4 = localBuildG4Contract(session, correction, resolved)
sampleRateHz = double(session.RadarTable.SampleRate_Hz(1));
mapSampleRateHz = sampleRateHz ./ resolved.MapDecimationFactor;
nativeCpiSamples = round(resolved.CpiDurationS .* sampleRateHz);
mapCpiSamples = round(resolved.CpiDurationS .* mapSampleRateHz);
sampleCount = double(session.RadarTable.NumSamples(1));
windowCount = floor(sampleCount ./ nativeCpiSamples);
centerWindowIndex = ceil(windowCount ./ 2.0);
windowStartSample = ...
    (centerWindowIndex - 1.0) .* nativeCpiSamples + 1.0;
mapSummaryTable = table( ...
    1.0, string(session.RadarTable.RelativePath(1)), ...
    "long", "center", windowStartSample, centerWindowIndex, ...
    resolved.CpiDurationS, mapCpiSamples, ...
    VariableNames={ ...
    'Repetition', 'RelativePath', 'CpiLabel', 'WindowLabel', ...
    'WindowStartSample', 'WindowIndex', 'CpiDuration_s', ...
    'CpiSamples'});
originDelayRadius = max(2.0, ceil( ...
    (correction.LagResidualMax_samples + 16.0) ./ ...
    resolved.MapDecimationFactor));
originDopplerRadius = max(5.0, ...
    correction.ResidualFrequencySpread_Hz + 10.0);
baseline = struct( ...
    Method="ambgfun", ...
    MapRateMode="reduced_rate_g5_candidate_product", ...
    MapSampleRateHz=mapSampleRateHz, ...
    MapDecimationFactor=resolved.MapDecimationFactor, ...
    OriginSearchDelayRadius_samples=originDelayRadius, ...
    OriginSearchDopplerRadius_Hz=originDopplerRadius, ...
    ExclusionDelayRadius_samples=max(6.0, ...
    originDelayRadius + 2.0), ...
    ExclusionDopplerRadius_Hz=max(25.0, ...
    2.0 .* originDopplerRadius), ...
    ZeroDopplerRidgeExclusion_Hz=25.0, ...
    AppliedLag_samples=correction.AppliedLag_samples, ...
    AppliedResidualFrequency_Hz= ...
    correction.AppliedResidualFrequency_Hz, ...
    AppliedCorrectionSource=correction.Source);
interpretation = struct( ...
    OverallLabel="diagnostic_only", ...
    OverallRationale="This compact G4 contract supports the paired " + ...
    "diagnostic demonstration only; it does not promote or replace " + ...
    "the passed formal G4-R R4 map-rate-validity evidence.", ...
    SceneObservabilityLabel="NOT_APPLICABLE_SYNTHETIC_PROFILE", ...
    FullRateAuditAgreementLabel="NOT_RUN_DIAGNOSTIC_DEMO", ...
    ReferenceLabel=string(session.RadarTable.Antenna2(1)), ...
    SurveillanceLabel=string(session.RadarTable.Antenna1(1)), ...
    CaveatCodes="r5a_authorized_not_executed");
g4 = struct( ...
    DatasetId=string(session.DatasetId), ...
    StageId="G4_Diagnostic_CAF_Input_Contract", ...
    Options=struct( ...
    MapDecimationFactor=resolved.MapDecimationFactor, ...
    MapSampleRateHz=mapSampleRateHz, ...
    ReviewMapRows=128.0, ReviewMapCols=128.0, ...
    FigureFloor_dB=-60.0), ...
    MapSummaryTable=mapSummaryTable, ...
    BaselineProductDefinition=baseline, ...
    Interpretation=interpretation, ...
    RecommendedBaselineCpiLabel="long");
end

function localVerifyCorrectionReuse(g5, g4, correction, caseLabel)
g4Match = g4.BaselineProductDefinition.AppliedLag_samples == ...
    correction.AppliedLag_samples && ...
    g4.BaselineProductDefinition.AppliedResidualFrequency_Hz == ...
    correction.AppliedResidualFrequency_Hz;
g5Match = g5.AppliedCorrection.AppliedLag_samples == ...
    correction.AppliedLag_samples && ...
    g5.AppliedCorrection.AppliedResidualFrequency_Hz == ...
    correction.AppliedResidualFrequency_Hz;
if ~(g4Match && g5Match)
    error("runRealBackgroundSyntheticPipeline:CorrectionReuse", ...
        "The %s case did not reuse the control-derived G3 correction.", ...
        caseLabel);
end
end

function maps = localIdentifyMaps(maps, resolved, caseId)
for mapIndex = 1:numel(maps)
    maps(mapIndex).CampaignId = resolved.SuiteId;
    maps(mapIndex).BackgroundId = resolved.BaseSessionId;
    maps(mapIndex).CaseId = caseId;
end
end

function session = localBuildDetectorReplaySession( ...
    mapProducts, truthTable, resolved)

if any(arrayfun(@(item) isfield(item, "Samples") || ...
        isfield(item, "RadarScans"), mapProducts))
    error("runRealBackgroundSyntheticPipeline:ReplayRetention", ...
        "Detector replay session cannot retain raw IQ.");
end

session = struct( ...
    SchemaVersion="field_background_detector_replay_session_v1", ...
    MapProducts=mapProducts, ...
    TruthTable=truthTable, ...
    Context=struct( ...
    CampaignId=resolved.SuiteId, ...
    BackgroundId=resolved.BaseSessionId, ...
    Finalize=true, ...
    EnforceCampaignCounts=true, ...
    ExpectedMapCount=6.0, ...
    ExpectedOperatingPointCount=54.0, ...
    ExpectedTruthOpportunityCount=27.0), ...
    ContainsRawIq=false, ...
    RetentionPolicy= ...
    "workspace_only_not_saved_in_compact_pipeline_result");

end

function truth = localBuildDetectorTruth( ...
    targetEvidence, resolved, caseId, evidenceRole)
truth = addvars(targetEvidence, ...
    repmat(resolved.BaseSessionId, height(targetEvidence), 1), ...
    repmat(caseId, height(targetEvidence), 1), ...
    repmat(string(evidenceRole), height(targetEvidence), 1), ...
    Before=1, NewVariableNames={ ...
    'BackgroundId', 'CaseId', 'EvidenceRole'});
if ~ismember("GeometryClass", ...
        string(truth.Properties.VariableNames))
    truth = addvars(truth, ...
        repmat("geo_trajectory", height(truth), 1), ...
        NewVariableNames="GeometryClass");
end
end

function crops = localBuildDetectionRegionCrops(maps, detectorConfiguration)
delayLimits = double(detectorConfiguration.CutDelayLimits_s);
dopplerLimits = double(detectorConfiguration.CutDopplerLimits_Hz);
crops = repmat(struct( ...
    CaseId="", CandidateName="", ...
    DetectionRegionPower_dB=single.empty(0, 0), ...
    DelayAxis_s=zeros(1, 0), DopplerAxis_Hz=zeros(0, 1)), ...
    numel(maps), 1);
for mapIndex = 1:numel(maps)
    delayMask = maps(mapIndex).DelayAxis_s >= delayLimits(1) & ...
        maps(mapIndex).DelayAxis_s <= delayLimits(2);
    dopplerMask = maps(mapIndex).DopplerAxis_Hz >= ...
        dopplerLimits(1) & maps(mapIndex).DopplerAxis_Hz <= ...
        dopplerLimits(2);
    cropPower = double(maps(mapIndex).MapLinear( ...
        dopplerMask, delayMask));
    maximumPower = max(cropPower, [], "all");
    crops(mapIndex) = struct( ...
        CaseId=string(maps(mapIndex).CaseId), ...
        CandidateName=string(maps(mapIndex).CandidateName), ...
        DetectionRegionPower_dB=single(10.0 .* log10(max( ...
        cropPower, maximumPower .* 1.0e-5))), ...
        DelayAxis_s=double(maps(mapIndex).DelayAxis_s(delayMask)), ...
        DopplerAxis_Hz=double( ...
        maps(mapIndex).DopplerAxis_Hz(dopplerMask)));
end
end

function verification = localBuildVerification( ...
    inputIntegrity, controlG3, correctionHash, controlG5, ...
    injectedG5, injectedTruth, g6, resolved)
configuration = g6.Configuration;
truthSupport = injectedTruth.ExpectedDelay_s >= ...
    configuration.CutDelayLimits_s(1) & ...
    injectedTruth.ExpectedDelay_s <= ...
    configuration.CutDelayLimits_s(2) & ...
    injectedTruth.ExpectedDoppler_Hz >= ...
    configuration.CutDopplerLimits_Hz(1) & ...
    injectedTruth.ExpectedDoppler_Hz <= ...
    configuration.CutDopplerLimits_Hz(2);
placementRows = injectedG5.SyntheticTargetEvidenceTable;
truthWithinPhysicsMap = all( ...
    placementRows.WithinPhysicsSearchRegion) && ...
    all(placementRows.CoordinateError_bins <= sqrt(2.0));
pfaIndex = find(configuration.Pfa == resolved.PfaToHighlight, 1);
if isempty(pfaIndex)
    error("runRealBackgroundSyntheticPipeline:UnsupportedPfa", ...
        "PfaToHighlight must be one of the unchanged G6-D values.");
end
truthRows = g6.TruthOpportunityTable( ...
    g6.TruthOpportunityTable.PfaIndex == pfaIndex & ...
    g6.TruthOpportunityTable.CaseId == resolved.InjectedCaseId & ...
    g6.TruthOpportunityTable.CandidateName == ...
    "conservative_lms", :);
controlDetections = g6.DetectionTable( ...
    g6.DetectionTable.PfaIndex == pfaIndex & ...
    g6.DetectionTable.CaseId == resolved.ControlCaseId & ...
    g6.DetectionTable.CandidateName == ...
    "conservative_lms", :);
injectedTargetMatch = any(truthRows.Matched);
controlNuisanceMatch = any( ...
    controlDetections.AssociationRole == "nuisance_control_alarm");
truthWithinDetectorSupport = all(truthSupport);
[truthEvaluationStatus, truthEvaluationDetail] = ...
    helperClassifyTruthEvaluation( ...
    truthWithinPhysicsMap, truthWithinDetectorSupport, ...
    injectedTargetMatch);
finalDetectionCriterionEvaluated = truthWithinPhysicsMap && ...
    truthWithinDetectorSupport;
verification = struct( ...
    ReferenceChannelExactlyUnchanged= ...
    inputIntegrity.ReferenceChannelExactlyUnchanged, ...
    ControlSurveillanceExactlyUnchanged= ...
    inputIntegrity.ControlSurveillanceExactlyUnchanged, ...
    InjectedSurveillanceDeltaFiniteNonzero= ...
    inputIntegrity.InjectedSurveillanceDeltaFinite && ...
    inputIntegrity.InjectedSurveillanceDeltaNonzero, ...
    TruthWithinPhysicsMap=truthWithinPhysicsMap, ...
    TruthWithinDetectorSupport=truthWithinDetectorSupport, ...
    TruthWithinMapAndDetectorSupport= ...
    truthWithinPhysicsMap && truthWithinDetectorSupport, ...
    TruthEvaluationStatus=truthEvaluationStatus, ...
    TruthEvaluationDetail=truthEvaluationDetail, ...
    MapPlacementAgreesWithGeneratorTruth=truthWithinPhysicsMap, ...
    G1ThroughG5ExecutedForBothCases= ...
    controlG5.StageId == "G5_Mitigation" && ...
    injectedG5.StageId == "G5_Mitigation", ...
    G3DerivedOnceFromControl=true, ...
    G3CorrectionReusedExactly=true, ...
    G3CorrectionSha256=correctionHash, ...
    G3ControlOverallLabel=localG3OverallLabel(controlG3), ...
    G6DIntegrityPassed=g6.Integrity.AllPassed, ...
    G6DCellGeometryExact=all( ...
    g6.MapTable.CutCount == 12832.0), ...
    DetectionGeneratedBeforeTruthAssociation= ...
    g6.Integrity.DetectionGenerationTruthBlind && ...
    all(g6.DetectionTable.DetectionGeneratedTruthBlind), ...
    HighlightPfa=resolved.PfaToHighlight, ...
    ConservativeInjectedTargetMatch=injectedTargetMatch, ...
    ConservativeControlNuisanceMatch=controlNuisanceMatch, ...
    FinalDetectionCriterionEvaluated=finalDetectionCriterionEvaluated, ...
    FinalDetectionCriterionPassed=finalDetectionCriterionEvaluated && ...
    injectedTargetMatch && ~controlNuisanceMatch, ...
    NoRetuningPerformed=true);
verification.AllStructuralChecksPassed = all([ ...
    verification.ReferenceChannelExactlyUnchanged, ...
    verification.ControlSurveillanceExactlyUnchanged, ...
    verification.InjectedSurveillanceDeltaFiniteNonzero, ...
    verification.TruthWithinPhysicsMap, ...
    verification.MapPlacementAgreesWithGeneratorTruth, ...
    verification.G1ThroughG5ExecutedForBothCases, ...
    verification.G3DerivedOnceFromControl, ...
    verification.G3CorrectionReusedExactly, ...
    verification.G6DIntegrityPassed, ...
    verification.G6DCellGeometryExact, ...
    verification.DetectionGeneratedBeforeTruthAssociation]);
end

function summary = controlSessionSummary(entry, g2)
summary = localSessionSummary(entry, g2, "control");
end

function summary = injectedSessionSummary(entry, g2)
summary = localSessionSummary(entry, g2, "injected");
end

function summary = localSessionSummary(entry, g2, role)
summary = struct( ...
    CaseId=string(entry.dataset_id), ...
    Role=string(role), ...
    G1Status="decoded", ...
    G2Status=string(g2.Receiver.AnalysisValidity));
end

function stageTable = localBuildStageSummary( ...
    control, injected, controlG3, verification)
caseId = [ ...
    control.CaseId; injected.CaseId; ...
    control.CaseId; injected.CaseId; ...
    control.CaseId; injected.CaseId; ...
    control.CaseId; injected.CaseId; ...
    control.CaseId; injected.CaseId];
gate = repmat(["G1"; "G1"; "G2"; "G2"; "G3"; ...
    "G3"; "G4"; "G4"; "G5"; "G5"], 1, 1);
status = [ ...
    control.G1Status; injected.G1Status; ...
    control.G2Status; injected.G2Status; ...
    localG3OverallLabel(controlG3); ...
    "reused_control_correction"; ...
    "caf_executed"; "caf_executed"; ...
    "three_products_executed"; "three_products_executed"];
claim = [ ...
    "input_integrity_only"; "input_integrity_only"; ...
    "synthetic_profile"; "synthetic_profile"; ...
    "control_derived"; "no_rederivation"; ...
    "diagnostic"; "diagnostic"; ...
    "diagnostic"; "diagnostic"];
stageTable = table(caseId, gate, status, claim, ...
    VariableNames={ ...
    'CaseId', 'Gate', 'Status', 'ClaimBoundary'});
stageTable.Properties.UserData = verification.G1ThroughG5ExecutedForBothCases;
end

function compact = localCompactConfiguration(resolved)
compact = rmfield(resolved, "GeoTrajectoryTargets");
compact.TruthSourceMode = "geo_trajectory_v1";
compact.CandidateNames = [ ...
    "none"; "conservative_lms"; "aggressive_lms"];
compact.WindowLabel = "center";
compact.CpiLabel = "long";
compact.GeneratedIqRetention = ...
    "separate_ignored_bb_artifacts";
end

function audit = localNativeFunctionAudit()
audit = table( ...
    ["Trajectory"; "Echo synthesis"; "Map formation"; ...
    "Mitigation"; "Detection"], ...
    ["geoTrajectory / lookupPose"; ...
    "phased.WidebandFreeSpace"; ...
    "ambgfun / resample"; ...
    "dsp.LMSFilter"; ...
    "phased.CFARDetector2D"], ...
    ["Custom geographic waypoints"; ...
    "RMS-normalized surveillance-only injection"; ...
    "100 ms center CPI at factor 200"; ...
    "None, conservative, aggressive"; ...
    "Unchanged G6-D CA-CFAR and NMS"], ...
    VariableNames={ ...
    'Workflow', 'NativeMATLABAnalogue', 'AppliedUpdate'});
end

function provenance = localBuildProvenance( ...
    artifact, controlEntry, injectedEntry, correctionHash, resolved)
producerFile = fullfile(resolved.ProducerRoot, ...
    "SyntheticHDTVSimulation", ...
    "generateRealBackgroundSyntheticSuite.m");
runnerFile = fullfile(resolved.RepoRoot, ...
    "runRealBackgroundSyntheticPipeline.m");
provenance = struct( ...
    BaseSessionManifest=resolved.BaseSessionManifest, ...
    BaseCapturePath=string(artifact.base_capture_path), ...
    GeneratedSuiteFolder=string(artifact.suite_folder), ...
    GeneratedSuiteManifest=string(artifact.manifest_path), ...
    ControlCapturePath=string(controlEntry.output_bb_path), ...
    InjectedCapturePath=string(injectedEntry.output_bb_path), ...
    ControlTruthPath=string(controlEntry.output_truth_path), ...
    InjectedTruthPath=string(injectedEntry.output_truth_path), ...
    BaseCaptureSha256=helperG4RSha256(artifact.base_capture_path), ...
    ControlCaptureSha256=helperG4RSha256( ...
    controlEntry.output_bb_path), ...
    InjectedCaptureSha256=helperG4RSha256( ...
    injectedEntry.output_bb_path), ...
    ProducerSourceSha256=helperG4RSha256(producerFile), ...
    RunnerSourceSha256=helperG4RSha256(runnerFile), ...
    CorrectionSha256=correctionHash);
end

function summary = localBuildTrajectorySummary(targets, truthBundle)
track = truthBundle.bistatic_tracks(1);
summary = struct( ...
    TargetId=string(targets(1).target_id), ...
    Callsign=string(targets(1).callsign), ...
    WaypointsLla_deg_m=double(targets(1).waypoints_lla_deg_m), ...
    TimeOfArrival_s=double(targets(1).time_of_arrival_s(:)), ...
    EchoGainDB=double(targets(1).echo_gain_db), ...
    TxLla_deg_m=double(truthBundle.tx_lla_deg_m), ...
    RxLla_deg_m=double(truthBundle.rx_lla_deg_m), ...
    TruthTime_s=double(track.t_utc(:) - ...
    truthBundle.radar_epoch_utc), ...
    ExcessDelay_s=double(track.R_excess_m(:) ./ ...
    physconst("LightSpeed")), ...
    BistaticDoppler_Hz=double(track.f_D_hz(:)));
end

function compact = localCompactG2(g2)
compact = struct( ...
    AcquisitionVerdict=string(g2.Acquisition.CollectionValidityVerdict), ...
    ReceiverAnalysisValidity=string(g2.Receiver.AnalysisValidity), ...
    ReceiverIntegrityVerdict=string( ...
    g2.Receiver.ReceiverIntegrityVerdict), ...
    ChannelSummaryTable=g2.Receiver.ChannelSummaryTable, ...
    PilotSummaryTable=g2.Pilot.RoleSummaryTable);
end

function compact = localCompactG5(g5, g4Contract)
compact = struct( ...
    G4ExecutionMethod= ...
    "baseline none candidate formed with production ambgfun semantics", ...
    G4MapSummaryTable=g4Contract.MapSummaryTable, ...
    AppliedCorrection=g5.AppliedCorrection, ...
    MitigationCandidateTable=g5.MitigationCandidateTable, ...
    MitigationMetricTable=g5.MitigationMetricTable, ...
    SuppressionSummaryTable=g5.SuppressionSummaryTable, ...
    ResidualErrorPowerTable=g5.ResidualErrorPowerTable, ...
    SyntheticTargetEvidenceTable=g5.SyntheticTargetEvidenceTable, ...
    FormalGateDecisionEmitted=false);
end

function audit = localAuditCompactResult(results)
prohibited = localFindProhibitedFields(results, "results");
numericSizes = localCollectNumericSizes(results);
audit = struct( ...
    Compact=isempty(prohibited) && max(numericSizes) <= 401.0 * 32.0, ...
    RawIqPresent=any(contains(prohibited, "samples", ...
    IgnoreCase=true)) || any(contains(prohibited, "rawiq", ...
    IgnoreCase=true)), ...
    FullMapCollectionPresent=any(contains(prohibited, ...
    "maplinear", IgnoreCase=true)) || any(contains(prohibited, ...
    "fullmap", IgnoreCase=true)), ...
    ProhibitedFieldPaths=prohibited, ...
    LargestNumericElementCount=max(numericSizes));
end

function paths = localFindProhibitedFields(value, currentPath)
paths = strings(0, 1);
names = ["samples"; "radarscans"; "rawiq"; "maplinear"; ...
    "fullmap"; "fullmapcollection"];
if isstruct(value)
    fields = string(fieldnames(value));
    for elementIndex = 1:numel(value)
        for fieldIndex = 1:numel(fields)
            field = fields(fieldIndex);
            nextPath = currentPath + "." + field;
            if any(lower(field) == names)
                paths(end + 1, 1) = nextPath; %#ok<AGROW>
            end
            paths = [paths; localFindProhibitedFields( ...
                value(elementIndex).(field), nextPath)]; %#ok<AGROW>
        end
    end
elseif istable(value)
    variables = string(value.Properties.VariableNames);
    for variableIndex = 1:numel(variables)
        if any(lower(variables(variableIndex)) == names)
            paths(end + 1, 1) = currentPath + "." + ...
                variables(variableIndex); %#ok<AGROW>
        end
    end
elseif iscell(value)
    for elementIndex = 1:numel(value)
        paths = [paths; localFindProhibitedFields( ...
            value{elementIndex}, currentPath)]; %#ok<AGROW>
    end
end
end

function sizes = localCollectNumericSizes(value)
sizes = 0;
if isnumeric(value) || islogical(value)
    sizes = numel(value);
elseif isstruct(value)
    fields = fieldnames(value);
    for elementIndex = 1:numel(value)
        for fieldIndex = 1:numel(fields)
            sizes = [sizes; localCollectNumericSizes( ...
                value(elementIndex).(fields{fieldIndex}))]; %#ok<AGROW>
        end
    end
elseif istable(value)
    variables = value.Properties.VariableNames;
    for variableIndex = 1:numel(variables)
        sizes = [sizes; localCollectNumericSizes( ...
            value.(variables{variableIndex}))]; %#ok<AGROW>
    end
elseif iscell(value)
    for elementIndex = 1:numel(value)
        sizes = [sizes; localCollectNumericSizes( ...
            value{elementIndex})]; %#ok<AGROW>
    end
end
end

function conclusion = localBuildConclusion(verification, resolved)
if verification.TruthEvaluationStatus == "outside_physics_map_invalid"
    outcome = "invalid_truth_outside_physics_map";
    detail = "Generator truth did not pass full-map placement validation; " + ...
        "the fixed detection criterion is not interpretable.";
elseif ~verification.FinalDetectionCriterionEvaluated
    outcome = "not_evaluated_outside_detector_support";
    detail = "Conservative LMS was not evaluated at the truth location " + ...
        "because truth lies outside the fixed CFAR/NMS support. " + ...
        "Parameters were not retuned.";
elseif verification.FinalDetectionCriterionPassed
    outcome = "criterion_passed";
    detail = sprintf( ...
        "Conservative LMS at Pfa %.0e produced an injected-target match " + ...
        "and no matched-control nuisance alarm.", ...
        resolved.PfaToHighlight);
else
    outcome = "criterion_failed_without_retuning";
    detail = sprintf( ...
        "Conservative LMS at Pfa %.0e did not satisfy the fixed paired " + ...
        "criterion. Parameters were not retuned.", ...
        resolved.PfaToHighlight);
end
conclusion = struct( ...
    Outcome=outcome, ...
    Detail=string(detail), ...
    Limitation= ...
    "Diagnostic synthetic integration only; no field detection or tracking claim.");
end

function label = localG3OverallLabel(g3)
label = "";
if isfield(g3, "OverallLabel")
    label = string(g3.OverallLabel);
elseif isfield(g3, "Interpretation") && ...
        isfield(g3.Interpretation, "OverallLabel")
    label = string(g3.Interpretation.OverallLabel);
end
end

function localPlotSummary(results)
views = results.TargetCenteredViews;
candidateMask = string({views.CandidateName}) == ...
    "conservative_lms";
views = views(candidateMask);
tiledlayout(1, 2);
for viewIndex = 1:numel(views)
    nexttile
    imagesc(views(viewIndex).DelayAxis_s .* 1e6, ...
        views(viewIndex).DopplerAxis_Hz, ...
        views(viewIndex).TargetRegionPower_dB);
    axis xy
    hold on
    plot(views(viewIndex).ExpectedDelay_s .* 1e6, ...
        views(viewIndex).ExpectedDoppler_Hz, ...
        "gd", MarkerSize=9, LineWidth=1.5)
    hold off
    xlabel("Bistatic delay (\mus)")
    ylabel("Doppler (Hz)")
    title(strrep(views(viewIndex).CaseId, "_", " "))
    colorbar
end
end
