%[text] # Synthetic HDTV IQ Through G1-G5
%[text] This quick-path analysis checks whether one packaged SyntheticDataGeneration capture can traverse the existing passive-bistatic G1-G5 computations. It is an interoperability and pre-detection diagnostic, not a detector, tracker, field-equivalence claim, or formal gate approval.
%[text] The checked-in configuration processes part 1 only. Change |partSelection| to |"all"| only after the single-part path has been reviewed.
%%
%[text] ## Setup and Exact Synthetic Dataset
repoRoot = helperResolveRepoRoot(string(fileparts(mfilename("fullpath"))));
syntheticDataRoot = fullfile(fileparts(repoRoot), ...
    "flightTest_SynthDataBranch", "captures");
sessionId = "seed_demo_20260730T155438811";
sessionRoot = fullfile(syntheticDataRoot, sessionId);
partSelection = 1;
surveillanceChannelIndex = 1;
referenceChannelIndex = 2;
showFigures = true;
saveCompactResult = true;
assert(isfolder(sessionRoot), "Synthetic session folder not found: %s", ...
    sessionRoot);
assert(surveillanceChannelIndex ~= referenceChannelIndex && ...
    all([surveillanceChannelIndex, referenceChannelIndex] >= 1) && ...
    all([surveillanceChannelIndex, referenceChannelIndex] <= 2) && ...
    all(mod([surveillanceChannelIndex, referenceChannelIndex], 1) == 0), ...
    "Synthetic channel roles must be distinct integer indices 1 and 2.");
fprintf("Session: %s | Part selection: %s | CH%d surveillance | CH%d reference\n", ...
    sessionId, string(partSelection), surveillanceChannelIndex, ...
    referenceChannelIndex);
%%
%[text] ## Source Package and Producer-Readiness Review
manifestPath = fullfile(sessionRoot, "session_manifest.json");
manifest = jsondecode(fileread(manifestPath));
assert(string(manifest.session_id) == sessionId, ...
    "Manifest session ID does not match the configured session.");
assert(string(manifest.data_origin) == "synthetic", ...
    "Expected data_origin=synthetic.");
assert(string(manifest.generator_name) == "generateSyntheticHDTVSession", ...
    "Unexpected synthetic generator.");
assert(string(manifest.synthetic_radar_data_product) == ...
    "synthetic_hdtv_iq_session_v2", "Unexpected synthetic radar product.");
assert(string(manifest.signal_mode) == "seed_backed_bistatic_v1", ...
    "Unexpected synthetic signal mode.");
assert(string(manifest.target_echo_dataset_mode) == ...
    "conditioned_target_echo_dataset_v1", ...
    "Unexpected target-echo dataset mode.");
assert(double(manifest.capture_repetitions) == 15, ...
    "Expected exactly 15 capture repetitions.");
radarRelativePaths = string(manifest.radar_files(:));
radarAbsolutePaths = fullfile(sessionRoot, ...
    strrep(radarRelativePaths, "/", filesep));
assert(numel(radarRelativePaths) == 15 && all(isfile(radarAbsolutePaths)), ...
    "The complete 15-part radar package is not present.");
assert(all([manifest.readiness_check.packaging_integrity_pass, ...
    manifest.readiness_check.target_placement_pass]), ...
    "Package integrity and target placement must pass before PBR analysis.");
producerFailureClasses = string( ...
    manifest.readiness_check.failure_classes(:));
producerStatus = string(manifest.readiness_check.status);
assert(producerStatus == "fail" && ...
    any(producerFailureClasses == "seed_preservation_failure"), ...
    "The expected producer readiness caveat was not found.");
fprintf("Producer readiness: %s | Caveat: %s | Packaging: pass | Target placement: pass\n", ...
    upper(producerStatus), strjoin(producerFailureClasses, ", "));
%[text] The producer readiness result remains a failure because of |seed_preservation_failure|. PBR continues only as an exploratory consumer because packaging integrity and target placement passed; this script does not relabel the generator result as a pass.
%%
%[text] ## G1 Ingest
stageTimer = tic;
loadOptions = struct( ...
    IncludeSamples=true, ...
    PartSelection=partSelection, ...
    SessionRoot=sessionRoot);
sessionData = loadIQData(sessionId, repoRoot, loadOptions);
g1Runtime_s = toc(stageTimer);
assert(sessionData.PartSelection.PackagePartCount == 15, ...
    "G1 did not retain the complete package inventory.");
if isnumeric(partSelection)
    assert(sessionData.PartSelection.SelectedPartCount == 1 && ...
        sessionData.RadarTable.Repetition(1) == 1, ...
        "The checked-in quick path must decode only part 1.");
else
    assert(sessionData.PartSelection.SelectedPartCount == 15 && ...
        isequal(sessionData.RadarTable.Repetition, (1:15).'), ...
        "The all-parts path must preserve all 15 repetition numbers.");
end
assert(sessionData.RadarTable.NumChannels(1) == 2 && ...
    sessionData.RadarTable.IsComplex(1), ...
    "The selected capture must contain two-channel complex IQ.");
assert(sessionData.RadarTable.Antenna1(1) == "CH1" && ...
    sessionData.RadarTable.Antenna2(1) == "CH2" && ...
    sessionData.RadarTable.ChannelLabelSource(1) == ...
    "generated_index_labels", ...
    "Synthetic captures without antenna metadata require neutral labels.");
assert(all(sessionData.ManifestInventoryTable.Observed( ...
    sessionData.ManifestInventoryTable.RequiredByManifest)), ...
    "At least one manifest-declared package file is missing.");
selectedSamples = sessionData.RadarScans(1).Samples;
assert(~isempty(selectedSamples) && all(isfinite(selectedSamples), "all"), ...
    "G1 decoded empty or nonfinite IQ.");
g1Status = "caveated";
g1ResultLabel = "selected_parts_decoded_generator_caveat";
fprintf("G1: %d/%d parts decoded | %.3f s | %.3f MHz | %.3f MHz center | %s\n", ...
    sessionData.PartSelection.SelectedPartCount, ...
    sessionData.PartSelection.PackagePartCount, ...
    sessionData.RadarTable.Duration_s(1), ...
    sessionData.RadarTable.SampleRate_Hz(1) / 1e6, ...
    sessionData.RadarTable.CenterFrequency_Hz(1) / 1e6, g1Status);
if showFigures
    overviewStride = max(1, floor(size(selectedSamples, 1) / 5000));
    overviewIndices = 1:overviewStride:size(selectedSamples, 1);
    overviewTime_s = (overviewIndices - 1) ./ ...
        sessionData.RadarTable.SampleRate_Hz(1);
    tiledlayout(2, 1)
    nexttile
    plot(overviewTime_s, abs(double(selectedSamples(overviewIndices, 1))))
    hold on
    plot(overviewTime_s, abs(double(selectedSamples(overviewIndices, 2))))
    hold off
    grid on
    xlabel("Time (s)")
    ylabel("Magnitude (counts)")
    title("Selected-Part Magnitude Overview")
    legend("CH1 surveillance", "CH2 reference", Location="best")
    nexttile
    scatter(real(double(selectedSamples(overviewIndices, 1))), ...
        imag(double(selectedSamples(overviewIndices, 1))), 4, ".")
    hold on
    scatter(real(double(selectedSamples(overviewIndices, 2))), ...
        imag(double(selectedSamples(overviewIndices, 2))), 4, ".")
    hold off
    axis equal
    grid on
    xlabel("In-phase (counts)")
    ylabel("Quadrature (counts)")
    title("Decimated IQ Constellation Overview")
    legend("CH1 surveillance", "CH2 reference", Location="best")
end
%%
%[text] ## G2 RF and Pre-Detection Health
%[text] Hardware identity, antenna, cabling, clock/lock, overrun, operator, and site checks are |NOT_APPLICABLE| for this packaged synthetic profile. Numerical signal-health and pilot-aware checks remain active.
collectionMetadataInfo = helperReadCollectionMetadata( ...
    fullfile(sessionRoot, "collection_metadata.json"), sessionId);
captureLogInfo = struct( ...
    LogPath="", LogPresent=false, SessionId="", CaptureSessionId="", ...
    SessionIdsAgree=false, SelectedAntennas="", RadioProduct="", ...
    RadioSerial="", ClockSource="", TimeSource="", ...
    MasterClockRate_Hz=NaN, RoundCount=0, CollectionStartedCount=0, ...
    CaptureFileCount=0, WarningCount=0, ContainsOverrunText=false, ...
    ContainsLockStatusText=false, ContainsAgcText=false, ...
    ContainsMappingVerificationText=false);
roleOptions = struct( ...
    DataProfile="synthetic", ...
    ReferenceChannelIndex=referenceChannelIndex, ...
    SurveillanceChannelIndex=surveillanceChannelIndex);
stageTimer = tic;
g2Acquisition = helperAnalyzeG2AcquisitionEvidence(sessionData, ...
    captureLogInfo, collectionMetadataInfo, roleOptions);
g2Receiver = helperAnalyzeG2ReceiverIntegrity(sessionData, ...
    collectionMetadataInfo, roleOptions);
g2Pilot = helperAnalyzeG2PilotAwareSignalQuality(sessionData, ...
    collectionMetadataInfo, roleOptions);
g2Runtime_s = toc(stageTimer);
assert(g2Receiver.AnalysisValidity == "valid", ...
    "G2 receiver-integrity analysis is invalid.");
assert(all(isfinite(g2Receiver.RoleEvidence.ReferenceMeanPsd)) && ...
    all(isfinite(g2Receiver.RoleEvidence.SurveillanceMeanPsd)), ...
    "G2 returned nonfinite role-mapped PSD.");
assert(all(isfinite(g2Pilot.RoleEvidence.ReferenceMeanPsd)) && ...
    all(isfinite(g2Pilot.RoleEvidence.SurveillanceMeanPsd)), ...
    "G2 pilot-aware analysis returned nonfinite PSD.");
g2Status = "caveated";
g2ResultLabel = "numeric_health_executed_hardware_not_applicable";
referenceSummary = g2Receiver.ChannelSummaryTable( ...
    g2Receiver.ChannelSummaryTable.ChannelRole == "reference", :);
surveillanceSummary = g2Receiver.ChannelSummaryTable( ...
    g2Receiver.ChannelSummaryTable.ChannelRole == "surveillance", :);
referencePilot = g2Pilot.RoleSummaryTable( ...
    g2Pilot.RoleSummaryTable.Role == "reference", :);
surveillancePilot = g2Pilot.RoleSummaryTable( ...
    g2Pilot.RoleSummaryTable.Role == "surveillance", :);
fprintf("G2: reference minus surveillance %.2f dB | pilot prominence %.2f/%.2f dB | hardware checks NOT_APPLICABLE\n", ...
    g2Receiver.RoleEvidence.ReferenceMinusSurveillancePower_dB_Median, ...
    referencePilot.MedianPilotProminence_dB, ...
    surveillancePilot.MedianPilotProminence_dB);
if showFigures
    tiledlayout(3, 2)
    nexttile
    plot(g2Receiver.RoleEvidence.PsdFrequencyHz / 1e6, ...
        pow2db(g2Receiver.RoleEvidence.ReferenceMeanPsd + eps))
    hold on
    plot(g2Receiver.RoleEvidence.PsdFrequencyHz / 1e6, ...
        pow2db(g2Receiver.RoleEvidence.SurveillanceMeanPsd + eps))
    hold off
    grid on
    xlabel("Frequency offset (MHz)")
    ylabel("PSD (dB/Hz)")
    title("Role-Mapped Power Spectra")
    legend("Reference CH2", "Surveillance CH1", Location="best")
    nexttile
    pilotFrequencyMHz = g2Pilot.RoleEvidence.PsdFrequencyOffset_Hz / 1e6;
    pilotMask = abs(g2Pilot.RoleEvidence.PsdFrequencyOffset_Hz - ...
        g2Pilot.Options.ExpectedPilotOffsetHz) <= 0.25e6;
    plot(pilotFrequencyMHz(pilotMask), ...
        pow2db(g2Pilot.RoleEvidence.ReferenceMeanPsd(pilotMask) + eps))
    hold on
    plot(pilotFrequencyMHz(pilotMask), ...
        pow2db(g2Pilot.RoleEvidence.SurveillanceMeanPsd(pilotMask) + eps))
    hold off
    grid on
    xlabel("Frequency offset (MHz)")
    ylabel("PSD (dB/Hz)")
    title("ATSC Pilot Region")
    legend("Reference CH2", "Surveillance CH1", Location="best")
    nexttile
    bar(categorical(["Reference", "Surveillance"]), ...
        [referenceSummary.MedianMeanPower_dBFS, ...
        surveillanceSummary.MedianMeanPower_dBFS])
    ylabel("Mean power (dBFS)")
    title("Channel Power")
    grid on
    nexttile
    bar(categorical(["Reference", "Surveillance"]), ...
        [referenceSummary.MinPeakHeadroom_dB, ...
        surveillanceSummary.MinPeakHeadroom_dB])
    ylabel("Peak headroom (dB)")
    title("Headroom")
    grid on
    nexttile
    bar(categorical(["Reference", "Surveillance"]), ...
        [referenceSummary.MaxDcMeanRatio_dB, ...
        surveillanceSummary.MaxDcMeanRatio_dB; ...
        referenceSummary.MaxDcSpike_dB, ...
        surveillanceSummary.MaxDcSpike_dB].')
    ylabel("Level (dB)")
    title("DC Indicators")
    legend("Mean ratio", "Spectral spike", Location="best")
    grid on
    nexttile
    yyaxis left
    bar(categorical(["Reference", "Surveillance"]), abs([ ...
        referenceSummary.MedianIqAmplitudeImbalance_dB, ...
        surveillanceSummary.MedianIqAmplitudeImbalance_dB]))
    ylabel("|Amplitude imbalance| (dB)")
    yyaxis right
    plot(categorical(["Reference", "Surveillance"]), abs([ ...
        referenceSummary.MedianIqPhaseProxy_deg, ...
        surveillanceSummary.MedianIqPhaseProxy_deg]), "o-", ...
        LineWidth=1.5)
    ylabel("|Phase proxy| (deg)")
    title("IQ Health")
    grid on
end
%%
%[text] ## G3 Synchronization and Coherence
%[text] G3 retains the established 25, 50, and 100 ms CPI definitions. A single part can establish computational behavior and a usable correction, but cross-part repeatability remains |NOT_ASSESSED_SINGLE_PART|.
g3Options = roleOptions;
g3Options.ExpectedDatasetId = sessionId;
g3Options.ExpectedReferenceLabel = "CH2";
g3Options.ExpectedSurveillanceLabel = "CH1";
g3Options.ExpectedRepetitionCount = ...
    sessionData.PartSelection.SelectedPartCount;
stageTimer = tic;
g3Analysis = helperAnalyzeG3SyncCore(sessionData, ...
    collectionMetadataInfo, g3Options);
g3Runtime_s = toc(stageTimer);
assert(all(isfinite(g3Analysis.LagTable.XcorrLagMedian_samples)) && ...
    all(isfinite(g3Analysis.ResidualFrequencyTable. ...
    ResidualFrequencyMedian_Hz)) && ...
    all(isfinite(g3Analysis.CpiCoherenceTable.CoherenceMedian)), ...
    "G3 returned nonfinite synchronization or coherence metrics.");
if sessionData.PartSelection.SelectedPartCount == 1
    g3Status = "executed_with_single_part_caveat";
    g3ResultLabel = "usable_correction_repeatability_not_assessed";
else
    g3Status = "executed";
    g3ResultLabel = "selected_part_repeatability_assessed";
end
fprintf("G3: strategy %s | lag %.3f samples | residual %.3f Hz | %s\n", ...
    g3Analysis.RecommendedStrategyCandidate, ...
    g3Analysis.GlobalCorrection.AppliedLag_samples, ...
    g3Analysis.GlobalCorrection.AppliedResidualFrequency_Hz, ...
    g3Analysis.CrossPartRepeatabilityStatus);
if showFigures
    tiledlayout(3, 1)
    nexttile
    plot(categorical(g3Analysis.LagTable.CpiLabel), ...
        g3Analysis.LagTable.XcorrLagMedian_samples, "o-", LineWidth=1.5)
    ylabel("Lag (samples)")
    title("G3 Lag by CPI")
    grid on
    nexttile
    plot(categorical(g3Analysis.ResidualFrequencyTable.CpiLabel), ...
        g3Analysis.ResidualFrequencyTable.ResidualFrequencyMedian_Hz, ...
        "o-", LineWidth=1.5)
    ylabel("Residual frequency (Hz)")
    title("G3 Residual Frequency by CPI")
    grid on
    nexttile
    plot(categorical(g3Analysis.CpiCoherenceTable.CpiLabel), ...
        g3Analysis.CpiCoherenceTable.CoherenceMedian, "o-", ...
        LineWidth=1.5)
    hold on
    plot(categorical(g3Analysis.CpiCoherenceTable.CpiLabel), ...
        g3Analysis.CpiCoherenceTable.CoherencePassFraction, "s-", ...
        LineWidth=1.5)
    hold off
    ylim([0 1])
    ylabel("Fraction")
    title("G3 Coherence by CPI")
    legend("Median coherence", "Pass fraction", Location="best")
    grid on
end
%%
%[text] ## G4 Passive Ambiguity Map
%[text] The quick profile forms exactly one reduced-rate 50 ms center-window map. It skips the five-CPI sensitivity sweep and full-rate audit, does not consult truth coordinates, and records skipped audit work as |NOT_RUN_QUICK_MODE|.
g4Options = g3Options;
g4Options.MapCpiLabels = "medium";
g4Options.MapCpiDurations_s = 0.050;
g4Options.MapWindowLabels = "center";
g4Options.RunFullRateAudit = false;
stageTimer = tic;
g4Analysis = helperAnalyzeG4PassiveBaselineMap(sessionData, ...
    collectionMetadataInfo, g3Analysis, g4Options);
g4Runtime_s = toc(stageTimer);
assert(height(g4Analysis.MapSummaryTable) == ...
    sessionData.PartSelection.SelectedPartCount && ...
    g4Analysis.FullRateAuditStatus == "NOT_RUN_QUICK_MODE", ...
    "G4 did not honor the requested quick profile.");
g4Map = g4Analysis.RepresentativeMaps(1);
assert(~isempty(g4Map.Map_dB) && all(isfinite(g4Map.Map_dB), "all") && ...
    all(isfinite(g4Map.DelayAxis_s)) && ...
    all(isfinite(g4Map.DopplerAxis_Hz)), ...
    "G4 returned an invalid ambiguity map or axes.");
g4Status = "executed_quick_map";
g4ResultLabel = string(g4Analysis.Interpretation.SceneObservabilityLabel);
fprintf("G4: %dx%d map | peak %.1f samples, %.1f Hz | scene %s | audit %s\n", ...
    size(g4Map.Map_dB, 1), size(g4Map.Map_dB, 2), ...
    g4Map.DirectPathDelay_samples, g4Map.DirectPathDoppler_Hz, ...
    g4ResultLabel, g4Analysis.FullRateAuditStatus);
if showFigures
    imagesc(g4Map.DelayAxis_s * 1e6, g4Map.DopplerAxis_Hz, ...
        g4Map.Map_dB)
    axis xy
    xlabel("Bistatic delay (\mus)")
    ylabel("Doppler (Hz)")
    title("Synthetic " + sessionId + ": 50 ms Baseline Map")
    colorbar
end
%%
%[text] ## G5 Mitigation Comparison
%[text] The same G4 row is evaluated with no mitigation, conservative normalized LMS, and aggressive normalized LMS. The comparison is diagnostic and does not constitute a mitigation recommendation.
g5Options = roleOptions;
g5Options.CandidateNames = [ ...
    "none"; ...
    "conservative_lms"; ...
    "aggressive_lms" ...
    ];
g5Options.ReviewCpiLabels = "medium";
g5Options.ReviewWindowLabels = "center";
g5Options.ReviewRepetitions = sessionData.RadarTable.Repetition;
g5Options.MaxReviewRows = ...
    sessionData.PartSelection.SelectedPartCount;
stageTimer = tic;
g5Analysis = helperAnalyzeG5Mitigation(sessionData, ...
    collectionMetadataInfo, g3Analysis, g4Analysis, g5Options);
g5Runtime_s = toc(stageTimer);
assert(height(g5Analysis.MitigationMetricTable) == ...
    3 * sessionData.PartSelection.SelectedPartCount && ...
    all(isfinite(g5Analysis.MitigationMetricTable.DirectPathPeak_dB)) && ...
    all([g5Analysis.ResidualErrorPowerTable.LmsConvergedFinite]), ...
    "G5 did not produce three finite candidate results.");
g5Status = "executed_quick_comparison";
g5ResultLabel = "three_candidate_diagnostic";
fprintf("G5: none/conservative/aggressive complete | suppression %.2f/%.2f dB | retention %.2f/%.2f dB\n", ...
    g5Analysis.SuppressionSummaryTable.MedianDirectPathSuppression_dB(2), ...
    g5Analysis.SuppressionSummaryTable.MedianDirectPathSuppression_dB(3), ...
    g5Analysis.ProtectedRegionRetentionTable.MedianProtectedRetention_dB(2), ...
    g5Analysis.ProtectedRegionRetentionTable.MedianProtectedRetention_dB(3));
if showFigures
    g5Maps = g5Analysis.RepresentativeMaps;
    sharedColorMinimum = min(arrayfun(@(map) ...
        min(map.Map_dB, [], "all"), g5Maps));
    sharedColorMaximum = max(arrayfun(@(map) ...
        max(map.Map_dB, [], "all"), g5Maps));
    tiledlayout(1, 3)
    for candidateIndex = 1:numel(g5Maps)
        nexttile
        delayMicroseconds = g5Maps(candidateIndex).DelayAxis_samples ./ ...
            g5Analysis.Options.MapSampleRateHz * 1e6;
        imagesc(delayMicroseconds, g5Maps(candidateIndex).DopplerAxis_Hz, ...
            g5Maps(candidateIndex).Map_dB)
        axis xy
        clim([sharedColorMinimum, sharedColorMaximum])
        xlabel("Bistatic delay (\mus)")
        ylabel("Doppler (Hz)")
        title(strrep(g5Maps(candidateIndex).CandidateName, "_", " "))
        colorbar
    end
end
%%
%[text] ## Integrated G1-G5 Result
gate = ["G1"; "G2"; "G3"; "G4"; "G5"];
executionStatus = [g1Status; g2Status; g3Status; g4Status; g5Status];
runtime_s = [g1Runtime_s; g2Runtime_s; g3Runtime_s; ...
    g4Runtime_s; g5Runtime_s];
resultLabel = [g1ResultLabel; g2ResultLabel; g3ResultLabel; ...
    g4ResultLabel; g5ResultLabel];
stageSummary = table(gate, executionStatus, runtime_s, resultLabel, ...
    VariableNames=["Gate", "ExecutionStatus", "Runtime_s", "ResultLabel"])
%[text] The exact generated IQ traversed G1-G5 without manual data rewriting. The upstream generator still reports |seed_preservation_failure|; only part 1 was analyzed; cross-part repeatability, detection, tracking, field equivalence, and formal gate approval remain outside this result.
%%
%[text] ## Saved Result and Next Step
quickResults = struct();
quickResults.Configuration = struct( ...
    RepoRoot=repoRoot, SyntheticDataRoot=syntheticDataRoot, ...
    SessionId=sessionId, SessionRoot=sessionRoot, ...
    PartSelection=partSelection, ...
    SurveillanceChannelIndex=surveillanceChannelIndex, ...
    ReferenceChannelIndex=referenceChannelIndex, ...
    ShowFigures=showFigures, SaveCompactResult=saveCompactResult);
quickResults.SourceProvenance = struct( ...
    DataOrigin=string(manifest.data_origin), ...
    GeneratorName=string(manifest.generator_name), ...
    SyntheticRadarDataProduct=string( ...
    manifest.synthetic_radar_data_product), ...
    SignalMode=string(manifest.signal_mode), ...
    TargetEchoDatasetMode=string(manifest.target_echo_dataset_mode), ...
    SafetyCheckpointCommit="da82227");
quickResults.ProducerReadiness = struct( ...
    Status=producerStatus, FailureClasses=producerFailureClasses, ...
    PackagingIntegrityPass=logical( ...
    manifest.readiness_check.packaging_integrity_pass), ...
    TargetPlacementPass=logical( ...
    manifest.readiness_check.target_placement_pass));
quickResults.PartSelection = sessionData.PartSelection;
quickResults.StageStatus = stageSummary;
quickResults.Timing = struct(G1_s=g1Runtime_s, G2_s=g2Runtime_s, ...
    G3_s=g3Runtime_s, G4_s=g4Runtime_s, G5_s=g5Runtime_s, ...
    Total_s=sum(runtime_s));
quickResults.G1 = struct( ...
    RadarTable=sessionData.RadarTable, ...
    ManifestInventoryTable=sessionData.ManifestInventoryTable, ...
    NativeReaderContract=sessionData.NativeReaderContract, ...
    ChannelContract=sessionData.ChannelContract, ...
    TimingModel=sessionData.TimingModel);
quickResults.G2 = struct();
quickResults.G2.AcquisitionStatus = ...
    g2Acquisition.CollectionValidityVerdict;
quickResults.G2.RoleInfo = g2Receiver.RoleInfo;
quickResults.G2.ReceiverIntegrityVerdict = ...
    g2Receiver.ReceiverIntegrityVerdict;
quickResults.G2.DevelopmentReadiness = g2Receiver.DevelopmentReadiness;
quickResults.G2.ChannelSummaryTable = g2Receiver.ChannelSummaryTable;
quickResults.G2.PilotSummaryTable = g2Pilot.RoleSummaryTable;
quickResults.G2.PilotDashboardTable = g2Pilot.DashboardTable;
quickResults.G3 = struct();
quickResults.G3.OverallLabel = g3Analysis.Interpretation.OverallLabel;
quickResults.G3.CrossPartRepeatabilityStatus = ...
    g3Analysis.CrossPartRepeatabilityStatus;
quickResults.G3.RecommendedStrategyCandidate = ...
    g3Analysis.RecommendedStrategyCandidate;
quickResults.G3.GlobalCorrection = g3Analysis.GlobalCorrection;
quickResults.G3.LagTable = g3Analysis.LagTable;
quickResults.G3.ResidualFrequencyTable = ...
    g3Analysis.ResidualFrequencyTable;
quickResults.G3.CpiCoherenceTable = g3Analysis.CpiCoherenceTable;
quickResults.G4 = struct();
quickResults.G4.ExecutionStatus = g4Status;
quickResults.G4.FullRateAuditStatus = g4Analysis.FullRateAuditStatus;
quickResults.G4.Interpretation = g4Analysis.Interpretation;
quickResults.G4.MapSummaryTable = g4Analysis.MapSummaryTable;
quickResults.G4.RepresentativeMap = g4Map;
quickResults.G5 = struct();
quickResults.G5.ExecutionStatus = g5Status;
quickResults.G5.ReviewStatus = g5Analysis.ReviewStatus;
quickResults.G5.MitigationCandidateTable = ...
    g5Analysis.MitigationCandidateTable;
quickResults.G5.SuppressionSummaryTable = ...
    g5Analysis.SuppressionSummaryTable;
quickResults.G5.ResidualErrorPowerTable = ...
    g5Analysis.ResidualErrorPowerTable;
quickResults.G5.ProtectedRegionRetentionTable = ...
    g5Analysis.ProtectedRegionRetentionTable;
quickResults.G5.RepresentativeMaps = g5Analysis.RepresentativeMaps;
quickResults.OverallInterpretation = struct( ...
    GeneratorStatus="fail_seed_preservation", ...
    InteroperabilityStatus="exact_package_traversed_G1_through_G5", ...
    PreDetectionStatus="finite_diagnostics_and_maps_produced", ...
    CoverageLimitation="selected_parts_only", ...
    ClaimLimitation="no_detection_tracking_field_equivalence_or_gate_approval");
resultPath = ""; %#ok<NASGU>
if saveCompactResult
    runTimestamp = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyyMMdd'T'HHmmssSSS"));
    resultFolder = fullfile(repoRoot, "artifacts", "quick", sessionId, ...
        runTimestamp);
    if ~isfolder(resultFolder)
        mkdir(resultFolder);
    end
    resultPath = fullfile(resultFolder, "quickResults.mat");
    save(resultPath, "quickResults");
end
fprintf("Saved compact result: %s\n", resultPath);
%[text] Review the part-1 figures and summaries before deciding whether to run the same quick profile across all 15 parts or address the producer seed-preservation caveat first.
%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
