function verification = verifyG4PassiveBaselineMapSlice(datasetId, ...
    repoRoot, options)
%VERIFYG4PASSIVEBASELINEMAPSLICE Run helper-level verification for G4.
%
%   VERIFICATION = VERIFYG4PASSIVEBASELINEMAPSLICE() runs the first-slice
%   helper verification plan for the passive baseline map implementation.
%   The verification covers:
%   - optional G3 regression against a saved pre-refactor snapshot
%   - synthetic delay/Doppler orientation checks
%   - baseline helper execution and schema/value checks
%   - negative controls for blocked/mismatched upstream contracts and
%     sign-flipped correction behavior

arguments
    datasetId (1,1) string = "20260622T102123"
    repoRoot (1,1) string = string(fileparts(mfilename("fullpath")))
    options (1,1) struct = struct()
end

repoRoot = helperResolveRepoRoot(repoRoot);
datasetId = string(datasetId);
resolvedOptions = localResolveVerificationOptions(options);

fprintf("Running G4 helper verification for dataset %s\n", datasetId);
fprintf("Repository root:\t%s\n", repoRoot);

sessionData = struct();
collectionMetadataInfo = struct();
currentG3Analysis = struct();
syntheticSessionData = struct();
syntheticMetadataInfo = struct();
syntheticG3Results = struct();
syntheticOptions = struct();
syntheticTruth = struct();
g3RegressionStatus = localBuildSkippedStatus("G3 regression skipped.");
syntheticStatus = localBuildSkippedStatus("Synthetic checks skipped.");
baselineStatus = localBuildSkippedStatus("Baseline checks skipped.");
negativeControlStatus = localBuildSkippedStatus( ...
    "Negative controls skipped.");

if resolvedOptions.RunSyntheticOrientation || ...
        resolvedOptions.RunNegativeControls
    [syntheticSessionData, syntheticMetadataInfo, syntheticG3Results, ...
        syntheticOptions, syntheticTruth] = localBuildSyntheticFixture();
end

if resolvedOptions.RunSyntheticOrientation
    syntheticNoCorrectionAnalysis = helperAnalyzeG4PassiveBaselineMap( ...
        syntheticSessionData, syntheticMetadataInfo, syntheticG3Results, ...
        localMergeStructs(syntheticOptions, struct( ...
        "VerificationAppliedLag_samples", 0.0, ...
        "VerificationAppliedResidualFrequency_Hz", 0.0)));
    syntheticCorrectedAnalysis = helperAnalyzeG4PassiveBaselineMap( ...
        syntheticSessionData, syntheticMetadataInfo, syntheticG3Results, ...
        syntheticOptions);
    syntheticStatus = localRunSyntheticChecks( ...
        syntheticNoCorrectionAnalysis, syntheticCorrectedAnalysis, ...
        syntheticTruth);
end

if resolvedOptions.RunG3Regression || resolvedOptions.RunBaselineExecution || ...
        resolvedOptions.RunNegativeControls
    try
        loadOptions = struct("IncludeSamples", true);
        sessionData = loadIQData(datasetId, repoRoot, loadOptions);
    catch loadException
        error("verifyG4PassiveBaselineMapSlice:LoadSessionFailed", ...
            "Failed to load dataset %s: %s", datasetId, ...
            loadException.message);
    end

    collectionMetadataPath = fullfile(sessionData.DatasetRoot, ...
        "collection_metadata.json");

    try
        collectionMetadataInfo = helperReadCollectionMetadata( ...
            collectionMetadataPath, datasetId);
    catch metadataException
        error("verifyG4PassiveBaselineMapSlice:LoadMetadataFailed", ...
            "Failed to read collection metadata for dataset %s: %s", ...
            datasetId, metadataException.message);
    end
end

if resolvedOptions.RunG3Regression
    currentG3Analysis = helperAnalyzeG3SyncCore(sessionData, ...
        collectionMetadataInfo);
    g3RegressionStatus = localRunG3RegressionCheck(currentG3Analysis, ...
        resolvedOptions.G3BaselineSnapshotPath);
end

if resolvedOptions.RunBaselineExecution
    if resolvedOptions.UseSavedG3SnapshotForBaselineExecution && ...
            isfile(resolvedOptions.G3BaselineSnapshotPath)
        baselineData = load(resolvedOptions.G3BaselineSnapshotPath, ...
            "analysis");
        g3ForBaselineExecution = baselineData.analysis;
    else
        if isempty(fieldnames(currentG3Analysis))
            currentG3Analysis = helperAnalyzeG3SyncCore(sessionData, ...
                collectionMetadataInfo);
        end

        g3ForBaselineExecution = currentG3Analysis;
    end

    syncPrep = helperPrepareG3SyncInputs(sessionData, ...
        collectionMetadataInfo, struct(), g3ForBaselineExecution);
    baselineG4Analysis = helperAnalyzeG4PassiveBaselineMap(sessionData, ...
        collectionMetadataInfo, g3ForBaselineExecution);
    baselineStatus = localRunBaselineChecks(baselineG4Analysis, syncPrep);
end

if resolvedOptions.RunNegativeControls
    negativeControlStatus = localRunNegativeControls(sessionData, ...
        collectionMetadataInfo, syntheticSessionData, ...
        syntheticMetadataInfo, syntheticG3Results, syntheticOptions);
end

verification = struct();
verification.DatasetId = datasetId;
verification.StageId = "G4_Passive_Baseline_Analysis_Core";
verification.G3Regression = g3RegressionStatus;
verification.SyntheticOrientation = syntheticStatus;
verification.BaselineExecution = baselineStatus;
verification.NegativeControls = negativeControlStatus;
verification.Passed = g3RegressionStatus.Passed && ...
    syntheticStatus.Passed && baselineStatus.Passed && ...
    negativeControlStatus.Passed;

fprintf("G3 regression:\t%s\n", string(g3RegressionStatus.Status));
fprintf("Synthetic checks:\t%s\n", string(syntheticStatus.Status));
fprintf("Baseline checks:\t%s\n", string(baselineStatus.Status));
fprintf("Negative controls:\t%s\n", string(negativeControlStatus.Status));
fprintf("Overall verification:\t%s\n", string(verification.Passed));

end

function resolvedOptions = localResolveVerificationOptions(options)

resolvedOptions = struct();
resolvedOptions.G3BaselineSnapshotPath = fullfile("C:", "tmp", ...
    "g3_sync_core_baseline_before_refactor.mat");
resolvedOptions.RunG3Regression = true;
resolvedOptions.RunSyntheticOrientation = true;
resolvedOptions.RunBaselineExecution = true;
resolvedOptions.RunNegativeControls = true;
resolvedOptions.UseSavedG3SnapshotForBaselineExecution = true;

optionFields = fieldnames(options);

for idx = 1:numel(optionFields)
    fieldName = optionFields{idx};
    resolvedOptions.(fieldName) = options.(fieldName);
end

resolvedOptions.G3BaselineSnapshotPath = string( ...
    resolvedOptions.G3BaselineSnapshotPath);

end

function status = localBuildSkippedStatus(note)

status = struct();
status.Status = "skipped";
status.Passed = true;
status.Note = string(note);

end

function [sessionData, collectionMetadataInfo, g3SyncResults, options, ...
    truth] = localBuildSyntheticFixture()

rng(42, "twister");
datasetId = "synthetic_g4";
sampleRateHz = 10000;
samplesPerRepetition = 10000;
repetitionCount = 15;
knownDelaySamples = 20;
knownResidualFrequency_Hz = 30;
referenceSeed = complex(randn(samplesPerRepetition, 1), ...
    randn(samplesPerRepetition, 1));
radarScans = repmat(struct( ...
    "Samples", [], ...
    "RelativePath", "", ...
    "Repetition", NaN ...
    ), repetitionCount, 1);
repetition = (1:repetitionCount).';
relativePath = strings(repetitionCount, 1);
sampleRateColumn = repmat(sampleRateHz, repetitionCount, 1);
numSamplesColumn = repmat(samplesPerRepetition, repetitionCount, 1);
antenna1 = repmat("RF0:RX2", repetitionCount, 1);
antenna2 = repmat("RF1:RX2", repetitionCount, 1);

for idx = 1:repetitionCount
    time_s = (0:samplesPerRepetition - 1).' ./ sampleRateHz;
    reference = referenceSeed + 0.01 .* complex( ...
        randn(samplesPerRepetition, 1), ...
        randn(samplesPerRepetition, 1));
    surveillance = [ ...
        zeros(knownDelaySamples, 1); ...
        reference(1:end - knownDelaySamples) ...
        ];
    surveillance = surveillance .* exp(1j .* 2.0 .* pi .* ...
        knownResidualFrequency_Hz .* time_s);
    radarScans(idx).Samples = [surveillance reference];
    radarScans(idx).RelativePath = "synthetic/rep_" + idx + ".bb";
    radarScans(idx).Repetition = idx;
    relativePath(idx) = radarScans(idx).RelativePath;
end

radarTable = table(repetition, relativePath, sampleRateColumn, ...
    numSamplesColumn, antenna1, antenna2, VariableNames = ...
    {'Repetition', 'RelativePath', 'SampleRate_Hz', 'NumSamples', ...
    'Antenna1', 'Antenna2'});
sessionData = struct();
sessionData.DatasetId = datasetId;
sessionData.DatasetRoot = pwd;
sessionData.RadarTable = radarTable;
sessionData.RadarScans = radarScans;
sessionData.CpiContract = struct("CrossFileAllowed", false);
collectionMetadataInfo = struct();
collectionMetadataInfo.MetadataPresent = true;
collectionMetadataInfo.SessionIdMatches = true;
collectionMetadataInfo.ReferenceChannel = ...
    struct("ChannelLabel", "RF1:RX2");
collectionMetadataInfo.SurveillanceChannel = ...
    struct("ChannelLabel", "RF0:RX2");
g3SyncResults = struct();
g3SyncResults.OverallLabel = "ready";
g3SyncResults.RecommendedStrategyCandidate = ...
    "global_session_correction";
options = struct();
options.ExpectedDatasetId = datasetId;
options.ExpectedRepetitionCount = repetitionCount;
options.CorrelationSampleCount = 4096;
options.CorrelationMaxLagSamples = 64;
options.CoherenceWindowLength = 64;
options.CoherenceOverlap = 32;
options.CoherenceNfft = 64;
options.SpectrogramWindowLength = 64;
options.SpectrogramOverlap = 32;
options.SpectrogramNfft = 64;
options.SpectrogramMinimumBandBins = 8;
options.MapDecimationFactor = 10;
options.ReviewMapRows = 128;
options.ReviewMapCols = 128;
options.SceneReadyOffOriginNonzeroDopplerEnergyFraction = 0.95;
options.SceneCaveatedOffOriginNonzeroDopplerEnergyFraction = 0.90;
options.SceneReadyOffOriginOccupiedFraction = 0.25;
options.SceneCaveatedOffOriginOccupiedFraction = 0.20;
truth = struct();
truth.SampleRateHz = sampleRateHz;
truth.MapDecimationFactor = options.MapDecimationFactor;
truth.ExpectedRawDelay_samples = ...
    -knownDelaySamples / options.MapDecimationFactor;
truth.ExpectedRawDoppler_Hz = -knownResidualFrequency_Hz;
truth.DelayTolerance_samples = 1.0;
truth.DopplerTolerance_Hz = 3.0;

end

function status = localRunG3RegressionCheck(currentG3Analysis, ...
    baselineSnapshotPath)

status = struct();
status.Status = "passed";
status.Passed = true;
status.Note = "Current G3 output matched the saved pre-refactor snapshot.";

if ~isfile(baselineSnapshotPath)
    status.Status = "skipped";
    status.Passed = true;
    status.Note = "No saved pre-refactor G3 snapshot was available.";
    return
end

baselineData = load(baselineSnapshotPath, "analysis");
baselineAnalysis = baselineData.analysis;
localAssert(isequaln(currentG3Analysis.QuestionSummaries, ...
    baselineAnalysis.QuestionSummaries), ...
    "G3 question summaries changed after the sync-prep refactor.");
localAssert(isequaln(currentG3Analysis.LagTable, ...
    baselineAnalysis.LagTable), ...
    "G3 lag table changed after the sync-prep refactor.");
localAssert(isequaln(currentG3Analysis.ResidualFrequencyTable, ...
    baselineAnalysis.ResidualFrequencyTable), ...
    "G3 residual-frequency table changed after the sync-prep refactor.");
localAssert(isequaln(currentG3Analysis.CpiCoherenceTable, ...
    baselineAnalysis.CpiCoherenceTable), ...
    "G3 CPI coherence table changed after the sync-prep refactor.");
localAssert(isequaln(currentG3Analysis.StrategyComparisonTable, ...
    baselineAnalysis.StrategyComparisonTable), ...
    "G3 strategy comparison changed after the sync-prep refactor.");
localAssert(isequaln(currentG3Analysis.Interpretation, ...
    baselineAnalysis.Interpretation), ...
    "G3 interpretation changed after the sync-prep refactor.");

end

function status = localRunSyntheticChecks(syntheticNoCorrectionAnalysis, ...
    syntheticCorrectedAnalysis, syntheticTruth)

status = struct();
status.Status = "passed";
status.Passed = true;
status.Note = "Synthetic orientation and display-axis checks passed.";

medianRawDelay_samples = median( ...
    syntheticNoCorrectionAnalysis.MapSummaryTable.GlobalPeakDelay_samples);
medianRawDoppler_Hz = median( ...
    syntheticNoCorrectionAnalysis.MapSummaryTable.GlobalPeakDoppler_Hz);
localAssert(abs(medianRawDelay_samples - ...
    syntheticTruth.ExpectedRawDelay_samples) <= ...
    syntheticTruth.DelayTolerance_samples, ...
    "Synthetic raw delay sign convention check failed.");
localAssert(abs(medianRawDoppler_Hz - ...
    syntheticTruth.ExpectedRawDoppler_Hz) <= ...
    syntheticTruth.DopplerTolerance_Hz, ...
    "Synthetic raw Doppler sign convention check failed.");
localAssert(abs(median( ...
    syntheticCorrectedAnalysis.MapSummaryTable.DirectPathDelay_samples)) <= ...
    syntheticTruth.DelayTolerance_samples, ...
    "Synthetic corrected direct-path delay did not return to origin.");
localAssert(abs(median( ...
    syntheticCorrectedAnalysis.MapSummaryTable.DirectPathDoppler_Hz)) <= ...
    syntheticTruth.DopplerTolerance_Hz, ...
    "Synthetic corrected direct-path Doppler did not return to origin.");
localAssert(any(syntheticCorrectedAnalysis.MapSummaryTable.InterpretationLabel == ...
    "scene_limited_direct_path_dominated"), ...
    "Synthetic direct-path-dominated fixture did not produce a " + ...
    "scene-limited map label.");
localAssert(any(syntheticCorrectedAnalysis.MapSummaryTable.OriginNeighborhoodContainsGlobalPeak), ...
    "Synthetic fixture did not preserve origin containment.");
localAssert(all(syntheticCorrectedAnalysis.QuestionSummaries.InterpretationLabel( ...
    syntheticCorrectedAnalysis.QuestionSummaries.QuestionId == "Q2") ~= ...
    "ready"), ...
    "Synthetic direct-path-dominated fixture must not make Q2 ready.");
localAssert(all(syntheticCorrectedAnalysis.QuestionSummaries.InterpretationLabel( ...
    syntheticCorrectedAnalysis.QuestionSummaries.QuestionId == "Q4") ~= ...
    "ready"), ...
    "Synthetic direct-path-dominated fixture must not make Q4 ready.");

for idx = 1:numel(syntheticCorrectedAnalysis.RepresentativeMaps)
    representativeMap = syntheticCorrectedAnalysis.RepresentativeMaps(idx);
    localAssert(isequaln(representativeMap.DisplayDelayAxis_samples, ...
        representativeMap.DelayAxis_samples - ...
        representativeMap.DirectPathDelay_samples), ...
        "Display delay axis is not derived directly from the raw delay axis.");
    localAssert(isequaln(representativeMap.DisplayDopplerAxis_Hz, ...
        representativeMap.DopplerAxis_Hz - ...
        representativeMap.DirectPathDoppler_Hz), ...
        "Display Doppler axis is not derived directly from the raw " + ...
        "Doppler axis.");
end

end

function status = localRunBaselineChecks(baselineG4Analysis, syncPrep)

status = struct();
status.Status = "passed";
status.Passed = true;
status.Note = "Baseline helper execution and value-level checks passed.";

localAssert(height(baselineG4Analysis.MapSummaryTable) == 225, ...
    "MapSummaryTable must contain 225 rows.");
localAssert(height(baselineG4Analysis.RepeatabilityTable) == 15, ...
    "RepeatabilityTable must contain 15 rows.");
localAssert(height(baselineG4Analysis.CpiSelectionTable) == 5, ...
    "CpiSelectionTable must contain 5 rows.");
localAssert(height(baselineG4Analysis.QuestionSummaries) == 4, ...
    "QuestionSummaries must contain 4 rows.");
localAssert(numel(baselineG4Analysis.RepresentativeMaps) == 15, ...
    "RepresentativeMaps must contain 15 entries.");
localAssert(numel(baselineG4Analysis.RawAxisRepresentativeMaps) == 15, ...
    "RawAxisRepresentativeMaps must contain 15 entries.");
localAssert(height(baselineG4Analysis.FullRateAuditSummaryTable) == 9, ...
    "FullRateAuditSummaryTable must contain 9 rows.");
localAssert(strlength(string( ...
    baselineG4Analysis.RecommendedBaselineCpiLabel)) > 0, ...
    "RecommendedBaselineCpiLabel must be populated.");
localAssert(isequal(string({baselineG4Analysis.CpiDefinitions.Label}).', ...
    ["short"; "short_mid"; "medium"; "medium_long"; "long"]), ...
    "G4 CPI sensitivity set must contain the fixed five labels.");
requiredMapFields = [ ...
    "MapRateMode"; ...
    "MapDecimationFactor"; ...
    "MapSampleRateHz"; ...
    "RawDirectPathDelayOffset_samples"; ...
    "RawDirectPathDopplerOffset_Hz"; ...
    "OffOriginNonzeroDopplerEnergyFraction"; ...
    "ZeroDopplerRidgeEnergyFraction"; ...
    "OffOriginOccupiedFraction_abovePeakMinus20dB"; ...
    "DirectPathToOffRidgeEnergy_dB" ...
    ];
for fieldIndex = 1:numel(requiredMapFields)
    localAssert(any(string(baselineG4Analysis.MapSummaryTable.Properties.VariableNames) == ...
        requiredMapFields(fieldIndex)), ...
        "MapSummaryTable is missing required field " + ...
        requiredMapFields(fieldIndex) + ".");
end

requiredSelectionFields = [ ...
    "SceneObservabilityScore"; ...
    "RepeatabilityScore"; ...
    "CoordinateStabilityScore"; ...
    "RateAuditAgreementLabel"; ...
    "SensitivitySetMember" ...
    ];
for fieldIndex = 1:numel(requiredSelectionFields)
    localAssert(any(string(baselineG4Analysis.CpiSelectionTable.Properties.VariableNames) == ...
        requiredSelectionFields(fieldIndex)), ...
        "CpiSelectionTable is missing required field " + ...
        requiredSelectionFields(fieldIndex) + ".");
end

localAssert(all(baselineG4Analysis.MapSummaryTable.MapRateMode == ...
    "reduced_rate_main_product"), ...
    "Reduced-rate map rows must report their map-rate mode.");
localAssert(all(baselineG4Analysis.MapSummaryTable.MapDecimationFactor == ...
    baselineG4Analysis.Options.MapDecimationFactor), ...
    "MapSummaryTable decimation factors must match Options.");
localAssert(all(baselineG4Analysis.MapSummaryTable.MapSampleRateHz == ...
    baselineG4Analysis.Options.MapSampleRateHz), ...
    "MapSummaryTable sample rates must match Options.");
localAssert(all(ismember(baselineG4Analysis.MapSummaryTable.InterpretationLabel, ...
    ["implementation_suspect"; ...
    "scene_limited_direct_path_dominated"; ...
    "reviewable_scene_present"])), ...
    "MapSummaryTable contains an unsupported map interpretation label.");
localAssert(any(string(baselineG4Analysis.FullRateAuditSummaryTable.Properties.VariableNames) == ...
    "RawRateAuditMethod"), ...
    "FullRateAuditSummaryTable must report the raw-rate audit method.");
localAssert(all(baselineG4Analysis.FullRateAuditSummaryTable.RawRateAuditMethod == ...
    "ambgfun_cut_proxy"), ...
    "FullRateAuditSummaryTable must use the bounded ambgfun cut proxy.");
localAssert(all(ismember(baselineG4Analysis.FullRateAuditSummaryTable.AgreementLabel, ...
    ["agreement"; "caveated_agreement"; "disagreement"])), ...
    "FullRateAuditSummaryTable contains an unsupported agreement label.");
localAssert(all(baselineG4Analysis.CpiSelectionTable.SensitivitySetMember), ...
    "All G4 CPI rows must be marked as sensitivity-set members.");
localAssert(all(baselineG4Analysis.MapSummaryTable.AppliedLag_samples == ...
    syncPrep.GlobalCorrection.AppliedLag_samples), ...
    "G4 applied lag does not match the shared sync-prep output.");
localAssert(all(abs( ...
    baselineG4Analysis.MapSummaryTable.AppliedResidualFrequency_Hz - ...
    syncPrep.GlobalCorrection.AppliedResidualFrequency_Hz) <= 1.0e-12), ...
    "G4 applied residual frequency does not match the shared sync-prep output.");
localAssert(all(isfinite( ...
    baselineG4Analysis.RepeatabilityTable.MaskedLinearCorrelationMedian)), ...
    "Masked repeatability correlations must be finite.");
localAssert(all(abs( ...
    baselineG4Analysis.RepeatabilityTable.MaskedLinearCorrelationMedian) ...
    <= 1.0), ...
    "Masked repeatability correlations must stay within [-1, 1].");
localAssert(isfield(baselineG4Analysis.Interpretation, ...
    "OverallLabel") && isfield(baselineG4Analysis.Interpretation, ...
    "UpstreamValidityLabel") && isfield( ...
    baselineG4Analysis.Interpretation, ...
    "SceneObservabilityLabel") && isfield( ...
    baselineG4Analysis.Interpretation, ...
    "ImplementationConfidenceLabel") && isfield( ...
    baselineG4Analysis.Interpretation, ...
    "FullRateAuditAgreementLabel") && isfield( ...
    baselineG4Analysis.Interpretation, ...
    "ReducedRateAuditCaveatCodes"), ...
    "Interpretation is missing one or more required labels.");

for idx = 1:numel(baselineG4Analysis.RepresentativeMaps)
    representativeMap = baselineG4Analysis.RepresentativeMaps(idx);
    mapSize = size(representativeMap.Map_dB);
    localAssert(numel(representativeMap.DelayAxis_samples) == mapSize(2), ...
        "Representative map delay axis length does not match the map width.");
    localAssert(numel(representativeMap.DopplerAxis_Hz) == mapSize(1), ...
        "Representative map Doppler axis length does not match the map height.");
    localAssert(all(diff(representativeMap.DelayAxis_samples) > 0.0), ...
        "Representative map delay axis must be strictly monotonic.");
    localAssert(all(diff(representativeMap.DopplerAxis_Hz) > 0.0), ...
        "Representative map Doppler axis must be strictly monotonic.");
    localAssert(isequaln(representativeMap.DisplayDelayAxis_samples, ...
        representativeMap.DelayAxis_samples - ...
        representativeMap.DirectPathDelay_samples), ...
        "Representative map display delay axis is inconsistent.");
    localAssert(isequaln(representativeMap.DisplayDopplerAxis_Hz, ...
        representativeMap.DopplerAxis_Hz - ...
        representativeMap.DirectPathDoppler_Hz), ...
        "Representative map display Doppler axis is inconsistent.");
    localAssert(abs(representativeMap.DirectPathDelay_samples) <= ...
        baselineG4Analysis.BaselineProductDefinition. ...
        OriginSearchDelayRadius_samples, ...
        "Representative direct-path delay is outside the declared " + ...
        "origin-search neighborhood.");
    localAssert(abs(representativeMap.DirectPathDoppler_Hz) <= ...
        baselineG4Analysis.BaselineProductDefinition. ...
        OriginSearchDopplerRadius_Hz, ...
        "Representative direct-path Doppler is outside the declared " + ...
        "origin-search neighborhood.");
end

end

function status = localRunNegativeControls(sessionData, ...
    collectionMetadataInfo, ...
    syntheticSessionData, syntheticMetadataInfo, syntheticG3Results, ...
    syntheticOptions)

status = struct();
status.Status = "passed";
status.Passed = true;
status.Note = "Negative controls behaved as expected.";

localExpectError(@() helperAnalyzeG4PassiveBaselineMap(sessionData, ...
    collectionMetadataInfo, struct(), struct()), ...
    "helperAnalyzeG4PassiveBaselineMap:MissingG3Result");
localExpectError(@() helperAnalyzeG4PassiveBaselineMap(sessionData, ...
    collectionMetadataInfo, struct("OverallLabel", "blocked", ...
    "RecommendedStrategyCandidate", "global_session_correction"), ...
    struct()), ...
    "helperAnalyzeG4PassiveBaselineMap:NonQualifyingG3Status");
localExpectError(@() helperAnalyzeG4PassiveBaselineMap(sessionData, ...
    collectionMetadataInfo, struct("OverallLabel", "ready", ...
    "RecommendedStrategyCandidate", "per_capture_correction"), ...
    struct()), ...
    "helperAnalyzeG4PassiveBaselineMap:UnexpectedG3Strategy");

syntheticSyncPrep = helperPrepareG3SyncInputs(syntheticSessionData, ...
    syntheticMetadataInfo, syntheticOptions, syntheticG3Results);

signFlipAnalysis = helperAnalyzeG4PassiveBaselineMap( ...
    syntheticSessionData, syntheticMetadataInfo, syntheticG3Results, ...
    localMergeStructs(syntheticOptions, struct( ...
    "VerificationAppliedLag_samples", ...
    -syntheticSyncPrep.GlobalCorrection.AppliedLag_samples, ...
    "VerificationAppliedResidualFrequency_Hz", ...
    -syntheticSyncPrep.GlobalCorrection.AppliedResidualFrequency_Hz)));
localAssert(any(signFlipAnalysis.MapSummaryTable.InterpretationLabel == ...
    "implementation_suspect"), ...
    "The sign-flipped correction negative control did not produce an " + ...
    "implementation-suspect label.");

end

function outputStruct = localMergeStructs(baseStruct, updateStruct)

outputStruct = baseStruct;
fieldNames = fieldnames(updateStruct);

for idx = 1:numel(fieldNames)
    outputStruct.(fieldNames{idx}) = updateStruct.(fieldNames{idx});
end

end

function localExpectError(functionHandle, expectedIdentifier)

didError = false;

try
    functionHandle();
catch caughtException
    didError = true;
    localAssert(caughtException.identifier == expectedIdentifier, ...
        "Unexpected error identifier: " + ...
        string(caughtException.identifier));
end

localAssert(didError, "Expected the helper to throw an error.");

end

function localAssert(condition, message)

if ~condition
    error("verifyG4PassiveBaselineMapSlice:AssertionFailed", "%s", ...
        message);
end

end
