classdef g4RCancellationCharacterizationTest < matlab.unittest.TestCase
    %G4RCANCELLATIONCHARACTERIZATIONTEST Focused G4-R cancellation tests.

    properties (SetAccess = private)
        RepoRoot
    end

    methods (TestClassSetup)
        function addRepositoryToPath(testCase)
            testFile = string(mfilename("fullpath"));
            testCase.RepoRoot = fileparts(fileparts(testFile));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.RepoRoot));
        end
    end

    methods (TestMethodSetup)
        function preserveRandomState(testCase)
            originalRandomState = rng;
            testCase.addTeardown(@() rng(originalRandomState));
        end
    end

    methods (Test)
        function testRegularizedWienerRecoversKnownFir(testCase)
            rng(501, "twister");
            reference = complex(randn(8192, 1), randn(8192, 1));
            knownCoefficients = [0.8 + 0.1j; -0.25 + 0.15j; 0.1 - 0.05j];
            desired = filter(knownCoefficients, 1, reference);

            estimate = helperEstimateG4RWienerFir( ...
                reference, desired, numel(knownCoefficients), ...
                struct("RegularizationFraction", 1.0e-6));

            recoveryError = norm(estimate.Coefficients - knownCoefficients) ./ ...
                norm(knownCoefficients);
            testCase.verifyLessThan(recoveryError, 0.02);
            testCase.verifyEqual(estimate.CorrelationEstimator, ...
                "xcorr_biased");
        end

        function testFrozenNativeNlmsExplicitlyDisablesScoreAdaptation(testCase)
            rng(502, "twister");
            calibrationReference = complex(randn(4096, 1), randn(4096, 1));
            scoreReference = complex(randn(4096, 1), randn(4096, 1));
            calibrationSurveillance = filter([0.7; -0.2], 1, ...
                calibrationReference);
            scoreSurveillance = filter([0.7; -0.2], 1, scoreReference);

            result = helperApplyG4RNativeFirstCancellation( ...
                calibrationReference, calibrationSurveillance, ...
                scoreReference, scoreSurveillance, "frozen_nlms");

            testCase.verifyFalse(result.ScoreAdaptationEnabled);
            testCase.verifyTrue(all(isfinite(result.ResidualSignal)));
            testCase.verifyGreaterThan(result.MaxStepSize, 0.0);
        end

        function testNativeFirstResidualUsesProductionResamplePath(testCase)
            rng(503, "twister");
            reference = complex(randn(8001, 1), randn(8001, 1));
            surveillance = filter([0.6; -0.15], 1, reference);
            estimate = helperEstimateG4RWienerFir( ...
                reference(1:4096), surveillance(1:4096), 2.0);

            cancellation = helperApplyG4RNativeFirstCancellation( ...
                reference(1:4096), surveillance(1:4096), ...
                reference, surveillance, "wiener_fir", ...
                struct("WienerCoefficients", estimate.Coefficients));
            [reducedResidual, coefficients] = helperResampleG4FullRepetition( ...
                cancellation.ResidualSignal, 4.0);
            reconstruction = helperReconstructG4Resample( ...
                cancellation.ResidualSignal, 4.0, coefficients);

            testCase.verifyEqual(numel(reducedResidual), ...
                reconstruction.ActualOutputSampleCount, AbsTol=0.0);
            testCase.verifyTrue(all(isfinite( ...
                reconstruction.FilteredNativeOutput)));
        end

        function testDryRunPreservesFixedTargetFreeManifest(testCase)
            result = runG4RCancellationCharacterization( ...
                testCase.RepoRoot, struct( ...
                "ExecutionMode", "dry_run", "SaveResult", false));

            manifest = result.Manifest.ControlTable;
            testCase.verifyEqual(height(manifest), 9.0, AbsTol=0.0);
            testCase.verifyTrue(all( ...
                manifest.CalibrationRepetition ~= manifest.ScoreRepetition));
            testCase.verifyTrue(all(manifest.CalibrationTargetFree));
            testCase.verifyEqual(result.Configuration.MapContract, ...
                "r4_factor200_production_full_map_common_physical_grid");
            testCase.verifyFalse(result.FormalG5Enabled);
            testCase.verifyFalse(result.FormalG6Enabled);
            testCase.verifyFalse(result.FormalG8Enabled);
        end

        function testSelectedScoreManifestRetainsPartAndEpoch(testCase)
            outputRoot = string(tempname);
            mkdir(outputRoot);
            testCase.addTeardown(@() rmdir(outputRoot, "s"));
            [baseManifestPath, scoreScan] = localSelectedScoreManifestFixture( ...
                outputRoot);
            selectedManifestRoot = fullfile(outputRoot, "selected_score");

            selection = helperBuildG4RSelectedScoreManifest( ...
                baseManifestPath, scoreScan, selectedManifestRoot);
            selectedManifest = jsondecode(fileread(selection.ManifestPath));

            testCase.verifyTrue(selection.SinglePartContract);
            testCase.verifyEqual( ...
                string(fileparts(selection.ManifestPath)), ...
                string(selectedManifestRoot));
            [~, manifestName, manifestExtension] = fileparts( ...
                selection.ManifestPath);
            testCase.verifyEqual(string(manifestName) + ...
                string(manifestExtension), "session_manifest.json");
            testCase.verifyEqual(numel(selectedManifest.radar_files), 1.0, ...
                AbsTol=0.0);
            testCase.verifyEqual(string(selectedManifest.radar_files{1}), ...
                string(scoreScan.FilePath));
            testCase.verifyEqual(selectedManifest.radar_epoch_utc, ...
                scoreScan.RecordingUTC, AbsTol=1.0e-12);
            testCase.verifyEqual(selectedManifest.capture_duration_s, ...
                scoreScan.Duration_s, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                selectedManifest.g4r_selected_score_capture.source_score_repetition, ...
                scoreScan.Repetition, AbsTol=0.0);

            producerRoot = fullfile(fileparts(testCase.RepoRoot), ...
                "flightTest_SynthDataBranch", "SyntheticHDTVSimulation");
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(producerRoot));
            context = helperSyntheticResolveSessionContext( ...
                selection.ManifestPath, RepoRoot=fileparts(testCase.RepoRoot));
            testCase.verifyEqual(string(context.radar_files{1}), ...
                string(scoreScan.FilePath));
            testCase.verifyEqual(context.radar_epoch_utc, ...
                scoreScan.RecordingUTC, AbsTol=1.0e-12);
        end

        function testDecisionRulesRequireMapSuppressionAndTargetGuard(testCase)
            [mapRateTable, targetGuardTable] = localDecisionFixture();
            selection = struct("Nominated", false);
            decision = helperEvaluateG4RCancellationDecision( ...
                mapRateTable, targetGuardTable, selection);

            frozenRow = decision.MethodDecisionTable( ...
                decision.MethodDecisionTable.Method == "frozen_native_nlms", :);
            resetRow = decision.MethodDecisionTable( ...
                decision.MethodDecisionTable.Method == "current_reset_nlms", :);
            testCase.verifyTrue( ...
                frozenRow.RecommendReviewedUpstreamCorrection);
            testCase.verifyFalse( ...
                resetRow.RecommendReviewedUpstreamCorrection);
            testCase.verifyEqual(decision.Outcome, ...
                "candidate_requires_reviewed_upstream_correction");

            mapRateTable.ReducedDirectPathToOffRidge_dB( ...
                mapRateTable.Method == "frozen_native_nlms") = 8.0;
            decision = helperEvaluateG4RCancellationDecision( ...
                mapRateTable, targetGuardTable, selection);
            testCase.verifyEqual(decision.Outcome, ...
                "rate_order_semantics_supported_no_promoted_candidate");
        end

        function testCoordinatorRequiresExactIsolatedShardManifest(testCase)
            outputRoot = string(tempname);
            mkdir(outputRoot);
            testCase.addTeardown(@() rmdir(outputRoot, "s"));
            benchmarkPath = fullfile(outputRoot, "benchmark.mat");
            benchmark = localCoordinatorBenchmarkFixture(benchmarkPath);
            result = benchmark;
            save(benchmarkPath, "result");

            backgroundIds = unique( ...
                string(benchmark.Manifest.ControlTable.BackgroundId), ...
                "stable");
            shardPaths = strings(numel(backgroundIds), 1);

            for backgroundIndex = 1:numel(backgroundIds)
                shardPaths(backgroundIndex) = fullfile(outputRoot, ...
                    "shard_" + backgroundIds(backgroundIndex) + ".mat");
                shard = localCoordinatorShardFixture( ...
                    backgroundIds(backgroundIndex), benchmarkPath, ...
                    benchmark.Manifest);
                result = shard;
                save(shardPaths(backgroundIndex), "result");
            end

            combined = runG4RCancellationCharacterizationCoordinator( ...
                testCase.RepoRoot, struct( ...
                "BenchmarkResultPath", benchmarkPath, ...
                "ShardResultPaths", shardPaths, ...
                "OutputRoot", outputRoot, "SaveResult", true));

            testCase.verifyEqual(height(combined.ShardAuditTable), 3.0, ...
                AbsTol=0.0);
            testCase.verifyEqual(height(combined.MapRateMetricTable), 27.0, ...
                AbsTol=0.0);
            testCase.verifyTrue(isfile(fullfile( ...
                combined.BundleRoot, "report_manifest.json")));
            testCase.verifyTrue(combined.HtmlReport.ExternalDependencyFree);
        end

        function testHtmlReportUsesLocalAssetsOnly(testCase)
            outputRoot = string(tempname);
            mkdir(outputRoot);
            testCase.addTeardown(@() rmdir(outputRoot, "s"));
            reportInput = localBuildReportFixture();

            report = helperBuildG4RCancellationHtmlReport( ...
                reportInput, outputRoot);

            testCase.verifyTrue(isfile(report.HtmlPath));
            testCase.verifyTrue(isfolder(report.AssetRoot));
            testCase.verifyEqual(height(report.FigureTable), 3.0, ...
                AbsTol=0.0);
            testCase.verifyTrue(all(isfile(fullfile( ...
                outputRoot, report.FigureTable.RelativePath))));
            testCase.verifyTrue(report.ExternalDependencyFree);
            testCase.verifyTrue(contains( ...
                string(fileread(report.HtmlPath)), "report_assets/"));
            testCase.verifyTrue(contains( ...
                string(fileread(report.HtmlPath)), "href=""summary.html"""));
        end
    end
end

function [baseManifestPath, scoreScan] = localSelectedScoreManifestFixture(outputRoot)

scoreCapturePath = fullfile(outputRoot, "score_part_5.bb");
fileIdentifier = fopen(scoreCapturePath, "w");
cleanupFile = onCleanup(@() fclose(fileIdentifier));
fwrite(fileIdentifier, uint8([1 2 3 4]), "uint8");
clear cleanupFile

adsbPath = fullfile(outputRoot, "score_truth.gz");
fileIdentifier = fopen(adsbPath, "w");
cleanupFile = onCleanup(@() fclose(fileIdentifier));
fwrite(fileIdentifier, uint8([5 6 7 8]), "uint8");
clear cleanupFile

baseManifest = struct( ...
    "session_id", "fixture_session", ...
    "session_folder", "fixture_session", ...
    "capture_duration_s", 1.0, ...
    "capture_repetitions", 15.0, ...
    "capture_repetition_spacing_s", 1.0, ...
    "radar_active_window_s", 29.0, ...
    "radar_recorded_iq_seconds_s", 15.0, ...
    "radar_epoch_utc", 1000.0, ...
    "sdr_defaults", struct( ...
    "sample_rate_hz", 6.144e6, "center_frequency_hz", 599e6), ...
    "radar_files", {{scoreCapturePath}}, ...
    "adsb_files", {{adsbPath}});
baseManifestPath = fullfile(outputRoot, "session_manifest.json");
writelines(jsonencode(baseManifest, PrettyPrint=true), baseManifestPath);

scoreScan = struct( ...
    "FilePath", string(scoreCapturePath), ...
    "RecordingUTC", 1010.125, ...
    "Duration_s", 1.0, ...
    "SampleRate", 6.144e6, ...
    "CenterFrequency", 599e6, ...
    "Repetition", 5.0);
end

function [mapRateTable, targetGuardTable] = localDecisionFixture()

backgroundId = repmat("background", 6, 1);
timePairId = [ ...
    "1_to_2"; "4_to_5"; "1_to_2"; "4_to_5"; "1_to_2"; "4_to_5"];
method = [ ...
    "none"; "none"; "current_reset_nlms"; "current_reset_nlms"; ...
    "frozen_native_nlms"; "frozen_native_nlms"];
allPairCriteriaPass = [true; true; false; true; true; true];
reducedDirectPathToOffRidge_dB = [10.0; 10.0; 7.0; 7.0; 6.0; 6.0];
mapRateTable = table( ...
    backgroundId, timePairId, method, allPairCriteriaPass, ...
    reducedDirectPathToOffRidge_dB, ...
    VariableNames=["BackgroundId", "TimePairId", "Method", ...
    "AllPairCriteriaPass", "ReducedDirectPathToOffRidge_dB"]);

targetGuardTable = table( ...
    ["none"; "current_reset_nlms"; "frozen_native_nlms"], ...
    [true; true; true], [10.0; 8.5; 9.5], ...
    VariableNames=["Method", "TruthPeakWithinOneCell", ...
    "InjectedVsControlTruthContrast_dB"]);

end

function benchmark = localCoordinatorBenchmarkFixture(benchmarkPath)

backgroundId = repelem( ...
    ["background_a"; "background_b"; "background_c"], 3, 1);
timePairId = repmat(["1_to_2"; "4_to_5"; "9_to_10"], 3, 1);
pairPosition = repmat(["early"; "center"; "late"], 3, 1);
calibrationRepetition = repmat([1.0; 4.0; 9.0], 3, 1);
scoreRepetition = repmat([2.0; 5.0; 10.0], 3, 1);
controlTable = table( ...
    backgroundId, timePairId, pairPosition, calibrationRepetition, ...
    scoreRepetition, true(9, 1), repmat(0.1, 9, 1), ...
    VariableNames=["BackgroundId", "TimePairId", "PairPosition", ...
    "CalibrationRepetition", "ScoreRepetition", ...
    "CalibrationTargetFree", "CpiDuration_s"]);

benchmark = struct();
benchmark.SchemaVersion = "g4r_cancellation_characterization_v1";
benchmark.ExecutionMode = "benchmark";
benchmark.ResultPath = string(benchmarkPath);
benchmark.Configuration = struct( ...
    "MapContract", "r4_factor200_production_full_map_common_physical_grid");
benchmark.Manifest = struct( ...
    "ControlTable", controlTable, ...
    "ExpectedControlCount", 9.0, ...
    "TargetGuardBackgroundId", "background_a", ...
    "TargetGuardTimePairId", "4_to_5");
benchmark.Projection = struct("FitsAuthorizedBudget", true);
benchmark.WienerSelection = struct( ...
    "Nominated", false, "SelectedTapCount", NaN);
benchmark.WienerSearchDetailTable = table( ...
    strings(0, 1), VariableNames="BackgroundId");
benchmark.WienerSelectionTable = table( ...
    [1.0; 8.0], [0.0; 1.14], [0.0; 0.57], [0.0; 3.0], ...
    [1.0; 5.0], [true; true], ...
    VariableNames=["TapCount", "FirSpan_us", ...
    "ImpulseEnergyCentroidDelay_us", "ImpulseEnergy95Delay_us", ...
    "MedianHeldOutCancellationDepth_dB", ...
    "AllControlsNonnegativeCancellation"]);

end

function shard = localCoordinatorShardFixture( ...
        backgroundId, benchmarkPath, manifest)

controlRows = manifest.ControlTable( ...
    manifest.ControlTable.BackgroundId == backgroundId, :);
methods = ["none"; "current_reset_nlms"; "frozen_native_nlms"];
rowCount = height(controlRows) .* numel(methods);
mapBackgroundId = strings(rowCount, 1);
mapTimePairId = strings(rowCount, 1);
mapMethod = strings(rowCount, 1);
mapCriteriaPass = true(rowCount, 1);
mapDirectPathRatio = zeros(rowCount, 1);
rowIndex = 0;

for controlIndex = 1:height(controlRows)
    for methodIndex = 1:numel(methods)
        rowIndex = rowIndex + 1;
        mapBackgroundId(rowIndex) = backgroundId;
        mapTimePairId(rowIndex) = controlRows.TimePairId(controlIndex);
        mapMethod(rowIndex) = methods(methodIndex);

        switch methods(methodIndex)
            case "none"
                mapDirectPathRatio(rowIndex) = 10.0;
            case "current_reset_nlms"
                mapDirectPathRatio(rowIndex) = 8.0;
            otherwise
                mapDirectPathRatio(rowIndex) = 6.0;
        end
    end
end

mapRateMetricTable = table( ...
    mapBackgroundId, mapTimePairId, mapMethod, mapCriteriaPass, ...
    mapDirectPathRatio, ...
    VariableNames=["BackgroundId", "TimePairId", "Method", ...
    "AllPairCriteriaPass", "ReducedDirectPathToOffRidge_dB"]);
heldOutMetricTable = localCoordinatorHeldOutFixture(mapRateMetricTable);

if backgroundId == manifest.TargetGuardBackgroundId
    targetGuardTable = table( ...
        methods, true(numel(methods), 1), [10.0; 9.0; 9.5], ...
        VariableNames=["Method", "TruthPeakWithinOneCell", ...
        "InjectedVsControlTruthContrast_dB"]);
else
    targetGuardTable = table( ...
        strings(0, 1), false(0, 1), zeros(0, 1), ...
        VariableNames=["Method", "TruthPeakWithinOneCell", ...
        "InjectedVsControlTruthContrast_dB"]);
end

shard = struct();
shard.SchemaVersion = "g4r_cancellation_characterization_v1";
shard.ExecutionMode = "background_shard";
shard.ResultPath = "";
shard.Configuration = struct("BenchmarkResultPath", string(benchmarkPath));
shard.WienerSelection = struct( ...
    "Nominated", false, "SelectedTapCount", NaN);
shard.MapRateMetricTable = mapRateMetricTable;
shard.HeldOutMetricTable = heldOutMetricTable;
shard.TargetGuardTable = targetGuardTable;
shard.WienerCoefficientRecords = struct([]);
shard.HardwareEvidenceTable = table( ...
    backgroundId, "antenna", "name", "recorded", "recorded", ...
    VariableNames=["BackgroundId", "EvidenceCategory", "MetadataField", ...
    "RecordedValue", "EvidenceStatus"]);
shard.SourceFingerprintTable = table( ...
    backgroundId, "source", "fixture", ...
    VariableNames=["BackgroundId", "Category", "Sha256"]);
shard.BackgroundContractTable = table( ...
    backgroundId, "single_configuration_not_compared", ...
    "not_established_from_this_study", ...
    VariableNames=["BackgroundId", "HardwareConfigurationStatus", ...
    "HardwareSufficiencyStatus"]);

end

function heldOutMetricTable = localCoordinatorHeldOutFixture(mapRateMetricTable)

rowCount = height(mapRateMetricTable) .* 2;
backgroundId = repelem(string(mapRateMetricTable.BackgroundId), 2, 1);
timePairId = repelem(string(mapRateMetricTable.TimePairId), 2, 1);
method = repelem(string(mapRateMetricTable.Method), 2, 1);
processingRate = repmat(["native"; "reduced"], ...
    height(mapRateMetricTable), 1);
cancellationDepth_dB = zeros(rowCount, 1);
heldOutMetricTable = table( ...
    backgroundId, timePairId, method, processingRate, cancellationDepth_dB, ...
    VariableNames=["BackgroundId", "TimePairId", "Method", ...
    "ProcessingRate", "CancellationDepth_dB"]);

end

function result = localBuildReportFixture()

result = struct();
result.Question = "fixture";
result.Outcome = "fixture";
result.MapRateValidityStatus = "retune_pending_bounded_correction";
result.CollectionSuitabilityStatus = "blocked";
result.DecisionRationale = "fixture";
result.NextAction = "fixture";
result.HardwareEvidenceTable = table( ...
    "background", "antenna", "name", "recorded", "recorded", ...
    VariableNames=["BackgroundId", "EvidenceCategory", "MetadataField", ...
    "RecordedValue", "EvidenceStatus"]);
result.WienerSelectionTable = table( ...
    [1.0; 8.0], [0.0; 1.14], [0.0; 0.57], [0.0; 3.0], ...
    [1.0; 5.0], [true; true], ...
    VariableNames=["TapCount", "FirSpan_us", ...
    "ImpulseEnergyCentroidDelay_us", "ImpulseEnergy95Delay_us", ...
    "MedianHeldOutCancellationDepth_dB", "AllControlsNonnegativeCancellation"]);
result.HeldOutMetricTable = table( ...
    ["none"; "wiener_fir"], ["native"; "native"], [0.0; 5.0], ...
    VariableNames=["Method", "ProcessingRate", "CancellationDepth_dB"]);
result.MapRateMetricTable = table( ...
    "none", "1_to_2", 0.99, ...
    VariableNames=["Method", "TimePairId", "NormalizedMapCorrelation"]);
result.TargetGuardTable = table( ...
    "none", true, 0.0, ...
    VariableNames=["Method", "TruthPeakWithinOneCell", ...
    "InjectedVsControlTruthContrast_dB"]);
result.MethodDecisionTable = table( ...
    ["none"; "wiener_fir"], [0.0; 5.0], [0.0; 0.5], ...
    VariableNames=["Method", "MedianDirectPathSuppression_dB", ...
    "TargetContrastLoss_dB"]);
result.SourceFingerprintTable = table( ...
    "fixture", "source", "abc", ...
    VariableNames=["BackgroundId", "Category", "Sha256"]);
result.ArtifactLinkTable = table( ...
    "summary.html", "fixture", ...
    VariableNames=["RelativePath", "Description"]);

end
