classdef helperAnalyzeDirectPathQuickViewTest < matlab.unittest.TestCase
    %HELPERANALYZEDIRECTPATHQUICKVIEWTEST Direct-path evidence regression.

    properties (SetAccess = private)
        RepoRoot
        QuickResult
        ConfirmClippingResult
    end

    methods (TestClassSetup)
        function analyzeReferenceComparisons(testCase)
            testFile = string(mfilename("fullpath"));
            testCase.RepoRoot = fileparts(fileparts(testFile));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.RepoRoot));
            testCase.QuickResult = helperAnalyzeDirectPathQuickView( ...
                "20260827T135456", "20260827T141921", ...
                testCase.RepoRoot, struct("Mode", "quick"));
            testCase.ConfirmClippingResult = ...
                helperAnalyzeDirectPathQuickView( ...
                "20260827T135456", "20260827T140613", ...
                testCase.RepoRoot, struct("Mode", "confirm"));
        end
    end

    methods (Test)
        function testQuickModeAndDeterioration(testCase)
            result = testCase.QuickResult;
            comparison = result.ComparisonTable;
            amplitudeRows = comparison(ismember(comparison.MetricId, ...
                ["mean_iq_power", "atsc_pilot_psd", ...
                "atsc_band_power"]), :);

            testCase.verifyEqual( ...
                result.Baseline.SelectedManifestIndices, [1, 8, 15]);
            testCase.verifyEqual( ...
                result.Candidate.SelectedManifestIndices, [1, 8, 15]);
            testCase.verifyEqual(result.WindowDuration_s, 0.125, ...
                AbsTol=eps);
            testCase.verifyGreaterThanOrEqual( ...
                amplitudeRows.DeltaReference, -20.5);
            testCase.verifyLessThanOrEqual( ...
                amplitudeRows.DeltaReference, -13.0);
            testCase.verifyLessThanOrEqual( ...
                amplitudeRows.DeltaReferenceMinusSurveillance, -13.0);
            testCase.verifyEqual(result.Trend.Label, "WORSE");
        end

        function testEveryReportedDifferenceIsPairedArithmetic(testCase)
            [reportedValues, expectedValues, nonApplicableValues] = ...
                localBuildDifferenceAudit(testCase.QuickResult);

            testCase.verifyEqual(reportedValues, expectedValues, ...
                AbsTol=1.0e-10);
            testCase.verifyTrue(all(isnan(nonApplicableValues)));
        end

        function testEveryLabelHasCompleteEvidence(testCase)
            evidence = testCase.QuickResult.EvidenceTable;
            textVariables = ["Check", "ObservedValues", "Units", ...
                "ComparisonDirection", "Criterion", "Source", ...
                "Result", "Explanation"];
            populated = localEvidenceFieldsPopulated(evidence, ...
                textVariables);
            permittedSources = ismember(evidence.Source, ...
                ["existing G2", "field-screen heuristic", ...
                "informational"]);

            testCase.verifyTrue(all(populated));
            testCase.verifyTrue(all(permittedSources));
        end

        function testConfirmModeExposesClipping(testCase)
            result = testCase.ConfirmClippingResult;
            candidateMetrics = result.Candidate.ChannelMetricTable;
            clippingRow = result.EvidenceTable( ...
                result.EvidenceTable.Check == "Clipping", :);

            testCase.verifyEqual( ...
                result.Candidate.SelectedManifestIndices, 1:15);
            testCase.verifyGreaterThan( ...
                max(candidateMetrics.ExactRailSampleCount), 0);
            testCase.verifyNotEqual(clippingRow.Result, "Met");
            testCase.verifyNotEmpty(clippingRow.ObservedValues);
        end
    end
end

function [reportedValues, expectedValues, nonApplicableValues] = ...
    localBuildDifferenceAudit(result)

comparison = result.ComparisonTable;
applicableRows = comparison.DifferenceApplicable;
nonApplicableRows = ~applicableRows;
baselineExpected = localPairedDifferenceMedians( ...
    result.Baseline, comparison.FieldName(applicableRows));
candidateExpected = localPairedDifferenceMedians( ...
    result.Candidate, comparison.FieldName(applicableRows));
reportedValues = [ ...
    comparison.BaselineReferenceMinusSurveillance(applicableRows); ...
    comparison.CandidateReferenceMinusSurveillance(applicableRows); ...
    comparison.DeltaReference; ...
    comparison.DeltaSurveillance; ...
    comparison.DeltaReferenceMinusSurveillance(applicableRows) ...
    ];
expectedValues = [ ...
    baselineExpected; ...
    candidateExpected; ...
    comparison.CandidateReference - comparison.BaselineReference; ...
    comparison.CandidateSurveillance - ...
    comparison.BaselineSurveillance; ...
    candidateExpected - baselineExpected ...
    ];
nonApplicableValues = [ ...
    comparison.BaselineReferenceMinusSurveillance(nonApplicableRows); ...
    comparison.CandidateReferenceMinusSurveillance(nonApplicableRows); ...
    comparison.DeltaReferenceMinusSurveillance(nonApplicableRows) ...
    ];

end

function values = localPairedDifferenceMedians(session, fieldNames)

channelMetrics = session.ChannelMetricTable;
referenceRows = channelMetrics(channelMetrics.Role == "reference", :);
surveillanceRows = channelMetrics( ...
    channelMetrics.Role == "surveillance", :);
values = zeros(numel(fieldNames), 1);

for metricIndex = 1:numel(fieldNames)
    fieldName = char(fieldNames(metricIndex));
    pairedDifferences = referenceRows.(fieldName) - ...
        surveillanceRows.(fieldName);
    values(metricIndex) = median(pairedDifferences);
end

end

function populated = localEvidenceFieldsPopulated(evidence, variableNames)

populated = true(height(evidence), 1);

for variableIndex = 1:numel(variableNames)
    values = strtrim(string(evidence.(variableNames(variableIndex))));
    populated = populated & strlength(values) > 0;
end

end
