classdef helperAnalyzeG6ProductDiscriminationTest < ...
        matlab.unittest.TestCase
    %HELPERANALYZEG6PRODUCTDISCRIMINATIONTEST Focused G6-D tests.

    properties (SetAccess = private)
        RepoRoot
    end

    methods (TestClassSetup)
        function addRepositoryToPath(testCase)
            testFile = string(mfilename("fullpath"));
            testCase.RepoRoot = fileparts(fileparts(testFile));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                testCase.RepoRoot));
        end
    end

    methods (Test)
        function testCutBoundariesAndCount(testCase)
            [maps, geometry] = localBuildMapTriplet("common", "bg_a");

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));

            testCase.verifyEqual(result.MapTable.CutCount, ...
                12832 .* ones(3, 1), AbsTol=0.0);
            testCase.verifyEqual(result.MapTable.CutDelayMinimum_s, ...
                repmat(geometry.DelayCut(1), 3, 1), ...
                AbsTol=1.0e-15);
            testCase.verifyEqual(result.MapTable.CutDelayMaximum_s, ...
                repmat(geometry.DelayCut(end), 3, 1), ...
                AbsTol=1.0e-15);
            testCase.verifyEqual(result.MapTable.CutDopplerMinimum_Hz, ...
                -750.0 .* ones(3, 1), AbsTol=0.0);
            testCase.verifyEqual(result.MapTable.CutDopplerMaximum_Hz, ...
                750.0 .* ones(3, 1), AbsTol=0.0);
            testCase.verifyTrue(result.Integrity.AxisValid);
        end

        function testThresholdAndDetectionCountMonotonicity(testCase)
            maps = localBuildMonotonicMapTriplet();

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));
            rows = result.OperatingPointTable( ...
                result.OperatingPointTable.CandidateName == "none", :);

            testCase.verifyGreaterThanOrEqual( ...
                diff(rows.ThresholdMedian), zeros(8, 1));
            testCase.verifyLessThanOrEqual( ...
                diff(rows.DetectionCount), zeros(8, 1));
            testCase.verifyTrue(any(diff(rows.DetectionCount) < 0.0));
            testCase.verifyTrue(all( ...
                result.MapTable.ThresholdMonotonic));
            testCase.verifyTrue(all( ...
                result.MapTable.DetectionCountMonotonic));
        end

        function testNmsSuppressionAndPlateauTie(testCase)
            maps = localBuildNmsMapTriplet();

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));
            detections = result.DetectionTable( ...
                result.DetectionTable.CandidateName == "none" & ...
                result.DetectionTable.PfaIndex == 1, ...
                {'RowIndex', 'ColumnIndex'});
            detections = sortrows(detections, ...
                {'RowIndex', 'ColumnIndex'});
            expected = table([65.0; 115.0], [15.0; 20.0], ...
                VariableNames={'RowIndex', 'ColumnIndex'});

            testCase.verifyEqual(detections, expected);
        end

        function testOneToOneMultiTargetAssociation(testCase)
            [maps, geometry] = localBuildMapTriplet( ...
                "two_targets", "bg_a");
            truth = localBuildTruthTable( ...
                maps, geometry, "injected", 2);

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, truth, struct(CampaignId="fixture"));
            opportunities = result.TruthOpportunityTable( ...
                result.TruthOpportunityTable.CandidateName == "none" & ...
                result.TruthOpportunityTable.PfaIndex == 1, :);

            testCase.verifyEqual(height(opportunities), 2);
            testCase.verifyTrue(all(opportunities.Matched));
            testCase.verifyEqual(numel(unique( ...
                opportunities.DetectionId)), 2);
            testCase.verifyLessThanOrEqual( ...
                opportunities.NormalizedDelayError, ones(2, 1));
            testCase.verifyLessThanOrEqual( ...
                opportunities.NormalizedDopplerError, ones(2, 1));
        end

        function testMatchedControlsAreNuisanceAlarms(testCase)
            [maps, geometry] = localBuildMapTriplet( ...
                "common", "bg_a", "control");
            truth = localBuildTruthTable( ...
                maps, geometry, "matched_control", 1);

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, truth, struct(CampaignId="fixture"));
            detections = result.DetectionTable( ...
                result.DetectionTable.PfaIndex == 1, :);
            operatingRows = result.OperatingPointTable( ...
                result.OperatingPointTable.PfaIndex == 1, :);

            testCase.verifyEmpty(result.TruthOpportunityTable);
            testCase.verifyEqual(unique( ...
                detections.AssociationRole), ...
                "nuisance_control_alarm");
            testCase.verifyFalse(any( ...
                detections.FalseAlarmClaimed));
            testCase.verifyEqual( ...
                operatingRows.ControlAlarmCount, ones(3, 1));
            testCase.verifyEqual( ...
                operatingRows.TargetHitCount, zeros(3, 1));
        end

        function testNegativeMapIsBlocked(testCase)
            maps = localBuildMalformedMapTriplet("negative");

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "blocked");
            testCase.verifyFalse(result.Integrity.StructuralValid);
            testCase.verifyTrue(contains( ...
                result.IntegrityIssues(1), "InvalidMap"));
        end

        function testAxisMismatchIsBlocked(testCase)
            maps = localBuildMalformedMapTriplet("axis");

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "blocked");
            testCase.verifyFalse(result.Integrity.StructuralValid);
            testCase.verifyTrue(contains( ...
                result.IntegrityIssues(1), "MapAxisMismatch"));
        end

        function testDetectionGenerationIsTruthBlind(testCase)
            [maps, geometry] = localBuildMapTriplet("common", "bg_a");
            matchingTruth = localBuildTruthTable( ...
                maps, geometry, "injected", 1);
            displacedTruth = matchingTruth;
            displacedTruth.ExpectedDelay_s(:) = -1.15e-3;
            displacedTruth.ExpectedDoppler_Hz(:) = 700.0;

            matchingResult = helperAnalyzeG6ProductDiscrimination( ...
                maps, matchingTruth, struct(CampaignId="fixture"));
            displacedResult = helperAnalyzeG6ProductDiscrimination( ...
                maps, displacedTruth, struct(CampaignId="fixture"));
            generationVariables = { ...
                'DetectionId', 'MapId', 'PfaIndex', 'Pfa', ...
                'RowIndex', 'ColumnIndex', 'Delay_s', 'Doppler_Hz', ...
                'PowerLinear', 'NoiseEstimate', 'Threshold', ...
                'DetectionGeneratedTruthBlind'};

            testCase.verifyEqual( ...
                matchingResult.DetectionTable(:, generationVariables), ...
                displacedResult.DetectionTable(:, generationVariables));
        end

        function testInsufficientRecommendation(testCase)
            maps = localBuildMapTriplet("common", "bg_a");

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, table(), struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "insufficient");
            testCase.verifyTrue(result.Integrity.AllPassed);
        end

        function testConservativeRecommendation(testCase)
            [maps, geometry] = localBuildMapTriplet( ...
                "conservative", "bg_a");
            truth = localBuildTruthTable( ...
                maps, geometry, "injected", 1);

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, truth, struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "conservative");
        end

        function testAggressiveRecommendation(testCase)
            [maps, geometry] = localBuildMapTriplet( ...
                "aggressive", "bg_a");
            truth = localBuildTruthTable( ...
                maps, geometry, "injected", 1);

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, truth, struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "aggressive");
        end

        function testNoneRecommendationForExactTie(testCase)
            [maps, geometry] = localBuildMapTriplet("common", "bg_a");
            truth = localBuildTruthTable( ...
                maps, geometry, "injected", 1);

            result = helperAnalyzeG6ProductDiscrimination( ...
                maps, truth, struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "none");
        end

        function testRetuneRecommendationForBackgroundCrossover(testCase)
            [mapsA, geometry] = localBuildMapTriplet( ...
                "conservative", "bg_a");
            mapsB = localBuildMapTriplet("aggressive", "bg_b");
            truthA = localBuildTruthTable( ...
                mapsA, geometry, "injected", 1);
            truthB = localBuildTruthTable( ...
                mapsB, geometry, "injected", 1);

            result = helperAnalyzeG6ProductDiscrimination( ...
                [mapsA; mapsB], [truthA; truthB], ...
                struct(CampaignId="fixture"));

            testCase.verifyEqual(result.Recommendation, "retune");
        end

        function testOneOutputG5BehaviorIsUnchanged(testCase)
            [sessionData, metadata, g3, g4, options] = ...
                localBuildValidG5Fixture();

            oneOutput = helperAnalyzeG5Mitigation( ...
                sessionData, metadata, g3, g4, options);
            [twoOutput, fullMaps] = helperAnalyzeG5Mitigation( ...
                sessionData, metadata, g3, g4, options);

            testCase.verifyEqual(oneOutput, twoOutput);
            testCase.verifyEqual(numel(fullMaps), 9);
            testCase.verifyTrue(all(arrayfun( ...
                @(item) ~isempty(item.MapLinear), fullMaps)));
            testCase.verifyEqual(unique(string( ...
                {fullMaps.AxisOrientation})).', ...
                "rows_doppler_columns_delay");
        end
    end
end

function [maps, geometry] = localBuildMapTriplet( ...
    mode, backgroundId, caseId)

if nargin < 3
    caseId = "injected_case";
end

[delayAxis_s, dopplerAxis_Hz, geometry] = localBuildAxes();
baseMap = ones(numel(dopplerAxis_Hz), ...
    numel(delayAxis_s), "single");
targetLocations = localTargetLocations();
candidateNames = [ ...
    "none"; "conservative_lms"; "aggressive_lms"];
maps = repmat(struct( ...
    "CampaignId", "fixture", ...
    "BackgroundId", string(backgroundId), ...
    "CaseId", string(caseId), ...
    "CandidateName", "", ...
    "WindowLabel", "center", ...
    "AxisOrientation", "rows_doppler_columns_delay", ...
    "MapLinear", baseMap, ...
    "DelayAxis_s", delayAxis_s, ...
    "DopplerAxis_Hz", dopplerAxis_Hz), 3, 1);

for candidateIndex = 1:numel(candidateNames)
    maps(candidateIndex).CandidateName = ...
        candidateNames(candidateIndex);
    includeFirstTarget = localCandidateHasTarget( ...
        mode, candidateNames(candidateIndex));

    if includeFirstTarget
        candidateMap = maps(candidateIndex).MapLinear;
        candidateMap(targetLocations(1, 1), ...
            targetLocations(1, 2)) = 100.0;
        maps(candidateIndex).MapLinear = candidateMap;
    end

    if mode == "two_targets"
        candidateMap = maps(candidateIndex).MapLinear;
        candidateMap(targetLocations(2, 1), ...
            targetLocations(2, 2)) = 90.0;
        maps(candidateIndex).MapLinear = candidateMap;
    end
end

geometry.TargetLocations = targetLocations;

end

function hasTarget = localCandidateHasTarget(mode, candidateName)

hasTarget = mode == "common" || mode == "two_targets";

if mode == "conservative"
    hasTarget = candidateName == "conservative_lms";
elseif mode == "aggressive"
    hasTarget = candidateName == "aggressive_lms";
elseif mode == "none"
    hasTarget = candidateName == "none";
end

end

function maps = localBuildMonotonicMapTriplet()

[maps, geometry] = localBuildMapTriplet("none", "bg_a");
peakPowers = [5.0; 7.0; 10.0; 20.0];
cutLocations = [40, 8; 110, 12; 180, 18; 250, 24];

for candidateIndex = 1:numel(maps)
    candidateMap = ones(size(maps(candidateIndex).MapLinear), ...
        "single");

    for peakIndex = 1:numel(peakPowers)
        rowIndex = geometry.CutRows(cutLocations(peakIndex, 1));
        columnIndex = geometry.CutColumns( ...
            cutLocations(peakIndex, 2));
        candidateMap(rowIndex, columnIndex) = ...
            peakPowers(peakIndex);
    end

    maps(candidateIndex).MapLinear = candidateMap;
end

end

function maps = localBuildNmsMapTriplet()

[maps, geometry] = localBuildMapTriplet("none", "bg_a");
cutLocations = [50, 10; 52, 10; 100, 15; 101, 15; 100, 16];
peakPowers = [100.0; 30.0; 80.0; 80.0; 80.0];

for candidateIndex = 1:numel(maps)
    candidateMap = ones(size(maps(candidateIndex).MapLinear), ...
        "single");

    for peakIndex = 1:numel(peakPowers)
        rowIndex = geometry.CutRows(cutLocations(peakIndex, 1));
        columnIndex = geometry.CutColumns( ...
            cutLocations(peakIndex, 2));
        candidateMap(rowIndex, columnIndex) = ...
            peakPowers(peakIndex);
    end

    maps(candidateIndex).MapLinear = candidateMap;
end

end

function maps = localBuildMalformedMapTriplet(mode)

maps = localBuildMapTriplet("common", "bg_a");

if mode == "negative"
    maps(1).MapLinear(1, 1) = -1.0;
else
    maps(1).DelayAxis_s = maps(1).DelayAxis_s(1:end - 1);
end

end

function truth = localBuildTruthTable( ...
    maps, geometry, evidenceRole, targetCount)

rowCount = numel(maps) .* targetCount;
backgroundId = strings(rowCount, 1);
caseId = strings(rowCount, 1);
candidateName = strings(rowCount, 1);
windowLabel = repmat("center", rowCount, 1);
role = repmat(string(evidenceRole), rowCount, 1);
targetId = strings(rowCount, 1);
expectedDelay_s = zeros(rowCount, 1);
expectedDoppler_Hz = zeros(rowCount, 1);
searchDelayHalfExtent_s = repmat( ...
    1.1 .* geometry.DelaySpacing_s, rowCount, 1);
searchDopplerHalfExtent_Hz = repmat( ...
    1.1 .* geometry.DopplerSpacing_Hz, rowCount, 1);
sourceCaseId = strings(rowCount, 1);
callsign = strings(rowCount, 1);
geometryClass = repmat("fixture", rowCount, 1);
rowIndex = 0;

for mapIndex = 1:numel(maps)
    for targetIndex = 1:targetCount
        rowIndex = rowIndex + 1;
        location = geometry.TargetLocations(targetIndex, :);
        backgroundId(rowIndex) = maps(mapIndex).BackgroundId;
        caseId(rowIndex) = maps(mapIndex).CaseId;
        candidateName(rowIndex) = maps(mapIndex).CandidateName;
        targetId(rowIndex) = "target_" + targetIndex;
        expectedDelay_s(rowIndex) = ...
            maps(mapIndex).DelayAxis_s(location(2));
        expectedDoppler_Hz(rowIndex) = ...
            maps(mapIndex).DopplerAxis_Hz(location(1));
        sourceCaseId(rowIndex) = "source_" + targetIndex;
        callsign(rowIndex) = "CALL" + targetIndex;
    end
end

truth = table(backgroundId, caseId, candidateName, ...
    windowLabel, role, targetId, expectedDelay_s, ...
    expectedDoppler_Hz, searchDelayHalfExtent_s, ...
    searchDopplerHalfExtent_Hz, sourceCaseId, callsign, ...
    geometryClass, VariableNames={ ...
    'BackgroundId', 'CaseId', 'CandidateName', 'WindowLabel', ...
    'EvidenceRole', 'TargetId', 'ExpectedDelay_s', ...
    'ExpectedDoppler_Hz', 'SearchDelayHalfExtent_s', ...
    'SearchDopplerHalfExtent_Hz', 'SourceCaseId', 'Callsign', ...
    'GeometryClass'});

end

function [delayAxis_s, dopplerAxis_Hz, geometry] = localBuildAxes()

delayCut = linspace(-1.20e-3, -0.15e-3, 32);
delaySpacing_s = delayCut(2) - delayCut(1);
delayAxis_s = [ ...
    delayCut(1) + (-5:-1) .* delaySpacing_s, ...
    delayCut, ...
    delayCut(end) + (1:5) .* delaySpacing_s];
dopplerCut = linspace(-750.0, 750.0, 401).';
dopplerSpacing_Hz = dopplerCut(2) - dopplerCut(1);
dopplerAxis_Hz = [ ...
    dopplerCut(1) + (-15:-1).' .* dopplerSpacing_Hz; ...
    dopplerCut; ...
    dopplerCut(end) + (1:15).' .* dopplerSpacing_Hz];
geometry = struct();
geometry.DelayCut = delayCut;
geometry.DopplerCut = dopplerCut;
geometry.DelaySpacing_s = delaySpacing_s;
geometry.DopplerSpacing_Hz = dopplerSpacing_Hz;
geometry.CutRows = (16:416).';
geometry.CutColumns = 6:37;
geometry.TargetLocations = localTargetLocations();

end

function locations = localTargetLocations()

locations = [ ...
    15 + 120, 5 + 12; ...
    15 + 280, 5 + 25];

end

function [sessionData, collectionMetadataInfo, g3SyncResults, ...
    g4Analysis, g5Options] = localBuildValidG5Fixture()

randomState = rng;
cleanup = onCleanup(@() rng(randomState));
rng(41, "twister");
sampleRateHz = 4000.0;
sampleCount = 4000.0;
time_s = (0:sampleCount - 1).' ./ sampleRateHz;
reference = complex(randn(sampleCount, 1), ...
    randn(sampleCount, 1));
delayedReference = [zeros(20, 1); reference(1:end - 20)];
target = delayedReference .* exp( ...
    1j .* 2.0 .* pi .* 80.0 .* time_s);
surveillance = 0.8 .* reference + 0.2 .* target + ...
    0.02 .* complex(randn(sampleCount, 1), ...
    randn(sampleCount, 1));
radarScans = struct( ...
    "Samples", [surveillance, reference], ...
    "RelativePath", "synthetic/rep_1.bb", ...
    "Repetition", 1.0);
radarTable = table( ...
    1.0, "synthetic/rep_1.bb", sampleRateHz, sampleCount, ...
    2.0, "RF0:RX2", "RF1:RX2", ...
    VariableNames={'Repetition', 'RelativePath', ...
    'SampleRate_Hz', 'NumSamples', 'NumChannels', ...
    'Antenna1', 'Antenna2'});
sessionData = struct( ...
    "DatasetId", "synthetic_g6_regression", ...
    "DatasetRoot", string(pwd), ...
    "RadarTable", radarTable, ...
    "RadarScans", radarScans, ...
    "CpiContract", struct("CrossFileAllowed", false));
collectionMetadataInfo = struct( ...
    "MetadataPresent", true, ...
    "SessionIdMatches", true, ...
    "ReferenceChannel", struct("ChannelLabel", "RF1:RX2"), ...
    "SurveillanceChannel", struct("ChannelLabel", "RF0:RX2"));
g3SyncResults = struct("OverallLabel", "ready");
mapDecimationFactor = 10.0;
mapSampleRateHz = sampleRateHz ./ mapDecimationFactor;
cpiDuration_s = 0.1;
cpiSamples = round(cpiDuration_s .* mapSampleRateHz);
windowLabels = ["early"; "center"; "late"];
mapSummaryTable = table( ...
    ones(3, 1), repmat("synthetic/rep_1.bb", 3, 1), ...
    repmat("short", 3, 1), windowLabels, ...
    [1.0; 1001.0; 2001.0], (1:3).', ...
    repmat(cpiDuration_s, 3, 1), ...
    repmat(cpiSamples, 3, 1), ...
    VariableNames={'Repetition', 'RelativePath', 'CpiLabel', ...
    'WindowLabel', 'WindowStartSample', 'WindowIndex', ...
    'CpiDuration_s', 'CpiSamples'});
baselineProductDefinition = struct( ...
    "Method", "ambgfun", ...
    "MapRateMode", "reduced_rate_g5_candidate_product", ...
    "MapSampleRateHz", mapSampleRateHz, ...
    "MapDecimationFactor", mapDecimationFactor, ...
    "OriginSearchDelayRadius_samples", 3.0, ...
    "OriginSearchDopplerRadius_Hz", 25.0, ...
    "ExclusionDelayRadius_samples", 6.0, ...
    "ExclusionDopplerRadius_Hz", 35.0, ...
    "ZeroDopplerRidgeExclusion_Hz", 25.0, ...
    "AppliedLag_samples", 0.0, ...
    "AppliedResidualFrequency_Hz", 0.0, ...
    "AppliedCorrectionSource", "synthetic_fixture");
interpretation = struct( ...
    "OverallLabel", "blocked", ...
    "OverallRationale", "Synthetic regression fixture.", ...
    "SceneObservabilityLabel", "blocked", ...
    "FullRateAuditAgreementLabel", "agreement", ...
    "ReferenceLabel", "RF1:RX2", ...
    "SurveillanceLabel", "RF0:RX2", ...
    "CaveatCodes", strings(0, 1));
g4Analysis = struct( ...
    "DatasetId", sessionData.DatasetId, ...
    "StageId", "G4_Synthetic_Regression", ...
    "Options", struct( ...
    "MapDecimationFactor", mapDecimationFactor, ...
    "MapSampleRateHz", mapSampleRateHz, ...
    "ReviewMapRows", 32.0, ...
    "ReviewMapCols", 32.0, ...
    "FigureFloor_dB", -60.0), ...
    "BaselineProductDefinition", baselineProductDefinition, ...
    "MapSummaryTable", mapSummaryTable, ...
    "Interpretation", interpretation, ...
    "RecommendedBaselineCpiLabel", "short");
g5Options = struct( ...
    "ReviewCpiLabels", "short", ...
    "ReviewWindowLabels", windowLabels, ...
    "ReviewRepetitions", 1.0, ...
    "MaxReviewRows", 3.0, ...
    "MapDecimationFactor", mapDecimationFactor, ...
    "MapSampleRateHz", mapSampleRateHz, ...
    "ReviewMapRows", 32.0, ...
    "ReviewMapCols", 32.0, ...
    "DataProfile", "synthetic", ...
    "ReferenceChannelIndex", 2.0, ...
    "SurveillanceChannelIndex", 1.0, ...
    "RunPostHocSyntheticTargetEvidence", false, ...
    "ConservativeLmsLength", 8.0, ...
    "ConservativeLmsStepSize", 0.01, ...
    "AggressiveLmsLength", 16.0, ...
    "AggressiveLmsStepSize", 0.05);

end
