classdef runRealBackgroundSyntheticPipelineTest < matlab.unittest.TestCase
    %RUNREALBACKGROUNDSYNTHETICPIPELINETEST End-to-end paired demo test.

    properties (SetAccess = private)
        Results
        DetectorReplaySession
        BaselineReplay
    end

    methods (TestClassSetup)
        function runPipelineOnce(testCase)
            testFile = string(mfilename("fullpath"));
            repoRoot = fileparts(fileparts(testFile));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(repoRoot));
            temporaryRoot = string(tempname);
            mkdir(temporaryRoot);
            testCase.addTeardown(@() rmdir(temporaryRoot, "s"));
            generatedRoot = fullfile( ...
                temporaryRoot, "generated_iq");
            resultRoot = fullfile(temporaryRoot, "results");

            [testCase.Results, testCase.DetectorReplaySession] = ...
                runRealBackgroundSyntheticPipeline( ...
                GeneratedIqRoot=generatedRoot, ...
                ResultRoot=resultRoot, ...
                SuiteId="pipeline_integration_test", ...
                ShowFigures=false, ...
                SaveResult=true);
            testCase.BaselineReplay = helperReplayG6DDetector( ...
                testCase.DetectorReplaySession, ...
                helperBuildG6DDetectorConfiguration());
        end
    end

    methods (Test)
        function testPairedInputIntegrity(testCase)
            verification = testCase.Results.Verification;

            testCase.verifyTrue( ...
                verification.ReferenceChannelExactlyUnchanged);
            testCase.verifyTrue( ...
                verification.ControlSurveillanceExactlyUnchanged);
            testCase.verifyTrue( ...
                verification.InjectedSurveillanceDeltaFiniteNonzero);
        end

        function testGeometryAndProcessingIntegrity(testCase)
            verification = testCase.Results.Verification;

            testCase.verifyTrue(verification.TruthWithinPhysicsMap);
            testCase.verifyTrue(verification.TruthWithinDetectorSupport);
            testCase.verifyTrue( ...
                verification.TruthWithinMapAndDetectorSupport);
            testCase.verifyEqual( ...
                verification.TruthEvaluationStatus, "eligible_and_detected");
            testCase.verifyTrue( ...
                verification.MapPlacementAgreesWithGeneratorTruth);
            testCase.verifyTrue( ...
                verification.G1ThroughG5ExecutedForBothCases);
            testCase.verifyTrue( ...
                verification.G3CorrectionReusedExactly);
        end

        function testCompactG3DisplayTraces(testCase)
            visuals = testCase.Results.G3.Visuals;

            testCase.verifyTrue(visuals.ControlDerived);
            testCase.verifyTrue(visuals.ReusedByInjected);
            testCase.verifyEqual(visuals.SourceCpiLabel, "short");
            testCase.verifyLessThanOrEqual( ...
                numel(visuals.CorrelationMagnitude), 8193);
            testCase.verifyLessThanOrEqual( ...
                numel(visuals.CoherenceMagnitude), 4096);
            testCase.verifyTrue(all(isfinite( ...
                visuals.CorrelationMagnitude), "all"));
            testCase.verifyTrue(all(isfinite( ...
                visuals.CrossPhase_rad), "all"));
            testCase.verifyTrue(all(isfinite( ...
                visuals.CoherenceMagnitude), "all"));
        end

        function testCompactMitigationProfiles(testCase)
            candidateTable = ...
                testCase.Results.G4G5.Injected.MitigationCandidateTable;

            testCase.verifyEqual(sort(candidateTable.CandidateName), ...
                ["aggressive_lms"; "conservative_lms"; "none"]);
            testCase.verifyTrue(any( ...
                candidateTable.UsesDspLMSFilter));
        end

        function testDetectorContract(testCase)
            verification = testCase.Results.Verification;

            testCase.verifyTrue(verification.G6DIntegrityPassed);
            testCase.verifyTrue(verification.G6DCellGeometryExact);
            testCase.verifyEqual( ...
                testCase.Results.G6D.MapTable.CutCount, ...
                12832 .* ones(6, 1), AbsTol=0.0);
            testCase.verifyTrue( ...
                verification.DetectionGeneratedBeforeTruthAssociation);
        end

        function testBaselineReplayReproducesDetectorResult(testCase)
            baseline = testCase.Results.G6D;
            replay = testCase.BaselineReplay;

            testCase.verifyEqual( ...
                baseline.Configuration, replay.Configuration);
            testCase.verifyEqual(baseline.MapTable, replay.MapTable);
            testCase.verifyEqual( ...
                baseline.OperatingPointTable, replay.OperatingPointTable);
            testCase.verifyEqual( ...
                baseline.TruthOpportunityTable, ...
                replay.TruthOpportunityTable);
            testCase.verifyEqual( ...
                baseline.TruthCutDiagnosticTable, ...
                replay.TruthCutDiagnosticTable);
            testCase.verifyEqual( ...
                baseline.DetectionTable, replay.DetectionTable);
        end

        function testReplaySessionIsWorkspaceOnlyAndIqFree(testCase)
            session = testCase.DetectorReplaySession;

            testCase.verifyFalse(session.ContainsRawIq);
            testCase.verifyFalse(isfield(testCase.Results, ...
                "DetectorReplaySession"));
            testCase.verifyTrue(all(arrayfun( ...
                @(item) isfield(item, "MapLinear"), ...
                session.MapProducts)));
            testCase.verifyFalse(any(arrayfun( ...
                @(item) isfield(item, "Samples") || ...
                isfield(item, "RadarScans"), session.MapProducts)));
        end

        function testGeometryCenteredDisplayViews(testCase)
            views = testCase.Results.TargetCenteredViews;
            injectedView = views( ...
                string({views.CaseId}) == "field_plus_geo_target" & ...
                string({views.CandidateName}) == "conservative_lms");

            testCase.verifyTrue(injectedView.TargetWithinView);
            testCase.verifySize( ...
                injectedView.TargetRegionPower_dB, [401 32]);
            testCase.verifyGreaterThanOrEqual( ...
                injectedView.ExpectedDelay_s, ...
                min(injectedView.DelayAxis_s));
            testCase.verifyLessThanOrEqual( ...
                injectedView.ExpectedDelay_s, ...
                max(injectedView.DelayAxis_s));
            testCase.verifyGreaterThanOrEqual( ...
                injectedView.ExpectedDoppler_Hz, ...
                min(injectedView.DopplerAxis_Hz));
            testCase.verifyLessThanOrEqual( ...
                injectedView.ExpectedDoppler_Hz, ...
                max(injectedView.DopplerAxis_Hz));
        end

        function testFixedDetectionCriterion(testCase)
            verification = testCase.Results.Verification;

            testCase.verifyEqual( ...
                verification.HighlightPfa, 1e-3, AbsTol=0.0);
            testCase.verifyTrue( ...
                verification.ConservativeInjectedTargetMatch);
            testCase.verifyFalse( ...
                verification.ConservativeControlNuisanceMatch);
            testCase.verifyTrue( ...
                verification.FinalDetectionCriterionEvaluated);
            testCase.verifyTrue( ...
                verification.FinalDetectionCriterionPassed);
            testCase.verifyTrue(verification.NoRetuningPerformed);
        end

        function testCompactSavedResult(testCase)
            audit = testCase.Results.CompactResultAudit;
            runnerPath = fullfile( ...
                testCase.Results.Configuration.RepoRoot, ...
                "runRealBackgroundSyntheticPipeline.m");

            testCase.verifyTrue(audit.Compact);
            testCase.verifyFalse(audit.RawIqPresent);
            testCase.verifyFalse(audit.FullMapCollectionPresent);
            testCase.verifyLessThanOrEqual( ...
                audit.LargestNumericElementCount, 401 .* 32);
            testCase.verifyTrue(isfile(testCase.Results.ResultPath));
            testCase.verifyEqual( ...
                testCase.Results.Provenance.RunnerSourceSha256, ...
                helperG4RSha256(runnerPath));
        end

        function testClaimBoundary(testCase)
            boundary = testCase.Results.ClaimBoundary;

            testCase.verifyTrue(boundary.DiagnosticIntegrationOnly);
            testCase.verifyFalse(boundary.FieldDetectionClaimed);
            testCase.verifyFalse(boundary.TrackingClaimed);
            testCase.verifyFalse(boundary.FormalG4RStateChanged);
            testCase.verifyFalse(boundary.FormalG6OrG8Enabled);
            testCase.verifyEqual( ...
                boundary.TruthUse, "post_hoc_association_only");
        end
    end
end
