function evidence = extractDeepDive2CompactGeometryEvidence(projectRoot, options)
%EXTRACTDEEPDIVE2COMPACTGEOMETRYEVIDENCE Write compact sequel geometry evidence.
%
%   EVIDENCE = EXTRACTDEEPDIVE2COMPACTGEOMETRYEVIDENCE(PROJECTROOT) reads
%   only the Trajectory structures in the two hash-verified saved field-
%   background result bundles. It verifies their common Tx/Rx geometry,
%   converts Tx and the initial target waypoints to receiver-local ENU with
%   a WGS-84 ellipsoid, and writes scalar JSON for Deep Dive 2.
%
%   The extractor never loads IQ, retained maps, detector replays, or
%   processing helpers. It neither changes detector settings nor runs the
%   passive-bistatic pipeline.

arguments
    projectRoot (1, 1) string {mustBeNonzeroLengthText} = ...
        string(fileparts(fileparts(fileparts(mfilename("fullpath")))))
    options.OutputDirectory (1, 1) string = fullfile( ...
        fileparts(mfilename("fullpath")), "deep_dive_2_data_v1")
    options.WriteJson (1, 1) logical = true
end

if ~isfolder(projectRoot)
    error("extractDeepDive2CompactGeometryEvidence:ProjectRoot", ...
        "Project root does not exist: %s.", projectRoot);
end

sourceSpecs = localSourceSpecs(projectRoot);
trajectories = repmat(localEmptyTrajectory(), numel(sourceSpecs), 1);
sourceRecords = repmat(localEmptySourceRecord(), numel(sourceSpecs), 1);

for sourceIndex = 1:numel(sourceSpecs)
    spec = sourceSpecs(sourceIndex);
    if ~isfile(spec.AbsolutePath)
        error("extractDeepDive2CompactGeometryEvidence:MissingSource", ...
            "Required saved result is missing: %s.", spec.AbsolutePath);
    end

    actualHash = localSha256File(spec.AbsolutePath);
    if actualHash ~= spec.ExpectedSha256
        error("extractDeepDive2CompactGeometryEvidence:SourceHash", ...
            "SHA-256 mismatch for %s.", spec.RelativePath);
    end

    loaded = load(spec.AbsolutePath, "results");
    if ~isfield(loaded, "results") || ...
            ~isfield(loaded.results, "Trajectory")
        error("extractDeepDive2CompactGeometryEvidence:Trajectory", ...
            "Saved result %s does not contain results.Trajectory.", ...
            spec.RelativePath);
    end

    trajectories(sourceIndex) = localValidateTrajectory( ...
        loaded.results.Trajectory, spec.RelativePath);
    sourceRecords(sourceIndex) = struct( ...
        Id=spec.Id, ...
        RelativePath=spec.RelativePath, ...
        Sha256=actualHash, ...
        Role=spec.Role);
end

if ~localEqualLla(trajectories(1).TxLla_deg_m, ...
        trajectories(2).TxLla_deg_m) || ...
        ~localEqualLla(trajectories(1).RxLla_deg_m, ...
        trajectories(2).RxLla_deg_m)
    error("extractDeepDive2CompactGeometryEvidence:SharedGeometry", ...
        "The 45 km and 15 km sources do not share their Tx/Rx geometry.");
end

receiverLla = trajectories(1).RxLla_deg_m;
transmitterEnu = localReceiverLocalEnu( ...
    trajectories(1).TxLla_deg_m, receiverLla);
scenarios = repmat(localEmptyScenarioRecord(), numel(trajectories), 1);
for scenarioIndex = 1:numel(trajectories)
    scenarios(scenarioIndex) = localScenarioRecord( ...
        sourceSpecs(scenarioIndex), trajectories(scenarioIndex), receiverLla);
end

detectorSupport = struct( ...
    Delay_us=[-1200.0, -150.0], ...
    Doppler_Hz=[-750.0, 750.0], ...
    Description="Frozen diagnostic detector support; unchanged by this extractor.");

evidence = struct( ...
    SchemaVersion="deep_dive_2_compact_geometry_v1", ...
    Purpose="Compact scalar geometry evidence for a code-drawn instructional sequel.", ...
    ExtractionBoundary= ...
    "Read only results.Trajectory; no IQ, maps, replay, pipeline run, or detector modification.", ...
    Sources=sourceRecords, ...
    SharedTxRxGeometry=true, ...
    PlanView=struct( ...
    CoordinateFrame="receiver_local_ENU", ...
    Receiver=struct("East_km", 0.0, "North_km", 0.0), ...
    AltitudeOmitted=true, ...
    Limitation="Horizontal receiver-local East/North plan view; altitude is omitted."), ...
    Transmitter=localKilometerRecord(transmitterEnu), ...
    DetectorSupport=detectorSupport, ...
    DisplayConvention=struct( ...
    Delay="tau_display = -tau_excess", ...
    Doppler="f_display = -f_bistatic", ...
    Limitation= ...
    "This project's display convention, not a universal passive-bistatic or CAF sign rule."), ...
    Scenarios=scenarios, ...
    ClaimBoundary=struct( ...
    PipelineRecomputation=false, ...
    DetectorRetuning=false, ...
    DetectorSupportWidening=false, ...
    FieldAircraftDetectionClaim=false, ...
    ObjectDetectionEmitted=false, ...
    TrackingClaim=false));

if options.WriteJson
    if ~isfolder(options.OutputDirectory)
        mkdir(options.OutputDirectory);
    end
    outputPath = fullfile(options.OutputDirectory, "compact_geometry.json");
    fileIdentifier = fopen(outputPath, "w", "n", "UTF-8");
    if fileIdentifier < 0
        error("extractDeepDive2CompactGeometryEvidence:Output", ...
            "Cannot write %s.", outputPath);
    end
    cleanup = onCleanup(@() fclose(fileIdentifier));
    fprintf(fileIdentifier, "%s\n", jsonencode(evidence, PrettyPrint=true));
    clear cleanup
end
end

function specs = localSourceSpecs(projectRoot)

specs = [ ...
    struct( ...
    Id="S11", ...
    RelativePath="artifacts/20260622T102123/Field_Background_Synthetic_Demo/" + ...
    "field_background_demo_final_20260908/" + ...
    "fieldBackgroundSyntheticPipelineResults.mat", ...
    ExpectedSha256="d64ac4ef034f6278050b084e9ebbf73a386c91b6f997ff8afe04107ca1cd0dea", ...
    Role="45 km receiver-local north-offset scenario"), ...
    struct( ...
    Id="S12", ...
    RelativePath="artifacts/20260622T102123/Field_Background_Synthetic_Demo/" + ...
    "field_background_close_target_support_probe_20260914T190224119Z/" + ...
    "fieldBackgroundSyntheticPipelineResults.mat", ...
    ExpectedSha256="ed77b873a08381b5291f30765697b65b9690f1bbbd6eb2420429fc2b2a563419", ...
    Role="15 km receiver-local north-offset scenario") ...
    ];
for index = 1:numel(specs)
    specs(index).AbsolutePath = fullfile(projectRoot, specs(index).RelativePath);
end
end

function trajectory = localValidateTrajectory(value, sourcePath)

requiredFields = [ ...
    "WaypointsLla_deg_m", "TxLla_deg_m", "RxLla_deg_m", ...
    "TruthTime_s", "ExcessDelay_s", "BistaticDoppler_Hz"];
if ~all(isfield(value, requiredFields))
    error("extractDeepDive2CompactGeometryEvidence:TrajectoryFields", ...
        "Trajectory in %s does not contain the required compact fields.", ...
        sourcePath);
end

waypoints = double(value.WaypointsLla_deg_m);
txLla = double(value.TxLla_deg_m(:).');
rxLla = double(value.RxLla_deg_m(:).');
truthTime = double(value.TruthTime_s(:));
excessDelay = double(value.ExcessDelay_s(:));
bistaticDoppler = double(value.BistaticDoppler_Hz(:));
if ~isequal(size(waypoints), [3, 3]) || numel(txLla) ~= 3 || ...
        numel(rxLla) ~= 3 || isempty(truthTime) || ...
        numel(truthTime) ~= numel(excessDelay) || ...
        numel(truthTime) ~= numel(bistaticDoppler) || ...
        any(~isfinite([waypoints(:); txLla(:); rxLla(:); truthTime; ...
        excessDelay; bistaticDoppler]))
    error("extractDeepDive2CompactGeometryEvidence:TrajectoryValues", ...
        "Trajectory geometry or scalar coordinate arrays are invalid in %s.", ...
        sourcePath);
end

trajectory = struct( ...
    WaypointsLla_deg_m=waypoints, ...
    TxLla_deg_m=txLla, ...
    RxLla_deg_m=rxLla, ...
    TruthTime_s=truthTime, ...
    ExcessDelay_s=excessDelay, ...
    BistaticDoppler_Hz=bistaticDoppler);
end

function trajectory = localEmptyTrajectory

trajectory = struct( ...
    WaypointsLla_deg_m=zeros(3, 3), ...
    TxLla_deg_m=zeros(1, 3), ...
    RxLla_deg_m=zeros(1, 3), ...
    TruthTime_s=zeros(0, 1), ...
    ExcessDelay_s=zeros(0, 1), ...
    BistaticDoppler_Hz=zeros(0, 1));
end

function record = localEmptySourceRecord

record = struct( ...
    Id="", ...
    RelativePath="", ...
    Sha256="", ...
    Role="");
end

function record = localScenarioRecord(spec, trajectory, receiverLla)

initialEnu = localReceiverLocalEnu( ...
    trajectory.WaypointsLla_deg_m(1, :), receiverLla);
midpointIndex = ceil(numel(trajectory.TruthTime_s) ./ 2.0);
physicalExcessDelay_us = ...
    trajectory.ExcessDelay_s(midpointIndex) .* 1.0e6;
physicalBistaticDoppler_Hz = ...
    trajectory.BistaticDoppler_Hz(midpointIndex);
if ~isscalar(physicalExcessDelay_us) || ...
        any(~isfinite(physicalExcessDelay_us), "all") || ...
        any(physicalExcessDelay_us <= 0.0, "all")
    error("extractDeepDive2CompactGeometryEvidence:PhysicalDelay", ...
        "%s does not have positive physical excess delay.", spec.Id);
end

displayDelay_us = -physicalExcessDelay_us;
displayDoppler_Hz = -physicalBistaticDoppler_Hz;
detectorEligible = displayDelay_us >= -1200.0 && ...
    displayDelay_us <= -150.0 && ...
    displayDoppler_Hz >= -750.0 && displayDoppler_Hz <= 750.0;

record = struct( ...
    SourceId=spec.Id, ...
    Label=spec.Role, ...
    InitialWaypoint=localKilometerRecord(initialEnu), ...
    RepresentativeTruthTime_s=trajectory.TruthTime_s(midpointIndex), ...
    PhysicalExcessDelay_us=physicalExcessDelay_us, ...
    PhysicalBistaticDoppler_Hz=physicalBistaticDoppler_Hz, ...
    DisplayDelay_us=displayDelay_us, ...
    DisplayDoppler_Hz=displayDoppler_Hz, ...
    PhysicalDelayStatement="Physical excess delay is positive.", ...
    DisplayDelayStatement= ...
    "Negative displayed delay is intentional under this project's display convention.", ...
    DetectorEligible=detectorEligible);
end

function record = localEmptyScenarioRecord

record = struct( ...
    SourceId="", ...
    Label="", ...
    InitialWaypoint=struct("East_km", 0.0, "North_km", 0.0, "Up_km", 0.0), ...
    RepresentativeTruthTime_s=0.0, ...
    PhysicalExcessDelay_us=0.0, ...
    PhysicalBistaticDoppler_Hz=0.0, ...
    DisplayDelay_us=0.0, ...
    DisplayDoppler_Hz=0.0, ...
    PhysicalDelayStatement="", ...
    DisplayDelayStatement="", ...
    DetectorEligible=false);
end

function enu = localReceiverLocalEnu(lla_deg_m, receiverLla_deg_m)

ellipsoid = wgs84Ellipsoid("meter");
[east_m, north_m, up_m] = geodetic2enu( ...
    lla_deg_m(1), lla_deg_m(2), lla_deg_m(3), ...
    receiverLla_deg_m(1), receiverLla_deg_m(2), receiverLla_deg_m(3), ...
    ellipsoid);
enu = [double(east_m), double(north_m), double(up_m)];
end

function record = localKilometerRecord(enu_m)

record = struct( ...
    East_km=enu_m(1) ./ 1000.0, ...
    North_km=enu_m(2) ./ 1000.0, ...
    Up_km=enu_m(3) ./ 1000.0);
end

function isEqual = localEqualLla(leftLla, rightLla)

isEqual = isequal(size(leftLla), size(rightLla)) && ...
    all(abs(double(leftLla(:)) - double(rightLla(:))) <= 1.0e-9);
end

function digest = localSha256File(filePath)

if ~usejava("jvm")
    error("extractDeepDive2CompactGeometryEvidence:Java", ...
        "A MATLAB JVM is required to verify source SHA-256 hashes.");
end

messageDigest = java.security.MessageDigest.getInstance("SHA-256");
fileIdentifier = fopen(filePath, "rb");
if fileIdentifier < 0
    error("extractDeepDive2CompactGeometryEvidence:Read", ...
        "Cannot read %s.", filePath);
end
cleanup = onCleanup(@() fclose(fileIdentifier));
while true
    bytes = fread(fileIdentifier, 4 .* 1024 .* 1024, "*uint8");
    if isempty(bytes)
        break
    end
    messageDigest.update(typecast(uint8(bytes(:)), "int8"));
end
signedDigest = int8(messageDigest.digest());
digestBytes = typecast(signedDigest, "uint8");
digest = lower(string(reshape(dec2hex(digestBytes, 2).', 1, [])));
end
